SERMOES.sermao({
  id: 'bernardo-cantico-57',
  colecao: 'bernardo-cantico',
  ordem: 57,
  numero: 'LVII',
  titulo: 'Das visitas do Senhor, que devemos observar, e dos sinais pelos quais se podem perceber',
  fonte: 'De visitationibus Domini observandis',
  argumento: `A esposa, vigilante, acompanhou cada passo da vinda do esposo: ele vem, apressa-se, aproxima-se, está presente, olha e, por fim, fala. E o olhar acompanhado da palavra é sinal de amor; Pedro, olhado e não falado, chorou. Mas nós, que também somos a Igreja, por que não percebemos essas visitas? A culpa é do nosso descuido, e Bernardo, cujo ofício é falar, descreve com simplicidade os sinais que ele mesmo e outros experimentaram.

Uma exortação à justiça ou às virtudes anuncia que ele está para vir; a correção de um justo lhe abre caminho; a palavra ouvida com desejo mostra que ele se apressa; a palavra ardente que queima a consciência é o fogo que vai à sua frente; a conversão e o amor são ele mesmo, fogo que consome sem afligir; a luz súbita sobre as Escrituras é o seu olhar pelas frestas da parede. Então vem a voz: "levanta-te, apressa-te" — para ganhar almas —, e a alma oscila entre a contemplação e a pregação, sem saber qual das duas Deus quer a cada hora. Amiga pela pregação, pomba pela oração, formosa pela contemplação: Marta, Lázaro e Maria, que Bernardo reconhece no seu mosteiro, nos que administram, nos noviços e nos mais adiantados.

Tradução feita do texto latino de Migne (PL 183, 1050-1055).`,
  pontos: [
    {
      n: 1,
      texto: `Eis que o meu amado me fala (Ct 2,10). Vede os progressos da graça, e reparai nos degraus da condescendência divina. Considerai a devoção e a diligência da esposa: com que olho vigilante observa a vinda do esposo, e depois contempla com o maior cuidado tudo o que é dele. Ele vem, apressa-se, aproxima-se, está presente, olha, fala; e nenhum destes momentos escapa à atenção da esposa, nem ao seu conhecimento. Vem nos anjos, apressa-se nos patriarcas, aproxima-se nos profetas, está presente na carne, olha nos milagres, fala nos apóstolos. Ou assim: vem pelo afeto e pelo empenho de ter misericórdia; apressa-se pelo zelo de socorrer; aproxima-se humilhando-se a si mesmo; está presente aos que vivem agora; olha adiante para os que hão de vir; fala ensinando e persuadindo a respeito do reino de Deus. Assim é, pois, a vinda do esposo. Com ele vêm as bênçãos e as riquezas da salvação, e tudo o que é dele transborda de delícias, cheio de mistérios alegres e salutares. E a que ama vigia e observa. E feliz aquela que o Senhor achar vigilante. Não passará por ela nem a deixará para trás; mas parará e lhe falará, e lhe falará palavras de amor, pois falará como amado. Pois é assim que tens: Eis que o meu amado me fala. Com razão é chamado amado, porque vem falar palavras de amor, e não de repreensão.`
    },
    {
      n: 2,
      texto: `Pois ela não é daqueles que o Senhor repreende com razão por saberem distinguir o aspecto do céu, mas não conhecerem o tempo da sua vinda (cf. Mt 16,3). Pois esta, tão diligente, prudente e bem vigilante, viu-o vir de longe, reparou nele saltando na sua pressa, e observou com a maior vigilância que transpunha os soberbos, para se aproximar dela, humilde, pela humildade; e, por fim, quando já estava de pé e se escondia atrás da parede, nem assim deixou de o reconhecer presente, e até o sentiu olhando pelas janelas e pelas grades; e agora, em recompensa de tanta devoção e de tão religiosa solicitude, ouve-o falar. Pois, se ele tivesse olhado e não tivesse falado, aquele olhar podia ser suspeito de ser antes de indignação do que de amor. Enfim, olhou para Pedro e não lhe disse palavra; e talvez por isso ele chorou (Lc 22,61-62): porque, olhando-o, se calou. Mas esta, como depois do olhar mereceu também a palavra, não só não chora, mas até se gloria, clamando de alegria: Eis que o meu amado me fala. Vês que o olhar do Senhor, embora permaneça sempre o mesmo em si, nem sempre tem a mesma eficácia, mas se conforma aos méritos de cada um daqueles para quem olha: a uns infunde temor, a outros traz antes consolação e segurança. Enfim, olha para a terra e a faz tremer (cf. Sl 103,32), ao passo que olhou para Maria e lhe infundiu a graça. Olhou, diz, para a humildade da sua serva; pois eis que desde agora todas as gerações me chamarão feliz (Lc 1,48). Não são palavras de quem chora ou treme, mas de quem se alegra. Do mesmo modo olhou aqui para a esposa, e ela nem tremeu, nem chorou como Pedro, porque não tinha o gosto da terra, como ele; mas pôs alegria no seu coração, atestando com a palavra o afeto com que a olhara.`
    },
    {
      n: 3,
      texto: `Enfim, ouve como as palavras que diz não são de quem se indigna, mas de quem ama. Segue-se: Levanta-te, apressa-te, minha amiga, minha pomba, minha formosa. Feliz a consciência que merece ouvir isto de si! Quem pensas que há entre nós tão vigilante e tão atento ao tempo da sua visita, e que observe com tanto cuidado o esposo que chega, em cada um dos seus momentos, que, quando ele vier e bater, lhe abra logo (cf. Lc 12,36)? Pois estas coisas não se dizem da Igreja de tal modo que cada um de nós, que juntos somos a Igreja, não deva participar destas suas bênçãos. Pois todos nós, sem exceção e sem diferença, fomos chamados a isto: a possuir por herança as bênçãos (cf. 1Pd 3,9). Por isso alguém ousava dizer ao Senhor: Adquiri por herança para sempre os teus testemunhos, porque são a exultação do meu coração (Sl 118,111); por aquela herança, creio, pela qual confiava ser filho de seu Pai, que está nos céus. Ora, se filho, também herdeiro: herdeiro de Deus e coerdeiro de Cristo (Rm 8,17). E gloria-se de ter adquirido por esta herança uma grande coisa: os testemunhos do Senhor. Oxalá eu merecesse ter a meu respeito ao menos um testemunho do Senhor! Pois ele exulta não num só, mas em muitos testemunhos. Enfim, diz ainda: No caminho dos teus testemunhos me deleitei, como em todas as riquezas (Sl 118,14). E, na verdade, que são as riquezas da salvação, as delícias do coração, a segurança verdadeira e bem guardada da alma, senão os testemunhos do Senhor a nosso favor? Pois não é aprovado, diz, quem se recomenda a si mesmo, mas aquele a quem Deus recomenda (2Cor 10,18).`
    },
    {
      n: 4,
      texto: `Por que somos ainda até agora defraudados destas recomendações ou testemunhos divinos, e privados da herança paterna? Como se ele não nos tivesse gerado também a nós, por sua vontade, pela palavra da verdade (cf. Tg 1,18), assim não nos lembramos de ter sido recomendados por ele em nada deste modo, nem de ter obtido a nosso respeito testemunho algum dele. Onde está o que diz o Apóstolo, que o próprio Espírito de Deus dá testemunho ao nosso espírito de que somos filhos de Deus (Rm 8,16)? Como filhos, se não temos parte na herança? A nossa própria pobreza nos acusa, sem dúvida, de negligência e descuido. Pois, se algum de nós, segundo a palavra do Sábio, entregar o seu coração inteira e perfeitamente a vigiar desde a madrugada pelo Senhor que o fez, e orar na presença do Altíssimo (Eclo 39,6); e ao mesmo tempo se empenhar com todos os desejos, segundo o profeta Isaías, em preparar os caminhos do Senhor e endireitar as veredas do seu Deus (Is 40,3); e puder dizer com o Profeta: Os meus olhos estão sempre voltados para o Senhor (Sl 24,15), e: Eu tinha sempre o Senhor diante de mim (Sl 15,8) — não receberá este a bênção do Senhor e a misericórdia de Deus, seu salvador (Sl 23,5)? Será visitado, sem dúvida, muitas vezes, e nunca ignorará o tempo da sua visita, por mais que aquele que visita em espírito venha às escondidas e furtivamente, como amante pudico. A alma bem vigilante, pois, o verá, com a mente sóbria, quando ainda está longe, e depois perceberá todas as coisas que mostramos que a esposa notou, com tanta diligência e precisão, na vinda do amado; porque ele mesmo diz: Os que vigiarem de madrugada por mim me encontrarão (Pr 8,17). Pois reconhecerá também o desejo de quem se apressa, e sentirá logo quando estiver perto e quando já estiver presente; e verá com olho feliz até o olho que a olha, como um raio de sol que entra pelas janelas e pelas frestas da parede; e por fim ouvirá vozes de exultação e de amor, chamada amiga, pomba, formosa.`
    },
    {
      n: 5,
      texto: `Quem é sábio, e entenderá estas coisas, de modo a poder distingui-las dignamente umas das outras, designar cada uma e defini-las para que os outros as entendam? Se isso se espera de mim, eu preferiria ouvi-lo de alguém que o tivesse experimentado, acostumado e exercitado nestas coisas. Mas, como todo aquele que é assim prefere, por pudor, esconder no silêncio o que no silêncio percebe, e julga mais seguro guardar para si o seu segredo, digo eu, a quem cabe por ofício falar e não é lícito calar, o que quer que conheço destas coisas por experiência própria ou alheia, e que muitos podem experimentar facilmente, deixando as coisas mais altas aos que as podem alcançar. Se, pois, for advertido, por fora por um homem ou por dentro pelo Espírito, a defender a justiça e a guardar a equidade, tal persuasão salutar será para mim, sem dúvida, o anúncio da vinda próxima do esposo e uma espécie de preparação para receber dignamente o visitador do alto; como indica o Profeta, dizendo que a justiça caminhará diante dele (Sl 84,14); e que fala assim a Deus: A justiça e o juízo, diz, são a preparação do teu trono (Sl 88,15). E a mesma esperança me sorrirá, se ressoar uma palavra sobre a humildade ou a paciência, ou ainda sobre a caridade fraterna e a obediência devida aos superiores; e sobretudo sobre buscar a santidade e a paz e procurar a pureza do coração; pois a Escritura diz: À casa do Senhor convém a santidade (Sl 92,5); e: O seu lugar foi estabelecido na paz (Sl 75,3); e: Os puros de coração verão a Deus (Mt 5,8). Tudo, pois, o que for sugerido ao ânimo sobre estas ou quaisquer outras virtudes será para mim, como disse, sinal de que a visita do Senhor das virtudes está próxima da minha alma.`
    },
    {
      n: 6,
      texto: `E, se o justo me corrigir com misericórdia e me repreender (cf. Sl 140,5), sentirei o mesmo, sabendo que o zelo e a benevolência do justo abrem caminho àquele que sobe sobre o ocaso (cf. Sl 67,5). Bom ocaso, quando, à correção do justo, o homem fica de pé e o vício cai, e o Senhor sobe sobre ele, pisando-o com os pés e esmagando-o para que não se levante. Não se deve, pois, desprezar a repreensão do justo, que é ruína do pecado, saúde do coração, e também caminho de Deus para a alma. E nenhuma palavra que edifique para a piedade, para as virtudes, para os bons costumes, deve ser ouvida com descuido; porque também ali está o caminho pelo qual se mostra a salvação de Deus (Sl 49,23). E, se a palavra vem agradável e bem aceita, de modo que, afastado o fastio, seja ouvida com desejo, deve-se crer que o Esposo já não só vem, mas se apressa, isto é, vem com desejo. Pois é o desejo dele que cria o teu; e, se tu te apressas a acolher a sua palavra, é porque ele se apressa a entrar; pois não fomos nós, diz, que o amamos, mas ele nos amou primeiro (1Jo 4,10). E, se sentes também a palavra ardente, e por ela a consciência queimar-se na lembrança do pecado, lembra-te então daquele de quem a Escritura diz que um fogo irá à sua frente (Sl 96,3), e não duvides de que ele está perto. Enfim, o Senhor está perto dos que têm o coração atribulado (Sl 33,19).`
    },
    {
      n: 7,
      texto: `Mas, se com aquela palavra não só te compunges, mas te convertes todo ao Senhor, jurando e decidindo guardar os juízos da sua justiça (cf. Sl 118,106), fica sabendo que ele já está presente, sobretudo se te sentes arder no seu amor. Pois lês dele uma coisa e outra: que um fogo vai à sua frente, e que ele mesmo é fogo. Pois Moisés diz dele que é um fogo devorador (Dt 4,24). E diferem nisto: o fogo que é enviado à frente tem ardor, mas não amor; aquece, mas não depura; move, mas não faz avançar. É enviado à frente só para despertar e preparar, e ao mesmo tempo para te advertir do que és por ti mesmo, para que depois te saiba mais doce o que logo serás por Deus. Mas o fogo que é Deus consome, mas não aflige; queima suavemente, devasta felizmente. Pois é verdadeiramente brasa devastadora (cf. Sl 119,4), mas que exerce a força do fogo sobre os vícios de tal modo que faz na alma as vezes de unção. Na força pela qual és mudado, pois, e no amor pelo qual és inflamado, reconhece o Senhor presente. Pois a direita do Senhor mostrou a sua força (Sl 117,16). E esta mudança da direita do Altíssimo (Sl 76,11) não se faz senão no fervor do espírito e na caridade sem fingimento, de modo que quem é assim diga: O meu coração abrasou-se dentro de mim, e na minha meditação se acende um fogo (Sl 38,4).`
    },
    {
      n: 8,
      texto: `E, consumida por este fogo toda mancha do pecado e toda ferrugem dos vícios, se, purificada e serenada já a consciência, se seguir uma súbita e insólita dilatação da mente e uma infusão de luz que ilumina o entendimento, quer para a ciência das Escrituras, quer para o conhecimento dos mistérios — a primeira, julgo, é dada para o nosso deleite, e a segunda para a edificação do próximo —, este é, sem dúvida, o olho de quem olha, que faz brilhar como a luz a tua justiça, e o teu direito como o meio-dia (cf. Sl 36,6), segundo aquilo do profeta Isaías: A tua luz, diz, nascerá como o sol (cf. Is 58,10). Mas este raio de tão grande claridade não se derramará por portas abertas, e sim por estreitas aberturas, enquanto estiver de pé esta parede arruinada do corpo. Enganas-te se esperas outra coisa, a qualquer pureza de coração que chegues, quando aquele contemplador eminente diz: Agora vemos como num espelho e em enigma; mas então veremos face a face (1Cor 13,12).`
    },
    {
      n: 9,
      texto: `Depois deste olhar de tão grande condescendência e misericórdia, segue-se a voz que insinua com brandura e suavidade a vontade divina; e esta voz não é outra coisa senão o próprio amor, que não pode ficar ocioso, e que solicita e persuade às coisas de Deus. Enfim, a esposa ouve que se levante e se apresse — sem dúvida, para ganhar almas. Pois a contemplação verdadeira e casta tem isto: a mente que ela inflamou com veemência no fogo divino, enche-a às vezes de tamanho zelo e desejo de ganhar para Deus quem o ame igualmente, que ela interrompe de muito boa vontade o repouso da contemplação pelo empenho da pregação; e, tendo alcançado em parte o que desejava, volta ao mesmo repouso com tanto mais ardor quanto mais frutuosamente se lembra de o ter interrompido; e, provado outra vez o gosto da contemplação, volta com mais vigor, com a prontidão de costume, a conquistar ganhos. Mas entre estas alternâncias a mente muitas vezes flutua, temendo e agitando-se veementemente, com medo de, arrastada de um lado e de outro pelos seus afetos, apegar-se a uma destas coisas mais do que é justo, e assim, numa ou noutra, desviar-se, ainda que um pouco, da vontade divina. E talvez o santo Jó sofresse alguma coisa assim, quando dizia: Se durmo, digo: Quando me levantarei? E de novo espero a tarde (Jó 7,4); isto é: quando repouso, acuso-me da obra descuidada; e, quando estou ocupado, acuso-me igualmente do repouso perturbado. Vês o homem santo agitar-se gravemente entre o fruto da obra e o sono da contemplação; e, embora sempre ocupado com coisas boas, arrepender-se sempre como de coisas más, e buscar a cada momento, com gemidos, a vontade de Deus. Pois o único remédio e refúgio em coisas assim é a oração e o frequente gemido a Deus, para que se digne mostrar-nos continuamente o que, quando e até que ponto quer que façamos. Tens, na minha opinião, estas três coisas — a pregação, a oração, a contemplação — recomendadas e designadas em três palavras. Pois com razão se chama amiga a que conquista com empenho e fidelidade os ganhos do esposo, pregando, aconselhando, servindo. Com razão pomba, a que, gemendo e suplicando na oração pelas suas faltas, não cessa de atrair para si a misericórdia divina. Com razão também formosa, a que, brilhando de desejo celeste, se reveste da beleza da contemplação do alto, ao menos nas horas em que o pode fazer com comodidade e oportunidade.`
    },
    {
      n: 10,
      texto: `Mas vê também se se pode ajustar a este tríplice bem de uma só alma aquilo das três pessoas que moravam numa só casa, amigas do Salvador e muito íntimas dele. Falo de Marta, que serve; de Maria, que se dedica ao repouso; e de Lázaro, como que gemendo sob a pedra e implorando a graça da ressurreição (Lc 10,38-42; Jo 11). Isto se disse porque a esposa é descrita tão diligente e tão vigilante em observar os caminhos do esposo que de modo nenhum lhe pode escapar quando e com quanta pressa ele vem a ela; e nenhuma surpresa a pode apanhar de modo que ignore quando está longe, quando perto e quando presente; e porque por isso mereceu não só ser olhada com misericórdia, mas também ser alegrada, por bondade, com palavras de amor, e alegrar-se muito com a voz do esposo.`
    },
    {
      n: 11,
      texto: `E nós acrescentamos a isto, ainda que com ousadia, que também qualquer alma dentre nós, se vigiar do mesmo modo, será igualmente saudada como amiga, consolada como pomba, abraçada como formosa. Será tido por perfeito todo aquele em cuja alma se virem concorrer estas três coisas de modo conveniente e oportuno: que saiba gemer por si e exultar em Deus, e ao mesmo tempo seja capaz de socorrer as necessidades do próximo; agradável a Deus, cauteloso consigo, útil aos seus. Mas quem é capaz destas coisas (cf. 2Cor 2,16)? Oxalá elas se conservem por longo tempo em todos nós — se não todas em cada um, ao menos cada uma em diversos, como hoje parece que as temos! Pois temos Marta, como amiga do Salvador, nos que administram fielmente as coisas exteriores. Temos também Lázaro, como pomba que geme: os noviços, que, mortos há pouco para os pecados, se cansam no seu gemido, sob o temor do juízo, por causa das feridas ainda recentes; e, como os feridos que dormem nos sepulcros, de quem já ninguém se lembra (cf. Sl 87,6), julgam-se assim esquecidos, até que, à ordem de Cristo, retirado o peso do temor como a massa da pedra que os oprimia, possam respirar na esperança do perdão. Temos também Maria, que contempla, naqueles que, com o passar de um tempo mais longo e com a cooperação da graça de Deus, puderam progredir para algo melhor e mais alegre: quando, já confiantes no perdão, não se preocupam tanto em revolver dentro de si a triste imagem dos pecados, quanto se deleitam insaciavelmente em meditar dia e noite na lei de Deus; e às vezes até, contemplando com o rosto descoberto a glória do esposo, com alegria inefável, são transformados na mesma imagem, de claridade em claridade, como pelo Espírito do Senhor (2Cor 3,18). Para que exorta a esposa a levantar-se e a apressar-se aquele que pouco antes parecia defendê-la, para que não a despertassem enquanto dormia, veremos noutro sermão. Esteja presente ele mesmo, para se dignar abrir-nos também a razão deste mistério, o esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
