SERMOES.sermao({
  id: 'bernardo-cantico-29',
  colecao: 'bernardo-cantico',
  ordem: 29,
  numero: 'XXIX',
  titulo: 'Da queixa da Igreja contra os que a combatem, ou contra os que combatem a unidade fraterna',
  fonte: 'De querimonia Ecclesiae contra suos impugnatores',
  argumento: `Sobre «os filhos da minha mãe combateram contra mim». Bernardo pergunta por que a esposa se queixa só dos de casa, quando tantos de fora a combateram — e responde que é porque o mal doméstico é o mais doloroso e o mais perigoso. Daí uma exortação à paz entre os irmãos, que desce ao miúdo: não só as injúrias abertas, mas o cochicho, o resmungo, o nariz torcido, a testa franzida. Uma palavra que parece leve a quem a diz pode deixar o outro ferido em silêncio, sem poder orar nem ler.

Depois vira a imagem do avesso: também os bons combatem, com a espada da palavra, os seus irmãos, para os ferir para a salvação. E fala da flecha escolhida do amor de Cristo, que atravessou a alma de Maria de lado a lado — e da sua esperança de sentir, ao menos, a ponta dela.

Tradução feita do texto latino de Migne (PL 183, 928-933).`,
  pontos: [
    {
      n: 1,
      texto: `Os filhos da minha mãe combateram contra mim (Ct 1,5). Anás e Caifás, e Judas Iscariotes, eram filhos da Sinagoga; e estes combateram com a maior aspereza contra a Igreja, filha também ela da Sinagoga, logo no seu nascimento, pendurando no madeiro Jesus, que a reunia. Pois já então Deus cumpriu por meio deles o que outrora tinha anunciado pelo profeta: Ferirei o pastor, e as ovelhas se dispersarão (Zc 13,7). E talvez seja dela aquela voz do cântico de Ezequias: A minha vida foi cortada como por um tecelão; quando eu ainda começava a urdir, ele me cortou (Is 38,12). Entende, pois, que foi destes, e dos outros daquele povo que se sabe terem contrariado o nome cristão, que a esposa disse: Os filhos da minha mãe combateram contra mim. E com acerto os chama filhos da sua mãe, e não também do seu pai, pois não tinham a Deus por pai, mas eram do diabo, seu pai (Jo 8,44) — homicidas, como aquele que foi homicida desde o princípio. Por isso não diz «os meus irmãos» nem «os filhos do meu pai», mas: Os filhos da minha mãe combateram contra mim. De outro modo, se não fizesse esta distinção, pareceria incluir também o apóstolo Paulo entre aqueles de quem se queixa, pois também ele perseguiu outrora a Igreja de Deus (1Cor 15,9); mas alcançou misericórdia, porque o fez por ignorância, estando na incredulidade (1Tm 1,13), e provou que tinha Deus por pai e que era irmão da Igreja, tanto pelo pai como pela mãe.`
    },
    {
      n: 2,
      texto: `Mas repara como acusa nomeadamente os filhos da sua mãe, e só a eles, como se só eles tivessem culpa. Quanto não sofreu também dos de fora! Como diz o profeta: Muitas vezes me combateram desde a minha juventude; e: Sobre as minhas costas trabalharam os pecadores (Sl 128,1-3). Por que te queixas, então, particularmente dos filhos da tua mãe, tu que não ignoras ter sido combatida tantíssimas vezes por uma nação e outra? Chamado à mesa do rico, diz a Escritura, considera com atenção o que te põem diante. Irmãos, estamos sentados à mesa de Salomão. Quem mais rico que Salomão? Não falo das riquezas da terra, ainda que Salomão também as tivesse em abundância; mas olhai para esta mesa, como está cheia de delícias do alto. São coisas espirituais e divinas as que nela nos põem diante. Considera, pois, com atenção, diz, o que te põem diante, sabendo que deves preparar coisas semelhantes (Pr 23,1-2). Eu, quanto está em mim, reparo com atenção que se me põe diante, nestas palavras da esposa — e que diz respeito inteiramente à minha instrução e à minha cautela —, o fato de só se mencionar, e nomeadamente, a perseguição dos de casa, e de se calarem tantas e tão graves coisas que se sabe ter ela sofrido, em toda a terra e de toda nação que há debaixo do céu, dos infiéis, dos hereges e dos cismáticos. Conheço a prudência da esposa, e não julgaria que ela deixou isso de lado por acaso ou por esquecimento. Mas chora com mais clareza aquilo que sente de modo diferente e de que julga que devemos guardar-nos com mais vigilância. Que é isso? O mal interno e doméstico. Isto te é dito claramente no Evangelho, pela boca do próprio Salvador: E os inimigos do homem serão os da sua própria casa (Mt 10,36). Isto também no profeta: O homem da minha paz, que comia o meu pão, levantou contra mim o calcanhar (Sl 40,10); e ainda: Se um inimigo me tivesse amaldiçoado, eu o teria suportado; e, se quem me odiava tivesse falado com arrogância contra mim, talvez me tivesse escondido dele. Mas tu, homem de uma só alma comigo, meu guia e meu conhecido, que comias comigo manjares doces (Sl 54,13-15)... — isto é: o que sofro de ti, meu conviva e companheiro de casa, sinto-o com mais pena e suporto-o com mais custo. Sabeis de quem é esta queixa, e a respeito de quem.`
    },
    {
      n: 3,
      texto: `Reconhecei, pois, também a esposa a queixar-se dos filhos da sua mãe com o mesmo afeto, porque no mesmo espírito, quando diz: Os filhos da minha mãe combateram contra mim. Por isso diz noutro lugar: Os meus amigos e os meus próximos aproximaram-se contra mim e pararam (Sl 37,12). Afastai sempre de vós, peço, este mal tão abominável e detestável, vós que experimentastes, e experimentais todos os dias, como é bom e como é agradável habitarem os irmãos juntos (Sl 132,1) — contanto que juntos, e não para escândalo. De outro modo, não é nem agradável nem bom, mas péssimo e penosíssimo. Ai daquele homem por quem se perturba o laço agradável da unidade! Carregará a sua condenação, seja ele quem for (Gl 5,10). Antes eu morra do que ouvir entre vós alguém a clamar com razão: Os filhos da minha mãe combateram contra mim. Não sois todos vós, nesta comunidade, como filhos de uma só mãe, irmãos uns dos outros? Que coisa de fora vos poderá perturbar ou entristecer, se estais bem por dentro e vos alegrais na paz fraterna? Quem vos poderá fazer mal, diz a Escritura, se fordes zelosos do bem? (1Pd 3,13) Por isso, aspirai aos dons melhores (1Cor 12,31), para vos mostrardes zelosos do bem. O dom excelentíssimo é a caridade, de todo incomparável, que o esposo celeste tantas vezes cuidava de inculcar à sua nova esposa, ora dizendo: Nisto conhecerão todos que sois meus discípulos, se tiverdes amor uns aos outros; ora: Dou-vos um mandamento novo: que vos ameis uns aos outros (Jo 13,35.34); e: Este é o meu mandamento: que vos ameis uns aos outros (Jo 15,12); e rezando para que fossem um, como ele e o Pai são um (Jo 17,11). E vê se o próprio Paulo, que te convida aos dons melhores, não põe a caridade acima de tudo, seja quando diz que é maior que a fé e a esperança e mais excelente que a ciência, seja quando, depois de enumerar muitos e admiráveis dons da graça do alto, nos manda enfim por um caminho ainda mais excelente — e esse caminho não é outro senão a caridade. Que poderíamos comparar àquilo que se prefere ao próprio martírio e à fé que transporta montanhas (1Cor 12,31; 13,3)? É isto, pois, o que digo: que a vossa paz venha de vós mesmos; e tudo o que de fora parece ameaçar não assusta, porque não faz mal. E, ao contrário, tudo o que de fora pareça afagar não é consolação nenhuma, se dentro — o que Deus não permita! — tiver germinado a semente da discórdia.`
    },
    {
      n: 4,
      texto: `Por isso, caríssimos, tende paz entre vós e não vos ofendais uns aos outros — nem com obras, nem com palavras, nem com qualquer sinal —, para que ninguém, amargurado e tomado pela falta de ânimo e pela tempestade (Sl 54,9), se veja obrigado a apelar para Deus contra os que o feriram ou entristeceram, e aconteça romper nesta palavra dura: Os filhos da minha mãe combateram contra mim. Pois, pecando assim contra o irmão, pecais contra Cristo, que diz: O que fizestes a um destes mais pequeninos, a mim o fizestes (Mt 25,40.45). E não é só das ofensas mais graves que é preciso guardar-se — da injúria aberta, por exemplo, ou da maldição —, mas também do cochicho escondido e venenoso. Não basta, digo, guardar a boca destas coisas e de outras semelhantes; é preciso evitar também as leves — se é que se deve chamar leve a qualquer coisa que te atrevas contra o irmão com vontade de ferir, quando basta isto, se te iras contra ele, para ficares réu do juízo de Deus (Mt 5,22). E com razão: pois o que tu julgas leve, e por isso lanças mais levianamente, muitas vezes o outro o recebe de outro modo — homem que vê a aparência e julga segundo a aparência, pronto a suspeitar uma trave onde há um cisco e a julgar fornalha uma faísca. Pois nem todos têm aquela caridade que tudo crê (1Cor 13,7); e os sentidos e os pensamentos do homem são mais inclinados a suspeitar o mal do que a crer o bem — sobretudo onde a disciplina do silêncio nem permite a ti, que estás em causa, desculpar-te, nem a ele abrir a ferida da suspeita que sofre, para que se cure. E assim ele se queima e morre, com a ferida fechada e mortal, gemendo dentro de si, enquanto, todo entregue à ira e à disputa, não consegue revolver em silêncio outra coisa na mente senão a ofensa que recebeu. Não pode orar, não pode ler, não pode meditar em nada de santo ou de espiritual; e assim, cortado o sopro da vida, enquanto caminha para a morte, privada dos seus alimentos, a alma por quem Cristo morreu — que ânimo tens tu entretanto, pergunto? Que sabor tem para ti a tua oração, ou qualquer obra que faças entretanto, quando contra ti Cristo clama angustiado do peito do irmão que entristeceste: O filho da minha mãe combate contra mim, e o que comia comigo manjares doces encheu-me de amargura?`
    },
    {
      n: 5,
      texto: `E, se disseres que ele não devia ter-se perturbado tanto por causa tão leve, respondo: quanto mais leve era, tanto mais levemente podias não a ter cometido. Aliás, não sei como chamas leve, como já disse, a qualquer coisa que passe de irar-se, quando da boca do próprio juiz ouviste que até isso fica sujeito ao juízo. Pois então? Chamarás leve aquilo em que Cristo é ofendido, aquilo por que hás de ser arrastado ao juízo de Deus, quando é coisa terrível cair nas mãos do Deus vivo (Hb 10,31)? Tu, pois, se por acaso receberes uma ofensa — o que às vezes é difícil não acontecer nestas comunidades —, não te apresses, à maneira dos do mundo, a ferir o irmão com uma resposta atravessada; nem ouses de modo algum, sob pretexto de corrigir, trespassar com palavra aguda e ardente a alma por quem Cristo se dignou ser pregado na cruz; não grunhas como quem repreende, não resmungues entre os lábios como quem murmura, não torças o nariz nem dês gargalhadas como quem escarnece, não franzas a testa como quem investe ou ameaça. Que a tua agitação morra ali mesmo onde nasce, e não se lhe permita sair, porque traz a morte e mataria; para que também tu possas dizer com o Profeta: Fiquei perturbado, e não falei (Sl 76,5).`
    },
    {
      n: 6,
      texto: `Soube de alguns que entendem isto de modo mais alto, como dito do diabo e dos seus anjos, que, tendo sido também eles filhos daquela Jerusalém do alto que é a nossa mãe, desde que caíram não cessam de combater a Igreja, sua irmã. Mas também não discuto, se alguém tomar isto em bom sentido: quando os espirituais que há na Igreja combatem os seus irmãos carnais com a espada do espírito, que é a palavra de Deus (Ef 6,17), ferindo-os para a salvação e fazendo-os avançar, com estes combates, para as coisas espirituais. Oxalá o justo me corrija com misericórdia e me repreenda (Sl 140,5), ferindo e curando, matando e dando vida, para que também eu ouse dizer: Vivo, mas já não sou eu, é Cristo que vive em mim (Gl 2,20). Põe-te de acordo com o teu adversário, diz o Senhor, enquanto estás com ele a caminho, para que não te entregue ao juiz, e o juiz ao carrasco (Mt 5,25). Bom adversário, com quem, se eu estiver de acordo, nem o juiz terá de que me acusar, nem o carrasco! Quanto a mim, se alguma vez entristeci algum de vós por coisas assim, não me arrependo: pois foram entristecidos para a salvação (2Cor 7,9). E não sei se alguma vez o fiz sem grande tristeza também minha, segundo aquilo: A mulher, quando dá à luz, está triste (Jo 16,21). Mas longe de mim lembrar-me ainda da aflição, tendo nas mãos o fruto da minha dor, ao ver Cristo formado nos filhos. E não sei como me são mais ternamente ligados os que, depois de repreensões e por meio de repreensões, enfim sararam da sua fraqueza, do que os que se mantiveram fortes desde o princípio, sem precisar de tal remédio.`
    },
    {
      n: 7,
      texto: `Neste sentido, pois, poderá a Igreja, ou a alma que ama a Deus, dizer que o sol a queimou: enviando e armando dentre os filhos da sua mãe os que a combatessem para a salvação e a levassem cativa para a fé e para o amor dele, trespassada de muitas daquelas flechas de que está escrito: As flechas do poderoso são agudas (Sl 119,4); e ainda: As tuas flechas cravaram-se em mim. E por isso continua: Não há saúde na minha carne (Sl 37,3-4) — para que, tornado por isso mais são e mais forte segundo a alma, diga: O espírito está pronto, mas a carne é fraca (Mt 26,41); e com o Apóstolo: Quando sou fraco, então é que sou poderoso e forte (2Cor 12,10). Vês como a fraqueza da carne aumenta o vigor do espírito e lhe dá forças? Assim, ao contrário, saibas que a força da carne produz a fraqueza do espírito. E que há de admirar que te tornes mais forte quando o inimigo enfraquece? A não ser que, com a maior loucura, tenhas por amiga aquela que não cessa de ter desejos contra o espírito (Gl 5,17). Vê, pois, se não é com prudência que o santo pede para ser flechado e combatido para a salvação, quando diz na oração: Trespassa as minhas carnes com o teu temor (Sl 118,120). Ótima flecha é este temor, que trespassa e mata os desejos da carne, para que o espírito se salve. E aquele que castiga o seu corpo e o reduz à servidão (1Cor 9,27), não te parece que também ele ajuda a mão de quem combate contra ele?`
    },
    {
      n: 8,
      texto: `É também flecha a palavra de Deus, viva e eficaz, e mais penetrante que qualquer espada de dois gumes (Hb 4,12), da qual diz o Salvador: Não vim trazer a paz, mas a espada (Mt 10,34). É também flecha escolhida (Is 49,2) o amor de Cristo, que não só trespassou a alma de Maria, mas a atravessou de lado a lado (Lc 2,35), de modo a não deixar no peito virginal nenhuma parcela vazia de amor; e assim ela amava de todo o coração, de toda a alma, com todas as forças, e era cheia de graça. Ou então a atravessou de lado a lado para chegar até nós, e para que todos recebêssemos daquela plenitude, e ela se tornasse mãe da caridade, cujo pai é Deus, que é caridade; dando à luz e pondo no sol a tenda dele (Sl 18,6), para se cumprir a Escritura que diz: Fiz de ti luz das nações, para que sejas a minha salvação até os confins da terra (Is 49,6). Isto se cumpriu por Maria, que deu à luz visível na carne aquele que recebera invisível, e não da carne nem com a carne. E ela recebeu em todo o seu ser a grande e doce ferida do amor; eu, porém, me julgaria feliz se sentisse ao menos a ponta extrema desta espada picar-me por dentro, para que, recebida ao menos uma pequena ferida de amor, também a minha alma dissesse: Estou ferida de caridade (Ct 2,5). Quem me dera ser, deste modo, não só ferido, mas vencido de todo, até se apagar a cor e o calor daquilo que combate contra a alma!`
    },
    {
      n: 9,
      texto: `Se as filhas deste mundo lançarem em rosto a uma alma assim que está pálida e sem cor, não te parece que ela poderá responder com propriedade: Não repareis em eu ser morena, porque o sol me queimou? E, se se lembrar de que chegou a isto pelas exortações ou repreensões de alguns servos de Deus, que a amavam com o zelo de Deus, não poderá acrescentar, em consequência e com verdade: Os filhos da minha mãe combateram contra mim? O sentido será, pois, segundo o que se disse, que a Igreja, ou qualquer alma aplicada, o diz não como quem geme ou se queixa, mas como quem se alegra e dá graças, e ainda se gloria de ser digna de ser e de ser chamada morena e sem cor pelo nome e pelo amor de Cristo; e atribua isso não à sua própria diligência, mas à graça e à misericórdia que a preveniu e que lhe mandou esses irmãos. Pois como creria sem quem pregasse? E como pregariam, se não fossem enviados? (Rm 10,14-15) Ela lembra que os filhos da sua mãe combateram contra ela não como quem está irada, mas como quem não é ingrata. Por isso segue: Puseram-me a guardar as vinhas. E creio que esta palavra, se for examinada espiritualmente, não parecerá ter em si queixa nem rancor, mas antes exalar algo de favorável. Mas, para lhe tocarmos, antes de ousarmos pôr-lhe a mão — pois o lugar é santo —, havemos de tornar propício, com as orações de costume, e assim consultar aquele Espírito que perscruta as profundezas de Deus; ou então o Unigênito, que está no seio do Pai, esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus sobre todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
