SERMOES.sermao({
  id: 'bernardo-cantico-73',
  colecao: 'bernardo-cantico',
  ordem: 73,
  numero: 'LXXIII',
  titulo: 'Como Cristo virá para julgar em forma humana, para aparecer suave aos eleitos; e como é menor que os anjos e, ao mesmo tempo, mais sublime que eles',
  fonte: 'Qualiter Christus ad judicandum veniet in forma humana',
  argumento: `"Volta; sê semelhante, meu amado, à gazela e ao filhote dos cervos, sobre os montes de Betel." Mal o esposo parte, a esposa já o chama de volta: o amor sem medida esquece o pudor e a conveniência. Os judeus ficam com esta letra, como o irmão mais velho que não quer entrar na festa; a Igreja procura nela o espírito e a vida. A esposa são os apóstolos, que, vendo o Senhor partir para o Pai, lhe pedem que apresse a vinda prometida — como a Igreja pede todos os dias: "Venha o teu reino".

A gazela e o filhote significam também a fraqueza do sexo e da idade: a esposa pede que Cristo venha julgar não na forma de Deus, mas na forma humana em que nasceu menino de uma mulher, para que a semelhança da natureza dê confiança aos eleitos, pois até os santos precisam de misericórdia. Os saltos do filhote separam os bons dos maus; os montes de Betel são os anjos, acima dos quais aparece aquele que foi diminuído um pouco abaixo deles — diminuído, não menor, porque se diminuiu por compaixão.

Tradução feita do texto latino de Migne (PL 183, 1134-1138).`,
  pontos: [
    {
      n: 1,
      texto: `Volta; sê semelhante, meu amado, à gazela e ao filhote dos cervos (Ct 2,17). Quê? Ainda agora ele vai, e já o chamas de volta? Que surgiu de repente em tão pouco tempo? Esqueceste alguma coisa? Sim: esqueceu tudo o que não é ele, e até a si mesma. Enfim, embora não seja desprovida de razão, agora, ao que parece, não está senhora da sua razão. Nem se vê de modo algum que tenha, no que sente, o pudor que talvez tenha nos costumes. É o amor sem medida que faz isto. É ele que, triunfando em si e tornando cativo todo sentimento de pudor, toda medida de conveniência, todo conselho de deliberação, gera um certo descaso e um certo descuido de toda modéstia e oportunidade. Pois vê agora como, mal ele começa a ir-se, já lhe pede que volte. Pede-lhe até que se apresse, e que corra como algum animal selvagem dos bosques que corre velozmente, por exemplo, a gazela ou o filhote dos cervos. Este é o teor da letra, e esta é a porção dos judeus.`
    },
    {
      n: 2,
      texto: `Eu, porém, como recebi do Senhor (cf. 1Cor 11,23), procurarei no seio profundo da palavra sagrada o espírito e a vida (cf. Jo 6,64); e esta é a minha parte, eu que creio em Cristo. Por que não tiraria da letra estéril e insípida o manjar doce e salutar do espírito, como o grão da palha, a amêndoa da casca, o tutano do osso? Nada tenho a ver com essa letra, que, provada, sabe a carne, e, engolida, traz a morte; mas o que nela está coberto vem do Espírito Santo. E o Espírito fala mistérios, segundo o testemunho do Apóstolo (1Cor 14,2); mas Israel, em vez do mistério velado, fica com o próprio véu do mistério. Por quê, senão porque ainda está posto um véu sobre o seu coração (cf. 2Cor 3,15)? Assim, o que a letra soa é dele; o que ela significa é meu; e por isso para ele é o ministério da morte na letra (cf. 2Cor 3,7), para mim a vida no espírito. Pois o espírito é que dá a vida (Jo 6,64): porque dá a inteligência. Não é a inteligência vida? Dá-me inteligência, e viverei (Sl 118,144), diz o Profeta ao Senhor. A inteligência não fica de fora, não se prende à superfície, não apalpa como um cego as coisas exteriores; mas perscruta o fundo, e costuma arrebatar e levar para si, com toda a avidez, os preciosíssimos despojos da verdade, e dizer ao Senhor com o Profeta: Eu me alegrarei com as tuas palavras como quem encontra muitos despojos (Sl 118,162). Assim, com efeito, o reino da verdade sofre violência, e os violentos o arrebatam (Mt 11,12). Mas aquele irmão mais velho que, vindo do campo, representou o povo antigo e terreno — que, ensinado a gostar da debulha (cf. Os 10,11) por causa de uma herança terrena, geme angustiado, com a fronte esfolada, sob o pesado jugo da lei, e suporta o peso do dia e o calor (cf. Mt 20,12) —, esse, digo, porque não teve inteligência, ainda agora está de fora e, nem convidado pelo pai, quer entrar na casa do banquete, privando-se até hoje da música, da dança e do novilho cevado (Lc 15,25-30). Infeliz, que se recusa a experimentar como é bom e agradável os irmãos viverem unidos (Sl 132,1). E fique isto dito para distinguir a parte da Igreja e a parte da Sinagoga, de modo que a cegueira desta se torne mais manifesta pela sabedoria daquela, e a felicidade daquela sobressaia pela lamentável insensatez desta.`
    },
    {
      n: 3,
      texto: `Examinemos agora as palavras da esposa, e procuremos exprimir os castos afetos do santo amor de tal modo que não pareça ter ficado na palavra sagrada nada sem razão, nada indecoroso ou inoportuno. Se nos vier à mente aquela hora em que o Senhor Jesus — pois ele é o esposo — passava deste mundo para o Pai (Jo 13,1), e ao mesmo tempo o que sentia então aquela sua Igreja doméstica, recém-casada, quando se via abandonada, como viúva desolada, pela sua única esperança — falo dos apóstolos, que, deixando tudo, o tinham seguido (cf. Mt 19,27) e permanecido com ele nas suas provações (cf. Lc 22,28) —; se pensarmos nisto, digo, não parecerá sem motivo nem fora de propósito, penso eu, que ela, tão triste com a partida, estivesse igualmente ansiosa pela volta, sobretudo estando assim afetada e assim deixada. Assim, para ela, que amava e estava necessitada, esta era a dupla razão de exortar o amado: já que não se podia convencê-lo a não ir e subir para onde estava antes (cf. Jo 6,63), que ao menos apressasse a vinda que prometera de novo. Pois o desejar e pedir que ele seja semelhante a animais selvagens, e a animais tais que parecem os mais ágeis na corrida, é indício de um ânimo que deseja, para quem nada se apressa bastante. Não é isto que pede todos os dias, quando diz na oração: Venha o teu reino (Mt 6,10)?`
    },
    {
      n: 4,
      texto: `Eu, porém, julgo que, além da agilidade, se exprime com não menos significação também a fraqueza: a do sexo, na gazela; a da idade, no filhote. Ela quer, pois, parece-me, que ele, embora venha com poder, não apareça no juízo na forma de Deus (cf. Fl 2,6), mas naquela em que não só nasceu, mas nasceu para nós como menino (cf. Is 9,6), e isto só do sexo feminino, mais fraco. Para quê? Para que, por uma e outra coisa, seja lembrado de se abrandar com o fraco no dia da ira, e se recorde, no juízo, de que a misericórdia triunfa sobre o juízo (cf. Tg 2,13). Pois, se observar as iniquidades, até as dos eleitos, quem subsistirá (Sl 129,3)? Os astros não são puros diante dele (cf. Jó 25,5), e nos seus anjos encontrou maldade (Jó 4,18). Ouve, enfim, o que diz a Deus um santo e eleito: Tu, diz, perdoaste a impiedade do meu pecado. Por isso te suplicará todo santo no tempo oportuno (Sl 31,5-6). Também os santos, pois, precisam de suplicar pelos pecados, para serem salvos pela misericórdia, não confiando na própria justiça. Pois todos pecaram, e todos precisam da misericórdia (cf. Rm 3,23). Para que, pois, quando se irar, se lembre da misericórdia (cf. Hab 3,2), ela lhe pede que apareça com o aspecto da misericórdia, aquele de que fala o Apóstolo: E, no aspecto, reconhecido como homem (Fl 2,7).`
    },
    {
      n: 5,
      texto: `E isto, necessariamente. Pois, se mesmo com este abrandamento haverá no juízo tanta equidade, no juiz tanto rigor, na majestade tanta sublimidade, tanta novidade na própria face das coisas, que, segundo o profeta, não se poderá imaginar o dia da sua vinda (Ml 3,2), que seria, pensas, se aquele fogo devorador (cf. Hb 12,29) — falo do Deus onipotente — viesse na grandeza, na força e na pureza da sua divindade, para mostrar o seu poder contra a folha arrebatada pelo vento e perseguir a palha seca (Jó 13,25)? E é homem, diz; e quem o conhecerá (cf. Jr 17,9)? E quem ficará de pé para o ver (Ml 3,2)? Quanto mais nenhum dos homens suportaria Deus, se se mostrasse a nós sem o homem, inacessível pela claridade, inatingível pela altura, incompreensível pela majestade! Mas agora, quando em breve se inflamar a sua ira (Sl 2,13), quão agradável aparecerá, por causa dos filhos da graça, a doce visão de um homem: firmeza da fé, força da esperança, aumento da confiança, isto é, de que a graça e a misericórdia estão com os seus santos, e o seu olhar sobre os seus eleitos (Sb 4,15)! Enfim, o próprio Deus Pai deu ao Filho o poder de julgar, não porque é seu Filho, mas porque é Filho do homem (Jo 5,27). Ó verdadeiro Pai das misericórdias (cf. 2Cor 1,3)! Quer que os homens sejam julgados por um homem, para que, em tamanho pavor e perturbação dos maus, a semelhança da natureza dê confiança aos eleitos. Tinha-o predito outrora o santo Davi, orando e profetizando ao mesmo tempo: Ó Deus, diz, dá ao rei o teu juízo, e a tua justiça ao filho do rei (Sl 71,2). E não destoa disto a promessa feita pelos anjos, que, tendo ele subido, falavam assim aos apóstolos: Este Jesus, que do meio de vós foi elevado ao céu, virá do mesmo modo como o vistes ir para o céu (At 1,11) — isto é, nesta mesma forma e substância do corpo.`
    },
    {
      n: 6,
      texto: `Fica claro, por tudo isto, que a esposa tem em si o conselho divino e não ignora o mistério da vontade do alto, ela que, sob a figura de animais sem armas e sem força, anuncia, com o afeto de quem ora e o espírito de quem profetiza, que no juízo se há de mostrar a natureza mais fraca — ou antes, inferior, porque já não será fraca —; de modo que aquele que moverá o céu e a terra com o seu poder, cingido de força (cf. Sl 64,7) contra os insensatos, apareça, no entanto, suave e manso, e como que inteiramente desarmado, por causa dos eleitos. Aqui se pode acrescentar ainda que, para separar uns dos outros, ele precisará de certo modo tanto dos saltos do filhote como dos olhos da gazela, para poder ver e distinguir, em tão grande multidão e em tamanha perturbação, sobre quais deve saltar e por cima de quais deve passar, para que não aconteça ser pisado o justo em vez do ímpio, quando esmagar os povos na sua ira (cf. Sl 109,5). Pois, quanto aos ímpios, é necessário que se cumpra a profecia de Davi, ou antes, a palavra do Senhor que fala pela sua boca: Hei de esmigalhá-los como o pó diante do vento, hei de apagá-los como a lama das ruas (Sl 17,43); e também se reconhecerá então cumprida outra palavra, que predissera por outro profeta, quando, voltando para junto dos anjos, disser: Pisei-os no meu furor e calquei-os na minha ira (Is 63,3).`
    },
    {
      n: 7,
      texto: `Se, porém, a alguém parecer que se deve antes entender que o nosso filhote há de passar por cima dos maus e saltar sobre os bons, não discuto: pense apenas que os saltos estarão dispostos para distinguir os bons e os maus. Pois também eu, se bem me lembro, disse assim noutro sermão, onde se encontra este mesmo versículo, posto pelo autor noutro lugar, mais acima, e também explicado por mim. Mas ali se disse que este filhote salta e passa por cima segundo a distribuição da graça, que nesta vida é dada a uns e não a outros, por um juízo de Deus justo, mas oculto; aqui, porém, segundo a retribuição final e diversa dos méritos. E talvez pareça confirmar este sentido o final deste versículo, que eu quase tinha esquecido. Pois, depois de dizer: Sê semelhante, meu amado, à gazela e ao filhote dos cervos, acrescenta: sobre os montes de Betel. Pois na casa de Deus, que é o que significa Betel, os montes não são maus. Por isso o filhote, saltando sobre eles, não os pisa, mas os alegra, para que se cumpra a Escritura que diz: Os montes e as colinas cantarão louvores diante de Deus (Is 55,12). Há, sem dúvida, montes que, segundo o Evangelho, a fé comparada ao grão de mostarda remove (Mt 17,19); mas não são os montes de Betel. Pois a fé de modo nenhum remove os que são de Betel, mas os honra.`
    },
    {
      n: 8,
      texto: `E, se os principados e as potestades, e também as demais legiões dos espíritos bem-aventurados e as virtudes dos céus, são os montes de Betel — de modo que entendamos deles o que se disse: Os seus fundamentos estão sobre os montes santos (Sl 86,1) —, certamente não é vil nem desprezível este filhote, que se viu aparecer acima de montes tão excelentes, tornado tanto superior aos anjos quanto mais excelente é o nome que herdou (Hb 1,4). Que importa, pois, que no salmo leiamos que foi diminuído um pouco abaixo dos anjos (Sl 8,6)? Pois não é menos excelente por ter sido feito menor; nem o Apóstolo e o Profeta disseram coisas contrárias, pois tinham o mesmo Espírito. Pois, se foi por condescendência que foi diminuído, e não por necessidade, nada se põe com isso em desfavor da sua bondade, mas a seu favor. Enfim, o Profeta disse que foi diminuído, não que é menor, exaltando a graça e repelindo a injúria. Pois a natureza recusa a inferioridade, e a causa desculpa a diminuição. Foi diminuído porque ele mesmo quis (cf. Is 53,7): diminuído por vontade sua e por necessidade nossa. Diminuir-se assim foi compadecer-se. Que perda é esta? Tudo o que pareceu perder-se para a majestade acrescentou-se à piedade. Aliás, nem o Apóstolo calou este grande segredo de tão grande piedade, mas diz: Vemos, porém, aquele que foi diminuído um pouco abaixo dos anjos, Jesus, coroado de glória e de honra por causa da paixão da morte (Hb 2,9).`
    },
    {
      n: 9,
      texto: `E isto tenhamos dito sobre o nome e a semelhança do filhote, para a aplicarmos ao esposo, segundo a palavra da esposa, sem injúria à majestade. Que digo, sem injúria à majestade, quando nem a fraqueza ficou sem honra? É filhote, é pequenino; diz-se também semelhante à gazela, como nascido de mulher (cf. Gl 4,4); e, no entanto, está sobre os montes de Betel; e, no entanto, foi feito mais alto que os céus (Hb 7,26). Não diz: sendo ou existindo mais alto que os céus, mas: feito mais alto que os céus; para que ninguém pense que se disse daquela natureza em que ele é aquele que é (cf. Ex 3,14). E também onde é preferido aos anjos, diz-se igualmente que foi tornado superior, e não que permanece ou existe superior. Daí se vê que, não só naquilo que é desde a eternidade, mas também naquilo que se fez no tempo, reivindica para si toda eminência acima de todo principado e potestade (cf. Ef 1,21), enfim, acima de toda criatura, como primogênito de toda a criação (Cl 1,15). Assim, o que é loucura de Deus é mais sábio que os homens, e o que é fraqueza de Deus é mais forte que os homens (1Cor 1,25). Isto diz o Apóstolo. A mim, porém, não parece que erre quem disser que a loucura e a fraqueza de Deus devem ser preferidas também à sabedoria e à fortaleza dos anjos. Assim, pois, esta passagem se aplicará convenientemente à Igreja universal.`
    },
    {
      n: 10,
      texto: `Quanto ao que diz respeito a uma alma em particular — pois também uma só, se ama a Deus com doçura, com sabedoria, com intensidade, é esposa —, cada homem espiritual pode observar em si mesmo que experiência própria lhe corresponde. Eu, por mim, não recearei dizer diante de vós seja o que for que me foi concedido experimentar em mim de coisas deste gênero. Pois, ainda que, ao ser ouvido, talvez pareça vil e desprezível, não me importa; porque quem é espiritual não me desprezará, e quem não o é não me entenderá. Contudo, se guardar isto para outro sermão, talvez não faltem os que se edifiquem com o que, entretanto, rogado, o Senhor inspirar: o esposo da Igreja, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
