SERMOES.sermao({
  id: 'bernardo-cantico-33',
  colecao: 'bernardo-cantico',
  ordem: 33,
  numero: 'XXXIII',
  titulo: 'Do que a mente devota deve sempre buscar; o que é o meio-dia; e dos quatro gêneros de tentação que sempre se devem evitar',
  fonte: 'De his quae semper sectanda sunt a mente devota',
  argumento: `A esposa pede: mostra-me onde apascentas, onde repousas ao meio-dia. Bernardo lê nisso o desejo da pátria, onde o pastor pode deitar-se porque o rebanho está seguro, e onde o alimento é o próprio Verbo, sem a casca do sacramento nem a palha da letra. A vida de Cristo na terra foi aurora; a ressurreição, manhã; o meio-dia pleno ainda está por vir, e só ele dissipa todas as sombras.

Daí nasce a parte mais célebre do sermão: a leitura do salmo 90 como mapa das quatro tentações — o temor da noite, que assusta os principiantes; a flecha que voa de dia, que é a vanglória; o negócio que anda nas trevas, que é a hipocrisia ambiciosa; e o demônio do meio-dia, que ataca os perfeitos com a aparência de um bem maior. Bernardo aplica as quatro, em seguida, à história da Igreja: os mártires, os hereges, a corrupção do clero do seu tempo — descrita com uma dureza que não poupa ninguém — e, por fim, o Anticristo.

Tradução feita do texto latino de Migne (PL 183, 951-959).`,
  pontos: [
    {
      n: 1,
      texto: `Mostra-me, tu a quem a minha alma ama, onde apascentas, onde repousas ao meio-dia (Ct 1,6). E um outro diz: Mostra-me por que me julgas assim (Jó 10,2). Ali, sem dúvida, não protesta contra a sentença, mas investiga a causa, pedindo que os açoites o instruam, e não que o livrem deles. Outro ainda reza, dizendo: Mostra-me, Senhor, os teus caminhos, e ensina-me as tuas veredas (Sl 24,4). E que caminhos ou veredas quis dizer, ele o mostra em outro lugar: Conduziu-me, diz, pelas veredas da justiça (Sl 22,3). São três, pois, as coisas que a alma ávida de Deus não cessa de indagar: a justiça, o juízo e o lugar onde habita a glória do esposo — como o caminho por onde andar, a cautela com que andar e a morada para onde andar. Dessa morada tens isto no profeta: Uma coisa pedi ao Senhor, e esta buscarei: habitar na casa do Senhor todos os dias da minha vida (Sl 26,4); e ainda: Senhor, amei a beleza da tua casa e o lugar onde habita a tua glória (Sl 25,8). Quanto às outras duas: A justiça e o juízo, diz, são a preparação do teu trono (Sl 88,15). Com razão a mente devota busca estas três coisas, que são o trono de Deus e a preparação do trono. E é belo como tudo concorre igualmente, por privilégio da esposa, para a perfeição das virtudes: que ela seja formosa pela forma da justiça, cautelosa pelo conhecimento dos juízos, casta pelo desejo da presença, ou da glória, do esposo. Assim, sem dúvida, convém que seja a esposa do Senhor: bela, instruída e casta. O pedido que pus em último lugar é, pois, o deste passo; pois ela pede àquele a quem a sua alma ama que lhe mostre onde apascenta e onde repousa ao meio-dia.`
    },
    {
      n: 2,
      texto: `E repara, primeiro, com que elegância distingue o amor do espírito do afeto da carne: querendo designar o amado antes pelo próprio afeto do que pelo nome, não diz simplesmente: Tu a quem amo; mas: Ó tu, a quem ama a minha alma — indicando um amor espiritual. Depois, observa com atenção o que tanto a atrai no lugar do pasto. Nem te passe despercebido o que diz da hora do meio-dia, e que se procura sobretudo aquele lugar onde quem apascenta também repousa, o que é sinal de grande segurança. Pois julgo que se acrescentou "repousas" porque ali não é preciso ficar de pé e vigiar, guardando o rebanho, já que o rebanho, mesmo com o pastor deitado e descansando à sombra, corre livremente pelos pastos. Feliz região, onde as ovelhas entram e saem à vontade, e não há quem as espante! Quem me dera ver-vos, e a mim convosco, apascentados nos montes junto com aquelas noventa e nove que, segundo se lê, ali foram deixadas quando o seu pastor, por bondade, desceu em busca da única que se tinha extraviado (Mt 18,12)! Seguro, sem dúvida, repousa perto delas quem nem sequer hesitou em afastar-se para longe, sabendo que as deixava em lugar seguro. Com razão a esposa suspira por aquele lugar; com razão anseia pelo lugar do pasto e ao mesmo tempo da paz — mais: do repouso, da segurança, da exultação, da admiração, do assombro. Pois também a mim, miserável — ai! —, que vivo longe e o saúdo de longe (cf. Hb 11,13), eis que a simples lembrança dele me leva às lágrimas, bem conforme o afeto e a voz dos que dizem: Junto aos rios da Babilônia, ali nos sentamos e choramos, lembrando-nos de ti, Sião (Sl 136,1). Dá-me vontade de exclamar também eu, com a esposa e com o Profeta: Louva o teu Deus, ó Sião, porque reforçou as trancas das tuas portas, abençoou os teus filhos dentro de ti; ele, que pôs a paz nas tuas fronteiras e te sacia com a flor do trigo (Sl 147,12-14). Quem não desejaria ardentemente ser apascentado ali, pela paz, pela flor do trigo, pela fartura? Ali nada se teme, nada enfastia, nada falta. Morada segura: o paraíso; alimento doce: o Verbo; riqueza sem medida: a eternidade.`
    },
    {
      n: 3,
      texto: `Também eu tenho o Verbo, mas na carne; também a mim se serve a verdade, mas no sacramento. O anjo se farta da flor do trigo e se sacia com o grão sem casca; eu, por enquanto, tenho de me contentar com uma espécie de casca do sacramento, com o farelo da carne, com a palha da letra, com o véu da fé. E tais coisas, provadas, trazem a morte, se não recebem das primícias do Espírito (Rm 8,23) algum tempero, por pequeno que seja. É mesmo a morte na panela para mim, se não for adoçada com a farinha do profeta (2Rs 4,40-41). Enfim, sem o espírito, o sacramento é recebido para condenação (1Cor 11,29), a carne de nada serve (Jo 6,64), a letra mata (2Cor 3,6) e a fé está morta (Tg 2,26). Mas é o espírito que dá a vida (Jo 6,64), para que eu viva nelas. Contudo, por mais que o espírito as torne substanciosas, de modo nenhum se recebe com igual prazer a casca do sacramento e a flor do trigo, a fé e a visão, a lembrança e a presença, a eternidade e o tempo, o rosto e o espelho, a imagem de Deus e a forma de servo. Em tudo isto, a minha fé é rica, e o meu entendimento, pobre. E acaso têm o mesmo sabor o entendimento e a fé, se esta é para o mérito e aquele para o prêmio? Vês, pois, que há tanta distância entre os alimentos quanto entre os lugares; e que, assim como os céus estão acima da terra (cf. Is 55,9), assim os que neles habitam abundam em bens melhores.`
    },
    {
      n: 4,
      texto: `Apressemo-nos, pois, filhos, apressemo-nos rumo ao lugar mais seguro, ao pasto mais suave, ao campo mais rico e mais fértil. Apressemo-nos, para habitarmos sem medo, termos fartura sem falta, banquetearmo-nos sem fastio. Pois tu, Senhor dos exércitos, que julgas todas as coisas com tranquilidade (Sb 12,18), ali também apascentas todos com igual segurança. É o mesmo que é Senhor dos exércitos e pastor das ovelhas. Ali, pois, apascentas e ao mesmo tempo repousas; mas não aqui. Enfim, estavas de pé quando, do céu, olhavas uma das tuas ovelhinhas — falo de Estêvão — cercada de lobos na terra (At 7,55). Por isso, peço-te, mostra-me onde apascentas, onde repousas ao meio-dia — isto é, o dia inteiro: pois aquele meio-dia é o dia todo, e não conhece a tarde. E por isso aquele dia nos teus átrios vale mais que mil (Sl 83,11), porque não conhece o ocaso. Mas talvez tenha tido uma manhã: quando, pela primeira vez, o dia santificado brilhou para nós, pelas entranhas de misericórdia do nosso Deus, com que nos visitou o Sol nascente que vem do alto (Lc 1,78). Então, verdadeiramente, recebemos, ó Deus, a tua misericórdia no meio do teu templo (Sl 47,10), quando, no meio da sombra da morte, nasceu para nós a luz do romper da manhã, e de manhã vimos a glória do Senhor (cf. Ex 16,7). Quantos reis e profetas quiseram ver, e não viram (Lc 10,24)! Por quê? Senão porque era noite, e ainda não viera aquela manhã esperada, à qual fora prometida a misericórdia? Por isso alguém orava, dizendo: Faze-me ouvir pela manhã a tua misericórdia, porque em ti esperei (Sl 142,8).`
    },
    {
      n: 5,
      texto: `Houve, com efeito, uma espécie de aurora deste dia, desde que o sol da justiça (Ml 4,2) foi anunciado à terra pelo arcanjo Gabriel, e a Virgem concebeu Deus no seio, por obra do Espírito Santo, e Virgem o deu à luz; e depois, durante todo o tempo em que foi visto na terra e conviveu com os homens (Br 3,38). Pois durante todo esse tempo a luz apareceu tão pequena, e tão verdadeiramente como luz de aurora, que quase todos ignoravam que entre os homens já era dia. Enfim, se o tivessem conhecido, nunca teriam crucificado o Senhor da glória (1Cor 2,8). E até aos poucos discípulos se dizia: Ainda há pouca luz em vós (Jo 12,35); porque era a aurora e o começo — ou antes, o indício — do dia, enquanto o Sol ainda escondia os seus raios e não os espalhava sobre a terra. Também Paulo dizia que a noite passou e o dia se aproximou (Rm 13,12), dando a entender que ainda então havia tão pouca luz que preferiu dizer que o dia se tinha aproximado, e não que tinha chegado. E quando dizia isso? Certamente quando o Sol, de volta da mansão dos mortos, já se tinha elevado às alturas do céu. Quanto mais quando a semelhança da carne do pecado (Rm 8,3), como uma nuvem espessa, ainda cobria a aurora, com todos os sofrimentos do nosso corpo, a ponto de não faltarem nem a morte amarga nem a cruz infame! Quanto mais, digo, era então pequena e muito tênue a luz, e parecia vir antes da presença da aurora que da do Sol!`
    },
    {
      n: 6,
      texto: `Era aurora, pois — e bastante escura —, toda aquela vida de Cristo sobre a terra, até que, pondo-se e nascendo de novo, afugentou a aurora com a luz mais clara da sua presença de sol; e, feita a manhã, a noite foi tragada pela vitória (cf. 1Cor 15,54). Enfim, tens: E muito cedo, no primeiro dia da semana, vêm ao sepulcro, já nascido o sol (Mc 16,2). Não foi manhã, quando nasceu o Sol? E trouxe da ressurreição uma beleza nova e uma luz mais serena que de costume; pois, ainda que o tenhamos conhecido segundo a carne, agora já não o conhecemos assim (2Cor 5,16). Está escrito no Profeta: Revestiu-se de beleza, revestiu-se de fortaleza e cingiu-se (Sl 92,1); porque sacudiu as fraquezas da carne como umas nuvens, vestindo a túnica da glória. Desde então o Sol se elevou e, espalhando aos poucos os seus raios sobre a terra, começou pouco a pouco a aparecer em toda parte mais claro e a ser sentido mais quente. Mas, por mais que aqueça e se fortaleça, e multiplique e estenda os seus raios por todo o curso desta nossa mortalidade — pois estará conosco até a consumação dos séculos (Mt 28,20) —, não chegará contudo à luz do meio-dia, nem será visto agora naquela plenitude em que há de ser visto depois, e somente por aqueles a quem ele julgar dignos desta visão. Ó verdadeiro meio-dia, plenitude de calor e de luz, em que o sol se detém, as sombras desaparecem, os pântanos secam e os maus cheiros se dissipam! Ó solstício perene, em que o dia já não há de declinar! Ó luz do meio-dia, ó brandura da primavera, ó beleza do verão, ó fartura do outono; e, para que não pareça que omiti alguma coisa, ó repouso e descanso do inverno! Ou então, se preferes: só o inverno terá então passado e ido embora (cf. Ct 2,11). Mostra-me, diz ela, este lugar de tanta claridade, de tanta paz e de tanta plenitude, para que — assim como Jacó, permanecendo ainda no corpo, viu o Senhor face a face e a sua alma foi salva (Gn 32,30); ou como Moisés o viu, não por figuras e enigmas, nem por sonhos, como os outros profetas, mas de um modo muito superior e desconhecido dos demais, conhecido só dele e de Deus (Nm 12,6-8); ou como Isaías, com os olhos do coração abertos, o viu sobre um trono alto e elevado (Is 6,1); ou ainda como Paulo, arrebatado ao paraíso, ouviu palavras inefáveis (2Cor 12,4) e viu com os seus olhos o seu Senhor Jesus Cristo (cf. 1Cor 9,1) — assim também eu mereça contemplar-te, no êxtase da mente, na tua luz e na tua beleza, apascentando com mais fartura, repousando com mais segurança.`
    },
    {
      n: 7,
      texto: `Pois também aqui apascentas, mas não até a saciedade; e não se pode repousar, mas é preciso ficar de pé e vigiar, por causa dos temores da noite (Ct 3,8). Ai! Nem a luz é clara, nem a refeição é plena, nem a morada é segura; por isso, mostra-me onde apascentas, onde repousas ao meio-dia. Tu me chamas feliz quando tenho fome e sede de justiça (Mt 5,6). Que é isto ao lado da felicidade daqueles que se saciaram dos bens da tua casa (Sl 64,5), que se banqueteiam e exultam na presença de Deus e se deleitam na alegria (Sl 67,4)? E também, se sofro alguma coisa por causa da justiça, igualmente me declaras feliz (Mt 5,10). E, sem dúvida, ser apascentada onde se teme sofrer tem o seu prazer, mas não segurança. E ser apascentada e sofrer ao mesmo tempo — não é um prazer incômodo? Aqui tudo me sai aquém da perfeição, muita coisa contra o meu desejo, e nada em segurança. Quando me encherás de alegria com o teu rosto (Sl 15,11)? O teu rosto, Senhor, eu buscarei (Sl 26,8). O teu rosto é o meio-dia. Mostra-me onde apascentas, onde repousas ao meio-dia. Sei muito bem onde apascentas sem repousar; mostra-me onde apascentas e repousas. Não ignoro onde costumas apascentar em outras horas; mas quero saber onde apascentas ao meio-dia. Pois, no tempo da minha mortalidade e no lugar da minha peregrinação, acostumei-me, sob a tua guarda, a ser apascentada e a apascentar na lei, nos profetas e nos salmos que falam de ti (cf. Lc 24,44); e também nos pastos do Evangelho e junto dos apóstolos igualmente repousei; muitas vezes também mendiguei, como pude, o sustento para mim e para os meus nos feitos dos santos, nas suas palavras e nos seus escritos; mais vezes, porém — porque estava mais à mão —, comi o pão da dor (Sl 126,2) e bebi o vinho da compunção (Sl 59,5); e as minhas lágrimas tornaram-se o meu pão de dia e de noite, enquanto me dizem todos os dias: Onde está o teu Deus? (Sl 41,4). Exceto o que recebo da tua mesa: pois preparaste diante de mim uma mesa contra os que me afligem (Sl 22,5); dela, digo, recebo, por benefício da tua misericórdia, algo com que de algum modo respiro, todas as vezes que a minha alma está triste e todas as vezes que me perturba (Sl 41,6). Estes pastos eu os conheço, e frequentei-os seguindo-te como pastor; mas mostra-me, peço-te, também os que não conheço.`
    },
    {
      n: 8,
      texto: `Há também outros pastores, que dizem ser teus companheiros e não o são, que têm os seus próprios rebanhos e os seus territórios cheios de pasto de morte, onde apascentam nem contigo nem por meio de ti; nos seus limites eu não entrei, nem me aproximei deles. São eles os que dizem: Eis aqui o Cristo, ei-lo ali (Mc 13,21), prometendo pastos mais ricos de sabedoria e de ciência; e acreditam neles, e muitos acorrem a eles, e eles os fazem filhos da geena duas vezes mais do que eles mesmos (Mt 23,15). Por que isso, senão porque ali não há meio-dia nem luz transparente, para que a verdade se conheça com clareza? E facilmente se aceita em seu lugar a falsidade, por causa da verossimilhança, que no escuro não se distingue facilmente do verdadeiro; sobretudo porque as águas roubadas são mais doces, e o pão escondido é mais saboroso (Pr 9,17). E por isso peço que me mostres onde apascentas, onde repousas ao meio-dia — isto é, às claras —, para que eu, seduzida, não comece a vaguear atrás dos rebanhos dos teus companheiros, assim como eles mesmos andam errantes, sem firmeza em nenhuma certeza da verdade, sempre aprendendo e nunca chegando ao conhecimento da verdade (2Tm 3,7). Isto diz a esposa por causa das doutrinas variadas e vãs dos filósofos e dos hereges.`
    },
    {
      n: 9,
      texto: `A mim, porém, parece que não só por causa delas, mas também por causa dos enganos dos poderes invisíveis, como são os espíritos sedutores, que estão de emboscada e preparam as suas flechas na aljava para ferir no escuro os retos de coração (Sl 10,3) — por causa destes, digo, e sobretudo, parece-me que também nós devemos desejar aquele meio-dia, para surpreendermos em plena luz as astúcias do diabo e distinguirmos com toda a facilidade do nosso anjo aquele anjo de Satanás que se transfigura em anjo de luz (2Cor 11,14). Pois não somos capazes de nos guardar do assalto e do demônio do meio-dia (Sl 90,6) senão com uma luz igualmente de meio-dia. E julgo que este demônio se chama do meio-dia porque há alguns do número dos malignos que, sendo noite — e noite perpétua — por culpa da sua vontade tenebrosa e obstinada, sabem, contudo, fingir-se dia para enganar; e não só dia, mas meio-dia; assim como o seu príncipe, não contente de ser igual a Deus, até se opõe a ele e se eleva acima de tudo o que se chama Deus ou recebe culto (2Ts 2,4). Por isso, se no coração daquele que algum demônio do meio-dia deste gênero tenha tomado para tentar não brilhar, vindo do alto, o verdadeiro meio-dia, que desmascare e denuncie o falso, não haverá como precaver-se; mas ele o tentará e o derrubará, sem dúvida, sob a aparência do bem, persuadindo o incauto e desprevenido a tomar o mal por bem. E então quem tenta aparece como meio-dia — isto é, como claridade maior —, quando exibe a imagem de um bem maior.`
    },
    {
      n: 10,
      texto: `Quantas vezes, por exemplo, sugeriu antecipar as vigílias, para depois zombar de quem cochilava durante o ofício solene dos irmãos? Quantas vezes sugeriu prolongar os jejuns, para tornar alguém tão inútil para o serviço divino quanto o deixava fraco? Quantas vezes, com inveja dos que progrediam bem nos mosteiros, persuadiu-os, a pretexto de maior pureza, a buscar o ermo; e os infelizes acabaram por conhecer quão verdadeira é a palavra que tinham lido em vão: Ai do que está só, porque, se cair, não terá quem o levante (Ecl 4,10)! Quantas vezes incitou ao trabalho manual mais do que era preciso, e deixou o monge, com as forças quebradas, incapaz para os demais exercícios da regra? A quantos persuadiu a dar muito ao exercício do corpo, que, segundo o Apóstolo, serve para pouco (1Tm 4,8), e lhes roubou a piedade? Enfim, vós mesmos vistes por experiência como alguns — digo-o para vergonha deles — que antes não se podiam conter (tal era o ímpeto de espírito com que se lançavam a tudo) chegaram depois a tanta moleza que, conforme a palavra do Apóstolo, tendo começado pelo espírito, acabam agora pela carne (Gl 3,3): que aliança vergonhosa fizeram com o próprio corpo, ao qual antes tinham declarado guerra cruel! Podes ver — que vergonha! — procurando sem pudor o supérfluo os que antes recusavam com a maior obstinação o necessário. Mas, se alguns porventura perseveram invencíveis na sua obstinação, jejuando sem discernimento e perturbando com uma singularidade que dá na vista aqueles com quem devem morar numa casa de um só costume (cf. Sl 67,7), não sei, francamente, se julgam conservar a piedade, quando me parece que gente assim a lançou para mais longe ainda. Pois os que, sábios aos seus próprios olhos, decidiram consigo não se submeter nem ao conselho nem ao preceito, vejam o que hão de responder — não a mim, mas àquele que diz: Resistir é como o pecado da adivinhação, e não querer obedecer é como o crime da idolatria (1Sm 15,23). E antes tinha dito que a obediência vale mais do que as vítimas, e escutar mais do que oferecer a gordura dos carneiros (1Sm 15,22) — isto é, a abstinência dos obstinados. Por isso o Senhor diz pelo Profeta: Acaso comerei eu a carne dos touros, ou beberei o sangue dos bodes? (Sl 49,13) — dando a entender que de modo algum lhe seriam agradáveis os jejuns dos soberbos ou dos impuros.`
    },
    {
      n: 11,
      texto: `Mas receio, na verdade, que, ao condenar os que exageram, pareçamos soltar as rédeas aos gulosos; e que estes ouçam, para seu perigo, o que se diz àqueles como remédio. Por isso, ouvi, uns e outros: há quatro gêneros de tentações, e a palavra do profeta os descreve para nós deste modo: A sua verdade te cercará como escudo; não temerás o temor da noite, nem a flecha que voa de dia, nem o negócio que anda nas trevas, nem o assalto e o demônio do meio-dia (Sl 90,5-6). Prestai atenção também vós, os outros: espero que isto seja proveitoso a todos. Todos nós que nos convertemos ao Senhor sentimos, e sentimos ainda, o que diz a santa Escritura: Filho, ao te aproximares do serviço de Deus, permanece no temor e prepara a tua alma para a tentação (Eclo 2,1). Assim, segundo o que ensina a experiência comum, o primeiro que agita os começos da nossa conversão é o temor, que logo à entrada nos incutem o horror de uma vida mais estreita e a austeridade de uma disciplina a que não estamos acostumados. E este se chama temor da noite, ou porque a noite, nas Escrituras, costuma significar as adversidades, ou porque aquilo por que nos dispomos a sofrer as adversidades ainda não está revelado. Pois, se brilhasse aquele dia em cuja luz víssemos juntos os trabalhos e os prêmios, não haveria temor nenhum de trabalho algum, pelo desejo dos prêmios, já que ficaria claro, em plena luz, que os sofrimentos do tempo presente não têm proporção com a glória futura que se há de revelar em nós (Rm 8,18). Mas agora, porque os prêmios estão escondidos aos nossos olhos, e por enquanto é noite deste lado, somos tentados, naturalmente, pelo temor da noite, e, pelos bens que não vemos, receamos suportar as adversidades presentes. Os que entram devem, pois, vigiar e orar antes de tudo contra esta primeira tentação, para que, surpreendidos de repente pela pusilanimidade de espírito e pela tempestade (Sl 54,9), não recuem — Deus nos livre! — do bem começado.`
    },
    {
      n: 12,
      texto: `Vencida esta tentação, armemo-nos também contra os louvores dos homens, que tiram a sua matéria sobretudo de uma vida louvável. De outro modo, ficaremos expostos à ferida da flecha que voa de dia, que é a vanglória. Pois a fama voa; e voa de dia, porque nasce das obras da luz. Se esta é afastada com um sopro, como brisa vã, resta que se ofereça algo mais sólido, das riquezas e das honras do mundo, para ver se quem não se importa com louvores deseja dignidades. E vê se não foi esta a ordem da tentação que se seguiu com o Senhor nosso: depois de lhe sugerirem o precipício por pura vaidade, mostraram-lhe e ofereceram-lhe todos os reinos do mundo (Mt 4,6.8). Tu, pois, a exemplo do Senhor, recusa também estas coisas. De outro modo, é inevitável que te enrede o negócio que anda nas trevas, que é a hipocrisia. Pois ela descende da ambição, e a sua morada é nas trevas: esconde o que é e finge o que não é. E negocia o tempo todo: conserva a aparência da piedade para se esconder (cf. 2Tm 3,5), reivindica para si a força dela e compra honras.`
    },
    {
      n: 13,
      texto: `A última tentação é o demônio do meio-dia, que costuma armar ciladas sobretudo aos perfeitos — aos que, como homens de virtude, venceram tudo: os prazeres, os favores, as honras. Pois que resta ainda ao tentador, com que possa combater abertamente contra gente assim? Vem, por isso, escondido, quem às claras não se atreve; e aquele que bem sabe, por experiência, ter horror a todo mal declarado, procura derrubá-lo com um falso bem. Mas os que podem dizer com o Apóstolo: Não ignoramos as suas astúcias (2Cor 2,11), quanto mais progridem, tanto mais cuidadosos são em guardar-se deste laço. Daí vem que Maria se perturba com a saudação do anjo (Lc 1,29), suspeitando, se não me engano, de alguma cilada; e Josué não acolhe o anjo amigo antes de saber que é amigo. Pois pergunta se é dos seus ou dos adversários (Js 5,13-15), como quem tem experiência das manhas do demônio do meio-dia. Também os apóstolos, certa vez, quando se afadigavam a remar, com o vento contrário a sacudir a barca, vendo o Senhor andar sobre o mar e julgando que era um fantasma, a ponto de gritarem de medo, não mostraram claramente que suspeitavam do demônio do meio-dia? E lembrai-vos da Escritura, que diz que foi na quarta vigília da noite que veio até eles andando sobre o mar. Tema-se, pois, esta tentação em quarto lugar, isto é, no último e mais alto; e quanto mais alguém se vir de pé no cume, tanto mais vigilante entenda que deve guardar-se do assalto e do demônio do meio-dia. E o verdadeiro meio-dia manifestou-se aos discípulos quando ouviram: Sou eu, não tenhais medo (Mt 14,25-27); e afastou-se deles a suspeita do falso. Oxalá também a nós, todas as vezes que a falsidade disfarçada tenta infiltrar-se, o verdadeiro meio-dia, vindo do alto, envie a sua luz e a sua verdade (Sl 42,3) para desmascará-la, e separe a luz das trevas (Gn 1,4), para que o profeta não nos censure como aos que fazem da luz trevas e das trevas luz (Is 5,20).`
    },
    {
      n: 14,
      texto: `Mais ainda: se a extensão do sermão não vos cansar, tentarei aplicar estas quatro tentações, pela sua ordem, ao próprio corpo de Cristo, que é a Igreja. E eis que o faço o mais brevemente que posso. Vede se a Igreja primitiva não foi primeiro invadida com demasiada violência pelo temor da noite. Pois era noite quando todo aquele que matava os santos julgava prestar culto a Deus (Jo 16,2). Vencida, porém, esta tentação e acalmada a tempestade, ela se tornou ilustre e, segundo a promessa que lhe fora feita, em pouco tempo foi posta como orgulho dos séculos (Is 60,15). E o inimigo, doído por ter sido frustrado, passou astutamente do temor da noite à flecha que voa de dia, e com ela feriu alguns da Igreja. E levantaram-se homens vãos, ávidos de glória, e quiseram fazer um nome para si (cf. Gn 11,4); e, saindo da Igreja (cf. 1Jo 2,19), afligiram por muito tempo a própria mãe com doutrinas diversas e perversas. Mas também esta peste foi repelida pela sabedoria dos santos, como a primeira pela paciência dos mártires.`
    },
    {
      n: 15,
      texto: `Eis os tempos de hoje: livres, pela misericórdia de Deus, de uma e de outra daquelas maldades, mas verdadeiramente imundos pelo negócio que anda nas trevas. Ai desta geração, por causa do fermento dos fariseus, que é a hipocrisia (Lc 12,1)! — se é que se deve chamar hipocrisia a uma coisa que já não consegue esconder-se, de tão abundante, nem o procura, de tão despudorada. Hoje uma podridão fétida se alastra por todo o corpo da Igreja; e quanto mais larga, mais sem esperança; e tanto mais perigosa quanto mais interna. Pois, se se levantasse um inimigo declarado, um herege, seria lançado fora e secaria (cf. Jo 15,6); se um inimigo violento, ela talvez se escondesse dele (Sl 54,13). Mas agora, a quem há de expulsar, ou de quem há de esconder-se? Todos são amigos, e todos inimigos; todos íntimos, e todos adversários; todos da casa, e nenhum pacífico; todos próximos, e todos buscam os próprios interesses (Fl 2,21). São ministros de Cristo, e servem ao Anticristo. Andam cobertos de honras, com os bens do Senhor, os que ao Senhor não prestam honra. Daí esse brilho de meretriz que vês todos os dias, essa roupa de comediante, esse aparato de rei. Daí o ouro nos freios, nas selas e nas esporas; e brilham mais as esporas que os altares. Daí as mesas esplêndidas de iguarias e de taças; daí as comilanças e as bebedeiras (Rm 13,13); daí a cítara, a lira e a flauta (Is 5,12); daí os lagares transbordando e as despensas cheias, que vertem de uma coisa para outra (Sl 143,13). Daí os tonéis de vinho temperado, daí as bolsas recheadas. É por coisas assim que querem ser, e são, prepostos das igrejas, deãos, arcediagos, bispos, arcebispos. Pois estes cargos não se obtêm pelo mérito, mas por aquele negócio que anda nas trevas.`
    },
    {
      n: 16,
      texto: `Foi predito há muito tempo, e agora chegou o tempo de se cumprir: Eis que na paz a minha amargura é amaríssima (Is 38,17). Amarga primeiro na morte dos mártires, mais amarga depois no combate com os hereges, amaríssima agora nos costumes dos da casa. Ela não pode nem afugentá-los nem fugir deles: tanto se fortaleceram e se multiplicaram sem conta (Sl 39,6). A chaga da Igreja é interna e incurável; e por isso na paz a sua amargura é amaríssima. Mas em que paz? Há paz, e não há paz (cf. Jr 6,14). Paz da parte dos pagãos, e paz da parte dos hereges; mas certamente não da parte dos filhos. Neste tempo, é esta a voz da que se lamenta: Criei filhos e os engrandeci, e eles me desprezaram (Is 1,2). Desprezaram-me e mancharam-me com uma vida torpe, com um lucro torpe, com um comércio torpe — enfim, com o negócio que anda nas trevas. Resta agora que surja do meio deles o demônio do meio-dia, para seduzir os que ainda restam em Cristo, permanecendo na sua simplicidade. Pois já engoliu os rios dos sábios e as torrentes dos poderosos, e confia que o Jordão lhe corra para dentro da boca (Jó 40,18) — isto é, os simples e humildes que há na Igreja. Pois ele é o Anticristo, que há de fingir-se não só dia, mas meio-dia, e se elevará acima de tudo o que se chama Deus ou recebe culto; mas o Senhor Jesus o matará com o sopro da sua boca e o destruirá com o esplendor da sua vinda (2Ts 2,4.8) — ele, o verdadeiro e eterno Meio-Dia, esposo e advogado da Igreja, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
