SERMOES.sermao({
  id: 'bernardo-cantico-58',
  colecao: 'bernardo-cantico',
  ordem: 58,
  numero: 'LVIII',
  titulo: 'De como o esposo exorta a esposa, isto é, os perfeitos, a governar os imperfeitos; e da poda dos vícios, para que as virtudes cresçam',
  fonte: 'Quomodo sponsus hortatur sponsam ad regimen imperfectorum',
  argumento: `O esposo, que há pouco proibia que acordassem a amada, agora a acorda: "Levanta-te, apressa-te, e vem". Não é inconstância: é a alternância, nesta vida, entre o santo repouso e a ação necessária. E ele não diz "vai", mas "vem": ela não é mandada sozinha, é conduzida. As vinhas que é preciso podar são as almas e as comunidades, e o convite é feito às almas mais perfeitas, chamadas por Deus, e não pela própria ambição, a governar os outros.

Há, porém, um tempo para a poda. O inverno foi o tempo da paixão: fazia frio, e Pedro, que cortou a orelha do servo, ouviu que guardasse a espada, porque não era tempo de podar. As chuvas más que encharcavam a terra são os gritos da multidão contra Cristo, a tagarelice dos filósofos, as doutrinas dos hereges, e até os preceitos de Moisés fora do seu tempo. As flores são a carne de Cristo ressuscitada e os primeiros que creram; a poda vem com a paz. E, para cada um, é sempre tempo de podar: os vícios não morrem, só se reprimem — "o jebuseu mora dentro das tuas fronteiras" —, e progride quem, ao examinar-se, acha o que censurar e o censura.

Tradução feita do texto latino de Migne (PL 183, 1055-1061).`,
  pontos: [
    {
      n: 1,
      texto: `Levanta-te, apressa-te, minha amiga, minha pomba, minha formosa, e vem (Ct 2,10). Quem diz isto? Sem dúvida, o esposo. E não é ele quem pouco antes proibia com tanto empenho que despertassem a amada? Como, pois, manda agora não só que se levante, mas até que se apresse? Vem-me à mente uma coisa semelhante do Evangelho. Naquela noite em que o Senhor foi entregue, depois de ter mandado aos discípulos que estavam com ele, cansados das longas vigílias, que dormissem enfim e descansassem, na mesma hora diz: Levantai-vos, vamos; eis que se aproxima aquele que me vai entregar (Mt 26,46). Agora também, do mesmo modo, quase no mesmo instante, proíbe que despertem a esposa e a desperta, dizendo: Levanta-te e vem. Que quer dizer, pois, esta mudança tão súbita de vontade ou de resolução? Pensaremos que o esposo agiu com leviandade, e quis antes uma coisa que logo depois não quis? De modo nenhum. Mas reconhecei aquelas alternâncias do santo repouso e da ação necessária que, se vos lembrais, vos recomendei atrás, e não uma só vez; e que nesta vida não há abundância de contemplação, nem repouso prolongado, quando a utilidade do ofício e do trabalho pressiona de modo mais urgente e insistente. O esposo, pois, segundo o seu costume, quando sente que a amada repousou um pouco no seu seio, não hesita em arrastá-la de novo para as coisas que pareceram mais úteis. Não, porém, contra a sua vontade: pois de modo nenhum faria ele o que proibiu que se fizesse; mas, para a esposa, ser arrastada pelo esposo é receber dele o desejo pelo qual é arrastada: o desejo das boas obras, o desejo de dar fruto para o esposo; pois para ela o viver é o esposo, e o morrer é lucro (cf. Fl 1,21).`
    },
    {
      n: 2,
      texto: `E é um desejo veemente, que a incita não só a levantar-se, mas a levantar-se depressa; pois tens assim: Levanta-te, apressa-te, e vem. E não pouco a conforta ouvir: Vem, e não: Vai; entendendo por isso que não tanto é enviada quanto conduzida, e que o esposo virá com ela. Pois que haveria de difícil para ela, tendo-o por companheiro? Põe-me junto de ti, diz, e lute contra mim a mão de quem quiser (Jó 17,3); e ainda: Ainda que eu ande no meio da sombra da morte, não temerei mal nenhum, porque tu estás comigo (Sl 22,4). Não é, pois, despertada contra a sua vontade, quando primeiro se faz que ela o queira; o que não é outra coisa senão a avidez de um santo ganho que lhe é infundida. É animada também para a obra que lhe é confiada, e a oportunidade do tempo a torna mais pronta. É tempo de agir, diz, ó esposa, porque passou o inverno, quando ninguém podia trabalhar. Também a chuva que, inundando, cobria a terra, impedia as culturas e matava as sementeiras ou impedia a semeadura — essa chuva, digo, escorreu, foi-se e retirou-se; apareceram as flores na nossa terra, anunciando sem dúvida que chegou a temperatura amena da primavera, a comodidade para trabalhar, a proximidade das colheitas e dos frutos. Depois acrescenta onde e em que se deve trabalhar primeiro: Chegou, diz, o tempo da poda (Ct 2,11-12). É levada, pois, a cultivar as vinhas; e, para que elas possam responder aos lavradores com frutos mais abundantes, é preciso, antes de tudo, lançar fora os sarmentos estéreis, cortar os nocivos, podar os supérfluos. Isto segundo a letra.`
    },
    {
      n: 3,
      texto: `Vejamos agora o que, sob esta figura como que histórica, se nos dá a entender espiritualmente. Que as vinhas são as almas ou as Igrejas, e qual a razão disto, já vos disse, e ouvistes, e não precisais de ouvi-lo de novo. Para as visitar, corrigir, instruir, salvar, é convidada, pois, a alma mais perfeita — contanto que lhe tenha cabido este ministério não pela sua ambição, mas chamada por Deus, como Aarão (cf. Hb 5,4). E que é o próprio convite, senão um íntimo estímulo da caridade, que nos incita piedosamente a zelar pela salvação dos irmãos, a zelar pela beleza da casa do Senhor, pelo aumento dos seus ganhos, pelo aumento dos frutos da sua justiça, pelo louvor e glória do seu nome? Todas as vezes, pois, que aquele que tem por ofício governar almas ou dedicar-se à pregação sentir o seu homem interior movido por tais afetos religiosos para com Deus, entenda que, sem dúvida, o esposo está presente, e que é convidado por ele para as vinhas. Para quê, senão para arrancar e destruir, edificar e plantar (cf. Jr 1,10)?`
    },
    {
      n: 4,
      texto: `Mas, como para esta obra, assim como para todas as coisas debaixo do céu, nem todo tempo serve e é apto (cf. Ecl 3,1), aquele que convida acrescenta que chegou o tempo da poda. Sabia que este tempo tinha chegado quem dizia: Eis agora o tempo favorável, eis agora o dia da salvação; não dando a ninguém motivo de escândalo, para que o nosso ministério não seja criticado (2Cor 6,2-3). Sem dúvida exortava a podar já e a cortar o que é vicioso e supérfluo, e enfim tudo o que pudesse ser tropeço e impedir o fruto da salvação, sabendo que chegara o tempo da poda. Por isso dizia também a um fiel cultivador das vinhas: Repreende, censura, exorta (2Tm 4,2) — indicando nas duas primeiras destas coisas a poda ou a extirpação, e na última a plantação. E isto disse o esposo pela boca de Paulo sobre o tempo de trabalhar. Mas ouve o que falou pela sua própria boca, sob outra figura e com outro nome, à esposa ainda nova, sobre a consideração dos tempos. Não dizeis vós, diz, que faltam quatro meses e vem a colheita? Eis que vos digo: Levantai os olhos e vede os campos, que já estão brancos para a colheita (Jo 4,35); e ainda: A messe é grande, e os operários são poucos: pedi ao Senhor da messe que mande operários para a sua messe (Mt 9,37-38). Assim, pois, como ali mostrava que chegara o tempo de ceifar as searas das almas, assim também aqui anuncia que chegou o tempo de podar as vinhas igualmente espirituais, isto é, as almas ou as Igrejas; querendo talvez distinguir, pela diversidade das palavras, uma coisa da outra, de modo que entendamos pelas messes os povos, e pelas vinhas as comunidades de santos que vivem juntos.`
    },
    {
      n: 5,
      texto: `O tempo de inverno, que diz ter passado, parece-me designar aquele tempo em que o Senhor Jesus já não andava abertamente entre os judeus, porque tinham conspirado contra ele, querendo matá-lo. Por isso dizia a alguns: O meu tempo ainda não chegou; mas o vosso tempo está sempre pronto; e ainda: Subi vós a esta festa; eu não subo (Jo 7,1-10). Contudo, depois subiu também ele, não abertamente, mas como que às escondidas. Desde então, pois, até a vinda do Espírito Santo, pela qual os corações entorpecidos dos fiéis se aqueceram de novo como por um fogo, que o Senhor mandou à terra precisamente para isto (cf. Lc 12,49), foi inverno. Negarás que era inverno quando Pedro estava sentado junto às brasas, com o coração não menos gelado que o corpo? Enfim: Fazia frio, diz (Jo 18,18). Grande frio, na verdade, apertara o coração do que negava. E não admira, pois o fogo lhe tinha sido tirado. Pois pouco antes ardia de um zelo nada pequeno, estando ainda perto do fogo, ele que, desembainhando a espada para não perder o fogo, cortou a orelha do servo. Mas não era tempo de poda; e por isso ouve: Mete a tua espada no seu lugar. Pois era a hora e o poder das trevas; e qualquer dos discípulos que então levantasse a espada, de ferro ou da palavra, ou havia de ser abatido pelo ferro, sem ganhar ninguém nem produzir fruto nenhum, ou então havia de ser obrigado a negar pela espada do medo; e assim pereceria mais ainda ele mesmo, segundo a palavra do Senhor que ele logo acrescentou, dizendo: Todo aquele que tomar a espada perecerá pela espada (Mt 26,51-52). Pois qual dos outros ficaria de pé sem medo diante da imagem temível da morte, quando o próprio chefe tremia e cedia, ele que fora premunido pela voz confortadora do seu comandante e prevenido para confortar os outros (cf. Lc 22,32)?`
    },
    {
      n: 6,
      texto: `Mas nem ele nem os outros se tinham ainda revestido da força do alto; e por isso não era seguro para eles sair às vinhas, empunhar o sacho da língua e, com a espada do Espírito, podar as videiras e limpar os ramos, para que dessem mais fruto (cf. Jo 15,2). Enfim, o próprio Senhor calava-se na paixão e, interrogado sobre muitas coisas, não respondia (Mt 27,12), feito, segundo o Profeta, como homem que não ouve e não tem na boca réplica nenhuma (Sl 37,15). E dizia: Se eu vos disser, não me acreditareis; e, se vos interrogar, não me respondereis (Lc 22,67-68) — sabendo que ainda não chegara o tempo da poda, e que a sua vinha de modo nenhum corresponderia aos trabalhos empregados, isto é, não daria fruto algum nem de fé nem de boa obra. Por quê? Porque era inverno nos corações dos infiéis, e umas chuvas invernais de maldade tinham ocupado a terra, mais prontas a sufocar as sementes da palavra lançadas do que a fazê-las crescer, e a frustrar todo o trabalho que se empregasse no cultivo das vinhas.`
    },
    {
      n: 7,
      texto: `Que chuvas pensais que digo agora? Estas que vemos as nuvens, correndo pelo ar, espalharem sobre a terra com vento tempestuoso? Não é assim. Mas as que levam da terra para o ar os homens de espírito turbulento, que põem a boca contra o céu, e cuja língua percorre a terra (cf. Sl 72,9) e, como chuva amaríssima, torna a própria terra pantanosa e estéril e inútil para as plantas e as sementeiras — não, certamente, estas visíveis e corporais, dadas para os nossos usos corporais, das quais Deus não se ocupa, como não se ocupa dos bois (cf. 1Cor 9,9). Mas para quais? Sem dúvida, para as que a mão de Deus, e não a do homem, semeou e plantou; que podiam germinar ou enraizar-se na fé e na caridade e produzir frutos de salvação, se fossem regadas com chuvas boas e oportunas. Enfim, são as almas pelas quais Cristo morreu. Ai das nuvens que fazem chover sobre elas tais chuvas, que produzem lama e não fruto! Pois, assim como há árvores boas e más, que dão frutos diferentes conforme a sua diferença — as boas, bons; as más, maus —, assim julgo que há nuvens boas, que fazem chover chuvas boas, e más, que fazem chover chuvas más. E vê se não nos indicou talvez esta diferença de nuvens e chuvas aquele que dizia: Mandarei às minhas nuvens que não façam chover sobre ela — sem dúvida, sobre a vinha (Is 5,6). Por que pensas que acrescentou expressamente "minhas", senão porque há também nuvens más, que não são dele? Fora, fora, dizem, crucifica-o (Jo 19,15)! Ó nuvens violentas e turvas! Ó chuva tempestuosa! Ó torrente de iniquidade, mais própria para devastar do que para fecundar! E não foi menos má nem menos amarga, ainda que caísse com menos ímpeto, aquela chuva que se seguiu: Salvou os outros, e não pode salvar-se a si mesmo. O Cristo, rei de Israel, desça agora da cruz, e creremos nele (Mt 27,42). A loquacidade cheia de vento dos filósofos não é chuva boa, pois trouxe à terra antes esterilidade que fertilidade. Muito mais as doutrinas perversas dos hereges são chuvas más, que em lugar de frutos produzem espinhos e abrolhos. Chuvas más são também as tradições dos fariseus, que o Salvador censurou; e eles mesmos, nuvens más. E, que não julgues que faço injúria a Moisés — pois aquela é uma nuvem boa —, não direi que é bom tudo o que também ela fez chover, para não contradizer aquele que diz: Dei-lhes — isto é, aos judeus, sem dúvida por meio de Moisés — preceitos que não eram bons, e normas pelas quais não viveriam (Ez 20,25). Aquela observância literal do sábado, por exemplo, que anuncia o repouso, mas não o dá; o rito dos sacrifícios que se mandava; a proibição de comer carne de porco e algumas outras coisas semelhantes, que Moisés julga impuras — tudo isto é chuva que desce daquela nuvem, mas não quero que desça algum dia no meu campo ou no meu jardim. Terá sido boa no seu tempo; se vier fora do tempo, já não a julgo boa. Toda chuva, ainda que mansa e caindo mansamente, se for fora de tempo, é incômoda.`
    },
    {
      n: 8,
      texto: `Enquanto, pois, estas águas pestilentas ocuparam a terra e prevaleceram sobre ela, as vinhas não tiveram o seu tempo, nem houve razão para convidar a esposa a podá-las. Mas, quando elas escorreram, apareceu a terra seca, e nela apareceram as flores, significando que chegara o tempo da poda. Perguntas quando foi isto? Quando pensas, senão quando a carne de Cristo refloresceu na ressurreição? E esta é a primeira e a maior flor que apareceu na nossa terra. Pois Cristo é as primícias dos que dormem (1Cor 15,20). Ele mesmo, digo, a flor do campo e o lírio dos vales (Ct 2,1), Jesus, que se julgava filho de José (Lc 3,23), de Nazaré — nome que quer dizer flor. Esta flor, pois, apareceu primeiro, mas não sozinha. Pois também muitos corpos de santos que dormiam ressuscitaram com ele, e apareceram ao mesmo tempo na nossa terra como flores luminosíssimas. Enfim, vieram à cidade santa e apareceram a muitos (Mt 27,52-53). Flores foram também os primeiros do povo que creram, primícias dos santos. Flores, os seus milagres, que, à maneira de flores, produziam o fruto da fé. Pois, depois que aquela chuva da incredulidade se foi e se retirou um pouco, ou em parte, logo se seguiu a chuva generosa que Deus reservou para a sua herança (cf. Sl 67,10), e começaram a aparecer as flores. O Senhor deu a sua benignidade, e a nossa terra deu as suas flores (cf. Sl 84,13), de modo que num dia creram três mil do povo, e noutro cinco mil (At 2,41; 4,4): tanto cresceu em pouco tempo o número das flores, isto é, a multidão dos que creram. E a geada da maldade não pôde prevalecer contra as flores que apareciam, nem roubar, como costuma, o fruto da vida que elas prometiam.`
    },
    {
      n: 9,
      texto: `Pois, revestidos da força do alto todos os que tinham crido, levantaram-se entre eles homens que desprezaram as ameaças dos homens, fortes na fé. Sofreram, é verdade, muitíssimos opositores; mas não cederam nem fugiram de fazer e de anunciar as obras de Deus. Pois, segundo aquilo do salmo, entendido espiritualmente: Semearam campos e plantaram vinhas, e colheram o fruto do seu produto (Sl 106,37). Com o passar do tempo, a tempestade acalmou-se e, restituída a paz à terra, as vinhas cresceram, propagaram-se, estenderam-se e multiplicaram-se sem conta. E só então a esposa é convidada às vinhas — não para plantar, mas para podar o que já estava plantado. E com oportunidade: pois esta obra requeria o tempo da paz. Pois quando seria possível fazê-la no tempo da perseguição? De outro modo, tomar nas mãos espadas de dois gumes, exercer a vingança sobre as nações e os castigos sobre os povos, prender os seus reis com grilhões e os seus nobres com algemas de ferro, executar neles o julgamento escrito (Sl 149,6-9) — pois isto é podar as vinhas —, todas estas coisas, digo, mal se fazem em paz, mesmo no tempo da paz. E basta disto.`
    },
    {
      n: 10,
      texto: `O sermão poderia até terminar aqui, se primeiro eu tivesse advertido cada um de vós, segundo o meu costume, a respeito da sua vinha. Pois quem cortou de si tão perfeitamente tudo o que é supérfluo que julgue não ter nada que mereça poda? Crede-me: o que foi podado torna a brotar, o que foi expulso volta, o que foi apagado se reacende, o que foi adormecido desperta de novo. É pouco, pois, ter podado uma vez; é preciso podar muitas vezes, ou antes, se possível, sempre; porque, se não fechas os olhos, sempre achas o que é preciso podar. Por mais que tenhas progredido, permanecendo neste corpo, enganas-te se julgas que os vícios estão mortos, e não antes reprimidos. Queiras ou não, o jebuseu habita dentro das tuas fronteiras (cf. Jz 1,21): pode ser subjugado, mas não exterminado. Sei, diz, que o bem não habita em mim. É pouco, se não confessar também que o mal está nele. Pois diz: Não faço o que quero, mas o que detesto, isso faço. E, se faço o que detesto, já não sou eu que o faço, mas o pecado que habita em mim (Rm 7,18-20). Ou, pois, te preferes ao Apóstolo, se ousas — pois esta voz é dele —, ou confessa com ele que também tu não estás livre de vícios. Enfim, a virtude está no meio dos vícios; e por isso precisas não só de poda diligente, mas também de circuncisão. De outro modo, é de temer que ela, sem que o saibas, vá definhando pouco a pouco, lambida, ou antes roída, de todos os lados pelos vícios; ou que, se estes crescerem por cima dela, seja sufocada. Num perigo tão grande, só há um conselho: observar com cuidado e, logo que apareçam as cabeças dos que renascem, cortá-las com pronta severidade. A virtude não pode crescer juntamente com os vícios. Para que ela tenha vigor, pois, não se deixe que eles cresçam. Tira o supérfluo, e brota o que é salutar. Tudo o que tiras à cobiça acrescenta-se à utilidade. Dediquemo-nos à poda. Pode-se a cobiça, para que a virtude se fortaleça.`
    },
    {
      n: 11,
      texto: `Para nós, irmãos, é sempre tempo de poda, como ela é sempre necessária. Pois confio que para nós o inverno já passou. Sabeis de que inverno falo? Daquele temor que não está na caridade, que inicia todos na sabedoria, mas não leva ninguém à perfeição; porque a caridade, sobrevindo, o expulsa, como o verão expulsa o inverno. Pois o verão é a caridade; e, se ela já veio — ou antes, porque veio, como é justo que eu pense de vós —, é necessário que tenha secado toda chuva de inverno, isto é, toda lágrima de angústia que antes arrancavam a amarga lembrança do pecado e o temor do juízo. Assim — o que digo sem hesitar, se não de todos vós, sem dúvida da maioria —, esta chuva já se foi e se retirou; pois aparecem também as flores, sinais de uma chuva mais suave. Também o verão tem as suas chuvas, suaves e abundantes. Que há de mais doce do que as lágrimas da caridade? Pois a caridade chora, mas de amor, não de tristeza; chora de desejo, chora com os que choram. Não duvido de que com tal chuva sejam regadas com mais abundância as obras da vossa obediência, que contemplo com alegria: não enegrecidas pela murmuração, não obscurecidas pela tristeza, mas alegres e floridas com uma certa alegria espiritual. São assim, como se trouxésseis sempre flores nas mãos.`
    },
    {
      n: 12,
      texto: `Se, pois, o inverno passou, a chuva se foi e se retirou; se, enfim, apareceram as flores na nossa terra, e logo uma espécie de temperatura primaveril da graça espiritual anuncia o tempo da poda, que resta senão que daqui em diante nos entreguemos todos a esta obra tão santa, tão necessária? Examinemos, segundo o profeta, os nossos caminhos (Lm 3,40) e os nossos afetos, e julgue cada um ter progredido, não quando não achar nada que censurar, mas quando censurar o que achar. Não te examinaste em vão, se percebeste que é preciso examinar-te de novo; e o teu exame não te enganou todas as vezes que julgaste dever repeti-lo. E, se fazes isto todas as vezes que é preciso, então o fazes sempre. Lembra-te, pois, de que sempre precisas do auxílio do alto e da misericórdia do esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
