SERMOES.sermao({
  id: 'bernardo-cantico-27',
  colecao: 'bernardo-cantico',
  ordem: 27,
  numero: 'XXVII',
  titulo: 'Do adorno da esposa, e de como a alma santa se chama céu',
  fonte: 'De ornatu sponsae, et qualiter anima sancta in coelum dicatur',
  argumento: `Enterrado o irmão, Bernardo volta ao trabalho: não convém chorar por muito tempo a quem se alegra. E explica enfim as peles de Salomão. O Salomão que interessa não é o rei, mas o «maior que Salomão», que estendeu o céu como uma pele — e o céu que se compara à esposa não é o dos astros, mas o céu do céu, o dos nove coros angélicos.

Daí a tese central do sermão: toda alma santa é um céu. Tem por sol a inteligência, por lua a fé, por estrelas as virtudes, que brilham de noite e se escondem de dia. E o tamanho de uma alma mede-se pela sua caridade: a que tem muita é grande, a que tem pouca é pequena, a que não tem nenhuma é nada. Termina com uma sequência de contrastes — tenda de Cedar e santuário de Deus, casa de barro e sala régia — que resume a esposa, negra e formosa ao mesmo tempo.

Tradução feita do texto latino de Migne (PL 183, 912-921).`,
  pontos: [
    {
      n: 1,
      texto: `Tendo acompanhado com os devidos ofícios de humanidade o amigo que voltava à pátria, volto, irmãos, ao propósito de edificar, que tinha interrompido. Pois não convém chorar por muito tempo a quem se alegra, e é despropositado derramar muitas lágrimas sobre quem está sentado ao banquete. E, se choramos as nossas aflições, nem isso convém fazer demais, para não parecer que não tanto o amávamos quanto buscávamos nele as nossas conveniências. Que a alegria do amado tempere a tristeza dos que ficaram desolados; e que se nos torne mais suportável não estar ele conosco, porque está com Deus. Confiado, pois, nas vossas orações, quero trazer à luz, se puder, o que quer que seja que sinto escondido naquelas peles que se apresentaram como exemplo da formosura da esposa. Isto, se vos lembrais, foi tocado, mas ficou por examinar; o que se examinou e explicou foi como é negra como as tendas de Cedar. Como é, então, formosa como as peles de Salomão (Ct 1,4) — como se Salomão, em toda a sua glória, tivesse alguma coisa à altura da formosura da esposa e da glória do seu adorno? Se disséssemos que estas peles, sejam elas quais forem, se referem não à formosura da esposa, mas antes à negrura, como as tendas de Cedar, talvez coubesse, e não faltaria com que mostrar que se ajusta — como também mostraremos. Mas, se julgamos que a beleza de quaisquer peles se deve comparar ao esplendor da esposa, aqui precisamos mesmo da ajuda daquele a cuja porta batestes, para podermos abrir dignamente este mistério. Pois que coisa, das que brilham à vista, não parecerá vil e feia a quem julga com retidão, se for comparada à beleza interior de uma alma santa? Que coisa assim mostra em si a figura deste mundo, que passa (1Cor 7,31), capaz de igualar a beleza de uma alma que, despida da velhice do homem terreno, se revestiu da beleza daquele que vem do céu — ornada, em vez de colares, dos melhores costumes, mais pura e mais alta que o próprio céu, mais resplandecente que o sol? Não olhes, pois, para este Salomão, quando quiseres investigar a que peles a esposa se gloria de ser semelhante em formosura.`
    },
    {
      n: 2,
      texto: `Que quer dizer, então: Sou formosa como as peles de Salomão? Uma coisa grande e admirável, a meu ver — contanto que aqui olhemos não para aquele, mas para este de quem se diz: Eis aqui alguém maior que Salomão (Mt 12,42). Pois este é tanto o meu Salomão que não só se chama pacífico — que é o que quer dizer Salomão —, mas a própria paz, como testemunha Paulo: ele é a nossa paz (Ef 2,14). Junto deste Salomão não duvido que se possa achar algo que não hesitaria em comparar à formosura da esposa. E, a respeito das suas peles em particular, repara no Salmo: Estendes o céu como uma pele (Sl 103,2). Não foi aquele Salomão, por mais sábio e poderoso que fosse, que estendeu o céu como uma pele, mas este, que não é tanto sábio quanto a própria Sabedoria: foi ele que o estendeu e o criou. Pois é deste, e não daquele, a voz que diz: Quando ele preparava os céus — o Deus Pai, sem dúvida —, eu estava lá. Estava lá, sem dúvida, junto de quem preparava os céus, o seu poder e a sua sabedoria. E não penses que estava lá ociosa, como só para ver, porque disse «eu estava lá» e não «eu preparava». Olha um pouco mais abaixo e acharás que acrescenta claramente: Eu estava com ele, compondo todas as coisas (Pr 8,27-30). Enfim, diz: Tudo o que o Pai faz, também o Filho o faz do mesmo modo (Jo 5,19). Também ele, pois, estendeu o céu como uma pele. Belíssima pele, que, à maneira de uma grande tenda, cobre toda a face da terra e deleita a vista dos homens com a variedade tão vistosa do sol, da lua e das estrelas. Que há de mais formoso do que esta pele? Que há de mais ornado do que o céu? E, contudo, nem mesmo ele se pode comparar de modo algum à glória e à formosura da esposa: fica aquém justamente porque também a sua figura passa, sendo corporal e sujeita aos sentidos do corpo. Pois as coisas que se veem são temporais; as que não se veem são eternas (2Cor 4,18).`
    },
    {
      n: 3,
      texto: `Mas a esposa tem uma beleza racional e uma figura espiritual, e esta é eterna, porque é imagem da eternidade. A sua beleza, por exemplo, é a caridade, e a caridade, como ledes, nunca acaba (1Cor 13,8). É também a justiça: E a sua justiça, diz, permanece pelos séculos dos séculos (Sl 111,3). É ainda a paciência; e ledes igualmente que a paciência dos pobres não perecerá para sempre (Sl 9,19). E a pobreza voluntária? E a humildade? Não merece uma o reino eterno (Mt 5,3), e a outra, igualmente, uma exaltação eterna? (Lc 14,11) Para lá tende também o santo temor do Senhor, que permanece pelos séculos dos séculos (Sl 18,10). Assim a prudência, assim a temperança, assim a fortaleza e as demais virtudes, que são senão pérolas no adorno da esposa, a brilhar com um esplendor perpétuo? Perpétuo, digo, porque são o assento e o fundamento da perpetuidade. Pois na alma não há lugar para a vida perpétua e bem-aventurada senão por meio das virtudes, postas de permeio. Por isso o Profeta diz a Deus, que é a vida bem-aventurada: A justiça e o juízo são o preparo do teu trono (Sl 88,15). E o Apóstolo diz que Cristo habita nos nossos corações — não de qualquer modo, mas expressamente pela fé (Ef 3,17). Também quando o Senhor ia sentar-se sobre o jumentinho, os discípulos estenderam por baixo as suas vestes (Mt 21,7-8), dando a entender que o Salvador, ou a salvação, de modo nenhum se assenta numa alma nua, que não encontre vestida da doutrina e dos costumes dos apóstolos. E por isso a Igreja, que tem a promessa da felicidade futura, cuida entretanto de se preparar e de se adornar com veste dourada, envolta na variedade (Sl 44,10) das graças e das virtudes, para ser achada digna e capaz da plenitude da graça.`
    },
    {
      n: 4,
      texto: `A esta variedade espiritual tão bela, que ela entretanto recebeu da primeira veste, como que numa veste da sua santificação, eu de modo algum compararia em formosura este céu visível e corporal, ainda que no seu gênero seja belíssimo pela variedade dos astros. Mas há um céu do céu, de que diz o Profeta: Cantai ao Senhor, que sobe acima do céu do céu, para o oriente (Sl 67,33-34). E este céu é intelectual e espiritual; e aquele que fez os céus com inteligência (Sl 135,5) o criou e o estabeleceu para sempre, e nele habita. E não penses que a devoção da esposa fica aquém daquele céu onde sabe que habita o amado: pois onde está o seu tesouro, aí está também o seu coração (Mt 6,21). Imita os que estão diante do rosto por que suspira; e, não podendo por ora juntar-se a eles pela visão, procura conformar-se a eles pela vida, clamando mais com os costumes do que com a voz: Senhor, amei a beleza da tua casa e o lugar onde habita a tua glória (Sl 25,8).`
    },
    {
      n: 5,
      texto: `E não julga de modo algum indigno de si tomar deste céu a sua comparação. Este céu está estendido como uma pele — não pelos espaços dos lugares, mas pelos afetos das almas —, e está ornado de obras admiráveis e variadas do artífice. E as suas divisões não são de cores, mas de bem-aventuranças. Pois a uns constituiu anjos; a outros, arcanjos; a outros, virtudes; a outros, dominações; a outros, principados; a outros, potestades; a outros, tronos; a outros, querubins; e a outros, serafins. Assim é estrelado este céu, assim é pintada esta pele. Esta é uma das peles do meu Salomão, e a principal em todo o adorno da sua glória multiforme. E esta grande pele contém em si muitíssimas outras peles de Salomão, pois cada bem-aventurado e cada santo que ali está é também uma pele de Salomão. São bondosos e estendidos na caridade, chegando até nós, a quem não invejam a glória que têm, mas a desejam para nós; de modo que, por causa disso, não lhes pesa demorar-se junto de nós, atentos a nós e cuidando de nós — todos espíritos servidores, enviados para servir por causa dos que hão de receber a herança da salvação (Hb 1,14). Por isso, assim como toda aquela multidão reunida dos bem-aventurados se chama, no singular, céu do céu, assim também, por causa de cada um deles, que são céus, se chamam céus dos céus; e a cada um se refere o que se diz: Estendes o céu como uma pele (Sl 103,2). Já vistes, creio, que peles são essas, e de que Salomão, de cuja semelhança a esposa se gloria.`
    },
    {
      n: 6,
      texto: `Contemplai agora a glória daquela que se compara ao céu — e àquele céu que é tanto mais glorioso quanto mais divino. E não é sem razão que toma a comparação de onde tira a origem. Pois, se pelo corpo, que tem da terra, se compara às tendas de Cedar, por que não se há de gloriar, pela alma, que é do céu, de ser igualmente semelhante ao céu — sobretudo quando a vida testemunha a origem, a dignidade da natureza e a pátria? Adora e serve a um só Deus, como os anjos; ama a Cristo acima de tudo, como os anjos; é casta como os anjos — e isto numa carne de pecado e num corpo frágil, coisa que os anjos não têm; busca, enfim, e saboreia o que está junto deles, não o que está sobre a terra. Que marca mais evidente de uma origem celeste do que conservar a semelhança inata mesmo na região da dessemelhança; do que um exilado tomar para si, na terra, a glória da vida celibatária; do que viver como anjo, enfim, num corpo quase animal? Estas coisas são de um poder celeste, não terreno, e mostram claramente que é do céu a alma que as pode. Mas ouve ainda com mais clareza: Vi a cidade santa, a nova Jerusalém, que descia do céu, da parte de Deus, preparada como uma esposa adornada para o seu marido; e acrescentou: E ouvi uma grande voz, vinda do trono, que dizia: Eis a tenda de Deus com os homens, e ele habitará com eles (Ap 21,2-3). Para quê? Creio que para ganhar para si uma esposa dentre os homens. Coisa admirável! Vinha buscar a esposa, e não vinha sem esposa. Procurava uma esposa, e a esposa estava com ele. Eram duas, então? De modo nenhum! Pois uma só é a minha pomba, diz ele (Ct 6,8). Mas, assim como quis fazer de vários rebanhos de ovelhas um só, para que haja um só rebanho e um só pastor (Jo 10,16), assim também, tendo desde o princípio por esposa, unida a si, a multidão dos anjos, aprouve-lhe convocar também dentre os homens uma Igreja e uni-la à que é do céu, para que haja uma só esposa e um só esposo. Com esta que se lhe juntou, aquela ficou completa, não duplicada; e reconhece que se disse dela: Uma só é a minha perfeita (Ct 6,8). E o que as faz uma só é a conformidade: agora, numa devoção semelhante; depois, também numa glória igual.`
    },
    {
      n: 7,
      texto: `Tens, pois, os dois vindos do céu: o esposo, que é Jesus, e a esposa, que é Jerusalém. E ele, para ser visto, esvaziou-se a si mesmo, tomando a forma de servo, tornando-se semelhante aos homens e reconhecido em aspecto como homem (Fl 2,7). Mas ela — em que forma, pensamos, em que figura ou em que aspecto a viu descer aquele que a viu? Porventura na multidão dos anjos, que viu a descer e a subir sobre o Filho do homem? (Jo 1,51) Mas dizemos melhor que viu a esposa quando viu o Verbo na carne, reconhecendo dois numa só carne. Pois, quando aquele santo Emanuel trouxe à terra o magistério da disciplina celeste; quando, por ele e nele, nos foi dada a conhecer uma imagem visível daquela Jerusalém do alto, que é a nossa mãe (Gl 4,26), e da sua beleza — que outra coisa vimos senão a esposa no esposo, admirando um só e mesmo Senhor da glória como esposo coroado e como esposa adornada com as suas joias (Is 61,10)? Aquele que desceu é, pois, o mesmo que subiu (Ef 4,10), para que ninguém suba ao céu senão aquele que desceu do céu (Jo 3,13): um só e mesmo Senhor, esposo na cabeça e esposa no corpo. E não foi em vão que o homem celeste foi visto na terra, pois dos terrenos fez muitíssimos celestes, semelhantes a si, para que se cumpra o que se lê: Qual é o celeste, tais são também os celestes (1Cor 15,48). Desde então, pois, vive-se na terra ao modo dos celestes: à semelhança daquela criatura bem-aventurada do alto, também esta — que veio dos confins da terra para ouvir a sabedoria de Salomão — se une com amor casto ao marido celeste; ainda não, como aquela, unida pela visão, mas desposada pela fé, segundo a promessa de Deus, que diz pelo profeta: Eu te desposarei comigo na misericórdia e nas compaixões, e te desposarei comigo na fidelidade (Os 2,19-20). Por isso se esforça por conformar-se cada vez mais à forma que veio do céu, aprendendo dela a ser modesta e sóbria, a ser pura e santa, a ser paciente e compassiva e, enfim, a ser mansa e humilde de coração. E por isso procura, com costumes assim, agradar mesmo de longe àquele que os anjos desejam contemplar (1Pd 1,12); para que, ardendo de um desejo angélico, prove que é concidadã dos santos e da casa de Deus (Ef 2,19), prove que é amada, prove que é esposa.`
    },
    {
      n: 8,
      texto: `Eu penso que toda alma assim não só é celeste pela origem, mas pode com razão chamar-se o próprio céu, pela imitação. E mostra claramente que a sua origem é de fato dos céus quando a sua vida está nos céus (Fl 3,20). Uma alma santa é, pois, um céu: tem por sol a inteligência, por lua a fé, por astros as virtudes. Ou então: o sol é o zelo da justiça, ou a caridade ardente; e a lua, a continência. Pois, assim como a claridade da lua, segundo dizem, só vem do sol, assim também sem a caridade ou a justiça a continência não tem mérito nenhum. Daí dizer o Sábio: Como é bela uma geração casta com caridade! (Sb 4,1) E não me arrependo de ter chamado estrelas às virtudes, ao considerar como a comparação se ajusta. Pois, assim como as estrelas brilham de noite e se escondem de dia, assim também a verdadeira virtude, que muitas vezes não aparece na prosperidade, sobressai na adversidade. Aquilo é cautela; isto, necessidade. A virtude é, pois, um astro, e o homem de virtude, um céu. A não ser que alguém, ao ler que Deus disse pelo profeta — O céu é o meu trono (Is 66,1) —, julgue que se deve entender este céu que gira e se vê, e não antes aquele de que a Escritura fala mais claramente noutro lugar: A alma do justo é o trono da sabedoria. Mas quem entende, pela doutrina do Salvador, que Deus é espírito e deve ser adorado em espírito (Jo 4,24), também não hesita em lhe atribuir um trono espiritual. Eu o faria com confiança, e não menos no espírito do homem justo do que no espírito angélico. Confirma-me neste sentido, sobretudo, aquela promessa fiel do Filho: Eu e o Pai viremos a ele — isto é, ao homem santo — e faremos nele a nossa morada (Jo 14,23). E creio que o Profeta não falou de outro céu quando disse: Tu, porém, habitas no santo, ó louvor de Israel (Sl 21,4). E o Apóstolo diz claramente que Cristo habita pela fé nos nossos corações (Ef 3,17).`
    },
    {
      n: 9,
      texto: `E não é de admirar que o Senhor Jesus habite de bom grado neste céu, que ele — não como os outros — não só mandou que se fizesse, mas lutou para o conquistar e morreu para o redimir. Por isso, depois do trabalho, alcançado o seu desejo, diz: Este é o meu repouso pelos séculos dos séculos; aqui habitarei, porque o escolhi (Sl 131,14). E feliz aquela a quem se diz: Vem, minha escolhida, e porei em ti o meu trono. Por que estás triste agora, minha alma, e por que me perturbas? (Sl 41,6) Pensas que também tu acharás em ti um lugar para o Senhor? (Sl 131,5) E que lugar temos em nós digno desta glória, suficiente para esta majestade? Quem me dera merecer ao menos adorar no lugar onde os seus pés pousaram! (Sl 131,7) Quem me dera ao menos seguir de perto as pegadas de alguma alma santa que ele escolheu para sua morada! Contudo, se ele se dignar embeber também a minha alma com a unção da sua misericórdia e estendê-la assim como uma pele — que, quando se unge, se alarga —, para que também eu possa dizer: Corri o caminho dos teus mandamentos, quando dilataste o meu coração (Sl 118,32), talvez também eu possa mostrar em mim mesmo, se não uma grande sala mobiliada onde ele se ponha à mesa com os seus discípulos (Lc 22,12), ao menos um lugar onde reclinar a cabeça (Mt 8,20). De longe olho para cima, para aqueles bem-aventurados de quem se diz: Habitarei neles e andarei entre eles (2Cor 6,16).`
    },
    {
      n: 10,
      texto: `Ó que largueza tem aquela alma, e que prerrogativa de méritos, que é achada digna de receber em si a presença divina e capaz de a conter! E que dizer daquela em que há até espaçosas galerias para a majestade passear? Não está, decerto, enredada em causas de tribunal nem em cuidados do mundo, nem entregue ao ventre e à luxúria; nem é curiosa de espetáculos, nem ávida de mandar, nem inchada pelo mando. Pois é preciso, primeiro, que a alma esteja vazia de tudo isso, para se tornar céu e morada de Deus. De outro modo, como poderá estar livre e ver que ele é Deus? (Sl 45,11) E não se deve de modo nenhum dar lugar ao ódio, à inveja ou ao rancor, porque na alma malévola não entrará a sabedoria (Sb 1,4). Depois, é preciso que ela cresça e se alargue, para ser capaz de Deus. E a sua largueza é o seu amor, como diz o Apóstolo: Alargai-vos na caridade (2Cor 6,13). Pois, embora a alma, sendo espírito, não admita grandeza corporal, a graça lhe dá o que a natureza lhe negou. Cresce e se estende, mas espiritualmente; cresce não em substância, mas em virtude; cresce também em glória; cresce para ser templo santo no Senhor (Ef 2,21); cresce, enfim, e progride até o homem perfeito, à medida da idade da plenitude de Cristo (Ef 4,13). Avalie-se, pois, o tamanho de cada alma pela medida da caridade que tem: a que tem muita caridade é grande; a que tem pouca, pequena; e a que não tem nenhuma é nada, como diz Paulo: Se eu não tiver caridade, nada sou (1Cor 13,2). E, se começar a ter um pouco, por pequeno que seja — de modo que cuide ao menos de amar os que a amam e de saudar os seus irmãos e os que a saúdam —, já diria que essa alma é alguma coisa, pois guarda ao menos, no dar e no receber, a caridade da convivência. Mas, segundo a palavra do Senhor, que faz ela de mais? (Mt 5,47) Não teria, pois, por larga nem por grande, mas antes por estreita e pequena, a alma que eu soubesse ter tão pouca caridade.`
    },
    {
      n: 11,
      texto: `Mas, se crescer e progredir de modo que, passando o limite deste amor estreito e interesseiro, alcance com toda a liberdade do espírito os largos confins da bondade gratuita, e cuide de se estender, com um regaço largo de boa vontade, a todo próximo, amando cada um como a si mesma — acaso se lhe dirá ainda com razão: Que fazes de mais? — ela, que se faz tão ampla? Tem um regaço amplo de caridade aquela que abraça a todos: mesmo aqueles a quem sabe não estar unida por nenhum laço da carne, nem atraída por nenhuma esperança de proveito, nem obrigada a nenhuma retribuição por algo recebido, nem presa, enfim, a dívida alguma, senão àquela de que se diz: A ninguém fiqueis devendo nada, a não ser o amor mútuo (Rm 13,8). E, se acrescentares ainda fazer violência ao reino da caridade por toda parte (Mt 11,12), até conseguires, como piedoso invasor, ocupá-lo até os seus últimos confins, julgando que nem aos inimigos se devem fechar as entranhas da compaixão; se fizeres o bem também aos que te odeiam, se orares pelos que te perseguem e caluniam (Mt 5,44), e procurares ser pacífico até com os que odeiam a paz (Sl 119,7): então sim a largueza do céu é a largueza da tua alma, e a altura não é diferente, nem a beleza dessemelhante. E só então se cumpre nela o que se diz: Estendes o céu como uma pele (Sl 103,2); e neste céu de admirável largueza, altura e beleza, o altíssimo, o imenso, o glorioso não só habita por condescendência, mas passeia à vontade.`
    },
    {
      n: 12,
      texto: `Vês que céus tem em si a Igreja, sendo ela mesma, no seu conjunto, um céu imenso, estendido de mar a mar e do rio até os confins da terra (Sl 71,8)? Vê também, em consequência, a quem a deves comparar nisto mesmo — se não te esqueceste do modelo desta coisa que lembrei pouco antes: o céu do céu e os céus dos céus. A exemplo, pois, daquela que está no alto, que é a nossa mãe, também esta, que ainda peregrina, tem os seus céus: homens espirituais, notáveis pela vida e pela fama, puros na fé, firmes na esperança, largos na caridade, suspensos na contemplação. E estes, fazendo chover a chuva salutar da palavra, trovejam com repreensões e relampejam com milagres. Estes narram a glória de Deus (Sl 18,2); estes, estendidos como peles sobre toda a terra, mostram em si mesmos a lei da vida e da disciplina, escrita pelo dedo de Deus, para dar ao seu povo o conhecimento da salvação (Lc 1,77); mostram também o Evangelho da paz, porque são peles de Salomão.`
    },
    {
      n: 13,
      texto: `Reconhece agora nestas peles a imagem daquelas do alto, que descrevi pouco acima no adorno do esposo. Reconhece também a rainha que está à sua direita (Sl 44,10), envolta em adornos semelhantes, mas não iguais. Pois, ainda que também a esta, no lugar da sua peregrinação e no dia da sua força, no esplendor dos santos (Sl 109,3), não caiba pequena parte de claridade e de beleza, àquela outra, porém, coroa-a de modo diferente a integridade e a consumação da glória dos bem-aventurados. É certo que eu chamaria perfeita e bem-aventurada também a esposa — mas em parte. Pois em parte é tenda de Cedar; formosa, contudo, seja naquela parte de si que já reina na bem-aventurança, seja também nos homens ilustres cuja sabedoria e virtudes a adornam, mesmo nesta noite, como o céu é adornado pelos seus astros. Daí o profeta: Os que forem sábios brilharão como o esplendor do firmamento; e os que ensinam a muitos a justiça, como as estrelas, pelas eternidades sem fim (Dn 12,3).`
    },
    {
      n: 14,
      texto: `Ó humildade! Ó sublimidade! Tenda de Cedar e santuário de Deus; morada terrena e palácio celeste; casa de barro e sala régia; corpo de morte e templo de luz; desprezo, enfim, para os soberbos, e esposa de Cristo. É negra, mas formosa, filhas de Jerusalém: ainda que o trabalho e a dor de um longo exílio lhe tirem a cor, adorna-a uma beleza celeste, adornam-na as peles de Salomão. Se tendes horror à negra, admirai também a formosa; se desprezais a humilde, olhai para cima, para a sublime. E quanto não tem de cautela, quanto não está cheio de conselho, de discernimento e de conveniência, que na esposa este abatimento e esta altura, por ora, se temperem uma à outra com tal medida que, entre as mudanças deste mundo, a sublimidade levante a humilde, para que não desfaleça na adversidade, e a humildade contenha a sublime, para que não se desvaneça na prosperidade? Com toda a beleza, as duas coisas, sendo contrárias entre si, concorrem juntas para o bem da esposa e servem à sua salvação.`
    },
    {
      n: 15,
      texto: `E isto quanto à comparação que a esposa parece tirar das peles de Salomão. Resta, porém, explicar sobre este mesmo versículo aquele sentido que lembrei e prometi no princípio: como toda a comparação se pode referir só à negrura. E não haveis de ficar sem o que vos prometi. Mas isso fica para o começo de outro sermão, tanto porque o comprimento deste já o exige, como para que a oração, como é costume, preceda aquilo que se há de dizer para louvor e glória do esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus bendito pelos séculos dos séculos. Amém.`
    }
  ]
});
