SERMOES.sermao({
  id: 'bernardo-cantico-36',
  colecao: 'bernardo-cantico',
  ordem: 36,
  numero: 'XXXVI',
  titulo: 'O saber das letras é bom para a instrução, mas o conhecimento da própria fraqueza é mais útil para a salvação',
  fonte: 'Quod scientia litterarum sit bona ad instructionem',
  argumento: `Bernardo começa a tratar das duas ignorâncias anunciadas no sermão anterior, e antes de tudo delimita a questão: nem toda ignorância condena. Muitos se salvaram sem as artes liberais, e os apóstolos não foram tirados de nenhuma escola. Isso não é desprezo pelo estudo, que ele reconhece ser útil à Igreja; o que decide tudo é o modo de saber, isto é, com que ordem, com que empenho e com que fim se aprende. Daí a célebre lista: há quem queira saber só por saber, e é curiosidade; para ser conhecido, e é vaidade; para vender o que sabe, e é comércio torpe; para edificar os outros, e é caridade; para ser edificado, e é prudência.

A ciência que não é cozida no fogo da caridade e não passa aos costumes torna-se, como um alimento mal digerido, em maus humores. Por isso a alma deve conhecer primeiro a si mesma: esse conhecimento humilha, mostra-lhe que vive na "região da dessemelhança" e a faz voltar-se para Deus, que então se deixa conhecer como misericordioso. O conhecimento de si é degrau para o conhecimento de Deus. O sermão fica em suspenso por causa dos monges que cochilam depois das longas vigílias da noite.

Tradução feita do texto latino de Migne (PL 183, 967-971).`,
  pontos: [
    {
      n: 1,
      texto: `Eis-me aqui para cumprir a minha promessa; eis-me aqui para os vossos desejos; eis-me aqui também para Deus, pelo serviço que lhe devo. Como vedes, sou impelido a falar por uma razão tríplice: a fidelidade ao compromisso, a caridade fraterna, o temor do Senhor. Se me calar, a minha boca me condenará (cf. Jó 9,20). E se falar? Temo, sem dúvida, o mesmo juízo: que a minha boca me condene igualmente, por falar e não fazer. Ajudai-me com as vossas orações, para que eu possa sempre dizer o que convém e cumprir com as obras o que digo. Sabeis que o sermão de hoje nos foi proposto sobre a ignorância, ou melhor, sobre as ignorâncias; pois, se vos lembrais, foram propostas duas: uma de nós mesmos, outra de Deus; e advertimos que devemos guardar-nos de ambas, porque ambas são condenáveis. Resta que eu torne isto mais claro e o exponha mais amplamente. Mas julgo que primeiro se deve perguntar se toda ignorância é condenável. E a mim parece que não: pois nem toda ignorância condena; há muitas e inumeráveis coisas que é lícito não saber, sem prejuízo da salvação. Por exemplo, se ignoras o ofício de ferreiro, ou de carpinteiro, ou de pedreiro, e quaisquer outras artes deste gênero que os homens exercem para as necessidades da vida presente, acaso isso te impede a salvação? Também sem todas aquelas artes que se chamam liberais — ainda que se aprendam e se exerçam com estudos mais nobres e mais úteis —, muitíssimos homens se salvaram, agradando a Deus pelos costumes e pelas obras. Quantos enumera o Apóstolo na Epístola aos Hebreus, que se tornaram amados não pela ciência das letras, mas pela consciência pura e pela fé sem fingimento (Hb 11)! Todos agradaram a Deus na sua vida pelos méritos da vida, não da ciência. Pedro, André, os filhos de Zebedeu e todos os demais condiscípulos não foram tirados da escola dos retóricos ou dos filósofos; e, no entanto, o Salvador por meio deles operou a salvação no meio da terra (Sl 73,12). Não os salvou pela sabedoria — como se houvesse neles mais sabedoria que em todos os viventes, conforme um santo confessou de si mesmo (Ecl 1,16) —, mas pela sua fé e mansidão; e fez deles santos, e até mestres. Enfim, deram a conhecer ao mundo os caminhos da vida (cf. Sl 15,11), e não com sublimidade de linguagem, nem com palavras doutas da sabedoria humana; mas, porque o mundo, com a sua sabedoria, não conheceu a Deus, aprouve a Deus salvar os que creem pela loucura da pregação deles (1Cor 2,1; 1,17.21).`
    },
    {
      n: 2,
      texto: `Talvez pareça que exagero em rebaixar a ciência, e que como que censuro os doutos e proíbo o estudo das letras. De modo nenhum! Não ignoro quanto os seus letrados foram e são úteis à Igreja, seja para refutar os adversários, seja para instruir os simples. Enfim, li: Porque rejeitaste a ciência, também eu te rejeitarei, para que não exerças para mim o sacerdócio (Os 4,6); li: Os que forem doutos brilharão como o esplendor do firmamento, e os que ensinam a muitos a justiça, como as estrelas, por toda a eternidade (Dn 12,3). Mas também sei onde li: A ciência incha (1Cor 8,1); e ainda: Quem aumenta a ciência aumenta também a dor (Ecl 1,18). Vês que há diferença entre as ciências, pois uma incha e outra entristece. Eu gostaria de saber qual delas te parece mais útil ou mais necessária para a salvação: a que incha ou a que dói. Mas não duvido que prefiras a que dói à que incha, porque a saúde que o inchaço finge, a dor a pede. E quem pede está perto da salvação, pois quem pede recebe (Lc 11,10). Enfim, aquele que cura os de coração contrito (Sl 146,3) abomina os inchados, como diz a Sabedoria: Deus resiste aos soberbos, e dá a graça aos humildes (Tg 4,6). E o Apóstolo dizia: Pela graça que me foi dada, digo a todos os que estão entre vós que não saibam mais do que convém saber, mas que saibam com sobriedade (Rm 12,3). Não proíbe saber, mas saber mais do que convém. E que é saber com sobriedade? Observar com a maior vigilância o que convém saber mais, e o que convém saber primeiro. Pois o tempo é breve (1Cor 7,29). Toda ciência, em si mesma, é boa, contanto que se apoie na verdade; mas tu, que, pela brevidade do tempo, te apressas a operar a tua salvação com temor e tremor (Fl 2,12), procura saber de preferência e mais amplamente aquilo que sentires mais próximo da salvação. Não é verdade que os médicos dos corpos consideram parte da medicina escolher, na tomada dos alimentos, o que se deve tomar primeiro, o que depois, e em que medida cada coisa? Pois, embora seja certo que são bons os alimentos que Deus criou, tu os tornas, para ti, nada bons, se ao tomá-los não observares a medida e a ordem. O que digo dos alimentos, entendei-o, pois, também das ciências.`
    },
    {
      n: 3,
      texto: `Mas é melhor remeter-vos ao Mestre. Pois esta sentença não é nossa, mas dele; ou melhor, é também nossa, porque é da Verdade. Quem julga saber alguma coisa, diz, ainda não sabe como convém saber (1Cor 8,2). Vês que não aprova quem sabe muitas coisas, se não souber o modo de saber. Vês, digo, como põe o fruto e a utilidade da ciência no modo de saber? Que chama, pois, modo de saber? Que, senão saberes com que ordem, com que empenho, com que fim convém conhecer cada coisa? Com que ordem: primeiro o que leva mais depressa à salvação; com que empenho: com mais ardor o que move com mais força ao amor; com que fim: não para a vanglória, ou a curiosidade, ou coisa semelhante, mas só para a edificação tua ou do próximo. Pois há os que querem saber só com o fim de saber: e é torpe curiosidade. E há os que querem saber para serem conhecidos: e é torpe vaidade. Estes, sem dúvida, não escapam à zombaria do poeta satírico, que canta a quem é assim: O teu saber não é nada, se outro não souber que sabes. E há também os que querem saber para vender a sua ciência — por exemplo, por dinheiro, por honras: e é torpe lucro. Mas há também os que querem saber para edificar: e é caridade. E ainda os que querem saber para serem edificados: e é prudência.`
    },
    {
      n: 4,
      texto: `De todos estes, só os dois últimos não se acham abusando da ciência, porque querem entender para agir bem. Enfim: Bom entendimento têm todos os que o praticam (Sl 110,10). Todos os outros ouçam: Para quem sabe fazer o bem e não o faz, é pecado (Tg 4,17); como se dissesse, por comparação: Para quem toma o alimento e não o digere, é nocivo. Pois o alimento não digerido, que não é bem cozido no estômago, gera maus humores, e corrompe o corpo, e não nutre. Assim também muita ciência metida no estômago da alma, que é a memória, se não for cozida pelo fogo da caridade, e assim distribuída e digerida por uma espécie de membros da alma — isto é, pelos costumes e pelas ações —, de modo que a alma se torne boa pelos bens que conheceu, com o testemunho da vida e dos costumes, não será essa ciência contada como pecado, como um alimento convertido em humores maus e nocivos? Acaso o pecado não é um mau humor? Acaso os maus costumes não são maus humores? E não sofrerá inchaços e cólicas na consciência quem é assim, sabendo o bem e não o fazendo? Não terá em si mesmo a sentença de morte (cf. 2Cor 1,9) e de condenação todas as vezes que lhe vier à mente a palavra que Deus disse: o servo que conhece a vontade do seu senhor e não faz o que é digno dela levará muitos açoites (Lc 12,47)? E vê se não era talvez na pessoa de uma alma assim que o profeta se lamentava, dizendo: Dói-me o ventre, dói-me o ventre (Jr 4,19). A não ser que a própria repetição pareça indicar um duplo sentido, de modo que, além deste que dissemos, busquemos também outro. Pois julgo que o Profeta pôde dizer isto em seu próprio nome: porque, cheio de ciência, ardendo de caridade e desejando de todo derramá-la, não encontrava quem se importasse de ouvir; e assim a sua ciência lhe era como um peso, porque não a podia comunicar. Lamenta, pois, o piedoso doutor da Igreja tanto os que desprezam saber como se deve viver como os que, sabendo-o, vivem mal apesar disso. E isto por causa de o Profeta repetir a mesma palavra.`
    },
    {
      n: 5,
      texto: `Percebes já quão verdadeiro foi o que sentiu o Apóstolo, que a ciência incha? Quero, pois, que a alma, antes de tudo, conheça a si mesma, porque isso o exige a razão tanto da utilidade como da ordem. Da ordem, porque o que nós somos é o primeiro para nós; da utilidade, porque tal ciência não incha, mas humilha, e é uma espécie de preparação para edificar. Pois o edifício espiritual de modo nenhum se pode manter de pé senão sobre o firme alicerce da humildade. E, para se humilhar, a alma não pode encontrar nada mais eficaz nem mais apropriado do que encontrar-se a si mesma na verdade: contanto que não disfarce, que não haja engano no seu espírito (Sl 31,2), que se ponha diante da sua própria face e não se deixe levar a desviar-se de si. Olhando-se assim à luz clara da verdade, não se achará na região da dessemelhança? E, suspirando, infeliz — pois já não lhe poderá ficar escondido que é verdadeiramente infeliz —, não clamará com o Profeta ao Senhor: Na tua verdade me humilhaste (Sl 118,75)? Pois como não se há de humilhar verdadeiramente neste verdadeiro conhecimento de si, quando se perceber carregada de pecados, oprimida pelo peso deste corpo mortal (cf. Sb 9,15), enredada nos cuidados terrenos, infectada pela borra dos desejos carnais, cega, curvada, fraca, envolvida em muitos erros, exposta a mil perigos, trêmula de mil temores, angustiada por mil dificuldades, sujeita a mil suspeitas, aflita por mil necessidades, inclinada aos vícios, sem forças para as virtudes? De onde lhe viria ainda a altivez dos olhos? De onde o levantar a cabeça? Não se voltará antes para a sua miséria, enquanto o espinho se lhe crava (Sl 31,4)? Há de voltar-se, digo, para as lágrimas, há de voltar-se para os prantos e gemidos, há de voltar-se para o Senhor, e em humildade clamará: Cura a minha alma, porque pequei contra ti (Sl 40,5). E, voltada para o Senhor, receberá consolação, porque ele é o Pai das misericórdias e o Deus de toda consolação (2Cor 1,3).`
    },
    {
      n: 6,
      texto: `Quanto a mim, enquanto olho para mim mesmo, o meu olho se detém na amargura (cf. Jó 17,2). Mas, se levantar o olhar e erguer os olhos para o auxílio da misericórdia divina, logo a visão alegre de Deus temperará a visão amarga de mim mesmo; e digo-lhe: A minha alma está perturbada dentro de mim; por isso me lembrarei de ti (Sl 41,7). E não é pequena visão de Deus experimentá-lo piedoso e acessível às súplicas, pois na verdade é benigno e misericordioso e disposto a perdoar o mal (Jl 2,13) — ele, cuja natureza é a bondade, e a quem é próprio compadecer-se sempre e perdoar. Por tal experiência, pois, e por tal ordem, Deus se dá a conhecer de modo salutar: quando o homem primeiro se conhecer posto na necessidade, e clamar ao Senhor, e o Senhor o ouvir e disser: Eu te livrarei, e tu me honrarás (Sl 49,15). E deste modo o conhecimento de ti será um degrau para o conhecimento de Deus; e ele será visto a partir da sua imagem, que em ti se renova, enquanto tu, contemplando com confiança, de rosto descoberto, a glória do Senhor, és transformado na mesma imagem, de claridade em claridade, como pelo Espírito do Senhor (2Cor 3,18).`
    },
    {
      n: 7,
      texto: `Mas repara agora, enfim, como um e outro conhecimento te são necessários para a salvação, de modo que não podes carecer de nenhum deles e salvar-te. Pois, se não te conheces, não terás em ti o temor de Deus, nem a humildade. Se podes contar com a salvação sem o temor de Deus e sem a humildade, tu verás. Fizestes bem em dar a entender, com esse murmúrio, que não pensais assim — ou antes, que não sois tão insensatos —, para que não nos demoremos no que é evidente. Mas prestai atenção ao resto. Ou será melhor pararmos, por causa dos sonolentos? Eu pensava cumprir num só sermão o que prometi sobre a dupla ignorância; e o teria feito, se não parecesse longo demais aos enfastiados. Pois vejo alguns bocejando, e outros até cochilando. E não admira: as vigílias da noite passada, que foram longuíssimas, desculpam-nos. Mas que direi àqueles que dormiram então e dormem agora mesmo assim? Mas não continuo agora a mexer na vergonha deles: basta tê-la tocado. Creio que daqui em diante vigiarão melhor, com medo do cautério da nossa observação. Nesta esperança, desta vez fazemos-lhes a vontade; e, por caridade para com eles, dividimos o que a razão pedia que fosse contínuo, ainda que a discussão fique em suspenso, pondo fim onde não havia fim. E eles, pela indulgência que se lhes concedeu, glorifiquem conosco o Esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
