SERMOES.sermao({
  id: 'bernardo-cantico-25',
  colecao: 'bernardo-cantico',
  ordem: 25,
  numero: 'XXV',
  titulo: 'Da negrura e da formosura da esposa, isto é, da Igreja',
  fonte: 'De nigredine et formositate sponsae',
  argumento: `Sobre «sou negra, mas formosa». Bernardo começa pela resposta da esposa às que a difamavam: não paga injúria com injúria e ainda as chama filhas de Jerusalém — e daí tira o retrato do bom superior, que é médico e não senhor.

Depois explica que não há contradição em ser negra e formosa, porque a cor não é a forma, e dá o exemplo de Paulo: de presença fraca e palavra desprezível, enegrecido por fomes, açoites e perigos de morte, e arrebatado ao terceiro céu. Negra no juízo dos homens, formosa no de Deus e dos anjos. E termina no próprio Cristo, que também poderia dizer: sou negro, mas formoso — formoso em si mesmo, negro por causa de ti.

Tradução feita do texto latino de Migne (PL 183, 899-903).`,
  pontos: [
    {
      n: 1,
      texto: `Eis o que eu dissera no sermão: que a esposa se vê obrigada a responder às rivais que a provocam — as quais, de corpo, parecem ser do número das jovenzinhas, mas de alma estão longe delas. Pois diz: Sou negra, mas formosa, filhas de Jerusalém (Ct 1,4). É evidente que falavam mal dela, lançando-lhe em rosto a sua negrura. Mas repara na paciência e na bondade da esposa. Não só não pagou maldição com maldição (1Pd 3,9), mas ainda as abençoou, chamando filhas de Jerusalém às que, pela sua maldade, mereciam antes ser chamadas filhas de Babilônia, ou filhas de Baal, ou qualquer outro nome injurioso que lhe ocorresse. Aprendera do profeta — ou antes, da própria unção que ensina a suavidade — que não se deve quebrar a cana rachada nem apagar a mecha que ainda fumega (Is 42,3). Por isso não julgou que devesse irritar ainda mais as que já estavam bastante agitadas, nem juntar coisa alguma aos aguilhões da inveja que as atormentava. Antes procurou ser pacífica com os que odiavam a paz (Sl 119,7), sabendo que era devedora também dos insensatos (Rm 1,14). Preferiu, pois, acalmá-las com um nome benévolo, porque se preocupava mais em cuidar da salvação das fracas do que em vingar-se.`
    },
    {
      n: 2,
      texto: `É uma perfeição que todos devem desejar; mas é propriamente o retrato dos melhores superiores. Pois os superiores bons e fiéis sabem que lhes foi confiado o cuidado de almas doentes, e não um cortejo de honras. E, quando pelo tom queixoso da voz percebem a murmuração interior de alguma delas — ainda que irrompa contra eles em injúrias e afrontas —, reconhecendo-se médicos e não senhores, preparam logo contra aquele delírio da alma não uma vingança, mas um remédio. É esta, pois, a razão por que a esposa chama filhas de Jerusalém às mesmas que suporta malévolas e maldizentes: para acalmar com palavra branda as que murmuram, serenar a agitação e curar a inveja. Pois está escrito: A língua pacífica aplaca as contendas (Pr 25,15). Aliás, as que são assim são de certo modo filhas de Jerusalém de verdade, e não é falsamente que a esposa lhes dá esse nome. Seja pelos sacramentos da Igreja, que recebem sem distinção junto com os bons; seja pela confissão de fé, que é comum a todos; seja pela convivência, ao menos corporal, com os fiéis; seja ainda pela esperança da salvação futura — da qual, enquanto vivem aqui, nem mesmo estas se devem dar por perdidas, por mais que vivam como perdidas —, não é sem razão que se chamam filhas de Jerusalém.`
    },
    {
      n: 3,
      texto: `Vejamos agora o que foi dizer: Sou negra, mas formosa. Não há contradição nestas palavras? De modo nenhum! Digo-o por causa dos simples, que não sabem distinguir entre a cor e a forma, quando a forma diz respeito à composição, e a negrura é uma cor. Nem tudo o que é negro é, sem mais, disforme. A negrura, por exemplo, não fica mal na pupila; e certas pedrinhas negras agradam nos adornos; e cabelos negros até aumentam a beleza e a graça de rostos claros. E o mesmo poderás notar facilmente em coisas sem conta, pois são inúmeras as que acharás sem cor na superfície e belas na composição. Deste modo, talvez, a esposa pode ter a beleza da composição e não estar livre de alguma mancha de negrura — mas só no lugar da sua peregrinação. Pois virá o dia em que o esposo da glória a apresentará a si mesmo, na pátria, gloriosa, sem mancha, nem ruga, nem coisa alguma semelhante (Ef 5,27). Mas agora, se dissesse que não tem negrura, estaria enganando a si mesma, e a verdade não estaria nela (1Jo 1,8). Não te admires, pois, de que tenha dito «sou negra» e, ao mesmo tempo, se glorie de ser formosa. Pois como não seria formosa aquela a quem se diz: Vem, formosa minha? (Ct 2,10) E aquela a quem se diz «vem» ainda não tinha chegado — para que ninguém pense que isto se disse não a esta negra, que ainda se afadiga pelo caminho, mas àquela bem-aventurada que já reina na pátria, totalmente sem negrura.`
    },
    {
      n: 4,
      texto: `Mas ouve de onde se disse negra e de onde formosa. Negra, porventura, pela vida sombria que levou antes, sob o príncipe deste mundo, quando ainda trazia a imagem do homem terreno; e formosa pela semelhança celeste pela qual depois a trocou, andando já em novidade de vida (Rm 6,4)? Mas, se é assim, por que não fala antes no passado — «fui negra» — em vez de dizer «sou negra»? Se, contudo, alguém gosta deste sentido, o que segue — como as tendas de Cedar, como as peles de Salomão (Ct 1,4) — deve entender-se de modo que, pela vida antiga, ela se tenha dito tenda de Cedar, e pela nova, tenda de Salomão. Que as peles são o mesmo que a tenda mostra o profeta, quando diz: De repente foram devastadas as minhas tendas, num instante as minhas peles (Jr 4,20). Primeiro, portanto, negra como as tendas desprezíveis de Cedar; depois, formosa como as peles do rei glorioso.`
    },
    {
      n: 5,
      texto: `Mas vejamos como uma e outra coisa se referem antes ao estado de uma vida melhor. Se considerarmos o aspecto exterior dos santos, o que está à vista — quão humilde é, quão desprezível, e como que descuidado por negligência —, enquanto por dentro, contemplando de rosto descoberto a glória de Deus, são transformados na mesma imagem, de claridade em claridade, como pelo Espírito do Senhor (2Cor 3,18): não nos parecerá com razão que qualquer alma assim pode responder aos que lhe lançam em rosto a negrura: Sou negra, mas formosa? Queres que te mostre uma alma ao mesmo tempo negra e formosa? As cartas, dizem, são fortes; mas a presença do corpo é fraca, e a palavra, desprezível (2Cor 10,10). Era Paulo. Avaliais então Paulo, ó filhas de Jerusalém, pela presença do corpo, e o desprezais como sem cor e disforme, porque vedes um homenzinho afligido pela fome e pela sede, pelo frio e pela nudez, em trabalhos sem conta, em açoites sem medida, muitas vezes em perigo de morte? (2Cor 11,23.27) É isto que enegrece Paulo. Por coisas assim o doutor das nações é tido por sem glória, sem nobreza, negro, obscuro — enfim, como o lixo deste mundo (1Cor 4,13). E, no entanto, não é ele que é arrebatado ao paraíso, que, atravessando um céu e outro, penetra pela sua pureza até o terceiro? Ó alma verdadeiramente belíssima! Ainda que habitasse um corpinho fraco, a beleza celeste não desdenhou recebê-la, a sublimidade angélica não a rejeitou, a claridade divina não a repeliu. E a esta chamais negra? É negra, mas formosa, filhas de Jerusalém: negra no vosso juízo, formosa no juízo de Deus e dos anjos. Se é negra, é por fora. E pouco lhe importa ser julgada por vós, ou pelos que julgam segundo a aparência (1Cor 4,3). Pois o homem vê a aparência, mas Deus vê o coração (1Sm 16,7). Por isso, ainda que negra por fora, é formosa por dentro, para agradar àquele a quem se consagrou. Não a vós: pois, se ainda vos agradasse, não seria serva de Cristo (Gl 1,10). Feliz negrura, que gera a brancura da mente, a luz da ciência, a pureza da consciência!`
    },
    {
      n: 6,
      texto: `Ouve, enfim, o que Deus promete pelo profeta a estes negros, que a humildade da penitência ou o zelo da caridade, como o calor do sol, parece ter tostado: Ainda que os vossos pecados sejam como escarlate, ficarão brancos como a neve; e ainda que sejam vermelhos como a púrpura, ficarão como a lã branca (Is 1,18). Não se deve desprezar nos santos esta negrura exterior, que produz a brancura interior e assim prepara um trono para a sabedoria. Pois a sabedoria é a brancura da vida eterna, como a define o Sábio (Sb 7,26); e há de ser branca a alma em que ela escolher o seu trono. E, se a alma do justo é o trono da sabedoria, não hesitaria em dizer que a alma do justo é branca. E talvez a própria justiça seja brancura. Ora, Paulo era justo, pois lhe estava reservada a coroa da justiça (2Tm 4,8). Branca era, pois, a alma de Paulo, e a sabedoria tinha nela o seu trono, de modo que ele falava sabedoria entre os perfeitos — a sabedoria escondida no mistério, que nenhum dos príncipes deste mundo conheceu (1Cor 2,6-8). E esta brancura de sabedoria e de justiça, nele, ou a produzia ou a merecia aquela negrura exterior: a presença fraca do corpo, os trabalhos sem conta, os muitos jejuns e vigílias. Por isso até o que há de negro em Paulo é mais belo do que todo adorno exterior, do que todo aparato régio. Não se lhe compara nenhuma beleza da carne, por maior que seja: nem uma pele luzidia, que há de arder; nem um rosto corado, vizinho da podridão; nem uma veste preciosa, sujeita a envelhecer; nem o brilho do ouro, nem o esplendor das pedras preciosas, nem coisa alguma dessas, que são todas para a corrupção.`
    },
    {
      n: 7,
      texto: `Com razão, pois, todo o cuidado dos santos, desprezando o adorno e o enfeite supérfluo do seu homem exterior, que certamente se corrompe, se aplica e se ocupa com toda a diligência em cultivar e adornar aquele homem interior que é à imagem de Deus e se renova dia após dia (2Cor 4,16). Pois estão certos de que nada pode ser mais aceito a Deus do que a sua imagem, se for restituída à beleza que lhe é própria. Por isso toda a sua glória está dentro, não fora: isto é, não na flor do feno nem na boca do povo, mas no Senhor. Daí dizerem: A nossa glória é esta: o testemunho da nossa consciência (2Cor 1,12) — porque da consciência só Deus é juiz, e é só a ele que desejam agradar; e agradar-lhe é a única glória verdadeira e suprema. Não é pequena, decerto, aquela glória que está dentro, e de que se digna gloriar-se o próprio Senhor da glória, como diz Davi: Toda a glória da filha do rei está dentro (Sl 44,14). E a glória de cada um está mais segura quando a tem em si mesmo, e não noutro. Mas talvez não se deva gloriar só da brancura interior, e sim também da negrura exterior, para que nada se perca para os santos e tudo concorra para o seu bem (Rm 8,28). Não só na esperança, pois, mas também nas tribulações nos devemos gloriar (Rm 5,3). De bom grado, diz o Apóstolo, me gloriarei nas minhas fraquezas, para que habite em mim o poder de Cristo. Desejável fraqueza, que é compensada pelo poder de Cristo! Quem me dera não só ser fraco, mas ficar desamparado e desfalecer de todo em mim mesmo, para ser firmado pelo poder do Senhor dos poderes! Pois o poder se aperfeiçoa na fraqueza. E diz enfim: Quando sou fraco, então é que sou forte e poderoso (2Cor 12,9-10).`
    },
    {
      n: 8,
      texto: `Sendo assim, a esposa converte com beleza em glória para si aquilo que as rivais lhe atiram como opróbrio, gloriando-se não só de ser formosa, mas também de ser negra. Pois não se envergonha da negrura, que sabe ter vindo antes também no esposo — e ser-lhe semelhante, que glória não é? Por isso nada julga mais glorioso para si do que carregar o opróbrio de Cristo (Hb 13,13). Daí aquela voz toda de exultação e de salvação: Longe de mim gloriar-me, a não ser na cruz de meu Senhor Jesus Cristo! (Gl 6,14) Grata é a ignomínia da cruz para quem não é ingrato ao Crucificado. É negrura, mas é a forma e a semelhança do Senhor. Vai ao santo Isaías, e ele te descreverá como o viu em espírito. Pois de quem outro diz que é homem das dores, experimentado no sofrimento, e que não tinha aparência nem beleza? E acrescentou: Nós o tivemos por leproso, ferido por Deus e humilhado. Mas ele foi ferido por causa das nossas iniquidades, esmagado por causa dos nossos crimes; e pelas suas chagas fomos curados (Is 53,3-5). Eis por que é negro. Junta a isto aquilo do santo Davi — És o mais belo dos filhos dos homens (Sl 44,3) — e tens no esposo tudo o que a esposa neste lugar testemunhou de si.`
    },
    {
      n: 9,
      texto: `Não te parece que, segundo o que se disse, também ele poderia responder com razão aos judeus seus adversários: Sou negro, mas formoso, filhos de Jerusalém? Negro, sem dúvida, pois não tinha aparência nem beleza; negro, porque era verme e não homem, opróbrio dos homens e desprezo do povo (Sl 21,7). Enfim, fez-se a si mesmo pecado (2Cor 5,21) — e terei receio de dizer que é negro? Olha-o sujo nos panos, roxo das chagas, coberto de escarros, pálido da morte — e ao menos então confessarás que é negro. Pergunta também aos apóstolos como o viram no monte; ou aos anjos, como é aquele que desejam contemplar; e admirarás que, ainda assim, é formoso. Formoso, pois, em si mesmo; negro por causa de ti. Quão formoso te reconheço, Senhor Jesus, mesmo na minha forma! Não só pelos milagres divinos com que resplandeces, mas também pela verdade, pela mansidão e pela justiça (Sl 44,5). Feliz quem, observando-te com atenção nestas coisas, homem que vives entre os homens, se oferece a si mesmo, quanto pode, como teu imitador. Este dom de felicidade, a tua formosa já o recebeu como primícias do seu dote: não tem preguiça de imitar o que em ti é formoso, nem vergonha de suportar o que é negro. Por isso dizia: Sou negra, mas formosa, filhas de Jerusalém; e acrescentou a comparação: Como as tendas de Cedar, como as peles de Salomão. Mas isto é obscuro, e não é para se tocar quando já estamos cansados. Tendes tempo para bater à porta. Se não vos descuidardes, virá aquele que revela os mistérios; e não tardará a abrir quem também convida a bater. Pois é ele quem abre, e ninguém fecha (Ap 3,7): o esposo da Igreja, Jesus Cristo, Senhor nosso, que é bendito pelos séculos dos séculos. Amém.`
    }
  ]
});
