SERMOES.sermao({
  id: 'bernardo-cantico-86',
  colecao: 'bernardo-cantico',
  ordem: 86,
  numero: 'LXXXVI',
  titulo: 'Da cautela e do recato da esposa que busca o Verbo; e louvor do recato',
  fonte: 'De cautela et verecundia sponsae quaerentis Verbum',
  argumento: `Retomando o versículo "No meu pequeno leito, durante as noites, busquei aquele a quem a minha alma ama", Bernardo quer agora tirar dele a lição moral, e começa pelo recato da esposa, que oferece como uma flor aos jovens: joia dos costumes, irmã da continência, lâmpada da mente pura, guarda da boa fama. Há um pudor que traz o pecado — o dos que se envergonham de ser vistos, e não de fazer o mal — e um que traz a glória. A esposa busca o Verbo no segredo do leito e da noite, como Cristo manda orar no quarto: a oração noturna, sem outras testemunhas senão Deus e o anjo, sobe mais pura. E orar é buscar o Verbo, pois nele estão todas as coisas; quem pede outra coisa deve pedi-la por causa dele.

Por fim, o pequeno leito significa a fraqueza humana, e a noite a ignorância em que todos nascemos, contra as quais se busca o Verbo, poder e sabedoria de Deus. O sermão interrompe-se aqui: Bernardo morreu em 1153 sem ter levado adiante o comentário, que chega assim até o início do capítulo terceiro do Cântico.

Tradução feita do texto latino de Migne (PL 183, 1195-1198).`,
  pontos: [
    {
      n: 1,
      texto: `Já não há por que me perguntarem por que a alma busca o Verbo: isso ficou dito acima mais que suficientemente. Vamos, sigamos o resto deste versículo, pelo menos no que diz respeito aos costumes. Aqui, repara primeiro no recato da esposa, e não sei se nos costumes humanos se pode notar coisa mais graciosa. Agrada-me, antes de tudo, tomá-lo de certo modo nas mãos e, como uma bela flor, colhê-lo desta passagem e oferecê-lo aos nossos jovens. Não que não se deva conservar com todo o empenho também na idade mais avançada — pois é, certamente, o ornamento de todas as idades —, mas porque a graça do terno recato brilha mais e mais belamente na idade mais tenra. Que há de mais amável que um jovem recatado? Que bela e que esplêndida joia dos costumes é esta na vida e no rosto de um jovem! Que verdadeira e nada duvidosa mensageira de boa esperança, que indício de boa índole! É para ele a vara da disciplina, que, ameaçando os afetos vergonhosos, contém os movimentos e as ações levianas da idade escorregadia e reprime os insolentes. Que coisa foge tanto das palavras torpes e de toda torpeza? É irmã da continência. Não há sinal tão manifesto da simplicidade da pomba (cf. Mt 10,16); e por isso é também testemunha da inocência. É uma lâmpada da mente pudica, sempre acesa, de modo que nada de torpe ou indecoroso tente instalar-se nela sem que ela logo o denuncie. Assim, exterminadora dos males e defensora da pureza inata, é a glória especial da consciência, guarda da boa fama, ornamento da vida, sede da virtude, primícias das virtudes, louvor da natureza e insígnia de toda honestidade. O próprio rubor das faces, que o pudor por acaso tenha trazido, quanta graça e beleza costuma dar ao rosto que dele se cobre!`
    },
    {
      n: 2,
      texto: `O recato é um bem tão natural do ânimo que até os que não receiam fazer o mal se envergonham, contudo, de ser vistos, como diz o Senhor: Todo aquele que faz o mal odeia a luz (Jo 3,20). E também os que dormem, dormem de noite, e os que se embriagam, embriagam-se de noite (1Ts 5,7), escondendo nas trevas as obras das trevas (cf. Rm 13,12), dignas de esconderijo. Mas há esta diferença: as coisas vergonhosas e ocultas (cf. 2Cor 4,2), que o pudor destes não se envergonha de ter, mas de mostrar, o recato da esposa de modo nenhum as encobre, mas cospe-as e as expulsa. Por isso diz o Sábio: Há um pudor que traz o pecado, e há um pudor que traz a glória (Eclo 4,25). A esposa busca o Verbo com recato, pois o busca no pequeno leito, durante as noites; mas este recato traz glória, não pecado. Busca-o para purificar a consciência, busca-o para ter o seu testemunho, para poder dizer: A minha glória é esta: o testemunho da minha consciência (2Cor 1,12). No meu pequeno leito, durante as noites, busquei aquele a quem a minha alma ama (Ct 3,1). O recato, se reparas, é indicado pelo lugar e pelo tempo. Que há de tão amigo do ânimo recatado como o segredo? Ora, tanto a noite como o pequeno leito têm segredo. Enfim, quando queremos orar, manda-se-nos entrar no quarto (Mt 6,6), certamente por causa do segredo. Isto, sem dúvida, por cautela, para que, orando diante de outros, o louvor humano não roube o fruto da oração e frustre o seu efeito. Mas com esta sentença és ensinado também ao recato. Que há de tão próprio do recato como evitar os próprios louvores, evitar a jactância? É claro que foi expressamente também por causa do recato que o filho e mestre do pudor mandou aos que oram procurar o segredo. Que há de tão indecoroso, sobretudo num jovem, como a ostentação da santidade? E, no entanto, é sobretudo nesta idade que se toma o início apropriado e oportuno da vida religiosa, como diz Jeremias: Bom é para o homem ter levado o jugo desde a sua juventude (Lm 3,27). Boa recomendação da oração que se vai fazer é antepor-lhe o recato, dizendo: Sou jovem e desprezado, mas não me esqueci dos teus preceitos (Sl 118,141).`
    },
    {
      n: 3,
      texto: `Quem quiser orar deve observar não só o lugar, mas também o tempo. O tempo de descanso é mais cômodo e mais apto; sobretudo quando o sono da noite impõe um silêncio profundo, então a oração sai certamente mais livre e mais pura. Levanta-te de noite, diz, ao começo das tuas vigílias, e derrama como água o teu coração diante do Senhor teu Deus (Lm 2,19). Com que segurança sobe de noite a oração, tendo por testemunhas só Deus e o santo anjo, que a recebe para a apresentar no altar do alto (cf. Ap 8,3-4)! Quão agradável e luminosa, colorida pelo rubor do recato! Quão serena e tranquila, sem ser perturbada por nenhum grito ou ruído! Quão pura, enfim, e sincera, sem nenhuma poeira da preocupação terrena, sem ser tentada por nenhum louvor ou adulação de quem a vê! Por isso a esposa, não menos com recato do que com cautela, procurava o segredo do pequeno leito e da noite, querendo orar, isto é, buscar o Verbo. Pois é uma só coisa. De outro modo, não oras retamente, se, orando, buscas alguma coisa fora do Verbo, ou que não buscas por causa do Verbo, porque nele estão todas as coisas. Nele estão os remédios das feridas, nele os socorros das necessidades, nele a reparação das faltas, nele as riquezas do progresso, nele, enfim, tudo o que convém aos homens receber ou ter, tudo o que é decoroso, tudo o que é necessário. Sem razão, pois, se pede ao Verbo outra coisa, se ele mesmo é tudo. Pois, ainda que pareçamos pedir estas coisas temporais, quando é necessário, se o Verbo é a causa, como é digno, certamente não buscamos aquelas, mas antes este, por causa do qual pedimos as outras. Sabem-no os que se acostumaram a dirigir todo o uso destas coisas para merecer o Verbo.`
    },
    {
      n: 4,
      texto: `Não nos custe, porém, investigar ainda os segredos deste pequeno leito e deste tempo, para ver se neles se esconde alguma coisa espiritual que seja proveitoso pôr à vista. E, se nos agrada entender que o nome de pequeno leito representa a fraqueza humana, e as trevas da noite a ignorância, igualmente humana, é coerente e bem conveniente que se busque com mais insistência o Verbo, poder de Deus e sabedoria de Deus (cf. 1Cor 1,24), contra um e outro mal de origem. Pois que há de mais conveniente do que opor à fraqueza o poder e à ignorância a sabedoria? E, para que não fique nos corações dos mais simples nenhuma dúvida sobre esta interpretação, ouçam o que diz sobre isto o santo Profeta: O Senhor lhe dê socorro no seu leito de dor; mudaste todo o seu leito na sua enfermidade (Sl 40,4). E isto quanto ao pequeno leito. E, quanto à noite da ignorância, que há de mais claro do que o que diz igualmente noutro salmo: Não souberam nem entenderam, andam nas trevas (Sl 81,5), exprimindo certamente a ignorância de todo o gênero humano, na qual nasceram? É dela, penso eu, que o bem-aventurado Apóstolo confessa ter nascido e se gloria de ter sido arrancado, dizendo: Ele nos arrancou do poder das trevas (Cl 1,13). Por isso dizia também: Não somos filhos da noite nem das trevas (1Ts 5,5); e ainda a todos os eleitos: Andai, diz, como filhos da luz (Ef 5,8).`
    }
  ]
});
