SERMOES.sermao({
  id: 'bernardo-cantico-76',
  colecao: 'bernardo-cantico',
  ordem: 76,
  numero: 'LXXVI',
  titulo: 'Da glória do esposo, na qual, igual ao Pai, está sentado à direita da sua glória; e de como os bons pastores devem ser solícitos, vigilantes e prudentes em apascentar as almas que lhes foram confiadas',
  fonte: 'De claritate sponsi',
  argumento: `"Pelas ruas e praças buscarei aquele a quem a minha alma ama." A esposa ainda pensa como pequenina: imagina que o ressuscitado voltou às praças para ensinar, curar e confundir os incrédulos; mas ele já tinha consumado a obra do Pai e apressava-se a subir para a sua direita. Retira-se da vista para que haja mérito na fé — bem-aventurados os que não viram e creram — e para receber do Pai a glória que tinha antes que o mundo existisse, igual à do Pai, pois o Pai e o Filho se glorificam mutuamente. Ali, à direita da glória, onde nenhum anjo se senta, encontra-o quem o busca; e encontra-o desde já pela fé, que alcança o inacessível: "creio na Trindade, que não compreendo".

Para que a nova esposa creia, é preciso quem pregue: são "os vigias que guardam a cidade", os pastores. A Igreja é cidade, esposa e ovelhas; e a tríplice pergunta de Jesus a Pedro — "amas-me?" — ensina que só deve aceitar o cuidado das ovelhas quem ama o Senhor mais do que a si mesmo. O pastor deve guardar a cidade dos tiranos, dos hereges e dos demônios, adornar a esposa com a disciplina e apascentar as ovelhas com a Escritura e sobretudo com o próprio exemplo; por isso ninguém deve cobiçar as honras sem a força, a ciência e a vida que o encargo exige. Chamado a outros assuntos, Bernardo interrompe aqui o sermão.

Tradução feita do texto latino de Migne (PL 183, 1150-1155).`,
  pontos: [
    {
      n: 1,
      texto: `Pelas ruas e praças buscarei aquele a quem a minha alma ama (Ct 3,2). Ainda pensa como pequenina. Penso que julgou que ele, saído do sepulcro, logo se tinha dirigido aos lugares públicos, para ensinar o povo como costumava, curar os doentes e manifestar a sua glória em Israel, para ver se o recebiam ressuscitado da morte aqueles que prometiam recebê-lo se descesse da cruz (cf. Mt 27,42). Mas ele tinha consumado a obra que o Pai lhe dera para fazer (cf. Jo 17,4); o que ela deveria ter entendido ao menos pela palavra dele, pendente da cruz, aquela que disse quando estava para expirar: Está consumado (Jo 19,30). Já não havia por que se confiar de novo às multidões, que talvez nem assim haveriam de crer nele. E apressava-se para o Pai, que lhe havia de dizer: Senta-te à minha direita, até que eu ponha os teus inimigos como escabelo dos teus pés (Sl 109,1). Pois com mais força e de modo mais divino, quando for levantado da terra, atrairá tudo a si (cf. Jo 12,32). Ela, porém, julgou que devia buscá-lo pelas ruas e praças, ávida de o gozar, mas ignorante do mistério. Frustrada, pois, de novo, repete: Busquei-o, e não o encontrei (Ct 3,2); para que se cumprisse a palavra que ele disse: Porque vou para o Pai, e já não me vereis (Jo 16,10).`
    },
    {
      n: 2,
      texto: `Talvez ela diga: Como crerão, então, naquele que não verão? Como se a fé viesse da vista, e não antes do ouvir (cf. Rm 10,17). Que há de grande em crer no que vês? E que louvor merece não negar crédito aos teus próprios olhos? Mas, se esperamos o que não vemos, esperamos com paciência (Rm 8,25); e a paciência é mérito. Enfim, bem-aventurados os que não viram e creram (Jo 20,29). Para que não se anule, pois, o mérito da fé, que ele se subtraia à vista, dando lugar à virtude. E também é tempo de se recolher já ao que é seu. Perguntas: a que é seu? À direita do Pai. Pois não julgará usurpação ser igual a Deus, sendo de condição divina (Fl 2,6). Seja, pois, este o lugar do Unigênito, no qual se veja repelida toda injúria contra ele. Que se sente ao lado, e não abaixo, para que todos honrem o Filho como honram o Pai (Jo 5,23). Nisto aparecerá a igualdade da majestade: se não o olhares como inferior ao Pai, nem como posterior. Mas ela, entretanto, não repara em nada disto: como que ébria de amor, correndo de um lado para outro, procura com os olhos aquele que o olho já não alcança, mas só a fé. Pois não pensa que Cristo deva entrar na sua glória (cf. Lc 24,26) de outro modo senão depois que, manifestada ao mundo abertamente a glória da ressurreição, seja confundida a impiedade, exultem os fiéis, se gloriem os discípulos, se convertam os povos, e enfim ele mesmo seja glorificado por todos, tornando-se clara para todos, pela presença do ressuscitado, a verdade do que ele tinha predito. Enganas-te, ó esposa. É preciso, sim, que estas coisas aconteçam, mas no seu tempo.`
    },
    {
      n: 3,
      texto: `Por ora, porém, vê se não é mais digno e mais conforme à justiça do alto que não se dê o que é santo aos cães, nem as pérolas aos porcos (cf. Mt 7,6); que antes, segundo a Escritura, seja tirado o ímpio, para que não veja a glória de Deus (Is 26,10); que a fé não seja privada do seu mérito, a qual se reconhece mais provada quando se crê o que não se vê; que se guarde nela para os dignos o que se esconde aos indignos, para que os que estão na imundície se tornem ainda mais imundos, e os justos se justifiquem ainda mais (Ap 22,11) — se não cochilarem de tédio (cf. Sl 118,28). Não é mais digno, também, que os céus e os céus dos céus não definhem nem fiquem confundidos na sua espera; que o próprio Pai onipotente não seja por mais tempo frustrado no desejo do seu coração; que, enfim, o Unigênito não seja de algum modo retardado na entrada da sua glória — o que, só por si, seria indigníssimo? Em quanto julgas que se deve estimar a glória dos mortais, por maior que seja, para que o devesse reter, ainda que por pouco, longe daquela que lhe foi preparada pelo seu Pai desde a eternidade? Acrescenta que de modo nenhum convém adiar por mais tempo o pedido do próprio Filho. Perguntas que pedido digo? Aquele em que diz: Pai, glorifica o teu Filho (Jo 17,1). O que, no entanto, eu entenderia que ele pediu não como suplicante, mas como quem sabe de antemão. Pede-se com liberdade o que está em poder de quem pede receber. O pedido do Filho é, pois, de condescendência, não de necessidade, pois ele dá com o Pai tudo o que recebe do Pai.`
    },
    {
      n: 4,
      texto: `Aqui se deve dizer também que não só o Pai glorifica o Filho, mas também o Filho glorifica o Pai; para que ninguém diga que o Filho é menor que o Pai, como quem é glorificado pelo Pai, quando também ele glorifica o Pai, pois diz o Filho: Pai, glorifica o teu Filho, para que o teu Filho te glorifique (Jo 17,1). Mas talvez ainda julgues que o Filho deve ser posto abaixo, porque parece receber do Pai, como quem não a tinha, a glória que depois devolve ao Pai. Ouve que não é assim: Glorifica-me, Pai, diz, com a glória que eu tinha junto de ti antes que o mundo existisse (Jo 17,5). Se, pois, a glória do Filho não é posterior, visto que é desde a eternidade, o Pai e o Filho glorificam-se mutuamente em igualdade. E, se é assim, onde está a primazia do Pai? Há, certamente, igualdade onde há coeternidade. E tão grande é a igualdade, que é uma só a glória de ambos, assim como eles são uma só coisa. Por isso me parece que, dizendo noutra ocasião: Pai, glorifica o teu nome, não pede outra coisa senão ser ele mesmo glorificado, pois nele e por ele seria sem dúvida glorificado o nome do Pai; e recebeu do Pai a resposta: Já o glorifiquei, e hei de glorificá-lo de novo (Jo 12,28). E esta mesma resposta do Pai não foi pequena glorificação do Filho. Mas vê-se que foi glorificado mais abundante e majestosamente junto às águas do Jordão, pelo testemunho de João, pelo sinal da pomba e pela voz do Pai que dizia: Este é o meu Filho amado (Mt 3,14.16-17). E também no monte, diante de três discípulos, foi glorificado magnificentíssimamente: pela mesma voz, que de novo desceu do céu sobre ele, pela admirável e extraordinária transfiguração do seu corpo, e ainda pelo testemunho dos dois profetas que ali apareceram falando com ele (Mt 17,2-5).`
    },
    {
      n: 5,
      texto: `Resta, pois, que, segundo a promessa do Pai, seja glorificado ainda uma vez; e essa será a plenitude da glória, à qual nada mais se poderá acrescentar. Mas onde será dada aquela bênção? Não, como ela suspeitou, nas praças ou nas ruas; a não ser, talvez, naquelas de que se diz: As tuas praças, Jerusalém, serão pavimentadas de ouro puro, e em todas as tuas ruas se cantará aleluia (Tb 13,22). Nestas, de fato, recebeu o Filho do Pai aquela glória à qual não se poderá encontrar outra semelhante, nem sequer nos céus. Pois a qual dos anjos se disse alguma vez: Senta-te à minha direita (Hb 1,13)? E não só do número dos anjos, mas nem sequer das outras ordens superiores dos bem-aventurados se achou alguém de modo algum capaz de receber esta glória supereminente. A nenhum deles foi dirigida aquela voz de glória singular, a nenhum foi dado experimentar em si a eficácia dessa voz. Tronos, dominações, principados ou potestades (cf. Cl 1,16) desejam, sem dúvida, olhar para ele (cf. 1Pd 1,12), mas não ousam comparar-se a ele. Assim, ao meu Senhor, e só a ele, foi dito e dado pelo Senhor (cf. Sl 109,1) sentar-se à direita da sua glória, como igual na glória, consubstancial na essência, semelhante pela geração, não desigual na majestade, não posterior na eternidade. Ali, ali o encontrará quem o buscar, e verá a sua glória: não a glória como de um qualquer dentre os outros, mas a glória como do Unigênito do Pai (Jo 1,14).`
    },
    {
      n: 6,
      texto: `Que farás, ó esposa? Pensas que podes segui-lo até lá? Ou ousas, ou és capaz de introduzir-te neste segredo tão santo, neste santuário tão secreto, para contemplar o Filho no Pai e o Pai no Filho? Certamente não. Aonde ele está, tu não podes ir agora; mas irás depois (cf. Jo 13,36). Mas vamos: segue, busca; e que aquela claridade e aquela sublimidade inacessíveis não te afastem de buscar, nem te façam desesperar de encontrar. Se podes crer, tudo é possível a quem crê (Mc 9,22). Perto está, diz, a palavra, na tua boca e no teu coração (Rm 10,8). Crê, e encontraste. Pois crer é ter encontrado. Os fiéis sabem que Cristo habita pela fé nos seus corações (Ef 3,17). Que há de mais perto? Busca, pois, segura; busca com devoção. Bom é o Senhor para a alma que o busca (Lm 3,25). Busca com os desejos, segue com as obras, encontra pela fé. Que não encontrará a fé? Alcança o inacessível, descobre o desconhecido, abarca o imenso, apreende o que é último; enfim, encerra de certo modo no seu vastíssimo seio a própria eternidade. Direi com confiança: creio na eterna e bem-aventurada Trindade, que não compreendo; e seguro pela fé aquilo que não abarco com a mente.`
    },
    {
      n: 7,
      texto: `Mas alguém diz: Como crerá sem quem pregue, se a fé vem do ouvir, e o ouvir pela palavra da pregação (Rm 10,14.17)? Deus proverá (cf. Gn 22,8). E eis que já estão prontos os que hão de instruir e formar no que é preciso a nova esposa, que vai casar-se com o esposo celeste, ensinar-lhe a fé e transmitir-lhe a forma da piedade e da religião. Ouve, pois, o que acrescenta: Encontraram-me os vigias que guardam a cidade (Ct 3,3). Quem são estes vigias? Sem dúvida aqueles que o Salvador, no Evangelho, declara bem-aventurados, se, quando vier, os encontrar vigiando (Lc 12,37). Que bons vigias, que velam enquanto nós dormimos, como quem há de prestar contas pelas nossas almas (cf. Hb 13,17)! Que bons guardas, que, vigilantes no ânimo e passando as noites em oração, sondam com sagacidade as ciladas dos inimigos, antecipam-se aos planos dos malvados, descobrem os laços, escapam às armadilhas, rompem as redes, frustram as maquinações! Estes são os que amam os irmãos e o povo cristão, que oram muito pelo povo e por toda a cidade santa (cf. 2Mc 15,14). Estes são os que, muito solícitos pelas ovelhas do Senhor que lhes foram confiadas, entregam o seu coração a velar desde a madrugada junto do Senhor que os fez, e suplicam na presença do Altíssimo (cf. Eclo 39,6). E velam e suplicam, conhecendo a sua insuficiência para guardar a cidade, e sabendo que, se o Senhor não guardar a cidade, em vão vigia quem a guarda (Sl 126,1).`
    },
    {
      n: 8,
      texto: `E, como o Senhor manda assim: Vigiai e orai, para não entrardes em tentação (Mc 14,38), é claro que sem este duplo exercício dos fiéis e sem o empenho dos guardas não pode estar segura a cidade, nem a esposa, nem as ovelhas. Perguntas a diferença entre elas? São uma só coisa: cidade, pela reunião; esposa, pelo amor; ovelhas, pela mansidão. Queres saber que a esposa é o mesmo que a cidade? Vi, diz, a cidade santa, a nova Jerusalém, que descia do céu, de junto de Deus, preparada como uma esposa enfeitada para o seu marido (Ap 21,2). Isto mesmo te aparecerá com clareza também quanto às ovelhas, se te lembrares com que insistência aquele primeiro guarda — falo de Pedro —, quando lhe foram confiadas pela primeira vez as ovelhas, foi ao mesmo tempo interrogado sobre o amor. Coisa que aquele sábio depositante não teria feito com tanto cuidado, se não se soubesse esposo, testemunhando-lhe isso do íntimo a sua consciência. Ouvi isto, amigos do esposo (cf. Jo 3,29) — se é que sois amigos. Mas disse pouco, amigos: é preciso que sejam amicíssimos os que são agraciados com o privilégio de tanta familiaridade. Não foi à toa que se repetiu tantas vezes, ao confiar-lhe as ovelhas: Pedro, amas-me (Jo 21,15-17)? E eu penso que isto significa o mesmo que se Jesus lhe tivesse dito: Se a tua consciência não te der testemunho de que me amas, e me amas muito e perfeitamente — isto é, mais do que as tuas coisas, mais do que os teus, mais até do que a ti mesmo, para se completar o número desta minha repetição —, de modo nenhum aceites este cuidado, nem te intrometas com as minhas ovelhas, pelas quais foi derramado o meu sangue. Palavra terrível, capaz de abalar até os corações intrépidos de quaisquer tiranos.`
    },
    {
      n: 9,
      texto: `Por isso, cuidai de vós (cf. At 20,28), todos os que recebestes em sorte a obra deste ministério; cuidai, digo, de vós e do precioso depósito que vos foi confiado (cf. 1Tm 6,20). É uma cidade: vigiai para a guardar e manter a concórdia. É uma esposa: cuidai do seu adorno. São ovelhas: tratai de as apascentar. E talvez não seja despropositado dizer que estas três coisas correspondem àquela tríplice pergunta do Senhor. A guarda da cidade, para ser suficiente, há de ser tríplice: contra a violência dos tiranos, contra a fraude dos hereges, contra as tentações dos demônios. O adorno da esposa está nas boas obras, nos costumes e na ordem. E o pasto das ovelhas está, em geral, nas pastagens das Escrituras, como na herança do Senhor; mas nelas há distinção. Pois há os mandamentos, que se impõem às almas duras e carnais pela lei da vida e da disciplina (cf. Eclo 45,6); há os legumes das dispensas, que se servem aos fracos e aos pusilânimes por consideração de misericórdia (cf. Rm 14,2); e há o alimento sólido e forte dos conselhos, que se propõe, tirado do íntimo da sabedoria, aos sãos e aos que têm os sentidos exercitados para discernir o bem e o mal (Hb 5,14). Aos pequeninos, como a cordeirinhos, dá-se a beber o leite da exortação, não alimento sólido (cf. 1Cor 3,2). Além disso, os pastores bons e solícitos não cessam de engordar o rebanho com exemplos bons e alegres, e mais com os seus do que com os alheios. Pois, se o fazem com os alheios e não com os seus, é vergonha para eles, e o rebanho assim não progride. Se, por exemplo, eu, que pareço ter entre vós o cuidado de pastor, vos puser diante a mansidão de Moisés, a paciência de Jó, a misericórdia de Samuel, a santidade de Davi e outros exemplos semelhantes dos bons, sendo eu mesmo áspero e impaciente, sem misericórdia e nada santo, a palavra, receio, sairá menos saborosa, e vós a recebereis com menos avidez. Mas deixo isto à piedade do alto, para que ela supra o que de nós vos falta e corrija o que está errado. O bom pastor cuidará também de que, segundo o Evangelho, se encontre que tem sal em si mesmo (Mc 9,49), sabendo que a palavra temperada com sal (cf. Cl 4,6), quanto mais agradar pela graça, tanto mais aproveitará para a salvação. Fique isto dito, por ora, sobre a guarda da cidade, o adorno da esposa e o pasto das ovelhas.`
    },
    {
      n: 10,
      texto: `Quero, porém, indicar ainda estas mesmas coisas um pouco mais expressamente, por causa daqueles que, ambicionando com excessiva avidez as honras, se submetem com pouca previdência a pesados encargos e se expõem a perigos; para que saibam a que vieram, como está escrito: Amigo, a que vieste (Mt 26,50)? Se não me engano, só para a guarda da cidade, para que se faça quanto basta, é preciso um homem forte, espiritual e fiel: forte para repelir as agressões, espiritual para descobrir as ciladas, fiel para não buscar os seus próprios interesses (cf. Fl 2,21). E, para honrar ou corrigir os costumes, o que pertence ao adorno da esposa, quem não reconhece claramente que será muito necessária a censura da disciplina, com grande diligência? Por isso, todo aquele a quem cabe esta obra deve arder naquele zelo com que, inflamado, dizia aquele insigne zelador da esposa do Senhor: Tenho por vós um zelo de Deus; pois vos desposei a um só marido, para vos apresentar a Cristo como virgem pura (2Cor 11,2). E como conduzirá os rebanhos do Senhor às pastagens das palavras divinas um pastor ignorante? E, se for douto, mas não for bom, é de temer que não tanto alimente com uma doutrina fecunda quanto prejudique com uma vida estéril. Temerariamente, pois, também nesta parte, se assume este encargo sem a ciência e sem uma vida louvável. Mas eis que — coisa que não louvamos — nos impõem o fim onde não havia fim. Chamam-nos para outro assunto, ao qual é indigno que este ceda. Estou angustiado de todos os lados (cf. Dn 13,22), e não sei o que me é mais penoso: ser arrancado deste assunto ou ser dispersado naquele; a não ser que as duas coisas juntas são mais penosas que qualquer delas. Ó servidão! Ó necessidade! Não faço o que quero, mas faço o que odeio (cf. Rm 7,15). Notai, porém, onde paramos, para que, logo que estejamos livres para voltar a isto, recomecemos dali, em nome do esposo da Igreja, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
