SERMOES.sermao({
  id: 'bernardo-cantico-78',
  colecao: 'bernardo-cantico',
  ordem: 78,
  numero: 'LXXVIII',
  titulo: 'Que a esposa, isto é, a Igreja dos eleitos, foi predestinada por Deus antes dos séculos, e que ele se antecipou a ela para que o buscasse e se convertesse',
  fonte: 'Quod sponsa praedestinata est a Deo ante saecula',
  argumento: `Bernardo paga a dívida do sermão anterior: por que a esposa diz que foi "encontrada" pelos vigias? Na obra da salvação, que é o casamento de Cristo com a Igreja, cooperam Deus, os anjos e os homens; mas Deus reserva para si três coisas, nas quais se antecipa a todos: a predestinação, antes dos tempos; a criação, com o tempo; e a inspiração, no tempo. Pela predestinação, a Igreja dos eleitos sempre esteve junto de Deus e sempre foi amada; criada, ficou escondida sob a condição comum de pecado e de morte, sem que anjo ou homem a reconhecesse; só a graça, visitando-a no seu tempo, a revelou, preparando os corações para o Evangelho.

Por isso os pregadores não a converteram nem a escolheram: encontraram-na já preparada, como os campos brancos para a colheita — assim como Pedro encontrou Cornélio, Ananias encontrou Paulo, Filipe encontrou Natanael, a quem o Senhor já tinha visto debaixo da figueira. E a esposa, como Maria, "achada" com o Espírito Santo, antecipa-se aos pregadores e pergunta-lhes: "Vistes aquele a quem a minha alma ama?"

Tradução feita do texto latino de Migne (PL 183, 1159-1162).`,
  pontos: [
    {
      n: 1,
      texto: `Se bem me lembro, paramos e ficamos presos na palavra "encontrar", ouvindo com certo escrúpulo que a esposa disse ter sido encontrada pelos seus pregadores. Expusemos as causas da nossa hesitação e dúvida, e pareceu que havia alguma coisa a investigar; mas o que se investigava não pôde ser explicado no fim do sermão, quando o tempo já nos apertava. Que resta, senão pagarmos agora a dívida? Na explicação do grande mistério — falo daquele que o Doutor das nações interpretou em Cristo e na Igreja (Ef 5,32), o santo e casto matrimônio; é a própria obra da nossa salvação —, nele, digo, três cooperam entre si: Deus, o anjo e o homem. E Deus, como não operaria e não cuidaria das núpcias do seu Filho amado? Ele, certamente, e com toda a vontade. E bastaria por si mesmo, sem o apoio destes; estes, porém, sem ele nada podem fazer (cf. Jo 15,5). Se, pois, os associou à obra deste ministério, não buscou para si um alívio, mas proveito para eles. Pois aos homens pôs os méritos na obra, segundo aquilo: O operário é digno do seu salário (Lc 10,7); e: Cada um receberá segundo o seu próprio trabalho (1Cor 3,8), quer o que planta na fé, quer o que rega o que foi plantado. E, quando se serve do ministério dos anjos para a salvação do gênero humano, não faz com que os anjos sejam amados pelos homens? Pois que os homens sejam amados pelos anjos pode notar-se sobretudo por isto: os anjos não ignoram que as antigas perdas da sua cidade hão de ser reparadas com os homens. E, certamente, não convinha que o reino da caridade se regesse por outras leis senão pelos amores piedosos e mútuos dos que hão de reinar juntos, e pelos afetos puros de uns para com os outros e para com Deus.`
    },
    {
      n: 2,
      texto: `Há, porém, muita diferença no modo de operar, conforme a dignidade de cada operário. Deus faz o que quer pela simples facilidade do querer, sem agitação, sem movimento, sem condicionamento de lugar, de tempo, de causa ou de pessoa. Pois é o Senhor dos exércitos, que julga todas as coisas com tranquilidade (Sb 12,18). É também a Sabedoria que dispõe todas as coisas com suavidade (Sb 8,1). O anjo, por sua vez, não opera sem movimento, tanto de lugar como de tempo, mas sem agitação. O homem, porém, ao operar, não está livre nem da agitação do ânimo, nem do movimento do corpo e da alma. Enfim, manda-se-lhe operar a sua salvação com temor e tremor (Fl 2,12), e comer o seu pão com o suor do seu rosto (Gn 3,19).`
    },
    {
      n: 3,
      texto: `Explicado isto, considera agora comigo que, nesta obra tão magnífica da nossa salvação, há três coisas que Deus, o seu autor, reivindica para si, e nas quais se antecipa a todos os seus auxiliares e colaboradores: a predestinação, a criação e a inspiração. Destas, a predestinação não teve princípio, não digo no nascimento da Igreja, mas nem sequer no princípio do mundo, nem, enfim, neste ou naquele tempo: é antes dos tempos. A criação, por sua vez, é com o tempo; a inspiração faz-se já no tempo, onde e quando Deus quer. Segundo a predestinação, certamente, a Igreja dos eleitos nunca deixou de estar junto de Deus. Se o incrédulo se admira disto, ouça o que o fará admirar-se mais: nunca deixou de lhe ser agradável, nunca deixou de ser amada. Por que não diria com ousadia o segredo que me revelou do coração de Deus aquele pronto divulgador dos desígnios do alto? Falo de Paulo, que, como muitas outras coisas, também não temeu divulgar este segredo das riquezas da bondade de Deus, dizendo: Abençoou-nos com toda a bênção espiritual nos céus, em Cristo, assim como nos escolheu nele antes da constituição do mundo, para sermos santos e imaculados na sua presença, na caridade; e acrescenta: Ele nos predestinou para a adoção de filhos por Jesus Cristo, segundo o desígnio da sua vontade, para louvor da glória da sua graça, pela qual nos agraciou no seu Filho amado (Ef 1,3-6). E não há dúvida de que isto se diz na voz de todos os eleitos; e eles são a Igreja. Naquele seio tão profundo da eternidade, pois, antes que ela saísse à luz e à obra desta criação, quem, mesmo dentre os espíritos bem-aventurados, a poderia de algum modo encontrar, a não ser aquele a quem a quisesse revelar a própria eternidade, que é Deus?`
    },
    {
      n: 4,
      texto: `E mesmo quando, a um aceno do Criador, se viu surgir nestas espécies e formas feitas e visíveis, não foi logo encontrada por nenhum dos homens ou dos anjos, porque não era reconhecida, obscurecida pela imagem do homem terreno (cf. 1Cor 15,49) e coberta pela escuridão da morte. Pois sem este véu de confusão, comum a todos, nenhum dos filhos dos homens entrou nesta vida, exceto, é claro, um só, que entra sem mancha (cf. Sl 14,2). Este é o Emanuel, que, no entanto, também ele, tomado de nós, se revestiu por nós da nossa maldição (cf. Gl 3,13), e da semelhança do nosso pecado, não da sua realidade. Pois tens isto: apareceu em semelhança de carne de pecado, para condenar o pecado na carne por causa do pecado (Rm 8,3). De resto, a entrada é uma só para todos em tudo (cf. Sb 7,6), digo, para os eleitos e para os réprobos. Pois não há distinção. Todos pecaram (cf. Rm 3,22-23), e todos trazem o capuz da sua vergonha. Por isso, embora a Igreja existisse já criada entre as coisas feitas, nem assim podia ser encontrada ou reconhecida por criatura alguma, escondendo-se entretanto, de um e de outro modo admirável, tanto no seio da feliz predestinação como na massa da mísera condenação.`
    },
    {
      n: 5,
      texto: `Mas aquela que a Sabedoria, predestinando, tinha escondido desde a eternidade, e que o Poder, criando, de modo nenhum tinha manifestado desde o princípio, a graça, visitando, revelou-a no seu tempo, segundo a ação que acima chamei inspiração, porque do espírito do esposo se infundiu nos espíritos humanos alguma coisa para a preparação do Evangelho da paz (cf. Ef 6,15), isto é, para preparar o caminho do Senhor e do Evangelho da sua glória nos corações de todos os que estavam predestinados para a vida (cf. At 13,48). Em vão teriam trabalhado os vigias em pregar, se esta graça não os tivesse precedido. Mas agora, vendo a palavra correr velozmente (cf. Sl 147,15), e os povos das nações converter-se ao Senhor com toda a facilidade, as tribos e as línguas acorrer à unidade da fé, e os confins da terra reunir-se numa só mãe católica, conheceram as riquezas da graça, que estavam escondidas desde os séculos no segredo da predestinação eterna (cf. Ef 3,9), e alegraram-se de ter encontrado aquela que o Senhor, antes dos séculos, tinha escolhido para sua esposa.`
    },
    {
      n: 6,
      texto: `Daí fica claro, penso eu, que não foi à toa que a esposa declarou ter sido encontrada por eles; mas porque reconhecia que foi por eles recolhida, não escolhida; achada, não convertida. Pois a conversão de cada um deve atribuir-se àquele a quem todos têm necessidade de dizer aquela palavra do salmo: Converte-nos, ó Deus, nossa salvação (Sl 84,5). Mas talvez não lhe aplicasse com igual propriedade a palavra "encontrar" como a palavra "converter". E assim é, de fato. Ao Senhor não cabe encontrar, mas antecipar-se; e o antecipar-se exclui o encontrar. Enfim, que haveria de encontrar quem nunca ignorou coisa alguma? O Senhor conhece os que são seus, diz alguém (2Tm 2,19). E ele mesmo, que diz? Eu sei, diz, os que escolhi desde o princípio (Jo 13,18). Certamente, aquela que desde a eternidade conheceu de antemão, escolheu, amou e criou, não era razoável que se dissesse encontrada por ele. Mas direi com confiança que foi preparada por ele para ser encontrada. Pois quem viu deu testemunho, e sabemos que o seu testemunho é verdadeiro (Jo 19,35). Vi, diz, a cidade santa, a nova Jerusalém, que descia do céu, preparada por Deus como uma esposa enfeitada para o seu marido (Ap 21,2); e ele é um dos vigias que guardam a cidade. Mas ouve aquele mesmo que a preparou, como que apontando-a com o dedo aos vigias, mas sob outra figura: Levantai os vossos olhos, diz, e vede os campos, que já estão brancos — isto é, preparados — para a colheita (Jo 4,35). Por isso o pai de família convida os operários ao trabalho quando sente que tudo já está de tal modo preparado que, sem muito trabalho seu, possam gloriar-se e dizer: Somos colaboradores de Deus (1Cor 3,9). Pois que hão de fazer? Buscar a esposa e, tendo-a encontrado, falar-lhe do amado. Pois não buscarão a sua glória, mas a do esposo, porque são amigos do esposo (cf. Jo 3,29). E não terão de trabalhar muito junto dela por isto: ela está ali, e já o busca com toda a devoção; a tal ponto a sua vontade foi preparada pelo Senhor (cf. Pr 8,35).`
    },
    {
      n: 7,
      texto: `Enfim, antes que eles digam qualquer coisa, pergunta pelo amado; e, tendo sido ela mesma antecipada, antecipa-se aos seus pregadores, perguntando e dizendo: Vistes aquele a quem a minha alma ama (Ct 3,3)? Com razão, pois, declarou ter sido encontrada pelos que guardam a cidade, ela que sabia que já tinha sido conhecida de antemão pelo Senhor da cidade, e que ele se antecipara a ela, de modo que aqueles a encontrassem assim, e não a fizessem assim. Assim Cornélio foi encontrado por Pedro, e Paulo por Ananias; pois o Senhor já se antecipara a ambos e os tinha preparado. Quem mais preparado que Saulo, que já tinha clamado, com a mente e a voz suplicantes: Senhor, que queres que eu faça (At 9,6)? E não menos Cornélio, que, pelas suas esmolas e orações — inspiradas, é certo, pelo Senhor —, mereceu chegar à fé (At 10,4). Também Filipe encontrou Natanael (Jo 1,45); mas antes o Senhor já o tinha visto quando estava debaixo da figueira (Jo 1,48): e este olhar do Senhor não foi uma preparação? E conta-se também que André encontrou Simão, seu irmão (Jo 1,41); mas este tinha sido igualmente previsto e conhecido de antemão pelo Senhor, para ser chamado Cefas (Jo 1,42), como forte na fé.`
    },
    {
      n: 8,
      texto: `Lemos de Maria que foi achada tendo concebido do Espírito Santo (Mt 1,18). E penso que nisto a esposa do Senhor tem alguma coisa de semelhante à sua mãe. Pois, se também ela não tivesse sido achada com algo do Espírito Santo, de modo nenhum teria perguntado com tanta familiaridade aos que a encontraram por aquele de quem é esse Espírito. Não esperou que eles dissessem a que tinham vindo; ela mesma falou, e da abundância do coração: Vistes aquele a quem a minha alma ama? Sabia que são bem-aventurados os olhos que o viram (cf. Lc 10,23), e, admirando os que o tinham visto, dizia: Sois vós aqueles a quem foi dado ver aquele que tantos reis e profetas quiseram ver e não viram (cf. Lc 10,24)? Sois vós os que merecestes contemplar na carne a Sabedoria, no corpo a Verdade, no homem Deus? Muitos dizem: Ei-lo aqui, ei-lo ali; mas eu julgo mais seguro dar crédito a vós, que comestes e bebestes com ele depois que ressuscitou dos mortos (At 10,41). E fique isto dito sobre o que a esposa perguntou aos vigias. Se algo faltou, será completado noutro sermão. Agora, porém, por isto sobretudo fica claro que o Espírito Santo se antecipou a ela; e que pelos que guardam a cidade foi encontrada e reconhecida como sendo verdadeiramente aquela que Deus conheceu de antemão e predestinou antes dos séculos, e preparou para o seu Filho amado como delícias eternas pelos séculos eternos, para que seja santa e imaculada na sua presença (cf. Ef 1,4), germinando como o lírio e florescendo eternamente (cf. Os 14,6) diante do Senhor, Pai do meu Senhor Jesus Cristo, esposo da Igreja, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
