SERMOES.sermao({
  id: 'bernardo-cantico-16',
  colecao: 'bernardo-cantico',
  ordem: 16,
  numero: 'XVI',
  titulo: 'Da contrição do coração e das três qualidades da verdadeira confissão',
  fonte: 'De cordis contritione, et de tribus speciebus verae confessionis',
  argumento: `Bernardo começa pedindo paciência. Julgara que um sermão bastaria para atravessar «esta floresta sombria e cheia de esconderijos das alegorias», e já vai no terceiro — e ainda falta caminho.

Depois explica os sete bocejos do menino ressuscitado por Eliseu como as sete marcas de uma alma que voltou à vida: quatro de compunção e três de confissão. As quatro são dois pudores e dois temores, conforme se pense em Deus como pai, benfeitor, criador e Senhor. As três são as qualidades que a confissão precisa ter — humilde, simples e cheia de fé —, e cada uma se define pelo seu contrário, com exemplos de monges que se gabam dos próprios pecados, de Saul, de Adão, de Caim e de Judas.

Tradução feita do texto latino de Migne (PL 183, 848-855).`,
  pontos: [
    {
      n: 1,
      texto: `Que significa, então, este número sete? Não sei se haverá entre nós alguém tão simples que julgue inúteis essas repetições e fortuito este número. E também não tenho por vão que o profeta, debruçando-se sobre o morto, se tenha encolhido à medida do corpo de um menino, ajustando a sua boca à boca dele, os seus olhos aos olhos dele e as suas mãos às mãos dele (2Rs 4,34). O Espírito Santo fez que tudo assim acontecesse e assim se escrevesse, sem dúvida para instrução daqueles espíritos que a companhia infiel de um corpo corrompido cercou, e que a sabedoria tola do mundo ensinou a desatinar. Pois o corpo que se corrompe pesa sobre a alma, e a morada terrena deprime a mente que muito pensa (Sb 9,15). Por isso ninguém se admire nem leve a mal que eu me mostre curioso ao esquadrinhar estas coisas, como se fossem boticas do Espírito Santo; pois sei que é assim que se vive, e que nisso está a vida do meu espírito (Is 38,16). Digo, contudo, aos que se adiantam com o engenho e, em cada sermão, quase exigem o fim antes de terem apanhado o começo: sou devedor também dos mais lentos, e sobretudo deles; e o meu empenho não é tanto explicar palavras quanto embeber corações. Preciso tirar a água e dá-la a beber, e isso não se faz correndo depressa, mas tratando com cuidado e exortando muitas vezes. Aliás, o exame destes mistérios deteve-nos mais do que eu esperava. Confesso que julguei bastar um sermão para isso, e que atravessaríamos depressa esta floresta sombria e cheia de esconderijos das alegorias, chegando em cerca de um dia de caminho à planície dos sentidos morais. Mas aconteceu de outro modo: já gastamos dois dias nisso, e ainda falta caminho. O olhar, de longe, voava sobre os cimos dos ramos e os picos dos montes; mas a imensidão dos vales lá embaixo e a espessura dos matagais frustravam a vista. Acaso eu podia prever, por exemplo, que o milagre de Eliseu saltaria assim de repente para o meio, quando tratávamos da vocação das nações e da rejeição dos judeus? E agora, já que demos com ele, não nos pese demorar um pouco, para voltarmos depois, na sequência, ao que deixamos de lado; pois também isto é alimento para as almas. Também aos cães e aos caçadores acontece muitas vezes largarem a caça que haviam levantado e seguirem outra que lhes surge de improviso.`
    },
    {
      n: 2,
      texto: `Dá-me não pequena firmeza de confiança que aquele grande homem, profeta poderoso em obras e em palavras, descendo do alto monte dos céus, se tenha dignado visitar-me a mim, que sou cinza e pó; compadecer-se de um morto, inclinar-se sobre quem jazia, encolher-se e igualar-se a um pequeno, repartir com um cego a luz dos seus olhos, soltar uma boca muda com o beijo da sua própria boca e fortalecer mãos débeis com o contato das suas. Rumino isto com doçura, e as minhas entranhas se enchem, e o meu interior se nutre, e todos os meus ossos brotam em louvor. Isto fez ele uma vez para todos; e sentimos cada dia, cada um de nós, que se repete em nós: dá-se ao coração a luz da inteligência, à boca a palavra que edifica, às mãos a obra da justiça. Dá sentir com fidelidade, dá falar com proveito, dá cumprir com eficácia. E é uma corda de três fios, que dificilmente se rompe (Ecl 4,12), para tirar as almas do cárcere do diabo e arrastá-las atrás de si para os reinos celestes — se sentes com retidão, se falas com dignidade e se confirmas com a vida. Tocou os meus olhos com os seus, ornando a fronte do homem interior com duas luzes claras: a fé e a inteligência. Juntou a sua boca à minha e imprimiu num morto o sinal da paz; porque, quando ainda éramos pecadores, nos reconciliou com Deus (Rm 5,10), a nós que estávamos mortos para a justiça. Aplicou boca a boca, soprando outra vez no meu rosto o hálito da vida — mas de uma vida mais santa que a primeira; pois da primeira vez criou-me alma vivente, e da segunda refez-me espírito que vivifica (1Cor 15,45). Pôs as suas mãos sobre as minhas, dando-me o exemplo das boas obras e a forma da obediência. Ou então lançou as suas mãos a coisas fortes, para ensinar as minhas mãos para o combate e os meus dedos para a guerra (Sl 143,1).`
    },
    {
      n: 3,
      texto: `E o menino bocejou sete vezes (2Rs 4,35). Para manifestar a glória do milagre bastava bocejar uma só vez; mas a repetição e o número notável avisam de um mistério. Se olhares para aquele corpo imenso do gênero humano, a princípio sem vida, vês a Igreja bocejar por toda parte como que sete vezes, desde que recebeu a vida ao debruçar-se o profeta sobre ela; porque costuma louvar sete vezes ao dia. E, se olhares para ti mesmo, saberás que vives a vida espiritual e cumpres este número místico se submeteres os cinco sentidos aos dois mandamentos da caridade e ofereceres, como diz o Apóstolo, os teus membros para servir à justiça, para a santificação — os mesmos que antes ofereceste para servir à iniquidade, para a iniquidade (Rm 6,19); ou então se puseres esses mesmos cinco a serviço da salvação do próximo e acrescentares, para completar o sete, estas duas coisas: cantar a Deus a misericórdia e o juízo.`
    },
    {
      n: 4,
      texto: `Tenho ainda outros sete bocejos, isto é, sete experiências sem as quais não há salvação verdadeira e certa de um espírito que voltou à vida: quatro pertencem ao sentido da compunção, três ao som da confissão. Se vives, se há voz e há sentido, também tu reconheces em ti essas mesmas coisas. Saberás que recuperaste o sentido por inteiro se sentires a consciência mordida por uma quádrupla compunção: dois pudores e dois temores; pois, para completar o sete, a vida é atestada por três qualidades de confissão, de que se falará depois. E não guarda também o santo Jeremias este número no seu pranto? Também tu, pois, tendo no teu lamento por ti mesmo esse modelo profético, pensa em Deus como teu criador, pensa nele como benfeitor, pensa nele como pai, pensa nele como Senhor. És culpado diante de todos esses títulos: chora por cada um. Ao primeiro e ao último responda o teu temor; aos dois do meio, o teu pudor. De um pai, decerto, não se tem medo, justamente por ser pai; pois é próprio do pai compadecer-se sempre e perdoar. E, se bate, bate com a vara, não com o cajado; e, depois de bater, cura. É voz de pai esta: Eu ferirei, e eu curarei (Dt 32,39). Não há, portanto, por que temer um pai que às vezes fere para corrigir, mas nunca para se vingar. Mas, se penso que ofendi um pai, há decerto com que me envergonhar, ainda que não haja com que me aterrar. Ele me gerou de livre vontade, pela palavra da verdade (Tg 1,18), e não me lançou fora sob o aguilhão de um desejo carnal, como fez quem gerou a minha carne. E depois nem sequer poupou o Unigênito por aquele que assim gerou. Assim ele se mostrou pai para mim, mas eu não me mostrei filho para ele. Com que cara levanto agora os olhos para o rosto de um pai tão bom, eu, filho tão mau? Envergonho-me de ter feito coisas indignas da minha origem; envergonho-me de ter vivido como degenerado, tendo pai tão grande. Derramai torrentes de água, meus olhos; cubra a vergonha o meu rosto, banhe o pudor o meu semblante e o tome a escuridão. Consuma-se na dor a minha vida, e os meus anos em gemidos (Sl 30,11). Que vergonha! Que fruto tirei daquilo de que agora me envergonho? (Rm 6,21) Se semeei na carne, da carne não colherei senão corrupção (Gl 6,8); se semeei no mundo, também ele passa, e a sua concupiscência (1Jo 2,17). E então? Coisas caducas, vãs, quase nada, e cujo fim é a morte — e eu, infeliz e insensato, não me envergonhei de as preferir ao amor e à honra do Pai eterno. Envergonho-me, envergonho-me de ouvir: Se eu sou pai, onde está a minha honra? (Ml 1,6)`
    },
    {
      n: 5,
      texto: `E, mesmo que não fosse Pai, ele me esmagaria com benefícios. Levanta contra mim testemunhas — para calar outras sem conta —: o sustento deste corpo, o uso deste tempo e, acima de tudo, o sangue do Filho amado, que clama da terra (Gn 4,10). Envergonho-me da minha ingratidão; e, para cúmulo da vergonha, sou acusado até de ter pago males por bens e ódio por amor (Sl 108,5). De um benfeitor, é certo, não tenho o que temer, como também não de um pai; pois é verdadeiramente benfazejo: dá com abundância e não lança em rosto (Tg 1,5). Não lança em rosto os dons, porque são dons; e os seus benefícios deu-os a mim, não os vendeu. Enfim, os seus dons são sem arrependimento (Rm 11,29). Mas, quanto melhor penso dele, tanto mais indignamente sou levado a pensar de mim. Envergonha-te e sofre, minha alma; porque, ainda que a ele convenha não reclamar e não lançar em rosto, a nós de modo nenhum fica bem termos sido ingratos e esquecidos. Ai! Que hei de dar ao Senhor, ao menos agora, por tudo o que ele me deu? (Sl 115,12)`
    },
    {
      n: 6,
      texto: `E, se por acaso o pudor for lento e não cumprir o seu papel, que se desperte o temor em socorro. Que se desperte, para despertar. Põe de lado por um momento os nomes ternos de benfeitor e de pai, e volta-te para os mais austeros. Pois daquele de quem se lê Pai das misericórdias e Deus de toda consolação (2Cor 1,3) lê-se também: O Senhor é o Deus das vinganças (Sl 93,1); lê-se: Deus é juiz justo e forte (Sl 7,12); lê-se: Terrível nos seus desígnios sobre os filhos dos homens (Sl 65,5); lê-se: Deus zeloso (Ex 20,5). Ser pai e ser benfeitor é para ti; ser Senhor e criador é para ele — pois, como testemunha a Escritura, fez todas as coisas por causa de si mesmo (Pr 16,4). Ora, se ele defende e guarda para ti o que é teu, julgas que alguma vez não haverá de zelar pelo que é seu? Julgas que não reclamará a honra devida ao seu poder? Foi por isso que o ímpio irritou a Deus, porque disse no seu coração: Ele não vai reclamar (Sl 9,34). E que é dizer no coração «ele não vai reclamar», senão não temer que reclame? Mas há de reclamar até o último centavo; há de reclamar e retribuir com abundância aos que agem com soberba (Sl 30,24). Reclamará do que foi redimido o serviço; e do que modelou, a honra e a glória.`
    },
    {
      n: 7,
      texto: `Admita-se que o pai dissimule e o benfeitor perdoe; mas o Senhor e Criador, não. E quem poupa o filho não poupará a obra que modelou, não poupará o servo mau. Pesa que pavor e que horror é ter desprezado aquele que te fez, e que fez todas as coisas, e ter ofendido o Senhor da majestade. É próprio da majestade ser temida, é próprio do Senhor ser temido — e sobretudo desta majestade e deste Senhor. Pois, se as leis humanas mandam punir com a morte quem é réu de lesa-majestade, ainda que humana, qual será o fim dos que desprezam a onipotência divina? Toca os montes, e eles fumegam (Sl 143,5) — e um pozinho vil ousa irritar majestade tão tremenda, ele que um sopro leve logo dispersará, sem que ninguém consiga recolhê-lo? É a ele, a ele que se deve temer: àquele que, depois de matar o corpo, tem poder de lançar também na geena (Lc 12,5). Tenho pavor da geena, tenho pavor do rosto do juiz, temível até às próprias potestades angélicas. Tremo diante da ira do poderoso, diante da face do seu furor, do estrondo do mundo a desabar, do incêndio dos elementos, da tempestade violenta, da voz do arcanjo e da palavra áspera. Tremo diante dos dentes da besta do inferno, do ventre da mansão dos mortos, dos que rugem já preparados para devorar. Horrorizo-me com o verme que rói e o fogo que queima, com o fumo, o vapor, o enxofre e o vento das procelas; horrorizo-me com as trevas exteriores. Quem dará água à minha cabeça e aos meus olhos uma fonte de lágrimas (Jr 9,1), para que eu previna com o choro de agora aquele choro, e o ranger de dentes, e as duras amarras das mãos e dos pés, e o peso de cadeias que apertam, prendem, queimam e não consomem? Ai de mim, minha mãe! Por que me geraste filho de dor, filho de amargura, de indignação e de pranto eterno? Por que fui recebido nos joelhos e amamentado a peitos, se nasci para a fogueira e para ser comida do fogo?`
    },
    {
      n: 8,
      texto: `Quem assim se comove recuperou sem dúvida o sentido, e nesse duplo temor e naquele pudor igualmente duplo tem os quatro bocejos. Os três que faltam há de acrescentá-los a voz da confissão; e já não se dirá dele que não há voz nem sentido — contanto, porém, que essa confissão proceda de um coração humilde, simples e cheio de fé. Confessa, pois, com humildade, com limpeza e com fé, tudo o que te morde a consciência; e terás cumprido essas repetições. Há os que se gloriam depois de fazer o mal e exultam com as piores coisas (Pr 2,14); e o profeta, apontando-os, diz: Publicaram os seus pecados como Sodoma (Is 3,9). Mas afasto esses da nossa discussão, como mundanos; pois que temos nós com os que estão fora? (1Cor 5,12)`
    },
    {
      n: 9,
      texto: `Ainda que também entre os que trazem hábito religioso e professaram a vida religiosa tenhamos ouvido alguns recordar e gabar-se, com a maior desfaçatez, dos seus males passados: por exemplo, o que fizeram outrora com valentia num combate de armas, ou com agudeza num embate de letras, ou qualquer outra coisa lisonjeira segundo a vaidade do mundo, mas nociva, perniciosa e danosa para a salvação da alma. Isto é sinal de um espírito ainda mundano; e o hábito humilde que tais homens vestem não é mérito de uma santa novidade, mas tampa que cobre a velhice antiga. Alguns recordam essas coisas como quem sofre e se arrepende; mas, procurando na intenção a própria glória, não apagam o que cometeram: enganam-se a si mesmos, pois de Deus ninguém zomba (Gl 6,7). Não despiram o homem velho: cobrem-no com o novo. Com tal confissão o fermento velho não é denunciado nem lançado fora: é consolidado, conforme aquilo: Envelheceram os meus ossos, enquanto eu clamava todo o dia (Sl 31,3). Envergonha-me lembrar o atrevimento de alguns, que não se envergonham de se gabar, com uma alegria de dar pena, de terem — já depois de tomar o hábito santo — derrubado alguém com astúcia e enganado um irmão num negócio; ou de terem devolvido com ousadia injúria por injúria e maldição por maldição, isto é, mal por mal.`
    },
    {
      n: 10,
      texto: `Mas há uma confissão tanto mais perigosamente nociva quanto mais sutilmente vã: quando não tememos descobrir de nós até o que é desonroso e torpe — não por sermos humildes, mas para que nos julguem humildes. Ora, buscar louvor pela humildade não é virtude de humildade: é a sua ruína. O verdadeiro humilde quer ser tido por desprezível, não ser proclamado humilde. Alegra-se de ser desprezado, e é soberbo só nisto: em desprezar os louvores. Que há de mais perverso e de mais indigno do que a confissão, guardiã da humildade, servir à soberba — e quereres parecer melhor justamente por onde pareces pior? Espantosa espécie de gabolice: não poderes ser tido por santo se não pareceres criminoso. Tal confissão, que tem a aparência da humildade e não a virtude, não só não merece perdão, mas até provoca a ira. De que serviu a Saul confessar que pecara, quando Samuel o repreendeu? (1Sm 15,30) Culpável foi, sem dúvida, aquela confissão que não apagou a culpa. Pois quando é que o mestre da humildade desprezaria uma confissão humilde — ele, a quem é próprio por natureza dar graça aos humildes? De modo nenhum poderia deixar de se aplacar, se a humildade que soou na boca tivesse brilhado no coração. Eis por que eu disse que a confissão deve ser humilde.`
    },
    {
      n: 11,
      texto: `Mas é preciso que seja também simples. Que ninguém tenha gosto em desculpar a intenção, se é culpada, só porque ela escapa aos homens; nem em aliviar uma culpa que é grave; nem em pô-la à sombra da persuasão alheia, quando ninguém o forçou contra a vontade. O primeiro caso não é confissão, é defesa; e não aplaca: provoca. O segundo mostra ingratidão; e, quanto menor se julga a culpa, tanto menor fica a glória de quem perdoa. E dá-se de menos bom grado o benefício que se sente menos agradecido e menos necessário. Por isso nega a si mesmo o perdão quem diminui o dom de quem o dá; e é o que faz todo aquele que tenta aliviar com palavras a própria culpa. Do último caso, enfim, desaconselhe-nos o exemplo do primeiro homem, que não negou a culpa e, contudo, não alcançou o perdão — sem dúvida por ter misturado nela a culpa da mulher (Gn 3,12). É uma forma de desculpa acusar outro quando és tu o repreendido. E, quanto a quereres desculpar-te quando te corrigem, pergunta ao santo Davi como isso não é só inútil, mas pernicioso. Ele chama palavras de malícia às desculpas nos pecados, e pede e suplica que o seu coração não se incline para elas (Sl 140,4). E com razão: peca contra a própria alma quem se desculpa, pois afasta de si o remédio do perdão e assim fecha para si mesmo, com a própria boca, a porta da vida. E que maior malícia há do que armar-se contra a própria salvação e trespassar-se a si mesmo com a ponta da própria língua? Enfim, quem é mau para si, para quem será bom? (Eclo 14,5)`
    },
    {
      n: 12,
      texto: `Seja também cheia de fé a confissão: confessa na esperança, sem desconfiar de modo algum do perdão; não aconteça que com a tua boca, em vez de te justificares, te condenes. Judas, o traidor do Senhor, e Caim, o fratricida, confessaram — e desconfiaram. Um disse: Pequei, entregando sangue inocente (Mt 27,4); o outro: A minha iniquidade é maior do que o perdão que eu possa merecer (Gn 4,13). E, ainda que verdadeira, de nada lhes valeu uma confissão sem fé. Estas três exigências da confissão, juntas às quatro anteriores da compunção, completam o número sete.`
    },
    {
      n: 13,
      texto: `E agora, assim compungido e assim confessado, e por isso certo da tua própria vida, estás também certo, creio eu, de que não é com nome vazio que se chama Jesus aquele que pôde e quis fazer em ti tais coisas; e de que ele não veio em vão atrás do bordão que enviara adiante. Não veio em vão, porque não veio vazio. Pois como estaria vazio aquele em quem habitou a plenitude? É que a ele não se deu o Espírito por medida (Jo 3,34). E veio na plenitude do tempo (Gl 4,4), mostrando assim que vinha cheio. Bem cheio estava aquele a quem o Pai ungiu com óleo de alegria mais que aos seus companheiros (Sl 44,8); ungiu-o e enviou-o cheio de graça e de verdade (Jo 1,14). Ungiu-o para que ele ungisse. Foram ungidos por ele todos os que mereceram receber da sua plenitude. Por isso diz: O Espírito do Senhor está sobre mim, porque me ungiu; enviou-me a anunciar aos mansos, a curar os contritos de coração, a pregar o perdão aos cativos e a abertura aos que estão presos, a anunciar o ano de graça do Senhor (Is 61,1-2). Vinha, como ouves, ungir as nossas feridas e aliviar as dores; e por isso veio ungido, veio manso e suave, e cheio de misericórdia para todos os que o invocam (Sl 85,5). Sabia que descia até doentes, e mostrou-se tal como convinha. E, como eram muitas as doenças, o médico previdente cuidou de trazer também muitos remédios. Trouxe o espírito de sabedoria e de inteligência, o espírito de conselho e de fortaleza, o espírito de ciência e de piedade, e o espírito do temor do Senhor (Is 11,2-3).`
    },
    {
      n: 14,
      texto: `Vês quantos frascos cheios de aromas preparou o médico celeste para curar as feridas daquele desgraçado que caiu nas mãos dos salteadores? São sete, talvez ajustados aos sete bocejos de que falamos, para despertá-los; pois nos frascos estava o espírito da vida. Foi deles que derramou óleo nas minhas feridas; derramou também vinho, mas menos que óleo. Assim convinha às minhas fraquezas: que a misericórdia se exaltasse acima do juízo, assim como o óleo, derramado no vinho, sobrenada. Trouxe, pois, cinco cântaros de óleo e apenas dois de vinho. O vinho foram só o temor e a fortaleza; os outros cinco significam o óleo pela suavidade que lhes é própria. Foi no espírito de fortaleza que ele, como um valente tomado pelo vinho (Sl 77,65), desceu à mansão dos mortos, quebrou as portas de bronze e partiu os ferrolhos de ferro (Sl 106,16); amarrou o forte e arrebatou os despojos do cativeiro. Desceu também no espírito do temor — mas como quem deve ser temido, não como quem teme.`
    },
    {
      n: 15,
      texto: `Ó Sabedoria! Com que arte de curar restauras, no vinho e no óleo, a saúde da minha alma — suave com força e forte com suavidade! Forte a meu favor, suave para mim. Enfim, alcanças com força de um extremo a outro e dispões tudo com suavidade (Sb 8,1), repelindo o inimigo e amparando o doente. Cura-me, Senhor, e ficarei curado (Jr 17,14); cantarei e louvarei o teu nome, e direi: Óleo derramado é o teu nome (Ct 1,2). Não vinho derramado — pois não quero que entres em juízo com o teu servo (Sl 142,2) —, mas óleo, porque me coroas de misericórdia e de compaixões (Sl 102,4). Óleo, sim: porque, sobrenadando em todos os líquidos com que se mistura, significa com clareza aquele nome que está acima de todo nome (Fl 2,9). Ó nome suavíssimo e docíssimo! Ó nome ilustre, escolhido, altíssimo, exaltado acima de tudo pelos séculos! Este é verdadeiramente o óleo que alegra o rosto do homem (Sl 103,15), que unge a cabeça de quem jejua (Mt 6,17), para que não sinta o óleo do pecador (Sl 140,5). Este é o nome novo que a boca do Senhor pronunciou (Is 62,2), e que o anjo lhe deu antes de ser concebido no ventre (Lc 2,21). Não só o judeu: todo aquele que o invocar será salvo (Jl 2,32), de tal modo se derramou por toda parte. Foi este o nome que o Pai deu ao Filho, esposo da Igreja, Nosso Senhor Jesus Cristo, que é Deus sobre todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
