SERMOES.sermao({
  id: 'bernardo-cantico-80',
  colecao: 'bernardo-cantico',
  ordem: 80,
  numero: 'LXXX',
  titulo: 'Discussão sutil sobre a imagem, isto é, o Verbo de Deus, e sobre a alma, que é feita à imagem; e do erro de Gilberto, bispo de Poitiers',
  fonte: 'De imagine sive Verbo Dei, et anima quae ad imaginem est',
  argumento: `Alguns monges queixam-se de que os últimos sermões, ocupados com Cristo e a Igreja, lhes deram pouco sal moral; Bernardo volta, pois, ao versículo "No meu pequeno leito busquei...", para aplicá-lo ao Verbo e à alma. O que une a alma ao Verbo é o parentesco: o Verbo é a imagem de Deus, e a alma é feita à imagem e semelhança. A imagem é reta e grande; a alma é grande pela capacidade das coisas eternas e reta pelo desejo das do alto. Mas no Verbo a grandeza e a retidão são uma só coisa, e uma só coisa com ele, porque as tem por geração, da substância do Pai; na alma são distintas dela e entre si: o pecador perde a retidão e fica curvado para a terra, mas conserva a grandeza, e por isso há esperança de salvação — "o homem passa em imagem", coxeando de um pé.

Só Deus é absolutamente simples: nele a grandeza, a bondade, a sabedoria e a divindade são o próprio Deus. Daí a condenação dos novos dialéticos que dizem que "a divindade não é Deus", e de Gilberto, bispo de Poitiers, cuja explicação de Boécio o papa Eugênio e os bispos reprovaram no concílio de Reims; Gilberto retratou-se, mas há quem continue a copiar o livro. Bernardo faz esta digressão como antídoto, antes de tratar da semelhança.

Tradução feita do texto latino de Migne (PL 183, 1166-1171).`,
  pontos: [
    {
      n: 1,
      texto: `Alguns de vós, como soube, suportam de má vontade que, há já alguns dias, enquanto me agrada deter-me no pasmo e na admiração dos mistérios, o sermão que vos sirvo não tenha sido temperado com nenhum sal moral, ou com muito pouco. Isto, é verdade, fora do costume. Mas é permitido rever o que foi dito? Não avanço sem antes percorrer tudo de novo. Eia, dizei, se vos lembrais, a partir de que passagem da Escritura começou esta privação, para eu recomeçar dali. Cabe a mim reparar o prejuízo, ou antes, ao Senhor, de quem tudo esperamos. De que princípio, pois, devemos retomar? Daqui: No meu pequeno leito, durante as noites, busquei aquele a quem a minha alma ama (Ct 3,1)? Se não me engano, daqui. A partir daí, e dali em diante, o meu único cuidado foi, dissipada a densa névoa destas alegorias, pôr à luz as delícias secretas de Cristo e da Igreja. Voltemos, pois, a investigar o sentido moral. Pois não me poderá ser penoso o que vos for proveitoso (cf. Fl 3,1). E isto se fará convenientemente se aplicarmos igualmente ao Verbo e à alma o que foi dito de Cristo e da Igreja.`
    },
    {
      n: 2,
      texto: `Mas alguém me diz: Por que juntas tu estas duas coisas? Que há de comum entre a alma e o Verbo? Muito, de todos os modos (cf. Rm 3,2). Primeiro, porque é tão grande o parentesco das naturezas, que este é a imagem, e aquela é feita à imagem. Depois, porque a semelhança atesta o parentesco. Pois não foi feita só à imagem, mas também à semelhança (cf. Gn 1,26). Perguntas em que é semelhante? Ouve primeiro sobre a imagem. O Verbo é a verdade, é a sabedoria, é a justiça: e estas são a imagem. De quê? Da justiça, da sabedoria e da verdade. Pois esta imagem é justiça da justiça, sabedoria da sabedoria, verdade da verdade, como luz da luz, Deus de Deus. Nenhuma destas coisas é a alma, porque não é a imagem. É, contudo, capaz delas e deseja-as; e talvez seja daí que é feita à imagem. Criatura elevada, que traz na capacidade a marca da majestade, e no desejo a da retidão. Lemos que Deus fez o homem reto (Ecl 7,30); e que o fez grande prova-o, como se disse, a capacidade. Pois o que é feito à imagem deve convir com a imagem, e não participar em vão do nome de imagem, assim como a própria imagem não se chama imagem por um nome só, ou vazio. Tens, com efeito, a respeito daquele que é a imagem, que, estando na forma de Deus, não julgou usurpação ser igual a Deus (Fl 2,6). Aqui se te indica a sua retidão, na forma de Deus, e a sua majestade, na igualdade; de modo que, comparando-se retidão com retidão e grandeza com grandeza, se veja que o que é feito à imagem e a imagem se correspondem harmoniosamente, assim como também a imagem corresponde, numa e noutra coisa, àquele de quem é imagem. Pois é dele que ouvistes o santo Davi cantar nos salmos, ora: Grande é o nosso Senhor, e grande o seu poder (Sl 146,5); ora: Reto é o Senhor nosso Deus, e não há nele iniquidade (Sl 91,16). Deste Deus reto e grande tem a sua imagem o ser também ela reta e grande; e tem-no a alma, que é feita à imagem.`
    },
    {
      n: 3,
      texto: `Mas digo: Não tem, pois, a imagem nada mais que a alma feita à imagem, já que também a esta atribuímos o ser grande e reta? Tem, e muitíssimo. Esta recebeu com medida; aquela, na igualdade. Não é isto mais? Repara ainda noutra coisa. A esta, uma e outra coisa deu-as a criação ou a condescendência; àquela, a geração. E não há dúvida de que isto é mais magnífico. E ninguém negará que é também mais eminente isto: que a esta uma e outra coisa foram dadas por Deus, e àquela vêm de Deus, isto é, da substância de Deus. Pois a imagem de Deus é consubstancial a Deus, e tudo o que parece ser comunicado a esta sua imagem é, em ambos, substancial, não acidental. Repara ainda numa coisa em que a imagem sobressai não pouco. O grande e o reto — quem não sabe que estas duas coisas diferem entre si por natureza? — são na imagem uma só coisa. E não só: são uma só coisa também com a imagem. Pois para a imagem, não só ser reta é o mesmo que ser grande, mas também ser grande e reta é o mesmo que ser. Na alma não é assim. A sua grandeza e a sua retidão são distintas dela e distintas entre si. Pois, se, como ensinei acima, a alma é grande porque é capaz das coisas eternas, e reta porque deseja as do alto, aquela que não busca nem gosta das coisas do alto, mas das que estão sobre a terra (cf. Cl 3,2), certamente não é reta, mas curvada; e, no entanto, nem por isso deixa de ser grande, permanecendo, mesmo assim, capaz da eternidade. Pois nunca deixará de ser capaz dela, ainda que nunca a receba, para que seja como está escrito: Contudo, o homem passa em imagem (Sl 38,7); mas só em parte, para que a eminência do Verbo se mostre pela sua própria integridade. Pois como cairia o Verbo da grandeza ou da retidão, se as tem de tal modo que é aquilo que tem? Ou então é só em parte para que, se fosse privada de tudo, não lhe restasse esperança de salvação. Pois, se deixasse de ser grande, deixaria também de ser capaz — já que, como disse, a grandeza da alma se mede pela capacidade. E que poderia esperar aquilo de que não fosse capaz?`
    },
    {
      n: 4,
      texto: `Assim, pela grandeza, que conserva mesmo perdida a retidão, o homem passa em imagem, como que coxeando de um pé, e feito filho estrangeiro. Pois penso que de tais se disse: Os filhos estrangeiros mentiram-me; os filhos estrangeiros envelheceram e coxearam, afastando-se das suas veredas (Sl 17,45-46). Belamente foram chamados filhos estrangeiros: filhos, pela grandeza conservada; estrangeiros, pela retidão perdida. E não teria dito: coxearam, mas: caíram, ou coisa semelhante, se os homens se tivessem despojado inteiramente da imagem. Mas agora, segundo a grandeza, o homem passa em imagem; quanto à retidão, como que coxeando, é perturbado e derrubado da imagem, dizendo assim a Escritura: Contudo, o homem passa em imagem; mas em vão se perturba (Sl 38,7). Em vão, inteiramente: pois segue-se: Entesoura, e não sabe para quem ajuntará (Sl 38,7). Por que não sabe, senão porque, inclinando-se para estas coisas baixas e terrenas, entesoura terra para si? Não sabe, com efeito, daquilo que confia à terra, para quem o ajuntará: se para a traça que destrói, se para o ladrão que escava (cf. Mt 6,19), se para o inimigo que saqueia, se para o fogo que devora. E daí vem ao homem infeliz, que se curva e se deita sobre as coisas da terra, aquela voz lamentosa do salmo: Tornei-me miserável e fiquei curvado até o fim; andava triste o dia inteiro (Sl 37,7). Pois experimenta em si mesmo a verdade daquela sentença do Sábio: Deus fez o homem reto, mas ele se enredou em muitas dores (Ecl 7,30). E logo se lhe dirige a voz do escárnio: Curva-te, para que passemos (Is 51,23).`
    },
    {
      n: 5,
      texto: `Mas de onde viemos parar aqui? Daquilo que queríamos ensinar: que o reto e o grande — este duplo bem com que tínhamos definido a imagem — não são uma só coisa na alma, nem com a alma, assim como ensinamos, com igualmente fiel afirmação, que são uma só coisa no Verbo e com o Verbo. Quanto à retidão, fica claro pelo que se disse que é distinta da alma e da grandeza da alma, pois, mesmo não existindo ela, a alma permanece, e grande. Mas de onde se mostrará a distinção entre a grandeza e a alma? Pois não se pode mostrar pelo mesmo caminho por que se mostrou a da retidão e da alma, visto que a alma não pode ser privada da sua grandeza como pode ser privada da retidão. Contudo, a sua grandeza não é a alma. Pois, embora a alma não se encontre sem a sua grandeza, esta se encontra também fora da alma. Perguntas onde? Nos anjos. Pois os anjos são grandes pelo mesmo motivo por que se prova a grandeza da alma: pela capacidade da eternidade. E, se ficou estabelecido que a alma difere da sua retidão por poder carecer dela, por que não ficaria igualmente claro que é distinta também da sua grandeza, que não pode reivindicar como só sua? Assim, não estando aquela em toda alma, nem esta só na alma, é claro que ambas diferem igualmente dela. Além disso: nenhuma forma é aquilo de que é forma. Ora, a grandeza é forma da alma. E não deixa de ser forma por ser inseparável dela. Pois isso mesmo são todas as diferenças substanciais; isso, não só os próprios em sentido estrito, mas também certas propriedades; isso, também inúmeras outras formas. A alma não é, pois, a sua grandeza, não mais que o corvo é a sua negrura, a neve a sua brancura, o homem a sua capacidade de rir ou a sua racionalidade; e, no entanto, nunca encontrarás o corvo sem negrura, nem a neve sem brancura, nem homem que não seja capaz de rir e racional. Assim também a alma e a grandeza da alma, embora inseparáveis, são distintas uma da outra. Como não seriam distintas, se esta está num sujeito, e aquela é sujeito e substância? Só a natureza suprema e incriada, que é Deus Trindade, reivindica para si esta pura e singular simplicidade da sua essência, de modo que nela não se encontra uma coisa e outra, nem um lugar e outro, nem sequer um modo e outro. Pois, permanecendo em si, é o que tem, e o que é, é-o sempre e de um só modo. Nela, as muitas coisas se reduzem a uma, e as diversas ao mesmo, de modo que nem tira pluralidade do grande número das coisas, nem sente alteração pela variedade. Contém todos os lugares e ordena cada coisa no seu lugar, sem estar contida em lugar nenhum. Os tempos passam debaixo dela, não para ela. Não espera o futuro, não relembra o passado, não experimenta o presente.`
    },
    {
      n: 6,
      texto: `Longe de nós, caríssimos, longe estes novatos, não dialéticos, mas hereges, que sustentam com a maior impiedade que a grandeza pela qual Deus é grande, e igualmente a bondade pela qual é bom, a sabedoria pela qual é sábio e a justiça pela qual é justo, enfim, a divindade pela qual é Deus, não são Deus. Pela divindade, dizem, Deus é Deus; mas a divindade não é Deus. Talvez não se digne ser Deus aquela que é tão grande que faz Deus! Mas, se não é Deus, que é? Pois ou é Deus, ou alguma coisa que não é Deus, ou nada. Não admites que seja Deus; mas, penso eu, também não admitirás que seja nada, aquela que confessas ser tão necessária a Deus que não só Deus não pode existir sem ela, mas é por ela que existe. E, se é alguma coisa que não é Deus, ou será menor que Deus, ou maior, ou igual. Mas como seria menor, se é por ela que Deus é? Resta que a confesses maior ou igual. Mas, se é maior, ela é o sumo bem, e não Deus; se é igual, há dois sumos bens, e não um: e uma e outra coisa repugnam ao sentir católico. Quanto à grandeza, à bondade, à justiça e à sabedoria, pensamos em tudo o mesmo que da divindade: são uma só coisa em Deus e com Deus. Pois não é bom por outra coisa senão por aquilo por que é grande, nem justo ou sábio por outra coisa senão por aquilo por que é grande e bom, nem, enfim, é todas estas coisas juntas por outra coisa senão por aquilo por que é Deus; e isto também só por si mesmo.`
    },
    {
      n: 7,
      texto: `Mas diz o herege: Quê? Negas que Deus seja Deus pela divindade? Não; mas afirmo que essa mesma divindade pela qual ele é, é também Deus, para não admitir que haja alguma coisa mais excelente que Deus. Pois também digo que é grande pela grandeza, mas pela grandeza que é ele mesmo, para não pôr alguma coisa maior que Deus; e confesso que é bom pela bondade, mas não por outra senão a que é ele mesmo, para não parecer ter encontrado alguma coisa melhor que ele; e do mesmo modo quanto ao resto. Seguro e de bom grado, sem tropeço, como se diz, sigo a sentença daquele que dizia: "Deus não é grande senão por aquela grandeza que é o que ele mesmo é; de outro modo, aquela grandeza será maior do que Deus". Este é Agostinho, fortíssimo martelo dos hereges. Se, pois, se pode dizer de Deus alguma coisa com propriedade, será mais correto e conveniente dizer: Deus é grandeza, bondade, justiça, sabedoria, do que: Deus é grande, bom, justo ou sábio.`
    },
    {
      n: 8,
      texto: `Por isso, não sem razão, no concílio que o papa Eugênio celebrou recentemente em Reims, pareceu, tanto a ele como aos outros bispos, perversa e de todo suspeita aquela explicação do livro de Gilberto, bispo de Poitiers, em que comentava deste modo as palavras de Boécio sobre a Trindade, que são perfeitamente sãs e católicas: "O Pai é a verdade, isto é, verdadeiro; o Filho é a verdade, isto é, verdadeiro; o Espírito Santo é a verdade, isto é, verdadeiro. E estes três juntos não são três verdades, mas uma só verdade, isto é, um só verdadeiro". Ó explicação obscura e perversa! Quanto mais verdadeira e sãmente teria dito, ao contrário: O Pai é verdadeiro, isto é, a verdade; o Filho é verdadeiro, isto é, a verdade; o Espírito Santo é verdadeiro, isto é, a verdade. E estes três são um só verdadeiro, isto é, uma só verdade. O que teria feito, se se dignasse imitar São Fulgêncio, que diz: "A única verdade do único Deus — ou antes, a única verdade que é o único Deus — não permite que se juntem o serviço e o culto do Criador e da criatura". Bom corretor seria aquele que falasse com toda a verdade da verdade, que sentisse com piedade e catolicidade a verdadeira e pura simplicidade da substância divina, na qual nada pode haver que não seja ela mesma, e ela mesma é Deus. Embora em alguns outros lugares aquele livro do referido bispo tenha parecido afastar-se mais manifestamente da retidão da fé; dos quais cito ainda um, como exemplo. Pois, dizendo o autor: "Quando se diz: Deus, Deus, Deus, refere-se à substância", o nosso comentador acrescentou: "Não à que ele é, mas àquela pela qual ele é". Longe esteja da Igreja católica admitir que haja uma substância, ou qualquer coisa, pela qual Deus seja Deus e que não seja Deus!`
    },
    {
      n: 9,
      texto: `Mas não dizemos isto contra ele, pois, naquela mesma assembleia, submetendo-se humildemente à sentença dos bispos, condenou pela própria boca tanto isto como as outras coisas que se acharam dignas de repreensão; mas por causa daqueles que, segundo se diz, ainda copiam e leem aquele livro, contra a proibição apostólica ali promulgada, persistindo com espírito de contenda em seguir o bispo naquilo em que ele mesmo não se manteve, e preferindo tê-lo por mestre do erro a tê-lo por mestre da correção. E não só, mas também por vossa causa, aproveitando a ocasião da diferença entre a imagem e a alma feita à imagem, julguei que valia a pena fazer esta digressão: para que, se alguns por acaso beberam alguma vez das águas furtadas, que parecem mais doces (Pr 9,17), tomando o antídoto, as vomitem; e, purificado o estômago da mente, passando ao que, segundo a nossa promessa, resta dizer sobre a semelhança, bebam com alegria águas já mais puras, não das nossas fontes, mas das fontes do Salvador (cf. Is 12,3), o esposo da Igreja, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
