SERMOES.sermao({
  id: 'bernardo-cantico-71',
  colecao: 'bernardo-cantico',
  ordem: 71,
  numero: 'LXXI',
  titulo: 'Dos lírios espirituais, isto é, das boas obras, cuja cor é a reta consciência e cujo perfume é a boa fama; de como o esposo nos apascenta e se apascenta de nós; e da unidade de Deus Pai com o Filho, e da alma santa com Deus',
  fonte: 'De liliis spiritualibus',
  argumento: `O esposo é lírio, mas não "entre espinhos", porque não tem pecado; e quem quer que ele habite em si deve ter lírios: obras cuja cor — a intenção do coração, julgada pela consciência — seja branca, e cujo perfume seja a boa fama. A fama não faz virtude do que a consciência condena; e dão brancura à obra a alegria de quem dá e a simplicidade sem dolo. Apascentar-se entre os lírios é deleitar-se com as virtudes, como Cristo em casa de Marta e Maria, que ao mesmo tempo as alimentava. Ele nos apascenta e se apascenta de nós: come-nos quando nos repreende, instrui e transforma, e é comido por nós, para que estejamos nele e ele em nós.

Daí uma longa distinção: o Pai e o Filho são "uma só coisa" pela unidade da essência, que não se produz, mas é eterna; Deus e a alma que se une a ele são "um só espírito" pela concordância das vontades na caridade — união feliz, se a experimentares; nenhuma, se a comparares. Por fim, uma terceira leitura do versículo: a palavra de Deus, que é o esposo, fica em jejum quando não é obedecida e nutre-se da obediência; mas não toca no que vem de mãos espinhosas, nem nas observâncias do monge em que se encontra a vontade própria.

Tradução feita do texto latino de Migne (PL 183, 1121-1128).`,
  pontos: [
    {
      n: 1,
      texto: `O fim do sermão anterior é o começo deste. O esposo, pois, é lírio, mas não lírio entre espinhos, porque não tem espinhos aquele que não cometeu pecado (cf. 1Pd 2,22). Enfim, declarou que a esposa é lírio entre espinhos (Ct 2,2); porque, se também ela disser que não tem espinhos, engana-se a si mesma, e a verdade não está nela (cf. 1Jo 1,8). A si mesmo, porém, declarou-se flor e lírio, mas não entre espinhos. Antes: Eu, diz, sou a flor do campo e o lírio dos vales (Ct 2,1). E não há menção de espinhos, porque é o único dos homens que não tem necessidade de dizer: Revolvi-me na minha aflição, enquanto se crava o espinho (Sl 31,4). Nunca está, pois, sem lírios aquele que está sempre sem vícios; porque é todo e sempre branco, o mais belo dos filhos dos homens (Sl 44,3). Tu, pois, que ouves ou lês estas coisas, procura ter lírios contigo, se queres ter habitando em ti este habitante dos lírios. A tua obra, o teu empenho, o teu desejo: que uma certa brancura e um certo perfume morais das próprias coisas atestem que são lírios. Também os costumes têm as suas cores, e têm os seus perfumes. Pois nas coisas do espírito a cor e o perfume não são a mesma coisa, não mais que nos corpos. Sobre a cor, consulte-se, pois, a consciência; sobre o perfume, a fama. Tornastes fétido o nosso cheiro diante do Faraó e dos seus servos, dizem aqueles (Ex 5,21), falando da reputação. A cor, por sua vez, dão-na à tua obra a intenção do coração e o juízo da consciência. Negros são os vícios, a virtude é branca. Entre esta e aqueles, a consciência, consultada, discerne. Permanece a sentença do Senhor sobre o olho mau e o olho luminoso (Mt 6,22-23), porque entre o branco e o negro fixou limites certos e separou a luz das trevas (cf. Gn 1,4). O que sai, pois, de um coração puro e de uma consciência boa (cf. 1Tm 1,5) é branco, e é virtude; e, se também a boa fama o seguir, é lírio, pois não lhe falta nem a brancura do lírio nem o seu perfume.`
    },
    {
      n: 2,
      texto: `E a virtude, embora não se torne por isso maior, torna-se mais bela e mais ilustre. Mas, se houver na consciência algum sinal escuro, também o que dela sair não estará sem ele. Pois, se a raiz está viciada, também o ramo (cf. Rm 11,16). E por isso, seja o que for que a raiz viciada produza de si, não sem transmitir o vício — por exemplo, uma palavra, uma ação, uma oração —, ainda que a fama pareça aplaudi-la, não há por que se chamar lírio; porque, ainda que o perfume pareça estar de acordo, a cor não está. Pois como seria lírio com o sinal escuro da impureza? Nem a fama poderá reivindicar para a virtude o que a consciência tiver provado ser vício. A virtude se contentará com a brancura da consciência, quando não puder segui-la o perfume da fama; mas o perfume da fama não bastará para desculpar o vício de uma consciência descorada. O homem de virtude, contudo, procurará sempre, quanto está nele, fazer o bem não só diante de Deus, mas também diante dos homens (Rm 12,17), para que seja verdadeiramente lírio.`
    },
    {
      n: 3,
      texto: `Mas é também brancura da alma o perdão de Deus, como ele mesmo diz pelo profeta: Ainda que os vossos pecados sejam como o escarlate, ficarão brancos como a neve; e, ainda que sejam vermelhos como o carmesim, ficarão como a lã branca (Is 1,18). E há uma brancura de que se reveste aquele que se compadece com alegria (cf. Rm 12,8). Pois, se olhares aquele que o Profeta pinta como homem alegre, que se compadece e empresta (Sl 111,5), não te parecerá que, da própria alegria do ânimo, deu uma certa brancura de piedade tanto ao seu rosto como à sua obra? Assim como, pelo contrário, se alguém dá com tristeza e como que por obrigação, mostra na mão e na fronte uma cor não branca, mas sombria. E por isso Deus ama quem dá com alegria (2Cor 9,7). Acaso também o triste? Certamente aquele que olhou para Abel por causa da brancura da sua prontidão, desviou o rosto de Caim, porque o seu semblante estava abatido (Gn 4,4-5) — de tristeza, sem dúvida, e de inveja. Repara que cor é a da tristeza ou da inveja, que desvia de si o olhar de Deus. Bela e elegantemente foi louvada a brancura da alegria, que dá cor ao benefício, naquele verso do poeta: E, acima de tudo, vieram os rostos bondosos. E não só quem dá com alegria, mas também quem dá com simplicidade (Rm 12,8) é amado por Deus. E a simplicidade é brancura. Prova-o o contrário: pois a duplicidade é um sinal escuro. Disse pouco: é uma mancha. Que é a duplicidade, senão dolo? Ora, de quem agiu com dolo diante de Deus, a iniquidade foi achada digna de ódio (Sl 35,3). E por isso, bem-aventurado aquele a quem o Senhor não imputa pecado, e em cujo espírito não há dolo (Sl 31,2). Belamente o Senhor assinalou em poucas palavras uma e outra mancha, o dolo e a tristeza, dizendo: Não vos mostreis tristes como os hipócritas (Mt 6,16). O esposo, pois, sendo virtude, compraz-se nas virtudes; sendo lírio, demora-se de bom grado entre os lírios; sendo brancura, deleita-se com as coisas brancas.`
    },
    {
      n: 4,
      texto: `E talvez seja isto o que se diz apascentar-se entre os lírios: deleitar-se com a brancura e o perfume das virtudes. Outrora, certamente, alimentava-se corporalmente em casa de Maria e de Marta (cf. Lc 10,38-39), reclinando-se também com o corpo entre lírios — falo delas, pois eram lírios —, e ao mesmo tempo restaurava o espírito com a devoção e as virtudes daquelas mulheres. Se naquela hora tivesse entrado um profeta, ou um anjo, ou qualquer outro ser espiritual, contanto que não ignorasse que majestade ali estava reclinada, não teria ele, pasmado com a condescendência e a familiaridade que o via ter com almas puras e corpos castos — mas terrenos e do sexo mais fraco —, razão para testemunhar: Vi-o não só demorar-se, mas também apascentar-se entre os lírios? Assim, pois, segundo uma coisa e outra — digo, a carne e o espírito —, o esposo foi encontrado apascentando-se entre os lírios. Penso, porém, que também ele, por sua vez, as apascentava, mas no espírito. Pelo próprio fato de se alimentar, como as apascentava! Como, digo, fortalecia a timidez daquelas mulheres, alegrava a sua humildade, enriquecia a sua devoção! Mas, se viste que para ele apascentar-se é apascentar, vê agora se, inversamente, apascentar não é para ele apascentar-se. Senhor, que me apascentas desde a minha juventude, diz o santo patriarca Jacó (Gn 48,15). Bom pai de família, que cuida dos da sua casa, sobretudo nos dias maus, para os sustentar na fome (cf. Sl 32,19), alimentando-os com o pão da vida e da inteligência (cf. Eclo 15,3), e nutrindo-os assim para a vida eterna. Mas, apascentando, penso eu, ele mesmo também se apascenta, e com os alimentos de que se nutre com gosto: os nossos progressos. Pois a alegria do Senhor é a nossa força (Ne 8,10).`
    },
    {
      n: 5,
      texto: `Assim, pois, quando apascenta, apascenta-se, e quando se apascenta, apascenta; ao mesmo tempo nos restaura com a sua alegria espiritual e se alegra com o nosso progresso, igualmente espiritual. O seu alimento é a minha penitência, o seu alimento é a minha salvação, o seu alimento sou eu mesmo. Não come ele cinza como pão (cf. Sl 101,10)? E eu, porque sou pecador, sou cinza, para ser comido por ele. Sou mastigado quando sou repreendido, engolido quando sou instruído, cozido quando sou mudado, digerido quando sou transformado, unido quando sou conformado. Não vos admireis disto: ele nos come e é comido por nós, para que nos unamos a ele mais estreitamente. De outro modo, certamente, não nos unimos a ele perfeitamente. Pois, se como e não sou comido, parecerá que ele está em mim, mas ainda não eu nele. E, se sou comido, mas não como, parecerá que ele me tem em si, mas não que está também em mim; e em nenhum destes casos haverá união perfeita. Mas que ele me coma, para me ter em si; e seja, por sua vez, comido por mim, para estar em mim; de modo que a ligação seja inteira e firme, quando eu estiver nele e ele igualmente em mim (cf. Jo 6,57).`
    },
    {
      n: 6,
      texto: `Queres que te mostre por uma comparação o que se diz? Ergue agora os olhos para uma certa correspondência, mais sublime, sem dúvida, mas semelhante a esta. Se o próprio esposo estivesse no Pai, sem que o Pai estivesse nele; ou se o Pai estivesse nele, sem que ele estivesse no Pai, ouso dizer que também a unidade deles ficaria aquém da perfeição — se é que ainda seria unidade. Mas agora, estando ele no Pai e o Pai nele, não há por onde a unidade coxeie: ele e o Pai são verdadeira e perfeitamente uma só coisa. Assim, pois, a alma para quem é bom unir-se a Deus (Sl 72,28) não se julgue perfeitamente unida a ele antes de sentir que ele permanece nela e ela nele. Não que, nem mesmo então, se diga que é uma só coisa com Deus, como o Pai e o Filho são uma só coisa; embora quem se une a Deus seja um só espírito com ele (1Cor 6,17). Isto eu li; aquilo não li. Não falo de mim, que nada sou; mas certamente ninguém, a não ser um louco, seja da terra, seja do céu, usurpará para si aquela palavra do Unigênito: Eu e o Pai somos uma só coisa (Jo 10,30). E, no entanto, eu, embora pó e cinza (cf. Gn 18,27), apoiado na autoridade da Escritura, de modo nenhum recearia dizer que sou um só espírito com Deus, se alguma vez me convencer, por experiências certas, de que estou unido a Deus à maneira de um daqueles que permanecem na caridade, e por isso permanecem em Deus, e Deus neles (cf. 1Jo 4,16), comendo a Deus e comidos por Deus. Pois penso que foi de tal união que se disse: Quem se une a Deus é um só espírito com ele. Que dizer, então? Diz o Filho: Eu estou no Pai, e o Pai está em mim (Jo 14,11), e somos uma só coisa (Jo 10,30); diz o homem: Eu estou em Deus, e Deus está em mim, e somos um só espírito.`
    },
    {
      n: 7,
      texto: `Mas acaso o Pai e o Filho, para estarem um no outro e, por isso, serem uma só coisa, comem-se mutuamente, como Deus e o homem, comendo-se de certo modo um ao outro, passam para dentro um do outro, tornando-se assim, se não uma só coisa, certamente um só espírito? Longe disso! Pois nem estes e aqueles estão um no outro do mesmo modo, nem é uma só a unidade de uns e de outros.`
    },
    {
      n: 8,
      texto: `O Pai e o Filho estão um no outro de um modo não só inefável, mas também incompreensível: cada um é capaz de conter o outro e de ser contido por ele; mas de tal modo é contido que não se reparte, e de tal modo contém que não recebe só uma parte. Pois, como canta a Igreja no hino: Todo o Filho está no Pai, e todo o Pai no Verbo. O Pai está no Filho, em quem sempre pôs a sua complacência (cf. Mt 3,17); e o Filho está no Pai, do qual, assim como nunca deixou de ter nascido, assim também nunca se separou. O homem, por sua vez, está em Deus, e Deus no homem, pela caridade, como diz João: Quem permanece na caridade permanece em Deus, e Deus nele (1Jo 4,16).`
    },
    {
      n: 9,
      texto: `Está bastante clara, se não me engano, não só a diversidade, mas também a desigualdade das unidades: uma existe numa só essência, a outra em essências diversas. Que há de tão distante entre si como a unidade de muitos e a de um só? Assim, como disse, o que distingue as unidades é dizer "um só" ou "uma só coisa": porque por "uma só coisa" se designa no Pai e no Filho a unidade da essência, e por "um só", entre Deus e o homem, não esta, mas uma certa concordância amorosa dos afetos. Com um acréscimo, porém, também o Pai e o Filho se dizem com toda a correção "um só": por exemplo, um só Deus, um só Senhor, e tudo o mais que se diz de cada um em relação a si mesmo, e não em relação ao outro. Pois não têm divindade ou majestade diversa, não mais que substância, essência ou natureza. Todas estas coisas, se as consideras com piedade, não são diversas nem divididas neles, mas são uma só coisa. Disse pouco: são uma só coisa também com eles. E aquela unidade pela qual se lê que muitos corações eram um só, e muitas almas uma só (cf. At 4,32)? Não deve, penso eu, ser chamada unidade, comparada com esta, que não une muitas coisas, mas designa de modo singular uma só. Singular e suprema é, pois, aquela unidade que não consiste numa união, mas existe desde a eternidade. E não é aquele comer espiritual de que falamos que a produz, porque ela nem sequer se produz: ela é. Muito menos se deve pensar que a produz alguma conjunção de essências, ou concordância de vontades, porque não há várias. Pois, como se disse, uma só é neles a essência e a vontade; e para o que é um não há concordância, nem composição, nem junção, nem coisa semelhante. É preciso que haja ao menos duas vontades para que haja concordância; e igualmente duas essências para que haja conjunção ou união por concordância. Nada disso há no Pai e no Filho, que não têm duas essências nem duas vontades. Uma só é neles uma e outra coisa; ou antes, como me lembro de ter dito, estas duas são uma só coisa neles, e uma só coisa também com eles; e por isso eles, permanecendo um no outro de modo tão imutável como incompreensível, são verdadeira e singularmente uma só coisa. Se alguém, porém, disser que há concordância entre o Pai e o Filho, não discuto, contanto que entenda não uma união de vontades, mas a unidade da vontade.`
    },
    {
      n: 10,
      texto: `Ora, Deus e o homem, porque existem e se distinguem com vontades e substâncias próprias, entendemos que permanecem um no outro de modo muito diferente: isto é, não confundidos nas substâncias, mas concordes nas vontades. E esta união é para eles comunhão de vontades e concordância na caridade. União feliz, se a experimentares; nenhuma, se a comparares. Voz de quem experimentou: Para mim, porém, é bom unir-me a Deus (Sl 72,28). Bom, certamente, se te unires por completo. Quem é que se une perfeitamente a Deus, senão aquele que, permanecendo em Deus como amado por Deus, atraiu por sua vez Deus a si, amando-o? Quando, pois, o homem e Deus estão unidos por todos os lados — e estão unidos por todos os lados quando, por um amor íntimo e mútuo, entraram nas entranhas um do outro —, direi sem hesitar que por isso Deus está no homem e o homem em Deus. Mas o homem está em Deus desde a eternidade, como amado desde a eternidade — se é que é daqueles que dizem que ele nos amou e nos agraciou no seu Filho amado antes da constituição do mundo (cf. Ef 1,4-6); Deus, porém, está no homem desde que é amado pelo homem. E, se é assim, o homem está em Deus mesmo quando Deus não está no homem; mas Deus não está em nenhum homem que não esteja em Deus. Pois quem não é amado não pode permanecer no amor, ainda que talvez ame por algum tempo; mas quem é amado pode ainda não amar. De outro modo, como se sustentaria que ele nos amou primeiro (1Jo 4,10)? E, quando já ama também aquele que antes era amado, o homem está em Deus e Deus no homem. Mas quem nunca ama, é claro que nunca foi amado; e por isso nem ele está em Deus, nem Deus nele. Fique isto dito para mostrar a diferença entre aquela ligação pela qual o Pai e o Filho são uma só coisa, e aquela pela qual a alma unida a Deus é um só espírito com ele; para que, lendo-se do homem que permanece na caridade que permanece em Deus, e Deus nele, e igualmente do Filho que está no Pai, e o Pai nele, não se pense que é igual a prerrogativa do adotado e a do Unigênito.`
    },
    {
      n: 11,
      texto: `Terminado isto, devemos voltar àquele que se apascenta entre os lírios, porque foi daí que partiu esta digressão até aqui: se não foi inútil, vós o julgareis. E eu já tinha proposto duas interpretações desta passagem: ou que ele, que é virtude e brancura, se apascenta das virtudes dos que estão vestidos de branco; ou que recebe os pecadores à penitência no seu corpo, que é a Igreja — ele que, não tendo cometido pecado, se fez a si mesmo pecado para os incorporar a si (cf. 2Cor 5,21), a fim de que fosse destruído o corpo do pecado (Rm 6,6), ao qual outrora estavam enxertados os pecadores, e eles se tornassem justiça nele, justificados gratuitamente (cf. Rm 3,24).`
    },
    {
      n: 12,
      texto: `Proponho ainda uma terceira interpretação que me ocorre; e julgo que bastará não só para explicar a passagem, mas também para terminar o sermão. A palavra de Deus é a verdade (cf. Jo 17,17), e é o próprio esposo. Sabeis isto; ouvi o resto. Quando é ouvida e não se lhe obedece, fica, por assim dizer, vazia e em jejum, toda triste e queixosa por ter sido proferida em vão. Mas, se lhe obedecerem, não te parecerá que a palavra cresceu e ganhou uma certa corpulência, porque à palavra se juntou a obra, como se se tivesse alimentado com certos frutos da obediência, com os frutos da justiça? Daí vem que diz no Apocalipse: Eis que estou à porta e bato: se alguém ouvir a minha voz e me abrir a porta, entrarei em sua casa e cearei com ele, e ele comigo (Ap 3,20). Este sentido parece confirmado também pela sentença do Senhor no profeta, onde diz que a sua palavra não voltará a ele vazia, mas prosperará e fará aquilo para que a enviou (Is 55,11). Não voltará a mim, diz, vazia ou em jejum, mas, como quem é bem-sucedido em tudo, se saciará com as boas ações dos que lhe obedecerem por amor. Enfim, no modo comum de falar, diz-se que uma palavra foi cumprida — como quem diz: preenchida — quando foi levada a efeito; como se, até que a obra a complete, estivesse vazia, magra e de certo modo faminta.`
    },
    {
      n: 13,
      texto: `Mas ouve de que alimento ele mesmo diz nutrir-se: O meu alimento, diz, é fazer a vontade de meu Pai (Jo 4,34). É palavra do Verbo, que indica claramente que o seu alimento é a boa ação; contanto, porém, que a encontre entre os lírios, isto é, entre as virtudes. De outro modo, se a encontrar fora deles, ainda que o alimento pareça bom em si mesmo, não lhe tocará aquele que se apascenta entre os lírios. Por exemplo, não recebe a esmola da mão do ladrão ou do usurário; nem sequer da do hipócrita, que, quando dá esmola, manda tocar a trombeta diante de si para ser glorificado pelos homens (Mt 6,2). Nem atenderá de modo algum a oração daquele que gosta de orar nas esquinas das praças, para ser visto pelos homens (Mt 6,5). Pois a oração do pecador será execrável (cf. Pr 28,9). Em vão ofereceria também o seu dom ao altar quem tem consciência de que o seu irmão tem alguma coisa contra ele (Mt 5,23-24). Enfim, não olhou para os dons de Caim (Gn 4,5), porque não andava retamente com o seu irmão. Segundo o testemunho do santo profeta, abominava até os sábados, as luas novas e os sacrifícios dos judeus, a ponto de declarar abertamente que a sua alma os odiava (cf. Is 1,13-14), e dizia: Quando vínheis à minha presença, quem vos pediu isso das vossas mãos (Is 1,12)? Creio que aquelas mãos não cheiravam a lírios, e por isso rejeitava o dom que delas vinha aquele que costuma apascentar-se entre os lírios, e não entre os espinhos. E como não teriam mãos espinhosas aqueles a quem dizia: As vossas mãos estão cheias de sangue (Is 1,15)? Também as mãos de Esaú eram peludas (cf. Gn 27,23), semelhantes a espinhos; e por isso não foram admitidas a servir o Santo.`
    },
    {
      n: 14,
      texto: `Receio que também entre nós haja alguns cujos dons o esposo não aceite, porque não cheiram a lírios. Pois, se no dia do meu jejum se encontrar a minha vontade, não é esse o jejum que o esposo escolheu, nem lhe agrada o meu jejum, que não sabe ao lírio da obediência, mas ao vício da vontade própria. E eu penso o mesmo não só do jejum, mas do silêncio, das vigílias, da oração, da leitura, do trabalho manual, enfim, de toda observância do monge, quando nela se encontra a sua própria vontade, e não a obediência ao seu superior. De modo nenhum julgaria que essas observâncias, embora boas em si, devam contar-se entre os lírios, isto é, entre as virtudes; mas quem for assim ouvirá do profeta: Acaso é este o serviço que eu escolhi, diz o Senhor? E acrescentará: No dia dos teus bens encontram-se as tuas vontades (cf. Is 58,3-5). Grande mal é a vontade própria, que faz com que os teus bens não sejam bens para ti. É preciso, pois, que as coisas deste gênero se tornem lírios, porque aquele que se apascenta entre os lírios não provará absolutamente nada que esteja manchado pela vontade própria. A Sabedoria atinge tudo por causa da sua pureza, e nada de manchado entra nela (Sb 7,24-25). Assim, pois, o esposo gosta de apascentar-se entre os lírios, isto é, junto dos corações puros e límpidos. Mas até quando? Até que aspire o dia e se inclinem as sombras (Ct 2,17). Este lugar é sombrio e cerrado: não entremos nesta floresta de profundo mistério senão à luz clara do dia. Pois, enquanto eu discorria longamente, o dia declinou; e somos arrancados, contra a vontade, a estes lírios. Nem me venceu a extensão do sermão, pois o perfume das flores lhe tiraria todo o enfado. Parece restar pouca coisa deste versículo. Mas esse pouco é muito escondido, como todo o resto deste cântico. Mas aquele que revela os mistérios (cf. Dn 2,28) estará presente, confio, quando começarmos a bater; e não fechará a boca dos que falam dele, ele de quem é mais próprio abrir o que está fechado: o esposo da Igreja, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
