SERMOES.sermao({
  id: 'bernardo-cantico-30',
  colecao: 'bernardo-cantico',
  ordem: 30,
  numero: 'XXX',
  titulo: 'De como as vinhas de que a Igreja se diz guarda significam o povo dos fiéis ou as almas dos eleitos; e da prudência da carne, que é morte',
  fonte: 'Qualiter populus fidelium seu animae electorum per vineas significantur',
  argumento: `Sobre «puseram-me a guardar as vinhas; a minha vinha, não a guardei». Lido pela história, é a Igreja expulsa de Jerusalém, que perdeu uma vinha e recebeu o mundo inteiro. Lido por Bernardo em si mesmo, é uma confissão: puseram-no a guardar as almas dos outros quando ele não guardava a sua, e agora, ocupado com muitas, guarda-a menos ainda.

Daí passa a Paulo, que não tinha a alma por mais preciosa do que ele mesmo, e a uma página de humor mordaz contra os monges que gastam o dia a discutir o que lhes faz mal: os legumes dão gases, o queijo pesa no estômago, o leite faz mal à cabeça. Hipócrates ensina a salvar a alma neste mundo; Cristo, a perdê-la. E quem invoca o conselho de Paulo a Timóteo para beber vinho não se esqueça do «um pouco».

Tradução feita do texto latino de Migne (PL 183, 933-940).`,
  pontos: [
    {
      n: 1,
      texto: `Puseram-me a guardar as vinhas (Ct 1,5). Quem? Aqueles teus agressores que acabaste de mencionar? Ouvi e entendei: não confessa ela ter sido promovida por aqueles mesmos de quem sofreu? E não é de admirar, se a razão do combate foi a intenção de corrigir. Pois quem não sabe que muitos foram muitas vezes combatidos com amizade e com proveito? Quantos vemos todos os dias progredir para melhor e ser levados mais alto pelos combates piedosos dos seus superiores! Mostremos antes, pois, se pudermos, como a Igreja foi combatida pelos filhos da sua mãe com ânimo hostil e, ao mesmo tempo, com um dano que lhe foi útil. Pois é mais agradável quando os que pretendem fazer mal aproveitam mesmo sem querer. A interpretação anterior comporta os dois sentidos: não faltaram os que a trataram com zelo bom e os que a trataram com zelo mau, combatendo com intenções diversas; mas uns e outros lhe foram úteis. Tanto se gloria, enfim, de ter progredido com o que sofreu dos adversários, que se alegra de ter sido posta sobre muitas vinhas, em troca de uma só que eles pareceram tirar-lhe. Isto me deram, diz ela, ao combater contra mim e contra a minha vinha, os que dizem: Arrasai-a, arrasai-a até os alicerces (Sl 136,7) — que eu trocasse uma por muitas. É o que acrescenta: A minha vinha não a guardei — como quem junta a causa por que lhe aconteceu ser posta a guardar não já uma só vinha, mas muitas. Isto quanto à letra.`
    },
    {
      n: 2,
      texto: `Mas, se a seguirmos simplesmente, contentes só com o que ela parece dizer à superfície, julgaremos ler na santa Escritura a respeito destas vinhas corporais e terrenas que vemos todos os dias receber do orvalho do céu e da gordura da terra (Gn 27,28), e das quais sai o vinho, em que há luxúria (Ef 5,18); e assim não teremos tirado de uma Escritura tão santa e divina nada digno — não digo da esposa do Senhor, mas nem sequer próprio de qualquer outra mulher. Pois que tem a ver com esposas guardar vinhas? E, ainda que se julgue que tenha, de onde mostraremos que a Igreja foi alguma vez encarregada de tal ofício? Porventura Deus se preocupa com vinhas? (1Cor 9,9) Mas, se em sentido espiritual entendermos as vinhas como as igrejas, isto é, como os povos fiéis, segundo o sentido do profeta que diz: A vinha do Senhor dos exércitos é a casa de Israel (Is 5,7), começará talvez a ficar claro para nós como não é de modo algum indigno da esposa ser posta a guardar as vinhas.`
    },
    {
      n: 3,
      texto: `E creio que até nisto aparecerá uma prerrogativa não pequena, se alguém se der ao trabalho de notar quanto ela alargou os seus limites, em vinhas assim, por todo o mundo, desde o dia em que foi atacada e expulsa de Jerusalém pelos filhos da sua mãe, juntamente com aquela sua primeira plantação nova — quero dizer, a multidão dos que creram, de quem se lê que tinham um só coração e uma só alma (At 4,32). E foi esta que ela agora confessa não ter guardado — mas não por insensatez sua. Pois não foi arrancada dali pela perseguição de modo a não ser plantada noutro lugar e arrendada a outros agricultores, que lhe deem os frutos a seu tempo (Mt 21,41). Não, não pereceu: mudou-se; e até cresceu e se alargou, como vinha que o Senhor abençoou. Levanta os olhos e vê se a sua sombra não cobriu os montes, e os seus ramos os cedros de Deus; se não estendeu os seus sarmentos até o mar, e os seus rebentos até o rio (Sl 79,11-12). E não é de admirar: é edifício de Deus, é lavoura de Deus (1Cor 3,9). Ele a fecunda, ele a propaga, ele a poda e a limpa, para que dê mais fruto (Jo 15,2). Quando é que deixaria sem o seu cuidado e o seu trabalho aquela que a sua direita plantou (Sl 79,16)? Não se há de ter em pouco uma vinha em que os apóstolos são os ramos, o Senhor é a videira e o seu Pai é o agricultor (Jo 15,1-5). Plantada na fé, lança raízes na caridade; cavada com a enxada da disciplina, estrumada com as lágrimas dos penitentes, regada com as palavras dos pregadores; e assim transborda de um vinho em que há alegria, mas não luxúria; de um vinho de toda a suavidade e de nenhuma sensualidade. É este o vinho que alegra o coração do homem (Sl 103,15); é este, sem dúvida, que também os anjos bebem com alegria. Pois alegram-se com a conversão e a penitência dos pecadores (Lc 15,10), sedentos da salvação dos homens. As lágrimas dos penitentes são o vinho deles, porque há nelas o odor da vida, o sabor da graça, o gosto do perdão, a alegria da reconciliação, a saúde da inocência que volta, a suavidade da consciência serenada.`
    },
    {
      n: 4,
      texto: `Daquela única vinha, pois, que a tempestade de uma perseguição cruel pareceu destruir, quantas se propagaram e floresceram de novo pela terra inteira! E sobre todas elas foi posta a esposa como guarda, de modo que não se entristece por não ter guardado a primeira. Consola-te, filha de Sião: se uma cegueira parcial atingiu Israel (Rm 11,25), que perdes tu? Admira o mistério e não chores a perda: alarga o regaço e recolhe a plenitude das nações. Dize às cidades de Judá: Era a vós que se devia anunciar primeiro a palavra de Deus; mas, como a rejeitais e vos julgais indignos da vida eterna, eis que nos voltamos para os pagãos (At 13,46). A Moisés, é verdade, Deus ofereceu que, se quisesse abandonar o povo prevaricador e expô-lo à vingança divina, ele mesmo poderia tornar-se uma grande nação; mas ele recusou (Ex 32,9-13). Por quê? Sem dúvida pelo imenso amor com que estava fortemente preso àquele povo; e porque não buscava o que era seu, mas a honra de Deus, nem o que lhe fosse útil a ele, mas a muitos. Assim fez ele.`
    },
    {
      n: 5,
      texto: `Eu, porém, creio que, por um desígnio mais secreto, este dom foi guardado por Deus, pela sua grandeza, para a esposa: que fosse ela, e não Moisés, a ser enviada a uma grande nação. Pois não convinha que o amigo do esposo arrebatasse à esposa a bênção; e por isso não Moisés, mas a nova esposa, a quem se diz: Ide pelo mundo inteiro e pregai o Evangelho a toda criatura (Mc 16,15) — ela, digo, é que foi enviada a uma grande nação. Poderia sê-lo a uma maior do que o mundo inteiro? E o mundo cedeu facilmente a quem trazia a paz e oferecia a graça. Mas não é com a lei como com a graça. Com que rostos diferentes se apresentam a qualquer consciência a suavidade desta e a austeridade daquela! Quem olharia do mesmo modo para quem condena e para quem consola, para quem cobra e para quem perdoa, para quem castiga e para quem abraça? Não se recebem com o mesmo desejo a sombra e a luz, a ira e a paz, o juízo e a misericórdia, a figura e a verdade, a vara e a herança, o freio e o beijo. Pesadas eram as mãos de Moisés, como testemunham Aarão e Hur (Ex 17,12); pesado o jugo da Lei, como testemunham os próprios apóstolos, que clamam ter sido insuportável para eles e para os seus pais (At 15,10): jugo pesado, e prêmio pobre, pois o que se promete é terra. Por isso Moisés não foi enviado a uma grande nação. Mas tu, mãe Igreja, que tens a promessa da vida presente e da futura (1Tm 4,8), alcanças facilmente, por uma dupla graça, ser recebida por todos: pelo jugo suave e pelo reino sublime. Expulsa de uma cidade, és recebida pelo mundo, porque o que prometes atrai tanto que o que impões não assusta. Por que choras ainda a perda de uma vinha, que te foi compensada com juros tão grandes? Porque foste abandonada e odiada, e não havia quem passasse por ti, farei de ti, diz ele, o orgulho dos séculos, alegria de geração em geração; e mamarás o leite das nações, e serás amamentada ao peito dos reis; e saberás que eu sou o Senhor que te salva, e o teu redentor, o Forte de Jacó (Is 60,15-16). É deste modo, pois, que a esposa diz ter sido posta a guardar as vinhas, e que não guardou a sua.`
    },
    {
      n: 6,
      texto: `Eu, a propósito deste lugar, costumo repreender-me a mim mesmo por ter tomado o cuidado das almas, eu que não era capaz de guardar a minha — entendendo as vinhas como almas. Se também tu aprovas esta nossa interpretação, vê em consequência se dizemos bem que a fé é a videira; as virtudes, os ramos; a obra, o cacho; a devoção, o vinho. Pois nem o ramo sem a videira, nem a virtude sem a fé é alguma coisa. Sem fé é impossível agradar a Deus (Hb 11,6) — e talvez seja até inevitável desagradar-lhe. Enfim, tudo o que não vem da fé é pecado (Rm 14,23). Era isto, pois, que deviam ter considerado os que me puseram a guardar as vinhas: se eu tinha guardado a minha. E quanto tempo ela ficou inculta e abandonada, reduzida a um deserto! Faltara-lhe de todo o vinho, secos os ramos das virtudes pela esterilidade da fé. Havia fé, mas morta. Pois como não estaria morta, sem obras? E isto na vida do mundo. Depois de me converter ao Senhor, comecei, confesso, a guardá-la um pouco melhor — mas não como convinha. E quem é capaz disso? Nem o santo Profeta, que diz: Se o Senhor não guardar a cidade, em vão vigia quem a guarda (Sl 126,1). Lembro-me de a quantas ciladas estava exposto também então da parte daquele que atira flechas às escondidas contra o inocente (Sl 63,5)! Quanto nos foi roubado, ó minha vinha, por tramas furtivas, justamente no tempo em que começamos a cuidar e a guardar-nos com mais vigilância! Quantos e que cachos de obras piedosas a ira sufocou, a ostentação levou, a vanglória estragou! Quanto sofremos da sedução da gula, quanto do espírito de acídia, quanto da falta de ânimo e da tempestade (Sl 54,9)! Assim era eu; e, contudo, puseram-me a guardar as vinhas, sem considerar o que eu fazia, ou tinha feito, da minha, e sem ouvir o mestre que repreende e diz: Se alguém não sabe governar a própria casa, como cuidará da Igreja de Deus? (1Tm 3,5)`
    },
    {
      n: 7,
      texto: `Admiro-me do atrevimento de muitos que vemos não colher das suas vinhas senão espinhos e abrolhos, e que, no entanto, não receiam meter-se também nas vinhas do Senhor. São ladrões e salteadores (Jo 10,8), não guardas nem cultivadores. Isto para eles. Mas ai de mim, também agora, pelo perigo da minha vinha! Ou antes, agora mais ainda, quando, ocupado com muitas, sou obrigado a ser menos diligente e menos cuidadoso com uma. Não me é dado nem cercá-la de sebe, nem cavar nela um lagar (Mt 21,33). Ai! Destruído foi o seu muro, e vindimam-na todos os que passam pelo caminho (Sl 79,13)! Está aberta e exposta à tristeza, à ira e à impaciência, que por ela passam à vontade. Estragam-na umas raposinhas diligentes (Ct 2,15), as necessidades que apertam; irrompem por toda parte as ansiedades, as suspeitas, as preocupações; e raramente faltam as turbas dos que brigam e o incômodo das causas. Não há como impedir, não há como fugir, nem sequer há tempo para orar. Com que chuva de lágrimas poderei regar a esterilidade da minha alma (Sl 34,12)? Queria dizer «da minha vinha», mas saiu assim por causa do costume do salmo; e o sentido é o mesmo, e não me pesa o engano que lembra a comparação, porque não se fala de uma vinha, mas de uma alma. Pense-se, pois, na alma quando se lê vinha, pois é sob a figura e o nome desta que se chora a esterilidade daquela. Com que lágrimas regarei, pois, a esterilidade da minha vinha? Todos os seus ramos secaram de míngua; jazem sem fruto, porque não têm umidade (Lc 8,6). Bom Jesus! Que feixes de sarmentos tirados deles não consome cada dia, no teu sacrifício, o fogo do meu coração contrito — tu és testemunha! Seja para ti, peço, um sacrifício o espírito atribulado; não desprezes, ó Deus, um coração contrito e humilhado (Sl 50,19).`
    },
    {
      n: 8,
      texto: `Assim aplico eu a mim este versículo, segundo a minha imperfeição. Mas será perfeito todo aquele que puder dizer de outro modo «não guardei a minha vinha» — naquele sentido em que fala o Salvador no Evangelho: Quem perder a sua alma por causa de mim há de encontrá-la (Mt 10,39). É capaz e digno de ser posto a guardar as vinhas aquele a quem o cuidado da própria vinha não impede nem atrasa no zelo e no cuidado das que lhe foram confiadas, porque não busca o que é seu nem o que lhe é útil, mas o que é útil a muitos (1Cor 10,33). Foi por isso que a Pedro se confiou este cuidado em tantas vinhas, as que eram da circuncisão: porque era homem pronto a ir para a prisão e para a morte (Lc 22,33), e o amor à sua vinha, isto é, à sua alma, não o prendia a ponto de o desviar do cuidado das que lhe foram confiadas. Com razão também a Paulo se confiou entre as nações uma floresta tão imensa de vinhas: porque também ele se mostrou pouco preocupado em guardar a sua, a ponto de estar pronto não só a ser preso, mas a morrer em Jerusalém pelo nome do Senhor Jesus Cristo (At 21,13). Enfim, diz: Nada disto temo, nem tenho a minha alma por mais preciosa do que eu mesmo (At 20,24). Ótimo avaliador das coisas, que julga que nada do que é seu se deve preferir a si mesmo.`
    },
    {
      n: 9,
      texto: `Quantos preferiram à própria salvação um pouco de dinheiro vilíssimo! Paulo, nem a alma. Não a tenho, diz ele, por mais preciosa do que eu. Fazes, então, diferença entre ti e a tua alma? Com prudência, sem dúvida, te estimas mais do que qualquer coisa tua. Mas como não és tu a tua alma? Creio que, como Paulo já então andava segundo o espírito e com a mente concordava com a lei de Deus, que é boa (Rm 7,16), julgou digno designar esta sua mente, como a parte principal e mais alta de si, com o nome de «si mesmo», e não com o de alguma coisa sua. E o resto — que é, como se sabe, de natureza inferior e por isso está preso a uma essência inferior e mais vil, que é o corpo, não só pelo ofício de lhe dar vida e sentidos, mas também pelo desejo de o acariciar e nutrir —, isto, digo, sensual e carnal, julgou-o o homem espiritual indigno de se chamar «ele mesmo», e preferiu contá-lo entre as coisas que são suas, em vez de se exprimir a si mesmo por ele. Quando digo «eu», diz ele, entende o que há de mais excelente em mim, aquilo em que estou firme pela graça de Deus — isto é, a mente e a razão. Quando falo da minha alma, entende aquela parte inferior que vês ajustada a dar vida à carne, e unida a ela até na concupiscência. Reconheço que isso fui, mas que já não sou, porque já não ando segundo a carne, mas segundo o espírito (Rm 8,4). Vivo, mas já não sou eu: é Cristo que vive em mim (Gl 2,20). Segundo a mente, sou eu; segundo a carne, não sou eu. Pois que importa que a alma ainda agora deseje carnalmente? Já não sou eu que o faço, mas o pecado que habita em mim (Rm 7,17). E por isso aquilo que em mim tem gosto pelas coisas da carne não o chamaria «eu», mas «meu» — e isso não é outra coisa senão a própria alma. Pois é de fato parte da alma o seu afeto carnal e a vida que ela dá ao corpo. Era esta alma sua que Paulo desprezava em comparação consigo, pronto a ser preso pelo Senhor e até a morrer em Jerusalém, e assim perder a sua alma, segundo o conselho do Senhor.`
    },
    {
      n: 10,
      texto: `Também tu, se deixares a tua própria vontade, se renunciares por inteiro aos prazeres do corpo, se crucificares a tua carne com os vícios e as concupiscências (Gl 5,24) e mortificares os teus membros que estão sobre a terra (Cl 3,5), mostrarás que és imitador de Paulo, que não tens a tua alma por mais preciosa do que tu; e mostrarás que és discípulo de Cristo, perdendo-a para a salvação. E é mais prudente perdê-la para a guardar do que guardá-la para a perder. Pois quem quiser salvar a sua alma há de perdê-la (Mt 16,25). Que dizeis vós a isto, observadores das comidas e descuidados dos costumes? Hipócrates e os seus seguidores ensinam a salvar as almas neste mundo; Cristo e os seus discípulos, a perdê-las. Qual dos dois mestres escolheis seguir? Mas bem se mostra quem discute assim: isto faz mal aos olhos, isto à cabeça, aquilo ao peito ou ao estômago. Cada um, de fato, põe diante de todos o que aprendeu do seu mestre. Leste estas distinções no Evangelho, ou nos profetas, ou nas cartas dos apóstolos? Foi sem dúvida a carne e o sangue que te revelaram esta sabedoria, não o espírito do Pai (Mt 16,17); pois é sabedoria da carne. Mas ouve o que pensam dela os nossos médicos: A sabedoria da carne, dizem, é morte; e ainda: A sabedoria da carne é inimiga de Deus (Rm 8,6-7). Devia eu propor-vos a sentença de Hipócrates ou de Galeno, ou coisa da escola de Epicuro? Sou discípulo de Cristo, e falo a discípulos de Cristo; se eu introduzir uma doutrina estranha, pequei. Epicuro e Hipócrates preferem, um o prazer do corpo, o outro a sua boa disposição; o meu Mestre prega o desprezo de ambas as coisas. A vida da alma no corpo — que um procura com o maior empenho, e ensina a procurar, com que sustentar, e o outro com que deleitar — o Salvador aconselha até a perdê-la.`
    },
    {
      n: 11,
      texto: `Pois que outra coisa te soou, vinda da escola de Cristo, quando há pouco se proclamou: Quem ama a sua alma há de perdê-la (Jo 12,25)? Disse «há de perdê-la», seja entregando-a, como o mártir, seja afligindo-a, como o penitente. Aliás, é uma espécie de martírio mortificar pelo espírito as obras da carne (Rm 8,13): menos horrível, sem dúvida, do que aquele em que os membros são cortados a ferro, mas mais penoso pela duração. Vês como esta sentença do meu Mestre condena a sabedoria da carne, pela qual ou se escorre para o luxo do prazer, ou se deseja mais do que convém a própria boa saúde do corpo? Que a verdadeira sabedoria não se escorre para os prazeres, ouviste-o do Sábio: nem sequer se acha na terra dos que vivem nas delícias (Jó 28,13). E quem a encontrou diz: Amei a sabedoria mais do que a saúde e do que toda beleza (Sb 7,10). Se mais do que a saúde e a beleza, quanto mais do que o prazer e a torpeza! E de que serve abster-se dos prazeres, se se gasta o cuidado de cada dia em investigar as diferenças de compleição e em indagar a variedade das comidas? Os legumes, diz um, dão gases; o queijo pesa no estômago; o leite faz mal à cabeça; o peito não aguenta beber água; as couves alimentam a melancolia; os alhos-porós acendem a cólera; os peixes de lagoa ou de água lodosa não se dão de modo nenhum com a minha compleição. Que é isto, que em todos os rios, campos, hortas e despensas mal se possa achar o que comas?`
    },
    {
      n: 12,
      texto: `Lembra-te, peço, de que és monge, não médico; e de que não serás julgado pela compleição, mas pela profissão. Poupa, peço, primeiro o teu próprio sossego; poupa depois o trabalho dos que servem; poupa o peso da casa; poupa a consciência. A consciência, digo, não a tua, mas a do outro: daquele que, sentado ao teu lado e comendo o que lhe põem, murmura da tua abstinência particular. Pois escandaliza-o ou a tua superstição odiosa, ou a dureza que ele talvez atribua àquele que tem de prover às tuas necessidades. O irmão, digo, escandaliza-se com a tua singularidade: ou te julga supersticioso, como quem anda atrás de coisas supérfluas, ou me acusa a mim de duro, por não procurar o necessário para o teu sustento. Em vão se lisonjeiam alguns com o exemplo de Paulo, que exorta o discípulo a não beber água, mas a usar um pouco de vinho por causa do estômago e das suas frequentes enfermidades (1Tm 5,23). Deviam reparar, primeiro, que o Apóstolo não aconselha tal coisa a si mesmo, nem o discípulo a pede para si. Depois, que isto não se diz a um monge, mas a um bispo, cuja vida era muitíssimo necessária a uma Igreja ainda tenra e que nascia. Era Timóteo. Dá-me outro Timóteo, e eu, se quiseres, o alimentarei com ouro e lhe darei a beber bálsamo. Mas tu dispensas-te a ti mesmo, com pena de ti. Confesso que desconfio da dispensa que tu dás a ti mesmo, e receio que a prudência da carne te engane sob a capa e o nome do discernimento. Quero ao menos que fiques avisado disto: se te agrada tanto a autoridade do Apóstolo quanto a beber vinho, não deixes de lado o «um pouco», que ele acrescentou. E basta disto. Mas voltemos à esposa e aprendamos dela a não guardar, com proveito, as próprias vinhas — sobretudo nós, que parecemos ter sido postos a guardar as vinhas do esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus sobre todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
