SERMOES.sermao({
  id: 'bernardo-cantico-43',
  colecao: 'bernardo-cantico',
  ordem: 43,
  numero: 'XLIII',
  titulo: 'De como a consideração da paixão e dos trabalhos de Cristo faz a esposa, isto é, a alma, caminhar ilesa entre as prosperidades e as adversidades deste mundo',
  fonte: 'Qualiter consideratio passionis et laborum Christi faciat sponsam pergere illaesam',
  argumento: `Um dos sermões mais conhecidos de toda a série. O rei do versículo anterior passa a ser "o meu amado", e do leito real desce para o peito da esposa: tanto pode a humildade. A mirra, amarga, significa as tribulações; e a esposa não chama o amado de feixe, mas de ramalhete, porque o amor torna leve o que pesa. Ela o põe entre os dois peitos, a alegria com os que se alegram e a compaixão com os que choram, para que nem a prosperidade a exalte nem a adversidade a abata.

No centro, um testemunho pessoal raro. Desde a conversão, Bernardo atou para si esse ramalhete com todas as angústias do Senhor — as necessidades da infância, as fadigas da pregação, as vigílias, os insultos, os escarros, os cravos, a mirra da cruz e a da sepultura —, porque sabia que lhe faltavam méritos. É a sua "filosofia mais alta": saber Jesus, e Jesus crucificado. Não pergunta onde o amado repousa ao meio-dia: abraça-o na cruz. E pede aos monges que o levem à frente dos olhos, e não às costas, como Simeão, Maria e José.

Tradução feita do texto latino de Migne (PL 183, 993-995).`,
  pontos: [
    {
      n: 1,
      texto: `O meu amado é para mim um ramalhete de mirra; repousará entre os meus peitos (Ct 1,12). Antes, rei; agora, amado. Antes, no leito real; agora, entre os peitos da esposa. Grande é a força da humildade, diante da qual até a majestade da Divindade se inclina com tanta facilidade. Depressa o nome de reverência se mudou em palavra de amizade; e quem estava longe em pouco tempo se fez perto (cf. Ef 2,13). O meu amado é para mim um ramalhete de mirra. A mirra, coisa amarga, significa a dureza e a aspereza das tribulações. Prevendo que elas a ameaçam por causa do amado, a esposa fala com alegria, confiando que enfrentará tudo com coragem. Os discípulos, diz a Escritura, saíam alegres da presença do conselho, por terem sido julgados dignos de sofrer afrontas pelo nome de Jesus (At 5,41). Por isso, enfim, não chama ao amado um feixe, mas um ramalhete, porque, pelo amor dele, tem por leve todo trabalho e toda dor que a ameacem. Bem se diz ramalhete, porque um pequenino nasceu para nós (Is 9,6). Bem se diz ramalhete, porque os sofrimentos do tempo presente não têm proporção com a glória futura que se há de revelar em nós (Rm 8,18). Pois a nossa tribulação presente, momentânea e leve, diz, produz em nós, além de toda medida, um peso eterno de glória (2Cor 4,17). Será, pois, um dia para nós um enorme monte de glória o que agora é um ramalhete de mirra. Não é um ramalhete aquele cujo jugo é suave e o fardo leve (Mt 11,30)? Não porque seja leve em si — pois não é leve a aspereza da paixão, a amargura da morte —, mas é leve para quem ama. E por isso não diz só: O meu amado é um ramalhete de mirra; mas: Para mim, diz, que o amo, é um ramalhete. Por isso também lhe chama amado, mostrando que a força do amor vence o incômodo de todas as amarguras, e que o amor é forte como a morte (Ct 8,6). E, para que saibas que ela não se gloria em si, mas no Senhor, e que não conta com a própria força, mas com o auxílio do Senhor, diz que ele repousará entre os seus peitos, e canta-lhe com segurança: Ainda que eu ande no meio da sombra da morte, não temerei mal nenhum, porque tu estás comigo (Sl 22,4).`
    },
    {
      n: 2,
      texto: `Lembro-me de ter definido, num dos sermões anteriores, os dois peitos da esposa como a alegria com quem se alegra e a compaixão, segundo a doutrina de Paulo, que diz: Alegrai-vos com os que se alegram, chorai com os que choram (Rm 12,15). E, como vive entre as adversidades e as prosperidades e sabe que de ambos os lados não faltam perigos, quer ter o amado entre estes seus dois peitos, para que, defendida contra ambos pela sua proteção contínua, nem as coisas alegres a exaltem, nem as tristes a abatam. Também tu, se és sábio, imitarás a prudência da esposa, e não deixarás que este tão querido ramalhete de mirra seja arrancado, nem por uma hora, do centro do teu peito, guardando sempre na memória e revolvendo em meditação contínua todas aquelas coisas amargas que ele sofreu por ti, para que possas dizer também tu: O meu amado é para mim um ramalhete de mirra; repousará entre os meus peitos.`
    },
    {
      n: 3,
      texto: `Também eu, irmãos, desde o começo da minha conversão, em lugar do monte de méritos que sabia faltar-me, tratei de atar para mim este ramalhete e colocá-lo entre os meus peitos, colhido de todas as angústias e amarguras do meu Senhor: primeiro, das necessidades da sua infância; depois, dos trabalhos que suportou pregando, das fadigas das suas andanças, das vigílias em oração, das tentações no jejum, das lágrimas da compaixão, das ciladas que lhe armavam nas conversas; por fim, dos perigos entre falsos irmãos (cf. 2Cor 11,26), dos insultos, dos escarros, das bofetadas, das zombarias, das afrontas, dos cravos e de outras coisas semelhantes, que a floresta do Evangelho, como se sabe, produziu em grande abundância para a salvação do nosso gênero. E, entre tantos raminhos desta mirra perfumada, julguei que de modo nenhum devia omitir também aquela mirra que lhe deram a beber na cruz (cf. Mc 15,23), nem aquela com que foi ungido na sepultura (cf. Jo 19,39). Na primeira, tomou sobre si a amargura dos meus pecados; na segunda, consagrou a futura incorrupção do meu corpo. Proclamarei, enquanto viver, a lembrança da abundância da suavidade destas coisas (cf. Sl 144,7); nunca me esquecerei destas misericórdias, porque nelas recebi a vida (cf. Sl 118,93).`
    },
    {
      n: 4,
      texto: `Por elas pedia outrora o santo Davi com lágrimas, dizendo: Venham a mim as tuas misericórdias, e viverei (Sl 118,77). Delas se lembrava com gemidos também um outro dos santos, dizendo: Muitas são as misericórdias do Senhor (cf. Sl 118,156). Quantos reis e profetas quiseram ver, e não viram (Lc 10,24)! Eles trabalharam, e eu entrei no seu trabalho (cf. Jo 4,38); eu colhi a mirra que eles plantaram; para mim foi guardado este ramalhete salutar; ninguém o tirará de mim; repousará entre os meus peitos. Meditar nestas coisas, eu o chamei sabedoria; nelas pus a perfeição da justiça, nelas a plenitude da ciência, nelas as riquezas da salvação, nelas a abundância dos méritos. Delas me vem às vezes a bebida de uma amargura salutar; delas, por sua vez, a suave unção da consolação. Elas me levantam nas adversidades e me contêm nas prosperidades; e, entre as alegrias e as tristezas da vida presente, a mim que caminho pela estrada real, oferecem de ambos os lados uma guia segura, repelindo os males que ameaçam de um lado e de outro. Elas me tornam favorável o juiz do mundo, porque o mostram manso e humilde, a ele que faz tremer as potestades; porque apresentam não só aplacável, mas também imitável, aquele que é inacessível aos principados e terrível para os reis da terra (cf. Sl 75,13). Por isso tenho estas coisas muitas vezes na boca, como vós sabeis; sempre no coração, como Deus sabe; são muito familiares à minha pena, como se vê. Esta é, por ora, a minha filosofia mais alta: saber Jesus, e Jesus crucificado (cf. 1Cor 2,2). Não pergunto, como a esposa, onde repousa ao meio-dia (Ct 1,6) aquele que abraço com alegria, repousando entre os meus peitos. Não pergunto onde apascenta ao meio-dia aquele que contemplo como Salvador na cruz. Aquilo é mais sublime; isto, mais suave. Aquilo é pão; isto é leite. Isto restaura as entranhas dos pequenos, isto enche os peitos das mães; e por isso repousará entre os meus peitos.`
    },
    {
      n: 5,
      texto: `Também vós, caríssimos, colhei para vós este ramalhete tão amado; metei-o no mais íntimo do coração; guarnecei com ele a entrada do peito, para que também entre os vossos peitos ele repouse. Tende-o sempre, não atrás, nos ombros, mas à frente, diante dos olhos, para que, levando-o sem lhe sentir o perfume, o peso não vos esmague e o perfume não vos reanime. Lembrai-vos de que Simeão o tomou nos braços (Lc 2,28); Maria o trouxe no seio e o aqueceu no regaço; a esposa colocou-o entre os seus peitos. E, para não omitir nada, o Verbo esteve na mão do profeta Zacarias, e também na de alguns outros. E penso que também José, esposo de Maria, muitas vezes lhe sorriu, tendo-o sobre os joelhos. Todos estes o tiveram à sua frente, e nenhum atrás. Sirvam-vos, pois, de exemplo, para que façais também assim. Pois, se tiverdes diante dos olhos aquele que levais, vendo as angústias do Senhor, certamente levareis com mais leveza as vossas, com a ajuda do próprio esposo da Igreja, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
