SERMOES.sermao({
  id: 'bernardo-cantico-77',
  colecao: 'bernardo-cantico',
  ordem: 77,
  numero: 'LXXVII',
  titulo: 'Dos maus pastores da Igreja; e de como os bem-aventurados no céu, juntamente com os anjos, socorrem os eleitos que ainda peregrinam',
  fonte: 'De malis pastoribus Ecclesiae',
  argumento: `Livre dos outros assuntos, Bernardo retoma o sermão interrompido. Os guias que a Igreja tem hoje não são os que devia ter: enfeitados como esposas, vivem dos bens da esposa, que fica pobre e nua; em vez de a guardar, perdem-na; em vez de a instruir, prostituem-na; exigem o preço dos pecados e não cuidam dos pecadores. Querem ser sucessores dos apóstolos, não imitadores; correm para a cátedra, não para o cuidado.

Os verdadeiros vigias que encontraram a esposa são os apóstolos e os homens apostólicos, que continuam a guardá-la depois da morte, juntamente com os anjos: os santos, porque passaram pelas mesmas misérias e sem a Igreja não chegam à perfeição; os anjos, porque dela se há de completar o seu número, diminuído pela queda de Satanás. Foram eles que encontraram a esposa, e não ela a eles: aprendam os que querem seguir o caminho espiritual sem mestre, cegos guias de cegos. Mas por que diz a esposa que foi "encontrada", se a Igreja nunca esteve reunida num só lugar? A questão fica para o sermão seguinte.

Tradução feita do texto latino de Migne (PL 183, 1155-1159).`,
  pontos: [
    {
      n: 1,
      texto: `Eia, estamos livres! Dissemos no sermão de ontem que guias quereríamos ter neste caminho por onde andamos, e não os que temos. Experimentamos que são muito diferentes. Nem todos os que hoje vês ao lado da esposa, de um e de outro lado, e que, como se diz vulgarmente, parecem escoltá-la, são amigos do esposo. Muito poucos são, dentre todos os seus queridos (cf. Lm 1,2), os que não buscam os próprios interesses (cf. Fl 2,21). Amam os presentes (cf. Is 1,23), e não podem amar ao mesmo tempo a Cristo, porque deram a mão ao dinheiro (cf. Mt 6,24). Olha como andam luzidios e enfeitados, cobertos de variados adornos, como uma esposa que sai do seu tálamo (cf. Sl 18,6). Se vires de repente, ao longe, um destes avançar, não pensarás antes que é a esposa, e não o guarda da esposa? E de onde pensas que lhes vem em tamanha abundância esta fartura de bens, este esplendor das vestes, este luxo das mesas, este amontoado de vasos de prata e de ouro, senão dos bens da esposa? Daí vem que ela é deixada pobre, necessitada e nua, com o rosto digno de pena, descuidado, desgrenhado, pálido. Por isso, nestes tempos, não é adornar a esposa, mas despojá-la; não é guardá-la, mas perdê-la; não é defendê-la, mas expô-la; não é instruí-la, mas prostituí-la; não é apascentar o rebanho, mas matá-lo e devorá-lo, dizendo deles o Senhor: Os que devoram o meu povo como quem come pão (Sl 13,4; 52,5); e: Porque devoraram Jacó e desolaram a sua morada (Sl 78,7); e noutro profeta: Comem os pecados do meu povo (Os 4,8); como se dissesse: exigem o preço dos pecados, e não dão aos pecadores o cuidado que lhes devem. Que prelado me darás que não vele mais por esvaziar as bolsas dos súditos do que por extirpar os vícios? Onde está quem, orando, aplaque a ira? Quem pregue o ano favorável do Senhor (Is 61,2)? Dizemos as coisas mais leves; as mais graves espera um juízo mais grave.`
    },
    {
      n: 2,
      texto: `Mas em vão nos detemos nestas ou naquelas coisas, porque eles não nos ouvem. E, ainda que talvez se ponha por escrito o que dizemos, desdenharão lê-lo; ou, se por acaso o lerem, hão de indignar-se contra mim, embora mais justo fosse indignarem-se contra si mesmos. Deixemos, pois, estes, que não são os que encontraram a esposa, mas os que a vendem; e procuremos antes aqueles pelos quais a esposa diz que foi encontrada. É verdade que estes receberam em sorte o lugar do ministério daqueles, mas não o seu zelo. Todos querem ser sucessores; imitadores, poucos. Oxalá se mostrassem tão vigilantes no cuidado como correm ligeiros para a cátedra! Vigiariam, certamente, guardando com solicitude a que aqueles encontraram e que a eles foi confiada. Ou antes, despertariam por si mesmos, e não deixariam que se dissesse deles: Os meus amigos e os meus próximos aproximaram-se e se levantaram contra mim (Sl 37,12). Queixa inteiramente justa, que a nenhuma época se aplica com mais justiça do que à nossa. Não basta aos nossos vigias não nos guardarem: também nos perdem. Mergulhados, com efeito, num profundo sono de esquecimento, não despertam a nenhum trovão das ameaças do Senhor, nem sequer para temerem o seu próprio perigo. Daí vem que não poupam os seus, eles que não se poupam a si mesmos, matando e morrendo ao mesmo tempo.`
    },
    {
      n: 3,
      texto: `Mas quem são aqueles vigias pelos quais a esposa diz ter sido encontrada? Sem dúvida os apóstolos e os homens apostólicos. Estes são verdadeiramente os que guardam a cidade, isto é, a mesma Igreja que encontraram; e com tanto mais vigilância quanto mais gravemente a veem agora em perigo, e em perigo de um mal doméstico e interno, como está escrito: E os inimigos do homem são os da sua própria casa (Mq 7,6). Pois não deixam privada da sua proteção aquela pela qual resistiram até o sangue (cf. Hb 12,4), mas protegem-na e guardam-na dia e noite, isto é, na sua vida e na sua morte. E, se é preciosa aos olhos do Senhor a morte dos seus santos (Sl 115,15), não duvido de que o fazem na morte com tanto mais poder quanto mais nela se fortaleceu o seu principado (Sl 138,17).`
    },
    {
      n: 4,
      texto: `Afirmas estas coisas, diz alguém, como se as visses com os teus olhos; e, no entanto, estão escondidas à vista humana. E eu respondo: Se julgas fiel o testemunho dos teus olhos, o testemunho de Deus é maior (1Jo 5,9). Pois ele diz: Sobre os teus muros, Jerusalém, pus guardas; o dia inteiro e a noite inteira, para sempre, não se calarão (Is 62,6). Mas isso, dizes, foi dito dos anjos. Não o nego: são todos espíritos servidores (Hb 1,14). Mas quem me proíbe de pensar o mesmo também destes, que no poder já não são de modo nenhum inferiores aos próprios anjos, e que no afeto e na misericórdia talvez nos sejam tanto mais irmãos quanto mais unidos a nós pela natureza? Junta ainda o terem suportado os mesmos sofrimentos e misérias em que nós, por ora, ainda nos encontramos. Não produzirá nada mais de compaixão ou de solicitude por nós, nas almas santas, o lembrarem-se, sem dúvida, de que também elas passaram por isso? Não é deles aquela voz: Passamos pelo fogo e pela água, e tu nos conduziste ao refrigério (Sl 65,12)? Quê? Eles passaram, e nos deixarão no meio dos fogos e das ondas, e nem sequer se dignarão estender a mão aos filhos em perigo? Não é assim. Estás bem servida, ó mãe Igreja; estás bem servida no lugar da tua peregrinação: do céu e da terra te vem o auxílio (cf. Sl 120,2). Os que te guardam não cochilam nem dormem (cf. Sl 120,4). Os teus guardas são os santos anjos; os teus vigias, os espíritos e as almas dos justos. Não erram os que pensam que foste encontrada por uns e outros espíritos, e que és guardada igualmente por uns e outros. E cada um tem a sua razão para esta solicitude: estes, porque sem ti não chegam à perfeição (cf. Hb 11,40); aqueles, porque só de ti hão de ser restaurados até a sua plenitude. Pois quem não sabe que, caindo do céu Satanás e os seus cúmplices, o número da multidão do alto ficou diminuído de uma parte não pequena? De ti, pois, todos esperam o seu acabamento: uns o do seu número, outros o do seu desejo. Reconhece, pois, a voz do salmo: Os justos me esperam, até que me retribuas (Sl 141,8).`
    },
    {
      n: 5,
      texto: `E deve notar-se que não se diz que ela os encontrou, mas antes que eles a encontraram a ela, enviados — suspeito eu — de propósito para isso mesmo. Pois como pregarão, se não forem enviados (Rm 10,15)? Enfim, tens nos Evangelhos a sua palavra: Ide; eis que vos envio (Lc 10,3); e: Ide, pregai o Evangelho a toda criatura (Mc 16,15). Assim é. Ela buscava o esposo, e o esposo não o ignorava. Pois fora ele que a despertara para isso mesmo, para que o buscasse, e lhe dera um coração para os preceitos e para a lei da vida e da disciplina (cf. Eclo 45,6), contanto que houvesse quem a instruísse e lhe ensinasse o caminho da prudência (cf. Is 40,14). E enviou ao seu encontro os que plantam e os que regam (cf. 1Cor 3,6), para a nutrirem e a confirmarem em toda a certeza da verdade, isto é, para lhe darem notícia do amado e a tornarem certa acerca dele; porque é a verdade que ela busca, e a que a sua alma verdadeiramente ama. E, na verdade, que amor fiel ou verdadeiro há na alma, senão aquele com que se ama a verdade? Sou dotado de razão, sou capaz da verdade; mas oxalá não o fosse, se me faltar o amor da verdade. Pois esse amor é o fruto destes ramos, e eu sou a raiz. Não estou a salvo do machado (cf. Mt 3,10), se for achado sem ele. Nesse dom da natureza, sem dúvida, resplandece aquela insígnia da imagem divina pela qual a alma sobrepuja os outros seres vivos. Daí vem que a minha alma ousa elevar-se aos doces e castos abraços da verdade, e repousar assim no seu amor com toda a segurança e suavidade — contanto, porém, que encontre graça aos olhos de tão grande esposo, para que ele a julgue digna de chegar a esta glória; ou antes, para que ele mesmo a apresente a si sem mancha nem ruga, nem coisa semelhante (Ef 5,27). Quanto perigo pensas que há, e de que castigo é digno, em ter ocioso tão grande dom de Deus? Mas disto, noutra ocasião.`
    },
    {
      n: 6,
      texto: `Agora, porém, a esposa não encontrou aquele que buscava; e foi encontrada por aqueles que não buscava. Ouçam isto os que não temem entrar nos caminhos da vida sem guia e sem mestre, sendo para si mesmos, na arte espiritual, discípulos e mestres ao mesmo tempo. E não lhes basta: ainda juntam discípulos para si, cegos guias de cegos (cf. Mt 15,14). Quantos se viu que por isso se desviaram perigosissimamente do caminho reto! Ignorando as astúcias de Satanás e os seus desígnios (cf. 2Cor 2,11), aconteceu que, tendo começado pelo espírito, acabaram pela carne (cf. Gl 3,3), arrastados torpemente, caídos para a condenação. Vejam, pois, os que são assim, como andar com cautela (cf. Ef 5,15), e tomem exemplo da esposa, que de modo nenhum conseguiu chegar àquele que desejava antes de lhe saírem ao encontro aqueles de cujo magistério se servisse para conhecer o amado, e certamente para aprender o temor do Senhor. Dá a mão ao sedutor quem se recusa a dá-la ao mestre. E quem deixa as ovelhas no pasto sem guarda é pastor não de ovelhas, mas de lobos.`
    },
    {
      n: 7,
      texto: `Vejamos agora como a esposa diz que foi encontrada. Pois parece-me que usou de modo bastante insólito a palavra "encontrar". Pois diz isto como se a Igreja tivesse vindo de um só lugar. Ora, ela veio do Oriente e do Ocidente, segundo a palavra do Senhor (Mt 8,11), e de todos os confins da terra. E nunca foi reunida num só lugar, onde fosse encontrada pelos apóstolos ou pelos anjos, para ser conduzida ou encaminhada àquele a quem a sua alma ama. Terá sido encontrada antes de ser reunida? Não, porque nem sequer existia. Por isso, se tivesse dito que foi recolhida, que foi reunida, ou, certamente — o que convém mais ao nome de Igreja —, que foi convocada pelos pregadores, eu teria passado adiante simplesmente, sem hesitar em nada. Pois são colaboradores de Deus (cf. 1Cor 3,9), a quem também ouviram dizer: Quem não recolhe comigo, dispersa (Mt 12,30). Nem me parecerá fora de propósito que alguém diga que foi fundada ou edificada por eles. Pois fizeram isso juntamente com aquele que diz nos Evangelhos: E sobre esta pedra edificarei a minha Igreja (Mt 16,18); e: Porque estava fundada sobre a rocha firme (Mt 7,25). Mas agora, não dizendo nada disto, e afirmando, contra o costume, que foi encontrada, faz-nos hesitar um pouco e leva-nos a suspeitar que se esconde nesta passagem alguma coisa que deve ser examinada com mais diligência.`
    },
    {
      n: 8,
      texto: `Queria, confesso, passar adiante e subtrair-me a este exame, para o qual não me sentia capaz. Mas, lembrando-me de em quantas coisas igualmente duvidosas e obscuras me senti ajudado, acima até da minha esperança, enquanto vós elevais os corações para o alto, envergonho-me da desconfiança; e, repreendendo o meu temor, empreendo — não, por certo, temerariamente — aquilo de que timidamente fugia. Estará presente, confio, o auxílio de costume; e, se não, junto de ouvintes benévolos não será inútil o que quis. Mas isto será o princípio do sermão seguinte; pois o presente terminamos aqui. Que ele mesmo vos conceda não só reter de memória o que se diz, mas também amá-lo ardentemente e cumpri-lo com eficácia: o esposo da Igreja, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
