SERMOES.sermao({
  id: 'bernardo-cantico-03',
  colecao: 'bernardo-cantico',
  ordem: 3,
  numero: 'III',
  titulo: 'Do beijo do pé, da mão e da boca do Senhor',
  fonte: 'De osculo pedis, manus et oris Domini',
  argumento: `Bernardo abre o sermão dizendo que hoje se lê no livro da experiência, e adverte que ninguém peça logo de início o beijo da boca. Traça então o caminho em três degraus — os pés, a mão, a boca —, tomando por figura a pecadora do Evangelho. O sermão é interrompido pela chegada de hóspedes ao mosteiro, e Bernardo sai para recebê-los.

Tradução feita do texto latino de Migne (PL 183, 794-796).`,
  pontos: [
    {
      n: 1,
      texto: `Hoje lemos no livro da experiência. Voltai-vos para dentro de vós mesmos, e cada um examine a própria consciência sobre o que vou dizer. Gostaria de saber se a algum de vós já foi concedido dizer de coração: Beije-me com o beijo da sua boca (Ct 1,1). Pois não é qualquer um que pode dizer isto com verdadeiro afeto; mas quem recebeu, ainda que uma só vez, o beijo espiritual da boca de Cristo, esse é impelido pela própria experiência e o pede de novo de bom grado. Penso que ninguém pode sequer saber o que ele é, senão quem o recebe: é o maná escondido (Ap 2,17), e só quem dele come terá ainda fome (Eclo 24,29). É a fonte selada (Ct 4,12), da qual o estranho não participa, e só quem dela bebe terá ainda sede. Ouve como o pede quem o experimentou: Devolve-me, diz ele, a alegria da tua salvação (Sl 50,14). Que não pretenda isto para si, portanto, uma alma como a minha, carregada de pecados e ainda sujeita às paixões da carne, que ainda não sentiu a suavidade do espírito e não tem nenhuma experiência das alegrias interiores.`
    },
    {
      n: 2,
      texto: `A uma alma assim, contudo, mostro o lugar que lhe convém no caminho da salvação. Não se erga temerariamente até a boca do sereníssimo Esposo, mas prostre-se comigo, cheia de temor, aos pés do severíssimo Senhor, e, como o publicano, olhe tremendo para a terra e não para o céu (Lc 18,13); não aconteça que o rosto acostumado às trevas, ofuscado pelas luzes do céu, seja esmagado pela glória e, ferido pelo esplendor desusado da majestade, volte a envolver-se numa cegueira ainda mais densa. Ó alma, quem quer que sejas nessa condição, não te pareça vil nem desprezível aquele lugar onde a santa pecadora depôs os seus pecados e se revestiu de santidade. Ali a etíope mudou de pele (Jr 13,23) e, restituída a uma nova brancura, já podia responder com confiança e verdade aos que a censuravam: Sou negra, mas formosa, filhas de Jerusalém (Ct 1,4). Queres saber com que arte o conseguiu, ou por que méritos o alcançou? Ouve em poucas palavras. Chorou amargamente e, arrancando do fundo das entranhas longos suspiros, sacudida por dentro de soluços salutares, lançou fora os humores amargos. O médico celeste acudiu sem demora, porque a sua palavra corre veloz (Sl 147,15). Não é a palavra de Deus um remédio? Certamente o é, forte e eficaz, que sonda os corações e os rins (Sl 7,10). Enfim, a palavra de Deus é viva e eficaz, mais penetrante que qualquer espada de dois gumes; penetra até dividir alma e espírito, juntas e medulas, e discerne os pensamentos (Hb 4,12). A exemplo, pois, desta bem-aventurada penitente, prostra-te também tu, ó mísera, para deixares de ser mísera; prostra-te também tu por terra; abraça os pés do Senhor, aplaca-o com beijos, rega-os com lágrimas — não para lavá-lo a ele, mas para te lavares a ti, e te tornares uma daquelas ovelhas tosquiadas que sobem do banho (Ct 4,2). E não ouses levantar o rosto, coberto de vergonha e de tristeza, antes de ouvires também tu: Os teus pecados estão perdoados (Lc 7,37-48); antes de ouvires: Levanta-te, levanta-te, cativa filha de Sião; levanta-te, sacode o pó (Is 52,1-2).`
    },
    {
      n: 3,
      texto: `Recebido, pois, o primeiro beijo aos pés, nem por isso presumas erguer-te logo ao beijo da boca: entre um e outro, terás como degrau um beijo intermediário, que receberás em segundo lugar, na mão. Ouve a razão disso. Se Jesus me disser: Os teus pecados estão perdoados, de que me adianta, se eu não deixar de pecar? Tirei a minha túnica; se tornar a vesti-la, que ganhei? Se tornar a sujar os pés que tinha lavado, de que terá valido lavá-los (Ct 5,3)? Sujo de toda espécie de vícios, jazi muito tempo no lodo da borra; mas, sem dúvida, recair é pior do que ter jazido. Lembro-me, enfim, de que aquele que me curou me disse: Eis que ficaste são; vai e não peques mais, para que não te aconteça coisa pior (Jo 5,14). Ora, quem me deu a vontade de me arrepender precisa acrescentar também a força de me conter, para que eu não repita aquilo de que tive de me arrepender, e o meu último estado não se torne pior que o primeiro (Mt 12,45). Pois ai de mim, mesmo arrependido, se ele retirar logo a sua mão, sem a qual nada posso fazer. Nada, digo: nem arrepender-me, nem conter-me. Por isso ouço o conselho do Sábio: Não repitas palavras na tua oração (Eclo 7,15). E temo também a ameaça do juiz contra a árvore que não dá bom fruto (Mt 3,10). Confesso, por isso, que não me basta a primeira graça, pela qual já me arrependo dos meus males, se não receber também a segunda: a de produzir frutos dignos de penitência (Lc 3,8) e não voltar mais ao vômito (Pr 26,11).`
    },
    {
      n: 4,
      texto: `Isto, portanto, me resta pedir e receber, antes de ousar tocar realidades mais altas e mais sagradas. Não quero chegar ao cume de repente; quero progredir pouco a pouco. Quanto desagrada a Deus a impudência do pecador, tanto lhe agrada o pudor do penitente. Mais depressa o aplacas se guardares a tua medida e não buscares o que está acima de ti. Longo e difícil é o salto do pé à boca, e nem sequer seria uma aproximação conveniente. Como assim? Ainda coberto do pó recente, vais tocar a boca sagrada? Ontem arrancado do lodo, hoje te apresentas diante do rosto da glória? Passa antes pela mão. Que ela primeiro te limpe e te levante. Como te levantará? Dando-te motivo para ousares. E que motivo é esse? A beleza da continência e os frutos dignos de penitência, que são as obras de piedade. Estas te levantarão do esterco (Sl 112,7) para a esperança de ousar coisas maiores. E, ao receberes o dom, beija a mão, isto é, dá glória não a ti, mas ao nome dele (Sl 113,9). Dá-lhe glória uma vez e outra: pelos pecados perdoados e pelas virtudes recebidas. Senão, vê como hás de proteger a fronte contra estes golpes: Que tens tu que não tenhas recebido? E, se o recebeste, por que te glorias como se não o tivesses recebido (1Cor 4,7)?`
    },
    {
      n: 5,
      texto: `Tendo, enfim, nesses dois beijos, a dupla experiência da bondade divina, talvez já não te envergonhes de aspirar a coisas mais santas. Pois, à medida que cresces na graça, cresce também a tua confiança. Daí vem que ames com mais ardor e batas à porta com mais confiança, pedindo o que sentes que te falta. E a quem bate se abrirá (Lc 11,10). Creio que aquele beijo supremo, seja ele qual for, de suprema condescendência e admirável suavidade, não será negado a quem está nessa disposição. Este é o caminho, esta é a ordem. Primeiro, lançamo-nos aos seus pés e choramos, diante do Senhor que nos fez (Sl 94,6), o mal que nós mesmos fizemos. Em segundo lugar, buscamos a mão daquele que nos levanta e fortalece os joelhos vacilantes. Por fim, depois de obter isso com muitas preces e lágrimas, ousamos talvez levantar a cabeça até a própria boca da glória — digo-o com temor e tremor —, não só para contemplá-la, mas também para beijá-la; porque o Cristo Senhor é espírito diante da nossa face (Lm 4,20), e, unidos a ele no beijo santo, tornamo-nos, por sua condescendência, um só espírito com ele.`
    },
    {
      n: 6,
      texto: `A ti, Senhor Jesus, a ti com razão disse o meu coração: A minha face te buscou; a tua face, Senhor, eu buscarei (Sl 26,8). Pela manhã me fizeste ouvir a tua misericórdia (Sl 142,8), quando, estando eu prostrado no pó e beijando os teus pés veneráveis, perdoaste a minha vida má. Depois, no correr do dia, alegraste a alma do teu servo (Sl 85,4), quando, no beijo da mão, me concedeste também a graça de viver bem. E agora, bom Senhor, que resta senão que, na plenitude da luz e no fervor do espírito, me admitas por tua bondade também ao beijo da boca e me enchas de alegria com a tua face (Sl 15,11)? Mostra-me, ó suavíssimo, ó sereníssimo, mostra-me onde apascentas o rebanho, onde repousas ao meio-dia (Ct 1,6). Irmãos, é bom estarmos aqui (Mt 17,4); mas eis que nos chamam os cuidados do dia (Mt 6,34). Os hóspedes que, segundo me avisam, acabam de chegar obrigam-me antes a interromper do que a concluir este sermão tão agradável. Vou ter com eles, para que nada falte aos deveres da caridade de que estamos falando, e não aconteça que também de nós se diga: Dizem e não fazem (Mt 23,3). Vós, entretanto, orai para que Deus aceite as ofertas voluntárias da minha boca (Sl 118,108), para vossa edificação e para louvor e glória do seu nome.`
    }
  ]
});
