SERMOES.sermao({
  id: 'bernardo-cantico-81',
  colecao: 'bernardo-cantico',
  ordem: 81,
  numero: 'LXXXI',
  titulo: 'Da afinidade e semelhança da alma com o Verbo, segundo a identidade da essência, a imortalidade da vida e a liberdade do arbítrio',
  fonte: 'De convenientia et similitudine animae cum Verbo',
  argumento: `Continua a investigação sobre a afinidade da alma com o Verbo, agora quanto à semelhança, para que a alma, conhecendo a sua origem, se envergonhe de uma vida indigna e se aproxime com confiança dos abraços do Verbo. A semelhança está em três coisas. A simplicidade: só em Deus ser é o mesmo que ser feliz; na alma, ser é o mesmo que viver — degrau inferior, mas o único a partir do qual se sobe à vida feliz; nos animais e nas plantas, nem isto, pois se desfazem nas suas partes. A imortalidade: a alma, sendo vida para si mesma, não pode cair da vida, embora mude com os afetos, ao passo que só Deus, imutável, possui a imortalidade perfeita; e a alma que vive segundo a carne está morta em vida.

A terceira é a liberdade do arbítrio, pedra preciosa engastada no ouro, que torna o homem capaz de mérito. O pecado não a destrói: a vontade, que se fez escrava consentindo no pecado, continua a sê-lo querendo, e cria para si uma necessidade que não a desculpa, porque é voluntária. Daí o gemido de Paulo: "Infeliz de mim!"; mas ele serve à lei de Deus com a mente, e o mal da carne já não é seu. Bernardo remete ao seu tratado sobre a Graça e o Livre-Arbítrio, onde falou de outro modo da imagem e da semelhança, mas não em contradição.

Tradução feita do texto latino de Migne (PL 183, 1171-1176).`,
  pontos: [
    {
      n: 1,
      texto: `Investigou-se antes a afinidade da alma com o Verbo, e isto necessariamente. Pois que acordo pode haver entre tão grande majestade e tão grande pobreza, para que se diga que aquela sublimidade e aquela humildade se abraçam, como de igual para igual, com o costume e o amor dos esposos? Se o dizemos com verdade, é uma confiança muito alegre; se falsamente, uma audácia muito digna de castigo. Por isso foi preciso investigar a afinidade entre eles; e já se encontrou muita, mas não toda. Pois quem, por mais obtuso que seja, não vê quão de perto se olham a imagem e o que é feito à imagem? Uma destas coisas o sermão de ontem, se vos lembrais, atribuiu a um, e a outra ao outro. E ali se mostrou o parentesco não só quanto à imagem, mas também quanto à semelhança; só que ainda não declaramos em que coisa, ou em que coisas, consiste principalmente a própria semelhança. Vamos, apliquemo-nos agora a esta declaração, para que, quanto mais plenamente a alma conhecer a sua origem, tanto mais se envergonhe de levar uma vida degenerada; ou antes, para que o que descobrir de viciado pelo pecado na sua natureza se esforce por reformá-lo com empenho, a fim de que, governando-se de modo digno da sua estirpe — pelo dom de Deus, é claro —, se aproxime com confiança dos abraços do Verbo.`
    },
    {
      n: 2,
      texto: `Repare, pois, que por esta nobreza da semelhança divina há nela aquela simplicidade natural da sua substância pela qual ser é para ela o mesmo que viver, embora não o mesmo que viver bem ou viver feliz; para que seja semelhança, não igualdade. Degrau próximo, mas degrau. Pois não são da mesma excelência nem da mesma altura ter como uma só coisa ser e viver, e ter como uma só coisa ser e viver feliz. Se, pois, aquilo é próprio do Verbo, pela sua sublimidade, e isto da alma, pela semelhança, salva a eminência do Verbo, é manifesta a afinidade das naturezas, manifesta a prerrogativa da alma. E, para que o que se diz fique mais claro: só para Deus ser é o mesmo que ser feliz; e esta é a primeira e puríssima simplicidade. A segunda é semelhante a esta: ter como uma só coisa ser e viver; e isto é da alma. A partir deste degrau, embora inferior, pode-se subir não só ao viver bem, mas também ao viver feliz; não que, mesmo então, ser seja o mesmo que ser feliz para quem lá chegar; de modo que se glorie da semelhança, mas tenha sempre, pela desigualdade, motivo para que todos os seus ossos digam: Senhor, quem é semelhante a ti (Sl 34,10)? Bom degrau é, contudo, o da alma, a partir do qual, e só dele, se sobe à vida feliz.`
    },
    {
      n: 3,
      texto: `Pois há seres vivos, e deles há dois gêneros: os que sentem e os que não sentem. Os que sentem são preferidos aos que não sentem, e a uns e outros é preferida a vida pela qual se vive e se sente. A vida e o vivente não estarão no mesmo degrau; muito menos a vida e as coisas que não têm vida. A alma é vida: vivente, sim, mas não por outra coisa senão por si mesma; e por isso, para falar com propriedade, não tanto vivente quanto vida. Daí vem que, infundida no corpo, o vivifica, de modo que o corpo, pela presença da vida, não é vida, mas vivente. Por onde se vê que nem sequer para o corpo vivo viver é o mesmo que ser, pois pode ser e não viver. Muito menos subirão a este degrau as coisas privadas de vida. Mas nem tudo o que se chama vida, ou é vida, poderá por isso chegar até aqui. Há a vida dos animais e a das árvores: uma dotada de sentido, a outra sem ele. Mas para nenhuma delas ser é o mesmo que viver, pois, segundo a opinião de muitos, existiram nos elementos antes de estarem, aquela nos membros, esta nos ramos. E, segundo isto, quando deixam de vivificar, deixam ao mesmo tempo de viver, mas não de ser. Soltam-se e dissolvem-se ao mesmo tempo, como coisas não só ligadas, mas compostas. Pois nenhuma delas é uma coisa simples, mas composta de muitas. E por isso não se reduz a nada, mas desfaz-se em partes, voltando cada uma ao seu princípio: por exemplo, o ar ao ar, o fogo ao fogo, e assim o resto. Para tal vida, pois, de modo nenhum ser e viver são o mesmo, pois ela é mesmo quando não vive.`
    },
    {
      n: 4,
      texto: `Nenhuma destas coisas, para as quais ser não é o mesmo que viver, jamais progredirá ou se elevará ao viver bem e feliz, pois nem sequer pôde chegar a este degrau inferior. Só a alma do homem, que se sabe estar neste degrau, foi criada nessa dignidade: vida pela vida, simples pelo simples, imortal pelo imortal, de modo que não está longe do degrau supremo, onde ser é o mesmo que viver feliz, no qual só está aquele que é o único bem-aventurado e poderoso, o Rei dos reis e Senhor dos senhores (1Tm 6,15). A alma recebeu, pois, na sua criação, se não o ser feliz, ao menos o poder ser feliz; aproximando-se assim, quanto lhe é dado, do degrau supremo, mas sem o atingir. Pois nem para ela, como dissemos acima, ser será alguma vez o mesmo que ser feliz, nem quando for feliz. Confessamos a semelhança; recusamos a igualdade. Por exemplo: Deus é vida, e a alma também é vida; semelhante, mas desigual. Semelhante, porque é vida, porque vive por si mesma, porque não só vive, mas vivifica, assim como ele é tudo isto. Desigual, quanto a criatura dista do Criador. Desigual, porque, assim como não existiria se não fosse criada por ele, também não viveria se não fosse vivificada por ele. Não viveria, digo, com a vida espiritual, não com a natural. Pois com a natural, mesmo a que não vive espiritualmente vive necessariamente de modo imortal. Mas que vida é essa, em que seria melhor não ter nascido do que não morrer para ela! É antes morte, e tanto mais grave porque é do pecado, não da natureza. Enfim, a morte dos pecadores é péssima (Sl 33,22). Assim, pois, a alma que vive segundo a carne está morta em vida (cf. 1Tm 5,6), pois melhor lhe seria não viver de todo do que viver assim. E desta morte, de certo modo vital, de modo nenhum ressurgirá, senão pela palavra da vida — ou antes, pelo Verbo que é a vida, que vive e vivifica.`
    },
    {
      n: 5,
      texto: `Por outro lado, a alma é imortal, e também nisto é semelhante ao Verbo, mas não igual. Pois a imortalidade da Divindade sobrepuja tanto, que o Apóstolo diz de Deus: O único que possui a imortalidade (1Tm 6,16). O que penso ter sido dito porque só Deus é imutável por natureza, ele que diz: Eu sou o Senhor, e não mudo (Ml 3,6). Pois a imortalidade verdadeira e íntegra não admite mudança, assim como não admite fim, porque toda mudança é uma certa imitação da morte. Pois tudo o que muda, ao passar de um modo de ser a outro, necessariamente morre de certo modo para o que é, para começar a ser o que não é. E, se há tantas mortes quantas mudanças, onde está a imortalidade? E a esta vaidade foi sujeita a própria criação, não por sua vontade, mas por causa daquele que a sujeitou na esperança (Rm 8,20). Contudo, a alma é imortal, porque, sendo ela vida para si mesma, assim como não tem por onde cair de si, também não tem por onde cair da vida. Mas, como é certo que ela muda com os seus afetos, reconheça que é semelhante a Deus na imortalidade de tal modo que saiba que lhe falta uma parte não pequena da imortalidade, cedendo a imortalidade absoluta e perfeita só àquele em quem não há mudança nem sombra de variação (Tg 1,17). Com esta discussão, contudo, descobriu-se que não é medíocre a dignidade da alma, que parece aproximar-se do Verbo por uma dupla vizinhança de natureza: a simplicidade da essência e a perpetuidade da vida.`
    },
    {
      n: 6,
      texto: `Mas ocorre ainda uma coisa, que de modo nenhum deixarei de lado, pois não torna a alma menos ilustre nem menos semelhante ao Verbo, e talvez até mais. É a liberdade do arbítrio, coisa verdadeiramente divina que resplandece na alma como uma pedra preciosa engastada no ouro. Por ela, com efeito, tem entre o bem e o mal, entre a vida e a morte (cf. Dt 30,15), e também entre a luz e as trevas, o conhecimento para julgar e a faculdade de escolher; e o mesmo quanto a outras coisas que, semelhantemente, pareçam opor-se entre si no que diz respeito à disposição do ânimo. Entre elas, um certo árbitro censor — que é o olho da alma — julga e discerne, árbitro no discernir e livre no escolher. Por isso se chama livre-arbítrio: porque lhe é permitido mover-se entre estas coisas segundo o arbítrio da vontade. Daí vem que o homem é capaz de merecer. Pois todo o bem ou mal que fizeres, que eras livre de não fazer, é com razão contado como mérito. E, assim como é com razão louvado não só quem pôde fazer o mal e não o fez (cf. Eclo 31,10), mas também quem pôde não fazer o bem e o fez, assim também não fica sem mau mérito tanto quem pôde não fazer o mal e o fez, como quem pôde fazer o bem e não o fez. Onde não há liberdade, também não há mérito. Por isso os animais privados de razão nada merecem, porque, assim como carecem de deliberação, carecem também de liberdade. São movidos pelo sentido, levados pelo impulso, arrastados pelo apetite. Pois não têm juízo com que se julguem ou se governem, nem sequer o instrumento do juízo, que é a razão. Daí vem que não são julgados, porque não julgam. Pois com que razão se lhes pediriam contas de uma razão que não receberam?`
    },
    {
      n: 7,
      texto: `Só o homem não sofre esta violência da natureza, e por isso é o único livre entre os seres vivos. E, no entanto, sobrevindo o pecado, também ele sofre uma certa violência, mas da vontade, não da natureza, de modo que nem assim é privado da liberdade inata. Pois o que é voluntário é também livre. É verdade que o pecado fez com que o corpo que se corrompe pese sobre a alma (Sb 9,15); mas pelo amor, não pelo peso. Pois, se a alma, que por si mesma pôde cair, já não pode por si mesma levantar-se, a causa é a vontade, que, enlanguescida e prostrada pelo amor viciado e vicioso do corpo corrompido, não admite ao mesmo tempo o amor da justiça. Assim, por não sei que modo perverso e admirável, a própria vontade, mudada para pior pelo pecado, cria para si uma necessidade; de modo que nem a necessidade, sendo voluntária, pode desculpar a vontade, nem a vontade, estando seduzida, pode excluir a necessidade. Pois esta necessidade é, de certo modo, voluntária. É uma espécie de violência agradável, que acaricia oprimindo e oprime acariciando; por isso a vontade culpada, uma vez que consentiu no pecado, já não pode por si mesma sacudi-lo de si, nem pode de modo algum, com razão, desculpar-se. Daí aquela voz queixosa, como de quem geme sob o peso desta necessidade: Senhor, diz, sofro violência; responde por mim (Is 38,14). Mas, sabendo, por outro lado, que não se queixaria com justiça contra o Senhor, já que a causa era antes a sua própria vontade, repara no que acrescentou em seguida: Que direi, ou que me responderá ele, se fui eu mesmo que o fiz (Is 38,15)? Estava oprimido por um jugo, mas não por outro senão o de uma servidão voluntária; e pela servidão era digno de compaixão, mas pela vontade, indesculpável. Pois é a vontade que, sendo livre, se fez escrava do pecado, consentindo no pecado; e é igualmente a vontade que se mantém sob o pecado, servindo voluntariamente.`
    },
    {
      n: 8,
      texto: `Vê o que dizes, diz-me alguém. Tu chamas voluntário ao que consta ser já necessário? É verdade que a vontade se entregou a si mesma; mas não é ela que se retém: antes é retida, mesmo sem querer. Concedes ao menos, e bem, que é retida. Mas retém atentamente isto: que é a vontade que confessas ser retida. Falas, pois, de uma vontade que não quer? A vontade, certamente, não é retida sem querer. Pois a vontade é de quem quer, não de quem não quer. E, se é retida querendo, é ela que se retém. Que dirá, pois, ou que lhe responderá, se foi ela mesma que o fez? Que fez? Fez-se escrava; donde se diz: Quem comete o pecado é escravo do pecado (Jo 8,34). Por isso, quando pecou — e pecou quando decidiu obedecer ao pecado —, fez-se escrava. Mas seria livre, se não continuasse a fazê-lo. Ora, continua, mantendo-se na mesma servidão. Pois a vontade não é retida sem querer: é vontade. Portanto, porque quer, não só se fez escrava, mas continua a fazer-se. Com razão, pois, deve lembrar-se muitas vezes: que lhe responderá, se foi ela que o fez, e é ela que o faz?`
    },
    {
      n: 9,
      texto: `Mas não me farás deixar de crer, dizes, na necessidade que padeço, que experimento em mim mesmo, e contra a qual luto sem cessar. Onde, pergunto, sentes esta necessidade? Não é na vontade? Não queres, pois, com pouca firmeza aquilo que queres até necessariamente. Muito queres aquilo que não podes deixar de querer, e não lutas muito contra isso. E onde há vontade, há também liberdade. Digo isto, porém, da natural, não da espiritual, a liberdade com que, como diz o Apóstolo, Cristo nos libertou (Gl 4,31). Pois desta diz o mesmo Apóstolo: Onde está o Espírito do Senhor, aí está a liberdade (2Cor 3,17). Assim, de um modo admirável e mau, sob esta necessidade de certo modo voluntária e mal livre, a alma é ao mesmo tempo escrava e livre: escrava pela necessidade, livre pela vontade; e, o que é mais admirável e mais infeliz, culpada porque livre, e escrava porque culpada, e por isso escrava porque livre. Infeliz de mim! Quem me libertará da opressão desta servidão vergonhosa (cf. Rm 7,24)? Infeliz, mas livre. Livre, porque homem; infeliz, porque escravo. Livre, porque semelhante a Deus; infeliz, porque contrário a Deus. Ó guarda dos homens, por que me puseste contrário a ti? Puseste-me, sim, porque não o impediste. Aliás, fui eu mesmo que me pus, e tornei-me pesado para mim mesmo (Jó 7,20). Com toda a justiça, para que o teu inimigo seja também meu inimigo, e quem te resiste resista também a mim. E eu, que me tornei contrário a ti, eu que me tornei contrário a mim mesmo, e encontro nos meus membros o que contradiz a minha mente e a tua lei (cf. Rm 7,23), quem me livrará das minhas próprias mãos? Pois não faço o que quero — e quem me impede sou eu, não outro —, e faço o que odeio (Rm 7,15) — e quem me obriga sou eu, não outro. E oxalá este impedimento e esta coação fossem de tal modo violentos que não fossem voluntários, pois talvez assim pudesse ser desculpado; ou, pelo menos, de tal modo voluntários que não fossem violentos, pois assim, certamente, poderia ser corrigido. Mas agora não há saída nenhuma para o infeliz, a quem a vontade, como disse, torna indesculpável, e a necessidade, incorrigível. Quem me arrancará da mão do pecador, e da mão de quem age contra a lei e do iníquo (cf. Sl 70,4)?`
    },
    {
      n: 10,
      texto: `Pergunta alguém de quem me queixo? De mim. Eu sou esse pecador, esse fora da lei, esse iníquo. Pecador, porque pequei; fora da lei, porque persisto, por vontade, em agir contra a lei. Pois a minha própria vontade é a lei nos meus membros, que recalcitra contra a lei divina. E, como a lei do Senhor é a lei da minha mente, como está escrito: A lei do seu Deus está no seu coração (Sl 36,31), por isso a minha própria vontade se mostra contrária até a mim mesmo, o que é a maior das iniquidades. Pois para quem não serei iníquo, eu que o sou para mim? Quem é mau para si mesmo, diz, para quem será bom (Eclo 14,5)? Confesso: não sou bom, porque não há bem em mim. Mas hei de consolar-me, porque esta é também a voz dos santos: Sei, diz, que em mim não habita o bem. Mas distingue o que diz: em mim; e explica: na minha carne (Rm 7,18), por causa da lei contrária que nela está. Pois tem uma lei também na mente, e essa é melhor. Não é boa a lei de Deus? E, se é mau por causa da lei má, como não será bom por causa da boa? Ou é sua a lei má que está na sua carne, e por isso é mau pela má, e de modo nenhum bom pela boa? Não é assim. A lei do seu Deus está na sua mente, e de tal modo na mente que é também da mente. É testemunha ele mesmo, que diz: Encontro nos meus membros outra lei, que luta contra a lei da minha mente (Rm 7,23). Seria seu o que é da sua carne, e não seu o que é da sua mente? Eu digo ainda mais. E por que não diria o que diz o mesmo mestre? Pois, servindo com a mente à lei de Deus, e com a carne à lei do pecado (Rm 7,25), mostra claramente o que confessa ser mais seu, quando julga tão alheio a si o mal que está na carne, que diz: Portanto, já não sou eu que o faço, mas o pecado que habita em mim (Rm 7,17). E talvez por isso tenha dito expressamente que encontrou nos seus membros outra lei, porque a considerava alheia e como que estranha. Por isso ouso dizer ainda mais — não, por certo, temerariamente —: que Paulo já não é mau pelo mal que tem na carne, mas antes bom pelo bem que tem na mente. Não é bom quem consente na lei de Deus, reconhecendo que é boa (cf. Rm 7,16)? Pois, ainda que confesse igualmente que serve à lei do pecado, fá-lo com a carne, não com a mente. E, servindo com a mente à lei de Deus e com a carne à lei do pecado, qual destas coisas julgas que se deve imputar sobretudo a Paulo, vê-lo tu. Quanto a mim, confesso que facilmente me convenço de que o que é da mente vale mais do que o que é da carne, não só para mim, mas também para o próprio Paulo, como já se disse, que diz: Se faço o que não quero, já não sou eu que o faço, mas o pecado que habita em mim (Rm 7,20).`
    },
    {
      n: 11,
      texto: `Mas basta isto sobre a liberdade. No livrinho que escrevi sobre a Graça e o Livre-Arbítrio, lê-se talvez sobre a imagem e a semelhança uma exposição diferente, mas, penso eu, não contrária. Lestes aquilo, ouvistes isto: qual aprovais mais, deixo ao vosso juízo; ou, se entendeis alguma coisa melhor do que uma e outra, nisto me alegro e me alegrarei (cf. Fl 1,18). Mas, seja como for, tendes por agora recomendadas três coisas principais: a simplicidade, a imortalidade e a liberdade. E penso que já vos aparece com clareza que a alma, pela semelhança inata e nobre que nelas brilha de modo tão insigne, tem não pequena afinidade com o Verbo, o esposo da Igreja, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
