SERMOES.sermao({
  id: 'bernardo-cantico-63',
  colecao: 'bernardo-cantico',
  ordem: 63,
  numero: 'LXIII',
  titulo: 'A vinha do homem piedoso e sábio é a sua própria vida, a sua mente e a sua consciência, que ele deve cultivar com seriedade; dos dois gêneros de raposas, os aduladores e os maldizentes; e das tentações dos noviços',
  fonte: 'De vinea viro pio et sapienti',
  argumento: `"Apanhai-nos as raposas pequenas, que destroem as vinhas." Bernardo começa por rejeitar a leitura literal: ninguém leria com tanta veneração um livro santo para aprender a guardar vinhas contra raposas. A vinha do sábio é a sua própria vida, a sua mente e a sua consciência; o insensato nem vinha tem, só urtigas e espinhos, e vive morto. No justo, a virtude é a videira, a ação é o ramo, o testemunho da consciência é o vinho.

As raposas mais perigosas são o maldizente oculto e o adulador lisonjeiro. O sábio procura "apanhá-los", mas com benefícios, conselhos e orações, amontoando brasas sobre a cabeça deles até os ganhar para Cristo. Os frutos da vinha são os nossos progressos, que o Homem-Deus considera seus. E Bernardo se volta para os noviços: neles a vinha ainda está em flor, e o perigo não são as raposas, mas a geada. Segue uma descrição célebre da tibieza que se instala na alma do noviço, como uma febre, e que termina no salto "do claustro para o mundo, do paraíso para o inferno". As raposas dos mais adiantados ficam para o sermão seguinte.

Tradução feita do texto latino de Migne (PL 183, 1080-1083).`,
  pontos: [
    {
      n: 1,
      texto: `Apanhai-nos as raposas pequenas, que destroem as vinhas; pois a nossa vinha está em flor (Ct 2,15). Está claro que não foi em vão que se foi às vinhas, pois se encontraram lá raposas a destruí-las. Isto é a letra. E o espírito? Antes de tudo, rejeitemos de todo nesta explicação o sentido comum e usual da letra, como inepto e insosso, e de todo indigno de ser recebido numa Escritura tão santa e tão autorizada. A não ser que alguém seja tão insensato e estúpido que tenha por grande coisa ter aprendido dela, como os filhos deste mundo, a cuidar das propriedades terrenas, a guardar e defender as vinhas dos animais que as invadem, para não perder o fruto do vinho, no qual está a luxúria, e para que não se percam o trabalho e a despesa. Grande prejuízo, sem dúvida, para lermos por isso o livro santo com tanto empenho e tanta veneração: aprender nele a guardar as vinhas das raposas, para que as bolsas não se esvaziem em vão no seu cultivo, se formos preguiçosos em guardá-las! Não sois tão rudes, nem tão desprovidos da graça espiritual, que penseis de modo tão carnal. Busquemos, pois, estas coisas no espírito. Ali encontramos, com um entendimento são e um sentido digno, tanto as vinhas em flor como as raposas que as destroem; e em apanhá-las ou afastá-las trabalha-se com mais honra e mais proveito. Ou duvidais de que se deve pôr muito mais vigilância em guardar as mentes do que as colheitas; muito mais cuidado em nos guardarmos, por causa daquelas, das maldades espirituais, do que em apanhar, por causa destas, as raposinhas astutas?`
    },
    {
      n: 2,
      texto: `Mas agora tenho de mostrar quais são estas videiras e estas raposas espirituais. A vós caberá, filhos, cuidar cada um da sua vinha, quando, pela minha exposição, perceber em que e de quem deve sobretudo guardar-se. Para o homem sábio, a vinha é a sua vida, a sua mente, a sua consciência. Pois o sábio não deixará em si nada inculto nem abandonado. O insensato não é assim. Nele acharás tudo descuidado, tudo caído, tudo inculto e sujo. O insensato não tem vinha. Como pode haver vinha onde não aparece em parte alguma nada plantado, nada trabalhado? A vida do insensato está toda coberta de espinhos e de abrolhos: e é vinha? Se o foi, já não o é, reduzida a um deserto. Onde está a videira da virtude? Onde o cacho da boa obra? Onde o vinho da alegria espiritual? Passei pelo campo do preguiçoso, diz, e pela vinha do homem insensato: e eis que as urtigas tinham enchido tudo, os espinhos lhe cobriam a superfície, e o muro de pedras estava destruído (Pr 24,30-31). Ouves o sábio zombar do insensato, porque, por descuido, reduziu a não-vinha os bens da natureza e os dons da graça que talvez recebera pelo banho da regeneração, a sua primeira vinha, plantada por Deus e não pelo homem. Enfim, não pode haver vinha onde não há vida. Pois aquilo que o insensato vive, eu antes o chamaria morte do que vida. Como pode haver vida com esterilidade? A árvore seca e tornada estéril não se julga morta? Também os sarmentos estão mortos. E matou, diz, com a saraiva as suas vinhas (Sl 77,47), mostrando que estão privadas de vida as que foram condenadas à esterilidade. Assim o insensato, pelo próprio fato de viver inutilmente, está morto enquanto vive (cf. 1Tm 5,6).`
    },
    {
      n: 3,
      texto: `Só ao sábio, pois, convém ter, ou antes ser, uma vinha, porque tem vida. É árvore frutífera na casa de Deus, e por isso árvore viva. Pois a própria sabedoria, pela qual se diz sábio e o é, é árvore de vida para os que a abraçam (Pr 3,18). Por que não viveria quem a abraça? Vive, mas da fé. Pois o sábio é justo, e o justo vive da fé (Hb 10,38). E, se a alma do justo é trono da sabedoria, como é, sem dúvida é sábio quem é justo. Este, pois, quer lhe chames justo, quer sábio, nunca viverá sem vinha, porque nunca deixará de viver. Pois para ele a vinha é o mesmo que a vida. E boa é a vinha do justo, ou antes, o justo é uma boa vinha: nele a virtude é a videira, a ação é o ramo, o vinho é o testemunho da consciência, a língua é o lagar onde ele se espreme em palavras. Enfim: A nossa glória, diz, é esta: o testemunho da nossa consciência (2Cor 1,12). Vês que no sábio nada fica ocioso? A palavra, o pensamento, o modo de viver, e tudo o mais que vem dele, por que não seria tudo lavoura de Deus, edifício de Deus (cf. 1Cor 3,9) e vinha do Senhor dos exércitos? Enfim, que se poderia perder dele, quando nem sequer a sua folha cairá (cf. Sl 1,3)?`
    },
    {
      n: 4,
      texto: `Mas a uma vinha assim nunca faltarão ataques, nunca faltarão ciladas. Pois onde há muitos bens, muitos são também os que os comem (Ecl 5,10). O sábio será cuidadoso em guardar a sua vinha não menos do que em cultivá-la, e não deixará que as raposas a devorem. Péssima raposa é o maldizente oculto; mas não é menos perverso o adulador lisonjeiro. O sábio se guardará destes. Procurará, quanto estiver em si, apanhar os que fazem estas coisas — mas apanhá-los com benefícios e serviços, com conselhos salutares e com orações por eles a Deus. Não cessará de amontoar tais brasas sobre a cabeça do maldizente (cf. Rm 12,20), e também sobre a do adulador, até que, se for possível, tire do coração daquele a inveja e deste a simulação, cumprindo o mandamento do esposo, que diz: Apanhai-nos as raposas pequenas, que destroem as vinhas. Não te parece apanhado aquele que, com o rosto coberto de rubor, envergonhando-se do seu próprio juízo, é ele mesmo testemunha da sua confusão e do seu arrependimento, seja por ter odiado um homem digníssimo de amor, seja por ter amado só com palavras e com a língua aquele por quem experimentou, ainda que tarde, ser amado com obras e em verdade (cf. 1Jo 3,18)? Apanhado, sem dúvida, e apanhado para o Senhor, segundo o que ele expressamente disse: Apanhai-nos. Oxalá eu pudesse apanhar assim todos os que sem causa se opõem a mim, para restituí-los ou ganhá-los para Cristo! Assim, assim sejam confundidos e envergonhados os que procuram a minha vida; recuem e corem os que me querem mal (Sl 34,4), para que também eu me ache obediente ao esposo, apanhando também eu as raposas, não para mim, mas para ele. Mas volte o sermão ao seu princípio, para que a explicação prossiga pela sua ordem.`
    },
    {
      n: 5,
      texto: `Apanhai-nos as raposas pequenas, que destroem as vinhas. É um passo moral; e, segundo a doutrina dos costumes, já mostramos que estas vinhas espirituais não são senão os homens espirituais, em quem tudo o que é interior está cultivado, tudo germina, tudo dá fruto e gera o espírito de salvação; de modo que, assim como se disse do reino de Deus, também destas vinhas do Senhor dos exércitos podemos dizer igualmente que estão dentro de nós (cf. Lc 17,21). Enfim, lê-se no Evangelho que o reino de Deus será dado a um povo que produza os seus frutos (Mt 21,43). São estes os que Paulo enumera, dizendo: O fruto do Espírito é caridade, alegria, paz, paciência, longanimidade, bondade, benignidade, mansidão, fé, modéstia, continência, castidade (Gl 5,22-23). Estes frutos são os nossos progressos. Estes são agradáveis ao esposo, porque ele cuida de nós (cf. 1Pd 5,7). Acaso Deus se preocupa com arbustos? O Homem-Deus ama os homens, não as árvores, e considera os nossos progressos como frutos seus. Observa com cuidado o tempo deles, sorri-lhes quando aparecem, e, solícito, esforça-se para que, uma vez aparecidos, não se percam para nós — ou antes, para que não se percam para ele: pois considera-se a si mesmo como nós. E por isso, previdente, manda que se apanhem para ele as raposinhas que armam ciladas, para que não roubem os frutos novos. Apanhai-nos, diz, as raposas pequenas, que destroem as vinhas. E, como se alguém dissesse: Temes cedo demais; ainda não chegou o tempo dos frutos, diz: Não é assim, pois a nossa vinha está em flor. Depois das flores, os frutos não tardam; ainda aquelas estão a cair, e estes já rompem, já começam a aparecer.`
    },
    {
      n: 6,
      texto: `Esta parábola é do tempo presente. Vedes estes noviços? Chegaram há pouco, converteram-se há pouco. Não podemos dizer deles que a nossa vinha já floresceu: está a florescer. Por enquanto, o que vedes aparecer neles é flor; o tempo dos frutos ainda não chegou. A flor é o seu modo de vida novo, a flor é a forma recente de uma vida mais corrigida. Revestiram-se de um rosto disciplinado e de uma boa compostura de todo o corpo. Agrada-me, confesso, o que aparece por fora: um cuidado menor do corpo e das roupas, palavras mais raras, o rosto mais alegre, o olhar mais pudico, o andar mais grave. Mas, como estas coisas começaram há pouco, pela sua própria novidade devem ser consideradas flores, e esperança de frutos mais do que frutos. Por vós, filhinhos, não tememos a astúcia das raposas, que, como se sabe, invejam mais os frutos do que as flores. O vosso perigo vem de outra parte. O que temo para as flores é a queimadura — não o roubo, mas a queimadura do frio. Desconfio do vento norte e das geadas da manhã, que costumam matar as flores temporãs e roubar os frutos. Assim, é do norte que se abre o vosso mal (cf. Jr 1,14). Diante do seu frio, quem resistirá (Sl 147,17)? Se este frio invadir uma vez a alma — pelo descuido da alma, como costuma acontecer, quando o espírito cochila — e depois, sem que ninguém o impeça (Deus nos livre!), chegar ao seu interior, descer às entranhas do coração e ao seio da mente, abalar os afetos, ocupar os caminhos do conselho, perturbar a luz do juízo, escravizar a liberdade do espírito, logo, como costuma acontecer no corpo aos que têm febre, sobrevém uma espécie de arrepio do ânimo, e o vigor afrouxa; finge-se fraqueza das forças, exagera-se o horror da austeridade, inquieta o medo da pobreza, o ânimo se encolhe, a graça se retira, a vida parece longa demais, a razão adormece, o espírito se apaga, o fervor de noviço esfria, a tibieza enfastiada pesa cada vez mais, a caridade fraterna arrefece, o prazer lisonjeia, a segurança engana, o costume chama de volta. Que mais? Faz-se que não se vê a lei, renuncia-se ao direito, proscreve-se o que é lícito, abandona-se o temor do Senhor. Por fim, rende-se à impudência, e ousa-se aquele salto temerário, vergonhoso, torpíssimo, cheio de ignomínia e de confusão: do alto para o abismo, do pavimento para o monturo, do trono para a cloaca, do céu para a lama, do claustro para o mundo, do paraíso para o inferno. Mostrar o princípio e a origem desta peste, e com que arte se evita ou com que virtude se vence, não é deste momento; isso ficará para outra ocasião. Agora prossigamos o que começamos.`
    },
    {
      n: 7,
      texto: `É preciso voltar o sermão para os mais adiantados e mais firmes, para a vinha que já floresceu; a qual, embora não tenha de temer o frio para as flores, não tem os frutos seguros contra as raposas. É preciso dizer mais claramente o que são espiritualmente estas raposas, por que se chamam pequenas, por que se manda sobretudo apanhá-las, e não afugentá-las ou matá-las; e também apresentar os diversos gêneros destes animais, para maior conhecimento e cautela dos ouvintes; mas não neste sermão, para evitar o fastio, e para que a prontidão da nossa devoção se mantenha na ação de graças e no louvor da glória do grande Esposo da Igreja, nosso Senhor Jesus Cristo, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
