SERMOES.sermao({
  id: 'bernardo-cantico-56',
  colecao: 'bernardo-cantico',
  ordem: 56,
  numero: 'LVI',
  titulo: 'Os pecados e os vícios são como paredes que se interpõem entre Deus e o pecador',
  fonte: 'Quod peccata et vitia sunt tanquam parietes',
  argumento: `"Eis que ele está de pé atrás da parede, olhando pelas janelas, espreitando pelas grades." A parede é a carne, e aproximar-se dela foi a encarnação; as janelas e as grades são os sentidos e os afetos humanos, pelos quais o Verbo fez a experiência das nossas misérias. Já as conhecia, mas de outro modo: assim como aprendeu a obediência pelo que sofreu, aprendeu também a misericórdia. E está "de pé" porque só ele esteve na carne sem pecado; foi quebrado no corpo na cruz e continuou de pé pela divindade, como o Moisés do salmo, que ficou de pé na quebra.

Para nós, também o nosso corpo esconde a sua face; mas o que separa de Deus não é o corpo, e sim o pecado. Entre a esposa e o esposo há uma só parede; entre o pecador e Deus há muitas. Bernardo as enumera: a concupiscência, o consentimento, o ato, o costume e o desprezo. Quem resiste à primeira impede que se levantem as outras. E é preciso deixar abertas as janelas da confissão: a grade estreita, que é a confissão dos pecados, feita com o coração apertado; e a janela larga, que é a confissão do louvor.

Tradução feita do texto latino de Migne (PL 183, 1046-1050).`,
  pontos: [
    {
      n: 1,
      texto: `Eis que ele está de pé atrás da parede, olhando pelas janelas, espreitando pelas grades (Ct 2,9). Segundo a letra, parece dizer que aquele que se via chegar aos saltos se tinha aproximado até a morada da esposa e, de pé atrás da parede, espreitava com curiosidade pelas janelas e pelas frestas, e por pudor não se atrevia a entrar. Segundo o espírito, entende-se igualmente que se aproximou, mas de outro modo — como convinha que o fizesse o esposo celeste e que o dissesse o Espírito Santo. Pois o entendimento verdadeiro e espiritual não admitirá nada que desdiga do autor ou do narrador. Aproximou-se, pois, da parede quando se uniu à carne. A carne é a parede, e a aproximação do Esposo é a encarnação do Verbo. E as grades e as janelas por onde se diz que olha, creio que são os sentidos da carne e os afetos humanos, pelos quais fez a experiência de todas as necessidades humanas. Enfim, ele mesmo tomou as nossas enfermidades e carregou as nossas dores (Is 53,4). Usou, pois, dos afetos humanos e dos sentidos corporais como de aberturas e janelas, para que, feito homem, conhecesse por experiência as misérias dos homens e se tornasse misericordioso. Já as conhecia antes, mas de outro modo. Conhecia, enfim, a virtude da obediência ele, o Senhor das virtudes; e, no entanto, como atesta o Apóstolo, aprendeu a obediência por aquilo que sofreu (Hb 5,8). Deste modo aprendeu também a misericórdia, embora a misericórdia do Senhor seja desde sempre (cf. Sl 102,17). Ensina-o também o mesmo Doutor dos gentios, quando afirma que ele foi provado em tudo à nossa semelhança, exceto no pecado, para se tornar misericordioso (cf. Hb 4,15; 2,17). Vês que se tornou o que era, que aprendeu o que sabia, e que procurou para si entre nós frestas e janelas por onde explorasse com mais cuidado as nossas calamidades? E encontrou na nossa parede arruinada e cheia de frestas tantas aberturas quantas foram as experiências da nossa fraqueza e corrupção que sentiu no seu corpo.`
    },
    {
      n: 2,
      texto: `Assim, pois, estava o esposo de pé atrás da parede, olhando pelas janelas e pelas grades. E bem se diz de pé, porque só ele esteve verdadeiramente de pé na carne, ele que não sentiu o pecado da carne. Podemos também entender com fé que esteve de pé pelo poder da divindade aquele que caiu pela fraqueza da carne, como ele mesmo diz: O espírito está pronto, mas a carne é fraca (Mt 26,41). E julgo que também apoia esta sentença aquilo que o santo Davi, como profeta do Senhor e profetizando, dizia do Senhor neste mistério — falando, sem dúvida, de Moisés, mas tendo em vista o Senhor. Pois ele é o verdadeiro Moisés, que veio verdadeiramente pela água, e não só na água, mas na água e no sangue (cf. 1Jo 5,6). Diz, pois, o profeta mencionado: Falou em exterminá-los — referindo-se ao Pai —, se Moisés, o seu escolhido, não se tivesse mantido de pé na quebra, diante dele, para desviar a sua ira, para que não os exterminasse (Sl 105,23). De que modo, pergunto, ficou Moisés de pé na quebra? Como, digo, ficou de pé, se foi quebrado; ou, se ficou de pé, como foi quebrado? Mas eu te mostro, se queres, quem verdadeiramente ficou de pé na quebra. Não conheço outro que o tenha podido, senão o meu Senhor Jesus, que vivia na própria morte; que, quebrado no corpo na cruz, estava de pé com o Pai pela divindade: numa natureza, suplicando conosco; na outra, perdoando com o Pai. E estava de pé atrás da parede, porque o que nele jazia estava manifesto na carne, e aquilo por que estava de pé escondia-se como que atrás da carne; um só e o mesmo, homem manifesto e Deus escondido.`
    },
    {
      n: 3,
      texto: `Mas também para cada um de nós, que desejamos a sua vinda, julgo que ele está igualmente de pé atrás da parede, enquanto este nosso corpo, que é certamente corpo de pecado (cf. Rm 6,6), nos esconde por ora a sua face e nos fecha a sua presença. Enfim: Enquanto estamos neste corpo, diz, vivemos exilados longe do Senhor (2Cor 5,6). Não por estarmos no corpo, mas por estarmos neste corpo, que vem do pecado e não existe sem pecado. E, para que saibas que o obstáculo não são os corpos, mas os pecados, ouve a Escritura: Os nossos pecados, diz, fazem separação entre nós e Deus (Is 59,2). E oxalá só me estorvasse a parede do corpo, e só tivesse por obstáculo o pecado que há na carne, e não se interpusessem muitos muros de vícios! Pois temo que, além do que está na natureza, eu tenha acrescentado muitíssimos obstáculos da minha própria iniquidade, com cuja interposição afastei demasiado de mim o Esposo; de modo que, se quiser dizer a verdade, devo confessar que ele está para mim atrás de paredes, e não atrás de uma parede.`
    },
    {
      n: 4,
      texto: `Mas digo isto com mais clareza. O Esposo está presente em toda parte, igualmente e sem diferença, pela presença da majestade divina e pela grandeza do seu poder. Mas, pela concessão ou pela retenção da graça, diz-se que está longe de uns e perto de outros — entenda-se, dos anjos e dos homens, isto é, das criaturas racionais. Enfim, a salvação está longe dos pecadores (Sl 118,155). E o santo Davi também diz: Por que, Senhor, te afastaste para longe (Sl 9,22)? Mas dos santos, por uma disposição piedosa, afasta-se às vezes por um tempo, e não de todo, mas só em parte. Dos pecadores, porém, de quem se diz: A soberba dos que te odeiam sobe sempre (Sl 73,23); e ainda: Os seus caminhos estão manchados em todo tempo (cf. Sl 9,26), está sempre, e muito longe, e isto na ira, e não na misericórdia. Por isso o santo ora a Deus e diz: Não te desvies na tua ira do teu servo (Sl 26,9), sabendo que também poderia desviar-se na misericórdia. O Senhor está, pois, perto dos seus santos e eleitos, mesmo quando parece estar longe; e não igualmente de todos, mas de uns mais, de outros menos, conforme a diversidade dos méritos. Pois, embora o Senhor esteja perto de todos os que o invocam com verdade (cf. Sl 144,18), e junto dos que têm o coração atribulado (cf. Sl 33,19), talvez não esteja tão perto de todos que possam dizer: Ele está de pé atrás da parede. Mas quão perto está da esposa aquele de quem ela está separada só por uma parede! Por isso ela deseja partir (cf. Fl 1,23) e, rompida a parede do meio (cf. Ef 2,14), estar com aquele que confia estar atrás da parede.`
    },
    {
      n: 5,
      texto: `Eu, porém, como sou pecador, não desejo partir, mas temo, sabendo que a morte dos pecadores é péssima (Sl 33,22). Como não será péssima a morte, onde a Vida não socorre? Tenho medo de sair, e estremeço à própria entrada do porto, porque não confio que esteja perto quem receba o que sai. Pois quê? Sairei seguro, se o Senhor não guardar a minha saída (cf. Sl 120,8)? Ai! Serei joguete dos demônios que me apanharão, sem ninguém ao lado que me resgate nem que me salve (cf. Sl 7,3). Nada disto tinha de temer a alma de Paulo, a quem uma só parede separava da vista e do abraço do Amado: a lei do pecado que encontrava nos seus membros (cf. Rm 7,23). Esta é a concupiscência da carne, de que não pôde de modo nenhum livrar-se enquanto esteve na carne. Com esta única parede interposta, não estava exilado longe do Senhor; por isso também desejava, clamando: Quem me livrará deste corpo de morte (Rm 7,24)? — sabendo que, pelo atalho da morte, chegaria logo à vida. Paulo confessava, pois, estar preso só por esta lei, a concupiscência, que suportava contra a vontade, cravada inamovivelmente na sua carne; quanto ao resto: A consciência, diz, de nada me acusa (1Cor 4,4).`
    },
    {
      n: 6,
      texto: `Mas quem é semelhante a Paulo, que não consinta às vezes nesta concupiscência, até obedecer ao pecado? Saiba, pois, quem consentiu no pecado que se pôs também uma segunda parede: o próprio consentimento, mau e ilícito; e quem é assim não pode gloriar-se de que o Esposo esteja para ele atrás da parede, pois já se interpõem paredes, e não uma parede. Muito menos se o consentimento chegar à obra, porque então uma terceira parede afasta e impede o acesso do esposo: o próprio ato do pecado. E se o costume fizer do pecado hábito, ou o hábito o levar até o desprezo? Como está escrito: O ímpio, quando chega ao fundo dos males, despreza tudo (Pr 18,3). Se saíres assim, não poderás ser devorado mil vezes pelos que rugem, prontos para a presa (cf. Eclo 51,4), antes de chegares ao Esposo, separado de ti já não por uma, mas por tão grande número de paredes? A primeira é a concupiscência; a segunda, o consentimento; a terceira, o ato; a quarta, o costume; a quinta, o desprezo. Cuida, pois, de resistir com todas as forças à primeira, a concupiscência, para que não te arraste ao consentimento; e toda a construção da maldade que viria depois se desvanece; e já não haverá nada que impeça o Esposo de se aproximar de ti, senão só a parede do corpo, de modo que também tu possas gloriar-te, dizendo dele: Eis que ele está de pé atrás da parede.`
    },
    {
      n: 7,
      texto: `Mas deves cuidar também, com toda a vigilância, de que ele encontre sempre abertas as janelas e umas grades das tuas confissões, pelas quais te olhe por dentro com benignidade; pois o seu olhar é o teu progresso. Dizem que as grades são janelas mais estreitas, como as que os que copiam livros costumam arranjar para receber luz sobre as páginas. Daí, creio, se chamam chanceleres os que por ofício estão encarregados de redigir documentos. Como há, pois, dois gêneros de compunção — um na tristeza pelas nossas faltas, outro na exultação pelos dons divinos —, todas as vezes que faço aquela confissão que não se faz sem aperto do coração, isto é, a dos meus pecados, parece-me que abro uma grade, isto é, uma janela mais estreita. E não há dúvida de que olha de bom grado por ela aquele piedoso observador que está de pé atrás da parede, porque Deus não desprezará um coração contrito e humilhado (Sl 50,19). Enfim, ele mesmo exorta a isto, dizendo: Dize primeiro as tuas iniquidades, para seres justificado (Is 43,26). E, se às vezes, com o coração dilatado pela caridade, ao considerar a bondade e a misericórdia divinas, me apetece soltar o ânimo em voz de louvor e ação de graças, penso que abro ao Esposo, que está de pé atrás da parede, já não uma janela estreita, mas amplíssima, pela qual, se não me engano, olha com tanto mais gosto quanto mais o honra o sacrifício de louvor (cf. Sl 49,23). Estaria à mão provar pelas Escrituras uma e outra confissão; mas falo a quem sabe, e não deveis ser sobrecarregados com o supérfluo, vós que mal bastais para investigar o necessário. Pois tantos são os mistérios deste epitalâmio e os louvores que nele se cantam à Igreja e ao seu esposo, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
