SERMOES.sermao({
  id: 'bernardo-cantico-37',
  colecao: 'bernardo-cantico',
  ordem: 37,
  numero: 'XXXVII',
  titulo: 'Do duplo conhecimento e da dupla ignorância, e dos males que produzem',
  fonte: 'De duplici notitia, et duplici ignorantia',
  argumento: `Bernardo retoma o fio interrompido pelos que cochilavam: sem o conhecimento de si não há humildade nem temor de Deus; sem o conhecimento de Deus não há amor. O saber das letras vem depois, como uma pintura, que precisa de parede firme. Oseias já dava a ordem: semeai na justiça, colhei a esperança da vida, e só então acendei a luz da ciência. Quem semeia entre lágrimas colhe já nesta vida a esperança, e a esperança é ela mesma alegria.

Depois, o reverso: as duas ignorâncias. A ignorância de si gera a soberba, princípio de todo pecado; a ignorância de Deus gera o desespero, a sua consumação. Soberba é ser maior aos próprios olhos do que se é na verdade. Não há perigo em rebaixar-se demais, como não há perigo em curvar-se muito ao passar por uma porta baixa; o perigo é erguer-se um dedo acima da medida. Por isso ninguém se deve comparar a ninguém, nem mesmo ao pior dos criminosos, que talvez a mão de Deus fará melhor que nós.

Tradução feita do texto latino de Migne (PL 183, 971-974).`,
  pontos: [
    {
      n: 1,
      texto: `Creio que não precisamos agora exortar-vos a ficar acordados, pois sem dúvida está bem acordada aquela palavra de censura, ainda recente, que ontem pronunciamos com caridade e que despertou bem alguns. Guardais, pois, na memória que tenho o vosso assentimento: ninguém se salva sem o conhecimento de si mesmo. É dele que nasce a humildade, mãe da salvação, e o temor do Senhor, que, assim como é o princípio da sabedoria, é também o da salvação. Ninguém, digo, se salva sem aquele conhecimento — entenda-se, quem tem idade e capacidade de conhecer. Digo isto por causa das criancinhas e dos que não têm uso da razão, com os quais o caso é outro. E se ignoras a Deus? Poderá haver esperança de salvação com a ignorância de Deus? Também não. Pois não podes nem amar a quem não conheces, nem possuir a quem não amaste. Conhece-te, pois, para temeres a Deus; conhece-o a ele, para igualmente o amares. Por um conhecimento és iniciado na sabedoria, pelo outro és nela consumado; porque o princípio da sabedoria é o temor do Senhor (Sl 110,10), e a plenitude da lei é a caridade (Rm 13,10). Deves, pois, guardar-te de uma e outra ignorância, tanto quanto é certo que sem o temor e o amor de Deus não pode haver salvação. As outras coisas são indiferentes: não trazem a salvação se as sabemos, nem a condenação se não as sabemos.`
    },
    {
      n: 2,
      texto: `Não digo, contudo, que se deva desprezar ou descuidar o saber das letras, que orna a alma, a instrui e a torna capaz de instruir também os outros. Mas convém e é proveitoso que venham antes aquelas duas coisas nas quais, como mostrou o raciocínio anterior, consiste o essencial da salvação. E vê se não tinha diante dos olhos, e não ensinava, esta ordem aquele que dizia: Semeai para vós na justiça, colhei a esperança da vida; e só então, diz, acendei para vós a luz da ciência (Os 10,12). Pôs a ciência em último lugar, como uma pintura, que não se pode sustentar sobre o vazio; e por isso pôs antes aquelas duas coisas e colocou-as por baixo dela, como quem põe alguma coisa sólida por baixo de uma pintura. Posso aplicar-me tranquilo à ciência, se antes tiver recebido, pelo benefício da esperança, a segurança da vida. Tu, pois, semeaste para ti na justiça se, a partir do verdadeiro conhecimento de ti, despertaste para temer a Deus, te humilhaste, derramaste lágrimas, distribuíste esmolas com largueza e te entregaste às demais obras de piedade; se afligiste o corpo com jejuns e vigílias, se cansaste o peito de golpes e os céus de clamores. Pois isto é semear na justiça. As sementes são as boas obras, os bons empenhos; as lágrimas são sementes. Iam, diz, e choravam, lançando as suas sementes. Mas quê? Chorarão sempre? De modo nenhum! Mas virão com exultação, trazendo os seus feixes (Sl 125,6). Com razão com exultação, pois trazem de volta feixes de glória. Isso, dizes, será na ressurreição, no último dia, e a espera é demasiado longa. Não desanimes, não desfaleças por pusilanimidade de espírito (cf. Sl 54,9); tens entretanto, das primícias do Espírito (cf. Rm 8,23), o que colher desde já com exultação. Semeai para vós, diz, na justiça, colhei a esperança da vida. Não te remete agora ao último dia, quando a coisa estará já na realidade, e não na esperança; fala do presente. Sem dúvida, grande será a alegria e imensa a exultação, quando vier a vida.`
    },
    {
      n: 3,
      texto: `Mas acaso a esperança de tamanha alegria ficará sem alegria? Alegres na esperança, diz o Apóstolo (Rm 12,12). E Davi não disse que se alegraria, mas que se alegrou, porque esperava ir à casa do Senhor (Sl 121,1). Ainda não possuía a vida, mas já tinha colhido a esperança da vida; e experimentava em si a verdade da Escritura, que atesta que não só a recompensa, mas também a própria espera dos justos é alegria (Pr 10,28). Esta alegria, no ânimo de quem semeou para si na justiça, nasce da confiança no perdão dos pecados — contanto que esse perdão seja atestado pela eficácia da graça recebida para viver daí em diante com mais santidade. Todo aquele dentre vós que sente estas coisas acontecerem dentro de si sabe o que diz o Espírito, cuja voz e cuja ação nunca discordam entre si. Entende, pois, o que se diz, porque sente por dentro o que ouve por fora. Pois o mesmo e único Espírito que fala em nós opera em vós, distribuindo a cada um como quer (1Cor 12,11): a uns o falar, a outros o fazer o que é bom.`
    },
    {
      n: 4,
      texto: `Quem de vós, pois, se alegra por ter respirado na esperança, depois daqueles começos amargos e chorosos da sua conversão, e por ter voado, levantado pelas asas da graça, para uma espécie de céu sereno da consolação do alto — esse já colhe, sem dúvida, recebendo o fruto temporão das suas lágrimas; e ele viu a Deus, e ouviu a voz que diz: Dai-lhe do fruto das suas mãos (Pr 31,31). Pois como não viu a Deus quem provou e viu como o Senhor é suave (Sl 33,9)? Quão doce e suave te sentiu, Senhor Jesus, aquele a quem não só perdoaste os pecados, mas concedeste também o dom da santidade; e não só isto, mas acrescentaste ainda, para cúmulo dos bens, a promessa da vida eterna! Feliz quem já colheu tanto, tendo entretanto o seu fruto para a santificação, e por fim a vida eterna (Rm 6,22)! Com razão, quem chorou ao encontrar-se a si mesmo alegrou-se ao ver o Senhor (cf. Jo 20,20), e, pondo os olhos na sua misericórdia, já recolheu tantos feixes: o perdão, a santificação, a esperança da vida. Ó quão verdadeira é a palavra que se lê no Profeta: Os que semeiam entre lágrimas colherão com exultação (Sl 125,5)! Nela se resumem brevemente os dois conhecimentos: o de nós mesmos, que semeia entre lágrimas; e o de Deus, que colhe na alegria.`
    },
    {
      n: 5,
      texto: `Indo, pois, à frente em vós este duplo conhecimento, a ciência que porventura crescer por cima dele já não incha, pois nada pode trazer de vantagem ou de honra terrena que não seja inferior à esperança concebida e à alegria da esperança, já mais profundamente enraizada no ânimo. E a esperança não confunde, porque o amor de Deus foi derramado nos nossos corações pelo Espírito Santo que nos foi dado (Rm 5,5). Aquela não confunde porque este infunde a certeza. Pois por ele o próprio Espírito dá testemunho ao nosso espírito de que somos filhos de Deus (Rm 8,16). Que nos poderia vir, pois, da nossa ciência, por maior que seja, que não fosse menor do que esta glória de sermos contados entre os filhos de Deus? Disse pouco: em comparação com ela, nem merece um olhar o próprio mundo com tudo o que o enche (cf. Sl 23,1), ainda que fosse dado inteiro em posse a cada um de nós. Mas, se nos domina a ignorância de Deus, como esperaremos naquele que ignoramos? Se a de nós mesmos, como seremos humildes, julgando ser alguma coisa, quando nada somos (cf. Gl 6,3)? E sabemos que nem os soberbos nem os desesperados têm parte ou companhia na herança dos santos (cf. Cl 1,12).`
    },
    {
      n: 6,
      texto: `Considera, pois, agora comigo com quanto cuidado e solicitude devemos afastar de nós estas duas ignorâncias, das quais uma gera o princípio de todo pecado, e a outra a sua consumação; assim como, dos dois conhecimentos que lhes correspondem, um gera o princípio da sabedoria e o outro a sua perfeição: aquele, o temor do Senhor; este, a caridade. Mas isto, quanto aos conhecimentos, já foi mostrado acima. Vê agora quanto às ignorâncias. Pois, assim como o princípio da sabedoria é o temor do Senhor (Eclo 1,16), assim o princípio de todo pecado é a soberba (Eclo 10,15); e, como o amor de Deus reivindica para si a perfeição da sabedoria, assim o desespero reivindica para si toda a consumação da maldade. E, assim como do conhecimento de ti vem em ti o temor de Deus, e do conhecimento de Deus, igualmente, o amor de Deus, assim, ao contrário, da ignorância de ti vem a soberba, e da ignorância de Deus vem o desespero. E a ignorância de ti gera em ti a soberba quando o teu pensamento, enganado e enganador, te diz mentirosamente que és melhor do que és. Pois isto é a soberba, isto é o princípio de todo pecado: seres maior aos teus olhos do que és diante de Deus, do que és na verdade. E por isso daquele que primeiro cometeu este grande pecado — falo do diabo — se disse que não permaneceu na verdade, mas é mentiroso desde o princípio (Jo 8,44); porque o que estava no seu pensamento não estava na verdade. E se ele se tivesse afastado da verdade no sentido de se julgar menor e inferior ao que a verdade o tinha? Sem dúvida a sua ignorância o desculparia, e de modo algum seria tido por soberbo; e a sua iniquidade não seria achada digna de ódio (cf. Sl 35,3), mas talvez a sua humildade, digna de graça. Pois, se conhecêssemos com clareza em que estado Deus tem cada um de nós, não deveríamos afastar-nos nem para cima nem para baixo, conformando-nos em tudo à verdade. Mas agora, porque este desígnio fez das trevas o seu esconderijo (cf. Sl 17,12), e a palavra está escondida para nós (cf. Lc 18,34), de modo que ninguém sabe se é digno de amor ou de ódio (Ecl 9,1), é sem dúvida mais justo e mais seguro, segundo o conselho da própria Verdade, escolhermos o último lugar, de onde depois sejamos levados com honra mais para cima, do que presumirmos um lugar mais alto, de onde logo tenhamos de sair envergonhados (Lc 14,9-10).`
    },
    {
      n: 7,
      texto: `Não há, pois, perigo nenhum, por mais que te humilhes, por mais que te julgues menor do que és, isto é, do que a verdade te tem. Mas é um grande mal e um perigo horrendo que te eleves, ainda que pouco, acima do verdadeiro; que te prefiras no teu pensamento, ainda que a um só, a quem talvez a verdade julgue igual a ti, ou mesmo superior. Pois, se passas por uma porta cuja verga é — para usar a palavra de todos os dias — baixa demais, não te faz mal nenhum inclinar-te quanto quiseres; mas faz mal se te endireitares, ainda que só a largura de um dedo, mais do que a medida da porta permite, de modo que batas e fiques com a cabeça machucada. Assim, na alma, não se deve temer nenhuma humilhação, por maior que seja; mas deve-se ter horror e grande medo de qualquer elevação, por mínima que seja, presumida temerariamente. Por isso, ó homem, não te compares nem aos maiores, nem aos menores, nem a alguns, nem a um só. Pois que sabes tu, ó homem, daquele único que talvez tens pelo mais vil e mais miserável de todos, cuja vida criminosíssima e singularmente torpe te causa horror, e que por isso julgas desprezível não só em comparação contigo — que talvez já confias viver com sobriedade, justiça e piedade (cf. Tt 2,12) —, mas também em comparação com todos os outros criminosos, como o mais criminoso de todos? Que sabes tu, digo, se ele, pela mudança que opera a destra do Altíssimo (Sl 76,11), não virá a ser em si mesmo melhor que tu e que eles, e se já não o é em Deus? E por isso não quis que escolhêssemos um lugar mediano, nem o penúltimo, nem sequer um entre os últimos; mas: Senta-te, diz, no último lugar (Lc 14,10) — para que te sentes sozinho, o último de todos, e não te atrevas, não digo a preferir-te a ninguém, mas nem sequer a comparar-te. Eis quão grande mal vem da ignorância de nós mesmos: o pecado do diabo, o princípio de todo pecado, a soberba. O que gera a ignorância de Deus, veremos em outra ocasião, pois agora a brevidade da hora não o permite, porque hoje nos reunimos tarde. Baste, pois, por agora, que cada um tenha sido advertido a não ignorar a si mesmo, não só pelo nosso sermão, mas também pela bondade do próprio esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
