SERMOES.sermao({
  id: 'bernardo-cantico-23',
  colecao: 'bernardo-cantico',
  ordem: 23,
  numero: 'XXIII',
  titulo: 'Dos três modos de contemplar a Deus, sob a figura de três câmaras',
  fonte: 'De tribus modis contemplationis circa Deum, sub figura trium cellarum',
  argumento: `O sermão mais arquitetado do livro. Bernardo toma três lugares do Cântico — o horto, as despensas e o quarto — e faz deles os três sentidos da Escritura: a história, a moral e a contemplação.

No horto, três tempos: criação, reconciliação, restauração. Nas despensas, três câmaras — a da disciplina, a da natureza e a da graça —, que são estar sujeito, conviver e governar. E no quarto, três lugares de contemplação, de que ele fala em primeira pessoa: aquele de onde Deus governa o mundo, que não deixa descansar; o do juízo secreto sobre os reprovados, lugar terrível e sem nenhum descanso; e o terceiro, o único em paz, onde Deus aparece sereno e sossegado, suave e manso.

No ponto 2 está a página aos superiores: sede mães, não senhores.

Tradução feita do texto latino de Migne (PL 183, 884-894).`,
  pontos: [
    {
      n: 1,
      texto: `Introduziu-me o rei nas suas despensas. Eis de onde vem o odor, eis para onde se corre. Tinha dito que era preciso correr, e em quê se devia correr; mas não tinha dito para onde. Corre-se, pois, para as despensas, e corre-se ao odor que delas sai; a esposa pressente-o com a sua costumeira perspicácia e deseja ser introduzida na plenitude dele. Mas que devemos entender por estas despensas? Pensemos, por ora, em certos lugares perfumados que o esposo tem, cheios de aromas e abarrotados de delícias: é numa casa dessas que se guarda o que há de melhor no horto e no campo. É para lá, pois, que correm juntas. Quem? As almas fervorosas no espírito. Corre a esposa, correm as jovenzinhas; mas quem ama com mais ardor corre mais depressa e chega primeiro. E, ao chegar, não sofre recusa — nem sequer demora: abre-se-lhe sem tardança, como a quem é da casa, como a quem é caríssima, especialmente amada e singularmente querida. E as jovenzinhas? Seguem de longe. Sendo ainda fracas, não conseguem correr com a mesma devoção que a esposa nem imitar de todo o desejo e o fervor dela; e por isso, chegando mais tarde, ficam de fora. Mas a caridade da esposa não descansa nem se ensoberbece com os próprios êxitos, como costuma acontecer, a ponto de se esquecer delas; antes as consola e as exorta à paciência, para que suportem com calma a recusa que lhes fizeram e a ausência dela. E anuncia-lhes a alegria que recebeu, não por outra razão senão para que se alegrem com ela, confiando em que não lhes será alheia nenhuma graça que venha à mãe. Pois ela não cuida de progredir de modo a descuidar delas, nem julga que os seus progressos se ajudem com o prejuízo delas. Por mais alto que a prerrogativa dos méritos a leve para longe delas, é forçoso que pela caridade e por um cuidado amoroso esteja sempre com elas. Deve, enfim, imitar o seu esposo, que sobe aos céus e ao mesmo tempo promete estar na terra com os seus até o fim dos tempos (Mt 28,20). Assim também ela: por mais que avance, por mais alto que seja levada, nunca se afasta, pelo cuidado, pela providência e pelo afeto, daquelas que gerou no Evangelho; nunca se esquece das suas entranhas.`
    },
    {
      n: 2,
      texto: `Diga-lhes, pois: Alegrai-vos, confiai. Introduziu-me o rei nas suas despensas: julgai-vos igualmente introduzidas. Pareço ter sido introduzida sozinha, mas não aproveitará a uma só. Todo o meu progresso é de todas vós: progrido para vós, e repartirei convosco tudo o que porventura merecer a mais do que vós. Queres saber sem sombra de dúvida que foi neste sentido e com este afeto que ela falou? Ouve o que elas respondem. Exultaremos e nos alegraremos em ti. Em ti, dizem, exultaremos e nos alegraremos; pois em nós ainda não o merecemos. E acrescentam: Lembradas dos teus peitos — isto é: esperamos com calma até que venhas, sabendo que hás de voltar a nós de peitos cheios. Confiamos que então exultaremos e nos alegraremos, lembradas entretanto dos teus peitos. E, ao acrescentarem mais que o vinho (Ct 1,3), dão a entender que, pela sua imperfeição, ainda são batidas pela lembrança dos desejos da carne, que o vinho significa; mas que esses mesmos desejos são vencidos pela memória da abundante suavidade que já experimentaram correr dos peitos. Falaria dos peitos, se não me lembrasse de já ter dito bastante sobre eles. Vês agora com que confiança tratam a mãe, como tomam por seus os ganhos e as alegrias dela, consolando-se do agravo da própria recusa com a entrada dela. Não confiariam assim, se não a reconhecessem como mãe. Ouçam isto os superiores, que sempre querem meter medo aos que lhes foram confiados, e raramente ser-lhes úteis. Instruí-vos, vós que julgais a terra (Sl 2,10). Aprendei que deveis ser mães dos vossos súditos, não senhores; empenhai-vos mais em ser amados do que temidos; e, se às vezes é preciso severidade, seja de pai, não de tirano. Mostrai-vos mães no acariciar e pais no corrigir. Amansai-vos, deixai a rudeza; suspendei os açoites, oferecei os peitos; que os peitos se encham de leite, e não inchem de arrogância. Por que pesais o vosso jugo sobre aqueles cujos fardos antes devíeis carregar? Por que o pequenino mordido pela serpente foge da consciência do sacerdote, quando antes devia correr para ele como para o regaço de uma mãe? Se sois espirituais, corrigi um assim com espírito de mansidão, olhando cada um para si mesmo, para que também não seja tentado (Gl 6,1). De outro modo ele morrerá no seu pecado; e o seu sangue, diz o Senhor, eu o pedirei da tua mão (Ez 3,20). Mas disto em outra ocasião.`
    },
    {
      n: 3,
      texto: `Agora que o encadeamento do texto ficou claro pelo que dissemos, vejamos o que devemos entender espiritualmente a respeito das despensas. Mais adiante fala-se também de um horto e de um quarto; junto ambos agora a estas despensas e trago-os para esta discussão, pois, tratados juntos, cada um se entenderá melhor pelos outros. E busquemos, se vos parece, estas três coisas nas santas Escrituras: o horto, a despensa e o quarto. É neles que de bom grado se ocupa e se demora a alma que tem sede de Deus, sabendo que ali há de encontrar, sem dúvida, aquele de quem tem sede. Seja, pois, o horto a história simples e plana; seja a despensa o sentido moral; seja o quarto o segredo da contemplação.`
    },
    {
      n: 4,
      texto: `E, primeiro, não me parece sem razão atribuir a história ao horto, porque nela se encontram homens de virtude como árvores frutíferas no horto do esposo e no paraíso de Deus: tantos frutos colhes quantos exemplos tiras das suas boas obras e dos seus costumes. Duvidará alguém de que um homem bom é plantação de Deus? Ouve o que canta o santo Davi a respeito do homem bom: Será como a árvore plantada junto às correntes das águas, que dará o seu fruto no tempo certo, e cuja folha não cairá (Sl 1,3). Ouve Jeremias cantar no mesmo espírito e quase nas mesmas palavras: Será como a árvore plantada junto às correntes das águas, que lança as raízes para a umidade e não temerá quando vier o calor (Jr 17,8). E ainda o Profeta: O justo florescerá como a palmeira, e há de crescer como o cedro do Líbano (Sl 91,13). E de si mesmo: Eu, porém, sou como oliveira frutífera na casa de Deus (Sl 51,10). A história é, pois, um horto, e ela mesma se divide em três: nela se contêm a criação do céu e da terra, a reconciliação e a restauração. A criação, como a semeadura ou a plantação do horto. A reconciliação, como o germinar do que foi semeado ou plantado; pois, no tempo devido, orvalhando os céus lá do alto e chovendo as nuvens o justo, abriu-se a terra e germinou o Salvador (Is 45,8), por quem se fez a reconciliação do céu e da terra. Ele é a nossa paz, que fez dos dois um só (Ef 2,14), pacificando com o seu sangue as coisas da terra e as do céu (Cl 1,20). E a restauração há de ser no fim dos tempos: haverá um céu novo e uma terra nova, e os bons serão recolhidos do meio dos maus como frutos de um horto, para serem guardados nas despensas de Deus. Naquele dia, como está escrito, o germe do Senhor será magnificência e glória, e o fruto da terra será sublime (Is 4,2). Tens, pois, três tempos no horto do sentido histórico.`
    },
    {
      n: 5,
      texto: `Também na doutrina moral se podem notar três coisas: como que três câmaras numa só despensa. E talvez por isso ela tenha dito despensas no plural, e não despensa, pensando neste número de câmaras. Mais adiante, enfim, gloria-se de ter sido introduzida na adega (Ct 2,4). Nós, pois — já que lemos: Dá ocasião ao sábio, e ele será mais sábio (Pr 9,9) —, tomando ocasião do nome que o Espírito Santo quis dar a esta câmara, ponhamos nome também às outras duas: a uma, dos aromas; à outra, dos perfumes. As razões destes nomes veremos depois. Por agora repara que tudo o que se acha junto do esposo é saudável e suave: vinho, perfumes, aromas. O vinho, segundo a Escritura, alegra o coração do homem (Sl 103,15); e lês também que o óleo alegra o rosto — óleo no qual se derrama o pó dos perfumistas, para que se façam os perfumes. E os aromas não são úteis só pela suavidade agradável do odor, mas também pela força de curar. Com razão a esposa exulta por ter sido introduzida ali, onde transborda tão grande abundância de graça.`
    },
    {
      n: 6,
      texto: `Mas tenho ainda outros nomes, e creio que de razão mais evidente. E, para os dar em ordem, chamaria à primeira câmara a da disciplina; à segunda, a da natureza; à última, a da graça. Na primeira aprendes, segundo a parte moral, a ser inferior; na segunda, igual; na terceira, superior — isto é: sob outro, com outro, sobre outro; ou assim: estar sujeito, conviver, governar. Primeiro, pois, aprendes a ser discípulo; depois, companheiro; por fim, mestre. A natureza gerou todos os homens iguais. Mas, uma vez que a soberba estragou nos costumes aquele bem da natureza, os homens tornaram-se incapazes de suportar a igualdade: disputam entre si quem há de ficar por cima, desejam ultrapassar-se uns aos outros e, ávidos de vanglória, invejam-se e provocam-se mutuamente. Por isso, antes de tudo, na primeira câmara há que domar com o jugo da disciplina a insolência dos costumes, até que a vontade teimosa, gasta por leis duras e longas dos mais velhos, se humilhe e se cure, e receba pela obediência o bem da natureza que perdera pela soberba. E, quando já por simples afeto natural — e não por medo da disciplina — tiver aprendido a portar-se, quanto está nela, de modo sociável e tranquilo com todos os companheiros da sua natureza, isto é, com todos os homens, passe enfim à câmara da natureza e experimente o que está escrito: Como é bom e como é agradável habitarem os irmãos juntos! É como o perfume na cabeça (Sl 132,1-2). Aos costumes já disciplinados, como a ingredientes triturados, junta-se o óleo da alegria, que é o bem da natureza; e faz-se um perfume bom e agradável. Ungido com ele, o homem torna-se suave e manso, homem de quem ninguém se queixa: não engana ninguém, não maltrata ninguém, não fere ninguém, não se levanta nem se prefere a ninguém; e ainda reparte de bom grado, no dar e no receber.`
    },
    {
      n: 7,
      texto: `Creio que, se entendeste bem as propriedades de uma e de outra câmara, hás de testemunhar que não foi sem cabimento chamar a esta a dos perfumes e àquela a dos aromas. Pois naquela, assim como a pancada violenta do pilão arranca e extrai a força e a fragrância dos ingredientes, assim também a força do magistério e o rigor da disciplina de certo modo tiram e espremem a força natural dos bons costumes. Nesta outra, porém, a mansidão agradável de um afeto voluntário e como que inato corre por si mesma, pronta a servir — tal qual o perfume que está na cabeça e que, ao leve toque do calor, desce e se espalha por tudo. Assim, na câmara da disciplina guardam-se como que ingredientes secos e simples de aromas, e por isso julguei que se devia chamar a dos aromas. E naquela a que chamamos da natureza, porque já se guardam perfumes como que prontos, também o nome lhe veio da coisa: chama-se a dos perfumes. E creio que a adega não tem outra razão para o seu nome senão esta: que nela se guarda o vinho de um zelo fervoroso na caridade. E de modo nenhum deve governar os outros quem ainda não mereceu ser nela introduzido. É preciso que arda com este vinho quem preside aos outros, como ardia o Doutor das Nações quando dizia: Quem desfalece, que eu não desfaleça? Quem se escandaliza, que eu não queime? (2Cor 11,29) De outro modo, é grande desonestidade quereres presidir a quem não cuidas de aproveitar, e reclamares para ti, com ambição demasiada, a sujeição daqueles por cuja salvação não zelas. A esta câmara chamei também a da graça — não porque alguém possa alcançar as outras duas sem graça, mas pela plenitude que só nesta se recebe. Pois a caridade é a plenitude da lei; e quem ama o irmão cumpriu a lei (Rm 13,10.8).`
    },
    {
      n: 8,
      texto: `Viste a razão dos nomes; vê agora a diferença entre as câmaras. Não é a mesma facilidade, nem a mesma capacidade, reprimir os sentidos desavergonhados e vagabundos e o apetite desregrado da carne pelo medo do mestre e pela censura rígida da disciplina, e entender-se bem com os companheiros por afeto espontâneo; viver com costumes corrigidos debaixo da férula, e ser agradável aos iguais tendo por única mestra a vontade. E ninguém diga tampouco que é o mesmo mérito, ou a mesma virtude, viver bem em sociedade e presidir com proveito. Quantos vivem tranquilos sob um superior, mas, se os soltares do jugo, verás que não conseguem sossegar nem manter-se de modo algum inofensivos para com os seus iguais! E verás também inúmeros que se portam com simplicidade e sem dar queixa entre os irmãos, e que, postos acima dos irmãos, o fazem não só sem proveito, mas com insensatez e com maldade. Estes contentam-se com uma boa medida mediana, tal como Deus lhes repartiu a medida da graça: já não precisam de mestre, mas ainda não servem para o magistério. Os segundos, pois, superam os primeiros nos costumes; mas acima de uns e de outros estão os que sabem estar acima. Enfim, aos que governam bem se promete que serão postos sobre todos os bens do seu Senhor (Mt 24,47). Mas poucos, de fato, governam com proveito; e menos ainda os que governam com humildade. Cumpre com facilidade as duas coisas, porém, aquele que alcançou perfeitamente o discernimento, mãe das virtudes, e que ao mesmo tempo se embriaga com o vinho da caridade até desprezar a própria glória, até esquecer-se de si e não buscar o que é seu — coisa que só se obtém dentro da adega, pelo magistério admirável do Espírito Santo. Pois a virtude do discernimento, sem o fervor da caridade, fica por terra; e um fervor veemente, sem o tempero do discernimento, precipita. Digno de louvor, portanto, aquele a quem não falta nenhum dos dois: que o fervor levante o discernimento e o discernimento governe o fervor. Assim deve ser o porte de quem governa. E diria que alcançou o melhor nos costumes, e o cume desta disciplina, aquele a quem foi dado percorrer e rodear todas estas câmaras sem tropeço: que em nada resista aos que estão acima, nem inveje os iguais, nem falte aos que lhe estão sujeitos no cuidado, nem os governe com soberba; obediente aos superiores, ajustado aos companheiros, descendo com proveito até os súditos. E esta marca de perfeição eu a concederia sem hesitar à esposa. É o que dá a entender a própria frase que ela disse — Introduziu-me o rei nas suas despensas —, ao mostrar-se introduzida não numa câmara só, mas em despensas, no plural.`
    },
    {
      n: 9,
      texto: `Venhamos agora ao quarto. E que é ele? Presumo eu saber o que seja? Não me atribuo de modo algum a experiência de coisa tão grande, nem me glorio de uma prerrogativa que só se guarda à bem-aventurada esposa; antes sigo com cautela aquilo dos gregos — conhece-te a ti mesmo —, para saber também, com o Profeta, o que me falta (Sl 38,5). Contudo, se nada soubesse, nada diria. O que sei, não vos invejo nem vos sonego; o que não sei, ensine-vos aquele que ensina ciência ao homem (Sl 93,10). Disse — e lembrai-vos — que o quarto do rei se há de buscar no segredo da contemplação. Mas, assim como disse dos perfumes que são muitos e diversos junto do esposo, e que nem todos estão à mão de todos, e sim os seus a cada um, conforme a diversidade dos méritos, assim também julgo que o rei não tem um só quarto, mas vários. Pois não há uma só rainha, mas muitas; e muitas são as concubinas, e as jovenzinhas não têm número (Ct 6,7). E cada uma encontra um segredo só seu com o esposo, e diz: O meu segredo é meu, o meu segredo é meu (Is 24,16). Não é dado a todos gozar num mesmo lugar da presença grata e secreta do esposo, mas conforme a cada um foi preparado pelo Pai dele (Mt 20,23). Pois não fomos nós que o escolhemos: foi ele que nos escolheu e nos pôs (Jo 15,16); e onde cada um foi posto por ele, ali está. Assim, uma mulher compungida recebeu em sorte o lugar junto aos pés do Senhor Jesus (Lc 7,38), enquanto outra achou à cabeça o fruto da sua devoção (Mt 26,7) — se é que era outra. E Tomé no lado, João no peito, Pedro no seio do Pai, Paulo no terceiro céu alcançaram a graça deste segredo.`
    },
    {
      n: 10,
      texto: `Qual de nós seria capaz de distinguir dignamente estas variedades de méritos, ou antes, de prêmios? Para não parecer, contudo, que passamos por cima do que sabemos: a primeira mulher fez o seu leito na segurança da humildade; a segunda, no trono da esperança; Tomé, na firmeza da fé; João, na largueza da caridade; Paulo, no íntimo da sabedoria; Pedro, na luz da verdade. Assim, pois, junto do esposo há muitas moradas (Jo 14,2); e, seja rainha, seja concubina, seja do número das jovenzinhas, cada uma recebe ali o lugar que convém aos seus méritos, e um limite até onde lhe é permitido avançar contemplando, entrar na alegria do seu Senhor e perscrutar os doces segredos do esposo. Isso, no lugar próprio, tentarei mostrar com mais distinção, quanto ele se dignar sugerir-me. Por agora baste saber isto: a nenhuma das jovenzinhas, a nenhuma das concubinas, nem sequer a nenhuma das rainhas está aberto o acesso àquele segredo do quarto que o esposo guarda, único, para a sua pomba formosa, a sua única perfeita. Por isso não me indigno de não ser admitido a ele — sobretudo porque me consta que nem a própria esposa chega por ora a todo o segredo que deseja. Tanto que ainda reclama que lhe mostrem onde apascenta o rebanho, onde repousa ao meio-dia (Ct 1,6).`
    },
    {
      n: 11,
      texto: `Mas ouvi até onde cheguei, ou julguei ter chegado; pois não se há de ter por gabolice o que exponho para o vosso proveito. Há um lugar junto do esposo de onde o próprio governador do universo decreta os seus direitos e dispõe os seus desígnios, estabelecendo leis para toda criatura — peso, medida e número. E este lugar é alto e secreto, mas de modo nenhum tranquilo. Pois, ainda que ele, quanto é de si, disponha tudo com suavidade, dispõe; e não deixa descansar o contemplativo que porventura chegue àquele lugar: antes o cansa de modo admirável — ainda que deleitoso —, enquanto ele perscruta e se admira, e o deixa inquieto. As duas coisas a esposa as exprime com beleza mais adiante — o deleite desta contemplação e a inquietação — quando confessa que dorme e que o seu coração vigia (Ct 5,2). Pois no sono de um espanto suavíssimo e de uma admiração serena ela indica sentir descanso; e na vigília, sofrer o cansaço de uma curiosidade inquieta e de um trabalho árduo. Daí o bem-aventurado Jó: Se durmo, digo: Quando me levantarei? E de novo espero a tarde (Jó 7,4). Percebes nestas palavras que a alma santa quer ora afastar-se de uma suavidade que de certo modo lhe pesa, ora buscar de novo esse peso suave? Pois não teria dito «quando me levantarei?», se aquele descanso da sua contemplação lhe agradasse por inteiro; mas, se por inteiro lhe desagradasse, não esperaria de novo a hora do descanso, isto é, a tarde. Não é, portanto, este o lugar do quarto, onde de modo algum se descansa por inteiro.`
    },
    {
      n: 12,
      texto: `Há ainda outro lugar, de onde vigia, imóvel, sobre a criatura racional reprovada, a atenção secretíssima e severíssima de Deus, juiz justo, terrível nos seus desígnios sobre os filhos dos homens (Sl 65,5). Neste lugar, digo, o contemplativo temente a Deus o vê, com juízo justo mas oculto, não apagando os males dos reprovados nem aceitando os seus bens; e ainda endurecendo os corações, para que não se doam, não voltem a si, não se convertam, e ele não os cure (Jo 12,40). E isso não sem uma razão certa e eterna, o que é tanto mais assustador quanto mais imóvel está fixo na eternidade. É muito de temer o que lemos no profeta a respeito destes, quando Deus, falando aos seus anjos, diz: Tenhamos compaixão do ímpio. E, quando eles, receosos, perguntam: Não aprenderá ele então a praticar a justiça? — Não, responde; e dá a razão: Na terra dos santos cometeu iniquidades, e não verá a glória do Senhor (Is 26,10). Temam os clérigos, temam os ministros da Igreja, que nas terras dos santos que possuem cometem tais iniquidades: não se contentam com o sustento que lhes devia bastar e retêm para si, com impiedade e sacrilégio, o supérfluo com que se deviam sustentar os necessitados; e não temem gastar, em serviço da própria soberba e do próprio luxo, o alimento dos pobres — pecando assim com dupla iniquidade, pois roubam o alheio e abusam de coisas sagradas nas suas vaidades e torpezas.`
    },
    {
      n: 13,
      texto: `Quando, pois, se percebe que aquele cujos juízos são um abismo profundo poupa e se compadece de tais homens no presente, para não os poupar na eternidade — quem procuraria descanso neste lugar? Esta visão tem o tremor do juízo, não a segurança do quarto. É um lugar terrível, e sem nenhum descanso (Gn 28,17). Arrepiei-me todo, sempre que fui arrebatado a ele, repassando comigo, a tremer, aquela sentença: Quem sabe se é digno de amor ou de ódio? (Ecl 9,1) E não é de admirar que eu vacile ali — eu, folha levada pelo vento e palha seca (Jó 13,25) —, quando até aquele grande contemplativo confessa que os seus pés quase vacilaram e que os seus passos quase escorregaram. Ele dizia: Invejei os iníquos, ao ver a paz dos pecadores. Por quê? Não estão no trabalho dos homens, diz, nem são açoitados com os homens; por isso a soberba os prendeu (Sl 72,3-6) — para que não se humilhem até a penitência, mas sejam condenados por soberba com o soberbo diabo e com os seus anjos. Pois os que não estão no trabalho dos homens hão de estar no trabalho dos demônios, quando o juiz disser: Ide, malditos, para o fogo eterno, preparado para o diabo e para os seus anjos (Mt 25,41). E, no entanto, também este é lugar de Deus — não outra coisa senão casa de Deus e porta do céu (Gn 28,17). É aqui que se diz temer-se a Deus; aqui é santo e terrível o seu nome, e é como a entrada da glória: o temor do Senhor é o princípio da sabedoria (Sl 110,9-10).`
    },
    {
      n: 14,
      texto: `E não te espante que eu tenha dado o princípio da sabedoria a este lugar, e não ao anterior. Pois ali, como numa sala de aula sua, ouvimos a Sabedoria, mestra que ensina sobre tudo; aqui, nós a recebemos. Ali somos instruídos; aqui somos tocados. A instrução faz doutos; o afeto, sábios. O sol não aquece todos aqueles a quem ilumina; assim também a Sabedoria não acende logo para fazer muitos a quem ensinou o que se deve fazer. Uma coisa é conhecer muitas riquezas, outra possuí-las; e não é o conhecimento que faz rico, mas a posse. Assim também uma coisa é conhecer a Deus, outra temê-lo; e não é o conhecimento que faz o sábio, mas o temor, porque é ele que toca. Chamarás sábio a quem a própria ciência incha? Quem, senão o mais insensato dos homens, chamaria sábios aqueles que, tendo conhecido a Deus, não o glorificaram como Deus nem lhe deram graças? Eu antes penso como o Apóstolo, que declara abertamente insensato o coração deles (Rm 1,21). E com razão o temor do Senhor é o princípio da sabedoria; porque Deus começa a ter sabor para a alma quando a toca para temer, não quando a instrui para saber. Temes a justiça de Deus, temes o seu poder — e Deus justo e poderoso ganha sabor para ti, porque o temor é sabor. E o sabor faz o sábio, como a ciência faz o que sabe e as riquezas fazem o rico. E o primeiro lugar, então? Apenas prepara para a sabedoria: ali és preparado, para aqui seres iniciado. A preparação é o conhecimento das coisas. Mas a este conhecimento segue-se com a maior facilidade o inchaço da presunção, se o temor não o reprimir; e por isso se diz com razão que o temor do Senhor é o princípio da sabedoria, pois é ele o primeiro a opor-se à peste da insensatez. Ali, pois, há uma aproximação à sabedoria; aqui, a entrada. Mas nem aqui nem ali tem o contemplativo descanso perfeito, porque ali Deus aparece como quem está ocupado, e aqui como quem está perturbado. Não procures, portanto, o quarto nestes lugares: um parece antes a sala de aula de quem ensina; o outro, o tribunal de um juiz.`
    },
    {
      n: 15,
      texto: `Mas há um lugar onde Deus se vê verdadeiramente em repouso e tranquilo: lugar que não é de juiz nem de mestre, mas de esposo; e que para mim — dos outros não sei — é sem dúvida o quarto, se alguma vez me acontece ser nele introduzido. Mas, ai! Hora rara, e demora curta! Ali se reconhece com clareza que a misericórdia do Senhor é desde a eternidade e até a eternidade sobre os que o temem (Sl 102,17). E feliz quem pode dizer: Sou companheiro de todos os que te temem e guardam os teus mandamentos (Sl 118,63). Está firme o propósito de Deus, está firme a sentença de paz sobre os que o temem: ele faz vista grossa aos males deles e recompensa os seus bens, de modo que, admiravelmente, não só o bem, mas também o mal concorre para o bem deles. Ó único verdadeiramente feliz, aquele a quem o Senhor não imputa o pecado! (Sl 31,2) Pois quem não tenha pecado, ninguém há: todos pecaram e todos precisam da glória de Deus (Rm 3,23). Quem, porém, acusará os eleitos de Deus? (Rm 8,33) Basta-me, para toda a justiça, ter favorável aquele único contra quem pequei. Tudo o que ele decidir não me imputar é como se não tivesse existido. Não pecar é a justiça de Deus; a justiça do homem é o perdão de Deus. Vi estas coisas e entendi a verdade daquela sentença: Todo o que nasceu de Deus não peca, porque a geração celeste o guarda (1Jo 3,9). A geração celeste é a predestinação eterna, pela qual Deus amou os seus eleitos e os tornou agradáveis no seu Filho amado antes da fundação do mundo — aparecendo-lhe assim no santuário, para verem o seu poder e a sua glória, a fim de serem participantes da herança daquele de cuja imagem se mostrariam conformes. Notei, pois, que estes são como se nunca tivessem pecado: porque, ainda que pareçam ter faltado em alguma coisa no tempo, isso não aparece na eternidade, pois a caridade do Pai deles cobre a multidão dos pecados. E chamou felizes aqueles cujas iniquidades foram perdoadas e cujos pecados foram cobertos (Sl 31,1); e de repente brotou também em mim, a meu respeito, uma confiança tão grande, e infundiu-se em mim uma alegria tão grande, quanto fora decerto o temor que me precedera no lugar do horror, isto é, no lugar da segunda visão — a ponto de me parecer que eu era um daqueles bem-aventurados. Ah, se tivesse durado! Visita-me outra vez e outra ainda, Senhor, com a tua salvação, para que eu veja a felicidade dos teus eleitos e me alegre com a alegria do teu povo (Sl 105,4-5).`
    },
    {
      n: 16,
      texto: `Ó lugar de verdadeiro descanso, a que não sem razão eu daria o nome de quarto! Nele não se vê a Deus como que perturbado pela ira, nem como que retesado pelo cuidado; antes se prova ali que a sua vontade é boa, agradável e perfeita (Rm 12,2). Esta visão não aterra: acaricia. Não excita uma curiosidade inquieta: acalma-a. Não cansa os sentidos: tranquiliza-os. Aqui é que se descansa de verdade. Deus tranquilo tranquiliza tudo; e olhar para quem está em repouso é repousar. É ver o rei que, depois das disputas do dia, como que de pleitos no foro, despede as multidões, afasta de si o peso dos cuidados, busca pousada para a noite e entra no quarto com os poucos que julga dignos deste segredo e desta intimidade — tanto mais seguro no descanso quanto mais escondido, e tanto mais sereno quanto mais serenamente olha só para aqueles que ama. Se a algum de vós acontecer ser arrebatado alguma hora a este segredo e a este santuário de Deus, e ficar ali tão escondido que nada o chame nem o perturbe — nem os sentidos em atividade, nem um cuidado que espeta, nem uma culpa que morde, nem, o que é mais difícil de afastar, as imagens corporais que irrompem na imaginação —, esse, quando voltar até nós, poderá gloriar-se e dizer: Introduziu-me o rei no seu quarto (Ct 1,3). Se é este mesmo aquele de que exulta a esposa, não o afirmaria temerariamente. É, contudo, um quarto, e quarto de rei; pois, dos três lugares que atribuímos à tríplice visão, só este se fez em paz (Sl 75,3). Como se mostrou com clareza, no primeiro o descanso é escasso e no segundo é nenhum: ali ele aparece admirável e põe a curiosidade a trabalhar em investigar; aqui dá-se a conhecer como terrível e abala a nossa fraqueza. Mas neste terceiro lugar digna-se aparecer não terrível, e menos admirável do que amável: sereno e sossegado, suave e manso, e cheio de misericórdia para todos os que o contemplam.`
    },
    {
      n: 17,
      texto: `E, para que a vossa memória guarde um resumo de tudo o que num sermão já longo se discutiu sobre a despensa, o horto e o quarto, lembrai-vos de três tempos, três méritos e como que três prêmios: no horto, notai os tempos; na despensa, os méritos; e os prêmios naquela tríplice contemplação de quem busca o quarto. E sobre a despensa baste isto. Quanto ao horto e ao quarto, se ocorrer algo a acrescentar, ou coisas diferentes das que se disseram e que mereçam nota, não as deixaremos passar no lugar próprio. Se não, baste o que se disse, e não se repita; para que nunca venham a enfadar — o que Deus não permita! — as coisas que se dizem para louvor e glória do esposo da Igreja, Nosso Senhor Jesus Cristo, que é Deus sobre todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
