SERMOES.sermao({
  id: 'bernardo-cantico-55',
  colecao: 'bernardo-cantico',
  ordem: 55,
  numero: 'LV',
  titulo: 'De como o homem, pela verdadeira penitência, pode escapar do juízo de Deus',
  fonte: 'Qualiter homo per veram poenitentiam potest evadere judicium Dei',
  argumento: `O amado é comparado à gazela e ao filhote dos cervos. O filhote, que corre ainda mais depressa, exprime o desejo de quem vem salvar; a gazela, famosa pela vista aguda, o juízo de quem escolhe onde pôr o pé. Assim o Espírito Santo recomenda os dois bens do esposo, a misericórdia e o juízo; e o "filhote" lembra também a infância do Salvador, o pequenino que nasceu para nós.

Mas quem deseja a vinda do Salvador deve temer os olhos da gazela: "Esquadrinharei Jerusalém com lanternas". Jerusalém, diz Bernardo, são os que levam vida religiosa; os pecados de Babilônia são manifestos e não precisam de exame, mas os dos monges se escondem debaixo do nome e do hábito. O único remédio é julgar-se a si mesmo: quem se julga não será julgado, e Bernardo quer apresentar-se diante do rosto da ira já julgado, e não para ser julgado. A esposa, cuja consciência de nada a acusa, não teme o olhar do esposo; ele fala com ela. O sermão, curto, fica aberto para o seguinte.

Tradução feita do texto latino de Migne (PL 183, 1044-1046).`,
  pontos: [
    {
      n: 1,
      texto: `O meu amado é semelhante à gazela e ao filhote dos cervos (Ct 2,9). Isto depende do versículo anterior. Aquele que acabara de descrever saltando e apressando-se, compara-o, em consequência, à gazela e ao filhote dos cervos. E com propriedade, porque este gênero de animais é veloz na corrida e ágil no salto. Ora, a palavra é sobre o esposo, e o esposo é a Palavra. E o Profeta diz de Deus que a sua palavra corre velozmente (Sl 147,15) — o que convém bem a este passo, onde o esposo, que é a Palavra de Deus, é descrito saltando e transpondo, e por isso feito semelhante à gazela e ao filhote dos cervos. E esta é a razão da comparação. Acrescenta, porém — para que nenhuma parcela da comparação fique sem sentido —, que a gazela se distingue não só pela ligeireza da corrida, mas também pela agudeza da vista. O que se refere propriamente àquela parte da narração em que se diz que o esposo aparece não só saltando, mas também transpondo; porque, sem um olhar agudo e penetrante, não poderia de modo nenhum, sobretudo correndo, discernir em quem devia saltar e a quem devia transpor. De outro modo, para designar a velocidade de quem se apressa, poderia bastar a comparação só com o filhote do cervo, que, como se sabe, corre ainda mais rápido. Mas agora, como este esposo, embora pareça, amando ardentemente, precipitar-se correndo para os abraços da amada, sabe, contudo, dirigir os seus passos, ou antes os seus saltos, com prudente consideração, cuidando onde convém pôr o pé, foi preciso, sem dúvida, dar com o filhote do cervo também a comparação da gazela, para que por aquele se exprimisse o desejo de quem salva, e por esta o juízo de quem escolhe. Pois Cristo é justo e misericordioso, salvador e juiz: porque ama, quer que todos os homens se salvem e cheguem ao conhecimento da verdade (1Tm 2,4); e, porque julga, conhece os que são seus (2Tm 2,19) e sabe a quem escolheu desde o princípio (cf. Jo 13,18).`
    },
    {
      n: 2,
      texto: `Entendamos, pois, por ora, que estes dois bens do esposo, a misericórdia e o juízo, nos são recomendados pelo Espírito Santo nestes dois animais, para que, em testemunho da integridade e perfeição da nossa fé, também nós, imitando o Profeta, cantemos ao Senhor a misericórdia e o juízo (Sl 100,1). E não duvido que os curiosos e entendidos nestas coisas possam mostrar ainda outras propriedades destes animais que se possam aplicar ao esposo com proveito e propriedade; mas estas, creio, podem bastar para dar a razão da comparação proposta. Com beleza, porém, o Espírito Santo não deu a comparação do cervo, mas do filhote dos cervos, em que fez menção dos Patriarcas, dos quais vem Cristo segundo a carne (cf. Rm 9,5), e lembrou a infância do Salvador. Pois como um filhote apareceu o pequenino que nasceu para nós (Is 9,6). Mas tu, que desejas a vinda do Salvador, teme o exame do juiz, teme os olhos da gazela, teme aquele que diz pelo profeta: E naquele dia esquadrinharei Jerusalém com lanternas (Sf 1,12). Tem a vista aguda; o seu olho nada deixará sem esquadrinhar. Sondará os rins e os corações (Sl 7,10), e o próprio pensamento do homem se confessará a ele (cf. Sl 75,11). Que haverá seguro em Babilônia, se até Jerusalém espera o exame? Pois julgo que aqui o profeta designou com o nome de Jerusalém os que levam neste mundo uma vida religiosa, imitando quanto podem, com um modo de viver honesto e ordenado, os costumes daquela Jerusalém do alto; e não como os que são de Babilônia, que devastam a vida na perturbação dos vícios e na confusão dos crimes. Enfim, os pecados destes são manifestos e vão à frente para o juízo (cf. 1Tm 5,24), e não precisam de exame, mas de castigo. Mas os meus, que pareço monge e cidadão de Jerusalém, são pecados certamente ocultos, encobertos pelo nome e pelo hábito de monge; e por isso será preciso investigá-los com exame minucioso e, como que aproximando lanternas, trazê-los das trevas à luz.`
    },
    {
      n: 3,
      texto: `Podemos trazer também alguma coisa do salmo para confirmar o que se diz do exame de Jerusalém. Pois diz, na pessoa do Senhor: Quando chegar o tempo, julgarei as justiças (Sl 74,3). Diz, se não me engano, que há de discutir e examinar os caminhos dos justos e as suas ações. É muito de temer que, quando se chegar a isso, sob tão minucioso exame muitas das nossas justiças, como se julgam, apareçam como pecados. Há, porém, uma coisa: se nos julgarmos a nós mesmos, não seremos julgados (1Cor 11,31). Bom juízo, que me subtrai e me esconde daquele juízo divino e rigoroso. Tenho verdadeiramente horror de cair nas mãos do Deus vivo (cf. Hb 10,31); quero apresentar-me diante do rosto da ira já julgado, e não para ser julgado. O homem espiritual julga todas as coisas, e ele mesmo não é julgado por ninguém (1Cor 2,15). Julgarei, pois, os meus males, e julgarei também os meus bens. Os males, cuidarei de corrigi-los com ações melhores, de lavá-los com lágrimas, de puni-los com jejuns e com os outros trabalhos da santa disciplina. Nos bens, pensarei de mim com humildade e, segundo o preceito do Senhor, me terei por servo inútil, que fez apenas o que devia fazer (Lc 17,10). Farei o possível por não oferecer o joio em lugar do trigo, nem a palha junto com o grão. Esquadrinharei eu mesmo os meus caminhos e os meus afetos, para que aquele que há de esquadrinhar Jerusalém com lanternas não encontre em mim nada que não tenha sido esquadrinhado e examinado. Pois ele não julgará duas vezes a mesma coisa.`
    },
    {
      n: 4,
      texto: `Quem me dera seguir e perseguir com tanta clareza todas as minhas faltas que em nada tivesse de temer os olhos da gazela, em nada me acontecesse corar à luz das lanternas! E agora sou visto, mas não vejo; está presente o olho para o qual tudo está patente, embora ele mesmo não esteja patente. Virá o tempo em que conhecerei como também sou conhecido (cf. 1Cor 13,12); mas agora conheço em parte — e não sou conhecido em parte, mas por inteiro. Temo o olhar daquele observador que está de pé atrás da parede. Pois é isto que a Escritura acrescenta daquele que, pela agudeza da vista, comparou à gazela: Eis que ele está de pé atrás da parede, olhando pelas janelas, espreitando pelas grades (Ct 2,9). Disto trataremos no seu lugar. Temo, pois, este observador escondido das coisas escondidas. A esposa não teme nada, porque a consciência de nada a acusa. Enfim, que temeria a amiga, a pomba, a formosa? Pois tens logo a seguir: Eis que o meu amado, diz, me fala (Ct 2,10). A mim ele não fala; e por isso temo o seu olhar, porque não tenho testemunho. Tu, ó esposa, que ouves dizer de ti? Que te diz o teu amado? Levanta-te, diz, apressa-te, minha amiga, minha pomba, minha formosa (Ct 2,10). Mas também isto guardarei para outro princípio, e não apertarei na brevidade o que pede cuidado; para que não me ache culpado também disto, se nesta parte não fordes edificados no entendimento e no amor do esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
