SERMOES.sermao({
  id: 'bernardo-cantico-32',
  colecao: 'bernardo-cantico',
  ordem: 32,
  numero: 'XXXII',
  titulo: 'De como a alma santa recebe Cristo como esposo, e a alma fraca como médico; e da diferença dos pensamentos, e de onde nascem',
  fonte: 'Qualiter Christus suscipitur ab anima sancta tanquam sponsus',
  argumento: `Antes de explicar o pastor do meio-dia, Bernardo recapitula as figuras em que o Verbo aparece no Cântico e distribui-as segundo o estado de cada alma. À que deseja ardentemente partir e estar com Cristo, ele vem como esposo — e escapa-lhe das mãos quando ela julga segurá-lo. À que ainda se debate com os pecados, vem como médico. À que está cansada e tíbia, como companheiro de viagem que conta histórias da cidade de Deus. E aos magnânimos, que ousam pedir como Moisés, Filipe e Tomé, como rei rico que mostra os seus tesouros.

No meio, uma regra de discernimento que ficou clássica: os pensamentos maus são nossos, ou vêm do inimigo, e nem sempre se sabe de onde; mas os bons nunca são nossos — são palavras do Verbo, e é perigoso tomá-los por invenção própria.

Tradução feita do texto latino de Migne (PL 183, 945-951).`,
  pontos: [
    {
      n: 1,
      texto: `Mostra-me onde apascentas, onde repousas ao meio-dia (Ct 1,6). Estamos aqui; daqui avançamos. Mas, antes de começar a tratar desta visão e desta fala, julgo que convém recapitular brevemente as outras visões que vieram antes, e como se podem aplicar espiritualmente a nós segundo os desejos e os méritos de cada um; para que, compreendidas elas — se isso nos for dado —, brilhe também com mais facilidade o entendimento no exame desta. Mas é dificílimo. Pois, ainda que as palavras com que se descrevem essas visões ou comparações pareçam falar de corpos e de coisas corporais, são espirituais as coisas que nelas nos são servidas; e por isso é também no espírito que se hão de buscar as suas causas e razões. E quem é capaz de investigar e compreender tantos afetos e progressos da alma, segundo os quais se distribui esta graça tão multiforme da presença do esposo? Contudo, se entrarmos em nós mesmos, e o Espírito Santo se dignar mostrar-nos na sua luz aquilo que não desdenha fazer sem cessar em nós com a sua obra, creio que não ficaremos de todo sem entendimento destas coisas. Pois confio que não recebemos o espírito deste mundo, mas o Espírito que vem de Deus, para conhecermos o que Deus nos deu (1Cor 2,12).`
    },
    {
      n: 2,
      texto: `Se, pois, para algum de nós, como para o santo Profeta, o bem é estar unido a Deus (Sl 72,28) — e, para falar mais claramente, se há entre nós um homem de desejo (Dn 9,23) tal que deseje partir e estar com Cristo (Fl 1,23), e o deseje com veemência, tenha sede ardente e medite nisso sem cessar —, esse, sem dúvida, receberá o Verbo, no tempo da visita, não de outro modo senão na forma de esposo: isto é, na hora em que sentir que por dentro o apertam como uns braços da sabedoria, e que dali se derrama nele a suavidade do amor santo. Pois lhe será dado o desejo do seu coração (Sl 20,3), ainda que peregrine no corpo — mas em parte, e por um tempo, e tempo breve. Pois, quando, procurado com vigílias, súplicas, muito trabalho e chuva de lágrimas, se faz presente, de repente, quando se julga segurá-lo, escapa-se; e, vindo de novo ao encontro de quem chora e o persegue, deixa-se apanhar, mas não reter, pois de repente voa outra vez como que das mãos. E, se a alma devota insistir com preces e lágrimas, ele voltará de novo e não lhe negará o que os seus lábios pedem; mas logo tornará a desaparecer, e não será visto se não for de novo procurado com todo o desejo. Assim, pois, também neste corpo pode haver alegria frequente pela presença do esposo, mas não abundância: pois, se a visita alegra, a alternância aflige. E é preciso que a amada suporte isto até que, deposto de uma vez o fardo pesado do corpo, também ela voe, levantada pelas asas dos seus desejos, fazendo livremente o seu caminho pelos campos da contemplação e seguindo com a mente desembaraçada o amado aonde quer que vá.`
    },
    {
      n: 3,
      texto: `E, contudo, nem mesmo de passagem estará assim presente a toda alma, mas só àquela que uma devoção imensa, um desejo veemente e um afeto dulcíssimo mostram ser esposa, e digna de que o Verbo, ao vir visitá-la, se revista de beleza, tomando a forma de esposo. Pois quem ainda não se acha assim disposto, mas antes compungido pela lembrança das suas ações, e fala na amargura da sua alma dizendo a Deus: Não me condenes (Jó 10,1-2); ou talvez ainda é tentado perigosamente, arrastado e seduzido pela própria concupiscência (Tg 1,14) — esse não procura o esposo, mas o médico; e por isso não receberá beijos nem abraços, mas só remédios para as suas feridas, com óleo e com unguentos. Não é assim que muitas vezes sentimos e experimentamos na oração, nós que todos os dias ainda somos tentados pelas nossas faltas presentes e mordidos pelas passadas? De quanta amargura me livraste tantas vezes, bom Jesus, ao chegares! Quantas vezes, depois de choros angustiados, de gemidos e soluços que não se podem contar, ungiste a minha consciência ferida com a unção da tua misericórdia e a banhaste com óleo de alegria! Quantas vezes a oração, que me recebeu quase desesperado, me devolveu exultante e confiante no perdão! Os que passam pelo mesmo, esses sabem que o Senhor Jesus é verdadeiramente médico, que cura os de coração contrito e lhes enfaixa as feridas (Sl 146,3). Os que não o experimentaram, creiam nisto a ele mesmo, que diz: O Espírito do Senhor ungiu-me, enviou-me a evangelizar os mansos, a curar os contritos de coração (Is 61,1; Lc 4,18). Se ainda duvidam, aproximem-se e provem, e aprendam assim em si mesmos o que quer dizer: Quero misericórdia, e não sacrifício (Mt 9,13). Mas vejamos também o resto.`
    },
    {
      n: 4,
      texto: `Há os que, cansados dos exercícios espirituais, caídos na tibieza e postos numa espécie de desfalecimento do espírito, andam tristes pelos caminhos do Senhor, chegam de coração seco e enfadado a tudo o que lhes mandam, murmuram muitas vezes, queixam-se de que os dias são longos e longas as noites, dizendo com o santo Jó: Se durmo, digo: Quando me levantarei? E de novo espero a tarde (Jó 7,4). Quando, pois, nos acontece sofrer uma coisa assim, se o Senhor, compadecido, se aproximar de nós no caminho por onde andamos, e aquele que é do céu começar a falar do céu (Jo 3,31), e nos cantar alguma coisa agradável dos cânticos de Sião (Sl 136,3), e nos contar da cidade de Deus, da paz da cidade, da eternidade da paz, do estado da eternidade — digo-vos que aquela narração alegre servirá de carruagem à alma sonolenta e preguiçosa, a ponto de expulsar todo o enfado do espírito de quem ouve, e do corpo o cansaço. Parece-te que sofre outra coisa, ou pede outra coisa, aquele que diz: A minha alma adormeceu de tédio; fortalece-me com as tuas palavras (Sl 118,28)? E, quando o alcançar, não clamará: Como amei a tua lei, Senhor! Todo o dia é ela a minha meditação (Sl 118,97)? Pois as nossas meditações sobre ele e sobre a sua glória, a sua beleza, o seu poder, a sua majestade são como palavras do Verbo-esposo dirigidas a nós. E não só: também quando revolvemos com mente ávida os seus testemunhos e os juízos da sua boca, e meditamos na sua lei dia e noite (Sl 1,2), saibamos com certeza que o esposo está presente e nos fala, para que, deleitados com as suas palavras, não nos cansemos com os trabalhos.`
    },
    {
      n: 5,
      texto: `Tu, pois, quando sentires que se revolvem no teu espírito coisas assim, não as julgues pensamento teu, mas reconhece que fala aquele que diz no profeta: Sou eu que falo justiça (Is 63,1). Pois os pensamentos da nossa mente são muito parecidos com as palavras da Verdade que fala em nós; e ninguém distingue facilmente o que o seu coração gera dentro e o que ouve — a não ser quem repara com prudência no Senhor, que diz no Evangelho: Do coração saem os maus pensamentos (Mt 15,19); e aquilo: Por que pensais o mal nos vossos corações? (Mt 9,4); e: Quem diz a mentira fala do que é seu (Jo 8,44). E o Apóstolo: Não que sejamos capazes de pensar alguma coisa por nós mesmos, como vinda de nós — subentende-se: de bom —; a nossa capacidade vem de Deus (2Cor 3,5). Quando, pois, revolvemos no coração coisas más, é pensamento nosso; se são boas, é palavra de Deus. Aquelas, o nosso coração as diz; estas, ouve-as. Ouvirei, diz o salmo, o que o Senhor Deus fala em mim, porque falará de paz ao seu povo (Sl 84,9). É Deus, pois, que fala em nós a paz, a piedade, a justiça; e não somos nós que pensamos tais coisas por nós mesmos: ouvimo-las em nós. Mas os homicídios, os adultérios, os roubos, as blasfêmias e coisas semelhantes saem do coração (Mt 15,19): não os ouvimos, dizemo-los. Enfim, disse o insensato no seu coração: Não há Deus (Sl 13,1). E foi por isso que o ímpio irritou a Deus, porque disse no seu coração: Ele não vai reclamar (Sl 9,34). Mas há ainda outra coisa que se sente no coração e, no entanto, não é palavra do coração. Pois não sai do coração, como o nosso pensamento, nem é aquilo que dissemos vir ao coração, a palavra do Verbo, já que é mau. É lançado pelas potências inimigas, como se dão as sugestões por meio dos anjos maus (Sl 77,49); tal foi, por exemplo, o que se lê que o diabo pôs no coração de Judas, filho de Simão Iscariotes, para que entregasse o Senhor (Jo 13,2).`
    },
    {
      n: 6,
      texto: `Mas quem é tão vigilante e tão diligente observador dos seus movimentos interiores — dos que se dão nele e dos que vêm dele — que distinga com clareza, em cada sentimento ilícito do seu coração, entre a doença da mente e a mordida da serpente? Julgo que isso não é possível a nenhum mortal, a não ser a quem, iluminado pelo Espírito Santo, recebeu aquele dom especial que o Apóstolo, entre os outros carismas que enumera, chama o discernimento dos espíritos (1Cor 12,10). Pois, por mais que alguém, segundo Salomão, guarde o seu coração com todo o cuidado (Pr 4,23) e observe com a maior vigilância tudo o que se move dentro de si — ainda que talvez tenha nisso longo exercício e experiência frequente —, não poderá contudo reconhecer e distinguir com toda a nitidez, em si mesmo, o mal que nasce de dentro e o mal que foi semeado. Pois quem entende as próprias faltas? (Sl 18,13) E não importa muito sabermos de onde nos vem o mal, contanto que saibamos que está em nós: venha de onde vier, é preciso antes vigiar e orar para não consentirmos. Enfim, o profeta ora contra as duas espécies de mal, dizendo: Purifica-me, Senhor, das minhas faltas escondidas, e das alheias preserva o teu servo (Sl 18,13-14). E eu não vos posso transmitir o que não recebi. E não recebi, confesso, com que assinalar uma distinção certa entre o que o coração gera e o que o inimigo semeia. Pois ambos são maus, ambos vêm do mal; ambos estão no coração, mas nem ambos saem do coração. Tudo isto me é certo em mim, ainda que me seja incerto o que atribuir ao coração e o que ao inimigo. E nisto, como disse, não há perigo.`
    },
    {
      n: 7,
      texto: `Mas há um ponto em que se erra com perigo — ou antes, com condenação —, e ali, com razão, se nos fixa uma regra certa: que não demos a nós mesmos o que em nós é de Deus, julgando que a visita do Verbo é pensamento nosso. Tanto quanto o bem dista do mal, tanto distam, pois, estas duas coisas: porque nem do Verbo sai o mal, nem do coração sai o bem, a não ser o que porventura tenha antes concebido do Verbo; pois a árvore boa não pode dar frutos maus, nem a árvore má frutos bons (Mt 7,18). Mas creio já ter dito bastante sobre o que no nosso coração é de Deus e o que é nosso — e não em vão, a meu ver, mas para que os inimigos da graça saibam que o coração humano, sem a graça, não basta nem para pensar o bem; que a sua capacidade vem de Deus; e que o bem que se pensa é voz de Deus, e não filho do coração. Tu, pois, se ouves a sua voz, já não ignores de onde vem nem para onde vai (Jo 3,8): sabes que sai de Deus e vai para o coração. Mas cuida de que a palavra que sai da boca de Deus não volte a ele vazia, mas prospere e faça tudo aquilo para que a enviou (Is 55,11), para que também tu possas dizer: a graça de Deus em mim não foi vã (1Cor 15,10). Feliz a mente a quem o Verbo, companheiro inseparável, se mostra afável em toda parte, e que, deleitada sem cessar pela suavidade da sua conversa, se livra a toda hora dos incômodos e dos vícios da carne, resgatando o tempo dos dias maus (Ef 5,16). Não se cansará, não se afligirá; pois, como diz a Escritura: Não entristecerá o justo nada do que lhe acontecer (Pr 12,21).`
    },
    {
      n: 8,
      texto: `Quanto à figura do grande pai de família, ou da majestade régia, creio que aparece àqueles que, chegando ao coração alto (Sl 63,7), tornados mais magnânimos por uma maior liberdade de espírito e pureza de consciência, costumam ousar coisas maiores: inquietos e curiosos por penetrar o mais secreto, alcançar o mais alto e tentar o mais perfeito — não só no entendimento, mas também nas virtudes. Pois estes, pela grandeza da sua fé, são achados dignos de ser introduzidos em toda a plenitude; e não há, em todos os armazéns da sabedoria, nenhum de que o Senhor, Deus das ciências (1Sm 2,3), julgue dever afastar os que são ávidos de verdade e não têm consciência de vaidade. Assim era Moisés, que ousava dizer a Deus: Se achei graça aos teus olhos, mostra-te a mim (Ex 33,13.18). Assim era Filipe, que pedia que lhe mostrassem o Pai, a ele e aos seus condiscípulos (Jo 14,8); e assim Tomé, que se recusava a crer se não tocasse com a mão a ferida e o lado aberto (Jo 20,25). Fé pequena, mas que nascia, de modo admirável, da grandeza de ânimo. Assim também Davi, que dizia a Deus: A ti falou o meu coração: o meu rosto te buscou; o teu rosto, Senhor, eu buscarei (Sl 26,8). Estes ousam coisas grandes porque são grandes; e o que ousam, alcançam, segundo a palavra da promessa que lhes foi feita, que é esta: Todo lugar que o vosso pé pisar será vosso (Dt 11,24). Pois uma fé grande merece coisas grandes; e até onde estenderes nos bens do Senhor o pé da confiança, até aí possuirás.`
    },
    {
      n: 9,
      texto: `Enfim, a Moisés Deus fala boca a boca, e ele merece ver o Senhor às claras, não por enigmas e figuras — enquanto aos outros profetas Deus diz que só aparece em visão e lhes fala por sonho (Nm 12,6-8). Também a Filipe, segundo o pedido do seu coração, foi mostrado o Pai no Filho — sem dúvida naquilo que logo ouviu: Filipe, quem me vê, vê também o Pai; e: Eu estou no Pai, e o Pai está em mim (Jo 14,9-10). E a Tomé, segundo o desejo do seu coração, ofereceu-se para ser tocado (Jo 20,27), e não lhe negou o que os seus lábios pediam. E Davi? Não dá ele a entender que não ficou de todo privado do que desejava, quando diz que não daria sono aos seus olhos, nem repouso às suas pálpebras, enquanto não achasse um lugar para o Senhor (Sl 131,4-5)? A tais espíritos grandes, pois, o Esposo virá ao encontro como grande, e fará com eles coisas grandes (Sl 125,3), enviando a sua luz e a sua verdade e conduzindo-os e levando-os ao seu monte santo e às suas tendas (Sl 42,3), de modo que quem é assim diga: O Poderoso fez em mim grandes coisas (Lc 1,49). Os seus olhos verão o rei na sua beleza (Is 33,17), que irá à sua frente, conduzindo-o às belezas do deserto, às flores das rosas e aos lírios dos vales, aos encantos dos hortos e às águas das fontes, às delícias das despensas e aos perfumes dos aromas, e enfim aos próprios segredos do quarto.`
    },
    {
      n: 10,
      texto: `Estes são os tesouros da sabedoria e da ciência escondidos junto do esposo (Cl 2,3); estes, os pastos da vida preparados para refeição das almas santas. Feliz o homem que saciou com eles o seu desejo (Sl 126,5). Fique só avisado de uma coisa: que não queira ter sozinho o que pode bastar a muitos. Pois talvez seja por isso que, depois de tudo isto, o esposo é descrito aparecendo como pastor: para que quem alcançou tantos dons seja avisado de que deve apascentar o rebanho dos mais simples, que não conseguem alcançar estas coisas por si mesmos, assim como as ovelhas não se atrevem a sair para o pasto sem pastor. Por isso a esposa, reparando nisto com prudência, pede que lhe mostrem onde ele apascenta e onde repousa no calor do meio-dia — pronta, como se dá a entender, a ser apascentada e a apascentar com ele e sob ele. Pois não julga seguro levar o rebanho para longe do Pastor supremo, por causa dos assaltos dos lobos, sobretudo dos que vêm a nós em pele de ovelha (Mt 7,15); e por isso empenha-se em apascentar nos mesmos pastos que ele e em repousar nas mesmas sombras. E dá a razão: Para que eu não comece a vaguear atrás dos rebanhos dos teus companheiros (Ct 1,6). São os que querem parecer amigos do esposo e não o são; e, cuidando de apascentar os seus próprios rebanhos, e não os dele, andam de um lado e de outro armando ciladas e dizendo: Eis aqui o Cristo, ei-lo ali (Mc 13,21) — para seduzir muitos, afastá-los dos rebanhos de Cristo e juntá-los aos seus. Isto quanto ao texto da letra. O sentido espiritual que nela se esconde, esperai-o no começo de outro sermão — seja ele o que for que, enquanto orais, o esposo da Igreja, Jesus Cristo, Senhor nosso, se dignar repartir comigo pela sua misericórdia; ele, que é Deus sobre todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
