SERMOES.sermao({
  id: 'bernardo-cantico-34',
  colecao: 'bernardo-cantico',
  ordem: 34,
  numero: 'XXXIV',
  titulo: 'Da humildade e da paciência',
  fonte: 'In quo tractatur de humilitate et patientia',
  argumento: `A esposa pediu muito, e o esposo responde com dureza: se não te conheces, sai. Antes de explicar a frase, Bernardo detém-se no que ela ensina: Deus costuma humilhar antes de exaltar, como fez com Moisés, com os filhos de Zebedeu e com Jó; e quem se vê humilhado deve tomá-lo como sinal de que a graça se aproxima. Davi, amaldiçoado por um servo, proíbe que o calem, porque percebe que é Deus quem o humilha por aquela boca.

O centro do sermão é uma distinção precisa: humilhação não é humildade. Há quem seja humilhado com rancor, e é culpado; quem o seja com paciência, e é inocente; e quem o seja de bom grado, e só esse é justo. A paciência salva a alma, mas a graça é dada aos humildes, e só é humilde quem converte a humilhação em humildade, como Paulo, que se gloria de boa vontade nas suas fraquezas.

Tradução feita do texto latino de Migne (PL 183, 959-962).`,
  pontos: [
    {
      n: 1,
      texto: `Se não te conheces, ó mais bela entre as mulheres, sai e vai atrás dos rebanhos dos teus companheiros, e apascenta os teus cabritos junto às tendas dos pastores (Ct 1,7). Outrora o santo Moisés, porque confiava muito na graça e na familiaridade que tinha encontrado junto de Deus, aspirava a uma grande visão, a ponto de dizer a Deus: Se achei graça aos teus olhos, mostra-te a mim. Mas, em lugar dela, recebeu uma visão muito inferior, a partir da qual, porém, pudesse um dia chegar àquela que queria (Ex 33,13-23). Também os filhos de Zebedeu, andando na simplicidade do seu coração, ousaram eles mesmos pedir algo grande; mas foram reconduzidos ao degrau por onde era preciso subir (Mt 20,21-23). Assim também agora a esposa, porque parece pedir uma coisa grande, é contida com uma resposta bastante severa, mas sem dúvida útil e leal. Pois quem se esforça por chegar ao mais alto deve ter de si mesmo um sentimento humilde, para que, ao elevar-se acima de si, não caia de si mesmo, se não estiver firmemente assentado em si pela verdadeira humildade. E, porque as coisas maiores de modo algum se obtêm senão pelo mérito da humildade, quem há de ser promovido é humilhado pela repreensão e merece pela humildade. Tu, pois, quando te vires humilhado, toma isso como sinal favorável (cf. Sl 85,17), prova certa de que a graça se aproxima. Pois, assim como antes da ruína o coração se exalta (Pr 16,18), assim antes da exaltação se humilha (Pr 18,12). Lês, com efeito, uma coisa e outra: que Deus resiste aos soberbos e dá a graça aos humildes (Tg 4,6). Enfim, quando, depois de um triunfo insigne, julgou que devia recompensar com larga bênção a paciência tão grande e tão provada do seu servo Jó, não tratou primeiro de humilhá-lo com muitas e severas perguntas, e assim preparar o caminho à bênção (Jó 38–42)?`
    },
    {
      n: 2,
      texto: `Mas é pouco aceitarmos de bom grado quando Deus nos humilha por si mesmo, se não tivermos a mesma sabedoria quando o faz por meio de outro. Recebei, pois, um exemplo admirável disto no santo Davi. Certa vez foi amaldiçoado, e por um servo; mas ele nem sentiu a injúria redobrada, porque pressentiu a graça. Que tenho eu convosco, diz, filhos de Sárvia? (2Sm 16,10). Ó homem verdadeiramente segundo o coração de Deus (cf. At 13,22), que julgou dever irritar-se antes com quem o queria vingar do que com quem o insultava! Por isso falava com a consciência tranquila: Se paguei com o mal aos que me fizeram mal, caia eu com razão vazio diante dos meus inimigos (Sl 7,5). Proibiu, pois, que se fizesse calar o maldizente que o insultava, tendo as maldições por lucro. E acrescenta: Foi o Senhor que o mandou amaldiçoar Davi (2Sm 16,10). Verdadeiramente segundo o coração de Deus, ele que tirava a sua sentença do coração de Deus. Enfurecia-se a língua maldizente, e ele atentava no que Deus fazia em segredo. A voz do que o amaldiçoava nos ouvidos, e o ânimo inclinava-se para a bênção. Acaso estava Deus na boca do blasfemo? De modo nenhum! Mas serviu-se dele para humilhar Davi. E isso não escapou ao Profeta, a quem Deus tinha manifestado os segredos e mistérios da sua sabedoria (Sl 50,8); e por isso diz: Foi bom para mim que me humilhaste, para que eu aprenda os teus justos preceitos (Sl 118,71).`
    },
    {
      n: 3,
      texto: `Vês que a humildade nos justifica? Eu disse humildade, e não humilhação. Quantos são humilhados, e não são humildes! Uns são humilhados com rancor, outros com paciência, outros de bom grado. Os primeiros são culpados, os seguintes inocentes, os últimos justos. É verdade que também a inocência é uma parte da justiça; mas a sua perfeição está no humilde. E quem pode dizer: Foi bom para mim que me humilhaste, esse é verdadeiramente humilde. Não pode dizer isto quem suporta a contragosto; menos ainda quem murmura. A nenhum dos dois prometemos a graça por ser humilhado — ainda que, sem dúvida, estes dois difiram muito entre si, e um, pela sua paciência, possua a sua alma (Lc 21,19), e o outro pereça na sua murmuração. Mas, ainda que só um mereça a ira, nenhum dos dois merece a graça; pois Deus dá a graça não aos humilhados, mas aos humildes. E humilde é quem converte a humilhação em humildade; é esse quem diz a Deus: Foi bom para mim que me humilhaste. Aquilo que alguém apenas suporta com paciência não lhe é bom, mas penoso. Ora, sabemos que Deus ama quem dá com alegria (2Cor 9,7). Por isso, também quando jejuamos, manda-se que unjamos a cabeça com óleo e lavemos o rosto (Mt 6,17), para que a nossa boa obra seja temperada com uma certa alegria espiritual, e o nosso holocausto se torne gordo (cf. Sl 19,4). Pois só a humildade alegre e livre merece a graça que anuncia. A humildade forçada ou arrancada, como é a daquele homem paciente que possui a sua alma — esta humildade, digo, ainda que alcance a vida por causa da paciência, não terá a graça por causa da tristeza. Pois não lhe convém, a quem é assim, aquela palavra da Escritura: Glorie-se o humilde na sua exaltação (Tg 1,9); porque não se humilha espontaneamente nem de bom grado.`
    },
    {
      n: 4,
      texto: `Queres ver um humilde que se gloria com razão e é verdadeiramente digno de glória? De boa vontade, diz, me gloriarei nas minhas fraquezas, para que habite em mim a força de Cristo (2Cor 12,9). Não diz que suporta com paciência as suas fraquezas, mas que se gloria, e de boa vontade se gloria nelas, mostrando que é bom para ele ser humilhado; e que de modo nenhum lhe basta possuir a sua alma como quem é humilhado com paciência, se não receber também a graça como quem é humilhado por vontade própria. Ouve daí uma regra geral: Todo aquele que se humilha, diz, será exaltado (Lc 14,11). Dá a entender, sem dúvida, que não é toda humildade que há de ser exaltada, mas só aquela que vem da vontade, não da tristeza nem da necessidade (cf. 2Cor 9,7). Como também, pelo contrário, não será humilhado todo aquele que é exaltado, mas só será humilhado quem se exalta, precisamente por causa da vaidade voluntária. Assim, pois, será exaltado não quem é humilhado, mas quem se humilha espontaneamente — pelo mérito da vontade, é claro. Pois, ainda que a matéria da humildade seja fornecida por outro — por exemplo, afrontas, prejuízos, suplícios —, nem por isso se dirá com razão humilhado por outro, e não por si mesmo, aquele que decidiu sofrer todas essas coisas por causa de Deus, com a consciência calada e alegre.`
    },
    {
      n: 5,
      texto: `Mas aonde vamos? Suportais com paciência, ao que sinto, esta digressão sobre a humildade e a paciência; mas voltemos ao ponto de onde nos afastamos. Pois isto nos ocorreu por ocasião da resposta com que o esposo julgou dever conter a esposa que presumia coisas grandes — e não sem sabedoria, mas para que daí se lhe desse ocasião de uma humildade mais provada e maior, pela qual se tornasse mais digna de coisas melhores e mais capaz daquelas mesmas que pedia. Contudo, como ainda estamos à porta deste capítulo, comecemos o seu exame, se vos parece bem, no princípio de outro sermão, sobretudo para que as palavras do esposo não sejam explicadas nem ouvidas com enfado. Que isso afaste dos seus servos o próprio Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
