SERMOES.sermao({
  id: 'bernardo-cantico-24',
  colecao: 'bernardo-cantico',
  ordem: 24,
  numero: 'XXIV',
  titulo: 'Contra o detestável vício da maledicência; e em que consiste sobretudo a retidão do homem',
  fonte: 'Contra detestabile vitium detractionis',
  argumento: `Bernardo volta de Roma depois do fim do cisma de Anacleto — «aquietou-se a fúria leonina», diz, jogando com o nome dos Pierleoni — e retoma o comentário onde o deixara, em «os retos te amam».

Antes de explicar quem são os retos, detém-se num retrato dos maldizentes que ficou célebre: os que falam mal às claras e os que falam mal entre suspiros, de olhos baixos e voz chorosa, tanto mais persuasivos quanto se acredita que falam a contragosto. Depois define a retidão: não é a do corpo, que anda ereto, mas a da alma, que exige ao mesmo tempo fé reta e obras retas. Caim é o exemplo de quem ofereceu com retidão e repartiu sem ela.

Tradução feita do texto latino de Migne (PL 183, 894-899).`,
  pontos: [
    {
      n: 1,
      texto: `Desta terceira vez, irmãos, um olhar mais clemente contemplou do céu o nosso regresso de Roma, e um rosto enfim mais sereno sorriu-nos do alto. Aquietou-se a fúria leonina, a malícia chegou ao fim, a Igreja recobrou a paz. Foi reduzido a nada diante dele o maligno (Sl 14,4) que durante quase oito anos a perturbara com um cisma cruel. E terei eu voltado a vós, salvo de tantos perigos, para nada? Fui-vos devolvido pelos vossos desejos, e disponho-me para o vosso progresso: vivo pelos vossos méritos, e quero viver para o vosso esforço e para a vossa salvação. E, como quereis que eu continue o que há muito comecei no Cântico, aceito-o de bom grado, e julgo mais conveniente remendar o sermão interrompido do que começar algo novo. Receio, porém, que a dignidade do assunto não admita, como convém, um espírito desacostumado durante todo esse tempo e ocupado por tanto tempo com coisas não só tão diferentes, mas também tão indignas. Mas o que tenho, isso vos dou (At 3,6); e Deus poderá, pelo meu serviço fiel, dar-me também o que não tenho, para que eu o dê. Se não, culpe-se o engenho, não a vontade.`
    },
    {
      n: 2,
      texto: `O lugar por onde devemos começar, se não me engano, é este: Os retos te amam. Antes de começarmos a explicá-lo, vejamos de quem é a frase, isto é, quem a diz; pois nos cabe dizer o que o autor não diz. E talvez seja melhor atribuí-la às jovenzinhas, como se a acrescentassem às suas próprias palavras. Pois, tendo dito: Exultaremos e nos alegraremos em ti, lembradas dos teus peitos mais que do vinho — e não há dúvida de que falavam à mãe —, continuam na mesma fala e acrescentam: Os retos te amam (Ct 1,3). Creio que o dizem por causa de algumas delas, que não pensavam do mesmo modo, embora parecessem correr junto: buscavam o que era seu, não andavam com simplicidade nem com sinceridade, tinham inveja da glória particular da mãe e procuravam ocasião de murmurar contra ela, justamente por ter entrado sozinha nas despensas. Isto não é outra coisa senão aquilo que diz o Apóstolo: perigos entre falsos irmãos (2Cor 11,26). São estas, enfim, as que a obrigam logo a seguir a defender-se das suas censuras, quando lhes responde: Sou negra, mas formosa, filhas de Jerusalém (Ct 1,4). Assim, por causa das que murmuram e maldizem, as que são boas, simples, humildes e mansas dizem à esposa, para a consolar: Os retos te amam. Não te preocupes, dizem, com a censura injusta destas maldizentes, já que é certo que os retos te amam. É boa consolação, de fato, quando os maus nos difamam por fazermos o bem, que os retos nos amem. Contra a boca dos que falam iniquidade basta de sobra a opinião dos bons, com o testemunho da consciência. No Senhor se gloriará a minha alma; ouçam os mansos e alegrem-se (Sl 33,3). Os mansos, diz ele, que se alegrem. Que eu agrade aos mansos, e ouço com calma o que quer que a inveja das perdidas queira lançar contra mim.`
    },
    {
      n: 3,
      texto: `É neste sentido, pois, que creio ter sido posto «os retos te amam». E não sem razão, a meu ver: pois quase em toda parte, no coro das jovenzinhas, se encontram algumas assim, que observam com curiosidade o que a esposa faz, para a depreciar, não para a imitar. Atormentam-se com o bem dos seus superiores e alimentam-se do mal deles. Poderias vê-las andar à parte, juntar-se e sentar-se lado a lado, e logo soltar as línguas atrevidas num cochicho detestável. Uma se une a outra tão estreitamente que nem um sopro passa entre elas (Jó 41,7): tão grande é o gosto de maldizer, ou de ouvir quem maldiz. Fazem amizade para dizer mal, concordes para a discórdia. Travam entre si amizades inimicíssimas, e celebram a sua odiosa conversa com o mesmo afeto de uma malignidade que as une. Não fizeram outra coisa, outrora, Herodes e Pilatos, de quem conta o Evangelho que se tornaram amigos naquele dia (Lc 23,12) — isto é, no dia da paixão do Senhor. Quando se reúnem assim, já não é comer a ceia do Senhor (1Cor 11,20), mas antes servir e beber o cálice dos demônios (1Cor 10,21); pois, enquanto as línguas de umas trazem o veneno da perdição, os ouvidos de outras acolhem de bom grado a morte que entra. É assim que, segundo o profeta, a morte entra pelas nossas janelas (Jr 9,21): quando, com comichão nos ouvidos e na boca, disputamos para servir uns aos outros o copo mortal da maledicência. Não entre a minha alma no conselho dos maldizentes, porque Deus os odeia, como diz o Apóstolo: os maldizentes são odiosos a Deus (Rm 1,30). Ouve como o próprio Deus confirma esta sentença, falando no salmo: Quem difamava às escondidas o seu próximo, a esse eu perseguia (Sl 100,5).`
    },
    {
      n: 4,
      texto: `E não é de admirar, pois se sabe que este vício, mais que os outros, ataca e persegue a caridade, que é Deus — como também vós podeis perceber. Todo aquele que maldiz, primeiro denuncia a si mesmo como vazio de caridade. Depois, que outra coisa pretende ao maldizer, senão que aquele de quem fala se torne odioso ou desprezível para aqueles diante de quem fala? A língua maldizente fere, pois, a caridade em todos os que a ouvem e, quanto está nela, mata-a e apaga-a por completo; e não só neles, mas em todos os ausentes a quem a palavra, voando, porventura chegue por meio dos que estavam presentes. Vês com que facilidade e em quão pouco tempo uma palavra que corre veloz pode contaminar com a peste desta malícia uma multidão imensa de almas. Por isso o espírito profético diz destes: A sua boca está cheia de maldição e de amargura; os seus pés são velozes para derramar sangue (Sl 13,3). Tão velozes, sem dúvida, quanto corre veloz a palavra. Um só é o que fala, e diz uma só palavra; e, no entanto, essa única palavra, num só momento, ao infetar os ouvidos de uma multidão de ouvintes, mata-lhes as almas. Pois o coração amargo com o fel da inveja não pode espalhar, pelo instrumento da língua, senão amarguras, como diz o Senhor: A boca fala do que está cheio o coração (Lc 6,45). E esta peste tem as suas espécies: uns vomitam o veneno da maledicência às claras e sem pudor, tal como lhes vem à boca; outros tentam disfarçar com certo verniz de fingida modéstia a malícia que conceberam e que não conseguem reter. Verias soltarem-se primeiro suspiros profundos, e então, com certa gravidade e vagar, de rosto triste, olhos baixos e voz chorosa, sair a maldição — tanto mais persuasiva quanto os que ouvem acreditam que é dita a contragosto, e mais por compaixão do que por malícia. Dói-me muito, diz um, porque o estimo bastante, e nunca consegui corrigi-lo disso. E outro: Eu já sabia muito bem isso dele; mas por mim nunca se teria sabido. Mas, uma vez que a coisa se tornou pública por outro, não posso negar a verdade: digo-o com pesar, é mesmo assim. E acrescenta: Que grande pena! Porque em muitas outras coisas ele tem valor; mas nisto, para dizer a verdade, não há desculpa possível.`
    },
    {
      n: 5,
      texto: `Ditas estas poucas coisas contra um vício tão maligno, voltemos à ordem da explicação e mostremos quem se deve entender aqui por retos. Pois não creio que alguém de reto entendimento pense que se chamam retos, segundo o corpo, os que amam a esposa. Por isso devemos mostrar a retidão espiritual, isto é, a da alma ou do coração. É o Espírito que fala, exprimindo coisas espirituais em termos espirituais (1Cor 2,13). Foi segundo a alma, pois, e não segundo a matéria terrena e cheia de borra, que Deus fez o homem reto (Ecl 7,30). Pois o criou à sua imagem e semelhança (Gn 1,27); e ele, como cantas no salmo, é assim: Reto é o Senhor nosso Deus, e não há iniquidade nele (Sl 91,16). Deus, sendo reto, fez o homem reto, semelhante a si, isto é, sem iniquidade, assim como nele não há iniquidade. Ora, a iniquidade é vício do coração, não da carne; e assim saberás que é na parte espiritual de ti, e não na substância grosseira e de barro, que se há de conservar, ou restaurar, a semelhança de Deus. Pois Deus é espírito; e os que querem continuar semelhantes a ele, ou tornar-se semelhantes, têm de entrar no coração e tratar desse assunto no espírito — onde, contemplando de rosto descoberto a glória de Deus, sejam transformados na mesma imagem, de claridade em claridade, como pelo Espírito do Senhor (2Cor 3,18).`
    },
    {
      n: 6,
      texto: `É verdade que Deus deu também ao homem um corpo de porte ereto; talvez para que esta retidão corporal da obra exterior e mais vil lembrasse ao homem interior, feito à imagem de Deus, que guardasse a sua retidão espiritual, e para que a beleza do barro acusasse a deformidade da alma. Pois que há de mais indecoroso do que levar uma alma curvada num corpo ereto? É coisa perversa e feia que o vaso de barro, que é o corpo feito de terra, tenha os olhos para cima, olhe livremente para os céus e deleite a vista nas luzes do céu; e que a criatura espiritual e celeste, pelo contrário, arraste os seus olhos — isto é, os sentidos e os afetos interiores — para baixo, para a terra; e que, devendo ser criada na púrpura, se prenda à lama como uma das porcas e abrace o esterco (Lm 4,5). Envergonha-te, minha alma, de ter trocado a semelhança divina pela dos animais; envergonha-te de rolar na lama, tu que és do céu. Envergonha-te, alma — diz o corpo —, ao olhares para mim. Criada reta, semelhante a quem te criou, recebeste também a mim como ajuda semelhante a ti (Gn 2,18), ao menos segundo os traços da retidão corporal. Para onde quer que te voltes — para Deus, lá em cima, ou para mim, cá embaixo, pois ninguém jamais odiou a própria carne (Ef 5,29) —, em toda parte te sai ao encontro a figura da tua beleza, e em toda parte tens, a respeito da tua dignidade, um aviso familiar do magistério da sabedoria. Se eu, pois, retenho e guardo a prerrogativa que é minha, e que recebi por tua causa, como não te envergonhas tu de ter perdido a tua? Por que há de o Criador ver apagada em ti a sua semelhança, quando em mim conserva para ti a tua e a põe sem cessar diante dos teus olhos? Toda a ajuda que eu te devia, tu a converteste em vergonha para ti; abusas do meu serviço e habitas indignamente um corpo humano, espírito bruto e bestial.`
    },
    {
      n: 7,
      texto: `Almas curvadas assim não podem amar a esposa, porque não são amigas do esposo, sendo amigas do mundo. Quem quer ser amigo deste mundo, diz a Escritura, torna-se inimigo de Deus (Tg 4,4). Buscar e saborear o que é da terra é, pois, a curvatura da alma; e, do lado oposto, meditar e desejar o que é do alto é a retidão (Cl 3,1-2). E, para que seja perfeita, deve definir-se pelo sentir e pelo consentir. Eu te chamaria reto, de fato, se sentisses com retidão em tudo e não dissentisses com as obras. Que a fé e a ação anunciem o estado da alma, que é invisível. Julga reto aquele que tiveres provado ser católico na fé e justo nas obras; se não, não hesites em tê-lo por curvado. Pois assim tens escrito: Se ofereces com retidão, mas não repartes com retidão, pecaste (Gn 4,7). Ofereces com retidão cada uma destas coisas, mas não as repartes com retidão, separando uma da outra. Não sejas reto no oferecer e torto no repartir. Por que separas a ação da fé? Separas iniquamente, matando a tua fé; pois a fé sem obras está morta (Tg 2,20). Ofereces a Deus uma oferta morta? Pois, se a devoção é de certo modo a alma da fé, que é a fé que não age pelo amor (Gl 5,6) senão um cadáver sem vida? Honras bem a Deus com uma oferta fétida? Aplacas-o bem, tu que és o assassino da tua fé? Como pode haver sacrifício de paz onde há discórdia tão cruel? Não é de admirar que Caim se tenha levantado contra o irmão, ele que primeiro matara a própria fé. De que te admiras, Caim, se não olha para as tuas ofertas aquele que te despreza? (Gn 4,5) Nem é de admirar que não olhe para ti, que estás assim dividido em ti mesmo. Se dás a mão à devoção, por que dás a alma à inveja? Em desacordo contigo mesmo, não reconcilias Deus contigo; não o aplacas, pecas — ainda não por oferecer impiamente, mas por repartir sem retidão. Ainda não és fratricida, mas já és tido por assassino da fé. És reto, por acaso, ao estender a mão a Deus, tu cujo coração a inveja e o ódio ao irmão arrastam para a terra? Como pode ser reto aquele cuja fé está morta, cuja obra é morte, que não tem devoção nenhuma e tem muita amargura? Havia fé em quem oferecia, mas não havia amor na fé: a oferta era reta, mas a separação era cruel.`
    },
    {
      n: 8,
      texto: `A morte da fé é a separação da caridade. Crês em Cristo? Faze as obras de Cristo, para que a tua fé viva. Que o amor anime a tua fé, e a ação a prove. Que uma obra terrena não curve aquele que a fé nas coisas do céu levanta. Tu, que dizes permanecer em Cristo, deves andar como ele andou (1Jo 2,6). Mas, se buscas a própria glória, se invejas quem prospera, se falas mal de quem está ausente, se pagas na mesma moeda a quem te ofende — isso Cristo não fez. Confessas conhecer a Deus, mas com as obras o negas (Tt 1,16). Deste — não com retidão, mas com impiedade — a língua a Cristo e a alma ao diabo. Ouve, pois, o que ele diz: Este homem honra-me com os lábios, mas o seu coração está longe de mim (Is 29,13). Não és reto, decerto, tu que repartes com tão pouca retidão. Não podes levantar a cabeça, oprimida pelo jugo do diabo. Não consegues endireitar-te, tu a quem a iniquidade domina. As tuas iniquidades passaram por cima da tua cabeça e pesam sobre ti como um fardo pesado (Sl 37,5). Enfim, a iniquidade está sentada sobre um talento de chumbo (Zc 5,7). Vês que nem a fé reta faz o homem reto, se não age pelo amor. E quem está sem amor não tem com que amar a esposa. Mas também as obras, por retas que sejam, não bastam sem a fé para fazer o coração reto. Pois quem chamaria reto a um homem que não agrada a Deus? E sem fé é impossível agradar a Deus (Hb 11,6). Quem não agrada a Deus não pode achar Deus agradável; pois aquele a quem Deus agrada não pode desagradar a Deus. E a quem Deus não agrada, também não agrada a sua esposa. Como será reto, então, quem não ama nem a Deus nem à Igreja de Deus, a quem se diz: Os retos te amam? Se, pois, nem a fé sem obras nem as obras sem fé bastam para a retidão da alma, nós que cremos em Cristo, irmãos, empenhemo-nos em fazer retos os nossos caminhos e os nossos esforços. Levantemos os nossos corações, juntamente com as mãos, para Deus (Lm 3,41), para sermos achados retos por inteiro, comprovando com atos retos a retidão da nossa fé — amigos da esposa e amados do esposo, Jesus Cristo, Senhor nosso, que é Deus bendito pelos séculos. Amém.`
    }
  ]
});
