SERMOES.sermao({
  id: 'bernardo-cantico-49',
  colecao: 'bernardo-cantico',
  ordem: 49,
  numero: 'XLIX',
  titulo: 'De como a caridade é ordenada pelo discernimento, para que todos os membros da Igreja, isto é, os eleitos, se unam entre si',
  fonte: 'Qualiter per discretionem ordinatur charitas',
  argumento: `A esposa volta às jovenzinhas como quem está embriagada, e explica: o rei a introduziu na adega. Embriagada de amor, como os apóstolos no Pentecostes, que estavam embriagados, sim, mas do Espírito, e não de vinho doce. Também hoje quem sai da oração ardendo de amor e de zelo esteve na adega; outros dons, como a profecia ou as línguas, vêm de outras câmaras. Há dois arrebatamentos na contemplação: um do entendimento, na luz; outro do afeto, no fervor — e a adega é este segundo.

Mas o zelo sem ciência é insuportável, e por isso a esposa acrescenta: "ordenou em mim a caridade". O discernimento é o cocheiro das virtudes: sem ele, a virtude vira vício. É ele que mantém cada um no seu ofício e faz de muitos um só corpo. Bernardo aplica a si mesmo: deve cuidar primeiro dos seus monges, mas alegrar-se mais com o bem maior que Deus faz por meio de outros. Vendo os monges suspirar, consola-os: caminhar já é progredir, e a inveja que se sente e não se consente é uma doença a curar, não um crime a condenar.

Tradução feita do texto latino de Migne (PL 183, 1016-1020).`,
  pontos: [
    {
      n: 1,
      texto: `O rei me introduziu na adega e ordenou em mim a caridade (Ct 2,4). Segundo parece dizer a letra deste passo, depois de ter tido, como desejava, uma conversa muito doce e familiar com o amado, a esposa, quando ele se vai, volta às jovenzinhas, tão restaurada e inflamada pela sua vista e pelas suas palavras que parecia embriagada. E, como elas se espantassem com a novidade e perguntassem a causa, respondeu que não era de admirar que estivesse fervendo de vinho quem tinha entrado na adega. Assim, segundo a letra. Segundo o espírito, também não nega que está embriagada; mas de amor, não de vinho — a não ser que o amor é vinho. O rei me introduziu na adega. Quando o esposo está presente e a esposa lhe dirige a palavra, chama-o esposo, ou amado, ou "aquele a quem ama a minha alma"; mas, quando fala dele às jovenzinhas, chama-o rei. Por quê? Creio que porque convém à esposa, que ama e é amada, usar com mais familiaridade, no que lhe toca, os nomes do amor; e as jovenzinhas, como precisam de disciplina, devem ser contidas com o nome venerável da majestade.`
    },
    {
      n: 2,
      texto: `O rei me introduziu na adega. Que adega é esta, deixo de dizer, porque me lembro de já o ter dito. Contudo, se a palavra se referir à Igreja: quando os discípulos, cheios do Espírito Santo, foram tidos pelo povo como embriagados de vinho doce, então Pedro, como amigo do esposo, de pé no meio deles em favor da esposa, disse: Estes não estão embriagados, como pensais. Repara, entretanto, que não negou que estivessem embriagados, mas que estivessem embriagados como eles pensavam. Pois estavam embriagados, sim, mas do Espírito Santo, não de vinho doce. E, como que atestando ao povo que tinham sido verdadeiramente introduzidos na adega, diz de novo Pedro, por todos: Mas isto é o que foi dito pelo profeta Joel: Nos últimos dias, diz o Senhor, derramarei do meu Espírito sobre toda carne, e os vossos filhos e as vossas filhas profetizarão; os vossos jovens verão visões, e os vossos anciãos sonharão sonhos. Não te parece que foi uma adega aquela casa em que os discípulos estavam reunidos, quando de repente veio do céu um ruído, como de um vento impetuoso que chegava, e encheu toda a casa onde estavam sentados, e se cumpriu a profecia de Joel (At 2,2.13-17)? E cada um deles, saindo embriagado da abundância daquela casa e tendo bebido na torrente de tão grande delícia (cf. Sl 35,9), não podia dizer com razão: O rei me introduziu na adega?`
    },
    {
      n: 3,
      texto: `Mas também tu, se, recolhido o teu espírito, com a mente sóbria e livre de cuidados, entras sozinho na casa de oração e, de pé diante de Deus junto a algum dos altares, tocas a porta do céu com a mão do santo desejo e, apresentado aos coros dos santos — pois a tua devoção penetra até lá, já que a oração do justo penetra os céus (cf. Eclo 35,21) —, choras, digno de compaixão, na presença deles, as misérias e calamidades que sofres; se, com frequentes suspiros e gemidos inefáveis (cf. Rm 8,26), expões a tua necessidade e imploras a misericórdia; se, digo, fizeres isto, confio naquele que disse: Pedi e recebereis (Mt 7,7) que, se perseverares batendo, não sairás de mãos vazias. E, quando voltares a nós cheio de graça e de caridade, e não puderes, fervoroso de espírito, esconder o dom recebido, que comunicarás sem inveja; e fores, pela graça que te foi dada, não só agradável a todos, mas talvez até admirável, poderás também tu declarar com verdade: O rei me introduziu na adega; somente cuida de te gloriar, não em ti, mas no Senhor. E não diria que todo dom, ainda que espiritual, sai da adega, pois há junto do esposo outras câmaras e armazéns, que guardam dentro de si dons e carismas diversos, segundo as riquezas da sua glória; dessas câmaras me lembro de ter tratado mais amplamente em outro sermão. Não estão estas coisas guardadas junto de mim, diz, e seladas nos meus tesouros (Dt 32,34)? Conforme a diversidade das câmaras, pois, há diversidade de graças, e a cada um é dada a manifestação do Espírito para proveito comum. E, embora a um seja dada a palavra de sabedoria, a outro a palavra de ciência, a outro a profecia, a outro o dom das curas, a outro a variedade de línguas, a outro a interpretação das línguas, e a outros outras coisas semelhantes (1Cor 12,7-11), nenhum destes, contudo, poderá dizer, por causa de tais dons, que foi introduzido na adega. Pois estas coisas são tiradas de outras câmaras ou tesouros.`
    },
    {
      n: 4,
      texto: `Mas, se alguém obtém, orando, ser arrebatado em espírito até aquele segredo divino de onde logo volta ardendo com grande veemência de amor divino, fervendo de zelo pela justiça e muito fervoroso em todos os empenhos e ofícios espirituais, de modo a poder dizer: O meu coração abrasou-se dentro de mim, e na minha meditação se acende um fogo (Sl 38,4) — esse, quando da abundância da caridade começar a exalar a boa e salutar embriaguez do vinho da alegria, com razão se dirá que entrou na adega. Pois, como há dois arrebatamentos da contemplação bem-aventurada, um no entendimento e outro no afeto, um na luz e outro no fervor, um no conhecimento e outro na devoção, o afeto piedoso, o peito quente de amor, a infusão da santa devoção e também o espírito veemente cheio de zelo não se trazem de outro lugar senão da adega; e todo aquele a quem é dado levantar-se da oração com abundância destas coisas pode dizer com verdade: O rei me introduziu na adega.`
    },
    {
      n: 5,
      texto: `Segue-se: Ordenou em mim a caridade. Muito necessariamente. Pois o zelo sem ciência é insuportável (cf. Rm 10,2). Onde há, pois, zelo veemente, ali é sobretudo necessário o discernimento, que é a ordenação da caridade. O zelo sem ciência sempre se mostra menos eficaz e menos útil; e muitas vezes se sente que é até muito pernicioso. Quanto mais ardente, pois, o zelo, mais veemente o espírito e mais derramada a caridade, tanto mais vigilante deve ser a ciência que contenha o zelo, tempere o espírito, ordene a caridade. Por isso, para que a esposa não seja temida, sobretudo pelas jovenzinhas, como excessiva e insuportável por causa do ímpeto de espírito que parece ter trazido da adega, acrescenta que recebeu também o que é próprio do discernimento, isto é, a ordem da caridade. Pois o discernimento põe ordem em toda virtude; e a ordem dá medida e beleza, e também perpetuidade. Enfim, diz: Pela tua ordenação permanece o dia (Sl 118,91), chamando dia à virtude. O discernimento, pois, não é tanto uma virtude quanto a moderadora e como que o cocheiro das virtudes, o que ordena os afetos e ensina os costumes. Tira-o, e a virtude se tornará vício, e o próprio afeto natural se converterá antes em perturbação e em ruína da natureza. Ordenou em mim a caridade. E isto aconteceu quando, na Igreja, a uns fez apóstolos, a outros profetas, a outros evangelistas, a outros pastores e doutores, para o aperfeiçoamento dos santos (Ef 4,11-12). E é preciso que uma só caridade ligue todos estes e os harmonize na unidade do corpo de Cristo; o que de modo nenhum poderá fazer, se ela mesma não for ordenada. Pois, se cada um se deixar levar pelo seu ímpeto, segundo o espírito que recebeu, e correr indistintamente para tudo o que quiser, conforme se sente movido, e não pelo juízo da razão, então, não se contentando ninguém com o ofício que lhe foi atribuído, mas tentando todos fazer tudo ao mesmo tempo, sem discernimento, não haverá unidade, mas antes confusão.`
    },
    {
      n: 6,
      texto: `Ordenou em mim a caridade. Oxalá o Senhor Jesus ordene também em mim o pouquinho de caridade que me deu, de modo que me importe com tudo o que é dele, mas cuide antes de tudo do que é mais propriamente do meu estado ou ofício; mas de tal modo que, cuidando disto primeiro, me afeiçoe mais a muitas coisas que não me dizem respeito especialmente. Pois nem sempre o que se deve cuidar primeiro é também o que se deve amar mais; muitas vezes o que é primeiro no cuidado é menor na utilidade, e por isso deve ser menor também no afeto. Muitas vezes, pois, o que se antepõe por encargo se pospõe no juízo; e o que a verdade julga dever antepor-se, a ordem da caridade pede que se abrace com mais amor. Por exemplo: não me cabe, por encargo, o cuidado de todos vós? Pois bem: tudo o que eu anteponha a esta obra, de modo a velar menos por ela e a cumpri-la com menos dignidade e proveito, na medida das minhas forças, ainda que talvez pareça fazê-lo por caridade, a razão da ordem não o aprova. E, se me aplico antes de tudo a este cuidado, como devo, mas não me alegro mais com os ganhos maiores de Deus que porventura souber que se fazem por meio de outro, é claro que guardo a ordem da caridade em parte, e em parte não. Mas, se me mostro mais solícito com o que especialmente me cabe e, no entanto, mais afeiçoado ao que é maior, acho-me sem dúvida de ambos os lados de acordo com a ordem da caridade, e não há por que eu também não possa dizer: Ordenou em mim a caridade.`
    },
    {
      n: 7,
      texto: `E, se disseres que é difícil alguém alegrar-se mais com um grande bem alheio do que com um pequeno bem próprio, perceberás sem dúvida, ao menos por isso, a excelência da graça que há na esposa, e que não é qualquer alma que pode dizer: Ordenou em mim a caridade. Por que alguns de vós baixaram o rosto agora, ao ouvir esta palavra? Pois os fundos suspiros atestam a tristeza dos ânimos e o abatimento das consciências. É que, medindo-nos por nós mesmos, alguns de nós sentimos, pela experiência da nossa imperfeição, quão rara virtude é não invejar a virtude alheia — quanto mais alegrar-se com ela, e mais ainda alegrar-se com ela mais do que com a própria, tanto mais quanto cada um se vê superado em virtude. Ainda há pouca luz em nós, irmãos, em todos os que assim nos sentimos. Caminhemos enquanto temos a luz, para que as trevas não nos apanhem (Jo 12,35). Caminhar é progredir. Caminhava o Apóstolo, que dizia: Não julgo tê-lo alcançado; e acrescenta: Mas uma coisa: esquecendo o que fica para trás, lanço-me para o que está adiante (Fl 3,13). Que quer dizer "mas uma coisa"? Uma coisa, diz, como que me restou por remédio, por esperança, por consolação. Qual? Esquecendo o que fica para trás, lançar-me para o que está adiante. Grande confiança! O grande vaso de eleição recusa dizer-se perfeito, e confessa que progride. O perigo não é que as trevas da morte apanhem quem caminha, mas quem está sentado. E quem está sentado, senão quem não se importa de progredir? Guarda-te disso; e, se a morte te surpreender, estarás no refrigério (cf. Sb 4,7). Dirás a Deus: Os teus olhos viram a minha imperfeição; e, no entanto, diz, no teu livro todos serão escritos. Todos quem? Sem dúvida, os que se acham no desejo de progredir. Pois segue-se: Os dias serão formados, e ninguém neles (Sl 138,16) — subentende-se: perecerá. Entende por dias os que progridem, os quais, se a morte os surpreender, hão de ser completados naquilo que lhes falta. Serão formados, e nenhum deles ficará informe.`
    },
    {
      n: 8,
      texto: `E como posso eu progredir, dizes, se tenho inveja do irmão que progride? Se te dói invejar, sentes, mas não consentes. É uma paixão, que um dia há de ser curada, não uma ação que deva ser condenada. Só não te detenhas nela, meditando a iniquidade no teu leito (cf. Sl 35,5) — isto é, pensando como alimentar a doença, satisfazer a peste, perseguir o inocente, caluniando, rebaixando, deturpando o bem que ele fez e impedindo o que há de fazer. De outro modo, não faz mal a quem caminha e se lança para o melhor aquilo que já não é ele que faz, mas o pecado que habita nele (Rm 7,20). Não há, pois, condenação para aquele que não entrega os seus membros como armas à iniquidade (cf. Rm 6,13) — nem a língua para a maledicência, nem nenhuma outra parte do corpo para ferir ou prejudicar de algum modo —, mas antes se envergonha de estar assim mal disposto, e procura expulsar, confessando, chorando, orando, o vício enraizado desde há muito; e, quando não consegue, torna-se por isso mais manso com todos e mais humilde diante de si mesmo. Quem, em são juízo, condenaria o homem que aprendeu do Senhor a ser manso e humilde de coração (Mt 11,29)? Longe de nós que se ache privado da salvação o imitador do Salvador, o esposo da Igreja, nosso Senhor Jesus Cristo, que é Deus acima de todas as coisas, bendito pelos séculos! Amém.`
    }
  ]
});
