SERMOES.sermao({
  id: 'bernardo-cantico-45',
  colecao: 'bernardo-cantico',
  ordem: 45,
  numero: 'XLV',
  titulo: 'Da dupla beleza da alma; de como a alma fala ao Deus-Verbo, e o Verbo à alma, e quais são as suas línguas',
  fonte: 'De duplici pulchritudine animae',
  argumento: `Depois da correção, a recompensa: some o mestre, some o rei, fica o amado, e entre o Verbo e a alma começa uma conversa familiar, "como entre dois vizinhos". O esposo diz duas vezes "eis que és bela" porque há duas belezas: a inocência e a humildade. Humilde depois de pecar é amável; humilde sem ter perdido a inocência é admirável — como Maria. Aqui Bernardo fala de si com uma franqueza comovente: guardou mal a primeira veste, e pede ao menos que lhe seja guardada a segunda.

Os "olhos de pomba" são a simplicidade de quem se contenta com as chagas de Cristo, ou a vista espiritual que nasceu do ouvido. E a esposa responde "eis que és belo, meu amado": viu-o não como Senhor, com temor, como Isaías e Jacó, mas como amado — visão melhor, porque feita no amor. Mas como falam entre si o Verbo e a alma? Cada um tem a sua língua: a do Verbo é o favor da sua bondade; a da alma, o fervor da devoção. O sermão termina num hino à beleza de Cristo nas duas naturezas.

Tradução feita do texto latino de Migne (PL 183, 999-1004).`,
  pontos: [
    {
      n: 1,
      texto: `Eis que és bela, minha amiga, eis que és bela; os teus olhos são de pomba (Ct 1,14). Muito bem, ótimo! Do amor vinha a presunção da esposa; do amor, a indignação do esposo. O desfecho o prova. Pois à presunção seguiu-se a correção; à correção, a emenda; à emenda, a recompensa. Está presente o amado; afasta-se o mestre, desaparece o rei, despe-se a dignidade, deixa-se de lado a reverência. Pois a altivez cede onde o afeto prevalece. E, assim como outrora Moisés falava como um amigo a um amigo (cf. Ex 33,11), e o Senhor lhe respondia, assim também agora entre o Verbo e a alma se trava uma conversa muito familiar, como entre dois vizinhos. E não admira: de uma única fonte de amor corre para ambos o amarem-se um ao outro e o se aquecerem mutuamente. Por isso voam de um lado e de outro palavras mais doces que o mel, e trocam-se olhares cheios de toda suavidade, santos indícios de amor. Enfim, ele a chama amiga, declara-a bela, repete que é bela, e recebe dela, por sua vez, as mesmas coisas. E não é ociosa a repetição, que é confirmação do amor, e talvez indique alguma coisa que se deva investigar.`
    },
    {
      n: 2,
      texto: `Busquemos a dupla beleza da alma, pois é isto que me parece indicar. A beleza da alma é a humildade. Não digo isto por mim mesmo, pois o profeta o disse antes: Tu me aspergirás com o hissopo, e ficarei limpo (Sl 50,9), significando a humildade pela erva baixa que purifica o peito. É com ela que o rei e profeta, depois de uma queda grave, confia ser lavado e assim recuperar uma brancura de neve da inocência. Mas, em quem pecou gravemente, a humildade é amável, mas não admirável. Se, porém, alguém conserva a inocência e, no entanto, lhe junta a humildade, não te parece que possui a dupla beleza da alma? Santa Maria não perdeu a santidade e não careceu de humildade; e por isso o Rei desejou a sua beleza (cf. Sl 44,12), porque ela uniu a humildade à inocência. Enfim: Olhou, diz, para a humildade da sua serva (Lc 1,48). Felizes, pois, os que guardam limpas as suas vestes (cf. Ap 16,15) — isto é, as da simplicidade e da inocência —, contanto que acrescentem vestir também a beleza da humildade. Sem dúvida, a alma que for achada assim ouvirá: Eis que és bela, minha amiga, eis que és bela. Oxalá dissesses ao menos uma vez à minha alma, Senhor Jesus: Eis que és bela! Oxalá me guardes a humildade! Pois a primeira veste eu a guardei mal. Eu sou teu servo (Sl 115,16). Pois não me atrevo a declarar-me amigo, eu que não ouço repetido o testemunho da minha beleza. Basta-me ouvi-lo uma vez. Mas e se até isto estiver em dúvida? Sei o que farei: servo, venerarei a amiga; homenzinho disforme, admirarei nela a beleza acumulada; hei de alegrar-me com a voz do esposo, que admira também ele tão grande beleza. Quem sabe se ao menos por isto acharei graça aos olhos da amiga, para que, pela sua graça, também eu me ache entre os amigos? Enfim, o amigo do esposo está de pé e alegra-se muito com a voz do esposo (Jo 3,29). Eis a sua voz nos ouvidos da amada: ouçamos e alegremo-nos. Estão juntos, conversam um com o outro; fiquemos de pé também nós: que nenhum cuidado do mundo, nenhum atrativo do corpo nos afaste desta conversa.`
    },
    {
      n: 3,
      texto: `Eis que és bela, diz, minha amiga, eis que és bela. "Eis que" é voz de admiração; o resto, de louvor. Com razão é admirável aquela em quem a humildade não veio da santidade perdida, mas foi acolhida pela santidade conservada. Com razão é achada bela aquela a quem não faltou nenhuma das duas belezas. É ave rara na terra não perder a santidade, ou que a santidade não exclua a humildade; e por isso é feliz a que conservou ambas. Enfim, ficou provado: a consciência de nada a acusa, e ela não recusou a correção. Nós, mesmo quando cometemos faltas graves, mal suportamos ser repreendidos; ela, porém, sem ter pecado em nada, ouve com ânimo tranquilo palavras amargas contra si. Pois, se deseja ver a claridade do esposo, que mal há nisso? Antes, é digno de louvor. E, no entanto, repreendida, faz penitência e diz: O meu amado é para mim um ramalhete de mirra; repousará entre os meus peitos (Ct 1,12); isto é: Basta-me; já não quero saber senão Jesus, e Jesus crucificado (cf. 1Cor 2,2). Grande humildade! Inocente nos atos, assume o afeto de penitente; não tem de que se arrepender, e no entanto se arrepende. Por que foi então repreendida, perguntas, se não fez mal nenhum? Ouve agora o desígnio e a prudência do esposo. Assim como outrora foi posta à prova a obediência de Abraão, assim agora a humildade da esposa. E, assim como ele, cumprida a obediência, ouviu então: Agora sei que temes a Deus (Gn 22,12), assim também a ela se diz agora, como que com outras palavras: Agora sei que és humilde; pois é isto que quer dizer: Eis que és bela. E por isso repete o elogio, para assinalar que à glória da santidade se juntou a beleza da humildade. Eis que és bela, minha amiga, eis que és bela. Agora sei que és bela, não só pelo meu amor, mas também pela tua humildade. Não digo agora bela entre as mulheres, nem bela nas faces, nem no pescoço, como dizia antes; mas declaro-te bela simplesmente — não bela por comparação, não com restrição, não em parte.`
    },
    {
      n: 4,
      texto: `E acrescenta: Os teus olhos são de pomba. Ainda aqui se louva claramente a humildade. Pois refere-se a isto: que ela, repreendida pela sua alta indagação, não hesitou em descer logo a coisas mais simples, a ponto de dizer: O meu amado é para mim um ramalhete de mirra. Há, sem dúvida, grande distância entre o rosto da glória e um ramalhete de mirra; e por isso é grande sinal de humildade aceitar ser chamada de lá para cá. Os teus olhos, pois, são de pomba. Já não andas, diz, em coisas grandes, nem em maravilhas acima de ti (cf. Sl 130,1); mas, como a ave simplicíssima, contentas-te com coisas mais simples, fazendo o ninho nas fendas da rocha (cf. Ct 2,14), demorando-te nas minhas chagas, e contemplando de bom grado, com olho de pomba, só o que é de mim encarnado e padecente.`
    },
    {
      n: 5,
      texto: `Ou então, porque o Espírito Santo apareceu na forma desta ave (Mt 3,16), louva-se nela, com o nome de pomba, um olhar mais espiritual do que simples. E, se isto te agrada, deves referir este passo àquilo que pouco antes os companheiros lhe prometeram: fazer-lhe brincos de ouro (Ct 1,10) — não pretendendo, como então ensinei, enfeitar as orelhas do corpo, mas formar o ouvido do coração. Pôde, pois, acontecer que, purificado mais o coração pela fé, que vem pelo ouvido, ela se tornasse mais preparada para ver o que antes não podia. E, como pareceu que, com os brincos recebidos, tinha progredido para uma vista mais aguda, rumo ao entendimento espiritual, agradou ao esposo, a quem sempre agrada mais, quanto dele depende, ser visto em espírito; e, contando também isto entre os seus louvores, diz: Os teus olhos são de pomba. Contempla-me agora, diz, em espírito, porque o Cristo Senhor é um espírito diante da tua face (Lm 4,20). E tens com que o fazer, porque os teus olhos são de pomba. Antes não tinhas, e por isso tiveste de ser contida; mas agora tem a possibilidade de ver, porque os teus olhos são de pomba, isto é, espirituais. Não, certamente, a possibilidade que pedias — pois ainda agora não és capaz daquela —, mas uma que possa bastar-te entretanto. Deves ser conduzida de claridade em claridade (cf. 2Cor 3,18); e por isso vê agora como podes; e, quando puderes mais, verás mais.`
    },
    {
      n: 6,
      texto: `Não julgo, irmãos, não julgo que esta visão seja medíocre nem comum a todos, ainda que seja inferior àquela com que ele há de ser visto no futuro. Reparai, enfim, pelo que se segue. Pois segue-se: Eis que és belo, meu amado, eis que és belo (Ct 1,15). Vês a que altura está e quão alto elevou o cume da mente aquela que reivindica para si, como coisa sua, o Senhor do universo como amado. Repara, com efeito, como não diz simplesmente: Amado; mas: Meu amado, para o designar como seu. Grande visão, sem dúvida, a partir da qual ela cresceu até tal confiança e autoridade que, no Senhor de todos, não conhece o senhor, mas o amado. Pois julgo que desta vez não lhe foram apresentadas aos sentidos imagens da carne, ou da cruz, ou quaisquer outras semelhanças de fraquezas corporais. Pois nelas, segundo o profeta, não havia nele aparência nem beleza (Is 53,2). Ela, porém, depois de o contemplar, declara-o agora belo e formoso, dando a entender que ele lhe apareceu numa visão melhor. Pois fala com a esposa boca a boca, como outrora com o santo Moisés (cf. Nm 12,8); e ela vê a Deus às claras, não por enigmas e figuras. Enfim, declara-o com a boca tal como o contempla com a mente, numa visão verdadeiramente sublime e suave. Os seus olhos viram o rei na sua beleza (cf. Is 33,17) — não, porém, como rei, mas como amado. Tenha-o visto um sobre um trono alto e elevado; e tenha outro atestado que lhe apareceu face a face: a mim, contudo, parece-me que a superioridade, neste ponto, está do lado da esposa, porque ali se lê que foi visto o Senhor; aqui, o amado. Pois tens assim: Vi o Senhor sentado sobre um trono alto e elevado (Is 6,1); e ainda: Vi o Senhor face a face, e a minha alma foi salva (Gn 32,30). Mas, se eu sou Senhor, diz, onde está o temor que me é devido (Ml 1,6)? E, se a eles foi feita a revelação com temor — porque onde está o Senhor, está o temor —, eu, sem dúvida, se me dessem a escolher, abraçaria a visão da esposa com tanto mais gosto e tanto mais carinho quanto vejo que foi feita num afeto melhor, que é o amor. Pois o temor supõe castigo, e a caridade perfeita lança fora o temor (1Jo 4,18). Há, sem dúvida, muita diferença entre aparecer terrível nos seus desígnios sobre os filhos dos homens (Sl 65,5) e aparecer o mais belo dos filhos dos homens (Sl 44,3). Eis que és belo, meu amado, e formoso. Estas palavras soam claramente a amor, não a temor.`
    },
    {
      n: 7,
      texto: `Mas talvez te subam ao coração pensamentos (cf. Lc 24,38), e perguntes a ti mesmo, em dúvida: Com que razão se relatam palavras do Verbo dirigidas à alma, e da alma ao Verbo, de modo que ela ouviu a voz de quem lhe falava e afirmava que ela era bela, e logo devolveu o mesmo elogio a quem a louvava? Como podem acontecer estas coisas (cf. Jo 3,9)? Pois é com a palavra que nós falamos; a palavra não fala. Do mesmo modo, a alma não tem com que falar, se a boca do corpo não lhe formar as palavras para falar. Perguntas bem; mas repara que quem fala é o espírito, e que o que se diz se deve entender espiritualmente. Por isso, sempre que ouves ou lês que o Verbo e a alma conversam e se olham um ao outro, não imagines que se trocam vozes corporais, como também não aparecem imagens corporais dos que conversam. Ouve antes o que deves pensar em coisas assim. O Verbo é espírito, e a alma é espírito; e têm as suas línguas, com que falam um ao outro e se dão a conhecer presentes. A língua do Verbo é o favor da sua bondade; a da alma, o fervor da devoção. A alma que não tem esta língua é muda, como criança que ainda não fala, e não pode de modo nenhum conversar com o Verbo. Quando, pois, o Verbo move esta sua língua, querendo falar à alma, a alma não pode deixar de o sentir. Pois a palavra de Deus é viva e eficaz, e mais penetrante que qualquer espada de dois gumes, e chega até a divisão da alma e do espírito (Hb 4,12). E, por sua vez, quando a alma move a sua, muito menos pode isso escapar ao Verbo; não só porque está presente em toda parte, mas sobretudo porque, se ele não a estimular, a língua da devoção de modo nenhum se move para falar.`
    },
    {
      n: 8,
      texto: `Para o Verbo, pois, dizer à alma: És bela, e chamá-la amiga, é infundir-lhe com que ame e com que confie em ser amada. E para ela, por sua vez, chamar ao Verbo amado e declará-lo belo é atribuir-lhe, sem fingimento nem engano, o amar e o ser amada, e admirar a sua bondade e pasmar diante da graça. Pois a beleza dele é o seu amor; e é tanto maior quanto se antecipa. Por isso, com o íntimo do coração e com as vozes dos afetos mais profundos, ela proclama tanto mais e com tanto mais ardor que ele deve ser amado, quanto primeiro o sentiu a amar do que amado. Assim, o falar do Verbo é a infusão do dom; a resposta da alma é a admiração com ação de graças. E ama mais porque se sente vencida no amor; e admira mais porque se reconhece antecipada. Por isso não se contenta em dizer uma vez belo, mas repete também formoso, designando com esta repetição a excelência da beleza.`
    },
    {
      n: 9,
      texto: `Ou então, nas duas substâncias de Cristo, exprimiu uma beleza digna de toda admiração: numa, a da natureza; na outra, a da graça. Quão belo és para os teus anjos, Senhor Jesus, na forma de Deus, no dia da tua eternidade, gerado entre os esplendores dos santos antes da estrela da manhã (cf. Sl 109,3), esplendor e figura da substância do Pai (cf. Hb 1,3), e brancura perpétua e sem artifício nenhum da vida eterna (cf. Sb 7,26)! Quão formoso és para mim, meu Senhor, no próprio despojamento desta tua beleza! Pois, onde te esvaziaste, onde despiste a luz indefectível dos seus raios naturais, ali brilhou mais a piedade, ali resplandeceu mais a caridade, ali irradiou mais a graça. Quão clara nasces para mim, Estrela de Jacó (Nm 24,17)! Quão luminosa sais, Flor da raiz de Jessé (Is 11,1)! Com que luz alegre me visitaste nas trevas, Sol nascente que vens do alto (Lc 1,78)! Quão admirável e assombroso até para as Potestades do alto, na tua concepção pelo Espírito, no teu nascimento da Virgem, na inocência da vida, nas torrentes da doutrina, no fulgor dos milagres, na revelação dos mistérios! Enfim, com que fulgor, depois do ocaso, ressurges do coração da terra, Sol da justiça! Quão formoso na tua veste (cf. Is 63,1), Rei da glória, te recolhes por fim às alturas dos céus! Como não dirão todos os meus ossos, por todas estas coisas: Senhor, quem é semelhante a ti (Sl 34,10)?`
    },
    {
      n: 10,
      texto: `Pensa, pois, que a esposa, contemplando o amado, reparou nestas coisas e noutras semelhantes, quando dizia: Eis que és belo, meu amado, e formoso. E não só nestas, mas sem dúvida também em alguma coisa da beleza da natureza superior, que ultrapassa de todo o nosso olhar e escapa à nossa experiência. A repetição, pois, designou a beleza de uma e de outra substância. Ouve, depois, como ela dança de alegria à vista e às palavras do amado, e diante dele canta, cheia de júbilo, num canto nupcial, as coisas do amor. Pois segue-se: O nosso leito é florido, as vigas das nossas casas são de cedro, os nossos tetos de cipreste (Ct 1,15-16). Mas guardemos o canto da esposa para um novo princípio, para que também nós, mais dispostos pelo descanso, exultemos e nos alegremos nele com mais liberdade, para louvor e glória do seu esposo, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
