SERMOES.sermao({
  id: 'bernardo-cantico-47',
  colecao: 'bernardo-cantico',
  ordem: 47,
  numero: 'XLVII',
  titulo: 'Da tríplice flor — a virgindade, o martírio e a boa obra — e da devoção que se deve ter no ofício divino',
  fonte: 'De triplici flore',
  argumento: `A esposa elogiou o leito florido; o esposo responde: "Eu sou a flor do campo", para que ela saiba de onde vêm as flores de que se gloria. Bernardo distingue então três lugares da flor: o quarto, onde as flores cortadas murcham e precisam ser sempre renovadas, como as boas obras; o jardim, cultivado e fechado, como a virgindade; e o campo, aberto a todos e florido sem trabalho humano, como o martírio, e como Cristo, nascido sem semente de homem e sem conhecer a corrupção. Cristo é as três flores, mas chama-se flor do campo para animar a esposa, que sempre deseja o repouso, a aceitar o combate: ele é ao mesmo tempo o modelo de quem luta e o prêmio de quem vence. E é o lírio dos vales, porque a sua glória será a coroa dos humildes.

O sermão termina de modo muito concreto: chegou a hora do Ofício, e "nada se deve antepor à obra de Deus". Bernardo pede aos monges que cantem com vigor, sem cochilar, sem engolir palavras nem cantar pelo nariz, e com pureza, sem pensar em outra coisa — nem sequer nas boas leituras do claustro ou no sermão que acabaram de ouvir.

Tradução feita do texto latino de Migne (PL 183, 1008-1012).`,
  pontos: [
    {
      n: 1,
      texto: `Eu sou a flor do campo e o lírio dos vales (Ct 2,1). Julgo que isto se refere ao elogio que a esposa tinha feito do leito salpicado de flores. Para que ela não atribuísse a si aquelas flores com que o leito parecia adornado e o quarto embelezado, o esposo acrescenta que ele é a flor do campo; que as flores não nascem do quarto, mas do campo; e que é por dom seu e por participação nele que acontece o que brilha e o que perfuma. Para que ninguém a pudesse censurar e dizer: Que tens que não recebeste? E, se recebeste, por que te glorias como se não tivesses recebido (1Cor 4,7)?, ele mesmo, amante apaixonado e ao mesmo tempo mestre benigno, mostra à sua amada, com piedade e bondade, a quem deve atribuir o brilho de que se gloriava e o perfume do leito. Eu sou a flor do campo, diz: é de mim que vem aquilo de que te glorias. Também por este passo somos advertidos de modo muito salutar de que de nenhum modo convém gloriar-se; e, se alguém se gloria, glorie-se no Senhor (2Cor 10,17). Isto segundo a letra; investiguemos agora, com a ajuda daquele de quem se fala, o sentido espiritual que nela se esconde.`
    },
    {
      n: 2,
      texto: `E repara primeiro comigo em três estados da flor: no campo, no jardim, no quarto; para que depois se descubra mais facilmente por que escolheu chamar-se de preferência flor do campo. No campo e no jardim a flor nasce; no quarto, não. Perfuma e brilha nele, mas não ereta e de pé, como no jardim ou no campo, e sim deitada, como coisa que foi trazida, e não que ali nasceu. Por isso é preciso renová-las muitas vezes e pôr sempre flores mais frescas, porque não conservam por muito tempo o seu perfume nem a sua beleza. E se, como disse no outro sermão, o leito salpicado de flores é a consciência cheia de boas obras, vês sem dúvida, para manter a comparação, que de modo nenhum basta fazer o bem uma ou duas vezes, se não acrescentares sem cessar obras novas às primeiras, para que, semeando em bênçãos, também colhas bênçãos (cf. 2Cor 9,6). De outro modo, a flor da boa obra jaz e murcha, e em pouco tempo perde todo o brilho e todo o vigor, se não for continuamente renovada por outras e outras obras de piedade lançadas por cima. Isto, no quarto.`
    },
    {
      n: 3,
      texto: `No jardim, porém, não é assim; nem tampouco no campo. Pois às flores que uma vez produziram de si fornecem continuamente com que a sua beleza inata perdure por muito tempo. Diferem, contudo, também entre si: o jardim, para florir, é cultivado pela mão e pela arte dos homens; o campo, porém, produz flores naturalmente, por si mesmo, sem ajuda nenhuma do cuidado humano. Não te parece já perceber que campo é aquele, nem sulcado pelo arado, nem cavado pela enxada, nem adubado com esterco, nem semeado pela mão do homem, e, no entanto, honrado com aquela flor nobre sobre a qual, como é certo, repousou o Espírito do Senhor (cf. Is 11,2)? Eis, diz, o cheiro do meu filho, como o cheiro de um campo fértil que o Senhor abençoou (Gn 27,27). Aquela flor do campo ainda não se tinha revestido da sua forma, e já dava o seu perfume, quando o santo e velho Patriarca, murcho no corpo, turvo na vista, mas agudo no olfato, a pressentiu em espírito, a ponto de exclamar isto de alegria. Não devia, pois, declarar-se flor do quarto, ele que é flor sempre viçosa; nem tampouco do jardim, para que não parecesse gerado por obra humana. Mas com beleza e muita propriedade diz: Sou a flor do campo, ele que nasceu sem indústria humana, e sobre quem, uma vez nascido, nenhuma corrupção teve domínio depois, para que se cumprisse a palavra que disse: Não deixarás o teu Santo ver a corrupção (Sl 15,10).`
    },
    {
      n: 4,
      texto: `Mas, se te agrada, recebe também outra razão disto, que, a meu ver, não é de desprezar. Pois não é sem razão que o Sábio descreve o espírito como múltiplo (cf. Sb 7,22), senão porque costuma esconder muitas vezes, sob uma única casca da letra, sentidos diversos da sabedoria. Assim, segundo a divisão acima dos estados da flor, flor é a virgindade, flor é o martírio, flor é a boa obra. No jardim, a virgindade; no campo, o martírio; no quarto, a boa obra. E bem está a virgindade no jardim, porque lhe é familiar o pudor, que foge do público, se alegra com os esconderijos e aceita a disciplina. Enfim, no jardim a flor está fechada; no campo, exposta; no quarto, espalhada. E tens: Jardim fechado, fonte selada (Ct 4,12). O que significa na virgem a clausura do pudor e a guarda da santidade inviolada — contanto que seja tal que seja santa no corpo e no espírito (cf. 1Cor 7,34). E bem está o martírio no campo, pois os mártires são expostos à zombaria de todos, feitos espetáculo para os anjos e para os homens (cf. 1Cor 4,9). Não é deles a voz digna de compaixão do salmo: Tornamo-nos o opróbrio dos nossos vizinhos, zombaria e escárnio dos que estão ao nosso redor (Sl 78,4)? E bem está no quarto a boa obra, que torna a consciência tranquila e segura. Enfim, depois da boa obra dorme-se com mais segurança na contemplação; e alguém se põe a contemplar e investigar as coisas sublimes com tanto mais confiança quanto mais tem consciência de não ter faltado às obras da caridade por amor do seu próprio repouso.`
    },
    {
      n: 5,
      texto: `E todas estas coisas, de algum modo, é o Senhor Jesus. Ele é a flor do jardim: virgem, rebento nascido de uma virgem. Ele mesmo é a flor do campo: mártir, coroa dos mártires, modelo do martírio. Enfim, foi levado para fora da cidade, sofreu fora do acampamento (cf. Hb 13,12-13), foi levantado no madeiro, para ser visto pelos homens e escarnecido por todos. Ele é também a flor do quarto, espelho e exemplo de toda beneficência, como ele mesmo declarou aos judeus, dizendo: Mostrei-vos muitas boas obras da parte do meu Pai (Jo 10,32); e também a Escritura diz dele: Passou fazendo o bem e curando a todos (At 10,38). Se, pois, o Senhor é estas três coisas, por que razão preferiu, das três, chamar-se flor do campo? Sem dúvida para animar à paciência aquela a quem sabia que ameaçava a perseguição, se quisesse viver piedosamente em Cristo (cf. 2Tm 3,12). Declara-se, pois, de melhor vontade aquilo em que sobretudo quer tê-la por seguidora; e é o que eu disse em outra ocasião: ela deseja sempre o repouso, e ele a incita ao trabalho, anunciando-lhe que é preciso entrar no reino dos céus através de muitas tribulações (At 14,21). Por isso, quando se dispunha a voltar para o Pai, dizia à Igreja, nova na terra e recém-desposada: Vem a hora em que todo aquele que vos matar julgará prestar culto a Deus (Jo 16,2); e ainda: Se me perseguiram, diz, também vos perseguirão (Jo 15,20). Também tu podes colher no Evangelho muitas passagens semelhantes a este anúncio dos males que se hão de suportar.`
    },
    {
      n: 6,
      texto: `Eu sou a flor do campo e o lírio dos vales. Ela mostra o leito; ele chama para o campo, provoca ao exercício. Não julga que haja nada mais persuasivo para a levar a entrar no combate do que propor-se a si mesmo como exemplo ou como prêmio de quem combate. Eu sou a flor do campo. Nesta palavra pode entender-se uma coisa ou outra: que ele é o modelo de quem luta, ou a glória de quem triunfa. Tu és para mim uma e outra coisa, Senhor Jesus: espelho do sofrer e prêmio de quem sofre. Uma e outra provocam com força e acendem com veemência. Tu adestras as minhas mãos para a batalha (cf. Sl 143,1) com o exemplo da tua fortaleza; tu, depois da vitória, coroas a minha cabeça com a presença da tua majestade. Quer porque te contemplo a lutar, quer porque te espero não só como quem coroa, mas como a própria coroa, em ambos me atrais admiravelmente a ti; ambos são cordas fortíssimas para arrastar. Atrai-me atrás de ti (cf. Ct 1,3): sigo-te de boa vontade, e de melhor vontade gozo de ti. Se és tão bom, Senhor, para os que te seguem, como serás para os que te alcançam? Eu sou a flor do campo. Quem me ama venha ao campo; não se recuse a entrar no combate comigo e por mim, para poder dizer: Combati o bom combate (2Tm 4,7).`
    },
    {
      n: 7,
      texto: `E, como não são os soberbos ou arrogantes, mas antes os humildes, que não sabem presumir de si, os aptos para o martírio, acrescenta que é também o lírio dos vales, isto é, a coroa dos humildes, designando pela excelência desta flor a glória especial da sua futura exaltação. Pois virá o tempo em que todo vale será aterrado, e todo monte e colina serão rebaixados (Is 40,4); e então aparecerá aquela brancura da vida eterna, o lírio, não das colinas, mas dos vales. O justo germinará como o lírio, diz (Os 14,6). Quem é justo, senão o humilde? Enfim, quando o Senhor se inclinava sob as mãos do seu servo, o Batista, e este se assustava diante da majestade, diz: Deixa; pois assim nos convém cumprir toda justiça (Mt 3,15) — pondo, sem dúvida, a consumação da justiça na perfeição da humildade. O justo, pois, é humilde; o justo é vale. E, se formos achados humildes, também nós germinaremos como o lírio e floresceremos eternamente diante do Senhor. Não se mostrará ele verdadeiramente lírio dos vales, sobretudo então, quando transformar o corpo da nossa humildade, tornando-o semelhante ao corpo da sua glória (Fl 3,21)? Não diz: o nosso corpo, mas: o corpo da nossa humildade, para dar a entender que só os humildes serão iluminados pela brancura admirável e eterna deste lírio. E isto baste quanto ao esposo ter declarado que é a flor do campo e o lírio dos vales.`
    },
    {
      n: 8,
      texto: `Seria bom ouvir agora também o que em seguida declara da sua caríssima; mas a hora não o permite. Pois, segundo a nossa Regra, não é lícito antepor nada à obra de Deus. O Pai Bento quis que se desse este nome às solenidades de louvor que todos os dias se prestam a Deus no oratório precisamente para mostrar mais claramente com quanta atenção queria que nos dedicássemos a esta obra. Por isso vos advirto, caríssimos, a tomar parte sempre nos louvores divinos com pureza e com vigor. Com vigor, para que estejais diante do Senhor tanto com reverência como com prontidão: não preguiçosos, não sonolentos, não bocejando, não poupando a voz, não cortando as palavras pela metade, não saltando palavras inteiras, não soando com vozes quebradas e frouxas, balbuciando pelo nariz alguma coisa de efeminado, mas proferindo as palavras do Espírito Santo, como é digno, com som e afeto viris. Com pureza, para que, enquanto salmodiais, não penseis em outra coisa senão no que salmodiais. E não digo que se devam evitar só os pensamentos vãos e ociosos: devem-se evitar também — ao menos naquela hora e naquele lugar — aqueles que os irmãos encarregados de ofícios são muitas vezes obrigados a admitir, como que por necessidade, pelas necessidades da comunidade. E nem sequer aconselharia admitir então aquilo que talvez pouco antes tenhais lido nos livros, sentados no claustro, ou o que agora levais fresco deste auditório do Espírito Santo, enquanto vos falo de viva voz. São coisas salutares, mas não é salutar revolvê-las enquanto salmodiais. Pois o Espírito Santo não recebe com agrado, naquela hora, qualquer outra coisa que ofereças que não seja a devida, negligenciando o que deves. Possamos sempre fazer a sua vontade, segundo a sua vontade e por sua inspiração, pela graça e misericórdia do esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
