SERMOES.sermao({
  id: 'bernardo-cantico-14',
  colecao: 'bernardo-cantico',
  ordem: 14,
  numero: 'XIV',
  titulo: 'Da Igreja dos cristãos fiéis e da Sinagoga dos judeus infiéis',
  fonte: 'De Ecclesia fidelium Christianorum; et de Synagoga Judaeorum',
  argumento: `Uma alegoria do encontro entre a Igreja vinda das nações e a Sinagoga, armada sobre a parábola do filho pródigo e a dos trabalhadores da vinha. A Sinagoga pede juízo e o recebe; a Igreja pede misericórdia e a recebe. Bernardo insiste, porém, em que a rejeição é parcial e temporária: o Senhor não rejeitará o seu povo para sempre, e há de salvar o resto.

No ponto 6 vem a confissão mais pessoal do livro até aqui. Bernardo conta o frio de coração dos seus primeiros anos de conversão, e como bastava a palavra — ou a simples lembrança — de um homem espiritual para que soprasse o espírito e corressem as águas. E conta também a vergonha que isso lhe dava.

Tradução feita do texto latino de Migne (PL 183, 839-843).`,
  pontos: [
    {
      n: 1,
      texto: `Deus é conhecido na Judeia; grande é o seu nome em Israel (Sl 75,2). O povo das nações, que andava nas trevas, viu uma grande luz (Is 9,2) — a que estava na Judeia e em Israel — e quis aproximar-se e ser iluminado, para que, não sendo povo outrora, fosse agora povo (1Pd 2,10); e para que uma só pedra angular recebesse em si as duas paredes que vinham de lados opostos, e daí em diante o seu lugar fosse na paz (Sl 75,3). E dava confiança a voz de quem convidava, e que já se ouvira: Alegrai-vos, nações, com o seu povo (Dt 32,43; Rm 15,10). Quis, pois, aproximar-se; mas a Sinagoga o proibiu, declarando imunda e indigna a Igreja vinda das nações, lançando-lhe em rosto a borra da idolatria e a cegueira da ignorância, e dizendo: E tu, com que mérito? Não me toques. Por quê?, responde a outra. Acaso Deus é só dos judeus? Não é também das nações? (Rm 3,29) E, se a mim falta mérito, a ele não falta compaixão. Porventura ele é apenas justo? É também misericordioso. Senhor, venham sobre mim as tuas compaixões, e viverei; e ainda: Muitas são as tuas misericórdias, Senhor; vivifica-me segundo o teu juízo (Sl 118,77.156) — juízo que, assim temperado, é misericórdia. Que fará o Senhor justo e misericordioso, quando uma se gloria na lei, se aplaude pela própria justiça, não precisa de misericórdia e ainda despreza aquela que precisa; e a outra, do lado oposto, reconhece as próprias faltas, confessa a sua indignidade, recusa o juízo e implora a misericórdia? Que fará, digo, o juiz — e um juiz a quem julgar e compadecer-se são de tal modo próprios que nenhum dos dois lhe é mais próprio que o outro? Que poderia haver de mais conveniente do que receber cada uma segundo o que pediu: aquela o juízo, esta a misericórdia? O judeu pede juízo: tenha-o; e as nações glorifiquem a Deus pela sua misericórdia (Rm 15,9). E o juízo é este: que os que desprezam a justiça misericordiosa de Deus e querem estabelecer a sua própria — que não justifica, mas acusa — sejam entregues a essa mesma justiça sua, para serem por ela esmagados antes que justificados.`
    },
    {
      n: 2,
      texto: `É que ela vem da lei, que nunca levou ninguém à perfeição; é um jugo que nem eles nem os seus pais jamais puderam carregar (At 15,10). Mas a Sinagoga é forte: não faz caso do fardo leve nem do jugo suave. Está sã: não precisa de médico nem da unção do Espírito. Confia na lei: que esta a livre, se puder. Mas não foi dada uma lei capaz de vivificar (Gl 3,21); pelo contrário, ela mata: porque a letra mata (2Cor 3,6). Por isso, diz ele, eu vos digo: morrereis nos vossos pecados (Jo 8,24). Este é, pois, ó Sinagoga, o juízo que reclamas para o teu erro. Cega e litigiosa, ficas abandonada até que entre a plenitude das nações (Rm 11,25) — as mesmas que na tua soberba desprezas e na tua inveja repeles — e até que também ela reconheça aquele Deus que é conhecido na Judeia, e que grande é o seu nome em Israel. Pois foi para um juízo que Jesus veio a este mundo: para que os que não veem vejam, e os que veem fiquem cegos (Jo 9,39). Mas em parte apenas: porque o Senhor não rejeitará o seu povo (Sl 93,14) por inteiro, guardando para si, como semente, os apóstolos e a multidão dos que creram, cujo coração era um só e uma só a alma (At 4,32). E nem o rejeitará para sempre: há de salvar o resto. Pois de novo acolherá Israel, seu servo, e se lembrará da sua misericórdia (Lc 1,54); de modo que nem ali a misericórdia deixará de acompanhar o juízo — ali mesmo onde ela não achou lugar algum. Do contrário, se tivesse recebido segundo os méritos, teria sido juízo sem misericórdia para quem não usa de misericórdia (Tg 2,13). A Judeia tem muito óleo do conhecimento divino, e o retém com avareza, fechado em si como num vaso. Peço, e ela não se compadece nem empresta. Quer possuir sozinha o culto de Deus, sozinha o conhecimento dele, sozinha o seu grande nome; e não é zelo pelo que é seu: é inveja do que seria meu.`
    },
    {
      n: 3,
      texto: `Julga tu, pois, Senhor, a minha causa, e seja ainda mais engrandecido o teu grande nome, e multiplique-se ainda mais o óleo, que já é muito. Cresça, transborde, derrame-se, corra também para as nações, e toda carne conheça a salvação de Deus (Lc 3,6). Por que há de a unção salutar ficar toda na barba de Arão, como quer o judeu ingrato? Ela não é da barba, mas da cabeça; e a cabeça não é só da barba: é do corpo inteiro. Que a barba receba primeiro, pois, mas não sozinha. Derrame também sobre os membros inferiores aquilo que ela recebeu do alto. Desça, desça também até os peitos da Igreja o licor do alto — que ela, ávida, não se envergonha de espremer da barba para si; e, banhada pelo orvalho da graça, diga, para se mostrar não ingrata: Óleo derramado é o teu nome (Ct 1,2). Mas que transborde ainda, peço, e chegue até a orla da veste (Sl 132,2) — isto é, até mim, o último de todos e o mais indigno, mas ainda assim parte da veste. Pois também eu o reclamo dos peitos maternos, como pequenino em Cristo, e com pleno direito de filho. E, se murmurar aquele cujo olho é mau porque o outro é bom (Mt 20,15), responde tu por mim, Senhor: saia do teu rosto a sentença a meu respeito (Sl 16,2), e não do sobrolho de Israel. Ou antes, responde por ti mesmo e dize ao caluniador — pois é a ti que ele calunia, por dares de graça —; dize-lhe, pois: Quero dar também a este último o mesmo (Mt 20,14). Não agrada ao fariseu. Que resmungas? O meu direito é a vontade do juiz. Que há de mais justo para o mérito, que há de mais rico para o prêmio? Não lhe é lícito fazer o que quer? A mim faz-se misericórdia; a ti não se faz injustiça nenhuma. Toma o que é teu e vai-te. Se ele decidiu salvar-me também a mim, que perdes tu?`
    },
    {
      n: 4,
      texto: `Exagera quanto quiseres os méritos e exalta os suores: melhor é a misericórdia do Senhor do que as vidas (Sl 62,4). Confesso: não aguentei o peso do dia e o calor; mas carrego, conforme apraz ao pai de família, um jugo suave e um fardo leve. A minha obra mal é de uma hora; e, se é mais, o amor não me deixa senti-lo. Que o judeu exercite as próprias forças; a mim agrada-me provar qual é a vontade de Deus, boa, agradável e perfeita (Rm 12,2). É com ela que compenso o que me falta de obra e de tempo. Ele apoia-se num contrato ajustado; eu, no beneplácito de uma vontade. Creio — e não é insensatez —, pois na vontade dele está a vida (Sl 29,6). É ela que me reconcilia com o Pai, é ela que me devolve a herança, e com graça ainda mais abundante; é ela que desperta para mim a música, os cantos, o banquete e a alegria festiva de toda a casa em júbilo. Se o meu irmão mais velho se indigna — ele, que prefere comer um cabrito com os amigos lá fora a comer comigo, na casa do pai, o novilho cevado —, hão de responder-lhe: Era preciso fazer festa e alegrar-se, porque este meu filho estava morto e reviveu; tinha-se perdido e foi encontrado (Lc 15,32). Ainda agora a Sinagoga janta lá fora com os seus amigos, os demônios, a quem muito agrada que ela, insensata, devore o cabrito do pecado engolindo-o inteiro e de certo modo escondendo-o, guardando-o para si no ventre da sua torpeza e da sua insensatez — enquanto, desprezando a justiça de Deus e querendo estabelecer a sua própria, diz não ter pecado e não precisar da morte do novilho cevado, julgando-se pura e justa pelas obras da lei. Mas a Igreja, rasgado o véu da letra que mata na morte do Verbo crucificado, irrompe com ousadia até o santuário dele, precedida pelo espírito de liberdade; é reconhecida, agrada, toma o lugar da rival, torna-se esposa e goza dos abraços que lhe arrebatou. E, unindo-se no calor do espírito a Cristo Senhor, a quem se aperta, e correndo dele por toda parte, gota a gota, o óleo da sua exultação, ela o recebe mais que os seus companheiros (Sl 44,8) e diz: Óleo derramado é o teu nome. Que há de admirar que seja ungida aquela que abraça o Ungido?`
    },
    {
      n: 5,
      texto: `A Igreja, portanto, está à mesa lá dentro — mas, por ora, a Igreja dos perfeitos. Há esperança, contudo, também para nós. Fiquemos de sentinela à porta, nós, os menos perfeitos, alegres na esperança (Rm 12,12). Que o esposo e a esposa fiquem sós lá dentro e gozem dos abraços mútuos e secretos, sem o ruído dos desejos da carne e sem o tumulto perturbador das imagens do corpo. Mas o bando das jovenzinhas, que ainda não conseguem estar sem essas inquietações, espere lá fora; e espere sem receio, sabendo que lhe diz respeito aquilo que leem: Serão levadas ao rei as virgens que a seguem; as suas companheiras serão apresentadas a ti (Sl 44,15). E, para que cada uma saiba de que espírito é: chamo virgens àquelas que, unidas a Cristo antes de manchadas pelos abraços do mundo, perseveram com firmeza junto daquele a quem tanto mais felizmente se consagraram quanto mais cedo o fizeram; e chamo companheiras àquelas que, envergonhando-se enfim da sua antiga deformidade — quando, conformadas a este mundo, se prostituíam torpemente aos príncipes do mundo, isto é, aos espíritos imundos, em toda concupiscência carnal —, saem dela e se apressam a refazer-se segundo a forma do homem novo, com tanto mais sinceridade quanto mais tarde chegaram. Umas e outras avancem, pois, e não desfaleçam nem se cansem, ainda que não sintam ainda em si plenamente aquilo que lhes permitiria dizer também: Óleo derramado é o teu nome. Pois as jovenzinhas não ousam dirigir a palavra ao esposo por si mesmas. Mas, se procurarem seguir de mais perto as pegadas da mestra, ao menos se deleitarão com o odor do óleo derramado; e o próprio odor as moverá a desejar e a buscar coisas maiores.`
    },
    {
      n: 6,
      texto: `Muitas vezes eu mesmo — e não me envergonho de o confessar —, sobretudo no começo da minha conversão, estava duro e frio de coração e procurava aquele a quem a minha alma quisesse amar; pois ainda não podia amar a quem não tinha encontrado, ou ao menos amava menos do que queria, e por isso o procurava, para amar mais — e de modo nenhum o procuraria se já não o amasse de alguma forma. Enquanto, pois, eu o procurava, para que o meu espírito, entorpecido e lânguido, se aquecesse e descansasse nele; e não aparecia de parte alguma quem me socorresse, quem dissolvesse aquele inverno duro que nos travava os sentidos e fizesse voltar a suavidade da primavera e a amenidade espiritual — então a minha alma ia desfalecendo cada vez mais, enfadava-se e adormecia; e, de tédio, triste e quase desesperada, murmurava consigo: Quem poderá resistir diante deste frio? (Sl 147,17) E então, de repente, à palavra ou mesmo só à vista de algum homem espiritual e perfeito — às vezes à simples lembrança de um que estava morto ou ausente —, soprava o espírito e corriam as águas (Sl 147,18); e aquelas lágrimas eram para mim o meu pão de dia e de noite (Sl 41,4). E que era aquilo senão o odor que exalava da unção de que aquele homem estava banhado? Não era a unção em si, pois só chegava a mim por intermédio de um homem. E por isso, embora me alegrasse com o dom, ficava envergonhado e humilhado por só ter chegado até mim um hálito tênue, e não uma aspersão farta. Deleitado pelo olfato e não pelo tato, reconhecia-me indigno de que Deus se me tornasse doce por si mesmo. E, se ainda hoje me acontece o mesmo, recebo com avidez o dom concedido e fico-lhe grato; mas dói-me profundamente não o ter merecido por mim mesmo e não o ter recebido, como se diz, de mão em mão, depois de o pedir com insistência. Envergonha-me, de fato, comover-me mais com a lembrança de um homem do que com a de Deus. E então clamo, gemendo: Quando irei e aparecerei diante da face de Deus? (Sl 41,3) Creio que alguns de vós já passaram pelo mesmo, e ainda hoje passam às vezes. E que pensar disso, senão que assim ou se põe a nu a nossa soberba, ou se guarda a humildade, ou se alimenta a caridade fraterna, ou se desperta o desejo? Um só e mesmo alimento é remédio para os doentes e regime para os que adoecem com facilidade; fortalece os fracos e agrada aos sãos. Um só e mesmo alimento cura a doença e conserva a saúde; nutre o corpo e tem sabor no paladar.`
    },
    {
      n: 7,
      texto: `Mas voltemos às palavras da esposa, e cuidemos de ouvir o que ela diz de modo que procuremos também saborear o que ela saboreia. A esposa, como disse, é a Igreja. É a ela que mais se perdoou, e é ela que mais ama (Lc 7,47). O que a rival lhe lança em rosto como injúria, ela o volta em proveito próprio. Daí ser mais mansa na repreensão, mais paciente no trabalho; daí mais ardente no amor, mais atenta na cautela; daí mais humilde pela consciência que tem de si, mais bem aceita pelo pudor; daí mais pronta a obedecer, mais devota e mais solícita em dar graças. Enfim, enquanto aquela murmura e recorda os seus méritos, os seus trabalhos, o peso do dia e o calor, a Igreja recorda o benefício e diz: Óleo derramado é o teu nome.`
    },
    {
      n: 8,
      texto: `Este é o testemunho de Israel, para louvar o nome do Senhor (Sl 121,4) — não o Israel segundo a carne, porém, mas o que é segundo o espírito. Pois como poderia aquele dizê-lo? Não que não tenha óleo: é que não o tem derramado. Tem-no, mas guardado; tem-no nos livros, mas não nos corações. Fica preso por fora à letra; apalpa com as mãos um vaso cheio, mas fechado, e não o abre para se ungir. Dentro, é dentro que está a unção do espírito. Abre e unge-te, e já não serás casa rebelde. De que serve o óleo no vaso, se não o sentes também nos membros? De que te aproveita ler e reler nos livros o nome bondoso do Salvador, se não tens bondade nos costumes? É óleo: derrama-o, e sentirás a sua força, que é tríplice. Mas o judeu enjoa dessas coisas; vós, ouvi. Quero dizer por que o nome do esposo se compara ao óleo, o que ainda não tinha dito; e ocorrem-me três razões. Mas, visto que ele é chamado por muitos nomes — porque não se acha nenhum que o diga com propriedade, pois é inefável —, é preciso antes invocarmos o Espírito Santo, para que entre tantos ele se digne mostrar-nos por si mesmo qual é o único que quer que se entenda aqui, já que não lhe aprouve indicá-lo por escrito. Mas isso também fica para outra vez. Pois, ainda que tudo estivesse agora a postos, e nem vós estivésseis sobrecarregados nem eu cansado, a hora manda parar. Guardai aquilo para que vos tornei atentos, para que amanhã não seja preciso repetir. É isto que nos cabe, isto que temos entre mãos: ensinar por que o nome do esposo se compara ao óleo, e o que há a dizer sobre os nomes. E, uma vez que nada posso dizer de mim mesmo, fica marcada uma oração, para que o próprio esposo nos revele isso pelo seu Espírito — Jesus Cristo, Senhor nosso, a quem é a honra e a glória pelos séculos dos séculos. Amém.`
    }
  ]
});
