SERMOES.sermao({
  id: 'bernardo-cantico-38',
  colecao: 'bernardo-cantico',
  ordem: 38,
  numero: 'XXXVIII',
  titulo: 'De como da ignorância de Deus nasce o desespero, e em que sentido a esposa é chamada bela entre as mulheres',
  fonte: 'Qualiter ex ignorantia Dei nascitur desperatio',
  argumento: `Conclusão do díptico sobre as duas ignorâncias. Quem quer converter-se mas não conhece a bondade de Deus ouve o seu pensamento carnal dizer-lhe que os pecados são grandes demais, o corpo frágil demais, o hábito forte demais; e então, ou afunda na tristeza, ou volta para o mundo fingindo paz. Por isso Bernardo diz que ignoram a Deus todos os que não querem converter-se: imaginam duro e implacável aquele que é misericordioso, e fabricam para si um ídolo. A cada objeção responde com uma palavra da Escritura.

A esposa, porém, não é repreendida por ignorar a Deus, mas por não se conhecer: pediu, ainda no corpo, a visão do meio-dia. Por isso o esposo a chama bela "entre as mulheres" — bela em comparação, como Noé foi justo na sua geração e João o maior entre os nascidos de mulher. Ser toda bela e ver o esposo tal como ele é fica reservado para o fim.

Tradução feita do texto latino de Migne (PL 183, 974-977).`,
  pontos: [
    {
      n: 1,
      texto: `Que gera, pois, a ignorância de Deus? Pois é por aqui que se deve começar, já que, como vos lembrais, foi aqui que ontem terminamos. Que gera, então? Dissemos: o desespero; mas digamos de que modo. Suponhamos que alguém, voltando a si e descontente consigo mesmo por todos os males que fez, pensa em cair em si e voltar de todo o seu mau caminho e da sua vida carnal: se ignora quão bom é Deus, quão suave e manso, e quão generoso em perdoar (cf. Is 55,7), não o acusará o seu pensamento carnal, dizendo: Que fazes? Queres perder esta vida e a futura? Os teus pecados são enormes e numerosíssimos: por tantos e tão grandes, nem que arrancasses a própria pele conseguirias satisfazer. A tua compleição é frágil, a tua vida foi regalada, dificilmente vencerás o hábito. Por estas e outras razões semelhantes, o infeliz, desesperado, recua, ignorando com que facilidade a Bondade onipotente, que não quer que ninguém pereça (cf. 2Pd 3,9), desfaria tudo isto; e segue-se a impenitência, que é o maior dos delitos e a blasfêmia que não tem perdão. E ele, ou, perturbado, é tragado por uma tristeza excessiva (cf. 2Cor 2,7) e levado ao fundo, de onde já não há de emergir para receber consolação, como está escrito: O ímpio, quando chega ao fundo dos males, despreza tudo (Pr 18,3); ou então, fingindo e lisonjeando-se com uma razão qualquer que pareça verossímil, volta para o mundo de onde não voltará, para gozar e deleitar-se com todos os seus bens enquanto puder. Mas, quando disser: Paz e segurança, então lhe sobrevirá de repente a ruína, como as dores à mulher grávida, e não escapará (1Ts 5,3). Assim, pois, da ignorância de Deus vem a consumação de toda maldade, que é o desespero.`
    },
    {
      n: 2,
      texto: `O Apóstolo diz que alguns têm ignorância de Deus (1Cor 15,34). E eu digo que ignoram a Deus todos os que não querem converter-se a Deus. Pois sem dúvida não se recusam por outro motivo senão porque imaginam pesado e severo aquele que é piedoso, duro e implacável aquele que é misericordioso, cruel e terrível aquele que é amável; e a iniquidade mente a si mesma (cf. Sl 26,12), fabricando para si um ídolo que não é ele. Que temeis, homens de pouca fé? Que ele não queira perdoar os pecados? Mas ele os pregou na cruz juntamente com as suas mãos (cf. Cl 2,14). Que sois frágeis e delicados? Mas ele conhece a massa de que somos feitos (Sl 102,14). Que estais mal acostumados e amarrados ao hábito de pecar? Mas o Senhor solta os acorrentados (Sl 145,7). Talvez que, irritado pela enormidade e pela multidão dos crimes, hesite em estender a mão para ajudar? Mas onde abundou o delito, a graça costuma superabundar (Rm 5,20). Ou estais preocupados com a roupa, ou com o alimento, e com as outras coisas necessárias ao vosso corpo, e por isso hesitais em deixar o que é vosso? Mas ele sabe que precisais de tudo isso (Mt 6,25-32). Que quereis mais? Que é que ainda vos impede a salvação? Mas é isto que digo: ignorais a Deus, e nem sequer credes no que vos anunciamos (cf. Is 53,1). Queria que ao menos crêsseis nos que o experimentaram, porque, se não crerdes, não entendereis (Is 7,9). Mas a fé não é de todos (2Ts 3,2).`
    },
    {
      n: 3,
      texto: `Mas longe de nós pensar que a esposa é advertida de uma ignorância assim, isto é, da ignorância de Deus — ela, que recebeu daquele que é ao mesmo tempo seu esposo e seu Deus, não digo o conhecimento, mas tamanha amizade e familiaridade, que mereceu dele frequentes conversas e beijos, e agora fala com ousadia familiar: Mostra-me onde apascentas, onde repousas ao meio-dia. Ali, com efeito, pede que lhe mostrem não a ele, mas o lugar onde habita a sua glória — ainda que ele não seja uma coisa, e o seu lugar ou a sua glória outra. Mas julga-se que deve ser contida por causa da presunção, e advertida quanto ao conhecimento de si mesma, no qual, sem dúvida, pareceu enxergar um tanto turvo, ela que se julgou capaz de tamanha visão — ou porque, arrebatada no seu êxtase, reparou pouco que estava no corpo, ou porque esperou em vão poder, mesmo permanecendo no corpo, chegar àquela claridade inacessível. É, pois, imediatamente chamada de volta a si mesma: a ignorância é-lhe provada, e a ousadia, castigada. Se não te conheces, diz, sai (Ct 1,7). O esposo troveja terrivelmente contra a amada, não como esposo, mas como mestre; e não como quem está irado, mas para que, assustada, se purifique, e, purificada, se torne capaz desta mesma visão por que anseia. Pois aquela visão está reservada aos puros de coração (cf. Mt 5,8).`
    },
    {
      n: 4,
      texto: `E é com acerto que a chama bela — não de todo, mas bela entre as mulheres, isto é, com uma restrição —, para que também por isso seja mais contida e saiba o que lhe falta. Pois julgo que aqui se chamam mulheres as almas carnais e mundanas, que nada têm de viril, que nada de forte ou constante mostram nas suas ações, mas cujo viver e agir é todo frouxo, todo efeminado e mole. Mas a alma espiritual, ainda que já seja bela por não andar segundo a carne, mas segundo o espírito (Rm 8,4), pelo fato de ainda viver no corpo progride aquém da perfeição da beleza; e por isso não é bela de todo modo, mas bela entre as mulheres, isto é, entre as almas terrenas e que não são espirituais como ela; não, porém, entre as bem-aventuranças angélicas, nem entre as virtudes, as potestades, as dominações. Assim como um dos patriarcas foi achado e chamado outrora justo na sua geração (Gn 6,9), isto é, mais que todos os do seu tempo e da sua geração; e de Tamar se diz que foi justificada diante de Judá (Gn 38,26), isto é, em comparação com Judá; e no Evangelho se conta que o publicano desceu do templo justificado — mas justificado em comparação com o fariseu (Lc 18,14); e como aquele grande João foi outrora magnificamente louvado, porque não tinha ninguém maior do que ele — mas entre os nascidos de mulher (Lc 7,28), não entre os coros dos espíritos bem-aventurados e celestes —; assim também a esposa é agora chamada bela, mas, por enquanto, ainda entre as mulheres, e não entre as bem-aventuranças celestes.`
    },
    {
      n: 5,
      texto: `Deixe, pois, enquanto está na terra, de investigar com demasiada curiosidade as coisas que estão no céu, para que, perscrutando a majestade, não seja esmagada pela glória (cf. Pr 25,27). Deixe, digo, enquanto vive entre as mulheres, de indagar as coisas que estão junto daquelas sublimes potestades, só para elas claras, só a elas permitidas, como coisas celestes que os celestes podem ver. Esta visão que pedes que te mostrem, ó esposa, diz ele, é maravilhosa demais para ti (cf. Sl 138,6); não podes agora contemplar a claridade admirável do meio-dia em que habito. Pois disseste: Mostra-me onde apascentas, onde repousas ao meio-dia. Mas ser introduzido nas nuvens, penetrar na plenitude da luz, irromper nos abismos da claridade e habitar a luz inacessível (1Tm 6,16) não é deste tempo, nem deste corpo. Isso te está reservado para o fim, quando eu te apresentar a mim mesmo gloriosa, sem mancha nem ruga nem coisa semelhante (Ef 5,27). Não sabes que, enquanto vives neste corpo, estás exilada longe da luz (cf. 2Cor 5,6)? Como te julgas capaz de contemplar a beleza inteira, tu que ainda não és toda bela? Como, enfim, procuras ver-me na minha claridade, tu que ainda não te conheces? Pois, se te conhecesses mais plenamente, saberias sem dúvida que, oprimida pelo corpo que se corrompe (Sb 9,15), de modo nenhum podes erguer os olhos e fixá-los naquele fulgor que os anjos desejam contemplar (1Pd 1,12). Quando eu aparecer, serás toda bela, como eu sou todo belo; e, semelhantíssima a mim, me verás tal como sou (1Jo 3,2). Então ouvirás: Tu és toda bela, minha amiga, e não há mancha em ti (Ct 4,7). Mas agora, já em parte semelhante e em parte ainda dessemelhante, contenta-te em conhecer em parte. Atende a ti mesma, e não busques o que está acima de ti, nem investigues o que excede as tuas forças (Eclo 3,22). De outro modo, se não te conheces, ó bela entre as mulheres (Ct 1,7) — pois também eu te chamo bela, mas entre as mulheres, isto é, em parte; e, quando vier o que é perfeito, então desaparecerá o que é em parte (1Cor 13,10) —, se, pois, não te conheces... Mas o que se segue já foi dito, e não é preciso dizê-lo de novo. Eu tinha prometido tratar com proveito da dupla ignorância: se parece que o cumpri menos bem, perdoai a quem teve boa vontade. Pois o querer está ao meu alcance, mas não encontro como realizá-lo (Rm 7,18), a não ser na medida em que, para vossa edificação, se dignar concedê-lo na sua bondade o esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
