SERMOES.sermao({
  id: 'bernardo-cantico-04',
  colecao: 'bernardo-cantico',
  ordem: 4,
  numero: 'IV',
  titulo: 'Do tríplice progresso da alma, que se faz pelo beijo do pé, da mão e da boca do Senhor',
  fonte: 'De triplici profectu animae',
  argumento: `Retomando o sermão interrompido na véspera, Bernardo justifica primeiro por que chama beijos aos dois primeiros graus, e depois responde à objeção que se lhe poderia opor: se Deus é espírito, que boca, que mão, que pés são esses? A resposta abre o sermão para a questão de como Deus é o ser de todas as coisas — e é ela que ficará para o dia seguinte.

Tradução feita do texto latino de Migne (PL 183, 796-798).`,
  pontos: [
    {
      n: 1,
      texto: `O sermão de ontem abarcou, sob o nome dos três beijos, um certo tríplice progresso da alma. Porventura vos esqueceu? Hei de prossegui-lo na disputa de hoje, conforme Deus se dignar preparar, na sua doçura, para o pobre. Dissemos, se vos lembrais, que aqueles beijos se tomam nos pés, na mão e na boca, referindo cada um a cada estado. No primeiro consagram-se os primórdios da nossa conversão; o segundo concede-se aos que progridem; o terceiro, porém, só a perfeição, e rara, o experimenta. Somente deste último, que se põe em fim, tomou princípio esta Escritura que empreendemos tratar, e por causa dele acrescentamos nós os outros dois. Se necessariamente, vós o julgareis. Pois penso que a própria face do texto facilmente adverte que também aqueles se hão de buscar. Seria de admirar se também vós não advertísseis que deve haver, na verdade, outro beijo, ou outros beijos, dos quais quis distinguir aquele da boca quem disse: Beije-me com o beijo da sua boca (Ct 1,1). Pois por que, podendo bastar dizer simplesmente «beije-me», acrescentou todavia, contra o costume e o uso de falar, distinta e expressamente, «com o beijo da sua boca», senão para mostrar que o beijo que pedia era o sumo, e não o único? Não falamos, enfim, assim uns com os outros: «Beija-me», ou «dá-me um beijo»? E ninguém prossegue dizendo: «com a tua boca», ou «com o beijo da tua boca». Que mais? Preparando-nos para beijar um ao outro, estendemos as bocas um para o outro, e todavia não as reclamamos nominalmente um do outro. Enfim, quem narra, por exemplo, que o traidor foi recebido pelo Senhor num beijo, diz: E beijou-o (Mc 14,45), e não acrescentou: «com a sua boca», ou «com o beijo da sua boca». Assim, sem dúvida, costuma fazer todo aquele que escreve e que fala. São, portanto, estes três os afetos, ou progressos, das almas — bastante conhecidos e manifestos, ao menos aos que os experimentaram —, quando alcançam ver ou o perdão dos males cometidos, ou a graça para praticar os bens, ou ainda a presença do próprio perdoador e benfeitor, do modo, ao menos, que é possível em corpo frágil.`
    },
    {
      n: 2,
      texto: `De resto, recebei mais claramente por que razão chamei beijos ao primeiro e ao segundo. Todos sabemos que o beijo é sinal de paz. Ora, se, como diz a Escritura, os nossos pecados separam entre nós e Deus (Is 59,2), tire-se do meio o que está de permeio, e há paz. Quando, portanto, satisfazemos, para que, tirado o pecado que separa, sejamos reconciliados, o perdão que recebemos — que outra coisa direi que ele é, senão um certo beijo de paz? E este, entretanto, não se há de tomar em outro lugar senão aos pés. Pois humilde e envergonhada deve ser a satisfação pela qual se emenda a soberba transgressão.`
    },
    {
      n: 3,
      texto: `Mas, quando também somos agraciados com certa aprazível familiaridade de mais ampla graça, para viver mais emendadamente e conversar de modo mais digno de Deus, com maior confiança levantamos já a cabeça do pó, para beijar, como é costume, a mão do doador — se, todavia, do dom recebido buscamos não a nossa glória, mas a do autor, e a ele atribuímos os seus dons, e não a nós. Do contrário, se te glorias em ti e não antes no Senhor, ficas convencido de beijar a tua própria mão, e não a do Senhor: o que, segundo a sentença do bem-aventurado Jó, é iniquidade máxima e negação de Deus (Jó 31,28). Se, pois, conforme o testemunho da Escritura, buscar a própria glória é beijar a própria mão, sem dúvida quem dá glória a Deus não se diz sem congruência beijar a mão de Deus. E entre os homens vemos que assim é: que os servos costumam beijar os pés dos senhores ofendidos, quando lhes pedem perdão; e os pobres, as mãos dos ricos, quando deles recebem um dom.`
    },
    {
      n: 4,
      texto: `Mas, porque Deus é espírito (Jo 4,24), e aquela substância simples não é distinta por membros corpóreos alguns, haverá talvez quem de modo nenhum admita a seu respeito coisa semelhante, mas exija de mim que lhe mostrem as mãos ou os pés de Deus, e que assim se prove o que defino acerca do beijo dos pés e da mão. Mas que sucederá, se também eu, por minha vez, perguntar ao meu inquiridor acerca da boca de Deus, de sorte que ele demonstre que o que a Escritura diz do beijo da boca pertence a Deus? Certamente, ou tem, junto com esta, também aquelas; ou, junto com aquelas, carece igualmente desta. Ora, Deus tem boca, com que ensina ao homem a ciência; e tem mão, com que dá alimento a toda carne; e tem pés, dos quais a terra é escabelo, e aos quais, convertidos e humilhados, satisfazem sem dúvida os pecadores da terra. Todas estas coisas, digo, Deus as tem por efeito, não por natureza. Encontra, com efeito, junto de Deus, a envergonhada confissão onde se abata humilhando-se; e a pronta devoção, onde se refaça renovando-se; e a alegre contemplação, onde repouse saindo de si. Todas as coisas é para todos aquele que tudo administra, e nada é propriamente de tudo o que administra. Pois, quanto ao que é em si, habita uma luz inacessível (1Tm 6,16), e a sua paz excede todo sentido (Fl 4,7), e a sua sabedoria não tem número (Sl 146,5), e a sua grandeza não tem fim (Sl 144,3), nem o pode ver o homem e continuar vivo (Ex 33,20). Não porque esteja longe de cada um aquele que é o ser de todas as coisas, sem o qual tudo é nada; mas — e assim mais te admirarás — nada há mais presente que ele, e nada mais incompreensível. Pois que há mais presente a cada coisa do que o seu próprio ser? E que há, todavia, mais incompreensível a cada uma do que o ser de todas? Direi, na verdade, que Deus é o ser de todas as coisas, não porque elas sejam o que ele é, mas porque dele, e por ele, e nele são todas as coisas (Rm 11,36). É, portanto, o ser de todas as coisas que foram feitas o próprio autor delas — mas como causa, não como matéria. Deste modo, pois, aquela majestade se digna ser para as suas criaturas: para todas, aquilo que são; para as que vivem, também aquilo por que vivem; para as que usam da razão, luz; para as que dela usam retamente, virtude; para as que vencem, glória.`
    },
    {
      n: 5,
      texto: `E em todas estas coisas — criá-las, governá-las, administrá-las, movê-las, promovê-las, renová-las, firmá-las — não precisa de instrumentos corpóreos alguns aquele que só com a palavra criou tanto os corpos como os espíritos. As almas precisam de corpos e de sentidos corpóreos, para se darem a conhecer umas às outras e para poderem agir. Mas não assim o Deus onipotente, a quem, só pela vontade, sobra rápida eficiência tanto para criar as coisas como para ordená-las conforme quiser. Pode quanto quer aquele que quer, e sem o ofício ou a obediência de membros corporais. Pois quê? Para contemplar aquilo que ele mesmo fundou, julgas que precise do auxílio de um sentido corpóreo? Absolutamente nada, de tudo quanto há, se esconde ou escapa à luz que está presente em toda parte; e, todavia, para conhecer alguma coisa, não tem necessidade do ministério de um sentido que lha anuncie. E não somente conhece todas as coisas sem corpo, mas também se dá a conhecer sem corpo aos limpos de coração. Digo, porém, o mesmo mais largamente, para que se torne mais claro. Mas, porque talvez a estreiteza do sermão, que já se deve terminar, não o permite, é de melhor conselho que o adiemos para amanhã.`
    }
  ]
});
