SERMOES.sermao({
  id: 'bernardo-cantico-21',
  colecao: 'bernardo-cantico',
  ordem: 21,
  numero: 'XXI',
  titulo: 'De como a esposa, isto é, a Igreja, deseja ser levada atrás do esposo, isto é, de Cristo',
  fonte: 'Qualiter sponsa trahi se optat post sponsum',
  argumento: `Sobre «leva-me atrás de ti». Bernardo pergunta por que a esposa, que parecia forte bastante para levar os outros, precisa ela mesma de ser levada. A resposta abre o assunto da alternância: ninguém que ande no espírito permanece num mesmo estado, e ora se corre, ora é preciso ser puxado.

Daí saem dois conselhos práticos: no torpor, não desconfiar nem largar o exercício espiritual; na graça, não julgar que se possui o dom por direito de herança. No meio vem a página sobre o rico que se ajusta à própria bolsa como um servo à sua senhora. E no fim, a explicação do singular e do plural — a esposa guarda para si o que é duro e reparte o que é doce.

Tradução feita do texto latino de Migne (PL 183, 872-878).`,
  pontos: [
    {
      n: 1,
      texto: `Leva-me atrás de ti; correremos ao odor dos teus perfumes (Ct 1,3). Como? A esposa precisa de ser levada — e isso atrás do esposo? Como se o seguisse contra a vontade, e não de bom grado. Mas nem todo o que é levado o é contra a vontade: o doente ou o fraco, que não consegue andar por si, não se aborrece de ser levado ao banho ou à mesa, ainda que o réu se aborreça de ser levado a julgamento ou ao castigo. Quer ser levada, enfim, justamente por o pedir; e não o pediria se pudesse seguir o amado por si mesma, como queria. Mas por que não pode? Havemos de confessar que também a esposa está doente? Se uma qualquer das jovenzinhas se dissesse doente e pedisse para ser levada, não nos admiraríamos. Mas da esposa, que parecia bastante forte e perfeita para levar também outros — a quem não soará duro que ela mesma precise de ser levada, como doente ou fraca? De que alma havemos de confiar que é forte e sã, se admitirmos chamar doente àquela que, pela sua perfeição singular e virtude mais excelente, recebe o nome de esposa do Senhor? Ou terá sido a Igreja que o disse, ao ver o amado a subir, ansiando por segui-lo e por ser levada com ele à glória? Ainda que uma alma, por mais perfeita que seja, enquanto geme sob este corpo de morte e fica presa no cárcere deste mundo mau, atada por necessidades e torcida por culpas, forçosamente se ergue mais devagar e com mais custo à contemplação das coisas altas, e não tem liberdade plena para seguir o esposo aonde quer que vá. Daí aquela voz chorosa de quem geme: Infeliz de mim! Quem me livrará deste corpo de morte? (Rm 7,24) Daí aquela prece suplicante: Tira do cárcere a minha alma (Sl 141,8). Diga, pois, também a esposa, e diga gemendo: Leva-me atrás de ti — porque o corpo que se corrompe pesa sobre a alma, e a morada terrena deprime a mente que muito pensa (Sb 9,15). Ou o diz porque deseja partir e estar com Cristo (Fl 1,23-24), sobretudo ao ver que aquelas por quem parecia necessário que ela ficasse na carne já vão bem e já amam o esposo, e estão seguras na caridade? Pois já dissera antes: Por isso as jovenzinhas te amaram. Agora é como se dissesse: Eis que as jovenzinhas te amam e, amando, se prendem a ti com firmeza, e já não precisam de mim; não tenho mais razão para demorar-me nesta vida. Por isso diz: Leva-me atrás de ti.`
    },
    {
      n: 2,
      texto: `Eu entenderia assim, se ela tivesse dito: Leva-me a ti. Mas, dizendo atrás de ti, parece-me antes pedir que possa seguir as pegadas do modo de viver dele, imitar a sua virtude, guardar a sua regra de vida e aprender a disciplina dos seus costumes. É nisto que mais se precisa de ajuda: para poder negar-se a si mesma, tomar a sua cruz e assim seguir a Cristo. Aqui é que a esposa precisa de ser levada — e não por outro senão por aquele mesmo que disse: Sem mim nada podeis fazer (Jo 15,5). Sei, diz ela, que de modo nenhum posso chegar a ti senão caminhando atrás de ti; e nem isso, sem a tua ajuda. Por isso peço que me leves atrás de ti. Feliz aquele cujo socorro vem de ti: dispôs no coração subidas neste vale de lágrimas (Sl 83,6), e há de chegar um dia até ti, nos montes das alegrias. Quão poucos querem ir atrás de ti, Senhor Jesus! E, no entanto, não há quem não queira chegar até ti, pois todos sabem que à tua direita há delícias para sempre (Sl 15,11). Por isso todos querem gozar de ti, mas não imitar-te; desejam reinar contigo, mas não padecer contigo. Era destes aquele que dizia: Morra a minha alma com a morte dos justos, e seja o meu fim semelhante ao deles (Nm 23,10). Desejava para si o fim dos justos, mas não os começos. Também os carnais desejam para si a morte dos espirituais, embora detestem a vida deles; pois sabem que é preciosa a morte dos santos, porque, quando ele der o sono aos seus amados, eis a herança do Senhor (Sl 126,2-3); e que felizes são os mortos que morrem no Senhor (Ap 14,13) — ao passo que, segundo a sentença do profeta, péssima é a morte dos pecadores (Sl 33,22). Não se dão ao trabalho de procurar aquele que desejam encontrar: querem alcançá-lo, mas não segui-lo. Não assim aqueles a quem ele dizia: Vós sois os que permanecestes comigo nas minhas provações (Lc 22,28). Felizes os que foram julgados dignos de um testemunho teu, bondoso Jesus! Esses iam de fato atrás de ti, com os pés e com os afetos. Fizeste-lhes conhecer os caminhos da vida, chamando-os para trás de ti, porque és caminho e vida, e dizes: Vinde após mim, e eu vos farei pescadores de homens (Mt 4,19); e ainda: Quem me serve, siga-me; e onde eu estiver, ali estará também o meu servo (Jo 12,26). Por isso diziam, gloriando-se: Eis que deixamos tudo e te seguimos (Mt 19,27).`
    },
    {
      n: 3,
      texto: `Assim também a tua amada, tendo deixado tudo por ti, deseja ir sempre atrás de ti, prender-se sempre às tuas pegadas e seguir-te aonde quer que vás; porque sabe que os teus caminhos são caminhos formosos e que todas as tuas veredas são de paz (Pr 3,17), e que quem te segue não anda nas trevas (Jo 8,12). E pede ser levada porque a tua justiça é como os montes de Deus (Sl 35,7), e as suas forças não bastam para chegar até ela. Pede ser levada, como se costuma, porque ninguém vem a ti se o teu Pai não o atrair (Jo 6,44). Ora, os que o Pai atrai, atrai-os também tu, pois as obras que o Pai faz, também o Filho as faz do mesmo modo (Jo 5,19). Mas pede com mais familiaridade ser levada pelo Filho, como pelo seu próprio esposo — que o Pai lhe enviou ao encontro como guia e mestre, para ir à sua frente no caminho dos costumes, preparar-lhe a estrada das virtudes, instruí-la como a si mesmo, ensinar-lhe o caminho da prudência e entregar-lhe a lei da vida e da disciplina; e assim ele se enamoraria, com razão, da formosura dela.`
    },
    {
      n: 4,
      texto: `Leva-me atrás de ti; correremos ao odor dos teus perfumes. Preciso ser levada porque o fogo do teu amor esfriou um pouco em nós, e diante deste frio já não conseguimos correr como ontem e anteontem. Mas correremos depois, quando devolveres a alegria da tua salvação, quando voltar o tempo mais ameno da graça, quando o Sol da justiça tornar a aquecer e passar a nuvem da tentação, que por ora se vê cobri-lo; e quando, ao sopro leve de uma brisa mais branda que o costume, os perfumes começarem a derreter-se, e os aromas a correr e a dar o seu odor. Então correremos, naquele odor correremos. Quando os perfumes soprarem, correremos; porque se irá o torpor que agora há, voltará a devoção, e já não precisaremos que nos levem: despertados pelo odor, correremos por nós mesmos. Por agora, porém, leva-me atrás de ti. Vês como quem anda no espírito não permanece num mesmo estado, nem avança sempre com a mesma facilidade, e como não está no homem o seu caminho (Jr 10,23)? Mas, conforme o Espírito que o governa dispõe, ora com mais lentidão, ora com mais ardor, esquece o que fica para trás e se estende para o que está adiante (Fl 3,13). Creio que, se prestardes atenção a isso, a vossa experiência vos responde por dentro aquilo que eu digo por fora.`
    },
    {
      n: 5,
      texto: `Quando, pois, te sentires tomado de torpor, de acídia ou de enfado, não desconfies por isso nem abandones o exercício espiritual; mas busca a mão de quem ajuda, pedindo, a exemplo da esposa, que te levem — até que, despertado de novo pela graça e feito mais pronto e mais alegre, corras e digas: Corri o caminho dos teus mandamentos, quando dilataste o meu coração (Sl 118,32). Mas deleita-te na graça, enquanto ela está presente, de modo a não julgares que possuis o dom de Deus por direito de herança, seguro dele como se nunca o pudesses perder; não aconteça que, quando de repente ele retirar a mão e tirar o dom, tu desanimes e fiques mais triste do que convém. Não digas, enfim, na tua abundância: Nunca serei abalado; para que não tenhas de dizer, gemendo, o que vem depois: Desviaste de mim o teu rosto, e fiquei perturbado (Sl 29,7-8). Antes cuidarás, se és sábio, de seguir o conselho do Sábio: no dia dos males não te esquecer dos bens, e no dia dos bens não te esquecer dos males (Eclo 11,27).`
    },
    {
      n: 6,
      texto: `No dia da tua força, pois, não fiques seguro: clama a Deus com o Profeta e dize: Quando me faltar a força, não me abandones (Sl 70,9). E no tempo da tentação consola-te e dize com a esposa: Leva-me atrás de ti; correremos ao odor dos teus perfumes. Assim a esperança não te deixará no tempo mau, nem a previdência te faltará no bom; e, entre as adversidades e as prosperidades de tempos mutáveis, guardarás uma certa imagem da eternidade — aquela igualdade inviolável e inabalável de um ânimo constante —, bendizendo o Senhor em todo tempo (Sl 33,2); e assim reclamarás para ti, mesmo entre os acontecimentos incertos e as quedas certas deste mundo vacilante, um estado de imutabilidade de certo modo perpétuo, quando começares a renovar-te e a refazer-te naquela antiga marca de semelhança com o Deus eterno, em quem não há mudança nem sombra de variação (Tg 1,17). Pois, como ele é, assim serás tu neste mundo (1Jo 4,17): nem medroso na adversidade, nem dissoluto na prosperidade. Nisto, digo, a nobre criatura, feita à imagem e semelhança daquele que a fez, mostra que está retomando e quase já recuperando a dignidade da honra antiga: quando julga indigno de si conformar-se a este mundo que passa, e antes se empenha em refazer-se, segundo a doutrina de Paulo, na novidade do seu entendimento (Rm 12,2), naquela semelhança em que sabe ter sido criada; e, com isso, obrigando ainda — como é justo — este mundo, que foi feito por causa dela, a conformar-se por sua vez a ela, de modo admirável; pois todas as coisas começam a concorrer para o seu bem (Rm 8,28), como que reconhecendo, na sua forma própria e natural, depois de lançada fora a aparência degenerada, o seu Senhor, para servir ao qual foram criadas.`
    },
    {
      n: 7,
      texto: `Daí julgar eu que aquela palavra que o Unigênito disse de si — que, se fosse levantado da terra, atrairia tudo a si — pode ser comum também a todos os seus irmãos: aqueles que o Pai conheceu de antemão e predestinou a serem conformes à imagem do seu Filho, para que ele seja o primogênito entre muitos irmãos (Rm 8,29). Também eu, portanto, digo com ousadia: se for levantado da terra, atrairei tudo a mim (Jo 12,32). Pois não tomo temerariamente para mim, irmãos meus, uma palavra daquele cuja semelhança visto. E, se é assim, não julguem os ricos deste mundo que os irmãos de Cristo possuem apenas as coisas do céu, só porque o ouvem dizer: Felizes os pobres em espírito, porque deles é o reino dos céus (Mt 5,3). Não pensem, digo, que só possuem o céu aqueles que só o ouvem prometido. Também possuem as coisas da terra: como quem nada tem, mas tudo possui (2Cor 6,10); não mendigando, como miseráveis, mas possuindo como senhores — e tanto mais senhores quanto menos cobiçosos. Enfim, para o homem fiel o mundo inteiro é riqueza (Pr 17,6). Inteiro mesmo: porque tanto as adversidades como as prosperidades dele o servem por igual e concorrem para o seu bem.`
    },
    {
      n: 8,
      texto: `O avarento, pois, tem fome das coisas da terra como um mendigo; o fiel as despreza como senhor. Aquele, possuindo, mendiga; este, desprezando, conserva. Pergunta a qualquer um dos que anseiam com coração insaciável por lucros temporais o que pensa daqueles que vendem os seus bens, dão-nos aos pobres e compram o reino dos céus com a fazenda da terra: agem com sabedoria ou não? Sem dúvida responderá: Com sabedoria. Pergunta-lhe então por que não faz ele o que aprova. Não posso, dirá. Por quê? Porque a avareza, que é sua senhora, não permite; porque não é livre; porque não são suas as coisas que parece possuir — nem ele é dono de si. Se são de fato tuas, gasta-as para lucrar e troca as da terra pelas do céu. Se não consegues, confessa que não és senhor do teu dinheiro, mas seu servo; seu guarda, não seu dono. Enfim, ajustas-te à tua bolsa como um servo à sua senhora: assim como ele forçosamente se alegra quando ela se alegra e sofre quando ela sofre, também tu cresces de ânimo quando a tua bolsa cresce, e diminuis quando ela diminui. Encolhes-te de tristeza quando ela se esvazia, e desmanchas-te de alegria — ou então te inchas de soberba — quando ela se enche. Assim é ele. Quanto a nós, cuidemos de imitar a liberdade e a constância da esposa que, bem instruída em tudo e com o coração formado na sabedoria, sabe ter em abundância e sabe passar necessidade (Fl 4,12). Ao pedir que a levem, mostra o que lhe falta — não de dinheiro, mas de força. E, ao consolar-se com a esperança de que a graça há de voltar, mostra que desfalece, sim, mas não desconfia.`
    },
    {
      n: 9,
      texto: `Diz, pois: Leva-me atrás de ti; correremos ao odor dos teus perfumes. E que há de admirar em precisar ser levada quem corre atrás de um gigante, quem se esforça por alcançar aquele que salta pelos montes e passa por cima das colinas (Ct 2,8)? A sua palavra corre velozmente, diz o salmo (Sl 147,15). Não consegue correr de igual para igual, não pode disputar a mesma velocidade com aquele que se lança como um gigante a percorrer o seu caminho (Sl 18,6); não pode com as suas forças, e por isso pede que a levem. Estou cansada, diz ela, desfaleço; não me abandones, mas leva-me atrás de ti — para que eu não comece a vaguear atrás de outros amantes, para que não corra como quem corre sem rumo (1Cor 9,26). Leva-me atrás de ti; pois é melhor para mim que me leves — que me faças alguma violência, assustando-me com ameaças ou exercitando-me com açoites — do que me poupares e me deixares no meu torpor, mal segura. Leva-me de certo modo contra a vontade, para me tornares voluntária; leva-me entorpecida, para me devolveres a correr. Virá o dia em que não precisarei de quem me leve, pois correremos de boa vontade e com toda a alegria. E não correrei sozinha, ainda que tenha pedido ser levada só eu: correrão comigo também as jovenzinhas. Correremos juntas, correremos ao mesmo tempo: eu, ao odor dos teus perfumes; elas, despertadas pelo meu exemplo e pela minha exortação. E assim todas correremos ao odor dos teus perfumes. A esposa tem quem a imite, assim como ela mesma imita a Cristo; e por isso não diz no singular «correrei», mas «correremos».`
    },
    {
      n: 10,
      texto: `Mas surge uma questão: por que, ao pedir que a levassem, não juntou também as jovenzinhas, dizendo «leva-nos» em vez de «leva-me»? Então? A esposa precisa de ser levada e as jovenzinhas não? Ó formosa, ó feliz, ó bem-aventurada, explica-nos a razão desta distinção. Leva-me, dizes. Por que «me», e não «nos»? Invejas-nos este bem? De modo nenhum! Pois não terias dito logo a seguir que as jovenzinhas haviam de correr contigo, se quisesses ir sozinha atrás do esposo. Por que, então, prestes a acrescentar no plural «correremos», pediste no singular ser levada? A caridade, diz ela, assim o pedia. Aprende por esta palavra a esperar de mim, no exercício espiritual, um duplo socorro vindo do alto: a correção e a consolação. Uma exercita por fora, a outra visita por dentro. Aquela reprime a insolência, esta levanta para a confiança; aquela produz humildade, esta consola quem está sem ânimo; aquela torna cautelosos, esta torna devotos. Aquela ensina o temor do Senhor; esta tempera o próprio temor, infundindo-lhe uma alegria que salva, como está escrito: Alegre-se o meu coração, para que tema o teu nome (Sl 85,11); e ainda: Servi ao Senhor com temor, e exultai diante dele com tremor (Sl 2,11).`
    },
    {
      n: 11,
      texto: `Somos levados quando nos exercitam com tentações e tribulações; corremos quando, visitados por consolações e inspirações interiores, respiramos como entre perfumes odorosos. Guardo, pois, para mim o que parece áspero e duro, como quem é forte, sã e perfeita, e digo no singular: Leva-me. O que é suave e doce reparto contigo, que és fraco, e digo: Correremos. Sei que as jovenzinhas são delicadas e tenras, e pouco capazes de suportar tentações; e por isso quero que corram comigo, mas não que sejam levadas comigo: quero tê-las por companheiras da consolação, não também do trabalho. Por quê? Porque são fracas, e receio que desfaleçam e sucumbam. A mim, ó esposo — diz ela —, corrige-me, exercita-me, prova-me, leva-me atrás de ti; porque estou pronta para os açoites (Sl 37,18) e sou capaz de suportar. Mas correremos juntas: serei levada sozinha, e correremos juntas. Correremos, correremos — mas ao odor dos teus perfumes, não na confiança dos nossos méritos; não contamos correr pela grandeza das nossas forças, mas pela multidão das tuas compaixões. Pois, se alguma vez corremos e fomos voluntárias, não foi por obra de quem quer, nem de quem corre, mas de Deus, que se compadece (Rm 9,16). Volte a compaixão, e correremos. Tu corres com a tua própria força, como um gigante poderoso; nós, se os teus perfumes não soprarem, não correremos. Tu, a quem o Pai ungiu com óleo de alegria mais que aos teus companheiros (Sl 44,8), corres na própria unção; nós correremos no odor dela: tu na plenitude, nós no odor. Seria hora de pagar o que me lembro de ter prometido, muito acima, sobre os perfumes do esposo — se o comprimento deste sermão não o impedisse. Adio, pois: a dignidade do assunto não suporta ser apertada por uma brevidade incômoda. Pedi ao Senhor da unção que se digne aceitar as ofertas voluntárias da minha boca, para gravar nos vossos desejos a memória da abundância da sua suavidade, que está no esposo da Igreja, Jesus Cristo, Senhor nosso. Amém.`
    }
  ]
});
