SERMOES.sermao({
  id: 'bernardo-cantico-85',
  colecao: 'bernardo-cantico',
  ordem: 85,
  numero: 'LXXXV',
  titulo: 'Das sete necessidades pelas quais a alma busca o Verbo; e como, enfim reformada, se aproxima para contemplar e gozar a sua doçura',
  fonte: 'De septem necessitatibus, propter quas anima quaerit Verbum',
  argumento: `Bernardo enumera sete razões pelas quais a alma busca o Verbo: para se pôr de acordo com ele e ser corrigida; para ser iluminada e conhecer; para se apoiar nele e ter virtude; para ser reformada e ter sabedoria; para se conformar a ele e ter beleza; para se casar com ele e ser fecunda; para gozar dele e ter alegria. O Verbo é o "adversário" dos nossos desejos carnais, com quem devemos pôr-nos de acordo no caminho; mas isto só se consegue refugiando-se nele. Depois, é a luz que ensina o que ele quer. Quem já está de pé no bem deve apoiar-se nele, porque três empurram — o diabo, o mundo e sobretudo o próprio homem, que pode cair pelo seu próprio empurrão.

A virtude é vigor e trabalho; a sabedoria é o sabor do bem, que torna saborosa a virtude, perdido pela insipiência de Eva e restituído por Maria. A beleza da alma é a honestidade, cuja morada é a boa consciência e que irradia para os gestos e as palavras. Então a alma ousa pensar nas núpcias: casada com o Verbo, dá à luz almas pela pregação ou inteligências espirituais pela contemplação, na qual por vezes sai de si para gozar do Verbo — doce comércio, mas momento breve e experiência rara, que não se ensina com a língua, mas com a graça, e se revela aos humildes.

Tradução feita do texto latino de Migne (PL 183, 1187-1194).`,
  pontos: [
    {
      n: 1,
      texto: `No meu pequeno leito busquei aquele a quem a minha alma ama (Ct 3,1). Para quê? Já se disse, e seria supérfluo repeti-lo; mas, por causa de alguns que não estavam presentes quando se tratou disto, direi alguma coisa brevemente, que talvez nem aos que estavam presentes desagrade ouvir. Pois então não se pôde dizer tudo. A alma busca o Verbo: para se pôr de acordo com ele e ser corrigida; para ser iluminada por ele e conhecer; para se apoiar nele e ter virtude; para ser reformada por ele e ter sabedoria; para se conformar a ele e ter beleza; para se casar com ele e ser fecunda; para gozar dele e ter alegria. Por todas estas causas a alma busca o Verbo. Não duvido de que haja muitíssimas outras; mas estas me ocorrem por ora. E quem tiver isto a peito poderá facilmente descobrir em si mesmo outras e outras. Pois muitos são os nossos desvios, muitas e infinitas as necessidades da alma, e as angústias não têm número. Mas o Verbo transborda mais rica e plenamente em bens, como Sabedoria que vence a malícia (cf. Sb 7,30), que vence o mal com o bem (cf. Rm 12,21). E agora recebei a razão destas que propus. E primeiro, o que é primeiro: vede como a alma se põe de acordo com ele para ser corrigida. Lemos nos Evangelhos que o Verbo diz: Põe-te de acordo com o teu adversário, enquanto estás com ele no caminho, para que não te entregue ao juiz, e o juiz ao carrasco (Mt 5,25). Que há de mais sensato? É conselho do Verbo, se não me engano, que se declara adversário, porque se opõe aos nossos desejos carnais, quando diz: Estes erram sempre no coração (Sl 94,10). Tu, pois, que ouves isto, se, com medo, começares a querer fugir da ira que há de vir (cf. Mt 3,7), creio que te preocuparás em como pôr-te de acordo com este adversário, que parece ameaçar-te tão terrivelmente com ela. Mas isso é impossível, se não estiveres em desacordo contigo mesmo, se não te opuseres a ti mesmo, se não combateres incansavelmente contra ti mesmo numa luta dura e vigilante; enfim, se não disseres adeus ao costume inveterado e à inclinação inata. Isto é duro. Se o tentares com as tuas forças, será como se tentasses deter com um dos teus dedos o ímpeto de uma torrente, ou fazer de novo voltar para trás o Jordão (cf. Sl 113,3). Que farás? Busca o Verbo, para te pores de acordo com ele, fazendo ele mesmo que te ponhas de acordo. Foge para aquele que se opõe a ti, para que por ele te tornes tal que já não se oponha a ti; para que acaricie quem ameaçava, e seja mais eficaz para te mudar a graça infundida do que a ira ameaçadora.`
    },
    {
      n: 2,
      texto: `Esta é, penso eu, a primeira necessidade pela qual a alma começa a buscar o Verbo. Mas, se ignoras o que quer aquele com quem já estás de acordo pela vontade, não se dirá também de ti que tens zelo de Deus, mas não segundo o conhecimento (Rm 10,2)? E, para que não julgues isto coisa leve, lembra-te de que está escrito: Quem o ignora será ignorado (1Cor 14,38). Queres saber o que aconselho também nesta necessidade? O mesmo que na primeira. Pelo meu conselho, irás também agora ao Verbo, e ele te ensinará os seus caminhos (cf. Is 2,3), para que não te aconteça, querendo o bem, mas ignorando-o, que, correndo, corras para fora do caminho e andes errante por lugares sem caminho, e não pelo caminho (cf. Sl 106,40). Pois o Verbo é luz. Enfim, a explicação das tuas palavras ilumina e dá inteligência aos pequeninos (Sl 118,130). Feliz és, se disseres também tu: A tua palavra é lâmpada para os meus pés e luz para as minhas veredas (Sl 118,105). E não progrediu pouco a tua alma, cuja vontade foi mudada e cuja razão foi iluminada, de modo que quer o bem e o conhece. Numa coisa recebeu a vida; na outra, a vista. Pois, querendo o mal, estava morta; e, ignorando o bem, cega.`
    },
    {
      n: 3,
      texto: `Já vive, já vê, já está firme no bem, mas pela ajuda e pela obra do Verbo. Está de pé, levantada pela mão do Verbo, como sobre dois pés: a devoção e o conhecimento. Está de pé, digo; mas julgue que para ela se disse: Quem julga estar de pé, veja que não caia (1Cor 10,12). Pensas que pode ficar de pé por si mesma aquela que por si mesma não pôde levantar-se? Não penso. Pois quê? Pela palavra do Senhor foram firmados os céus (Sl 32,6), e a terra ficará firme sem o Verbo? Por que, então, se podia ficar firme por si, orava o homem feito de terra: Confirma-me nas tuas palavras (Sl 118,28)? Enfim, ele o tinha experimentado. Dele mesmo foi aquela voz: Empurrado, fui derrubado para cair, mas o Senhor me amparou (Sl 117,13). Perguntas quem é esse que empurra? Não é um só. Empurra o diabo, empurra o mundo, empurra o homem. Perguntas que homem é esse? Cada um é o seu. Não te admires. A tal ponto o homem empurra a si mesmo e se precipita a si mesmo, que não tens por que temer outro que te empurre, se tu mesmo contiveres as tuas próprias mãos. Pois quem, diz, vos poderá fazer mal, se fordes zelosos do bem (1Pd 3,13)? A tua mão é o teu consentimento. Se, sugerindo o diabo ou persuadindo o mundo o que não convém, retiveres o teu consentimento, e não entregares os teus membros como armas à iniquidade, nem deixares reinar o pecado no teu corpo mortal (cf. Rm 6,12-13), mostraste-te zeloso do bem, e a malícia não te fez mal nenhum; vê se não te aproveitou até. Pois está escrito: Faze o bem, e terás o louvor dela (Rm 13,3). Confundidos foram os que buscavam a tua vida (cf. Sl 34,4), e tu cantarás: Se não me dominarem, então serei imaculado (Sl 18,14). Deste, certamente, o sinal de quem é zeloso do bem, se, segundo o conselho do Sábio, tens compaixão da tua alma (Eclo 30,24), se guardas o teu coração com toda a vigilância (Pr 4,23), se, segundo o Apóstolo, te guardas casto (1Tm 5,22). De outro modo, ainda que ganhes o mundo inteiro, se perderes a tua alma, de modo nenhum te julgamos zeloso do bem, como também não te julga o Salvador (Mt 16,26).`
    },
    {
      n: 4,
      texto: `Há, pois, três que ameaçam quem está de pé: destes, o diabo empurra com a inveja da malícia, o mundo com o vento da vaidade, e o homem empurra-se a si mesmo com o peso da sua corrupção. O diabo empurra, mas não derruba, se lhe negares a tua ajuda, o teu consentimento. Enfim, tens isto: Resisti ao diabo, e ele fugirá de vós (Tg 4,7). É ele que, invejoso, empurrou e derrubou os que estavam de pé no paraíso; mas porque consentiram, e não resistiram. É ele que, soberbo, se precipitou a si mesmo do céu, sem ninguém o empurrar; para que saibas quão mais o homem está à beira da sua própria queda, ele a quem pesa o peso da sua própria substância. Também o mundo empurra, porque está posto no maligno (1Jo 5,19). Empurra a todos, mas só derruba os seus amigos, isto é, os que estão de acordo com ele. Não quero ser amigo do mundo, para não cair. Pois quem quer ser amigo deste mundo torna-se inimigo de Deus (Tg 4,4); e não há queda mais grave do que esta. Por aqui se vê bem como o homem é o principal a empurrar-se a si mesmo, pois pode cair pelo seu próprio empurrão sem o dos outros, e não pode cair pelo dos outros sem o seu. A qual destes se deve resistir principalmente? A este, que, quanto mais interior, tanto mais incômodo; que basta sozinho para derrubar, ao passo que os outros sem ele nada podem fazer. Não sem razão o Sábio preferiu ao conquistador de cidades o homem que domina o seu ânimo (Pr 16,32). Isto é muito para ti: precisas de virtude, e não de uma qualquer, mas daquela de que sejas revestido do alto (cf. Lc 24,49). Pois ela, se for perfeita, facilmente torna o ânimo vencedor de si mesmo, e assim invencível em tudo. Pois é um vigor do ânimo que não sabe ceder, para defender a razão. Ou, se preferes, um vigor do ânimo que se mantém imóvel com a razão ou pela razão. Ou assim: um vigor do ânimo que, quanto está em si, obriga ou dirige tudo à razão.`
    },
    {
      n: 5,
      texto: `Quem subirá ao monte do Senhor (Sl 23,3)? Quem quer que empreenda chegar ao cume deste monte, isto é, à perfeição da virtude, saberá certamente quão árdua é a subida e quão vão o esforço sem a ajuda do Verbo. Feliz a alma que ofereceu aos anjos que a contemplam alegria e admiração ao mesmo tempo, a ponto de os ouvir dizer dela: Quem é esta que sobe do deserto, transbordando de delícias, apoiada no seu amado (Ct 8,5)? De outro modo, em vão se esforça, se não se apoia. Apoiando-se nele, porém, há de fortalecer-se até contra si mesma, e, tornada mais forte do que si mesma, obrigará tudo a servir à razão: como bom cocheiro, governará a ira, o medo, a cobiça e a alegria, como um carro do ânimo; e reduzirá ao cativeiro todo afeto carnal (cf. 2Cor 10,5) e o sentir da carne, à ordem da razão, em obediência à virtude. Como não seria tudo possível a quem se apoia naquele que tudo pode? Que voz de tão grande confiança: Tudo posso naquele que me fortalece (Fl 4,13)! Nada torna mais clara a onipotência do Verbo do que fazer onipotentes todos os que esperam nele. Enfim, tudo é possível a quem crê (Mc 9,22). Não é onipotente aquele para quem tudo é possível? Assim o ânimo, se não presumir de si, mas for fortalecido pelo Verbo, poderá certamente dominar-se a si mesmo, de modo que nenhuma injustiça o domine (cf. Sl 118,133). Assim, digo, apoiado no Verbo e revestido da virtude do alto, nenhuma violência, nenhuma fraude, nenhuma sedução poderá já derrubá-lo enquanto está de pé, ou subjugá-lo enquanto domina.`
    },
    {
      n: 6,
      texto: `Queres não temer quem empurra? Não venha a ti o pé da soberba, e a mão de quem empurra não te abalará (cf. Sl 35,12). Ali caíram os que praticam a iniquidade (Sl 35,13). Ali caíram o diabo e os seus anjos, que, embora não empurrados de fora, foram contudo expulsos, e não puderam ficar de pé. Enfim, não permaneceu na verdade (cf. Jo 8,44) aquele que não se apoiou no Verbo, que confiou na sua própria força. E talvez por isso tenha querido sentar-se, porque não conseguiu ficar de pé. Pois dizia: Hei de sentar-me no monte da aliança (Is 14,13). Mas, julgando Deus de outro modo, nem ficou de pé nem se sentou, mas caiu, como diz o Senhor: Eu via Satanás cair do céu como um raio (Lc 10,18). Portanto, quem está de pé, se não quer cair, não confie em si, mas apoie-se no Verbo. É o Verbo que diz: Sem mim nada podeis fazer (Jo 15,5). Assim é: sem o Verbo não podemos nem levantar-nos para o bem, nem ficar firmes no bem. Tu, pois, que estás de pé, dá glória ao Verbo e diz: Firmou os meus pés sobre a rocha e dirigiu os meus passos (Sl 39,3). É necessário que sejas sustentado pela força daquele por cuja mão és levantado. Isto, a propósito do que disse: que precisamos do Verbo, para nos apoiarmos nele e termos virtude.`
    },
    {
      n: 7,
      texto: `Agora deve ver-se o que também lembrei: que é pelo Verbo que somos reformados para a sabedoria. O Verbo é virtude, o Verbo é sabedoria (cf. 1Cor 1,24). Tome, pois, a alma a virtude da Virtude e a sabedoria da Sabedoria, e atribua um e outro dom só ao Verbo. De outro modo, se se arrogar uma e outra, ou qualquer delas, como vindas de outra parte, negue também que o riacho nasce da fonte, o vinho da videira, ou a luz da luz. Palavra fiel: Se alguém, diz, tem falta de sabedoria, peça-a a Deus, que dá a todos com generosidade e sem censurar, e ela lhe será dada (Tg 1,5). Isto diz ele. Eu, porém, não pensaria de outro modo sobre a virtude. A virtude é parente da sabedoria. A virtude é dom de Deus, e deve contar-se entre os dons excelentes, descendo também ela do alto, do Pai do Verbo (cf. Tg 1,17). E, se alguém julgar que ela é em tudo o mesmo que a sabedoria, não o nego — mas no Verbo, não na alma. Pois as coisas que no Verbo, pela singular simplicidade da natureza divina, são uma só, não têm na alma um só efeito, mas acomodam-se, como coisas diversas, às várias e diversas necessidades dela, para serem participadas. Segundo esta razão, certamente, uma coisa é o ânimo ser movido pela virtude, e outra ser governado pela sabedoria; uma coisa é dominar com força, outra deleitar-se na suavidade. Pois, embora a sabedoria seja poderosa e a virtude suave, para dar a cada palavra o seu significado próprio, o vigor mostra a virtude, e a tranquilidade do ânimo, com uma certa suavidade espiritual, mostra a sabedoria. Penso que foi esta que o Apóstolo designou quando, depois de muitas exortações pertencentes à virtude, acrescentou o que é da sabedoria: Na suavidade, no Espírito Santo (2Cor 6,6). Estar de pé, resistir, repelir a força com a força, que se contam entre as partes da virtude, são honra, sim, mas também trabalho. Pois não é o mesmo defender com trabalho a tua honra e possuí-la em paz. Não é o mesmo ser movido pela virtude e gozar da virtude. Tudo o que a virtude elabora com trabalho, a sabedoria o goza; e o que a sabedoria ordena, delibera e modera, a virtude o executa.`
    },
    {
      n: 8,
      texto: `Escreve a sabedoria no tempo livre, diz o Sábio (Eclo 38,25). Os ócios da sabedoria são, pois, os seus negócios; e quanto mais ociosa a sabedoria, tanto mais exercitada no seu gênero. Pelo contrário, a virtude exercitada é mais ilustre, e tanto mais provada quanto mais ativa. E, se alguém definir a sabedoria como o amor da virtude, não me parece desviar-se da verdade. Onde há amor, não há trabalho, mas sabor. E talvez a sabedoria tire o nome do sabor, porque, juntando-se à virtude como um tempero, a torna saborosa, ela que por si mesma se sentia de certo modo insossa e áspera. Nem julgaria repreensível quem definisse a sabedoria como o sabor do bem. Este sabor perdemo-lo quase desde a própria origem da nossa raça. Desde que o veneno da antiga serpente infeccionou o paladar do coração, prevalecendo o sentir da carne, a alma começou a não achar gosto no bem, e insinuou-se nela um sabor nocivo. Enfim, os sentidos e os pensamentos do homem são inclinados para o mal desde a juventude (Gn 8,21), isto é, desde a insipiência da primeira mulher. Assim, a insipiência da mulher excluiu o sabor do bem, porque a malícia da serpente enganou a insipiência da mulher. Mas por onde a malícia pareceu ter vencido por algum tempo, por aí se lamenta de ter sido vencida para sempre. Pois eis que de novo a sabedoria encheu o coração e o corpo de uma mulher, para que nós, que por uma mulher fomos deformados na insipiência, por uma mulher sejamos reformados para a sabedoria. E agora a sabedoria vence continuamente a malícia nas mentes em que entra, exterminando com um sabor melhor o sabor do mal que aquela introduziu. Entrando, a sabedoria, enquanto torna insosso o sentir da carne, purifica a inteligência, cura e restaura o paladar do coração. Com o paladar são, já tem gosto o bem, tem gosto a própria sabedoria, e não há bem melhor do que ela.`
    },
    {
      n: 9,
      texto: `Quantas coisas boas se fazem sem que tenham gosto para quem as faz! Pois são levados a elas não pelo gosto do bem, mas pela razão, ou por alguma ocasião, ou pela necessidade; e, ao contrário, a muitos não têm gosto os males que fazem, mas são induzidos a eles pelo medo ou pela cobiça de alguma coisa, mais do que pelo gosto do mal. Mas os que passaram ao afeto do coração ou são sábios, e deleitam-se com o próprio gosto do bem; ou são malignos, e comprazem-se na própria malícia, mesmo sem os aliciar a esperança de outro proveito. Pois que é a malícia, senão o gosto do mal? Feliz a mente que o gosto do bem e o ódio do mal tomaram por inteiro. Isto é ser reformado para a sabedoria; isto é experimentar felizmente a vitória da sabedoria. Pois em que se prova mais claramente que a sabedoria vence a malícia do que quando, excluído o gosto do mal, que não é outra coisa senão a própria malícia, se sente um gosto íntimo do bem ocupar com toda a suavidade o íntimo da mente? Assim, é próprio da virtude suportar com fortaleza as tribulações; da sabedoria, alegrar-se nas tribulações (cf. Rm 5,3). Fortalecer o teu coração e esperar o Senhor (cf. Sl 26,14) é da virtude; saborear e ver como o Senhor é suave (cf. Sl 33,9) é da sabedoria. E, para que um e outro bem se tornem mais claros pela sua própria natureza: a moderação do ânimo prova o sábio; a constância mostra o homem de virtude. E bem vem a sabedoria depois da virtude, porque a virtude é como um fundamento estável sobre o qual a sabedoria edifica para si a sua casa (cf. Pr 9,1). Mas era preciso que precedesse o conhecimento do bem, porque não há comunhão entre a luz da sabedoria e as trevas da ignorância. E era preciso também a boa vontade, porque a sabedoria não entrará numa alma malévola (Sb 1,4).`
    },
    {
      n: 10,
      texto: `Se, pois, na mudança da vontade se viu a vida restituída à alma, na instrução a saúde, na virtude a estabilidade, e enfim na sabedoria a maturidade, resta que lhe encontremos a beleza, sem a qual não pode agradar àquele que é o mais belo dos filhos dos homens (cf. Sl 44,3). Enfim, ela ouve: O rei desejará a tua beleza (Sl 44,12). Quantos bens da alma enumeramos, dons do Verbo: a boa vontade, a ciência, a virtude, a sabedoria; e não se lê que o Verbo rei deseje nenhum deles, mas só: O rei, diz, desejará a tua beleza. Diz o Profeta: O Senhor reina, revestiu-se de beleza (Sl 92,1). Como não havia de desejar para a sua imagem e esposa uma veste semelhante? Certamente, tanto mais cara lhe será quanto mais semelhante lhe for. Em que está, pois, a beleza da alma? Talvez naquilo que se chama honestidade? Pensemos assim por ora, se não ocorrer coisa melhor. Sobre a honestidade, interrogue-se a conduta exterior; não que a honestidade venha dela, mas manifesta-se por ela. Pois na consciência está a sua morada e a sua origem. Pois o seu esplendor é o testemunho da consciência (cf. 2Cor 1,12). Nada há de mais claro do que esta luz, nada de mais glorioso do que este testemunho, quando a verdade brilha na mente e a mente se vê na verdade. Mas como se vê? Pudica, modesta, temerosa, circunspecta, sem admitir absolutamente nada que anule a glória da consciência que dá testemunho; sem ter consciência de nada que a faça corar diante da presença da verdade, que a obrigue a desviar o rosto, como confundido e ofuscado pela luz de Deus. É isto, sim, isto é aquela beleza que, acima de todos os bens da alma, deleita os olhos divinos; e nós a chamamos e definimos como honestidade.`
    },
    {
      n: 11,
      texto: `E, quando o esplendor desta beleza tiver enchido mais abundantemente o íntimo do coração, é necessário que saia para fora, como a lâmpada escondida debaixo do alqueire (cf. Mt 5,15) — ou antes, como a luz que brilha nas trevas (cf. Jo 1,5), que não sabe esconder-se. E, quando ela resplandece e como que irrompe com os seus raios, o corpo, imagem da mente, recebe-a e difunde-a pelos membros e pelos sentidos, de modo que dela reluzam toda ação, a palavra, o olhar, o andar, o riso — se é que há riso — mesclado de gravidade e cheio de honestidade. Quando os movimentos, gestos e usos destes e dos outros membros e sentidos se mostrarem sérios, puros, modestos, livres de toda insolência e lascívia, alheios tanto à leviandade como à preguiça, ajustados à equidade, prontos para a piedade, a beleza da alma será manifesta — contanto, porém, que não haja dolo no seu espírito (cf. Sl 31,2). Pois pode acontecer que tudo isto seja simulado, e não se mova assim pela abundância do coração. E, para que esta beleza da alma resplandeça mais, defina-se, se vos agrada, a própria honestidade, na qual julgamos que ela se deve pôr: a nobreza da mente, solícita em conservar, com a boa consciência, a integridade da boa fama. Ou, segundo o Apóstolo: Procurar o bem não só diante de Deus, mas também diante dos homens (2Cor 8,21). Feliz a mente que se reveste desta beleza da castidade e como que de uma brancura de inocência celeste, pela qual reivindica para si a gloriosa conformidade, não com o mundo, mas com o Verbo, do qual se lê que é a brancura da vida eterna (Sb 7,26), o esplendor e a figura da substância de Deus (Hb 1,3).`
    },
    {
      n: 12,
      texto: `A partir deste degrau, a alma que é assim já ousa pensar nas núpcias. Como não ousaria, vendo-se tão pronta para o casamento quanto se vê semelhante? Não a aterra a altura, à qual a semelhança a associa, o amor a reconcilia, a profissão a desposa. A fórmula da profissão é esta: Jurei e decidi guardar os juízos da tua justiça (Sl 118,106). Seguindo-a, diziam os apóstolos: Eis que nós deixamos tudo e te seguimos (Mt 19,27). Semelhante é aquilo que, dito do casamento carnal, significou o casamento espiritual de Cristo e da Igreja: Por isso o homem deixará seu pai e sua mãe e se unirá à sua mulher, e serão os dois uma só carne (Ef 5,31-32); e, no Profeta, o gloriar-se da desposada: Para mim, porém, é bom unir-me a Deus, pôr no Senhor Deus a minha esperança (Sl 72,28). Quando, pois, vires uma alma que, deixando tudo, se une ao Verbo com todos os seus desejos, vive para o Verbo, se governa pelo Verbo, concebe do Verbo o que dá à luz para o Verbo; que pode dizer: Para mim, viver é Cristo, e morrer é lucro (Fl 1,21): considera-a esposa, casada com o Verbo. Confia nela o coração do seu marido (Pr 31,11), sabendo que é fiel aquela que, por ele, desprezou tudo e considera tudo como esterco, para o ganhar a ele (cf. Fl 3,8). Assim conhecia ele aquele de quem dizia: Este é para mim um vaso de eleição (At 9,15). Mãe verdadeiramente piedosa e fiel ao seu marido era a alma de Paulo, quando dizia: Filhinhos meus, por quem sofro de novo as dores do parto, até que Cristo seja formado em vós (Gl 4,19).`
    },
    {
      n: 13,
      texto: `Mas repara que no casamento espiritual há dois modos de dar à luz, e por isso também descendências diferentes, mas não contrárias: quando as santas mães, ou pregando, dão à luz almas, ou, meditando, dão à luz inteligências espirituais. Neste último modo, por vezes, sai-se de si e afasta-se até dos sentidos corporais, de modo que não se sente a si mesma a alma que sente o Verbo. Isto acontece quando a mente, atraída pela doçura inefável do Verbo, de certo modo se furta a si mesma, ou antes, é arrebatada e escapa de si mesma, para gozar do Verbo. De um modo é afetada a mente que dá fruto para o Verbo, e de outro a que goza do Verbo. Ali a solicita a necessidade do próximo; aqui a convida a suavidade do Verbo. Alegre, sem dúvida, está a mãe com os filhos; mas mais alegre a esposa nos abraços. Queridos são os filhos, penhores do amor; mas os beijos deleitam mais. Bom é salvar muitos; mas sair de si e estar com o Verbo é muito mais agradável. Mas quando acontece isto, ou por quanto tempo? Doce comércio, mas momento breve e experiência rara. É isto o que me lembro de ter dito acima, depois das outras coisas: que a alma busca o Verbo para gozar dele e ter alegria.`
    },
    {
      n: 14,
      texto: `Talvez alguém continue a perguntar-me ainda: que é gozar do Verbo? Respondo: procure antes alguém que o tenha experimentado, e pergunte a ele. Ou, se me fosse dado experimentá-lo, pensas que eu poderia exprimir o que é inefável? Ouve quem o experimentou: Se saímos de nós, diz, é por Deus; se estamos sóbrios, é por vós (2Cor 5,13). Isto é: uma coisa tenho com Deus, sendo só Deus testemunha; outra convosco. Aquilo me foi dado experimentar, mas de modo nenhum dizer; isto, porém, condescendo a vós de tal modo que eu o possa dizer e vós o possais entender. Ó tu, quem quer que sejas, que tens curiosidade de saber o que é isto, gozar do Verbo: prepara-lhe não o ouvido, mas a mente. Não o ensina a língua, mas a graça. Esconde-se aos sábios e prudentes, e revela-se aos pequeninos (cf. Mt 11,25). Grande, irmãos, grande e sublime virtude é a humildade, que merece o que não se ensina, digna de alcançar o que não se pode aprender, digna de conceber pelo Verbo e do Verbo o que ela mesma não pode explicar com as suas palavras. Por quê? Não porque assim o tenha merecido, mas porque assim aprouve (cf. Mt 11,26) diante do Pai do Verbo, esposo da alma, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
