SERMOES.sermao({
  id: 'bernardo-cantico-41',
  colecao: 'bernardo-cantico',
  ordem: 41,
  numero: 'XLI',
  titulo: 'De como a esposa recebe, enquanto espera, uma grande consolação da contemplação da claridade divina, antes de chegar à visão clara',
  fonte: 'Qualiter sponsa recipit interim magnam consolationem',
  argumento: `O pescoço da esposa não é enfeitado com colares: é ele mesmo como os colares. Bernardo vê no pescoço o entendimento, por onde passa para dentro da alma o alimento do espírito; o entendimento puro brilha pela própria verdade e não precisa, como o dos filósofos e hereges, de se pintar com palavras e silogismos.

Depois vêm os brincos de ouro marchetados de prata, prometidos no plural: quem fala são os companheiros do esposo, os anjos. Enquanto se caminha pela fé, instrui-se o ouvido, degrau para a vista. Aqui está uma das páginas mais finas do sermonário: quando a verdade brilha de relance na mente em êxtase, surgem logo, não se sabe de onde, imagens que a velam, para que a alma a suporte e a possa comunicar. O ouro é a sabedoria; a prata, a eloquência. A esposa queria o repouso da contemplação e recebe o trabalho da pregação, como Jacó recebeu Lia em lugar de Raquel: é preciso às vezes interromper os beijos pelos peitos que amamentam.

Tradução feita do texto latino de Migne (PL 183, 984-987).`,
  pontos: [
    {
      n: 1,
      texto: `O teu pescoço é como os colares (Ct 1,9). Costuma-se enfeitar o pescoço com colares, não compará-lo a eles. Mas façam isso aquelas que, por não terem beleza própria, precisam de mendigá-la de fora, para fingirem que são formosas. Pois o pescoço da esposa é em si tão formoso, e tão graciosamente formado como que pela natureza, que não precisa de adorno de fora. Que necessidade tem de se pintar com cores emprestadas quem se basta com a sua beleza própria e como que inata, a tal ponto que pode igualar o brilho dos próprios colares que se procuram para enfeitar? Foi isto, sem dúvida, que quis dar a entender quem não disse que do pescoço pendem colares, como é costume, mas que ele mesmo é como os colares. Não devemos agora invocar o Espírito Santo, para que, assim como por bondade nos concedeu encontrar as faces espirituais da esposa, se digne também mostrar-nos o seu pescoço espiritual? E ao meu entendimento — pois cabe-me dizer o que sinto — nada aparece, por ora, mais verossímil nem mais provável do que designar-se com o nome de pescoço o próprio entendimento da alma. Também tu, creio, o aprovarás, se reparares na razão da semelhança. Não te parece, com efeito, que o entendimento faz de certo modo as vezes do pescoço, pois por ele a tua alma faz passar para dentro de si os alimentos vitais do espírito e os transfere para umas como entranhas, que são os seus costumes e afetos? Este pescoço da esposa, pois, isto é, o entendimento puro e simples, como resplandece bastante por si mesmo com a verdade nua e aberta, não precisa de adorno; antes, ele mesmo, como um colar precioso, adorna graciosamente a alma, e por isso é descrito como semelhante aos próprios colares. Bom colar é a verdade, bom colar é a pureza ou simplicidade, e bom colar, sem dúvida, é saber com sobriedade (cf. Rm 12,3). O entendimento dos filósofos ou dos hereges não tem em si este brilho de pureza e de verdade; e por isso cuidam muito de colori-lo e pintá-lo com os enfeites das palavras e as astúcias dos silogismos, para que, se aparecer nu, não apareça também a torpeza do falso.`
    },
    {
      n: 2,
      texto: `Segue-se: Faremos para ti brincos de ouro, marchetados de prata (Ct 1,10). Se tivesse dito "farei", no singular, e não "faremos", no plural, eu afirmaria absolutamente e sem hesitar que também isto o diz o esposo. Mas agora vê se não o atribuiríamos com mais propriedade aos companheiros dele, que como que consolam a esposa com esta promessa: até que ela chegue à visão daquele por cujo desejo tanto arde, eles lhe farão brincos belos e preciosos, que são enfeites das orelhas. E isto, na minha opinião, porque a fé vem pelo ouvido (Rm 10,17); e, enquanto se caminha pela fé e não pela visão (2Cor 5,7), deve-se cuidar mais de instruir o ouvido do que de exercitar a vista. Pois em vão se aplica um olho que não foi purificado pela fé, já que só aos puros de coração se promete a possibilidade de ver (Mt 5,8). E está escrito: Purificando pela fé os seus corações (At 15,9). Como, pois, a fé vem pelo ouvido, e dela vem a purificação da vista, com razão eles se aplicavam a enfeitar as orelhas, já que o ouvido, como a razão ensinou, é preparação para a vista. Tu, dizem eles, ó esposa, anseias por contemplar a claridade do amado; mas isso é de outro tempo. Por agora, damos enfeites às tuas orelhas, o que te será entretanto consolação, e também preparação para aquilo mesmo que pedes; como se lhe dissessem aquela palavra do profeta: Ouve, filha, e vê (Sl 44,11). Desejas ver; mas ouve primeiro. O ouvido é um degrau para a vista. Ouve, pois, e inclina o teu ouvido aos enfeites que te fazemos, para que, pela obediência do ouvido, chegues à glória da visão. Nós damos ao teu ouvido gozo e alegria (cf. Sl 50,10). Pois dar à vista — na qual está a plenitude do gozo e o cumprimento do teu desejo — não é nosso, mas daquele a quem a tua alma ama. Ele, para que o teu gozo seja pleno (cf. Jo 16,24), se mostrará a ti; ele te encherá de alegria com o seu rosto. Tu, entretanto, recebe da nossa mão estes brincos para tua consolação; mas as delícias estão na sua direita até o fim (cf. Sl 15,11).`
    },
    {
      n: 3,
      texto: `É preciso notar que brincos lhe oferecem: De ouro, diz, e marchetados de prata. O ouro é o fulgor da divindade; o ouro é a sabedoria que vem do alto (Tg 3,17). Com este ouro, aqueles a quem cabe este ofício — os ourives do alto — prometem modelar umas como insígnias brilhantes da verdade e pô-las nos ouvidos interiores da alma. E isto não julgo que seja outra coisa senão tecer certas imagens espirituais e, nelas, levar aos olhos da alma que contempla os sentidos puríssimos da sabedoria divina, para que veja, ao menos como num espelho e em enigma, o que ainda de modo nenhum pode contemplar face a face (1Cor 13,12). São coisas divinas, e de todo desconhecidas a quem não as experimentou, as que dizemos: como é que, neste corpo mortal, estando ainda em vigor a fé e ainda não manifesta a substância da luz transparente, a contemplação da pura verdade às vezes já ousa desempenhar dentro de nós o seu papel, ao menos em parte; de modo que também a algum de nós, a quem isto tiver sido dado do alto, seja lícito tomar para si aquela palavra do Apóstolo: Agora conheço em parte; e ainda: Em parte conhecemos, e em parte profetizamos (1Cor 13,12.9). E, quando alguma coisa mais divina brilhou de relance, como na rapidez de um relâmpago, na mente arrebatada em êxtase, logo — não sei de onde —, seja para temperar o esplendor excessivo, seja para servir ao ensino, apresentam-se certas imagens de coisas inferiores, adaptadas convenientemente aos sentidos infundidos por Deus; e com elas aquele raio puríssimo e esplendidíssimo da verdade, como que envolto em sombra, torna-se mais suportável para a própria alma e mais acessível àqueles a quem ela o quiser comunicar. Julgo, porém, que estas imagens se formam em nós por sugestão dos santos anjos, assim como, pelo contrário, não há dúvida de que as sugestões contrárias e más são introduzidas pelos anjos maus (cf. Sl 77,49).`
    },
    {
      n: 4,
      texto: `E talvez venha daí aquele espelho e enigma, como disse, pelo qual o Apóstolo via (1Cor 13,12), fabricado como que pelas mãos dos anjos com estas imagens puras e belas; de modo que entendamos que é de Deus o que se vê puro e sem nenhuma fantasia de imagens corporais, e atribuamos ao ministério dos anjos qualquer imagem elegante com que isso apareça dignamente revestido. É o que parece ter indicado mais expressamente outra tradução, que diz: Faremos para ti imagens de ouro, obra de ourives, com incrustações de prata (Ct 1,10). É o mesmo "com incrustações de prata" e "marchetados de prata". E nisto me parece significar que não só as imagens são sugeridas interiormente pelos anjos, mas que também o brilho da expressão é fornecido por eles exteriormente, para que, adornadas de modo conveniente e gracioso, sejam recebidas pelos ouvintes com mais facilidade e mais prazer. E, se disseres: Que tem a ver a palavra com a prata?, diz-te o profeta: As palavras do Senhor são palavras puras, prata provada no fogo (Sl 11,7). Assim, pois, aqueles espíritos celestes servidores fazem para a esposa, peregrina na terra, brincos de ouro marchetados de prata.`
    },
    {
      n: 5,
      texto: `Mas vê como ela deseja uma coisa e recebe outra: a quem se esforça pelo repouso da contemplação impõe-se o trabalho da pregação; a quem tem sede da presença do esposo, confia-se o cuidado de gerar e alimentar os filhos do esposo. E isto não lhe acontece só agora; mas também outra vez, se bem me lembro, quando suspirava pelos abraços e beijos do esposo, responderam-lhe: Porque os teus peitos são melhores que o vinho (Ct 1,1); para que por aí entendesse que era mãe e que era chamada de volta a dar leite aos pequenos e a nutrir os filhos. Talvez também em outros lugares deste cântico possas tu mesmo notar isto, se não fores preguiçoso para investigar. Não foi isto prefigurado outrora no santo patriarca Jacó, quando, frustrado nos abraços de Raquel, tão desejados e tão longamente esperados, recebeu contra a vontade e sem saber, em lugar da estéril e bela, a fecunda de olhos baços (Gn 29,17-25)? Assim, pois, agora a esposa, desejando saber e perguntando onde o amado apascenta e repousa nas horas do meio-dia, recebe em lugar disso brincos de ouro marchetados de prata — isto é, a sabedoria com a eloquência —, sem dúvida para a obra da pregação.`
    },
    {
      n: 6,
      texto: `Com isto aprendemos que muitas vezes se devem interromper os doces beijos por causa dos peitos que amamentam; e que ninguém deve viver para si, mas para todos. Ai dos que receberam o dom de bem pensar e de bem falar de Deus, se tomam a piedade por fonte de lucro (cf. 1Tm 6,5); se convertem em vanglória o que tinham recebido para empregar em ganhos para Deus; se, tendo pensamentos altivos, não se acomodam aos humildes (cf. Rm 12,16)! Tremam diante do que se lê no profeta, onde o Senhor diz: Dei-lhes o meu ouro e a minha prata, e eles, com a minha prata e o meu ouro, fizeram Baal (Os 2,8). Tu, pois, ouve o que a esposa, tendo recebido de um lado a repreensão e do outro a promessa, respondeu. Pois nem se ensoberbece com as promessas, nem se irrita com a recusa; mas, como está escrito: Repreende o sábio, e ele te amará (Pr 9,8); e ainda, quanto aos dons e às promessas: Quanto maior fores, tanto mais te humilha em tudo (Eclo 3,20). Uma e outra coisa ficarão mais claras pela sua resposta. Mas, se vos parece bem, deixemos o exame dela para o princípio de outro sermão; e, pelo que foi dito, glorifiquemos o Esposo da Igreja, nosso Senhor Jesus Cristo, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
