SERMOES.sermao({
  id: 'bernardo-cantico-67',
  colecao: 'bernardo-cantico',
  ordem: 67,
  numero: 'LXVII',
  titulo: 'Do admirável afeto de amor da esposa, que ela deixa transbordar por amor de Cristo, seu esposo',
  fonte: 'De mirabili affectu dilectionis sponsae',
  argumento: `Com o versículo "O meu amado para mim, e eu para ele" começam as palavras da esposa. Bernardo nota que a frase está incompleta: deixada pelo esposo depois de tantas palavras, a esposa fala consigo mesma, e o que diz não é um discurso ordenado, mas o transbordar de um coração repleto — como a eructação de quem está saciado, que sai sem que se queira e traz o odor do vaso de onde vem. Assim "eructaram" Moisés, Isaías, Jeremias, Davi, João e Paulo; e Bernardo, pecador, dá graças por ser admitido ao menos a sentir-lhes o perfume, enquanto espera: o pecador nada espera, o justo espera, o bem-aventurado já possui.

Para dar à frase um sentido acessível a todos, propõe subentender "está atento": "O meu amado está atento a mim, e eu a ele", como no salmo: "Esperei, esperei o Senhor, e ele esteve atento a mim". Ao contrário do Profeta, a esposa põe primeiro a ação do amado, confessando a graça que se antecipa; mais adiante, invertendo a ordem, confessará também a graça que vem depois, atribuindo tudo à graça. A Sinagoga, que quis estabelecer a sua própria justiça, foi repudiada; a Igreja foi desposada na fé e na misericórdia. O que significa ser objeto da atenção de Deus fica para o sermão seguinte.

Tradução feita do texto latino de Migne (PL 183, 1102-1108).`,
  pontos: [
    {
      n: 1,
      texto: `O meu amado para mim, e eu para ele (Ct 2,16). Até aqui, as palavras do esposo. Esteja ele presente, para que possamos investigar dignamente as palavras da sua esposa, para glória dele e salvação nossa. Pois não são tais que possam ser consideradas e examinadas por nós como convém, se ele mesmo não for o guia da palavra. São, com efeito, tão fecundas em sentidos e tão profundas em mistérios quanto são suaves em graça. A que as compararei? Por ora, a um desses pratos de banquete que se distinguem por uma tripla qualidade: delicioso ao paladar, sólido para nutrir, eficaz como remédio. Assim, digo, assim é cada palavra da esposa: pela suavidade do seu som, acaricia o afeto; pela abundância dos sentidos, engorda e nutre a mente; e pela altura dos mistérios — que, quanto mais exercitam a inteligência, mais a assustam —, cura de modo admirável o inchaço da ciência que incha (cf. 1Cor 8,1). Pois, se por acaso algum desses que se julgam sabidos se entregar com demasiada curiosidade ao exame destas palavras, quando vir sucumbirem as forças do seu engenho e sentir toda a sua inteligência reduzida ao cativeiro (cf. 2Cor 10,5), não se verá obrigado, humilhado, a dizer aquela palavra: A tua ciência é admirável demais para mim; é elevada, e não poderei alcançá-la (Sl 138,6)? E agora, que sinal de grande suavidade traz já o começo das suas palavras! Vê que começo deu: O meu amado para mim, diz, e eu para ele. Parece uma palavra simples, porque soa com suavidade; mas disto se verá depois.`
    },
    {
      n: 2,
      texto: `Por ora, começa pelo amado e continua falando do amado, mostrando que nada mais sabe senão o amado. Está claro de quem fala; com quem fala, nem tanto. Pois não nos é permitido pensar que falasse com ele mesmo, visto que ele já não estava presente. E disso não há dúvida: logo em seguida parece chamá-lo de volta e como que gritar-lhe pelas costas: Volta, meu amado (Ct 2,17). Daí somos levados a não conjecturar outra coisa senão que ele, terminadas as suas palavras, se ausentou de novo, segundo o seu costume, e ela ficou, ainda assim, falando daquele que nunca está ausente para ela. Assim é: conservou na boca aquele que não se afastava do coração, nem mesmo quando se afastava. O que sai da boca vem do coração (cf. Mt 15,18), e a boca fala da abundância do coração (Lc 6,45). Fala, pois, do amado, como verdadeiramente amada e verdadeiramente digna de ser amada, porque ama muito (cf. Lc 7,47). Perguntamos com quem fala: pois de quem, já sabemos. E não se apresenta ninguém, senão talvez as jovenzinhas, que não podem afastar-se da mãe quando o esposo se retira. Mas penso que é melhor entender que falou assim consigo mesma, e não com outra pessoa, sobretudo porque a própria frase se mostra truncada e pouco coerente, de todo insuficiente para dar a entender algo a quem ouve — que é a principal razão por que falamos uns com os outros. O meu amado para mim, diz, e eu para ele. Nada mais? A frase fica suspensa; ou melhor, não fica suspensa, fica incompleta. O ouvinte fica em suspenso: não é instruído, mas é despertado.`
    },
    {
      n: 3,
      texto: `Que é isto que diz: ele para mim, e eu para ele? Não sabemos o que diz (cf. Jo 16,18), porque não sentimos o que ela sente. Ó alma santa, que é ele, o teu, para ti? E que és tu para ele? Que é, pergunto, este dar e retribuir que corre entre vós com tanta familiaridade e tanto favor? Ele para ti, e tu, por tua vez, para ele. Mas o quê? És tu para ele o mesmo que ele é para ti, ou outra coisa? Se falas para nós, se falas para que te entendamos, diz claramente o que sentes. Até quando nos manterás em suspenso (cf. Jo 10,24)? Ou, como diz o profeta, o teu segredo é só teu (cf. Is 24,16)? Assim é: falou o afeto, não a inteligência, e por isso não para a inteligência. Para quê, então? Para nada; só que, admiravelmente deleitada e vivamente tocada pelas palavras que tanto desejava, quando ele terminou, nem pôde calar de todo, nem conseguiu exprimir o que sentia. Pois não falou assim para exprimir, mas para não calar. A boca falou da abundância do coração, mas não à altura dessa abundância. Os afetos têm as suas vozes, pelas quais se traem mesmo sem querer: o medo, por exemplo, vozes medrosas; a dor, vozes de gemido; o amor, vozes alegres. Acaso o pranto dos que sofrem, os soluços ou gemidos dos aflitos, os gritos súbitos e descontrolados dos que são feridos ou dos que se assustam, ou ainda a eructação dos que estão saciados, são criados pelo costume, suscitados pela razão, ordenados pela deliberação, formados pela premeditação? É certo que tais coisas não saem por decisão do ânimo, mas irrompem por um impulso. Assim, o amor ardente e veemente, sobretudo o divino, quando não consegue conter-se dentro de si, não repara em que ordem, com que regra, com que sequência ou com que poucas palavras transborda, contanto que não sinta com isso nenhum prejuízo para si. Às vezes nem precisa de palavras, às vezes nem de voz alguma, contentando-se para isso só com suspiros. Daí vem que a esposa, ardendo de santo amor, e de modo incrível, para obter algum pequeno desafogo do ardor que padece, não considera o que diz nem como o diz; mas, sob a pressão do amor, o que lhe vem à boca não o pronuncia: eructa-o. E como não havia de eructar, assim alimentada e assim repleta?`
    },
    {
      n: 4,
      texto: `Percorre o texto deste canto nupcial desde o princípio até aqui, e vê se em alguma de todas as visitas e falas do esposo lhe foi concedida tanta abundância dele como desta vez; e se alguma vez recebeu da sua boca palavras não só tão numerosas, mas também tão agradáveis. Ela, pois, que tinha saciado de bens o seu desejo (cf. Sl 102,5), que admira se produziu antes uma eructação que uma palavra? E, se te parece que proferiu uma palavra, considera-a eructada, e não preparada nem ordenada de antemão. Pois a esposa não julga uma usurpação aplicar a si o dito do Profeta: O meu coração eructou uma palavra (Sl 44,2), visto estar repleta do mesmo espírito. O meu amado para mim, e eu para ele. Não tem nenhuma sequência; falta alguma coisa à frase. E daí? É uma eructação. Por que procuras numa eructação as junturas das frases, as solenidades do estilo? Que leis ou regras impões tu à tua eructação? Não aceita a tua moderação, não espera de ti composição, não pede conveniência nem oportunidade. Irrompe por si mesma do mais íntimo, não só quando não queres, mas até sem que o saibas, arrancada mais do que emitida. Contudo, a eructação traz um odor, às vezes bom, às vezes mau, conforme as qualidades contrárias dos vasos de onde sobe. Enfim, o homem bom tira do seu bom tesouro o bem, e o mau, o mal (Mt 12,35). Bom vaso é a esposa do meu Senhor, e bom é o odor que dela me chega.`
    },
    {
      n: 5,
      texto: `Graças te dou, Senhor Jesus, que te dignaste admitir-me ao menos a sentir o perfume. Sim, Senhor, pois também os cachorrinhos comem das migalhas que caem da mesa dos seus donos (Mt 15,27). A mim, confesso, cheira bem a eructação da tua amada, e da sua plenitude recebo com gratidão alguma coisa, ainda que pouca. Ela eructa para mim a memória da abundância da tua suavidade (cf. Sl 144,7), e senti o perfume de não sei quê de inefável da tua condescendência e do teu amor nesta palavra: O meu amado para mim, e eu para ele. Que ela, como é justo, se banqueteie e exulte na tua presença e se deleite na alegria (cf. Sl 67,4); contudo, que de tal modo saia de si para ti, que seja sóbria para nós (cf. 2Cor 5,13). Que ela, pois, se encha dos bens da tua casa (cf. Sl 64,5) e beba da torrente das tuas delícias (cf. Sl 35,9); mas, peço-te, que chegue até mim, pobre, ao menos um leve perfume quando ela eructar, depois de saciada. Bem eructou para mim Moisés, e bom é o odor da sua eructação, odor do poder que cria: No princípio, diz, Deus criou o céu e a terra (Gn 1,1). Bem Isaías, pois deu o suavíssimo odor da misericórdia que redime, eructando assim: Entregou a sua vida à morte, e foi contado entre os malfeitores, e ele carregou os pecados de muitos, e intercedeu pelos transgressores (Is 53,12) — para que não perecessem. Que coisa exala tanto a misericórdia? Boa também a eructação da boca de Jeremias; boa a de Davi, que diz: O meu coração eructou uma boa palavra (Sl 44,2). Todos ficaram cheios do Espírito Santo (cf. At 2,4), e, eructando, encheram todas as coisas de bondade. Pedis a eructação de Jeremias? Não a esqueci; já a estava preparando. Bom é esperar em silêncio a salvação do Senhor (Lm 3,26). É dele, não me engano; aproximai-a do nariz: a suavidade da justiça que recompensa, que ela traz consigo, vence o bálsamo. Quer que eu, sofrendo pela justiça, espere a recompensa para o futuro, e não a receba no presente, porque a recompensa da justiça é a salvação, não do mundo, mas do Senhor. Se tardar, diz, espera-o (Hab 2,3); e não murmures, porque é bom esperar em silêncio. Farei, pois, o que ele exorta: esperarei o Senhor, meu Salvador (cf. Mq 7,7).`
    },
    {
      n: 6,
      texto: `Mas sou pecador, e ainda me resta um longo caminho (cf. 1Rs 19,7), porque a salvação está longe dos pecadores (Sl 118,155). Não murmurarei, contudo: por ora me consolarei com o perfume. O justo se alegrará no Senhor (Sl 63,11), experimentando pelo gosto o que eu sinto pelo olfato. Aquele que o justo contempla, o pecador espera; e esperar é sentir o perfume. Pois a expectativa da criação, diz, espera a revelação dos filhos de Deus (Rm 8,19). Contemplar, por sua vez, é saborear e ver como o Senhor é suave (cf. Sl 33,9). Ou, antes, é justo quem espera, e bem-aventurado quem já possui? Enfim, a espera dos justos é alegria (Pr 10,28). Pois o pecador nada espera. E é pecador justamente porque, não só preso aos bens presentes, mas contente com eles, nada espera para o futuro, surdo àquela voz: Espera-me, diz o Senhor, no dia da minha ressurreição, no futuro (Sf 3,8). E por isso Simeão era justo (cf. Lc 2,25): porque esperava Cristo e já lhe sentia o perfume no espírito, a ele, a quem ainda não adorava na carne. E foi bem-aventurado na sua espera, porque pelo perfume da espera chegou ao gosto da contemplação. Enfim, diz: Os meus olhos viram a tua salvação (Lc 2,30). Justo também Abraão, que também ele esperou ver o dia do Senhor, e não foi confundido na sua espera: pois viu, e alegrou-se (Jo 8,56). Justos os apóstolos, quando ouviam: E vós, sede semelhantes a homens que esperam o seu senhor (Lc 12,36).`
    },
    {
      n: 7,
      texto: `E como não seria justo também Davi, quando dizia: Esperei, esperei o Senhor (Sl 39,2)? É ele o quarto dos que nomeei como tendo eructado para mim, e eu quase o deixava de lado. Não convinha. Este abriu a boca e aspirou o espírito (Sl 118,131), e, saciado, não só eructou, mas também cantou. Bom Jesus! Quanta suavidade derramou este nas minhas narinas e nos meus ouvidos com a sua eructação e o seu canto sobre o óleo de alegria com que Deus, o teu Deus, te ungiu de preferência aos teus companheiros; sobre a mirra, o aloés e a cássia que exalam as tuas vestes, desde os palácios de marfim, com que te alegraram as filhas dos reis na tua honra (Sl 44,8-10)! Oxalá me concedas a graça de ir ao encontro de tão grande profeta e amigo teu no dia da solenidade e da alegria, quando ele sair do teu tálamo cantando o seu canto nupcial com o saltério harmonioso e a cítara (cf. Sl 80,3), transbordando de delícias (cf. Ct 8,5), perfumado e perfumando todas as coisas com esse pó de aromas (cf. Ct 3,6)! Naquele dia, ou antes, naquela hora — pois, se alguma vez acontece, é uma hora, e talvez nem sequer uma hora, mas meia hora, segundo aquela palavra da Escritura: Fez-se silêncio no céu por cerca de meia hora (Ap 8,1) —, naquela hora, pois, a minha boca se encherá de alegria, e a minha língua de exultação (cf. Sl 125,2), quando eu sentir que cada um, não digo dos salmos, mas dos versículos, é uma eructação, e perfumada acima de todos os aromas (cf. Ct 4,10). Que há de mais fragrante que a eructação de João, que exala para mim a eternidade, a geração, a divindade do Verbo? Que direi das eructações de Paulo, de quanta suavidade encheram o mundo? Enfim, ele era o bom odor de Cristo em todo lugar (2Cor 2,14-15). As palavras inefáveis, certamente, embora não as profira para que eu as ouça, oferece-as, contudo, para que eu as deseje; e apraz sentir o perfume do que não é permitido ouvir (2Cor 12,4). Pois não sei como, quanto mais se escondem, mais agradam, e com mais avidez ansiamos pelo que nos é negado. Mas repara agora numa coisa semelhante na esposa: como, à maneira de Paulo, neste versículo, nem revela o segredo, nem, contudo, o deixa passar intacto, concedendo algo como que ao nosso olfato, o que talvez julgou não convir por ora ao nosso paladar, seja por nossa indignidade, seja por nossa incapacidade.`
    },
    {
      n: 8,
      texto: `O meu amado para mim, e eu para ele. Sem dúvida, arde neste lugar o amor mútuo de dois; mas nesse amor está, de um lado, a suma felicidade de uma, e, do outro, a admirável condescendência do outro. Pois este acordo, ou este abraço, não é entre iguais. De resto, quem ousaria dizer que sabe claramente de que se gloria ela, por esta prerrogativa do amor, como dado a ela e por ela retribuído, senão quem, por uma singular pureza de mente e santidade de corpo, mereceu experimentar em si mesmo algo semelhante? É coisa dos afetos; e não se chega a ela pelo raciocínio, mas pela conformidade. E quão poucos são os que podem dizer: Nós, porém, contemplando de rosto descoberto a glória do Senhor, somos transformados na mesma imagem, de claridade em claridade, como pelo Espírito do Senhor (2Cor 3,18)!`
    },
    {
      n: 9,
      texto: `Mas, para reduzir o que se lê a alguma forma de entendimento, qualquer que seja — ressalvado, certamente, o segredo singular da esposa, do qual por ora não é dado aproximar-se, sobretudo a gente como nós —, devemos acrescentar alguma coisa, tanto mais acomodada ao senso comum quanto mais usual, que dê às palavras sequência e aos pequeninos entendimento. E a mim parece bastar, para a nossa inteligência grosseira e de certo modo popular, que, ao dizer: O meu amado para mim, subentendamos: está atento; de modo que o sentido seja: O meu amado está atento a mim, e eu a ele. Se bem que não sou o único nem o primeiro a entender assim, pois o Profeta disse antes de mim: Esperei, esperei o Senhor, e ele esteve atento a mim (Sl 39,2). Tens claramente a atenção do Senhor para com o Profeta; e tens também a do Profeta para com o Senhor, quando diz: Esperei, esperei. Pois quem espera está atento, e esperar é estar atento. O sentido é exatamente o mesmo, e as palavras quase as mesmas no Profeta e na esposa; mas no Profeta estão invertidas: ele pôs primeiro o que ela pôs depois, e vice-versa.`
    },
    {
      n: 10,
      texto: `Mas a esposa falou com mais acerto, não apresentando o mérito, mas pondo à frente o benefício, e confessando que a graça do amado se antecipou a ela. E com toda a razão. Pois quem lhe deu primeiro, para ter de ser retribuído (Rm 11,35)? Enfim, ouve o que João pensa disso na sua Epístola: Nisto está o amor, diz: não fomos nós que amamos a Deus, mas foi ele que nos amou primeiro (1Jo 4,10). O Profeta, contudo, embora tenha calado a graça que se antecipa, não a negou; e a graça que vem depois, certamente não a calou. Mas recebe, noutro lugar, uma confissão ainda mais certa dele sobre esta matéria: E a tua misericórdia, diz — falava ao Senhor —, me seguirá todos os dias da minha vida (Sl 22,6). Ouve também, sobre a graça que se antecipa, um conhecimento dele não menos certo e manifesto: O meu Deus, diz, a sua misericórdia se antecipará a mim (Sl 58,11); e, dirigindo-se igualmente ao Senhor: Antecipem-se depressa a nós as tuas misericórdias, porque estamos extremamente pobres (Sl 78,8). Belamente, se não me engano, a esposa, mais adiante, põe estas mesmas palavras, não na mesma ordem, mas seguindo ela também a ordem do Profeta, dizendo assim: Eu para o meu amado, e o meu amado para mim (Ct 6,2). Por que assim? Para mostrar-se tanto mais cheia de graça quanto tudo atribuiu à graça, dando-lhe tanto as primeiras partes como as últimas. De outro modo, como seria cheia de graça, se tivesse alguma coisa que não viesse da graça? Não há por onde a graça entre, onde o mérito já ocupou o lugar. Portanto, a plena confissão da graça assinala a plenitude da própria graça na alma de quem a confessa. Pois, se há nela alguma coisa de próprio, na medida em que há, é necessário que a graça lhe ceda o lugar. Falta à graça tudo o que atribuis aos méritos. Não quero um mérito que exclua a graça. Tenho horror a tudo o que vem de mim, para que eu seja meu; a não ser que seja talvez mais meu aquilo que me faz meu. A graça me restitui a mim mesmo, justificado gratuitamente (cf. Rm 3,24), e assim libertado da servidão do pecado (cf. Rm 6,18). Enfim, onde está o Espírito, aí está a liberdade (2Cor 3,17).`
    },
    {
      n: 11,
      texto: `Ó insensata esposa, a Sinagoga, que, desprezando a justiça de Deus, isto é, a graça do seu esposo, e querendo estabelecer a sua, não se submeteu à justiça de Deus (cf. Rm 10,3)! Por isso a infeliz foi repudiada, e já não é ela a esposa, mas a Igreja, a quem se diz: Desposei-te comigo na fé; desposei-te comigo no juízo e na justiça; desposei-te comigo na misericórdia e nas compaixões (Os 2,19-20). Não foste tu que me escolheste, mas eu te escolhi (cf. Jo 15,16); e, para te escolher, não encontrei méritos teus, mas antecipei-me a ti. Assim, pois, desposei-te comigo na fé, e não nas obras da lei; e desposei-te na justiça, mas na justiça que vem da fé, não da lei (cf. Fl 3,9). Resta que julgues com juízo reto entre mim e ti — o juízo em que te desposei, no qual consta que interveio não o teu mérito, mas o meu querer. E o juízo é este: que não exaltes os teus méritos, não ponhas à frente as obras da lei, não te gabes de ter suportado o peso do dia e o calor (cf. Mt 20,12), tu que, como se sabe, foste desposada antes na fé e na justiça que vem da fé, e também na misericórdia e nas compaixões.`
    },
    {
      n: 12,
      texto: `A que é verdadeiramente esposa reconhece estas coisas e confessa uma e outra graça: primeiro, a que é primeira, pela qual foi antecipada; e depois, também a que vem em seguida. Diz, pois, agora: O meu amado para mim, e eu para ele, atribuindo ao amado o princípio. Mais adiante: Eu, diz, para o meu amado, e o meu amado para mim (Ct 6,2), concedendo-lhe igualmente o acabamento. Vejamos agora o que quer dizer: O meu amado para mim. Se se aceita que subentendamos, como já dissemos, "está atento", como diz o Profeta: Esperei, esperei o Senhor, e ele esteve atento a mim (Sl 39,2), eu sinto nesta palavra não sei quê de modo nenhum pequeno, nem de prerrogativa medíocre. Mas não se deve impor a ouvidos e mentes cansados uma coisa digna de toda a prontidão. Se não vos pesa, adie-se, e não por muito tempo: o sermão de amanhã começará por aí. Apenas orai para que, entretanto, nos guardem das ocupações que se precipitam sobre nós a graça e a misericórdia do esposo da Igreja, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
