SERMOES.sermao({
  id: 'bernardo-cantico-60',
  colecao: 'bernardo-cantico',
  ordem: 60,
  numero: 'LX',
  titulo: 'Da incredulidade dos judeus, com a qual encheram a medida dos seus pais matando Cristo',
  fonte: 'De incredulitate Judaeorum',
  argumento: `A figueira não tem flores: em lugar delas lança os figos verdes, que caem antes de amadurecer e dão lugar aos bons. Bernardo vê nela primeiro o povo em geral, cujos primeiros frutos são grosseiros e terrenos; depois, como o texto fala de uma só figueira, o povo judeu, que, nascido da raiz santa dos patriarcas, nunca se ergueu do chão. Brincando com a palavra latina que designa os figos verdes e quer dizer também "grosseiro", acusa-o com a dureza habitual da polêmica medieval: grosseiro nas ações, nos afetos, no entendimento preso à letra, no culto feito de sangue de animais, até encher a medida dos pais ao matar Cristo.

As vinhas em flor, cujo perfume afugenta as serpentes, são as almas dos primeiros cristãos, cuja boa fama se espalhou por toda parte e atraiu outros à fé — perfume dado, e não vendido. O fruto delas é o martírio. Ou são os patriarcas, que sentiram o perfume de Cristo mas só o deram ao mundo quando ele nasceu. Moralmente, as figueiras são os monges de trato mais suave, que amam sobretudo o próximo; as vinhas, os mais fervorosos e severos, que amam sobretudo a Deus. Figos verdes a lançar fora são o temor servil e a amargura dos pecados, e até a ciência e a profecia, que passarão; só a caridade não passa.

Tradução feita do texto latino de Migne (PL 183, 1066-1070).`,
  pontos: [
    {
      n: 1,
      texto: `A figueira deu os seus figos verdes (Ct 2,13). Este passo depende do que vem antes. Pois tinha dito que chegara o tempo da poda, afirmando-o tanto pelas flores que já apareciam como pela voz da rola que se ouvira. E afirma-o ainda pelo aparecimento dos figos verdes; pois não só pelas flores e pela voz da rola se reconhece o tempo, mas também pela figueira. Pois o ar não deixa de estar mais brando quando a figueira dá os seus figos verdes. A figueira não tem flores; mas, em lugar de flores, lança os figos verdes no tempo em que as outras árvores florescem. E, assim como as flores aparecem e passam, sem servir para nada, a não ser para anunciar o fruto que há de vir, assim também os figos verdes. Nascem, mas caem antes de amadurecer e dão lugar aos que hão de amadurecer, não sendo eles mesmos bons para comer. Também daqui, pois, como disse, o esposo tira a prova do tempo e o argumento para persuadir a esposa a não ter preguiça de ir às vinhas, porque não se perde o trabalho que vem no seu tempo. Assim diz a letra.`
    },
    {
      n: 2,
      texto: `E o espírito? Que vejamos aqui não uma figueira, mas um povo; pois Deus se ocupa dos homens, não das árvores. O povo é verdadeiramente uma figueira: frágil na carne, pequeno no entendimento, humilde no ânimo; e os seus primeiros frutos — para brincarmos um pouco com o nome latino dos figos verdes, grossi — são grosseiros e terrenos. Pois não é próprio do empenho do povo buscar primeiro o reino de Deus e a sua justiça (Mt 6,33), mas, como diz o Apóstolo, pensar nas coisas do mundo, em como agradar às mulheres, ou elas aos maridos (1Cor 7,33-34). Estes terão tribulações da carne (1Cor 7,28); mas não negamos que por fim hão de alcançar os frutos da fé, se tiverem no fim uma boa confissão, e sobretudo se resgatarem com esmolas as obras da carne (cf. Dn 4,24). Os primeiros frutos dos povos, pois, não são frutos, assim como não o são os figos verdes das figueiras. Enfim, se depois derem frutos dignos de penitência — pois não vem primeiro o que é espiritual, mas o que é animal (1Cor 15,46) —, hão de ouvir: Que fruto tivestes então naquelas coisas de que agora vos envergonhais (Rm 6,21)?`
    },
    {
      n: 3,
      texto: `Eu, porém, não julgo que aqui se possa entender livremente qualquer povo: um só é expressamente designado. Pois não disse "deram", como de várias, mas, como de uma só: A figueira deu os seus figos verdes; e esta, a meu ver, é o povo dos judeus. Quantas coisas o Salvador parece dizer contra ela em parábolas no Evangelho! Como aquilo: Um homem tinha uma figueira plantada na sua vinha (Lc 13,6), etc.; e ainda: Vede a figueira e todas as árvores (Lc 21,29); e a Natanael foi dito: Quando estavas debaixo da figueira, eu te vi (Jo 1,48). E de novo amaldiçoa a figueira, porque não encontrou nela fruto (Mc 11,13-14). Bem se diz figueira, porque, embora tenha nascido da boa raiz dos patriarcas, nunca quis crescer para o alto, nunca quis erguer-se do chão, nunca quis corresponder à raiz com a altura dos ramos, a nobreza das flores, a fecundidade dos frutos. Combinas muito mal com a tua raiz, árvore mesquinha, tortuosa, nodosa. Pois a raiz é santa (cf. Rm 11,16). Que aparece nos teus ramos digno dela? A figueira, diz, deu os seus figos verdes. Não os tiraste da raiz nobre, semente má. O que há nela vem do Espírito Santo, e por isso é todo fino e suave. De onde te vêm a ti estes frutos grosseiros? E, na verdade, que não era grosseiro naquele povo? Nem as ações, nem os afetos, nem o entendimento, nem sequer o rito com que prestava culto a Deus. Pois as ações estavam todas nas guerras; os afetos, nos lucros; o entendimento, na espessura da letra; o culto, no sangue de ovelhas e de bois.`
    },
    {
      n: 4,
      texto: `Mas alguém diz: como aquele povo nunca deixou de dar estes frutos grosseiros, nunca houve, então, tempo de poda, porque se diz que é um só o tempo de uma e de outra coisa. Não é assim. Dizemos que as mulheres deram à luz os filhos, não quando estão em trabalho de parto, mas quando já pariram. E dizemos que as árvores deram as suas flores, não quando começam a florir, mas antes quando acabam. Assim também aqui se disse que a figueira deu os seus figos verdes, não quando deu alguns, mas quando deu todos, isto é, quando a produção chegou ao fim. Perguntas em que tempo aconteceu a esse povo este acabamento? Quando matou Cristo, então se completou a sua maldade, segundo o que ele mesmo lhes predissera: Enchei a medida dos vossos pais (Mt 23,32). Por isso, no patíbulo, já a ponto de entregar o espírito, diz: Está consumado (Jo 19,30). Ó que remate deu aos seus frutos grosseiros esta figueira maldita, e logo condenada a uma secura eterna! Ó quanto os últimos são piores que os primeiros! Começando pelos inúteis, chegou aos perniciosos e venenosos. Ó afeto grosseiro e de víbora, odiar o homem que cura os corpos dos homens e salva as suas almas! Ó entendimento igualmente grosseiro e, sem dúvida, de boi, pois não entenderam a Deus nem sequer nas obras de Deus!`
    },
    {
      n: 5,
      texto: `Talvez o judeu se queixe de que exagero ao insultá-lo, dizendo que tem entendimento de boi. Mas leia Isaías, e ouvirá coisa pior que boi. O boi conhece o seu dono, diz, e o jumento a manjedoura do seu senhor; Israel não me conheceu, o meu povo não entendeu (Is 1,3). Vês, ó judeu, que sou mais brando contigo do que o teu profeta. Eu te comparei aos animais; ele te põe abaixo deles. Embora o profeta não tenha dito isto em seu próprio nome, mas no de Deus, que proclama ser Deus até pelas próprias obras: Se não me credes a mim, diz, crede nas obras; se não faço as obras de meu Pai, não me creiais (Jo 10,37-38); e nem assim despertam para entender. Nem a fuga dos demônios, nem a obediência dos elementos, nem a vida devolvida aos mortos puderam tirar-lhes este embotamento bestial, e mais que bestial; e desta cegueira, não menos espantosa do que lastimável, resultou que se precipitaram naquele crime tão horrendo e tão monstruosamente grosseiro, lançando mãos sacrílegas sobre o Senhor da majestade. Desde então, pois, pôde dizer-se que a figueira deu os seus figos verdes, quando as observâncias da lei daquele povo começaram a chegar como que ao fim, para que, sobrevindo as novas, segundo a antiga profecia, se lançassem fora as velhas (Lv 26,10). Nem mais nem menos como os figos verdes caem e cedem o lugar aos bons figos que vêm nascendo. Enquanto a figueira não deixou de produzir os seus figos verdes, diz, não te chamei, ó esposa, sabendo que ao mesmo tempo não podiam nascer os ótimos figos. Mas agora, produzidos os que deviam ser produzidos primeiro, já não te convido fora de tempo, pois se sabe que estão próximos os frutos bons e salutares, que hão de expulsar os inúteis.`
    },
    {
      n: 6,
      texto: `Pois as vinhas em flor, diz, exalaram o seu perfume (Ct 2,13); o que é igualmente sinal de que o fruto se aproxima. Este perfume afugenta as serpentes. Dizem que, quando as vinhas florescem, todo réptil venenoso abandona o lugar e não suporta de modo nenhum o perfume das flores novas. Quero que os nossos noviços reparem nisto e tenham confiança, pensando que espírito receberam, cujas primícias os demônios não suportam. Se assim é o fervor de noviço, que será a perfeição acabada? Avalie-se o fruto pela flor, e a força do sabor pela força do perfume. As vinhas em flor exalaram o seu perfume. E assim foi no princípio. À pregação da graça nova seguiu-se a vida nova nos que tinham crido, que, levando entre os gentios uma conduta boa, eram em todo lugar o bom perfume de Cristo (2Cor 2,14-15). Bom perfume é bom testemunho. Este perfume procede da boa obra, como da flor. E, como nos começos da fé nascente as almas fiéis, como umas vinhas espirituais, apareceram cheias de tal flor e de tal perfume, tendo bom testemunho também dos de fora, não é inconveniente, creio, entendermos que delas se disse: As vinhas em flor exalaram o seu perfume. Para quê? Para que, atraídos por ele, também os que ainda não tinham crido, considerando-os pelas suas boas obras, glorificassem também eles a Deus (cf. 1Pd 2,12), e assim o perfume começasse a ser para eles perfume de vida para a vida (cf. 2Cor 2,16). Por isso se diz com razão que deram o perfume, eles que não buscaram a sua glória, mas, com a sua boa fama, a salvação dos outros. De outro modo, podiam, como alguns, tomar a piedade por fonte de lucro — de ostentação, por exemplo, ou de recompensa. Mas isto seria, não dar o perfume, mas vendê-lo. Mas, como faziam tudo na caridade, não venderam o perfume: deram-no.`
    },
    {
      n: 7,
      texto: `Mas, se as vinhas são as almas, a flor a obra, o perfume a boa fama, qual é o fruto? O martírio. E, na verdade, o fruto da videira é o sangue do mártir. Quando der o sono aos seus amados, diz, eis a herança do Senhor: os filhos; a recompensa: o fruto do ventre (Sl 126,2-3). Quase teria dito: o fruto da videira. Por que não chamaria ao sangue do inocente, ao sangue do Justo, o puríssimo sangue da uva? Por que não mosto vermelho, provado, precioso, verdadeiramente da vinha de Sorec, espremido no lagar da paixão? Enfim, preciosa é aos olhos do Senhor a morte dos seus santos (Sl 115,15). Isto quanto a ter-se dito que as vinhas em flor exalaram o seu perfume.`
    },
    {
      n: 8,
      texto: `Assim é, se preferirmos referir este passo aos tempos da graça. Ou, se agrada mais referi-lo aos patriarcas — pois a vinha do Senhor dos exércitos é a casa de Israel (Is 5,7) —, o sentido será este: os profetas e os patriarcas sentiram o perfume de Cristo, que havia de nascer e morrer na carne, mas não deram então esse seu perfume, porque não mostraram na carne aquele que pressentiram em espírito. Não deram o seu perfume, nem tornaram público o seu segredo, esperando que se revelasse a seu tempo. Pois quem então compreenderia a sabedoria escondida no mistério (cf. 1Cor 2,7), ainda não mostrada num corpo? Assim, então as vinhas não deram o seu perfume. Mas deram-no depois, quando, pela sucessão das gerações, deram ao mundo Cristo, nascido delas segundo a carne por um parto virginal. Então, digo, aquelas vinhas espirituais deram o seu perfume, quando apareceu a bondade e o amor pelos homens de Deus, nosso Salvador (Tt 3,4), e o mundo começou a ter presente aquele que poucos tinham pressentido ainda ausente. Aquele homem, por exemplo, que, tocando Jacó e sentindo Cristo, disse: Eis o cheiro do meu filho, como o cheiro de um campo fértil que o Senhor abençoou (Gn 27,27), quando o dizia, guardava para si as suas delícias e não as comunicava a ninguém. Mas, quando chegou a plenitude do tempo, em que Deus enviou o seu Filho, nascido de mulher, nascido sob a lei, para resgatar os que estavam sob a lei (Gl 4,4-5), então o perfume que havia nele se espalhou por toda parte, a ponto de a Igreja, sentindo-o dos confins da terra, clamar: Óleo derramado é o teu nome; e as jovenzinhas corriam ao perfume deste óleo (Ct 1,2-3). Assim esta vinha deu o seu perfume, e naquele tempo deram-no também as outras, nas quais existira este mesmo perfume de vida. Como não o dariam aquelas de quem vem Cristo segundo a carne (cf. Rm 9,5)? Disse-se, pois, que as vinhas deram o seu perfume, ou porque as almas fiéis espalham por toda parte a boa fama de si mesmas; ou porque se tornaram públicos ao mundo os oráculos e as revelações dos patriarcas, e o seu perfume se espalhou por toda a terra, como diz o Apóstolo: É claramente grande o mistério da piedade: manifestou-se na carne, foi justificado no Espírito, apareceu aos anjos, foi pregado aos gentios, foi crido no mundo, foi elevado na glória (1Tm 3,16).`
    },
    {
      n: 9,
      texto: `Mas seria de admirar que nem esta figueira nem estas vinhas tivessem alguma coisa que edificasse os costumes. Eu julgo que este passo tem também um sentido moral. E digo, pela graça de Deus que há em nós, que temos figueiras e vinhas. Figueiras, os que são mais suaves nos costumes; vinhas, os que são mais fervorosos de espírito. Todo aquele que se comporta entre nós de modo comum e sociável, e não só vive sem queixa entre os irmãos, mas se oferece a todos com muita suavidade, em todo serviço de caridade, para que o desfrutem, por que não diria que faz com toda propriedade as vezes da figueira? Mas é preciso que primeiro tenha dado e lançado fora os seus figos verdes: o temor do juízo, que a caridade perfeita lança fora (cf. 1Jo 4,18); a amargura dos pecados, que necessariamente cede à confissão verdadeira, à infusão da graça e ao derramamento de muitas lágrimas; e outras coisas semelhantes, que, à maneira dos figos verdes, precedem a suavidade dos frutos — e que também vós podeis pensar por vós mesmos.`
    },
    {
      n: 10,
      texto: `Para que eu acrescente, contudo, alguma coisa deste gênero que me ocorre, vede se também não se podem contar entre os figos verdes a ciência, a profecia, as línguas e coisas semelhantes. Pois estas coisas, à maneira dos figos verdes, hão de acabar e ceder o lugar a outras melhores, como diz o Apóstolo: a ciência desaparecerá, as profecias acabarão, as línguas cessarão. Também a própria fé será excluída pelo entendimento, e é necessário que à esperança suceda a visão. Pois o que alguém vê, como o espera (cf. Rm 8,24)? Só a caridade não acaba (1Cor 13,8) — aquela com que se ama a Deus de todo o coração, de toda a alma, com todas as forças (Lc 10,27). Por isso de modo nenhum a contaria entre os figos verdes, nem sequer diria que pertence à figueira, mas às vinhas. Os que são vinhas mostram-se para conosco mais severos do que suaves: agem com espírito veemente, zelam pela disciplina, repreendem com a maior dureza os vícios, e aplicam a si com toda propriedade aquela voz: Não odiava eu, Senhor, os que te odeiam, e não me consumia contra os teus inimigos (Sl 138,21)? E ainda: O zelo da tua casa me devora (Sl 68,10). E a mim parece que aqueles sobressaem no amor do próximo, estes no amor de Deus. Mas apetece-me descansar debaixo desta videira e desta figueira (cf. Mq 4,4), onde dá sombra o amor de Deus e do próximo. Tenho um e outro quando te amo, Senhor Jesus Cristo, que és o meu próximo, porque és homem e usaste de misericórdia comigo (cf. Lc 10,37); e és, no entanto, Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
