SERMOES.sermao({
  id: 'bernardo-cantico-42',
  colecao: 'bernardo-cantico',
  ordem: 42,
  numero: 'XLII',
  titulo: 'Da dupla humildade: a que a verdade gera e a que a caridade inflama',
  fonte: 'De duplici humilitate',
  argumento: `A esposa, repreendida, responde com humildade, e Bernardo aproveita para falar como abade: feliz quem é repreendido e responde assim. Descreve com dor o que sente quando a correção volta vazia, e os três degraus da má resposta: o desprezo, a impaciência de quem se irrita com o médico e não com a flecha, e a impudência de quem defende o próprio pecado — sinal de que Deus já deixou de se irar, o que é o pior castigo.

Depois vem a distinção que dá nome ao sermão. Há uma humildade que nasce da verdade, fria, feita de conhecimento, que se impõe por necessidade a quem se vê como é; e há outra que nasce da caridade, quente, feita de afeto, que é voluntária — a de Cristo, "humilde de coração", que não se julgava vil e, no entanto, quis ser tratado como tal. O nardo, erva baixa e de natureza quente, é esta segunda. É preciso fazer da necessidade virtude: não querer parecer por fora diferente do que se é por dentro, e submeter-se até aos mais novos. O leito do rei é o seio do Pai; e a cena aplica-se à Igreja nascente, reunida em oração à espera do Espírito.

Tradução feita do texto latino de Migne (PL 183, 987-993).`,
  pontos: [
    {
      n: 1,
      texto: `Enquanto o rei estava no seu leito, o meu nardo deu o seu perfume (Ct 1,11). Estas são as palavras da esposa, que deixamos para hoje; esta é a resposta que ela deu depois de ser repreendida pelo esposo — não ao esposo, porém, mas aos companheiros dele, como é fácil perceber pelas próprias palavras. Pois, como não diz, na segunda pessoa: Enquanto estavas, ó rei, no teu leito, mas: Enquanto estava no seu leito, é claro que não fala a ele, mas dele. Imagina, pois, que o esposo, depois de a ter corrigido ou contido na medida que lhe pareceu, percebendo o seu pudor pelo rubor das faces, se retirou, para que ela, na sua ausência, dissesse mais livremente o que sentia; e para que, se tivesse ficado, como costuma acontecer, mais assustada e mais abatida do que convinha, as consolações dos companheiros a reanimassem. O que, no entanto, ele também não deixou de fazer por si mesmo, tanto quanto julgou conveniente para o momento. Pois, para deixar claro quanto se agradara dela naquela correção, que sentiu ser recebida dignamente e como convinha, não se ausentou antes de, pela abundância do coração — não há dúvida —, romper em louvores dela e elogiar a beleza das suas faces e do seu pescoço. Por isso também os que ficam com ela lhe falam com brandura e lhe oferecem presentes, conhecendo a vontade do Senhor. É, pois, a eles que ela responde. E assim é a trama literal da cena.`
    },
    {
      n: 2,
      texto: `Mas, antes de começarmos a tirar desta casca o miolo do espírito, digo brevemente uma coisa. Feliz aquele cuja repreensão obtém a resposta que temos por modelo neste passo! Oxalá, antes, não fosse preciso repreender ninguém! Isso seria melhor. Mas, como todos tropeçamos em muitas coisas (Tg 3,2), não me é lícito calar, a mim, a quem cabe por ofício repreender os que pecam, e a quem mais ainda a caridade o exige. E, se eu repreender e fizer o que me cabe, mas a repreensão, saindo, não fizer o que lhe cabe, nem aquilo para que a enviei, mas voltar a mim vazia (cf. Is 55,11), como um dardo que bate e ricocheteia, que ânimo julgais que tenho então, irmãos? Não fico angustiado, não fico atormentado? E, para tomar alguma coisa das palavras do Mestre, já que não posso tomar da sua sabedoria: sinto-me apertado entre duas coisas, e não sei o que escolher (Fl 1,22-23): se devo estar contente com o que disse, porque fiz o que devia, ou arrepender-me da minha palavra, porque não obtive o que queria. Queria, sem dúvida, matar o inimigo e arrancar-lhe o irmão; e não o consegui, antes aconteceu o contrário: feri a alma e aumentei a culpa, pois se lhe juntou o desprezo. Não querem ouvir-te, diz, porque não querem ouvir-me (Ez 3,7). Vês que majestade é desprezada. Não julgues que desprezaste só a mim. O Senhor falou; e o que disse ao profeta, disse também aos apóstolos: Quem vos despreza, a mim despreza (Lc 10,16). Não sou profeta, não sou apóstolo; e, no entanto, ouso dizê-lo, faço as vezes de profeta e de apóstolo, e estou enredado nos encargos daqueles a quem não me igualo nos méritos. Ainda que para grande confusão minha, ainda que com grande perigo para mim, sento-me na cátedra de Moisés, cuja vida, no entanto, não posso reivindicar, e cuja graça não experimento. E daí? Deixará por isso de se respeitar a cátedra, porque um indigno a ocupa? Ainda que os escribas e fariseus se sentem nela, diz: Fazei o que eles dizem (Mt 23,2-3).`
    },
    {
      n: 3,
      texto: `Muitas vezes, ao desprezo junta-se ainda a impaciência, de modo que alguém, repreendido, não só não se importa de ser corrigido, mas ainda se indigna contra quem o repreende, como o delirante que repele a mão do médico. Estranha perversidade! Irrita-se com quem o trata, e não se irrita com quem o flechou! Pois há quem flecha no escuro os retos de coração (Sl 10,3), e que agora te flechou mortalmente; e contra ele não te comoves? Indignas-te comigo, que desejo que fiques são? Irai-vos, diz, e não pequeis (Sl 4,5). Se te iras contra o pecado, não só não pecas, mas até destróis o pecado que tinhas cometido. Mas agora, rejeitando o remédio, conservas o pecado, e, irando-te sem razão, acrescentas pecado; e o pecado se torna pecador acima de toda medida (cf. Rm 7,13).`
    },
    {
      n: 4,
      texto: `Algumas vezes junta-se também a impudência, de modo que não só suporta com impaciência ser corrigido, mas ainda defende sem pudor aquilo por que é repreendido. Isto já é desespero. Tens, diz, a fronte de uma prostituta; não quiseste corar (Jr 3,3); e diz: Retirou-se de ti o meu zelo; não me irarei mais contra ti (Ez 16,42). Só de ouvir isto, estremeço. Sentes de quanto perigo, de quanto horror e tremor é a defesa do pecado? Diz ainda: Eu repreendo e castigo os que amo (Ap 3,19). Se, pois, o zelo te abandonou, abandonou-te também o amor; e não serás digno de amor, tu que és julgado indigno de castigo. Vês que Deus se ira mais precisamente quando não se ira. Tenhamos compaixão do ímpio, diz, e ele não aprenderá a praticar a justiça (Is 26,10). Esta misericórdia eu não a quero. É pior que toda ira esta compaixão, que me fecha os caminhos da justiça. Melhor me é, sem dúvida, segundo o conselho do Profeta, abraçar a correção, para que o Senhor não se ire e eu não pereça fora do caminho justo (Sl 2,12). Quero que te ires comigo, Pai das misericórdias; mas com aquela ira com que corriges o extraviado, não com aquela com que o empurras para fora do caminho. Aquilo o produz em nós o teu castigo benigno; isto o alimenta a tua temível dissimulação. Pois não é quando não sei, mas quando sinto que estás irado, que mais confio que me és propício: pois, quando estiveres irado, te lembrarás da misericórdia (Hab 3,2). Ó Deus, diz, tu lhes foste propício, e castigaste todas as suas invenções (Sl 98,8). Fala de Moisés, de Aarão e de Samuel, que acabara de nomear; e chama propiciação a Deus não ter poupado as suas faltas. Vai agora tu, pois, e fecha para ti esta propiciação para sempre, defendendo o erro e acusando a correção. Não é isto chamar bem ao mal, e mal ao bem? E desta odiosa impudência não brotará logo a impenitência, mãe do desespero? Pois quem se arrepende do que julga ser bom? Ai deles, diz (Is 5,20). Este ai é eterno. Uma coisa é alguém ser tentado pela própria concupiscência, arrastado e seduzido (cf. Tg 1,14); outra, desejar voluntariamente o mal como bem e correr para a morte como para a vida, numa segurança perversa. Por gente assim, digo, preferiria às vezes ter calado e fechado os olhos ao que surpreendi mal feito, a tê-lo repreendido para tamanha ruína.`
    },
    {
      n: 5,
      texto: `Talvez me digas que o meu bem volta para mim, que livrei a minha alma e estou limpo do sangue do homem a quem anunciei e falei, para que se afastasse do seu mau caminho e vivesse (cf. Ez 3,18-19). Mas, ainda que acrescentes inúmeras coisas assim, nada disso me consolará, vendo a morte do filho. Como se eu tivesse buscado com aquela repreensão a minha libertação, e não antes a dele! Pois que mãe, ainda que saiba ter empregado com o filho doente todo o cuidado e diligência que pôde, se por fim se vê frustrada e todos os seus trabalhos de todo ineficazes, morrendo ele apesar disso, deixou alguma vez por isso de chorar? E ela chora pela morte temporal; quanto mais me esperam pranto e grande lamento pela morte eterna do meu filho, ainda que a consciência não me acuse de ter deixado de lhe anunciar! Vês, pelo contrário, de quantos males livra a si e a nós quem, corrigido, responde com mansidão, aceita com pudor, obedece com modéstia, confessa com humildade. A esta alma eu me declararia em tudo devedor, ministro e servo, como a digníssima esposa do meu Senhor, que pode verdadeiramente dizer: Enquanto o rei estava no seu leito, o meu nardo deu o seu perfume.`
    },
    {
      n: 6,
      texto: `Bom perfume é o da humildade, que, subindo deste vale de lágrimas e espalhando-se por todas as regiões vizinhas, borrifa com agradável suavidade até o leito do rei. O nardo é uma erva baixa, e os que estudaram com mais cuidado as propriedades das ervas dizem que é de natureza quente. E por isso me parece que não é inconveniente entender aqui por ele a virtude da humildade — mas de uma humildade que arde com os vapores do santo amor. E digo isto porque há uma humildade que a verdade gera em nós, e que não tem calor; e há uma humildade que a caridade forma e inflama. Esta consiste no afeto; aquela, no conhecimento. Pois, se te olhares por dentro à luz da verdade e sem disfarce, e te julgares sem condescendência, não duvido de que também tu te humilharás aos teus próprios olhos, tornado mais vil para ti mesmo por este verdadeiro conhecimento de ti, ainda que talvez não suportes ainda sê-lo aos olhos dos outros. Serás humilde, pois, mas por enquanto por obra da verdade, e ainda não pela infusão do amor. Pois, se, assim como foste iluminado pelo esplendor da própria verdade, que te mostrou a ti mesmo com verdade e para teu bem, também tivesses sido tocado pelo seu amor, quererias sem dúvida, quanto está em ti, que todos tivessem de ti a mesma opinião que sabes que a verdade tem. Disse "quanto está em ti" porque muitas vezes não convém que todos saibam tudo o que sabemos de nós; e a própria caridade da verdade e a verdade da caridade nos proíbem querer tornar público o que possa prejudicar quem o venha a saber. De outro modo, se, preso pelo amor particular de ti mesmo, reténs fechado dentro de ti o juízo da verdade, quem duvida de que amas menos a verdade, já que lhe preferes a tua própria vantagem ou honra?`
    },
    {
      n: 7,
      texto: `Vês, pois, que não é a mesma coisa o homem já não ter de si um alto conceito, porque a verdade da luz o convenceu, e acomodar-se de bom grado aos humildes, ajudado pelo dom da caridade. Aquilo é de necessidade; isto, de vontade. Esvaziou-se a si mesmo, diz, tomando a forma de servo (Fl 2,7) — e dando-nos a forma da humildade. Ele mesmo se esvaziou, ele mesmo se humilhou, não por necessidade de juízo, mas por amor de nós. Podia, sem dúvida, mostrar-se vil e desprezível, mas não se considerar tal, porque sabia quem era. Foi, pois, humilde pela vontade, e não pelo juízo, ele que se apresentou tal como sabia não ser; e preferiu ser tido pelo menor, ele que não ignorava ser o maior. Enfim, diz: Aprendei de mim, que sou manso e humilde de coração (Mt 11,29). Disse "de coração", isto é, pelo afeto do coração, pela vontade. Excluiu, pois, a necessidade quem declarou a vontade. Pois não é como eu e tu, que nos achamos na verdade dignos de desonra e de desprezo, dignos do último e mais baixo lugar, dignos até de suplícios, dignos de açoites; não é assim, digo, com ele. E, no entanto, experimentou tudo isto porque quis, como humilde de coração — humilde, isto é, com aquela humildade que o afeto do coração aconselhou, não com a que o exame da verdade arrancou.`
    },
    {
      n: 8,
      texto: `Por isso disse que esta espécie de humildade voluntária é criada em nós não pela censura da verdade, mas pela infusão da caridade, porque é do coração, do afeto, da vontade; se com razão, julga tu. E examine igualmente o teu juízo se com razão a atribuí ao Senhor, de quem é certo que por caridade se esvaziou, por caridade se fez pouco menor que os anjos (cf. Hb 2,7), por caridade foi submisso aos pais (cf. Lc 2,51), por caridade se inclinou sob as mãos do Batista, por caridade suportou as fraquezas da carne, por caridade, enfim, se sujeitou à morte e ficou sem glória na cruz. E fique ainda ao teu arbítrio considerar esta outra coisa: se com razão julguei que esta mesma humildade, assim aquecida pela caridade, é designada pela erva baixa e quente, isto é, pelo nardo. E, se aprovares tudo isto — e o aprovarás, rendendo-te a uma razão evidentíssima —, então, se já estás humilhado diante de ti mesmo por aquela humildade necessária que a Verdade, que sonda os corações e os rins (cf. Sl 7,10), incute nos sentidos da alma vigilante, acrescenta a vontade e faze da necessidade virtude, pois não há virtude sem o consentimento da vontade. E isto se fará se não quiseres parecer por fora diferente do que te achas por dentro. De outro modo, teme ler de ti mesmo: Porque agiu com engano diante dele, para que a sua iniquidade fosse achada digna de ódio (Sl 35,3). Ter dois pesos, diz, é abominação diante de Deus (Pr 20,10). Pois quê? Em segredo, diante de ti mesmo, pesado na balança da verdade, dás-te pouco valor; e por fora, fingindo outro preço, vendes-te a nós por um peso maior do que dela recebeste? Teme a Deus, e não faças esta coisa péssima: que a vontade exalte aquele que a verdade humilha; pois isto é resistir à verdade, isto é lutar contra Deus. Antes, submete-te a Deus, e que a vontade seja submissa à verdade — e não só submissa, mas devota. Não estará a minha alma submissa a Deus?, diz (Sl 61,2).`
    },
    {
      n: 9,
      texto: `Mas é pouco ser submisso a Deus, se não o fores também a toda criatura humana por causa de Deus (cf. 1Pd 2,13): seja ao abade, como superior; seja aos priores, como constituídos por ele. Eu digo mais: submete-te aos iguais, submete-te também aos menores. Pois assim nos convém, diz, cumprir toda justiça (Mt 3,15). Vai também tu ao menor, se queres ser perfeito na justiça; dá a precedência ao inferior, inclina-te diante do mais novo. Fazendo isto, poderás também tu tomar para ti a palavra que a esposa disse: O meu nardo deu o seu perfume. O perfume é a devoção, o perfume é a boa fama, que chega a todos, para que sejas o bom perfume de Cristo em todo lugar (cf. 2Cor 2,14-15), admirado por todos, amado por todos. Isto não o pode o humilde que a verdade obriga à humildade, porque a guarda para si e não a deixa sair, para exalar por fora o seu perfume. Antes, não tem perfume, porque não tem devoção, visto que não se humilha espontaneamente nem de boa vontade. Mas a humildade da esposa, como o nardo, espalha o seu perfume: quente de amor, vigorosa de devoção, perfumada de boa fama. A humildade da esposa é voluntária, é perpétua, é fecunda. O seu perfume nem a censura o destrói, nem o louvor. Tinha ouvido: As tuas faces são belas como as da rola, e o teu pescoço é como os colares (Ct 1,9). Tinha recebido também a promessa do adorno de ouro, e, no entanto, responde com humildade; e, quanto maior se ouve dizer, tanto mais se humilha em tudo (cf. Eclo 3,20). Não se gloria dos méritos, nem entre os seus louvores se esquece da humildade, que ela mesma confessa humildemente sob o nome do nardo; como se dissesse com a voz da Virgem Maria: Não tenho consciência de mérito nenhum para tamanha honra, senão que Deus olhou para a humildade da sua serva (Lc 1,48). Pois que outra coisa quer dizer "o meu nardo deu o seu perfume" senão: A minha humildade agradou? Não a minha sabedoria, diz, não a minha nobreza, não a minha beleza, que eu não tinha; mas a humildade, a única coisa que em mim havia, deu o seu perfume — isto é, o de sempre. Como sempre, a humildade agrada a Deus; como sempre e por costume, o Senhor excelso olha para as coisas humildes; e por isso, enquanto o rei estava no seu leito, isto é, na sua morada excelsa, também até lá subiu o perfume da humildade. Habita nas alturas, diz, e olha para as coisas humildes no céu e na terra (Sl 112,5-6).`
    },
    {
      n: 10,
      texto: `Enquanto, pois, o rei estava no seu leito, o nardo da esposa deu o seu perfume. O leito do rei é o seio do Pai (cf. Jo 1,18), porque o Filho está sempre no Pai. E não duvides de que este rei é clemente, pois o seu leito perene é a morada da benignidade paterna. Com razão sobe até ele o clamor dos humildes, a ele, cuja morada é a fonte da piedade, a quem é familiar a suavidade, e cuja bondade é substancial, ou antes consubstancial; e tudo o que ele é, é do Pai, para que o temor dos humildes não suspeite na majestade régia nada que não seja paterno. Enfim: Por causa da miséria dos necessitados e do gemido dos pobres, agora me levantarei, diz o Senhor (Sl 11,6). Sabendo disto, pois, a esposa, como da casa e caríssima, não julga que a falta de méritos a afaste da graça do esposo, e confia só na humildade. Enfim, chama-lhe rei, pois, assustada pela repreensão, por enquanto não ousa chamá-lo esposo; e confessa que ele habita no alto — e nem assim a humildade desconfia.`
    },
    {
      n: 11,
      texto: `Podes aplicar com propriedade esta palavra à Igreja primitiva, se te lembrares daqueles dias em que, elevado o Senhor para onde estava antes (cf. Jo 6,63) e sentado à direita do Pai — aquele seu leito antigo, nobre e glorioso —, os discípulos estavam reunidos num mesmo lugar, perseverando unânimes na oração com as mulheres, com Maria, a mãe de Jesus, e com os irmãos dele (At 1,13-14). Não te parece que verdadeiramente, naquele tempo, o nardo da esposa, pequenina e temerosa, dava o seu perfume? Enfim, quando de repente veio do céu um ruído, como de um vento impetuoso que chegava, e encheu toda a casa onde estavam sentados (At 2,2), não pôde então a pobrezinha dizer com razão: Enquanto o rei estava no seu leito, o meu nardo deu o seu perfume? Ficou claro, sem dúvida, para todos os que estavam naquele lugar, quão agradável e aceito tinha subido o perfume dos humilhados, pois logo lhe responderam com tão copiosa e gloriosa recompensa. E ela não foi ingrata ao benefício. Ouve, pois, como, cheia de devoção, logo se prepara para suportar todos os males pelo nome dele; pois segue-se: O meu amado é para mim um ramalhete de mirra; repousará entre os meus peitos (Ct 1,12). A minha fraqueza, que conheceis, não me deixa ir mais adiante. Digo só isto: que, sob o nome de mirra, ela diz que está pronta a enfrentar as amarguras das tribulações por amor do amado. O resto do capítulo trataremos em outra ocasião, se, pelas vossas orações, o Espírito Santo estiver presente, para nos fazer entender as palavras da esposa, que ele mesmo formou inspirando-as, do modo que ele sabe convir aos louvores daquele de quem é o Espírito, o esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
