SERMOES.sermao({
  id: 'bernardo-cantico-79',
  colecao: 'bernardo-cantico',
  ordem: 79,
  numero: 'LXXIX',
  titulo: 'Do amor tenaz e indissolúvel com que a alma segura o esposo; e da volta do esposo, no fim dos tempos, para salvar a Sinagoga dos judeus',
  fonte: 'De amore tenaci et indissolubili',
  argumento: `"Vistes aquele a quem a minha alma ama?" O amor veemente não pensa em outra coisa, e a esposa pergunta pelo amado sem lhe dizer o nome, como se todos soubessem o que ela pensa: neste canto não se pesam as palavras, mas os afetos, e quem não ama não entende a língua do amor. Os vigias, que também amam, entendem-na e instruem-na depressa, com a palavra breve do Símbolo da fé; e ela, "passando além deles", encontra o amado. Era preciso passar por eles, mas também além deles, como Cristo passou da morte para a vida na ressurreição e passou além, até a glória, na ascensão: crer na ressurreição é passar; crer também na ascensão é passar além.

"Segurei-o, e não o soltarei": nem filósofos, nem hereges, nem perseguidores separaram a Igreja do amor de Cristo; ela o segura porque é segurada por ele, e não o solta nem em troca da bênção, como Jacó. Mas quer introduzi-lo "na casa de sua mãe" — a Sinagoga, cuja casa ficou deserta —, e não só na casa, mas no quarto: deseja que, no fim, Israel seja salvo e receba também a graça de esposa; não para lhe ceder o esposo, mas para o partilhar, pois ele fez de ambas uma só.

Tradução feita do texto latino de Migne (PL 183, 1163-1166).`,
  pontos: [
    {
      n: 1,
      texto: `Vistes aquele a quem a minha alma ama (Ct 3,3)? Ó amor precipitado, veemente, ardente, impetuoso, que não deixas pensar em outra coisa além de ti, que tens fastio do resto, que desprezas tudo fora de ti, contente contigo mesmo! Confundes as ordens, não fazes caso do costume, ignoras a medida; tudo o que parece ser de oportunidade, de razão, de pudor, de conselho ou de juízo, tu o vences em ti mesmo e o reduzes ao cativeiro. Eis que tudo o que ela pensa e o que diz soa a ti, cheira a ti, e a nada mais: a tal ponto reivindicaste para ti tanto o seu coração como a sua língua. Diz: Vistes aquele a quem a minha alma ama? Como se eles soubessem o que ela pensa! Perguntas por aquele a quem a tua alma ama? E ele não tem nome? Quem és tu, e quem é ele? E isto eu o digo por causa da singularidade da linguagem e do notável descuido das palavras, pelo qual esta escritura se mostra bem diferente das outras. Por isso, neste canto nupcial, não se devem pesar as palavras, mas os afetos. Por que assim, senão porque o santo amor, que é, como se sabe, a única matéria de todo este livro, não deve ser estimado pela palavra ou pela língua, mas pela obra e pela verdade (cf. 1Jo 3,18)? É o amor que fala em toda parte; e, se alguém deseja alcançar o conhecimento do que aqui se lê, que ame. De outro modo, em vão se aproxima de ouvir ou de ler o canto do amor quem não ama; porque um peito frio de modo nenhum pode receber uma palavra de fogo (cf. Sl 118,140). Pois, assim como não entende quem fala grego aquele que não sabe grego, nem quem fala latim aquele que não é latino, e assim por diante, assim a língua do amor será bárbara para quem não ama, e será como bronze que soa ou címbalo que retine (1Cor 13,1). Estes, porém — falo dos vigias —, porque também eles receberam do Espírito o amar, sabem o que diz o Espírito; e, conhecendo muito bem as vozes do amor, estão prontos a responder na mesma língua, isto é, com os cuidados do amor e os serviços da piedade.`
    },
    {
      n: 2,
      texto: `Enfim, em pouco tempo a despedem tão bem instruída sobre aquele que busca, que ela diz: Pouco depois de passar além deles, encontrei aquele a quem a minha alma ama (Ct 3,4). Bem diz "pouco", porque lhe deram uma palavra abreviada (cf. Rm 9,28), transmitindo-lhe o Símbolo da fé. E o que se segue é assim. Era preciso, sem dúvida, que a esposa passasse por eles, pelos quais havia de conhecer a verdade; mas também que passasse além deles. Pois, se não tivesse passado também além deles, não teria encontrado aquele que buscava. E não duvides de que foram eles mesmos que a persuadiram a isso. Pois não pregavam a si mesmos, mas ao seu Senhor Jesus (cf. 2Cor 4,5), que sem dúvida está acima deles e além deles. Por isso diz também: Passai a mim, todos os que me desejais (Eclo 24,26). E não bastava passar; ensina-se também a passar além. Pois aquele cujas pegadas ela seguia tinha passado além. Não só tinha passado da morte para a vida, mas tinha passado além, até a glória. Por que não havia de ser preciso que também ela passasse além? De outro modo, não podia alcançar aquele que não seguisse pelas mesmas pegadas aonde quer que tivesse ido.`
    },
    {
      n: 3,
      texto: `E, para que o que digo fique mais claro: se o meu Senhor Jesus tivesse ressuscitado dos mortos, mas não tivesse subido aos céus, não se poderia dizer dele que passou além, mas só que passou; e por isso a esposa que o buscava só teria de passar, e não de passar além. Mas agora, como ele, ressuscitando, já tinha passado, e acrescentara o passar além, subindo, com razão também ela disse que não passou, mas passou além, ela que o seguiu com a fé e a devoção até os céus. Crer na ressurreição é, pois, passar; crer também na ascensão é passar além. E talvez — como me lembro de ter dito certo dia, quando tratava disto — conhecesse aquela, e não conhecesse esta. Instruída, pois, por eles no que lhe faltava — isto é, que aquele que tinha ressuscitado também tinha subido —, subiu também ela, isto é, passou além, e encontrou. E como não havia de encontrar, chegando com a mente aonde ele está com o corpo? Pouco depois de passar além deles. E bem diz "deles": pois tanto a eles como aos outros seus membros que estão sobre a terra, a nossa cabeça precedeu e ultrapassou em dois pontos: a ressurreição, como já dissemos, e a ascensão. Pois Cristo é as primícias (1Cor 15,23). E, se ele nos precedeu, também a nossa fé. Pois aonde não o seguiria ela? Se subir ao céu, ela está lá; se descer ao inferno, está presente; e, se tomar as suas asas de madrugada e habitar nos confins do mar, até lá, diz, a tua mão me conduzirá, e a tua direita me segurará (Sl 138,8-10). Enfim, não foi segundo ela que o Pai do esposo, onipotente e sumamente bom, nos ressuscitou com ele e nos fez sentar à sua direita (cf. Ef 2,6)? E isto a propósito de a Igreja ter dito: passei além deles; porque passou além também de si mesma, estando pela fé onde ainda não chegou de fato. Penso que fica também claro por que preferiu dizer que passou além, e não que passou. E passemos nós ao que se segue.`
    },
    {
      n: 4,
      texto: `Segurei-o, e não o soltarei, até que o introduza na casa de minha mãe e no quarto daquela que me gerou (Ct 3,4). Assim é: desde então e daí em diante não falta a raça cristã, nem a fé na terra, nem a caridade na Igreja. Vieram as torrentes, sopraram os ventos e investiram contra ela, e não caiu, porque estava fundada sobre a rocha (Mt 7,25). E a rocha é Cristo (1Cor 10,4). Assim, nem pela verbosidade dos filósofos, nem pelas cavilações dos hereges, nem pelas espadas dos perseguidores ela pôde, nem poderá jamais, ser separada do amor de Deus que está em Cristo Jesus (Rm 8,39): tão fortemente segura aquele a quem a sua alma ama, tão bom é para ela unir-se a Deus (cf. Sl 72,28). A cola é boa, diz Isaías (Is 41,7). Que há de mais tenaz do que esta cola, que nem as águas lavam, nem os ventos desfazem, nem as espadas cortam? Enfim, as muitas águas não poderão apagar a caridade (Ct 8,7). Segurei-o, e não o soltarei. E o santo patriarca: Não te soltarei, diz, se não me abençoares (Gn 32,26). Assim também ela não o quer soltar, e talvez o queira ainda menos que o patriarca, porque nem sequer em troca da bênção: pois aquele, recebida a bênção, soltou-o; esta, porém, não. Não quero, diz, a tua bênção, mas a ti. Pois que há para mim no céu? E, fora de ti, que quis eu sobre a terra (Sl 72,25)? Não te soltarei, nem mesmo se me abençoares.`
    },
    {
      n: 5,
      texto: `Segurei-o, e não o soltarei. E talvez ele não queira menos ser segurado, pois declara: As minhas delícias são estar com os filhos dos homens (Pr 8,31); e promete: Eis que estou convosco todos os dias até a consumação dos séculos (Mt 28,20). Que há de mais forte que este laço, firmado por uma só e tão veemente vontade de dois? Segurei-o, diz. Mas ela, por sua vez, é igualmente segurada por aquele que segura, a quem diz noutro lugar: Seguraste a minha mão direita (Sl 72,24). Quem é segurada e segura, como pode já cair? Segura pela firmeza da fé, segura pelo afeto da devoção. Mas de modo nenhum seguraria por muito tempo, se não fosse segurada. E é segurada pelo poder e pela misericórdia do Senhor. Segurei-o, e não o soltarei, até que o introduza na casa de minha mãe e no quarto daquela que me gerou. Grande é a caridade da Igreja, que nem sequer à Sinagoga rival inveja as suas delícias. Que há de mais benigno do que estar pronta a partilhar até com a inimiga aquele a quem a sua alma ama? E não admira, porque a salvação vem dos judeus (Jo 4,22). Volte o Salvador ao lugar de onde saíra, para que o resto de Israel seja salvo (cf. Rm 9,27). Não sejam ingratos os ramos para com a raiz (cf. Rm 11,18), nem os filhos para com a mãe. Não invejem os ramos à raiz o que dela tiraram, nem os filhos à mãe o que mamaram nos seus peitos. Segure, pois, a Igreja firmemente a salvação que a Judeia perdeu e ela alcançou, até que entre a plenitude das nações, e assim todo o Israel seja salvo (Rm 11,25-26). Queira que a salvação, que é comum, venha a todos em comum, pois é recebida por todos de tal modo que nada diminui para cada um. E faz isto, e mais. Que mais? Deseja-lhe também o nome e a graça de esposa. Isto está certamente acima da salvação.`
    },
    {
      n: 6,
      texto: `Caridade incrível, se as palavras que ela mesma disse não a tornassem crível. Pois disse, se reparaste, que queria introduzir aquele que segurava não só na casa da mãe, mas também no quarto, o que é sinal de prerrogativa. Para a salvação bastava que entrasse na casa; mas o segredo do quarto significa a graça. Hoje, diz, entrou a salvação nesta casa (Lc 19,9). Como não haveria salvação para os da casa, tendo entrado na casa o Salvador? Mas aquela que merece recebê-lo no quarto tem à parte o seu segredo para si. A salvação é para a casa; as delícias guardam-se no tálamo. Hei de introduzi-lo na casa de minha mãe, diz. Em que casa, senão naquela de que outrora predissera aos judeus: Eis que a vossa casa vos será deixada deserta (Lc 13,35)? Fez o que disse, como tens também sobre isto o seu testemunho no profeta: Deixei a minha casa, abandonei a minha herança (Jr 12,7). E agora ela promete reconduzi-lo e restituir à casa de sua mãe a salvação perdida. E, se isto parece pouco, ouve que bem acrescenta: E no quarto daquela que me gerou. Quem entra no tálamo é o esposo. Grande poder do amor! O Salvador tinha saído indignado da sua casa e da sua herança; e agora, aplacado em atenção a ela, dobra-se a ponto de voltar não só como Salvador, mas também como esposo. Bendita sejas do Senhor, filha (Rt 3,10), que reprimes a indignação e restituis a herança. Bendita sejas para tua mãe, por cujo benefício se afasta a ira, volta a salvação, volta aquele que lhe diga: Eu sou a tua salvação (Sl 34,3). Não basta isto; acrescente e diga: Eu te desposarei comigo na fé; eu te desposarei comigo no juízo e na justiça; eu te desposarei comigo na misericórdia e nas compaixões (Os 2,19-20). Mas lembra-te de que aquela que promove esta amizade é a esposa. Como, pois, cede a outra o esposo — e tal esposo —, para não dizer que o deseja para ela? Não é assim. A boa filha deseja-o, sim, para a mãe, não para o ceder a ela, mas para o partilhar com ela. Um só basta para as duas; ou antes, já não eram duas, mas uma só nele. Pois ele é a nossa paz, que de ambas fez uma só (Ef 2,14), para que haja uma só esposa e um só esposo, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
