SERMOES.sermao({
  id: 'bernardo-cantico-08',
  colecao: 'bernardo-cantico',
  ordem: 8,
  numero: 'VIII',
  titulo: 'De como o beijo da boca de Deus significa o Espírito Santo, que a Igreja pede para si a fim de conhecer a santíssima Trindade',
  fonte: 'Quomodo per osculum oris Dei significatur Spiritus sanctus',
  argumento: `É o sermão mais doutrinal da série. Bernardo identifica o beijo da boca com o próprio Espírito Santo — a paz do Pai e do Filho, o vínculo que os une — e distingue dois modos de recebê-lo: o beijo da boca, que só cabe ao Filho, e o beijo vindo do beijo, que é o que a esposa pede, e o que João e Paulo receberam.

No caminho vem a advertência contra a curiosidade: a ciência que incha não procede do beijo, e não o recebeu nem quem entende a verdade sem amá-la, nem quem a ama sem entendê-la.

Tradução feita do texto latino de Migne (PL 183, 810-814).`,
  pontos: [
    {
      n: 1,
      texto: `Hoje, como sabeis pela promessa de ontem, proponho-me a tratar do beijo supremo, isto é, do beijo da boca. Ouvi com mais atenção aquilo que tem sabor mais doce, que raramente se saboreia e que mais dificilmente se entende. Começando um pouco mais de cima: parece-me que designou um beijo inefável, de que nenhuma criatura teve experiência, aquele que disse: Ninguém conhece o Filho senão o Pai, e ninguém conhece o Pai senão o Filho, e aquele a quem o Filho o quiser revelar (Mt 11,27). Pois o Pai ama o Filho e o abraça com um amor único: o supremo ao seu igual, o eterno ao que lhe é coeterno, o que é um ao que é único. Mas com afeto não menor o Filho o prende a si — tanto que por amor dele morre, como ele mesmo testemunha ao dizer: Para que todos saibam que amo o Pai, levantai-vos, vamos (Jo 14,31); e não há dúvida de que era para a paixão. Aquele conhecimento mútuo entre quem gera e quem é gerado, e juntamente aquele amor, que outra coisa são senão um beijo — o mais doce de todos, e o mais secreto?`
    },
    {
      n: 2,
      texto: `Quanto a mim, tenho por certo que a segredo tão grande e tão santo do amor divino nem mesmo a criatura angélica é admitida. Pois, como o próprio Paulo entende, aquela paz ultrapassa todo entendimento — até o dos anjos (Fl 4,7). Por isso ela, ainda que ouse muito, não se atreve a dizer «beije-me com a sua boca», reservando isso só ao Pai; e pede algo menor: Beije-me, diz, com o beijo da sua boca. Vede a nova esposa a receber um beijo novo: não da boca, porém, mas do beijo da boca. Soprou sobre eles, diz o texto — sem dúvida Jesus sobre os apóstolos, isto é, sobre a Igreja nascente — e disse: Recebei o Espírito Santo (Jo 20,22). Aquilo foi, com certeza, um beijo. O quê? Aquele sopro corporal? Não, mas o Espírito invisível, que se deu naquele sopro do Senhor justamente para que assim se entendesse que ele procede igualmente dele como do Pai — como um beijo verdadeiro, que é comum a quem beija e a quem é beijado. Basta, portanto, à esposa ser beijada pelo beijo do esposo, ainda que não o seja pela boca. E não considera coisa pequena nem vil ser beijada pelo beijo, pois isso não é outra coisa senão ser inundada pelo Espírito Santo. Com efeito, se com razão se toma o Pai por aquele que beija e o Filho por aquele que é beijado, não será fora de propósito entender que o beijo é o Espírito Santo — que é a paz imperturbável do Pai e do Filho, o vínculo firme, o amor indiviso, a unidade indivisível.`
    },
    {
      n: 3,
      texto: `É dele, portanto, que a esposa ousa falar, e é ele que pede com confiança, sob o nome de beijo, que se derrame nela. Tem, com efeito, uma razão que lhe dá ousadia. Pois o Filho, ao dizer: Ninguém conhece o Filho senão o Pai, e ninguém conhece o Pai senão o Filho, acrescentou: e aquele a quem o Filho o quiser revelar. Ora, a esposa não desconfia de que ele o queira para ela, se o quer para alguém. Pede, pois, com ousadia que se lhe dê o beijo, isto é, aquele Espírito no qual lhe sejam revelados o Filho e o Pai. É que um não se dá a conhecer sem o outro. Daí aquilo: Quem me vê, vê também o meu Pai (Jo 14,9); e aquilo de João: Todo o que nega o Filho também não tem o Pai; mas quem confessa o Filho tem também o Pai (1Jo 2,23). Do que fica claro que nem o Pai se conhece sem o Filho, nem o Filho sem o Pai. Com razão, portanto, põe a suma bem-aventurança não no conhecimento de um só, mas de ambos, aquele que diz: Esta é a vida eterna: que te conheçam a ti, o verdadeiro Deus, e àquele que enviaste, Jesus Cristo (Jo 17,3). E dos que seguem o Cordeiro se diz que trazem escrito na fronte o nome dele e o nome do seu Pai (Ap 14,1) — o que é gloriar-se de conhecer a um e a outro.`
    },
    {
      n: 4,
      texto: `Mas alguém dirá: Então não é necessário conhecer também o Espírito Santo, visto que, ao dizer que a vida eterna é conhecer o Pai e o Filho, ele se calou a respeito do Espírito Santo? É necessário, sim. Mas, onde o Pai e o Filho são conhecidos perfeitamente, como se poderia ignorar a bondade de ambos, que é o Espírito Santo? Pois um homem não se dá a conhecer por inteiro a outro enquanto fica escondido se é de boa ou de má vontade. Aliás, mesmo quando se disse: Esta é a vida eterna: que te conheçam a ti, o verdadeiro Deus, e àquele que enviaste, Jesus Cristo — se aquele envio mostra tanto o beneplácito do Pai, que envia por bondade, como o do Filho, que obedece de livre vontade, então não se calou de todo a respeito do Espírito Santo, uma vez que se fez menção de tão grande graça de um e de outro. Pois o amor e a bondade de ambos é o Espírito Santo.`
    },
    {
      n: 5,
      texto: `A graça deste tríplice conhecimento é, portanto, o que a esposa pede para si, na medida em que se pode receber em carne mortal, quando pede o beijo. E pede-o ao Filho, porque é do Filho revelá-lo a quem quiser. O Filho revela, pois, a si mesmo a quem quer, e revela também o Pai. E revela, sem dúvida, pelo beijo, isto é, pelo Espírito Santo, como testemunha o Apóstolo, que diz: A nós, porém, Deus o revelou pelo seu Espírito (1Cor 2,10). Mas, ao dar o Espírito pelo qual revela, revela também o próprio Espírito: dando, revela; e revelando, dá. Ora, a revelação que se faz pelo Espírito Santo não só ilumina para o conhecimento, mas também acende para o amor, como diz Paulo: O amor de Deus foi derramado nos nossos corações pelo Espírito Santo que nos foi dado (Rm 5,5). E talvez seja por isso que daqueles que, tendo conhecido a Deus, não o glorificaram como Deus, não se lê que tenham conhecido por revelação do Espírito Santo: porque, embora conhecessem, não amaram. O texto diz assim: Pois Deus lhes revelou. E não se acrescentou «pelo seu Espírito», para que mentes ímpias não tomassem para si o beijo da esposa — elas, que, contentes com a ciência que incha, não conheceram a caridade que edifica (1Cor 8,1). Diga, enfim, o próprio Apóstolo por que meio conheceram: Pelas coisas que foram feitas, diz ele, viram com a inteligência. Donde também fica claro que nem sequer conheceram perfeitamente aquele a quem de modo nenhum amaram. Pois, se o tivessem conhecido por inteiro, não teriam ignorado a bondade pela qual ele quis nascer em carne e morrer para os redimir. Ouve, enfim, o que lhes foi revelado de Deus: O seu eterno poder, diz, e a sua divindade (Rm 1,19-21). Vês que perscrutaram o que é de sublimidade e de majestade, na presunção do próprio espírito, não do de Deus; mas não entenderam que ele é manso e humilde de coração (Mt 11,29). E não é de admirar, pois também Behemot, que é a cabeça deles, nada tem de humilde; antes, como dele se lê, vê tudo o que é alto (Jó 41,25). Davi, ao contrário, não andava entre coisas grandes nem entre maravilhas acima de si (Sl 130,1-2), para não ser esmagado pela glória por perscrutar a majestade (Pr 25,27).`
    },
    {
      n: 6,
      texto: `Também vós, para pisardes com cautela nos sentidos ocultos, lembrai-vos sempre do que adverte o Sábio: Não procures o que é mais alto que tu, nem queiras perscrutar o que excede as tuas forças (Eclo 3,22). Andai neles no espírito, e não no vosso próprio juízo. O ensino do Espírito não aguça a curiosidade: acende a caridade. Com razão, pois, a esposa, buscando aquele a quem a sua alma ama (Ct 3,1), não se entrega aos sentidos da sua carne nem se contenta com os raciocínios vazios da curiosidade humana; mas pede o beijo, isto é, invoca o Espírito Santo, para receber dele ao mesmo tempo o sabor da ciência e o tempero da graça. E com razão a ciência que se dá no beijo é recebida com amor, porque o beijo é sinal de amor. Logo, a ciência que incha, por estar sem caridade, não procede do beijo. E tampouco o atribuam a si, de maneira alguma, os que têm zelo de Deus, mas não segundo a ciência (Rm 10,2). Pois a graça do beijo traz os dois dons juntos: a luz do conhecimento e a riqueza da devoção. É, com efeito, o Espírito de sabedoria e de inteligência, que, à maneira da abelha, que traz a cera e o mel, tem com que acender a luz da ciência e com que infundir o sabor da graça. Não pense, portanto, ter recebido o beijo nem aquele que entende a verdade e não a ama, nem aquele que a ama e não a entende. Neste beijo, decerto, não há lugar nem para o erro nem para a tibieza. Por isso, quem é esposa prepare, diante da dupla graça do sacrossanto beijo, os seus dois lábios: a razão, para a inteligência; a vontade, para a sabedoria; e assim, gloriando-se de um beijo pleno, mereça ouvir: Derramou-se a graça nos teus lábios; por isso Deus te abençoou para sempre (Sl 44,3). Assim o Pai, beijando o Filho, derrama nele em plenitude os segredos da sua divindade e respira a suavidade do amor; e é isso que a Escritura significa ao dizer: O dia proclama ao dia a palavra (Sl 18,3). A esse abraço eterno e singularmente feliz a nenhuma criatura, como já se disse, é dado assistir: só o Espírito de ambos é testemunha e sabedor do conhecimento e do amor que há entre eles. Pois quem conheceu o pensamento do Senhor? Ou quem foi o seu conselheiro? (Rm 11,34)`
    },
    {
      n: 7,
      texto: `Mas talvez alguém me diga: E a ti, como se tornou conhecido aquilo que confessas não ter sido confiado a nenhuma criatura? Certamente foi o Unigênito, que está no seio do Pai, quem o contou (Jo 1,18) — não a mim, diria eu, mísero e indigno, mas a João, o amigo do esposo, de quem são estas palavras; e não só a ele, mas também a João evangelista, o discípulo que Jesus amava. Pois também a alma deste agradou a Deus, sendo bem digna do nome e do dote de esposa, digna dos abraços do esposo, digna, enfim, de reclinar-se sobre o peito do Senhor. João bebeu do seio do Unigênito aquilo que este havia bebido do seio do Pai. E não foi só ele, mas também todos aqueles a quem o anjo do grande conselho dizia: Chamei-vos amigos, porque tudo quanto ouvi do meu Pai eu vos dei a conhecer (Jo 15,15). Bebeu também Paulo, cujo evangelho não vem de homem, nem o recebeu por meio de homem, mas por revelação de Jesus Cristo (Gl 1,11-12). Todos estes podem dizer, com tanta felicidade quanta verdade: O Unigênito, que está no seio do Pai, ele mesmo o contou a nós. E aquela narração, que foi para eles senão um beijo? Mas beijo vindo do beijo, e não da boca. Ouve, com efeito, o que é beijo da boca: Eu e o Pai somos um; e ainda: Eu estou no Pai, e o Pai está em mim (Jo 10,30.38). É um beijo tomado boca a boca; mas ninguém se aproxima. É, sem dúvida, um beijo de amor e de paz; mas aquele amor está acima de toda ciência, e aquela paz ultrapassa todo entendimento. E, contudo, aquilo que o olho não viu, nem o ouvido ouviu, nem subiu ao coração do homem (1Cor 2,9), Deus o revelou a Paulo pelo seu Espírito — isto é, pelo beijo da sua boca. Portanto, que o Filho esteja no Pai e o Pai no Filho, isso é beijo da boca. Mas o que se lê: Não recebemos o espírito deste mundo, mas o Espírito que vem de Deus, para conhecermos o que Deus nos deu (1Cor 2,12) — isso é beijo vindo do beijo.`
    },
    {
      n: 8,
      texto: `E, para distinguir um do outro com mais clareza: quem recebe a plenitude toma o beijo da boca; mas quem recebe da plenitude recebe o beijo vindo do beijo. Grande é Paulo, sem dúvida; mas, por mais que estenda a boca para o alto, ainda que se alce até o terceiro céu, é forçoso que fique aquém da boca do Altíssimo e permaneça em si mesmo, contente com a sua medida; e, como não poderá chegar até o rosto da glória, peça humildemente que desçam até ele e que do alto lhe enviem o beijo. Mas aquele que não julga usurpação ser igual a Deus (Fl 2,6), a ponto de ousar dizer: Eu e o Pai somos um — porque se une de igual para igual e abraça de igual para igual —, esse não mendiga o beijo de um lugar inferior, mas junta boca a boca na mesma altura e, por prerrogativa única, toma o beijo da boca. Para Cristo, portanto, o beijo é plenitude; para Paulo, participação: de modo que aquele se gloria de ser beijado pela boca, e este apenas pelo beijo.`
    },
    {
      n: 9,
      texto: `Feliz beijo, contudo, aquele pelo qual não só se conhece a Deus, mas se ama o Pai — que de modo algum se conhece plenamente, a não ser quando é amado perfeitamente. Qual de vós já sentiu alguma vez, no segredo da sua consciência, o Espírito do Filho a clamar: Abba, Pai? (Gl 4,6) Essa, essa mesma, tenha por certo que é amada com afeto de pai, pois se sente movida pelo mesmo espírito que move o Filho. Confia, quem quer que sejas, confia sem hesitar. No espírito do Filho reconhece-te filha do Pai, e esposa ou irmã do Filho. Com um e outro nome verás que é chamada a alma que é assim. Tenho à mão com que o provar; não me custará muito. É voz do esposo dirigida a ela: Vem ao meu jardim, minha irmã, minha esposa (Ct 5,1). É irmã, porque vem do mesmo Pai; é esposa, porque está no mesmo Espírito. Pois, se o matrimônio carnal faz de dois uma só carne, com quanto mais razão a união espiritual fará de dois um só espírito? Enfim, quem se une ao Senhor é um só espírito com ele (1Cor 6,17). Mas ouve também a respeito do Pai: com quanto amor e com quanta bondade ele a chama filha e, ao mesmo tempo, como a sua própria nora, a convida para os carinhosos abraços do Filho. Ouve, filha, diz ele, e vê, e inclina o teu ouvido; esquece o teu povo e a casa de teu pai, e o rei se enamorará da tua formosura (Sl 44,11-12). Vê de quem é que ela reclama o beijo. Ó alma santa, tem reverência, porque ele é o Senhor teu Deus — e talvez não deva ser beijado, mas adorado, com o Pai e o Espírito Santo pelos séculos dos séculos. Amém.`
    }
  ]
});
