SERMOES.sermao({
  id: 'bernardo-cantico-53',
  colecao: 'bernardo-cantico',
  ordem: 53,
  numero: 'LIII',
  titulo: 'Os montes e as colinas significam os espíritos celestes, que o esposo transpôs ao vir à terra no mistério da sua encarnação',
  fonte: 'Per montes et colles significari coelestes spiritus',
  argumento: `As jovenzinhas já não ousam perturbar o repouso da esposa, e ela reconhece nisso a voz do amado, que lhes infundiu um justo temor. Bernardo, que também é superior, confessa como é raro poder dedicar-se a si mesmo sem medo de fazer falta aos monges, e quanta segurança dá perceber que Deus aprova esse repouso. "A voz do meu amado; eis que ele vem": primeiro se ouve, depois se vê — como em Jó, como no Pentecostes, como no salmo: "Ouve, filha, e vê".

Mas que montes são esses pelos quais o esposo vem saltando? Não se trata de imaginar um gigante pulando serras: os montes e colinas são os espíritos celestes, as noventa e nove ovelhas deixadas nos montes. São montes pela altura e ovelhas pela mansidão, e pastam dentro de si mesmos o Verbo, ao passo que nós mendigamos o nosso pão por fora, nos livros e nas criaturas. Os saltos do esposo são a sua descida: do mais alto do céu à terra, por cima de querubins e serafins até as ordens mais baixas dos anjos, as colinas; e mais baixo ainda, feito pouco menor que os anjos, submisso a Maria e a José, inclinado sob as mãos de João.

Tradução feita do texto latino de Migne (PL 183, 1033-1038).`,
  pontos: [
    {
      n: 1,
      texto: `A voz do meu amado (Ct 2,8). Vendo a esposa o pudor novo das jovenzinhas e o seu temor respeitoso — pois tinham começado de novo a não ousar intrometer-se no seu santo repouso, nem se atreviam, como ontem e anteontem, a molestá-la enquanto repousava na contemplação —, reconhece que isto lhe veio do cuidado e da ação do esposo. E, exultando em espírito — quer pelo progresso delas, que são contidas numa inquietação excessiva e supérflua; quer pelo seu próprio repouso, daí em diante mais livre; quer ainda pela bondade e pelo favor do esposo, que tanto zela por esse seu repouso e defende com tanto empenho o seu suavíssimo ócio, ou antes, as suas ocupações mais ardentes —, diz que isto o faz a voz do seu amado, dirigida a elas por esta razão. Pois aquele que preside aos outros com solicitude quase nunca, ou raramente, se dedica a si mesmo com tranquilidade, porque teme sempre fazer falta aos súditos e desagradar a Deus, por antepor ao proveito comum o seu próprio repouso e a doçura da contemplação. Mas não é pouca a alegria e a segurança que às vezes lhe vêm, quando descansa suavemente, ao perceber, por um certo temor e reverência para com ele que Deus infundiu nos corações dos súditos, que o seu repouso agrada a Deus, pois é Deus que faz que eles suportem as suas necessidades com mais serenidade, em vez de ousarem perturbar temerariamente o grato repouso do pai espiritual. Pois o justo temor dos pequenos mostra claramente que ouviram por dentro a voz como que ameaçadora e repreensiva daquele que fala no profeta: Sou eu que falo justiça (Is 63,1). A sua voz é a sua inspiração e o infundir de um justo temor.`
    },
    {
      n: 2,
      texto: `Percebendo, pois, esta voz, a esposa, alegre e exultante, diz: A voz do meu amado. É amiga, e alegra-se muito com a voz do esposo (cf. Jo 3,29). E acrescenta: Eis que ele vem, saltando pelos montes, transpondo as colinas. Tendo percebido pelo ouvido a presença do amado, volta sem hesitar os olhos, bem curiosos, para ver aquele que ouvira. O ouvido conduz à vista, porque a fé vem pelo ouvido (Rm 10,17), e é por ela que os corações se purificam para que Deus possa ser visto; pois tens assim: Purificando pela fé os corações (At 15,9). Vê, pois, vir aquele que ouvira falar, guardando também aqui o Espírito Santo aquela ordem que está descrita assim no Profeta: Ouve, filha, e vê (Sl 44,11). E, para que percebas com mais certeza que não foi por acaso nem fortuitamente, mas de propósito e com cuidado, pela razão que expusemos, que aqui se pôs o ouvido antes da vista, vê se esta ordem das palavras não se acha guardada também pelo santo Jó, quando fala assim a Deus: Ouvi-te com os meus ouvidos, e agora os meus olhos te veem (Jó 42,5). E também onde se lembra que o Espírito Santo desceu sobre os apóstolos no dia de Pentecostes, não se descreve o ouvido precedendo a vista? Pois diz: De repente veio do céu um ruído, como de um vento impetuoso que chegava; e mais abaixo: E apareceram-lhes línguas repartidas, como de fogo (At 2,2-3). Também aqui, pois, se conta que a vinda do Espírito Santo foi percebida primeiro pelo ouvido, depois pela vista. Mas basta disto; pois também tu, se te importas de te dedicar a esta pesquisa, poderás talvez encontrar em outros lugares da Escritura algumas coisas semelhantes.`
    },
    {
      n: 3,
      texto: `Consideremos agora o que exige uma investigação mais cuidadosa e tem um acesso mais difícil — para o que confesso precisar inteiramente do auxílio do Espírito Santo, a fim de poder trazer à luz quais são aqueles montes ou colinas sobre os quais a Igreja contemplou com olhos alegres o esposo saltando e transpondo-os; creio que quando se apressava para a redenção daquela cuja beleza desejara. E penso assim, sem hesitar, porque me ocorre uma coisa semelhante no Profeta, que claramente previa e exprimia em espírito a vinda do Salvador: No sol pôs a sua tenda, e ele, como um esposo que sai do seu quarto, exultou como um gigante para percorrer o caminho; a sua saída é do mais alto do céu, e o seu percurso vai até o mais alto dele (Sl 18,6-7). Este percurso de ida e de volta é conhecidíssimo; e conhecidíssimo é de onde começou e para que se completou. Que faremos, então? Pintaremos para nós, lendo estas coisas nos salmos ou no presente cântico, um homem gigante, de alta estatura, apaixonado por alguma mulherzinha ausente, que, apressando-se para os abraços desejados, salta por cima destes montes e colinas que vemos erguer-se, com a sua massa corporal, sobre as planícies da terra, a tal altura que alguns deles parecem levantar o cume acima das nuvens? Mas não convém imaginar fantasias corporais deste gênero, sobretudo ao tratar deste cântico espiritual; e de modo nenhum nos é lícito, a nós que nos lembramos de ter lido no Evangelho que Deus é espírito, e que os que o adoram devem adorá-lo em espírito (Jo 4,24).`
    },
    {
      n: 4,
      texto: `Quais são, pois, estes montes e colinas espirituais, para que depois reconheçamos, em consequência, que saltos, e de que gênero, dava o esposo — que é Deus, e por isso espírito — neles ou por cima deles? Se julgarmos que são aqueles em que, segundo conta o Evangelho, foram deixadas outrora as noventa e nove ovelhas, quando o seu piedoso pastor veio à terra procurar a única que se perdera (Mt 18,12), a coisa continua ainda obscura, e o entendimento fica embaraçado, porque é difícil descobrir que outros montes ou colinas, igualmente espirituais, têm aquelas bem-aventuranças espirituais e supracelestes — pois são elas, sem dúvida, as ovelhas ali mencionadas — para neles habitar ou pastar. Contudo, se não houvesse alguns na verdade, a Verdade não o teria dito. Nem o Profeta teria dito, muito antes, da cidade do alto, Jerusalém, que os seus fundamentos estão sobre os montes santos (Sl 86,1), se não houvesse verdadeiramente ali montes santos. Enfim, para saberes que aquela morada celeste tem verdadeiramente montes e colinas, não só espirituais, mas também vivos e racionais, ouve Isaías: Os montes e as colinas cantarão louvores diante de Deus (Is 55,12).`
    },
    {
      n: 5,
      texto: `Quem são, pois, estes, senão os mesmos espíritos que habitam o céu, que, como dissemos, foram chamados ovelhas pela voz do Senhor, de modo que os montes sejam as próprias ovelhas? A não ser que te pareça absurdo que os montes pastem nos montes, ou as ovelhas nas ovelhas. Segundo a letra, soa duro; mas, segundo o entendimento espiritual, sabe doce, se repararmos com finura como o pastor de umas e outras ovelhas, isto é, Cristo, Sabedoria de Deus, distribui um só e mesmo pasto da verdade de um modo aos seus rebanhos da terra e de outro aos do céu. Pois nós, homens mortais, no lugar da nossa peregrinação, temos por enquanto de comer o nosso pão com o suor do nosso rosto (cf. Gn 3,19), mendigando-o por fora, com trabalho e fadiga: isto é, dos homens doutos, ou dos livros sagrados, ou então contemplando as perfeições invisíveis de Deus, compreendidas por meio das coisas criadas (cf. Rm 1,20). Os anjos, porém, recebem em toda plenitude — não de si mesmos, mas em si mesmos —, com tanta facilidade quanto felicidade, aquilo de que vivem felizes. Pois são todos ensinados por Deus (cf. Jo 6,45); coisa que, com verdade certa, se promete aos eleitos dentre os homens que um dia hão de alcançar, mas que ainda não lhes é dado experimentar com felicidade segura.`
    },
    {
      n: 6,
      texto: `Pastam, pois, os montes nos montes, ou as ovelhas nas ovelhas, quando aquelas substâncias espirituais do alto encontram abundantemente dentro de si mesmas, no Verbo da vida, com que perpetuar a sua vida feliz; sendo elas mesmas montes e ovelhas: montes, pela plenitude ou pela altura; ovelhas, pela mansidão. Pois, cheias de Deus, altas em méritos, cumuladas de virtudes, submetem, contudo, e inclinam com obediência total e humilde os seus cumes erguidos ao mando daquela majestade que as ultrapassa de longe, como ovelhas mansíssimas que andam em tudo ao aceno do seu pastor e o seguem aonde quer que vá (cf. Ap 14,4). E sobre elas, segundo o profeta Davi, verdadeiros montes santos, como sobre a sabedoria criada antes de todas as coisas, estão firmemente assentados desde o princípio os fundamentos da cidade do Senhor (Sl 86,1), que é uma só no céu e na terra, ainda que em parte peregrine e em parte reine. E delas igualmente, segundo Isaías, como de uns címbalos vivos e bem sonoros, ressoa sem cessar a ação de graças e a voz do louvor (Is 51,3), pois cumprem com voz suave e incessante o que há pouco lembramos do mesmo Profeta: que os montes e as colinas cantarão louvores diante de Deus; e também o que diz aquele outro, falando ao Senhor Deus: Felizes, diz, os que habitam na tua casa, Senhor: pelos séculos dos séculos te louvarão (Sl 83,5).`
    },
    {
      n: 7,
      texto: `Estes são, pois — para voltarmos ao ponto de onde nos afastamos um pouco, mas, creio, necessariamente —, os montes e as colinas em que a Igreja viu o esposo celeste saltando com admirável alegria, quando se apressava para os seus abraços; e não só saltando, mas também transpondo-os. Queres que te mostre estes saltos nos escritos dos profetas e dos apóstolos? Não que me ponha agora a desdobrar todos os testemunhos que sobre isto quem tem tempo pode encontrar neles (pois seria longo e não é necessário); ponho só aqueles que parecem confirmar breve e claramente o que se diz dos saltos do esposo. Davi diz dele que pôs a sua tenda no sol, e ele, como um esposo que sai do seu quarto, exultou como um gigante para percorrer o caminho; a sua saída é do mais alto do céu (Sl 18,6-7). Eis que salto deu: do mais alto do céu até a terra. Pois não encontro outro lugar onde tenha posto a sua tenda no sol — isto é, onde ele, que habita a luz inacessível, se tenha dignado mostrar a sua presença na luz e às claras — senão na terra. Enfim: Foi visto na terra e conviveu com os homens (Br 3,38). Na terra, digo, às claras — que é o mesmo que no sol — pôs a sua tenda, isto é, o corpo que se dignou formar para si do corpo da Virgem, para que nele fosse visto aquele que em si é invisível; e assim toda carne visse a salvação de Deus (cf. Lc 3,6), quando ele viesse na carne.`
    },
    {
      n: 8,
      texto: `Saltou, pois, pelos montes, isto é, por aqueles espíritos supremos, quando desceu até eles, revelando-lhes por bondade o mistério escondido desde os séculos (cf. Ef 3,9) e o grande mistério da piedade (cf. 1Tm 3,16). Mas, transpondo estes montes superiores e mais eminentes — isto é, os querubins e os serafins, e também as dominações, os principados e as potestades, e ainda as virtudes —, dignou-se descer até a ordem inferior dos anjos, como até as colinas. Mas acaso ficou nelas? Transpôs também as colinas. Pois não assumiu, diz, os anjos, mas a descendência de Abraão (Hb 2,16), que é inferior aos anjos, para que se cumprisse a palavra que disse o Profeta mencionado, falando assim ao Pai a respeito do Filho: Fizeste-o pouco menor que os anjos (Sl 8,6). Embora isto se possa entender como dito em louvor da natureza humana: que o homem, criado à imagem e semelhança de Deus e dotado de razão à maneira do anjo, dista contudo um pouco do anjo por causa do corpo feito de terra. Mas ouve o apóstolo Paulo declarar claramente dele: Ele, que era de condição divina, não julgou usurpação ser igual a Deus; mas esvaziou-se a si mesmo, tomando a forma de servo, fazendo-se semelhante aos homens e sendo reconhecido em seu aspecto como homem (Fl 2,6-7); e ainda: Quando chegou, diz, a plenitude do tempo, Deus enviou o seu Filho, nascido de mulher, nascido sob a lei, para resgatar os que estavam sob a lei (Gl 4,4-5). Aquele, pois, que nasceu de mulher e nasceu sob a lei, sem dúvida transpôs, descendo, não só os montes, isto é, as bem-aventuranças maiores e superiores, mas também os anjos menores, que, em comparação com os superiores, com razão se designam pelo nome de colinas. Mas o menor no reino dos céus é maior do que qualquer um que traga carne sobre a terra, ainda que seja aquele grande João Batista (Lc 7,28). Pois, ainda que confessemos que o Deus-homem, também enquanto homem, está incomparavelmente acima de todo principado e potestade, é certo, contudo, que, se os precede em majestade, ficou abaixo deles pela fraqueza. Assim, pois, saltou pelos montes e transpôs as colinas, quando, com a maior bondade, se mostrou inferior não só aos espíritos superiores, mas também aos inferiores. E não só se mostrou sujeito àqueles espíritos do alto, mas também aos que habitam casas de barro (cf. Jó 4,19), ultrapassando e vencendo com a sua humildade até a humildade dos homens. Enfim, era submisso a Maria e a José em Nazaré, quando tinha doze anos (Lc 2,42.51); e junto ao Jordão, já moço, inclinou-se sob as mãos de João (Mt 3,13). Mas o dia já declinou, e ainda não me apetece de modo nenhum descer destes montes.`
    },
    {
      n: 9,
      texto: `Mas, se desta vez quisermos explorar todas as amenidades destes montes, como nos agrada, e perscrutar os seus segredos, é de temer que o sermão perca a brevidade agradável, ou que a matéria, tão rica e excelente, seja privada pela pressa do cuidado devido. Descansemos, pois, hoje, se vos parece bem, nestes montes; porque é bom estarmos aqui, onde, postos pelo pastor Cristo num lugar de pasto junto com os santos anjos, somos apascentados com mais gosto e mais fartura. Pois também nós somos ovelhas do seu pasto (cf. Sl 94,7). Ruminemos, pois, como animais puros do bom pastor, o que engolimos com toda avidez no sermão de hoje; e, noutro sermão, receberemos com mais atenção o resto do mesmo capítulo, pela graça do esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
