SERMOES.sermao({
  id: 'bernardo-cantico-12',
  colecao: 'bernardo-cantico',
  ordem: 12,
  numero: 'XII',
  titulo: 'Do precioso perfume da piedade; e da reverência que os súditos devem aos seus superiores',
  fonte: 'De pretioso unguento pietatis',
  argumento: `O terceiro perfume, prometido dois sermões atrás. Faz-se «das necessidades dos pobres, das angústias dos oprimidos, das perturbações dos tristes, das culpas dos que erram» — ingredientes que parecem desprezíveis e dão o melhor dos aromas. Bernardo busca exemplos em Paulo, em Jó, em José, em Samuel, em Moisés e em Davi, e chega às mulheres que compraram aromas para ungir Jesus: não uma parte do corpo, mas o corpo inteiro, que é a Igreja.

No meio, uma defesa de si mesmo contra os que o acusavam de viver só para si; e, logo depois, um aviso aos monges que julgam de longe a vida dos bispos.

Tradução feita do texto latino de Migne (PL 183, 828-834).`,
  pontos: [
    {
      n: 1,
      texto: `Lembro-me de vos ter apresentado dois perfumes: um, o da contrição, que reúne muitas faltas; outro, o da devoção, que contém muitos benefícios. Ambos são saudáveis, mas não ambos suaves. O primeiro sente-se picante, porque a amarga lembrança dos pecados move à compunção e faz doer; o segundo é calmante, porque o olhar posto na bondade divina dá consolação e acalma a dor. Mas há um perfume que supera de longe os dois, e a este eu chamaria da piedade, porque se faz das necessidades dos pobres, das angústias dos oprimidos, das perturbações dos tristes, das culpas dos que erram e, enfim, de todas as aflições de quaisquer desgraçados, ainda que sejam inimigos. Parecem desprezíveis esses ingredientes; mas o perfume que deles se faz está acima de todos os aromas. É curativo: pois felizes os misericordiosos, porque alcançarão misericórdia (Mt 5,7). Assim, as muitas misérias recolhidas e olhadas com olhos de compaixão são os próprios ingredientes com que se compõem os melhores perfumes, dignos dos peitos da esposa e agradáveis ao olfato do esposo. Feliz a mente que cuidou de se enriquecer e de se nutrir recolhendo tais aromas, embebendo-os no óleo da misericórdia e cozinhando-os no ardor da caridade. Quem é, dize-me, esse homem agradável que se compadece e empresta (Sl 111,5) — inclinado a sofrer com os outros, pronto a socorrer, julgando ser mais feliz dar do que receber; fácil em perdoar, difícil em irar-se, de modo nenhum disposto a vingar-se, e olhando em tudo para as necessidades do próximo como para as suas? Ó alma, quem quer que sejas, se és assim disposta, assim banhada pelo orvalho da misericórdia, assim transbordante de entranhas de compaixão; se te fazes tudo para todos e te tornaste para ti mesma como um vaso quebrado, para acorreres sempre e em toda parte em socorro dos outros; se, enfim, morreste para ti a fim de viveres para todos — então possuis, feliz, o terceiro e melhor perfume, e as tuas mãos destilaram o licor de toda a suavidade. Não secará no tempo mau, nem o calor da perseguição o beberá; antes, Deus se lembrará sempre de todo o teu sacrifício, e o teu holocausto será rico (Sl 19,4).`
    },
    {
      n: 2,
      texto: `Há homens de riquezas na cidade do Senhor dos exércitos: pergunto se em algum deles se acham estes perfumes. E o primeiro que me ocorre, como sempre, é Paulo, vaso de eleição — na verdade um vaso de aromas, um vaso odorífero, cheio de todos os pós do perfumista. Pois era o bom odor de Cristo para Deus em todo lugar (2Cor 2,15). Espalhava ao longe e por toda parte a fragrância de muita suavidade aquele peito que o cuidado de todas as igrejas de tal modo tomara. Vê que ingredientes e que aromas acumulara para si. Cada dia morro, diz ele, pela glória que tenho de vós (1Cor 15,31); e ainda: Quem desfalece, que eu não desfaleça? Quem se escandaliza, que eu não queime? (2Cor 11,29) E este rico abundava em muitas coisas assim, que bem conheceis, para compor os melhores perfumes. Convinha, de fato, que cheirassem aos primeiros e mais puros aromas aqueles peitos que haviam de amamentar os membros de Cristo — de quem Paulo era certamente mãe, dando-os à luz uma vez e outra até que Cristo se formasse neles (Gl 4,19) e os membros fossem refeitos à semelhança da sua cabeça.`
    },
    {
      n: 3,
      texto: `Ouve também de outro rico, e de como tinha à mão ingredientes escolhidos com que fazer os melhores perfumes. O forasteiro, diz ele, não passou a noite fora; a minha porta esteve aberta ao viajante (Jó 31,32); e ainda: Fui olhos para o cego e pés para o coxo. Era pai dos pobres; quebrava os queixos do iníquo e arrancava-lhe a presa dos dentes (Jó 29,15-17). Se neguei aos pobres o que queriam, e fiz esperar em vão os olhos da viúva; se comi sozinho o meu bocado, sem que dele comesse o órfão; se desprezei o que passava sem roupa, e o pobre sem agasalho; se os seus flancos não me abençoaram, aquecidos com a lã das minhas ovelhas... (Jó 31,16-20) Com que odor, pensamos nós, esse homem terá perfumado a terra nessas obras? Cada obra era um aroma. Com eles enchera a própria consciência, para temperar o fedor da carne apodrecida com o hálito de uma suavidade interior.`
    },
    {
      n: 4,
      texto: `José, depois de fazer o Egito inteiro correr atrás de si ao odor dos seus perfumes, deu por fim a mesma fragrância a beber até aos que o tinham vendido. Proferia palavras de repreensão com rosto irado, mas irrompiam-lhe lágrimas da abundância do coração (Gn 43,30; 45,2) — não indício de ira, mas traição da ternura. Samuel chorava Saul, que procurava matá-lo (1Sm 15,35); e, derretendo-se por dentro ao calor do fogo da caridade, a gordura da compaixão escorria-lhe para fora pelos olhos. Enfim, pelo bom odor da sua fama, que espalhara por toda parte, a Escritura diz dele que todos, desde Dã até Bersabeia, souberam que Samuel era profeta fiel do Senhor (1Sm 3,20). Que direi de Moisés? De quanta gordura e de quanta substância ele também tinha enchido as entranhas! E aquela casa rebelde no meio da qual vivia então nunca conseguiu, com todo o seu murmúrio e todo o seu furor, apagar a unção do espírito de que uma vez ficara embebido, a ponto de fazê-lo deixar a sua mansidão entre brigas contínuas e discussões de todos os dias. Com razão o Espírito Santo testemunhou dele que era o mais manso de todos os homens que viviam sobre a terra (Nm 12,3). Com os que odiavam a paz ele era pacífico (Sl 119,7), a ponto de não só não se irar contra um povo ingrato e rebelde, mas até de abrandar com a sua intercessão o próprio Deus irado, como está escrito: Disse que os destruiria, se Moisés, o seu escolhido, não se tivesse posto de pé na brecha diante dele, para desviar a sua ira e impedir que os destruísse (Sl 105,23). E por fim: Se lhes perdoas, diz ele, perdoa; se não, risca-me do teu livro, que escreveste (Ex 32,31-32). Ó homem verdadeiramente ungido com a unção da misericórdia! Fala com o afeto de quem é pai, a quem nenhuma felicidade pode contentar se estiver separada dos filhos que deu à luz. Por exemplo: se um rico dissesse a uma mulher pobrezinha — Entra tu para o meu banquete, mas deixa lá fora o menino que trazes, porque chora e nos incomoda —, faria ela isso? Não preferirá ficar em jejum a comer sozinha com o rico, deixando abandonado o penhor que lhe é caro? Assim também não agrada a Moisés entrar sozinho na alegria do seu Senhor, ficando o povo lá fora — esse povo a quem ele se prende, ainda que inquieto e ingrato, fazendo as vezes de mãe e com afeto de mãe. Doem-lhe as entranhas; mas julga mais suportável a tortura do que o arrancamento.`
    },
    {
      n: 5,
      texto: `Que há de mais manso que Davi, que chorou a morte daquele que sempre tivera sede da sua? (2Sm 1,11) Que há de mais bondoso do que sofrer com a morte daquele a quem sucedia no reino? E, quanto à morte do filho parricida, com que dificuldade aceitou ser consolado! (2Sm 19,4) Tal afeto mostrava, decerto, grande abundância da melhor unção; e por isso orava sem receio: Lembra-te, Senhor, de Davi e de toda a sua mansidão (Sl 131,1). Todos estes, pois, tiveram os melhores perfumes, com que ainda hoje cheiram suavíssimamente por todas as igrejas. E não só eles, mas todos quantos nesta vida se mostraram assim benevolentes e benfazejos, e procuraram viver humanamente entre os homens, sem guardar para si nenhuma graça que se visse terem recebido, mas pondo-a em comum, considerando-se devedores tanto de amigos como de inimigos, de sábios e de ignorantes. E, tendo sido úteis a todos e humildes em tudo, foram, mais que todos, amados de Deus e dos homens, e a sua fragrância está em bênção. Todos os que assim nos precederam cheiraram no seu tempo, e cheiram ainda hoje, aos melhores perfumes. Também tu, se repartires de bom grado conosco, teus companheiros de tenda, o dom que recebeste do alto; se te mostrares entre nós sempre prestativo, afetuoso, agradecido, tratável, humilde — terás de todos o testemunho de que também cheiras aos melhores perfumes. Todo aquele entre vós que suporta com paciência as fraquezas dos irmãos, tanto do corpo como da alma, e que ainda, se lhe é permitido e se pode, os ajuda com serviços, os conforta com palavras e os orienta com conselhos — e, se a disciplina não o permite, ao menos não cessa de consolar o enfermo com orações solícitas: todo aquele, digo, que assim age entre vós espalha decerto um bom odor entre os irmãos, e um odor dos melhores perfumes. Um irmão assim é, na comunidade, como bálsamo na boca: apontam-no com o dedo, e todos dizem dele: Este é o amigo dos irmãos e do povo de Israel; este é o que muito ora pelo povo e por toda a cidade santa (2Mc 15,14).`
    },
    {
      n: 6,
      texto: `Mas voltemos ao Evangelho e procuremos algo que talvez diga respeito também a estes perfumes. Maria Madalena, Maria mãe de Tiago e Salomé compraram aromas para irem ungir Jesus (Mc 16,1). Que perfumes são estes, tão preciosos que se preparam e se compram para o corpo de Cristo, tão abundantes que bastam para o corpo inteiro? Pois de nenhum dos dois anteriores se lê que tenha sido comprado, ou feito de propósito para o serviço do Senhor, ou derramado sobre o corpo inteiro. Num lugar aparece de repente uma mulher que beija os pés e os unge com perfume (Lc 7,38; Jo 12,3); noutro, a mesma ou outra, com um vaso de alabastro, que o derrama sobre a cabeça (Mc 14,3). Aqui, porém, diz: compraram aromas para irem ungir Jesus. Compram não perfumes já prontos, mas aromas; e a unção que se faz em serviço do Senhor não é tomada pronta, mas preparada de novo; nem é para ungir só uma parte do corpo — os pés, por exemplo, ou a cabeça —, mas, como está escrito, para irem ungir Jesus: o que abrange o todo, sem distinguir parte alguma.`
    },
    {
      n: 7,
      texto: `Também tu, se te revestires de entranhas de misericórdia e te mostrares generoso e bondoso não só com os teus pais ou parentes, ou com aqueles que tens por benfeitores e de quem esperas benefício — pois isso até os pagãos fazem (Mt 5,47) —, mas, seguindo o conselho de Paulo, procurares fazer o bem a todos (Gl 6,10), de tal modo que, por amor de Deus, não julgues dever negar nem retirar nem ao inimigo um serviço humano, corporal ou espiritual: então é claro que também tu abundas nos melhores perfumes e que tomaste a teu cargo ungir, não só a cabeça ou os pés do Senhor, mas por toda parte, quanto está em ti, o corpo inteiro, que é a Igreja. E talvez tenha sido por isso que o Senhor Jesus não quis que a mistura preparada para ele se gastasse no seu corpo morto, para guardá-la para o corpo vivo. Pois vive a Igreja, que come o pão vivo descido do céu. Ela é o corpo de Cristo mais querido; e nenhum cristão ignora que aquele outro corpo foi entregue à morte para que este não provasse a morte. É ela que ele deseja ver ungida e cuidada; são os membros fracos dela que ele quer ver aliviados com atenção mais cuidadosa. Foi para ela, pois, que guardou os perfumes preciosos, quando, antecipando a hora e apressando a glória, não frustrou a devoção daquelas mulheres, mas a instruiu. Recusou ser ungido, mas por poupar, não por desprezar; não por recusar o serviço, mas por reservar o proveito. Falo do proveito, não deste perfume material e corporal, mas do espiritual, que naquele se figurava. Naquele, portanto, o Mestre da piedade poupou os melhores perfumes da piedade, que desejava ardentemente ver dados aos seus membros necessitados, tanto no corpo como no espírito. Pois pouco antes, quando se derramava sobre a sua cabeça, ou mesmo sobre os seus pés, um perfume bastante caro, acaso o proibiu? Antes se opôs aos que o proibiam. A Simão, indignado por ele deixar que uma pecadora o tocasse, teceu uma longa parábola de repreensão; e aos outros, que reclamavam do desperdício do perfume, respondeu: Por que incomodais esta mulher?`
    },
    {
      n: 8,
      texto: `Às vezes — para fazer aqui uma pequena digressão — enquanto eu estava sentado aos pés de Jesus, aflito, oferecendo o sacrifício de um espírito atribulado na lembrança dos meus pecados; ou então junto à sua cabeça, quando raramente me achava de pé e exultava na lembrança dos seus benefícios, ouvi quem dissesse: Para que este desperdício? Queixavam-se de que eu vivia só para mim, podendo, no entender deles, ser útil a muitos. E diziam: Isso podia ser vendido por muito e dado aos pobres (Mt 26,8-10). Mas não é bom negócio para mim ganhar o mundo inteiro e perder-me a mim mesmo, sofrendo o dano da minha própria alma. Entendendo, pois, que tais palavras são aquelas moscas mortiças de que fala a Escritura, que estragam a suavidade do perfume (Ecl 10,1), lembrei-me daquela sentença divina: Povo meu, os que te chamam feliz te induzem ao erro (Is 3,12). Mas que ouçam o Senhor desculpar-me e responder por mim, esses que me acusam de ociosidade: Por que incomodais esta mulher? — isto é: vós olhais para a aparência e por isso julgais segundo a aparência. Não é homem, como julgais, que possa lançar a mão a coisas fortes: é mulher. Por que tentais pôr-lhe um jugo para o qual eu o vejo pouco capaz? Uma boa obra ele faz em mim. Fique no bem, enquanto não tiver forças para o melhor. Se algum dia crescer de mulher para homem, e para homem perfeito, então poderá ser tomado também para uma obra de perfeição.`
    },
    {
      n: 9,
      texto: `Irmãos, reverenciemos os bispos, mas temamos os seus trabalhos. Se pesarmos os trabalhos, não ambicionaremos as honras. Reconheçamos que as nossas forças não estão à altura, e não nos agrade meter ombros moles e femininos debaixo das cargas dos homens; e não fiquemos a espiá-los, mas honremo-los. Pois é desumano censurar as obras daqueles cujos fardos recusas. É temerário que a mulher, fiando em casa, ralhe com o homem que volta da batalha. Digo, pois: se aquele que vive no claustro surpreender o que vive no meio do povo a portar-se por vezes com menos rigor ou menos cautela — na palavra, por exemplo, na comida, no sono, no riso, na ira, no julgar —, não salte logo a julgar, mas lembre-se do que está escrito: Melhor é a iniquidade do homem do que a mulher que faz o bem (Eclo 42,14). Pois tu, vigiando em guardar-te a ti mesmo, fazes bem; mas quem ajuda a muitos faz melhor e com mais coragem. E, se não consegue cumpri-lo sem alguma iniquidade — isto é, sem certa desigualdade na sua vida e no seu porte —, lembra-te de que a caridade cobre a multidão dos pecados (1Pd 4,8). Isto seja dito contra a dupla tentação com que muitas vezes os religiosos, por instigação do diabo, são levados ou a ambicionar a glória dos bispos, ou a julgar temerariamente os excessos deles.`
    },
    {
      n: 10,
      texto: `Mas voltemos aos perfumes da esposa. Vês como se há de preferir aos outros este perfume da piedade, o único que não se permite desperdiçar? Tão longe está de se desperdiçar que nem um copo de água fria fica sem recompensa (Mt 10,42). Bom é, contudo, o perfume da contrição, feito da lembrança dos pecados e derramado nos pés do Senhor; porque um coração contrito e humilhado Deus não despreza (Sl 50,19). Mas julgo muito melhor o que se chama da devoção, feito da lembrança dos benefícios de Deus, pois é tido por digno da cabeça, tanto que o próprio Deus diz dele: O sacrifício de louvor me honrará (Sl 49,23). E a ambos vence a unção da piedade, que se faz do olhar posto nos desgraçados e se derrama por todo o corpo de Cristo. Digo o corpo, não aquele que foi crucificado, mas o que foi adquirido pela paixão dele. É de fato o melhor perfume; e, em comparação com ele, mostrou não fazer caso dos outros aquele que disse: Quero misericórdia, e não sacrifício (Mt 9,13). É esta, pois, entre as demais virtudes, que eu creio exalarem sobretudo os peitos da esposa, que em tudo deseja conformar-se à vontade do esposo. Não cheirava Tabita, mesmo morta, ao odor da misericórdia? E por isso logo se restabeleceu da morte (At 9,39-41): porque prevaleceu o odor da vida.`
    },
    {
      n: 11,
      texto: `Mas ouvi uma palavra breve sobre o versículo de que tratamos. Todo aquele que embriaga com palavras e cheira bem pelos benefícios tenha por dito a si: Porque os teus peitos são melhores que o vinho, e cheiram aos melhores perfumes (Ct 1,1-2). E para isto quem é capaz? Qual de nós possui ao menos uma dessas coisas de modo inteiro e perfeito, sem ficar às vezes mais estéril no dizer e mais morno no agir? Mas há quem com razão e sem dúvida se glorie deste elogio: a Igreja, a quem nunca falta, no conjunto dos seus, com que embriagar e com que perfumar. Pois o que lhe falta num, tem-no noutro, segundo a medida do dom de Cristo e a disposição do Espírito, que reparte a cada um como quer (Ef 4,7; 1Cor 12,11). A Igreja perfuma naqueles que fazem amigos com o dinheiro injusto (Lc 16,9); embriaga nos ministros da palavra, que regam a terra com o vinho da alegria espiritual, a embriagam e dão fruto na paciência. Ela se chama esposa com ousadia e com segurança, porque tem de verdade peitos melhores que o vinho, e que cheiram aos melhores perfumes. E, embora nenhum de nós se atreva a tomar isso para si, a ponto de ousar chamar a sua alma esposa do Senhor, contudo, por sermos da Igreja, que com razão se gloria deste nome e da realidade que ele diz, não é sem razão que tomamos parte nessa glória. Pois aquilo que todos juntos possuímos plena e inteiramente, cada um de nós participa sem contestação. Graças te damos, Senhor Jesus, que te dignaste agregar-nos à tua queridíssima Igreja, não só para que fôssemos fiéis, mas também para que nos uníssemos a ti, à maneira de esposa, em abraços alegres, castos e eternos, contemplando também nós de rosto descoberto a tua glória, que te é comum com o Pai e o Espírito Santo pelos séculos dos séculos. Amém.`
    }
  ]
});
