SERMOES.sermao({
  id: 'bernardo-cantico-59',
  colecao: 'bernardo-cantico',
  ordem: 59,
  numero: 'LIX',
  titulo: 'Dos gemidos da alma que suspira pela pátria celeste, e do louvor da castidade e da viuvez',
  fonte: 'De gemitibus animae suspirantis ad coelestem patriam',
  argumento: `"A voz da rola ouviu-se na nossa terra." Pela segunda vez o Deus do céu diz "nossa terra", e Bernardo se detém nessa palavra: é o amor que fala, e o amor não conhece senhor. Ele não se fez como um de nós, mas um de nós; reivindica a terra como pátria, e não como propriedade.

A voz da rola é mais gemido que canto, e lembra a nossa peregrinação: o bom pregador arranca lágrimas, e não aplausos, e convence mais pelo exemplo que pela palavra. Enquanto os homens receberam de Deus só a terra que mana leite e mel, ninguém gemeu como peregrino; com a promessa do reino, o gemido passou a ser de todos. E diz-se "a voz", no singular, porque é o Espírito que geme em todos. A rola é também figura da castidade: tem um só companheiro e, perdido este, não procura outro, nem pousa em ramo verde; a pregação da virgindade só se ouviu na terra com o Evangelho. Voz e flor, palavra e milagre, ouvido e vista: assim entrou a fé no mundo. Os figos verdes da figueira ficam para o sermão seguinte.

Tradução feita do texto latino de Migne (PL 183, 1061-1066).`,
  pontos: [
    {
      n: 1,
      texto: `A voz da rola ouviu-se na nossa terra (Ct 2,12). Já não posso deixar de notar que, pela segunda vez, aquele que é do céu fala da terra: e com tanta condescendência, com tanta familiaridade, como se fosse um da terra. É o esposo: quando disse antes que as flores tinham aparecido na terra, acrescentou "nossa"; e agora igualmente diz: A voz da rola ouviu-se na nossa terra. E ficará sem razão uma expressão tão insólita em Deus, para não dizer indigna dele? Em parte alguma, creio, o acharás falando assim do céu; em parte alguma, noutro lugar, assim da terra. Repara, pois, quanta suavidade há em o Deus do céu dizer: na nossa terra. Ouvi, vós todos, filhos da terra e filhos dos homens: o Senhor fez grandes coisas por nós (Sl 125,3). Muito tem ele com a terra, muito com a esposa, que lhe aprouve tomar da terra para si. Na nossa terra, diz. Esta palavra não soa a domínio, mas a comunhão, a familiaridade. Di-lo como esposo, não como Senhor. Quê? É o Criador, e considera-se companheiro! Fala o amor, que não conhece senhor. É, sem dúvida, um canto de amor, e não convinha sustentá-lo senão com palavras de amor. Também Deus ama, e não tem isto de outro lugar: ele mesmo é aquilo com que ama. E por isso ama com mais veemência, porque não tanto tem o amor quanto o é. E aqueles a quem ama, tem-nos por amigos, não por servos. Enfim, de mestre se faz amigo; pois não chamaria amigos aos discípulos (cf. Jo 15,15), se não o fossem.`
    },
    {
      n: 2,
      texto: `Vês que até a majestade cede ao amor? Assim é, irmãos: o amor não olha ninguém de baixo para cima, mas também não olha ninguém de cima para baixo. Olha como iguais todos os que se amam perfeitamente, e harmoniza em si os altos e os humildes; e não só os faz iguais, mas os faz um. Tu talvez julgues que Deus fica fora desta regra do amor; mas quem se une a Deus é um só espírito com ele (1Cor 6,17). De que te admiras? Ele mesmo se fez como um de nós. Disse pouco: não como um de nós, mas um de nós. É pouco ser igual aos homens: é homem. Por isso reivindica para si a nossa terra, mas como pátria, não como propriedade. E por que não a reivindicaria? Dela vem a sua esposa, dela a substância do seu corpo, dela o próprio esposo, dela os dois numa só carne (cf. Ef 5,31). Se uma só carne, por que não também uma só pátria? O céu dos céus é do Senhor, diz, mas a terra, deu-a aos filhos dos homens (Sl 113,24). Como filho do homem, pois, herda a terra; como senhor, sujeita-a; como criador, governa-a; como esposo, partilha-a. Pois, ao dizer "na nossa terra", recusa sem dúvida a posse exclusiva, mas não rejeita a comunhão. E isto quanto a ter o esposo usado de uma palavra tão benigna, dignando-se dizer "na nossa terra". Vejamos agora o resto.`
    },
    {
      n: 3,
      texto: `A voz da rola ouviu-se na nossa terra. Também isto é sinal de que o inverno passou, e anuncia igualmente que chegou o tempo da poda. Isto segundo a letra. De resto, a voz da rola não soa muito doce, mas significa coisas doces. A própria avezinha, se a compras, não custa muito; se a examinas, vale não pouco. E a sua voz, mais semelhante à de quem geme do que à de quem canta, lembra-nos a nossa peregrinação. De boa vontade ouço a voz daquele mestre que não arranca aplausos para si, mas lágrimas de mim. Mostras-te verdadeiramente rola, se ensinas a gemer; e, se queres persuadir, deverás procurar fazê-lo mais gemendo do que declamando. Pois o exemplo, tanto em muitas outras coisas como sobretudo nesta, é mais eficaz que a palavra. Darás à tua voz a voz da força (cf. Sl 67,34), se se vir que aquilo de que persuades os outros, primeiro o persuadiste a ti mesmo. Mais forte é a voz da obra do que a da boca. Faze o que dizes, e não só me corrigirás mais facilmente, mas também te livrarás de uma vergonha nada leve. Já não te dirá respeito, se alguém disser: Atam fardos pesados e insuportáveis e os põem nos ombros dos homens, mas eles mesmos não os querem mover com o dedo (Mt 23,4). Nem precisarás temer aquilo: Tu que ensinas os outros, não te ensinas a ti mesmo (Rm 2,21).`
    },
    {
      n: 4,
      texto: `A voz da rola ouviu-se na nossa terra. Enquanto os homens receberam como recompensa do culto a Deus só uma recompensa na terra, e só a terra — aquela que mana leite e mel —, não se reconheceram peregrinos sobre a terra, nem gemeram à maneira da rola, como quem se lembra da pátria; antes, abusando do exílio como se fosse a pátria, entregaram-se a comer carnes gordas e a beber vinho doce. Assim, durante todo esse tempo, a voz da rola não se ouviu na nossa terra. Mas, quando se fez a promessa do reino dos céus, então os homens entenderam que não têm aqui cidade permanente, e começaram a buscar com toda avidez a futura (cf. Hb 13,14); e então, pela primeira vez, soou claramente na terra a voz da rola. Pois, quando cada alma santa já suspirava pela presença de Cristo, suportava com pena a demora do reino e saudava de longe, com gemidos e suspiros, a pátria desejada, não te parece que fazia as vezes da rola gemente e castíssima toda alma que assim procedesse na terra? Desde então, pois, a voz da rola ouviu-se na nossa terra. Como não me arrancaria lágrimas frequentes e gemidos diários a ausência de Cristo? Senhor, diante de ti está todo o meu desejo, e o meu gemido não te é escondido (Sl 37,10). Cansei-me no meu gemido, tu o sabes; mas feliz quem pôde dizer: Todas as noites lavarei o meu leito, regarei com as minhas lágrimas a minha cama (Sl 6,7). E não só a mim, mas a todos os que amam a sua vinda (cf. 2Tm 4,8), são conhecidos estes gemidos. Pois é isto o que ele mesmo dizia: Acaso podem os amigos do esposo estar de luto enquanto o esposo está com eles? Mas virão dias em que o esposo lhes será tirado, e então estarão de luto (Mt 9,15); como se dissesse: E então se ouvirá a voz da rola.`
    },
    {
      n: 5,
      texto: `Assim é, bom Jesus: vieram aqueles dias. Pois a própria criação geme e sofre dores de parto até agora, esperando a revelação dos filhos de Deus. E não só ela, mas também nós mesmos gememos no nosso íntimo, esperando a adoção de filhos de Deus, a redenção do nosso corpo (Rm 8,19.22-23), sabendo que, enquanto estamos neste corpo, vivemos exilados longe do Senhor (cf. 2Cor 5,6). E não são vazios os gemidos a que do céu se responde com tanta misericórdia: Por causa da miséria dos necessitados e do gemido dos pobres, agora me levantarei, diz o Senhor (Sl 11,6). Houve também no tempo dos patriarcas esta voz dos que gemem; mas rara, e cada um guardava para si o seu gemido. Por isso dizia alguém: O meu segredo é para mim, o meu segredo é para mim (Is 24,16). E também quem dizia: O meu gemido não te é escondido, mostrava sem dúvida que era escondido um gemido que só a Deus não estava escondido. E por isso não se podia dizer então: A voz da rola ouviu-se na nossa terra; porque o segredo de poucos ainda não tinha saído para a multidão. Mas, quando se proclamou abertamente: Buscai as coisas do alto, onde está Cristo, sentado à direita de Deus (Cl 3,1), este gemido de rola começou a pertencer já a todos, e todos passaram a ter a mesma razão de gemer, porque todos conheciam o Senhor, segundo o que se lê em Jeremias: E todos me conhecerão, do menor ao maior, diz o Senhor (Jr 31,34).`
    },
    {
      n: 6,
      texto: `Mas, se muitos gemem, que quer dizer a menção de um só? A voz da rola, diz. Por que não das rolas? Talvez o Apóstolo o resolva, quando diz que o próprio Espírito intercede pelos santos com gemidos inefáveis (Rm 8,26). Assim é. É apresentado gemendo aquele que faz gemer. E, por muitos que sejam os que ouves gemer assim, é a voz de um só que soa pelos lábios de todos. E por que não a daquele que a forma na boca de cada um, conforme as necessidades de cada qual? Enfim, a cada um é dada a manifestação do Espírito para proveito comum (1Cor 12,7). A voz de cada um o torna manifesto e mostra que está presente. E ouve do Evangelho que o Espírito Santo tem voz: O Espírito, diz, sopra onde quer, e ouves a sua voz, mas não sabes de onde vem nem para onde vai (Jo 3,8). Ainda que não o soubesse aquele mestre morto — Nicodemos — que ensinava aos mortos a letra que mata, saibamo-lo nós, que, transferidos da morte para a vida pelo Espírito que dá a vida, provamos por experiência certa e cotidiana, iluminados por ele, que os nossos desejos e gemidos vêm dele e vão para ele, e ali encontram misericórdia aos olhos de Deus. Pois quando tornaria Deus vã a voz do seu Espírito? E ele sabe o que deseja o Espírito, porque é segundo Deus que intercede pelos santos (cf. Rm 8,27).`
    },
    {
      n: 7,
      texto: `E não são só os gemidos que recomendam a rola; recomenda-a também a castidade. Por este mérito, enfim, foi digna de ser oferecida como vítima pelo parto virginal. Pois tens assim: Um par de rolas ou dois pombinhos (Lc 2,24). E, embora em outros lugares o Espírito Santo costume ser designado pela pomba, como ela é uma ave lasciva, não convinha oferecê-la em sacrifício ao Senhor, senão na idade em que não conhecia a lascívia. Mas da rola não se indica a idade, porque se lhe reconhece a castidade em qualquer idade. Enfim, contenta-se com um só companheiro; perdido este, já não admite outro, censurando nos homens a multiplicidade das núpcias. Pois, embora a culpa, por causa da incontinência, talvez seja perdoável, essa mesma incontinência tão grande é vergonhosa. Dá vergonha que, em matéria de honestidade, a razão não possa no homem o que a natureza pode na ave. Pois pode-se ver a rola, no tempo da sua viuvez, cumprir com empenho e sem se cansar a obra da santa viuvez. Podes vê-la sozinha em toda parte, ouvi-la gemer em toda parte; e nunca a verás pousada num ramo verde, para que aprendas dela a evitar o verde venenoso dos prazeres. Acrescenta que vive de preferência nos cumes dos montes e no alto das árvores, para nos ensinar — o que convém sobretudo ao propósito da castidade — a desprezar as coisas terrenas e amar as celestes.`
    },
    {
      n: 8,
      texto: `Daqui se conclui que a voz da rola é também a pregação da castidade. Pois não foi esta a voz que se ouviu na terra desde o princípio, mas antes aquela: Crescei e multiplicai-vos e enchei a terra (Gn 1,28). Em vão, sem dúvida, teria soado aquela voz da castidade, antes de ser revelada a pátria dos que ressuscitam, na qual, com muito mais felicidade, os homens nem se casarão nem serão dados em casamento, mas são como os anjos de Deus nos céus (cf. Lc 20,35-36). Dirás tu que era tempo para aquela voz quando toda mulher estéril em Israel estava sujeita à maldição, quando os próprios patriarcas tinham várias mulheres ao mesmo tempo, quando a lei obrigava o irmão a suscitar descendência ao irmão morto sem filhos? Mas, quando ressoou da boca da rola celeste aquele louvor dos eunucos que se fizeram eunucos por causa do reino de Deus (cf. Mt 19,12), e quando o conselho de outra rola igualmente castíssima sobre as virgens (cf. 1Cor 7,25) prevaleceu em toda parte, então, pela primeira vez, se pôde dizer com verdade: A voz da rola ouviu-se na nossa terra.`
    },
    {
      n: 9,
      texto: `Se, pois, na nossa terra apareceram as flores e se ouviu a voz da rola, sem dúvida a verdade foi conhecida tanto pela vista como pelo ouvido. Pois a voz ouve-se, a flor vê-se. A flor é o milagre, como diz a nossa interpretação anterior, que, juntando-se à voz, produz o fruto da fé. Se a fé vem pelo ouvido, a confirmação vem pela vista. Soou a voz, brilhou a flor, e a verdade brotou da terra (Sl 84,12) pela confissão dos fiéis, concorrendo juntamente a palavra e o sinal em testemunho da fé. Estes testemunhos tornaram-se sobremaneira dignos de fé (cf. Sl 92,5), porque a flor confirma a voz, e o olho, o ouvido. O que se vê confirma o que se ouve, para que seja válido o testemunho de dois — falo do ouvido e do olho. Por isso o Senhor dizia — falando aos discípulos de João —: Ide contar a João o que ouvistes e vistes (Lc 7,22). Não se lhes podia comunicar a certeza da fé de modo mais breve nem mais claro. E em pouco tempo se persuadiu também a terra inteira, com o mesmo argumento abreviado. O que ouvistes, diz, e vistes. Ó palavra abreviada, e contudo viva e eficaz! Afirmo sem nenhuma dúvida o que percebi com os ouvidos e com os olhos. Troveja a trombeta da salvação, fulguram os milagres, e o mundo crê. Depressa se persuade o que se diz, quando se mostra aquilo que espanta. E tens que os apóstolos partiram e pregaram em toda parte, cooperando com eles o Senhor e confirmando a palavra com os sinais que a acompanhavam (Mc 16,20). Tens no monte aquele que se transfigurou com uma claridade assombrosa e que foi também atestado pela voz do alto (Mt 17,2-5). Tens igualmente no Jordão a pomba que o designa e a voz que dá testemunho (Mt 3,16-17). Assim estas duas coisas, a voz e o sinal, concorrem juntas em toda parte, pela generosidade divina, para introduzir a fé, para que a verdade tenha entrada larga até a alma pelas duas janelas.`
    },
    {
      n: 10,
      texto: `Segue-se: A figueira deu os seus figos verdes (Ct 2,13). Não comamos deles: não são bons para comer, por não estarem maduros. Têm o aspecto dos bons figos, mas a semelhança, e não o sabor; designam talvez os hipócritas. Não os lancemos fora, porém; talvez precisemos deles para outra coisa. De outro modo, cairão por si mesmos, facilmente e antes do tempo, como a erva dos telhados, que seca antes de ser arrancada (Sl 128,6) — o que julgo dito dos hipócritas. Não é sem razão, porém, que se fez menção deles num canto nupcial. Servirão sem dúvida, se não para comer, para algum uso. Nas núpcias providenciam-se necessariamente muitas coisas além das iguarias. E eu julgo que isto de modo nenhum se deve omitir, tanto que, seja o que for, não o quero discutir no aperto do fim deste sermão; mas deixo-o para outro dia e para uma hora mais livre. Se com razão, podereis então verificá-lo; só que as vossas orações me obtenham a ocasião e a capacidade de exprimir o que sinto, para vossa edificação e para louvor e glória do esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
