SERMOES.sermao({
  id: 'bernardo-cantico-70',
  colecao: 'bernardo-cantico',
  ordem: 70,
  numero: 'LXX',
  titulo: 'Por que o esposo é chamado amado; e da verdade, da mansidão, da justiça e das demais virtudes, que são os lírios entre os quais ele se apascenta',
  fonte: 'Unde sponsus dilectus dicatur',
  argumento: `A esposa acrescenta que o amado "se apascenta entre os lírios", e esse rebaixamento afasta dela a acusação de ousadia. Aquele que apascenta todas as coisas e reina acima dos astros só se tornou o amado quando desceu aos lírios e foi visto apascentar-se entre eles: não podia ser amado antes de ser conhecido; os patriarcas e os profetas o amaram porque o viram em espírito, e ter crido é ter visto. Apascentar-se, porém, soa a indigência; e a esposa, que antes perguntava onde ele apascentava, conhece agora só o lugar humilde onde ele se apascenta.

Os lírios são as virtudes pelas quais o salmo faz o esposo reinar: a verdade, que brotou da terra e cujo perfume atraiu os magos; a mansidão do Cordeiro; a justiça, que florescerá eternamente. Tudo em Cristo é lírio, da concepção à ascensão, e o seu perfume alivia o exílio de quem não o viu, mas crê. Bernardo, pobre de lírios, deseja ao menos dois — a inocência e a continência —, guardados por um terceiro, a paciência, para que o amado se digne apascentar-se também nele.

Tradução feita do texto latino de Migne (PL 183, 1116-1121).`,
  pontos: [
    {
      n: 1,
      texto: `O meu amado para mim, e eu para ele, que se apascenta entre os lírios (Ct 2,16). Quem lhe imputaria agora presunção ou ousadia, se diz ter feito aliança com aquele que se apascenta entre os lírios? Ainda que se apascentasse entre os astros, só pelo fato de se apascentar, não sei que grandeza poderia parecer ter amizade ou familiaridade com alguém assim. Apascentar-se soa, certamente, a coisa vulgar e baixa. Mas agora, quando se diz que se apascenta entre lírios, o acréscimo deste rebaixamento afasta e repele para mais longe a acusação de temeridade. Pois que são os lírios? Segundo a palavra do Senhor, erva do campo, que hoje existe e amanhã é lançada ao forno (Mt 6,28-30). Que grandeza tem esse que se alimenta de erva, como um dos cordeiros ou dos novilhos? E é, de fato, cordeiro, e novilho cevado (cf. Lc 15,23). Mas tu talvez, mais atento, reparaste que aqui não se designa o pasto, mas o lugar: pois não se disse que se apascenta de lírios, mas entre os lírios. Seja. Não come erva como o boi (cf. Jó 40,10); mas andar no meio da erva e reclinar-se sobre a erva como um da multidão (cf. Jo 6,10), que grandeza pode ter? E que glória há para ela em ter por amado aquele que fez isso? Segundo a letra, aparece bem o pudor da esposa e a cautela da sua prudência no falar: ela dispõe as suas palavras com discernimento (cf. Sl 111,5) e tempera a glória das coisas com a modéstia das palavras.`
    },
    {
      n: 2,
      texto: `Aliás, ela não ignora que é um só aquele que se apascenta e aquele que apascenta; o que mora entre os lírios e o que reina acima dos astros. Mas lembra de melhor vontade as humilhações do amado — por humildade, sem dúvida, como disse; mais ainda, porém, porque começou a ser amado a partir do momento em que começou também a apascentar-se. E não só a partir daí, mas por causa disso. Pois aquele que nas alturas é Senhor, nas profundezas é amado: reinando acima dos astros, e amando entre os lírios. Amava também acima dos astros, porque em lugar nenhum e em tempo nenhum pôde deixar de amar, porque é amor (cf. 1Jo 4,8); mas, enquanto não desceu aos lírios e não foi visto apascentar-se entre os lírios, nem foi amado, nem se tornou o amado. Quê? Não foi amado pelos patriarcas e pelos profetas? Foi; mas não antes de ter sido visto também por eles apascentar-se entre os lírios. Pois não deixaram de ver aquele que previram; a não ser que alguém seja tão desprovido de espírito que pense que quem vê em espírito nada vê. Por que então se chamavam videntes — pois assim eram chamados os profetas (1Sm 9,9) —, se nada viram? Daí vem que quiseram ver aquele que não viram (cf. Lc 10,24). Pois não podiam querer ver no corpo aquele que não tivessem visto em espírito. Mas digo: acaso eram todos profetas (cf. 1Cor 12,29)? Como se todos tivessem querido ver, ou a fé fosse de todos (cf. 2Ts 3,2). Mas os que viram, ou foram profetas, ou deram crédito aos profetas. Pois ter crido é ter visto. E, se alguém disser que vê em espírito não só quem vê pelo espírito de profecia, mas também quem vê pela fé, não me parece que erre.`
    },
    {
      n: 3,
      texto: `Assim, pois, o fato de aquele que apascenta todos se ter dignado descer aos lírios e apascentar-se entre os lírios fez dele o amado, porque não pôde ser amado antes de ser conhecido. E por isso, ao fazer-se menção do amado, belamente se lembrou também aquilo que foi causa do amor e do conhecimento. Este alimento entre os lírios deve ser procurado em sentido espiritual: pois pensá-lo corporal seria ridículo. Mais ainda: também os próprios lírios espirituais, se pudermos, teremos de mostrar. Penso que teremos de dizer também de que se alimenta o amado entre os lírios: dos próprios lírios, ou de outras ervas ou flores escondidas entre os lírios? E nisto me parece mais difícil que se diga que se apascenta, e não que apascenta. Que apascente, não há dúvida, nem é indigno dele; mas apascentar-se soa a indigência, e parece que nem em sentido espiritual se lhe pode atribuir facilmente sem ofensa à majestade. E, por certo, não me lembro de ter notado até agora, neste cântico, que em algum lugar se diga que ele se apascenta, ao passo que, que apascenta, penso que vos lembrais comigo. Enfim, ela pediu certa vez que lhe mostrasse onde apascentava e onde repousava ao meio-dia (Ct 1,6). E agora diz o que ainda não tinha dito, que ele se apascenta; mas não pede igualmente que se lhe indique o lugar: ela mesma o indica, designando-o: entre os lírios. Conhece este, não conhecia aquele; porque não pode estar igualmente ao alcance o que é sublime e está nas alturas, e o que é humilde e está sobre a terra. Obra sublime, lugar também sublime: e até agora nem a própria esposa tem acesso a ele.`
    },
    {
      n: 4,
      texto: `E por isso esvaziou-se a si mesmo (cf. Fl 2,7) a ponto de o próprio pastor de todos se apascentar; e foi encontrado entre os lírios, e, visto pela Igreja, foi amado — o pobre pela indigente —, tornando-se o amado por causa da semelhança. E não só, mas também por causa da verdade, da mansidão e da justiça: porque por ele se cumpriram as promessas, foram perdoadas as iniquidades, foram julgados os demônios soberbos juntamente com o seu príncipe (cf. Jo 16,11). Assim apareceu digno de ser amado: verdadeiro por si mesmo, manso para com os homens, justo em favor dos homens. Ó esposo verdadeiramente digno de ser amado e abraçado com todas as fibras do coração! Por que hesitaria ainda a Igreja em entregar-se toda, com toda a devoção, a quem tão fielmente cumpre, tão piedosamente perdoa, tão justamente defende? O Profeta, aliás, tinha dito antes: Na tua formosura e na tua beleza, avança com êxito (Sl 44,5). Donde vem esta formosura e esta beleza? Penso que dos lírios. Que há de mais formoso que o lírio? Assim, nada há de mais belo que o esposo. Quais são, pois, os lírios de que lhe vem a formosura? Avança, diz, e reina, pela verdade, pela mansidão e pela justiça (Sl 44,5). São lírios; lírios, digo, nascidos da terra, brilhando sobre a terra, sobressaindo entre as flores da terra, perfumados acima do odor dos aromas. É, pois, entre estes lírios que está o esposo, e é deles que lhe vem toda a formosura e beleza. Pois, de outro modo — no que se refere às fraquezas da carne —, não tinha formosura nem beleza (Is 53,2).`
    },
    {
      n: 5,
      texto: `Bom lírio é a verdade, notável pela brancura, excelente pelo perfume; enfim, é a brancura da luz eterna (Sb 7,26), o esplendor e a figura da substância de Deus (cf. Hb 1,3). Lírio, certamente, que a nossa terra produziu por uma nova bênção, e que foi preparado diante da face de todos os povos, luz para a revelação das nações (Lc 2,31-32). Enquanto a terra esteve sob a maldição, produziu espinhos e abrolhos (cf. Gn 3,18). Mas agora a verdade brotou da terra (Sl 84,12), pela bênção do Senhor (cf. Sl 84,2): flor do campo de toda formosura, e lírio dos vales (cf. Ct 2,1). Reconhece o lírio pela brancura, que logo, no próprio nascer da flor, brilhou de noite para os pastores, dizendo o Evangelho que o anjo do Senhor se apresentou junto deles, e a claridade de Deus os envolveu com a sua luz (Lc 2,9). Bem se diz de Deus, porque não era a brancura do anjo, mas a do lírio. Aquele estava presente, mas esta resplandecia desde Belém. Reconhece o lírio também pelo perfume, pelo qual se deu a conhecer aos magos, que estavam longe. É verdade que apareceu a estrela; mas homens sérios de modo nenhum a teriam seguido, se não fossem atraídos por um íntimo perfume do lírio que tinha nascido. E é bem um lírio a verdade, cujo perfume anima a fé e cujo esplendor ilumina a inteligência. Ergue agora também os olhos para a própria pessoa do Senhor, que diz no Evangelho: Eu sou a verdade (Jo 14,6). E vê com quanta propriedade a verdade se compara ao lírio. Se não reparaste, repara como do meio desta flor saem como que pequenas hastes de ouro, cercadas de pétalas branquíssimas, dispostas em coroa com beleza e harmonia; e reconhece em Cristo a divindade de ouro, coroada pela pureza da natureza humana, isto é, Cristo com o diadema com que o coroou a sua mãe (Ct 3,11). Pois, no diadema com que o coroou o seu Pai, habita uma luz inacessível (cf. 1Tm 6,16), e por ora não poderias vê-lo nela. Mas disto, noutra ocasião.`
    },
    {
      n: 6,
      texto: `Por agora: a verdade é um lírio; é-o também a mansidão. E bem é lírio a mansidão, que tem a brancura da inocência e o perfume da esperança, pois, diz, há uma posteridade para o homem pacífico (Sl 36,37). O homem manso é de boa esperança, e não é menos, já no presente, um luminoso exemplo de vida em comum. Não é lírio a que brilha pelas boas obras e exala o perfume da esperança? Acrescenta que, assim como a verdade brotou da terra, assim também a mansidão. A não ser que alguém duvide de que brotou da terra o Cordeiro dominador da terra (Is 16,1), aquele cordeiro que foi levado ao matadouro e não abriu a boca (Is 53,7). E não só a mansidão ou a verdade brotou da terra, mas também a justiça, como diz o profeta: Céus, destilai lá do alto o vosso orvalho, e as nuvens chovam o justo; abra-se a terra e germine o Salvador, e brote juntamente a justiça (Is 45,8). E que a justiça seja um lírio, lembrai-vos da Escritura: O justo germinará como o lírio e florescerá eternamente diante do Senhor (cf. Os 14,6). Este lírio de modo nenhum existe hoje e amanhã é lançado ao forno, porque florescerá eternamente. E florescerá diante do Senhor, em cuja memória o justo será eterno, e não temerá a má notícia (Sl 111,7) — isto é, aquela que se ouvirá, mandando os pecadores para a fornalha de fogo (cf. Mt 13,42). E a brancura deste lírio, para quem não brilha, senão para quem não gosta dela? Enfim, é sol, mas não aquele que se levanta sobre bons e maus (cf. Mt 5,45). Pois os que hão de dizer: O sol da justiça não nasceu para nós (Sb 5,6), nunca viram a sua luz. Viram-na, porém, todos os que ouviram: Para vós, que temeis a Deus, nascerá o sol da justiça (Ml 4,2). A brancura deste lírio, pois, está com os justos; o perfume espalha-se até aos iníquos, ainda que não para o bem deles. Enfim, ouvimos os justos dizerem: Somos o bom odor de Cristo em todo lugar; para uns, odor de vida para a vida; para outros, odor de morte para a morte (2Cor 2,15-16). Quem, ainda que seja o mais criminoso, não aprova a boa fama do justo, embora não ame a sua obra? E feliz, se não se condena naquilo que aprova (cf. Rm 14,22). Mas condena-se, aprovando o bem e não o amando; e por isso não é feliz, mas infeliz, condenado pelo próprio juízo. Que há de mais infeliz que aquele para quem o odor da vida é mensageiro, não da vida, mas da morte? Ou antes, nem sequer mensageiro, mas portador.`
    },
    {
      n: 7,
      texto: `Há junto do esposo muitos outros lírios além destes que nos vieram do Profeta — falo da verdade, da mansidão e da justiça —; e já não será difícil a qualquer de vós encontrar por si mesmo outros semelhantes no jardim de um esposo tão delicioso. Tem-nos em abundância e superabundância: quem os poderia enumerar? Tantas virtudes, tantos lírios. Que fim têm as virtudes junto do Senhor das virtudes (cf. Sl 23,10)? Se em Cristo está a plenitude das virtudes, também a dos lírios. E talvez por isso ele mesmo se tenha chamado lírio (cf. Ct 2,1), porque vive todo entre lírios, e tudo o que é dele são lírios: a concepção, o nascimento, a vida, as palavras, os milagres, os sacramentos, a paixão, a morte, a ressurreição, a ascensão. Qual destas coisas não é branca e não exala o mais suave perfume? Enfim, na concepção resplandeceu tamanha claridade da luz do alto, pela abundância do Espírito que sobreveio, que nem a própria Virgem santa a teria suportado, se não fosse coberta com a sombra do poder do Altíssimo (cf. Lc 1,35). O nascimento, tornou-o branco a virgindade intacta da mãe; a vida, a inocência; as palavras, a verdade; os milagres, a pureza do coração; os sacramentos, o segredo da piedade; a paixão, a vontade de padecer; a morte, a liberdade de não morrer; a ressurreição, a fortaleza dos mártires; a ascensão, o cumprimento das promessas. Que bom perfume de fé há em cada uma destas coisas, enchendo os nossos tempos e as nossas entranhas, a nós que não vimos a brancura! E bem-aventurados os que não viram e creram (Jo 20,29). A minha parte nelas é o odor de vida que delas procede. Este, infundido nas minhas narinas pelo instrumento apropriado da fé — e tanto mais abundantemente quanto maior é a multidão dos lírios —, alivia o exílio e renova sem cessar nas minhas entranhas o desejo da pátria.`
    },
    {
      n: 8,
      texto: `Também alguns dos companheiros do esposo têm lírios, mas não em abundância. Pois todos receberam o Espírito com medida, com medida as virtudes e os dons; só não tem medida (cf. Jo 3,34) aquele que tem tudo. Uma coisa é ter lírios, outra ter só lírios. Quem me darás, dentre os filhos do cativeiro, tão inocente e santo que tenha podido cobrir de flores toda a sua terra, e de flores assim? Nem a criança de um só dia está sem mancha sobre a terra (cf. Jó 14,4-5). Grande é quem conseguir cultivar três ou quatro lírios na sua terra, em meio a tamanha densidade de espinhos e abrolhos, que são os rebentos envelhecidos da antiga maldição. Quanto a mim, que sou pobre, já será bom se algum dia, arrancando e cultivando, conseguir resgatar desta péssima seara — a das iniquidades e dos vícios — um pedacinho da minha terra onde possa produzir ao menos um lírio, para que talvez também em mim se digne às vezes apascentar-se aquele que se apascenta entre os lírios.`
    },
    {
      n: 9,
      texto: `Mas disse pouco: um só. A minha boca falou da penúria do meu coração. Um só, de modo nenhum basta; são necessários ao menos dois. Refiro-me à continência e à inocência, das quais uma sem a outra não salvará. Em vão, enfim, convidarei o esposo para uma só delas, qualquer que seja, ele de quem se diz que se apascenta não junto de um lírio, mas entre lírios. Procurarei, pois, ter lírios, para que não se queixe de haver um só lírio aquele que não quer apascentar-se senão entre lírios, e assim não se afaste irado do seu servo (cf. Sl 26,9). Ponho, pois, em primeiro lugar a inocência; e, se puder juntar-lhe a continência, me julgarei rico na posse de lírios. E serei rei, se puder acrescentar-lhes uma terceira: a paciência. Aquelas duas podem, de fato, bastar; mas, como também podem desfalecer nas tentações — pois a vida do homem sobre a terra é tentação (Jó 7,1) —, é certamente necessária a paciência, que seja como que a tutora e a guarda de ambas. Penso que, se vier aquele amante dos lírios e nos encontrar assim, não desdenhará apascentar-se junto de nós e celebrar junto de nós a Páscoa (cf. Mt 26,18), onde terá muita suavidade nas duas e grande segurança por causa da terceira. Mas como se diz que se apascenta aquele que apascenta todas as coisas, veremos depois. Por agora, vê-se que o esposo não só aparece entre os lírios, mas de modo nenhum pode jamais ser encontrado fora dos lírios, pois tudo o que é dele, e ele mesmo, é lírio: o esposo da Igreja, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
