SERMOES.sermao({
  id: 'bernardo-cantico-04',
  colecao: 'bernardo-cantico',
  ordem: 4,
  numero: 'IV',
  titulo: 'Do tríplice progresso da alma, que se faz pelo beijo do pé, da mão e da boca do Senhor',
  fonte: 'De triplici profectu animae',
  argumento: `Retomando o sermão interrompido na véspera, Bernardo explica primeiro por que chama beijos aos dois primeiros degraus, e depois responde a uma objeção: se Deus é espírito, que boca, que mão, que pés são esses? A resposta leva o sermão à questão de como Deus é o ser de todas as coisas — e é ela que fica para o dia seguinte.

Tradução feita do texto latino de Migne (PL 183, 796-798).`,
  pontos: [
    {
      n: 1,
      texto: `O sermão de ontem tratou, sob o nome de três beijos, de um tríplice progresso da alma. Acaso já o esquecestes? Hoje vou continuá-lo, conforme Deus, na sua doçura, se dignar prover ao pobre (Sl 67,11). Dissemos, se vos lembrais, que esses beijos se dão nos pés, na mão e na boca, e atribuímos cada um a uma etapa. O primeiro marca o início da nossa conversão; o segundo é concedido aos que progridem; o terceiro, só a perfeição o experimenta, e ela é rara. A Escritura que começamos a comentar parte apenas deste último, o que vem no fim; os outros dois fomos nós que os acrescentamos, por causa dele. Se era necessário, vós o julgareis. Penso, aliás, que a própria letra do texto facilmente sugere que também esses devem ser buscados. Seria de admirar que também vós não percebêsseis que deve haver, de fato, outro beijo, ou outros beijos, dos quais quis distinguir o beijo da boca aquele que disse: Beije-me com o beijo da sua boca (Ct 1,1). Pois, quando bastaria dizer simplesmente «beije-me», por que acrescentou, contra o modo habitual de falar, de forma clara e expressa, «com o beijo da sua boca», senão para mostrar que o beijo que pedia era o mais alto, e não o único? Não é assim, afinal, que falamos uns com os outros: «Beija-me», ou «dá-me um beijo»? E ninguém acrescenta: «com a tua boca», ou «com o beijo da tua boca». Mais ainda: quando duas pessoas se preparam para se beijar, aproximam a boca uma da outra, mas não a pedem expressamente. E o evangelista, ao narrar que o Senhor recebeu o traidor com um beijo, diz apenas: E beijou-o (Mc 14,45), sem acrescentar «com a sua boca» ou «com o beijo da sua boca». É assim, sem dúvida, que costuma fazer todo aquele que escreve ou fala. São estes, portanto, os três afetos, ou progressos, da alma — bem conhecidos e claros, pelo menos para quem os experimentou —: quando ela obtém o perdão do mal que fez, ou a graça para fazer o bem, ou ainda a contemplação da presença daquele mesmo que perdoa e concede os benefícios, na medida em que isso é possível num corpo frágil.`
    },
    {
      n: 2,
      texto: `Entendei agora com mais clareza por que chamei beijos ao primeiro e ao segundo. Todos sabemos que o beijo é sinal de paz. Ora, se, como diz a Escritura, os nossos pecados nos separam de Deus (Is 59,2), basta tirar do meio o que se interpõe, e há paz. Quando, portanto, damos satisfação a Deus e, removido o pecado que nos separava, somos reconciliados com ele, que outra coisa é o perdão que recebemos senão um beijo de paz? E esse beijo, por ora, só se pode receber aos pés. Pois deve ser humilde e envergonhada a satisfação com que se repara uma transgressão soberba.`
    },
    {
      n: 3,
      texto: `Mas, quando recebemos também uma graça mais abundante e certa doce familiaridade com Deus, para vivermos de modo mais reto e nos portarmos de maneira mais digna dele, então levantamos do pó a cabeça com mais confiança, para beijar, como se costuma fazer, a mão de quem nos deu o dom — contanto que, com o dom recebido, não busquemos a nossa glória, mas a de quem o deu, e atribuamos a ele os seus dons, e não a nós mesmos. Do contrário, se te glorias em ti mesmo e não no Senhor, fica provado que beijas a tua própria mão, e não a do Senhor: o que, segundo a palavra do bem-aventurado Jó, é a maior das iniquidades e uma negação de Deus (Jó 31,27-28). Se, pois, segundo o testemunho da Escritura, buscar a própria glória é beijar a própria mão, então não é descabido dizer que quem dá glória a Deus beija a mão de Deus. E vemos que assim acontece entre os homens: os servos costumam beijar os pés do senhor que ofenderam, quando lhe pedem perdão; e os pobres beijam as mãos dos ricos, quando deles recebem uma dádiva.`
    },
    {
      n: 4,
      texto: `Mas, como Deus é espírito (Jo 4,24), e aquela substância simples não se divide em membros corporais, talvez haja quem de modo algum aceite dizer tais coisas de Deus e exija que eu lhe mostre as mãos e os pés de Deus, para provar assim o que afirmo sobre o beijo dos pés e da mão. Mas e se eu, por minha vez, perguntar a esse questionador pela boca de Deus, para que ele me demonstre que aquilo que a Escritura diz do beijo da boca se aplica a Deus? Pois, certamente, ou Deus tem boca, e também mãos e pés; ou não tem mãos nem pés, e tampouco boca. Ora, Deus tem boca, com a qual ensina ao homem a ciência (Sl 93,10); tem mão, com a qual dá alimento a toda carne (Sl 135,25); e tem pés, dos quais a terra é o escabelo (Is 66,1), e diante dos quais os pecadores da terra, convertidos e humilhados, dão satisfação. Deus tem tudo isso, digo, por seus efeitos, e não por natureza. Com efeito, em Deus a confissão envergonhada encontra onde se prostrar em humildade; a devoção generosa, onde se refazer e renovar; e a contemplação alegre, onde repousar em êxtase. Aquele que governa todas as coisas é tudo para todos, e não é propriamente nenhuma delas. Pois, no que é em si mesmo, habita numa luz inacessível (1Tm 6,16); a sua paz ultrapassa todo entendimento (Fl 4,7); a sua sabedoria é sem medida (Sl 146,5); a sua grandeza não tem fim (Sl 144,3); e nenhum homem pode vê-lo e continuar vivo (Ex 33,20). Não que esteja longe de cada um de nós (At 17,27) aquele que é o ser de todas as coisas, sem o qual tudo é nada; mas — para que te admires ainda mais — nada há mais presente do que ele, e nada mais incompreensível. Pois que há de mais presente a cada coisa do que o seu próprio ser? E, no entanto, que há de mais incompreensível para cada uma do que o ser de todas? Digo que Deus é o ser de todas as coisas não porque elas sejam o que ele é, mas porque dele, por ele e nele são todas as coisas (Rm 11,36). O próprio Criador é, portanto, o ser de todas as coisas que foram feitas — mas como causa, e não como matéria. É deste modo que aquela majestade se digna ser para as suas criaturas: para todas, aquilo pelo qual existem; para as que têm vida, também aquilo pelo qual vivem; para as que usam a razão, luz; para as que a usam bem, virtude; para as que vencem, glória.`
    },
    {
      n: 5,
      texto: `E para todas essas obras — criar, governar, administrar, mover, fazer progredir, renovar, consolidar — não precisa de nenhum instrumento corporal aquele que, só com a palavra, criou tanto os corpos como os espíritos. As almas precisam de corpos e de sentidos corporais, para se darem a conhecer umas às outras e para poderem agir. Não é assim com o Deus onipotente, a quem basta a vontade para, com rapidez, criar as coisas e ordená-las como quiser. Ele pode tudo quanto quer, sem precisar do serviço de membros corporais. E então? Julgas que, para ver aquilo que ele mesmo criou, precise do auxílio de algum sentido corporal? Nada, absolutamente, se esconde ou escapa à luz que está presente em toda parte; e, no entanto, para conhecer alguma coisa, ele não precisa que um sentido lhe traga a notícia. E não somente conhece todas as coisas sem corpo, mas também se dá a conhecer sem corpo aos puros de coração. Gostaria de dizer isto mais longamente, para que ficasse mais claro. Mas, como o tempo que resta a este sermão, que já deve terminar, talvez não o permita, é mais prudente deixá-lo para amanhã.`
    }
  ]
});
