SERMOES.sermao({
  id: 'bernardo-cantico-06',
  colecao: 'bernardo-cantico',
  ordem: 6,
  numero: 'VI',
  titulo: 'Do Espírito supremo e sem limites, que é Deus; e de como a misericórdia e o juízo se chamam pés do Senhor',
  fonte: 'De summo et incircumscripto Spiritu',
  argumento: `Retomando o fio deixado no sermão anterior, Bernardo conclui que só Deus não precisa de corpo — e logo pergunta por que, então, a Escritura lhe dá boca, mão e pés. A resposta é a Encarnação: aquele que agia invisivelmente desde sempre tomou carne para que os homens, que só sabiam a carne, pudessem enfim reconhecê-lo.

Daí ele nomeia os dois pés do Senhor: a misericórdia e o juízo. E termina contando o que lhe aconteceu quando se prendeu demais a um só deles.

Tradução feita do texto latino de Migne (PL 183, 803-806).`,
  pontos: [
    {
      n: 1,
      texto: `Para que este sermão se ligue ao anterior: lembrais-vos do que ficou assente, que só o Espírito supremo e sem limites não precisa do instrumento nem do serviço de um corpo para tudo o que quer fazer, ou quer que se faça? Atribuamos, pois, com segurança, só a Deus a verdadeira incorporeidade, como lhe atribuímos a verdadeira imortalidade: só ele, entre os espíritos, ultrapassa de tal modo toda a natureza corporal que não precisa de corpo algum para obra alguma, bastando-lhe um simples aceno do espírito para fazer, quando quer, tudo o que quer. É, portanto, a única a não precisar de instrumento corporal, nem por causa de si nem por causa de outro, aquela majestade a cujo arbítrio onipotente toda obra obedece sem demora, diante de quem tudo o que é alto se inclina, tudo o que é contrário cede e tudo o que é criado se presta — e isso sem que nenhum auxílio, corporal ou espiritual, intervenha ou a socorra. Ensina e adverte sem língua; dá e retém sem mãos; sem pés corre e socorre os que se perdem.`
    },
    {
      n: 2,
      texto: `Assim agia também com os pais, nos séculos passados: os homens experimentavam benefícios contínuos, mas o benfeitor permanecia oculto para eles. Ele atingia com força de uma extremidade à outra; mas, dispondo tudo com suavidade (Sb 8,1), não era percebido pelos homens. E alegravam-se com os bens do Senhor; mas o Senhor dos exércitos, que julga todas as coisas com tranquilidade (Sb 12,18), esse eles ignoravam por completo. Vinham dele, mas não estavam com ele; viviam por ele, mas não para ele; dele lhes vinha o entendimento, mas não era a ele que entendiam — estranhos, ingratos, insensatos. Daí veio, por fim, que não atribuíssem ao autor o que eram, o que viviam e o que sabiam, mas o creditassem à natureza, ou então, o que era ainda mais insensato, à sorte; e muitos atribuíam muita coisa ao próprio esforço e à própria capacidade. Quanto os espíritos sedutores usurparam para si! Quanto se deu ao sol e à lua, quanto se atribuiu à terra e às águas, e quanto até às obras fabricadas pelas mãos dos mortais! Prestava-se culto divino a ervas, a arbustos e às mais miúdas e vis sementes.`
    },
    {
      n: 3,
      texto: `Ai! Foi assim que os homens perderam e trocaram a sua glória pela imagem de um novilho que come feno (Sl 105,20). Compadecido dos seus erros, Deus saiu por bondade do monte sombrio e espesso (Hab 3,3) e pôs no sol a sua tenda (Sl 18,6). Ofereceu carne aos que só sabiam a carne, para que por ela aprendessem a saborear também o espírito. Pois, ao fazer na carne e pela carne obras que não são da carne, mas de Deus — dando ordens à natureza, vencendo a sorte, tornando louca a sabedoria dos homens e derrotando a tirania dos demônios —, mostra claramente que é ele mesmo aquele por quem, antes, se faziam essas mesmas coisas, quando se faziam. Na carne, digo, e pela carne, operando maravilhas com poder e à vista de todos, dizendo palavras que curam, sofrendo indignidades, mostrou com evidência que é ele quem, com poder mas invisivelmente, criou os séculos, os governa com sabedoria e os protege com bondade. Enfim, quando anuncia o Evangelho aos ingratos, dá sinais aos infiéis e reza por quem o crucifica, não declara com toda a clareza que é ele quem, com o seu Pai, faz nascer cada dia o seu sol sobre bons e maus e faz chover sobre justos e injustos (Mt 5,45)? É isto que ele mesmo dizia: Se não faço as obras do meu Pai, não acrediteis em mim (Jo 10,37).`
    },
    {
      n: 4,
      texto: `Eis que abre a boca da sua carne para ensinar os discípulos no monte aquele que, em silêncio, ensina os anjos nos céus. Eis que ao toque de uma mão corporal se cura a lepra, foge a cegueira, volta a audição, solta-se a língua muda, o discípulo quase afogado é erguido; e reconhece-se sem dúvida alguma aquele a quem Davi, muito antes, dissera: Abres a tua mão e enches de bênção todo ser vivo (Sl 144,16); e ainda: Ao abrires a tua mão, tudo se encherá de bondade (Sl 103,28). Eis que a pecadora, prostrada e arrependida junto a uns pés corporais, ouve: Os teus pecados estão perdoados (Lc 7,48), e reconhece aquele de quem, muitos tempos antes, lera o que estava escrito: O diabo sairá diante dos seus pés (Hab 3,5). Pois onde o pecado é perdoado, ali sem dúvida o diabo é expulso do coração do pecador. Por isso, falando de todos os penitentes em geral, diz: Agora é o julgamento deste mundo; agora o príncipe deste mundo será lançado fora (Jo 12,31) — isto é: a quem se confessa com humildade, Deus perdoa o pecado, e o diabo perde o principado que havia tomado no coração do homem.`
    },
    {
      n: 5,
      texto: `Enfim, caminha sobre as ondas com pés de carne (Mt 14,25) aquele a quem o salmista, quando ele ainda não se revestira de carne, já cantara: No mar está o teu caminho, e as tuas veredas em muitas águas — o que quer dizer: pisas os corações inchados dos soberbos e reprimes os desejos instáveis dos carnais, justificando os ímpios e humilhando os orgulhosos. Mas, como isso se faz invisivelmente, o homem carnal não percebe por quem se faz. Por isso o salmista acrescenta: E as tuas pegadas não serão conhecidas (Sl 76,20). Daí, de novo, o Pai ao Filho: Senta-te à minha direita, até que eu ponha os teus inimigos como escabelo dos teus pés (Sl 109,1) — isto é: até que eu submeta à tua vontade todos os que te desprezam, uns contra a vontade e infelizes, outros de livre vontade e bem-aventurados. E como a carne não percebia esta obra do Espírito — pois o homem animal não percebe as coisas que são do Espírito de Deus (1Cor 2,14) —, foi preciso que a pecadora, inclinada corporalmente sobre uns pés corporais e beijando esses mesmos pés com lábios corporais, recebesse o perdão dos pecados; e assim aquela mudança operada pela direita do Altíssimo (Sl 76,11), com que ele justifica o ímpio de modo admirável, mas invisível, se tornasse conhecida até dos homens carnais.`
    },
    {
      n: 6,
      texto: `Não devo, porém, passar por cima daqueles pés espirituais de Deus, que o penitente deve beijar espiritualmente em primeiro lugar. Conheço a vossa curiosidade, que de bom grado não deixa passar nada que fique encoberto. E não se deve ter por coisa de pouco valor saber com que pés a Escritura tantas vezes diz que Deus ora está de pé, como naquilo: Adoraremos no lugar onde estiveram os seus pés (Sl 131,7); ora caminha, como naquilo: Habitarei neles e andarei entre eles (Lv 26,12; 2Cor 6,16); ora até corre, conforme aquilo: Exultou como um gigante para percorrer o seu caminho (Sl 18,6). Se ao Apóstolo pareceu acertado referir a cabeça de Cristo à divindade (1Cor 11,3), penso que também a nós não parecerá descabido que os pés pertençam à sua humanidade; e chamemos a um deles misericórdia, e ao outro juízo. Conheceis bem estas duas palavras; e, se pensardes nisso, elas vos ocorrerão juntas em muitíssimos lugares da Escritura. Que Deus assumiu o pé da misericórdia na carne à qual se uniu, ensina-o a Carta aos Hebreus, quando afirma que Cristo foi provado em tudo à nossa semelhança, exceto no pecado, para se tornar misericordioso (Hb 4,15). E quanto ao outro, a que chamamos juízo, não indica o próprio Deus feito homem, com toda a clareza, que também ele pertence igualmente à humanidade assumida, quando declara que o Pai lhe deu o poder de julgar, porque é Filho do homem (Jo 5,27)?`
    },
    {
      n: 7,
      texto: `Unindo-se, pois, harmoniosamente estes dois pés sob uma só cabeça, que é a divindade, o invisível Emanuel, nascido de mulher e sujeito à lei (Gl 4,4), foi visto na terra e conviveu com os homens (Br 3,38). Com esses mesmos pés ele passa ainda hoje, fazendo o bem e curando todos os oprimidos pelo diabo (At 10,38) — mas espiritualmente, mas invisivelmente. Com esses pés, digo, percorre as almas devotas, visitando sem cessar e sondando os corações e os rins dos fiéis. Vê se não serão estas as pernas do esposo, que a esposa mais adiante louva com tanta magnificência, comparando-as, se não me engano, a colunas de mármore assentadas sobre bases de ouro (Ct 5,15). E com toda a propriedade: pois na Sabedoria de Deus encarnada, que o ouro designa, a misericórdia e a verdade se encontraram (Sl 84,11); e, enfim, todos os caminhos do Senhor são misericórdia e verdade (Sl 24,10).`
    },
    {
      n: 8,
      texto: `Feliz a alma em que o Senhor Jesus tiver fincado uma vez os dois pés! Por dois sinais reconhecereis a alma que está nessa condição, pois traz necessariamente em si a marca daquelas pegadas divinas: são o temor e a esperança; aquele representa a imagem do juízo, esta a da misericórdia. Com razão o Senhor se compraz nos que o temem e nos que esperam na sua misericórdia (Sl 146,11), pois o temor é o princípio da sabedoria (Pr 1,7) e a esperança é o seu progresso; a consumação, essa a caridade reivindica para si. Sendo assim, não é pequeno o fruto deste primeiro beijo, que se recebe aos pés; cuida apenas de não ficar privado de nenhum dos dois. Pois, se já sentes compunção pela dor do pecado e pelo temor do juízo, imprimiste os lábios na pegada da verdade e do juízo. E, se temperas esse temor e essa dor olhando para a bondade divina e esperando alcançar o perdão, fica sabendo que abraças também o pé da misericórdia. De resto, não convém beijar um sem o outro: a lembrança apenas do juízo precipita no abismo do desespero, e a lisonja enganosa da misericórdia gera a pior das seguranças.`
    },
    {
      n: 9,
      texto: `Também a mim, infeliz, foi dado algumas vezes sentar-me junto aos pés do Senhor Jesus e abraçar ora um, ora outro, com toda a devoção, na medida em que a sua bondade se dignava admitir-me. Mas, se alguma vez, esquecido da misericórdia e picado pela consciência, eu me detinha um pouco mais no juízo, logo caía por terra, tomado de um medo incrível e de uma vergonha miserável, envolvido por um horror tenebroso, e das profundezas gritava, trêmulo, só isto: Quem conhece o poder da tua ira, e quem pode medir a tua cólera pelo temor que te é devido (Sl 89,11-12)? E, se, deixando esse, me acontecia segurar mais o pé da misericórdia, caía no extremo oposto e me desfazia em tal descuido e negligência que logo a oração ficava mais tíbia, a ação mais preguiçosa, o riso mais fácil, a conversa mais imprudente e, enfim, todo o meu estado, por dentro e por fora, mais inconstante. Por isso, instruído pela experiência, que é boa mestra, já não cantarei só o juízo nem só a misericórdia, mas cantarei para ti, Senhor, a misericórdia e o juízo juntos (Sl 100,1). Jamais esquecerei estes teus preceitos (Sl 118,93); os dois juntos serão o meu cântico no lugar da minha peregrinação (Sl 118,54), até que, exaltando-se a misericórdia acima do juízo (Tg 2,13), se cale a miséria e só cante para ti, daí por diante, a minha glória, e eu não seja mais atormentado (Sl 29,13).`
    }
  ]
});
