SERMOES.sermao({
  id: 'bernardo-cantico-18',
  colecao: 'bernardo-cantico',
  ordem: 18,
  numero: 'XVIII',
  titulo: 'Das duas operações do Espírito Santo: uma se chama derramamento; a outra, infusão',
  fonte: 'De duabus operationibus Spiritus sancti',
  argumento: `O sermão da taça e do canal. Bernardo distingue duas operações do Espírito: a infusão, que nos enche por dentro com as virtudes de que depende a nossa salvação; e o derramamento, que nos adorna por fora com dons destinados aos outros. E a regra é não inverter a ordem.

«O canal recebe e verte quase ao mesmo tempo; a taça espera até encher-se, e então reparte o que sobra, sem dano próprio.» Daí a queixa que ficou célebre: hoje há na Igreja muitos canais e pouquíssimas taças. O sermão termina enumerando as sete coisas que é preciso receber antes de ousar derramar.

Tradução feita do texto latino de Migne (PL 183, 859-863).`,
  pontos: [
    {
      n: 1,
      texto: `Óleo derramado é o teu nome (Ct 1,2). Que nos mostra com certeza o Espírito Santo dentro de nós, a propósito deste versículo? O que me ocorre por ora é a experiência de uma dupla operação sua: uma, pela qual primeiro nos firma por dentro com virtudes, para a salvação; outra, pela qual nos adorna também por fora com dons, para o ganho. Aquelas recebemos para nós; estes, para os nossos. Por exemplo: a fé, a esperança e a caridade são dadas a nós e por causa de nós, pois sem elas não podemos ser salvos. Já a palavra de ciência ou de sabedoria, a graça das curas, a profecia e outras semelhantes — de que podemos carecer sem dano para a própria salvação — são dadas, sem dúvida, para serem gastas na salvação do próximo. E a estas operações do Espírito Santo, que experimentamos em nós ou nos outros, chamemos, para que os nomes venham da coisa, infusão e derramamento. A qual das duas convém «óleo derramado é o teu nome»? Não ao derramamento? Pois, tratando-se de infusão, ela teria dito antes «óleo infundido» do que «óleo derramado». Foi, enfim, por causa do bom odor dos peitos banhados por fora que a esposa disse: Óleo derramado é o teu nome — atribuindo esse odor ao nome do esposo, como a um óleo derramado sobre os peitos. E todo aquele que se sente banhado pelo dom de uma graça exterior, com que possa por sua vez derramar sobre os outros, também esse pode dizer: Óleo derramado é o teu nome.`
    },
    {
      n: 2,
      texto: `Mas é preciso cuidado nestas coisas, para não dar o que recebemos para nós, nem reter o que recebemos para distribuir. Retens para ti o que é do próximo se, por exemplo, estando cheio de virtudes e ornado por fora com dons de ciência e de eloquência, prendes por medo, por preguiça ou por uma humildade pouco discreta, num silêncio inútil — e até condenável —, a palavra boa que poderia aproveitar a muitos: és decerto maldito, porque escondes o trigo em meio ao povo (Pr 11,26). E, ao contrário, espalhas e perdes o que é teu se, antes de estares todo cheio, te apressas a derramar quando estás pela metade — arando contra a lei com o primogênito do boi e tosquiando o primogênito da ovelha (Dt 15,19). Pois te privas da vida e da salvação que dás a outro, quando, vazio de intenção sadia, te inchas com o vento da glória vã, ou te infetas com o veneno da cobiça terrena, e morres inchado por um abscesso mortal.`
    },
    {
      n: 3,
      texto: `Por isso, se és sábio, hás de mostrar-te taça, e não canal. Pois o canal recebe e verte quase ao mesmo tempo; a taça, porém, espera até encher-se, e então reparte o que sobra, sem dano próprio, sabendo que é maldito quem torna pior a sua parte. E, para não teres o meu conselho por desprezível, ouve alguém mais sábio que eu: O tolo, diz Salomão, põe fora de uma vez todo o seu espírito; o sábio guarda alguma coisa para depois (Pr 29,11). Mas hoje temos na Igreja muitos canais e pouquíssimas taças. É tão grande a caridade daqueles por quem correm até nós as águas do céu, que querem derramar antes de receber; estão mais prontos a falar que a ouvir; apressam-se a ensinar o que não aprenderam; e desejam governar os outros, sem saberem governar-se a si mesmos. Eu não ponho nenhum grau de piedade, para a salvação, acima daquele que o Sábio estabeleceu ao dizer: Tem compaixão da tua alma, agradando a Deus (Eclo 30,24). E, se não tenho senão um pouco de óleo para me ungir, julgas que devo dá-lo a ti e ficar vazio? Guardo-o para mim, e de modo nenhum o tiro fora, a não ser por ordem do profeta. Se insistirem em pedir alguns daqueles que talvez pensem de mim mais do que veem em mim ou ouvem de mim, a resposta será esta: Para que não falte a nós e a vós, ide antes aos que vendem e comprai para vós (Mt 25,9). Mas a caridade, dizes tu, não busca o que é seu (1Cor 13,5). E sabes por quê? Não busca o que é seu justamente porque não lhe falta. Quem é que busca o que já tem? A caridade nunca deixa de ter o que é seu, isto é, o necessário à própria salvação; e não só tem: abunda. Quer abundar para si, para poder bastar a todos; guarda para si o quanto lhe basta, para não faltar a ninguém. De outro modo, se não está cheia, não é perfeita.`
    },
    {
      n: 4,
      texto: `Mas tu, irmão, cuja própria salvação ainda não está firme, cuja caridade ou ainda é nenhuma, ou é tão tenra e frágil como um caniço que cede a todo sopro, dá crédito a todo espírito e se deixa levar por todo vento de doutrina; ou antes: tu, cuja caridade é tão grande que, além do mandamento, amas o próximo mais do que a ti mesmo, e ao mesmo tempo tão pequena que, contra o mandamento, se derrete com um elogio, desfalece de medo, se perturba com a tristeza, se encolhe de avareza, se estica de ambição, se inquieta com suspeitas, se agita com insultos, se esvazia com preocupações, se incha com honrarias e definha de inveja — tu, digo, que te sentes assim no que é teu, com que loucura, pergunto, buscas ou aceitas cuidar do que é dos outros? Ouve o que aconselha uma caridade cautelosa e vigilante: Não para que os outros tenham alívio e vós aflição, mas para que haja igualdade (2Cor 8,13). Não queiras ser justo demais (Ecl 7,17). Basta que ames o próximo como a ti mesmo: isso é que é igualdade. Diz Davi: Encha-se a minha alma como de gordura e de substância, e a minha boca te louvará com lábios exultantes (Sl 62,6) — querendo, sem dúvida, primeiro receber e só depois derramar; e não só receber primeiro, mas encher-se, para transbordar de plenitude e não bocejar de vazio. Com cautela, para que o que é alívio para os outros não fosse aflição para ele; e também com pureza, imitando aquele de cuja plenitude todos recebemos. Aprende também tu a não derramar senão do que está cheio, e não queiras ser mais generoso do que Deus. Imite a taça a fonte. A fonte não corre em regato nem se estende em lago antes de se saciar das próprias águas. Não se envergonhe a taça de não ser mais pródiga que a sua fonte. A própria fonte da vida, cheia em si mesma e cheia de si mesma, não começou por brotar e saltar nos recessos próximos dos céus, enchendo tudo de bondade? E só então, cheias as partes mais altas e mais secretas, irrompeu para as terras e, do que sobrava, salvou os homens e os animais, como multiplicou a sua misericórdia. Primeiro encheu o interior; e então, transbordando nas suas muitas compaixões, visitou a terra, embebeu-a e a enriqueceu com abundância (Sl 64,10). Faze, pois, também tu do mesmo modo: enche-te primeiro, e então cuida de derramar. Uma caridade bondosa e prudente costuma transbordar, não escorrer-se. Filho meu, não te escorras, diz Salomão (Pr 3,21); e o Apóstolo: Por isso devemos estar atentos ao que ouvimos, para que não nos escorramos (Hb 2,1). Pois então? Serás mais santo que Paulo, mais sábio que Salomão? Aliás, nem me agrada enriquecer à custa do teu esvaziamento. Pois, se és mau para ti, para quem serás bom? (Eclo 14,5) Ajuda-me do que te sobra, se puderes; se não, poupa-te.`
    },
    {
      n: 5,
      texto: `Mas ouvi agora que coisas e quantas são necessárias à própria salvação, e quantas é preciso receber antes de ousarmos derramar — as que eu puder reunir brevemente por agora, pois a hora já vai muito adiantada e aperta para o fim do sermão. Chega o médico ao ferido, o espírito à alma. Pois qual alma não achará ele ferida pela espada do diabo, mesmo depois de curada, pelo remédio do batismo, a ferida da culpa antiga? Quando o espírito chega àquela alma que diz: Apodreceram e se corromperam as minhas cicatrizes, por causa da minha insensatez (Sl 37,6), de que se precisa primeiro? De cortar antes de tudo o inchaço ou a carne morta que porventura cresceu sobre a ferida e pode impedir a cura. Corte-se, pois, com o ferro de uma compunção aguda, a úlcera de um hábito inveterado. Mas a dor é áspera: alivie-se com o perfume da devoção, que não é outra coisa senão a alegria concebida da esperança do perdão. E essa alegria nasce da capacidade de se conter e da vitória sobre o pecado. Já dá graças e diz: Rompeste as minhas cadeias; a ti oferecerei um sacrifício de louvor (Sl 115,16-17). Depois aplica-se o remédio da penitência: o emplastro dos jejuns, das vigílias, das orações e de quaisquer outros exercícios de penitentes. No meio do esforço há que alimentá-lo com a comida da boa obra, para que não desfaleça. Que a obra seja comida, aprende-o daqui: O meu alimento é fazer a vontade de meu Pai (Jo 4,34). Acompanhem, pois, os trabalhos da penitência as obras de piedade, que o confortem. Grande confiança diante do Altíssimo dá a esmola, diz a Escritura (Tb 4,12). A comida dá sede: é preciso beber. Junte-se à comida da boa obra a bebida da oração, que assenta no estômago da consciência o que se fez de bom e o entrega a Deus. Orando se bebe o vinho que alegra o coração do homem (Sl 103,15), o vinho do espírito, que embriaga e faz esquecer os prazeres da carne. Umedece o interior de uma consciência ressequida, digere os alimentos das boas ações e os distribui pelos membros da alma, robustecendo a fé, confortando a esperança, fazendo crescer e ordenando a caridade, e nutrindo os costumes.`
    },
    {
      n: 6,
      texto: `Tomada a comida e a bebida, que resta senão que o doente descanse e se entregue ao repouso da contemplação, depois dos suores da ação? Dormindo na contemplação, sonha com Deus; pois por ora o vê num espelho e em enigma, não face a face (1Cor 13,12). E, contudo, aquele que assim é menos visto do que adivinhado, e isso de relance, como ao brilho de uma faísca que passa, e apenas roçado de leve — por ele a alma se inflama de amor e diz: A minha alma te desejou de noite, e também o meu espírito nas minhas entranhas (Is 26,9). Tal amor é zeloso; este convém ao amigo do esposo; é com este que deve arder o servo fiel e prudente que o Senhor constituiu sobre a sua família. Este enche, este ferve, este transborda; este já derrama sem receio, extravasando e irrompendo, e dizendo: Quem desfalece, que eu não desfaleça? Quem se escandaliza, que eu não queime? (2Cor 11,29) Pregue, dê fruto, renove os sinais e multiplique as maravilhas: não há por onde a vaidade se meta, onde a caridade ocupa tudo. Pois a caridade é a plenitude da lei e do coração (Rm 13,10) — contanto que seja plena. Enfim, Deus é caridade (1Jo 4,16); e não há nada entre as coisas que possa encher uma criatura feita à imagem de Deus, senão a caridade que é Deus, o único maior do que ela. Quem ainda não a alcançou é promovido com o maior perigo, por mais que pareça sobressair em outras virtudes. Ainda que tenha toda a ciência, ainda que dê todos os seus bens aos pobres, ainda que entregue o corpo para ser queimado — sem caridade está vazio (1Cor 13,2-3). Vede quantas coisas é preciso receber antes, para que ousemos derramar, dando da plenitude e não da penúria: primeiro, a compunção; depois, a devoção; em terceiro, o trabalho da penitência; em quarto, a obra de piedade; em quinto, a aplicação à oração; em sexto, o ócio da contemplação; em sétimo, a plenitude do amor. Tudo isto opera um só e mesmo Espírito, segundo a operação a que chamamos infusão; para que aquela outra, a que chamamos derramamento, se exerça com pureza e, por isso mesmo, com segurança, para louvor e glória de Nosso Senhor Jesus Cristo, que com o Pai e o Espírito Santo vive e reina, Deus, pelos séculos dos séculos. Amém.`
    }
  ]
});
