SERMOES.sermao({
  id: 'bernardo-cantico-13',
  colecao: 'bernardo-cantico',
  ordem: 13,
  numero: 'XIII',
  titulo: 'De como se deve atribuir sempre a Deus a glória e o louvor por todos os bens que nos concede',
  fonte: 'De gloria et laude Deo semper attribuenda',
  argumento: `O sermão nasce de uma digressão. Bernardo chegou ao «óleo derramado é o teu nome» e, antes de o explicar, detém-se no vício que esse versículo desmente: a ingratidão.

Começa pela imagem do mar e dos rios, que voltam a ele por caminhos subterrâneos para correrem de novo. Depois vem o fariseu, que honra a Deus com os lábios e a si mesmo no juízo do coração; depois José, que não tocou na mulher do seu senhor porque a mulher é a glória do homem; e por fim a partilha que o anjo fez em Belém — glória a Deus, paz aos homens. Bernardo aceita o acordo sem regatear.

Tradução feita do texto latino de Migne (PL 183, 834-839).`,
  pontos: [
    {
      n: 1,
      texto: `A origem de todas as fontes e de todos os rios é o mar; a das virtudes e das ciências é o Senhor Jesus Cristo. Pois quem é o Senhor das virtudes senão aquele que é o rei da glória? (Sl 23,10) E, segundo o cântico de Ana, esse mesmo é o Deus das ciências, o Senhor (1Sm 2,3). A continência da carne, a diligência do coração, a retidão da vontade — tudo isso mana daquela fonte. E não só isso: se alguém é arguto de engenho, se alguém brilha no falar, se alguém agrada pelos costumes, daí vem. Daí a palavra de ciência, daí a de sabedoria; pois ali estão escondidos todos os tesouros da sabedoria e da ciência (Cl 2,3). E os propósitos castos, os juízos justos, os desejos santos, não são regatos daquela fonte? Ora, se as massas de água voltam sem cessar para o mar por caminhos ocultos e subterrâneos, para de lá brotarem outra vez, num serviço contínuo e incansável, à nossa vista e ao nosso uso — por que não hão de os regatos espirituais voltar também, sem fraude e sem interrupção, à sua própria fonte, para não deixarem de regar os campos das mentes? Voltem os rios das graças ao lugar de onde saem, para correrem de novo. Torne a enviar-se ao seu princípio a torrente celeste, para que se derrame na terra com mais abundância. De que modo?, perguntas. Do modo que diz o Apóstolo: dando graças em tudo (1Ts 5,18). Tudo o que julgas ter de sabedoria, tudo o que julgas ter de virtude, atribui-o a Cristo, que é poder de Deus e sabedoria de Deus (1Cor 1,24).`
    },
    {
      n: 2,
      texto: `E quem é tão insensato, dizes tu, que dê a isso outra origem? Ninguém, decerto — tanto que até o fariseu dá graças (Lc 18,11), e nem por isso a sua justiça recebe louvor de Deus. Pois aquela ação de graças, se bem te lembras do Evangelho, não o torna mais grato. Por quê? Porque tudo quanto soe devoto na boca não basta para desculpar o inchaço do coração diante daquele que de longe conhece as coisas altas (Sl 137,6). De Deus, ó fariseu, ninguém zomba (Gl 6,7). Pensas ter alguma coisa que não tenhas recebido? Nada, dizes; e por isso dou graças a quem me deu. Se absolutamente nada, então também não houve em ti nenhum mérito prévio para receberes aquilo de que te glorias. E, se o confessas, em primeiro lugar é em vão que te inchas contra o publicano, que não tem o que tu tens justamente porque não recebeu como tu. Depois, cuida de não deixares de devolver a Deus por inteiro os dons dele e, desviando para ti alguma coisa da glória e da honra que lhe pertencem, não sejas com razão acusado de fraude — e de fraude contra Deus. Pois, se daquilo de que te gabas atribuísses a ti mesmo alguma coisa como vinda de ti, eu acreditaria que estavas antes enganado do que querendo fraudar, e corrigiria o erro. Mas, uma vez que, dando graças, provas que nada atribuis a ti e que reconheces com prudência que os teus méritos são dons de Deus, ao desprezares os outros denuncias que falaste com dois corações: num deles emprestando a língua à mentira, no outro usurpando a glória da verdade. Pois não julgarias o publicano desprezível em comparação contigo, se não te julgasses digno de honra em comparação com ele. Mas que respondes ao Apóstolo, que manda e diz: Só a Deus honra e glória? (1Tm 1,17) E que respondes ao anjo, que distingue e ensina o que Deus quer guardar para si e o que se digna repartir com os homens? Pois diz: Glória a Deus nas alturas, e paz na terra aos homens de boa vontade (Lc 2,14). Vedes como o fariseu, dando graças, honra a Deus com os lábios e a si mesmo no juízo do coração? Assim se pode notar que na boca de muitos a ação de graças soa mais por hábito do que por convicção ou por afeto — a ponto de os homens mais celerados costumarem dar graças a Deus pelos seus crimes e pelas suas infâmias, porque tudo lhes correu bem e próspero, ao gosto deles, no cumprimento das suas vontades perversas. Ouve, por exemplo, o ladrão que, ao trazer o mau fardo cobiçado de uma trama ímpia, exulta às escondidas e diz: Graças a Deus, não velei em vão, não perdi o trabalho da noite. Do mesmo modo, quem matou um homem, não se gloria e não dá graças por ter levado a melhor sobre o rival ou por se ter vingado do inimigo? E o adúltero, saltando de contente, rompe em louvores a Deus por ter enfim conseguido o que há muito desejava.`
    },
    {
      n: 3,
      texto: `Nem toda ação de graças, portanto, é aceita por Deus: só a que procede de uma simplicidade de coração pudica e pura. Digo pudica por causa dos que, gloriando-se até das suas más ações, costumam dar graças a Deus como se Deus se alegrasse com eles quando fazem o mal e exultasse com as piores coisas. Ouvirá quem é assim: Pensaste, iníquo, que eu seria semelhante a ti; hei de repreender-te e pôr-te tudo diante dos olhos (Sl 49,21). E acrescentei pura por causa dos hipócritas, que glorificam a Deus pelos seus bens, mas só de palavra, e guardam no coração aquilo que ofereceram com a boca; e, porque agem com dolo diante dele, a sua iniquidade é achada odiosa. Aqueles, de modo ímpio, atribuem a Deus os seus males; estes, com fraude, desviam para si os bens de Deus. O primeiro vício é tão estúpido, tão mundano e de certo modo tão bestial que nem preciso preveni-los contra ele; mas o segundo costuma armar ciladas sobretudo aos religiosos e aos homens espirituais. É grande e rara virtude, de fato, fazer coisas grandes e não te saberes grande; e que a tua santidade, manifesta a todos, só a ti fique escondida. Pareceres admirável e julgares-te desprezível: isto eu tenho por mais admirável do que as próprias virtudes. És verdadeiramente servo fiel se da muita glória do teu Senhor — que não sai de ti, mas passa por ti — nada te ficar nas mãos. Então, como diz o profeta, lanças fora a avareza que vem da extorsão e sacodes as tuas mãos de todo suborno (Is 33,15). Então, segundo o mandamento do Senhor, a tua luz brilha diante dos homens, para que glorifiquem não a ti, mas ao Pai que está nos céus (Mt 5,16). E, imitador de Paulo e dos pregadores fiéis, que não pregam a si mesmos (2Cor 4,5), também tu não buscas o que é teu, mas o que é de Jesus Cristo (Fl 2,21). Por isso também tu ouvirás: Muito bem, servo bom e fiel; porque foste fiel no pouco, sobre o muito te constituirei (Mt 25,21).`
    },
    {
      n: 4,
      texto: `José, sabendo que lhe estavam confiados a casa e todos os bens do seu senhor egípcio, não ignorou que a senhora ficava de fora; e por isso não consentiu em tocá-la. Não há, diz ele, entre todos os bens do meu senhor, nada que não esteja em meu poder ou que ele não me tenha entregado, exceto tu, que és a sua mulher (Gn 39,9). Sabia que a mulher é a glória do homem (1Cor 11,7), e julgou iníquo pagar tornando sem glória aquele que o tinha feito glorioso. Aquele homem, prudente pela sabedoria de Deus, percebeu que o marido zela pela mulher com firmeza, como pela própria glória, e que a guardou para si, sem confiá-la a outro; e não se atreveu a estender a mão ao que não lhe fora concedido. E então? O homem zela pela sua glória, e alguém se atreve a querer defraudar a Deus da sua, como se ele não zelasse por ela? Mas ouve o que ele diz: A minha glória não a darei a outro (Is 48,11). Que nos darás então, Senhor, que nos darás? A paz vos dou, diz ele, a paz vos deixo (Jo 14,27). Basta-me. Recebo com gratidão o que deixas, e deixo o que guardas. Assim me agrada; assim é o que me convém, não tenho dúvida. Renuncio de todo à glória, para que, se tomar o que não me foi concedido, não perca com razão também o que me foi oferecido. Quero a paz, desejo a paz, e nada mais. A quem não basta a paz, não bastas tu; pois tu és a nossa paz, que fizeste dos dois um só (Ef 2,14). Isto me é necessário, isto me basta: reconciliar-me contigo e reconciliar-me comigo. Pois, desde que me puseste como adversário teu, tornei-me pesado também a mim mesmo (Jó 7,20). Tenho cuidado de não ser ingrato ao benefício da paz que me deste, nem invasor sacrílego da tua glória. A ti, Senhor, a ti permaneça intacta a tua glória; comigo tudo vai bem, se eu tiver a paz.`
    },
    {
      n: 5,
      texto: `Abatido Golias, o povo alegrou-se com a paz recebida; mas foi Davi, só ele, que ficou glorioso. Josué, Jefté, Gedeão, Sansão, e até Judite, embora mulher, triunfaram gloriosamente dos inimigos nos seus dias; mas, enquanto os outros gozavam a paz com alegria, ninguém participou da glória deles. Judas Macabeu, também ele célebre por muitas vitórias, tendo dado tantas vezes a paz, com luta valente, a um povo que exultava — acaso repartiu alguma vez a glória com alguém? Diz o texto, enfim, que houve no povo não glória, mas grande alegria (1Mc 4,58). Que fez o Criador de todas as coisas menos do que todos esses, para que não deva também ele ser o único a gloriar-se? Sozinho criou tudo, sozinho triunfou do inimigo, sozinho libertou os cativos — e há de ter sócio na glória? O meu braço, diz ele, é que me ajudou; e ainda: Pisei sozinho o lagar, e dos povos ninguém estava comigo (Is 63,5.3). Que tenho eu, então, com a vitória, se nem estive na batalha? É o cúmulo da desfaçatez atribuir-me a glória sem a vitória, ou a vitória sem o combate. Recebei, ó montes, a paz para o povo (Sl 71,3); recebei a paz para vós, não a glória, guardando-a só para aquele que sozinho lutou e venceu. Assim, peço, assim seja: Glória a Deus nas alturas, e paz na terra aos homens de boa vontade. Mas não é de boa vontade, e sim de vontade claramente iníqua, aquele que, não se contentando com a paz, arqueja também pela glória de Deus, inquieto, de olho soberbo e coração insaciável (Sl 100,5) — e assim nem conserva a paz nem alcança a glória. Quem acreditaria na parede, se ela dissesse que gera o raio de luz que recebe pela janela? Ou, se as nuvens se gloriassem de ter gerado as chuvas, quem não riria? Para mim é claro que nem os regatos nascem dos canais, nem as palavras de prudência dos lábios ou dos dentes — ainda que o sentido corporal não alcance mais do que isso.`
    },
    {
      n: 6,
      texto: `Se nos santos vejo alguma coisa digna de louvor ou de admiração e a examino à luz clara da verdade, acabo por descobrir que um é o que aparece como digno de louvor, e outro é o que o é de fato; e louvo a Deus nos seus santos, seja Eliseu, seja o grande Elias, que ressuscitaram mortos. Eles nos mostram por fora coisas novas e insólitas, não por autoridade sua, mas por ministério; é Deus, que permanece neles, quem faz as obras. Invisível e inacessível em si mesmo, nos seus é visível e admirável — e só ele é admirável, ele que sozinho faz maravilhas (Sl 71,18). Não é louvor da pena a pintura ou a escrita que merece louvor, nem é glória da língua ou dos lábios a palavra boa. É hora de deixar falar também o profeta: Porventura o machado se gloriará contra aquele que corta com ele? Ou a serra se exaltará contra quem a maneja? Como se a vara se levantasse contra quem a levanta, ou o bastão se exaltasse, sendo apenas madeira (Is 10,15). Assim é contra o Senhor todo aquele que se gloria, se não se gloria no Senhor (2Cor 10,17). Se é preciso gloriar-se, Paulo me ensinou de quê e em quê: A nossa glória, diz ele, é esta: o testemunho da nossa consciência (2Cor 1,12). Glorio-me sem receio, se a consciência testemunha que nada tomo para mim da glória do Criador; sem receio, porque já não é contra o Senhor, mas no Senhor. Esta glória não só não nos é proibida, mas até nos é aconselhada, quando se diz: Buscais a glória uns dos outros, e não quereis a glória que vem só de Deus (Jo 5,44). Na verdade, gloriar-se só em Deus não vem senão só de Deus. E não é glória pequena: tão verdadeira quanto vinda da verdade, e na verdade tão rara que apenas uns poucos perfeitos se gloriam nela perfeitamente. Vão-se, pois, os vãos filhos dos homens, os mentirosos filhos dos homens; vão-se e enganem uns aos outros, todos juntos na sua vaidade (Sl 61,10). Pois quem se gloria com sabedoria examinará a própria obra e a submeterá com cuidado à luz da verdade; e assim terá a glória em si mesmo, e não na boca de outro (Gl 6,4). Sou tolo se confiar a minha glória ao cofrezinho dos teus lábios e começar a mendigá-la de ti sempre que quiser tê-la. Pois não fica ao teu arbítrio aprovar-me ou reprovar-me, conforme quiseres? Mas eu a guardo comigo: eu mesmo a guardo com mais fidelidade. Ou antes: nem a mim a confio; deposito-a naquele que é poderoso para guardar o meu depósito até aquele dia (2Tm 1,12), cuidadoso em guardar e fiel em restituir. Então cada um terá de Deus um louvor seguro — mas só aqueles que tiverem desprezado os louvores humanos. Pois a glória dos que gostam das coisas da terra está na sua vergonha, como também diz Davi: Os que agradam aos homens ficaram envergonhados, porque Deus os desprezou (Sl 52,6).`
    },
    {
      n: 7,
      texto: `Irmãos, se sabeis isto, nenhum de vós queira ser louvado nesta vida; porque todo favor que aqui captas e não devolves a Deus é um roubo que lhe fazes. Pois de onde te vem a glória, pó fétido, de onde? Da santidade da vida? Mas é o Espírito que santifica — o Espírito, digo, não o teu, mas o de Deus. Ainda que brilhes por prodígios e sinais, fazem-se pela tua mão, mas pelo poder de Deus. Ou lisonjeia-te o favor do povo, por teres dito uma palavra boa, e talvez bem dita? Mas foi Cristo quem deu a boca e a sabedoria (Lc 21,15). Pois que é a tua língua senão a pena do escriba? (Sl 44,2) E até isso recebeste emprestado. É um talento confiado, que será pedido de volta com juros. Se fores achado incansável no trabalho e fiel em entregar o fruto, receberás o salário do teu trabalho. Se não, o talento te será tirado, e ainda assim se exigirá o lucro, e serás chamado servo mau e preguiçoso. Todo louvor, pois, pelos bens da graça multiforme que aparece em vós, seja remetido a ele, autor e doador de tudo quanto é digno de louvor; e isso sem fingimento, como fazem os hipócritas; nem só por hábito, como fazem os mundanos; nem tampouco por necessidade, como os animais são postos a carregar fardos; mas como convém aos santos: com sinceridade fiel, com devoção atenta, com uma alegria agradável, mas não dissoluta. Assim, ao imolarmos a vítima do louvor e ao cumprirmos os nossos votos dia após dia, cuidemos com toda a vigilância de unir a compreensão ao uso, o afeto à compreensão, a exultação ao afeto, a seriedade à exultação, a humildade à seriedade, a liberdade à humildade; para que de vez em quando avancemos com os passos livres de uma mente purificada e sejamos arrebatados, por afetos fora do comum, às alegrias espirituais, aos encantos do júbilo, à luz de Deus, à suavidade, ao Espírito Santo; e assim provemos estar contados entre aqueles que o profeta via quando dizia: Senhor, andarão na luz do teu rosto, e no teu nome exultarão todo o dia, e serão exaltados na tua justiça (Sl 88,16-17).`
    },
    {
      n: 8,
      texto: `Mas talvez alguém me diga: Bem adverte; mas se dissesses coisas que viessem ao caso. Esperai um pouco: não me esqueci. Não temos entre mãos tratar daquilo que se diz: Óleo derramado é o teu nome? (Ct 1,2) Aí é que está a obra, aí é que está o trabalho. E se o que dissemos antes era necessário, julgai-o vós. De minha parte, notai em poucas palavras que não é coisa estranha ao assunto. Não vos lembrais de que, a respeito dos peitos da esposa, o último louvor foi o do bom cheiro dos perfumes? Que há de mais lógico, portanto, do que a esposa reconhecer que essa mesma fragrância é benefício do esposo, para que não se pense que a toma para si? E vedes bem que tudo o que dissemos antes serve a este sentido. Se os meus peitos, diz ela, cheiram assim e assim agradam, não o atribuo aos meus esforços nem aos meus méritos, mas à tua generosidade, ó esposo: é pelo óleo derramado, que é o teu nome. Isto quanto ao encadeamento do texto.`
    },
    {
      n: 9,
      texto: `Quanto à explicação do versículo em si — a propósito do qual alongamos tanto este sermão sobre o péssimo vício da ingratidão —, pede outro tempo e outro começo de sermão. Por agora baste ficardes advertidos disto: se a esposa não ousa de modo algum tomar para si coisa alguma de toda a sua virtude e da sua graça, quanto menos as jovenzinhas — que talvez sejamos nós? Digamos também nós, seguindo as pegadas da esposa, digamos: Não a nós, Senhor, não a nós, mas ao teu nome dá glória (Sl 113,1). Digamo-lo não só de palavra e de língua, mas de obra e de verdade; não aconteça — e muito o receio — que se diga também de nós: Amaram-no com a boca e com a língua lhe mentiram; o seu coração não era reto com ele, nem foram tidos por fiéis na sua aliança (Sl 77,36-37). Digamos, pois, digamos, clamando mais com o fundo do coração do que com os lábios da boca: Salva-nos, Senhor nosso Deus, e reúne-nos de entre as nações, para que louvemos o teu santo nome, não o nosso; e nos gloriemos no louvor — não no nosso, mas no teu (Sl 105,47) —, pelos séculos dos séculos. Amém.`
    }
  ]
});
