SERMOES.sermao({
  id: 'bernardo-cantico-02',
  colecao: 'bernardo-cantico',
  ordem: 2,
  numero: 'II',
  titulo: 'Da Encarnação de Cristo, anunciada pelos patriarcas e profetas e por eles ardentissimamente esperada',
  fonte: 'De Incarnatione Christi',
  argumento: `Prometido no fim do sermão anterior, começa aqui o comentário do primeiro versículo: Beije-me com o beijo da sua boca. Bernardo ouve nele a voz dos santos antigos, cansados de promessas e de demoras, que já não querem profetas mas o próprio Verbo. Daí a definição que dá ao centro do sermão: a boca que beija é o Verbo que assume, o beijado é a carne assumida, e o beijo é a pessoa composta de ambos — Cristo mediador.

Tradução feita do texto latino de Migne (PL 183, 789-794).`,
  pontos: [
    {
      n: 1,
      texto: `Pensando muitíssimas vezes no ardor do desejo dos Pais, que suspiravam pela presença de Cristo na carne, sinto compunção e confundo-me em mim mesmo; e agora a custo contenho as lágrimas, tanta é a vergonha da tibieza e do torpor destes miseráveis tempos nossos. Pois a qual de nós traz tanto gozo a exibição desta graça, quanto de desejo acendera nos santos antigos a promessa? Eis, com efeito, quantos hão de alegrar-se nesta Natividade que está prestes a celebrar-se! Mas oxalá pela natividade, e não pela vaidade! O desejo ardente daqueles, pois, e o afeto da piedosa expectação é o que me respira esta voz: Beije-me com o beijo da sua boca (Ct 1,1). Sentira, sem dúvida, em espírito, todo aquele que então podia ser espiritual, quanta graça seria derramada naqueles lábios. Por isso, falando no desejo da alma, dizia: Beije-me com o beijo da sua boca — desejando, sem dúvida, de todo o modo, não ser defraudado da participação de tão grande suavidade.`
    },
    {
      n: 2,
      texto: `Pois dizia cada um dos perfeitos: Que me importam estas bocas semeadoras de palavras dos profetas? Antes ele mesmo, o mais formoso entre os filhos dos homens, ele mesmo me beije com o beijo da sua boca. Já não ouço Moisés: com efeito, tornou-se para mim de língua embaraçada (Ex 4,10). Os lábios de Isaías são imundos (Is 6,5); Jeremias não sabe falar, porque é menino (Jr 1,6); e todos os profetas são sem língua. Ele mesmo, ele mesmo de quem falam, ele mesmo fale; ele mesmo me beije com o beijo da sua boca. Já não me fale neles, nem por eles, porque escuras são as águas nas nuvens do ar (Sl 17,12); mas ele mesmo me beije com o beijo da sua boca, cuja graciosa presença e cujos caudais de admirável doutrina se façam em mim fonte de água que salta para a vida eterna (Jo 4,14). Àquele que o Pai ungiu com óleo de alegria mais que aos seus companheiros (Sl 44,8) — porventura não me será dele infundida graça mais abundante? Se ao menos se dignar beijar-me com o beijo da sua boca. Cuja palavra, viva e eficaz (Hb 4,12), é para mim beijo: não, certamente, a conjunção dos lábios, que às vezes mente a paz dos ânimos, mas simplesmente a infusão dos gozos, a revelação dos segredos, uma admirável e de certo modo indistinta mistura da luz soberana com a mente iluminada. Pois quem adere a Deus é com ele um só espírito (1Cor 6,17). Com razão, portanto, não recebo visões nem sonhos, não quero figuras nem enigmas; enfado-me até das próprias espécies angélicas. Pois também a estas de longe sobrepuja o meu Jesus na sua formosura e na sua beleza. Não peço, pois, que me beije outro — nem anjo nem homem —, mas ele mesmo, com o beijo da sua boca. Nem, na verdade, presumo ser beijado pela sua própria boca (pois isso pertence à única felicidade e à singular prerrogativa do homem assumido); mas, mais humildemente, peço ser beijado pelo beijo da sua boca, que é comum a muitos, os quais podem dizer: E todos nós recebemos da sua plenitude (Jo 1,16).`
    },
    {
      n: 3,
      texto: `Atendei. Seja a boca que beija o Verbo que assume; o beijado, a carne que é assumida; e o beijo, que se faz igualmente daquele que beija e daquele que é beijado, seja a própria pessoa composta de ambos, o mediador de Deus e dos homens, o homem Cristo Jesus (1Tm 2,5). Por esta razão, pois, nenhum dos santos ousava dizer: Beije-me com a sua boca, mas somente: com o beijo da sua boca — reservando com efeito esta prerrogativa àquele a quem, de modo único e uma só vez, foi então impressa a boca do Verbo, quando a ele se entregou corporalmente toda a plenitude da divindade (Cl 2,9). Feliz beijo, e admirável por estupenda condescendência, no qual não se imprime boca em boca, mas Deus se une ao homem. E ali, sem dúvida, o contato dos lábios significa o abraço dos ânimos; aqui, porém, a confederação das naturezas compõe o humano com o divino, pacificando o que está na terra e o que está nos céus (Cl 1,20). Pois ele é a nossa paz, que de ambos fez um só (Ef 2,14). Por este beijo, portanto, suspirava todo santo do tempo antigo, porque pressentiam que nele se entesouravam a alegria e a exultação, e que nele estavam escondidos todos os tesouros da sabedoria e da ciência (Cl 2,3), e desejavam também eles receber da sua plenitude.`
    },
    {
      n: 4,
      texto: `Sinto que vos agrada o que se diz; mas recebei também outro sentido. Não estava oculto aos santos, ainda antes da vinda do Salvador, que Deus pensava pensamentos de paz sobre o gênero mortal (Jr 29,11). Pois não faria palavra alguma sobre a terra sem a revelar aos seus servos, os profetas (Am 3,7). Estava, contudo, esta palavra escondida para muitos (Lc 18,34). Havia, na verdade, naquele tempo, rara fé sobre a terra, e muito tênue esperança mesmo em muitos daqueles que aguardavam a redenção de Israel. Os que, porém, o sabiam de antemão, esses também prediziam que Cristo havia de vir em carne, e com ele a paz. Donde diz um deles: E haverá paz na nossa terra, quando ele vier (Mq 5,5). Antes, pregavam que por ele haviam os homens de recuperar a graça de Deus com toda a confiança, assim como divinamente o tinham recebido. O que também João, o precursor do Senhor, reconheceu cumprido em seu tempo, e testemunhou, dizendo: A graça e a verdade vieram por Jesus Cristo (Jo 1,17); e assim todo o povo cristão experimenta agora ser verdade.`
    },
    {
      n: 5,
      texto: `De resto, anunciando eles a paz, mas demorando-se o autor da paz, vacilava a fé do povo, enquanto não havia quem redimisse nem quem salvasse. E assim queixavam-se os homens das demoras, porque aquele príncipe da paz, tantas vezes anunciado, ainda não vinha, conforme falara pela boca dos seus santos profetas, que existem desde o princípio (Lc 1,70); e, tendo por suspeitas as promessas, reclamavam o sinal da prometida reconciliação, que é o beijo — como se qualquer um do povo respondesse aos mensageiros da paz: Até quando trazeis suspensa a nossa alma (cf. Jo 10,24)? Já de há muito anunciais a paz, e ela não vem; prometeis bens, e ainda há perturbação. Eis que isto mesmo, de muitos modos e de muitas maneiras, os anjos anunciaram aos pais, e os nossos pais a nós, dizendo: Paz, paz; e não há paz (Jr 6,14). Se Deus quer persuadir-me de que responde por tão frequente embaixada quanto ao beneplácito da sua vontade, e todavia não se mostra, beije-me com o beijo da sua boca, e assim, no sinal da paz, torne-me seguro da paz. Pois como hei de crer já em palavras? É preciso, antes, que as palavras sejam firmadas pela obra. Prove Deus que são verídicos os seus mensageiros (se é que são seus mensageiros), e siga-os ele mesmo, como tantas vezes prometeram, pois sem ele nada podem fazer. Enviou o servo, levou o báculo, e ainda não há voz nem vida (2Rs 4,29-31). Não me levanto, não sou ressuscitado, não sou sacudido do pó, não respiro em esperança, se o próprio profeta não descer e não me beijar com o beijo da sua boca.`
    },
    {
      n: 6,
      texto: `Acresce a isto que aquele que se declara nosso mediador junto de Deus é o Filho de Deus, e é Deus (1Tm 2,5). E que é o homem, para que a ele se dê a conhecer, ou o filho do homem, para que dele faça conta (Sl 143,3)? Que confiança tenho eu, para ousar entregar-me a tão grande majestade? Donde, digo eu, terra e cinza (Gn 18,27), presumo que Deus tenha cuidado de mim? Além disso, ele ama o seu Pai; de mim, porém, não tem necessidade, não carece dos meus bens (Sl 15,2). Donde, pois, me constará que o meu mediador não está inteiramente do lado de uma só das partes? Contudo, se verdadeiramente, como dizeis, Deus decretou compadecer-se, e pensa em tornar-se ainda mais aprazível, estabeleça um testamento de paz e firme comigo aliança perpétua no beijo da sua boca. Para não tornar vãs as coisas que saem dos seus lábios (Sl 88,35), aniquile-se, humilhe-se, incline-se, e beije-me com o beijo da sua boca. Para que o mediador, convindo por igual às duas partes, a nenhuma delas seja suspeito, faça-se homem o Deus Filho de Deus, faça-se filho do homem, e torne-me certo neste beijo da sua boca. Seguro recebo por mediador o Filho de Deus, a quem reconheço também como meu. De modo algum me será já suspeito: pois é meu irmão e minha carne (Gn 37,27). Penso, com efeito, que já não poderá desprezar-me osso dos meus ossos e carne da minha carne (Gn 2,23).`
    },
    {
      n: 7,
      texto: `Assim, pois, a antiga queixa exigia o sacrossanto beijo, isto é, o mistério do Verbo que havia de encarnar-se, enquanto a fé, fatigada pela longa e molesta expectação, desfalecia, e o povo infiel, vencido pelo tédio, murmurava contra as promessas de Deus. Invenção minha será isto, se não reconhecerdes vós também o mesmo pelas Escrituras. Daí, sem dúvida, aquelas vozes queixosas e cheias de murmuração: Manda, torna a mandar; espera, torna a esperar; um pouco aqui, um pouco ali (Is 28,10). Daí aquelas preces ansiosas e cheias de piedade: Dá a recompensa, Senhor, aos que esperam em ti, para que os teus profetas sejam achados fiéis. E ainda: Suscita, Senhor, as orações que em teu nome proferiram os antigos profetas (Eclo 36,18.17). Daí aquelas promessas brandas e cheias de consolação: Eis que o Senhor aparecerá, e não mentirá; se se demorar, espera-o, porque, vindo, virá, e não tardará (Hab 2,3). E ainda: Perto está de vir o seu tempo, e os seus dias não se prolongarão (Is 14,1). E, na pessoa do prometido: Eis que eu, diz, me inclino para vós como um rio de paz, e como torrente que transborda, a glória das gentes (Is 66,12). Em tais palavras bastante aparecem a instância dos pregadores e a desconfiança dos povos. Assim, pois, o povo murmurava e a fé vacilava; e, segundo o vaticínio de Isaías: Os anjos da paz choravam amargamente (Is 33,7). Portanto, para que todo o gênero humano não perecesse de desesperação, demorando-se Cristo — enquanto a fraca mortalidade suspeitava ser desprezada e desconfiava da graça da sua reconciliação com Deus, tantas vezes prometida —, os santos, que estavam certos quanto ao espírito, ansiavam pela certeza da presença na carne, e com toda a instância requeriam o sinal da paz a restaurar-se, por causa dos pusilânimes e dos incrédulos.`
    },
    {
      n: 8,
      texto: `Ó raiz de Jessé, que estás posto como sinal para os povos! (Is 11,10). Quantos reis e profetas quiseram ver-te, e não viram! (Lc 10,24). Feliz, contudo, entre todos, Simeão, cuja velhice foi rica de misericórdia! Pois exultou por ver o sinal do desejo; e viu, e alegrou-se; e, recebido o beijo da paz, é despedido em paz, tendo antes anunciado abertamente que Jesus nascera como sinal que havia de ser contradito (Lc 2,25-35). E assim foi inteiramente. Foi contradito o sinal da paz, logo que surgiu, mas por aqueles que odeiam a paz: pois é paz para os homens de boa vontade (Lc 2,14), e para os malévolos pedra de escândalo e rocha de tropeço. Herodes, enfim, turbou-se, e toda Jerusalém com ele (Mt 2,3); pois veio para o que era seu, e os seus não o receberam (Jo 1,11). Felizes aqueles pastores que passavam a noite em vigília e foram tidos por dignos da visão deste sinal. Já então se escondia aos sábios e prudentes, e se revelava aos pequeninos (Mt 11,25). E Herodes quis ver; mas, porque não com boa vontade, não mereceu — pois era sinal de paz, dado somente aos homens de boa vontade; a Herodes, porém, e aos seus semelhantes, não se dará senão o sinal do profeta Jonas. Ora, aos pastores diz o anjo: E isto vos servirá de sinal — a vós, humildes; a vós, obedientes; a vós, que não aspirais às coisas altas; a vós, que vigiais e meditais na lei de Deus dia e noite. Isto, diz, vos servirá de sinal. Que sinal? O que os anjos prometiam, o que os povos requeriam, o que os profetas haviam predito: isto fez agora o Senhor, e mostrou-vo-lo, para que nele recebam os incrédulos a fé, os pusilânimes a esperança, os perfeitos a segurança. Isto, pois, vos servirá de sinal. Sinal de quê? Da indulgência, da graça, da paz — e de uma paz que não terá fim. Este, portanto, é o sinal: Achareis um menino envolto em panos e posto numa manjedoura (Lc 2,12). E, todavia, é Deus que nele reconcilia consigo o mundo (2Cor 5,19). Morrerá pelos vossos pecados e ressuscitará pela vossa justificação, para que, justificados pela fé, tenhais paz para com Deus (Rm 4,25; 5,1). Este sinal de paz propunha outrora o profeta ao rei Acaz, para que o pedisse ao Senhor seu Deus, ou no alto, acima, ou no abismo, embaixo. Mas o rei ímpio recusou (Is 7,11-12), não crendo, o infeliz, que neste sinal as coisas ínfimas haviam de unir-se em paz às supremas: de sorte que também os do inferno, ao descer o Senhor para os salvar, recebessem eles próprios no ósculo santo o sinal da paz; e os espíritos superiores, do mesmo modo, quando ele tornasse aos céus, participassem dele em eterna suavidade.`
    },
    {
      n: 9,
      texto: `É preciso terminar o sermão; mas, para recolher em breve suma o que nele se discutiu: fica claro que este santo beijo foi necessariamente concedido ao mundo por duas causas — para dar fé aos fracos e para satisfazer o desejo dos perfeitos; e, além disso, que o próprio beijo não é outra coisa senão o mediador de Deus e dos homens, o homem Jesus Cristo, o qual, com o Pai e o Espírito Santo, Deus, vive e reina pelos séculos dos séculos. Amém.`
    }
  ]
});
