SERMOES.sermao({
  id: 'bernardo-cantico-11',
  colecao: 'bernardo-cantico',
  ordem: 11,
  numero: 'XI',
  titulo: 'Das duas coisas que pertencem à obra da redenção humana: o fruto e o modo',
  fonte: 'De duobus, hoc est fructu et modo, pertinentibus ad opus humanae redemptionis',
  argumento: `Bernardo insiste no perfume da devoção: que os monges desviem o pé, de vez em quando, da lembrança angustiada dos próprios caminhos e saiam para as veredas mais planas da memória dos benefícios de Deus. Se Caim tivesse tido esse freio, não teria desesperado.

Como é impossível recordar todos os benefícios, escolhe o maior — a redenção — e nela distingue duas coisas: o fruto, que é Deus ser tudo em todos, luz para a razão, paz para a vontade, eternidade para a memória; e o modo, que é o esvaziamento de Deus. No meio vem o lamento sobre «a minha mísera trindade», desterrada da Trindade bem-aventurada.

Tradução feita do texto latino de Migne (PL 183, 824-828).`,
  pontos: [
    {
      n: 1,
      texto: `Disse no fim do sermão — e não me pesa repeti-lo — que desejo que todos vós participeis daquela unção sagrada em que a santa devoção recorda os benefícios de Deus com alegria e ação de graças. Isso é bom, primeiro para aliviar os trabalhos da vida presente, que se tornam mais suportáveis quando exultamos no louvor de Deus; e depois porque nada representa na terra, com tanta propriedade, o estado da morada celeste como a alegria dos que louvam a Deus, dizendo a Escritura: Felizes os que habitam na tua casa, Senhor; pelos séculos dos séculos te louvarão (Sl 83,5). Creio que foi principalmente deste perfume que falou o Profeta: Como é bom e como é agradável habitarem os irmãos juntos! É como o perfume na cabeça (Sl 132,1-2). Pois não parece que isso possa convir ao primeiro. Esse, ainda que seja bom, não é agradável, porque a lembrança dos pecados produz amargura, não alegria. E nem os que o preparam habitam juntos, já que cada um chora e lamenta os próprios pecados. Mas os que se ocupam da ação de graças olham e pensam só em Deus, e por isso é que habitam verdadeiramente juntos. E é bom o que fazem, porque guardam com toda a justiça a glória para aquele a quem ela pertence; e é também agradável, porque deleita.`
    },
    {
      n: 2,
      texto: `Por isso aconselho a vós, meus amigos, que de vez em quando desvieis o pé da lembrança penosa e angustiada dos vossos caminhos e saiais para as veredas mais planas de uma memória mais serena: a dos benefícios de Deus; para que vós, que vos envergonhais ao olhar para dentro, respireis ao olhar para ele. Quero que experimenteis o que aconselha o santo Profeta: Deleita-te no Senhor, e ele te dará os pedidos do teu coração (Sl 36,4). A dor pelos pecados é necessária, sim, contanto que não seja contínua. Que se intercale com a lembrança mais alegre da bondade divina, para que o coração não endureça de tristeza e não se perca de vez pelo desespero. Misturemos mel ao absinto, para que a amargura saudável possa dar saúde quando, temperada com a doçura que se lhe junta, puder ser bebida. Ouve, enfim, como o próprio Deus tempera a amargura de um coração contrito, como chama de volta do abismo do desespero quem está sem ânimo, como consola o aflito e levanta o desconfiado com o mel de uma promessa suave e fiel. Diz ele pelo profeta: Eu refrearei a tua boca com o meu louvor, para que não pereças (Is 48,9). Isto é: para que, ao olhares para os teus crimes, não caias em tristeza excessiva e, desesperado, não te precipites como um cavalo sem freio e te percas, eu te segurarei com o freio do meu perdão e te levantarei com os meus louvores; e tu, que te envergonhas dos teus males, respirarás nos meus bens, ao veres que sou mais bondoso do que tu és culpado. Se Caim tivesse sido seguro por este freio, não teria dito, desesperado: A minha iniquidade é maior do que o perdão que eu possa merecer (Gn 4,13). De modo nenhum! Pois a bondade dele é maior do que qualquer iniquidade. Por isso o justo é acusador de si mesmo não sempre, mas apenas no começo da sua fala (Pr 18,17), e costuma fechar o fim da fala com os louvores de Deus. Vede, enfim, o justo a proceder nesta ordem: Pensei nos meus caminhos, diz ele, e voltei os meus pés para os teus testemunhos (Sl 118,59) — para que, tendo padecido nos próprios caminhos a ruína e a desventura, se deleitasse no caminho dos testemunhos de Deus como em todas as riquezas. Também vós, portanto, a exemplo do justo: se pensais de vós com humildade, pensai do Senhor segundo a bondade dele. Pois assim ledes no Sábio: Pensai do Senhor segundo a bondade, e buscai-o na simplicidade do coração (Sb 1,1). E disso a mente se convence com facilidade, se a lembrança da generosidade divina for frequente, ou antes, contínua. De outro modo, como se cumprirá aquilo do Apóstolo — dando graças em tudo (1Ts 5,18) —, se aquilo por que se devem as graças se afastou do coração? Não quero que caia sobre vós a censura feita aos judeus, de quem a Escritura testemunha que não se lembraram dos seus benefícios nem das maravilhas que lhes mostrou (Sl 77,11).`
    },
    {
      n: 3,
      texto: `Mas, como é impossível a todo homem recordar e reunir todos os bens que o Senhor misericordioso e compassivo não cessa de dar aos mortais — pois quem contará os poderes do Senhor, quem fará ouvir todos os seus louvores? (Sl 105,2) —, ao menos aquilo que é principal e maior, a saber, a obra da nossa redenção, nunca se afaste da memória dos que foram redimidos. Nesta obra cuidarei de vos apresentar sobretudo duas coisas, que agora me ocorrem. E hei de fazê-lo com o menor número de palavras que puder, lembrado daquela sentença: Dá ocasião ao sábio, e ele será mais sábio (Pr 9,9). As duas coisas são o modo e o fruto. E o modo é o esvaziamento de Deus; o fruto, o preenchimento que ele faz de nós. Meditar no fruto é o viveiro de uma santa esperança; meditar no modo é o incentivo de um amor supremo. Ambos são necessários ao nosso progresso, para que a esperança não seja interesseira, por não vir acompanhada do amor, nem o amor esfrie, por parecer sem fruto.`
    },
    {
      n: 4,
      texto: `Ora, o fruto que esperamos do nosso amor é aquele que prometeu o próprio a quem amamos: Uma medida cheia, apertada, sacudida e transbordante vos deitarão no regaço (Lc 6,38). Esta medida, ao que ouço, será sem medida. Mas gostaria de saber de que coisa será essa medida, ou antes, essa imensidão que se promete. Nenhum olho viu, ó Deus, fora de ti, o que preparaste para os que te amam (Is 64,4). Dize-nos tu, que preparas: que é que preparas? Cremos e confiamos, tal como prometes: Seremos saciados com os bens da tua casa (Sl 64,5). Mas com que bens, pergunto, e de que espécie? Porventura com trigo, vinho e azeite, com ouro e prata, ou com pedras preciosas? Mas isto já conhecemos e já vimos; e vemos, e já nos enfada. Buscamos aquilo que o olho não viu, nem o ouvido ouviu, nem subiu ao coração do homem (1Cor 2,9). Isso é que agrada, isso é que tem sabor, isso é que dá gosto procurar, seja lá o que for. Todos serão ensinados por Deus, diz ele (Jo 6,45); e ele será tudo em todos (1Cor 15,28). Ao que ouço, a plenitude que esperamos de Deus não será senão de Deus.`
    },
    {
      n: 5,
      texto: `Mas quem poderá abarcar quão grande abundância de doçura se encerra nestas poucas palavras: Deus será tudo em todos? Para não falar do corpo, vejo na alma três coisas — a razão, a vontade e a memória —, e estas três são a própria alma. Quanto falta a cada uma delas, neste mundo, da sua integridade e da sua perfeição, sente-o todo aquele que anda segundo o espírito. E por que isso, senão porque Deus ainda não é tudo em todos? Daí vem que a razão se engane tantas vezes nos seus juízos, que a vontade seja sacudida por quatro perturbações e que a memória se confunda com mil esquecimentos. A esta tríplice vaidade está sujeita, contra a vontade, a nobre criatura — mas na esperança (Rm 8,20). Pois aquele que sacia de bens o desejo da alma (Sl 102,5) há de ser, para a razão, plenitude de luz; para a vontade, abundância de paz; para a memória, continuidade de eternidade. Ó verdade, ó caridade, ó eternidade! Ó Trindade bem-aventurada e que faz bem-aventurados! A ti suspira miseravelmente a minha mísera trindade, porque de ti anda infelizmente desterrada. Ao afastar-se de ti, em quantos erros, dores e temores se enredou! Ai de mim! Que trindade trocamos pela tua! O meu coração está perturbado — e daí a dor; abandonou-me a minha força — e daí o pavor; e a luz dos meus olhos já não está comigo (Sl 37,11) — e daí o erro. Vê que trindade tão diferente mostraste, ó trindade da minha alma, no teu desterro.`
    },
    {
      n: 6,
      texto: `Mas então, por que estás triste, minha alma, e por que me perturbas? Espera em Deus, porque ainda hei de louvá-lo (Sl 41,6) — quando o erro se afastar da razão, a dor da vontade e todo temor da memória, e vier no lugar aquela serenidade admirável, aquela suavidade plena, aquela segurança eterna que esperamos. A primeira coisa fará Deus enquanto verdade; a segunda, Deus enquanto caridade; a terceira, Deus enquanto poder supremo — para que Deus seja tudo em todos: recebendo a razão uma luz inextinguível, alcançando a vontade uma paz imperturbável e aderindo a memória, para sempre, a uma fonte que não se esgota. Vede vós se é certo atribuir a primeira ao Filho, a segunda ao Espírito Santo e a última ao Pai; mas de modo que nada disso se tire ao Pai, nem ao Filho, nem ao Espírito Santo, para que a nenhuma das pessoas a distinção diminua a plenitude, ou a perfeição tire o que lhe é próprio. E reparai ao mesmo tempo no que de semelhante experimentam os filhos deste mundo com os atrativos da carne, com os espetáculos do mundo e com as pompas de Satanás — sendo que é com tudo isso que a vida presente ilude os míseros que a amam, como diz João: Tudo o que há no mundo é concupiscência da carne, concupiscência dos olhos e ambição do século (1Jo 2,16). Isto quanto ao fruto da redenção.`
    },
    {
      n: 7,
      texto: `Quanto ao modo, que definimos, se vos lembrais, como o esvaziamento de Deus, recomendo igualmente à vossa consideração três coisas principais. Pois aquele esvaziamento não foi simples nem pequeno: esvaziou-se a si mesmo até a carne, até a morte, até a cruz (Fl 2,7-8). Quem poderá avaliar dignamente que humildade, que mansidão, que bondade foi o Senhor da majestade revestir-se de carne, ser punido com a morte, ser aviltado na cruz? Mas alguém dirá: Não podia o Criador reparar a sua obra sem tanta dificuldade? Podia; mas preferiu fazê-lo à custa da própria afronta, para que o péssimo e odiosíssimo vício da ingratidão não achasse mais ocasião no homem. Tomou sobre si muito cansaço, para tornar o homem devedor de muito amor; e para que a dificuldade da redenção o lembrasse de dar graças, a ele que a facilidade da criação tinha tornado menos agradecido. Pois que dizia o homem, criado e ingrato? Fui criado de graça, é certo, mas sem nenhum peso ou trabalho para o meu autor: ele falou, e fui feito, como todas as outras coisas. Que grandeza há em dar coisas, por maiores que sejam, com a facilidade de uma palavra? Assim a impiedade humana, diminuindo o benefício da criação, tirava motivo de ingratidão justamente de onde devia tirar motivo de amor — e isso para buscar desculpas para os seus pecados (Sl 140,4). Mas fechou-se a boca dos que falavam iniquidade (Sl 62,12). Está mais claro que a luz quanto ele gastou agora por ti, ó homem: não se recusou a fazer-se servo, sendo Senhor; pobre, sendo rico; carne, sendo Verbo; filho do homem, sendo Filho de Deus. Lembra-te, pois, de que foste feito do nada, mas não foste redimido por nada. Em seis dias criou todas as coisas, e a ti entre elas; mas por trinta anos inteiros operou a tua salvação no meio da terra (Sl 73,12). Ó, quanto trabalhou, suportando! As necessidades da carne, as tentações do inimigo — não agravou tudo isso com a ignomínia da cruz e não o coroou com o horror da morte? E era necessário. Assim, assim salvaste os homens e os animais, Senhor; como multiplicaste a tua misericórdia, ó Deus! (Sl 35,7-8)`
    },
    {
      n: 8,
      texto: `Meditai nestas coisas, ocupai-vos delas. Reanimai com tais aromas as vossas entranhas, que por muito tempo o odor mais áspero dos pecados atormentou, para que abundeis também nestes perfumes, não menos suaves que saudáveis. Nem por isso julgueis já possuir aqueles ótimos que se louvam nos peitos da esposa; e começar a falar deles agora, a estreiteza de um sermão que já deve terminar não permite. O que se disse dos outros, guardai na memória e provai na vida; e sobre estes ajudai-me com as vossas orações, para que eu possa dizer algo digno de tão grandes delícias da esposa e que edifique as vossas almas para o amor do esposo, Nosso Senhor Jesus Cristo. Amém.`
    }
  ]
});
