SERMOES.sermao({
  id: 'bernardo-cantico-66',
  colecao: 'bernardo-cantico',
  ordem: 66,
  numero: 'LXVI',
  titulo: 'Dos erros dos hereges a respeito do matrimônio, do batismo das crianças, do purgatório, das orações pelos defuntos e da invocação dos santos',
  fonte: 'De erroribus haereticorum',
  argumento: `Último dos sermões sobre as raposas. Bernardo expõe e refuta as doutrinas dos hereges do seu tempo: ovelhas no hábito, raposas na astúcia, lobos nas obras. Proíbem o casamento e certos alimentos, como Paulo predisse dos "últimos tempos"; e, ao contrário das outras heresias, não sabem dizer quem foi o seu fundador. Condenar o matrimônio é abrir a porta a toda impureza; admiti-lo só entre virgens contradiz o Apóstolo, que permite à viúva casar-se de novo. Abster-se da carne e do leite pode ser penitência, mas julgar impuro o que Deus criou é blasfêmia maniqueia.

Dizem-se a única Igreja e sucessores dos apóstolos, mas escondem a luz debaixo do alqueire. Zombam do batismo das crianças — que são salvas na fé da mãe Igreja, como a filha da cananeia e o paralítico pela fé dos outros —, das orações pelos mortos, da intercessão dos santos e do purgatório; e negam os sacramentos dados por clérigos pecadores, como se Caifás não tivesse profetizado nem Judas sido escolhido. Bernardo relata que alguns, submetidos pelo povo ao juízo da água e condenados, preferiram morrer a converter-se, e o povo os matou: "aprovamos o zelo, mas não o fato, porque a fé se persuade, não se impõe" — embora julgue melhor a repressão pela autoridade legítima do que deixá-los arrastar outros. A firmeza deles não é a dos mártires, mas dureza de coração.

Tradução feita do texto latino de Migne (PL 183, 1093-1102).`,
  pontos: [
    {
      n: 1,
      texto: `Apanhai-nos as raposas pequenas, que destroem as vinhas (Ct 2,15). Eis-me diante destas raposas. São elas que passam pelo caminho e vindimam a vinha (cf. Sl 79,13). Não se contentam em abandonar o caminho, se não puderem também devastar a vinha, acrescentando a prevaricação. Não lhes basta ser hereges, se não forem também hipócritas, para que o pecado se torne pecador acima de toda medida (cf. Rm 7,13). São estes os que vêm em pele de ovelha (cf. Mt 7,15) para despir as ovelhas e despojar os carneiros. Não te parece cumprida uma e outra coisa, quando se veem os povos despojados da fé, e os sacerdotes despojados dos povos? Quem são estes salteadores? São ovelhas no hábito, raposas na astúcia, lobos nos atos e na crueldade. São os que querem parecer bons, e não sê-lo; não parecer maus, mas sê-lo. São maus e querem parecer bons, para não serem maus sozinhos; temem parecer maus, para não serem pouco maus. Pois a maldade sempre fez menos mal às claras, e o bom nunca foi enganado senão pela simulação do bem. Assim, pois, para mal dos bons, procuram parecer bons; não querem parecer maus, para terem mais liberdade de fazer o mal. Pois o que se faz entre eles não é cultivar as virtudes, mas colorir os vícios com uma espécie de verniz de virtudes. Enfim, dão à impiedade da superstição o nome de religião. Definem a inocência como não fazer mal às claras, reivindicando assim para si só a cor da inocência. Para encobrir a torpeza, adornaram-se com o voto de continência. E julgam que só nas esposas se deve contar a torpeza, quando é só a união com a esposa a causa que desculpa a torpeza no ato carnal. São homens rústicos e ignorantes, e de todo desprezíveis; mas não se deve, digo-vos, tratar com eles descuidadamente. Pois avançam muito na impiedade, e a sua palavra se alastra como um câncer (2Tm 2,16-17).`
    },
    {
      n: 2,
      texto: `Enfim, não os descuidou o Espírito Santo, que outrora profetizou tão claramente a respeito deles, dizendo o Apóstolo: O Espírito diz claramente que nos últimos tempos alguns se afastarão da fé, dando ouvidos a espíritos de erro e a doutrinas de demônios, de gente que fala mentiras com hipocrisia e tem a consciência cauterizada, que proíbe casar e manda abster-se dos alimentos que Deus criou para serem tomados com ação de graças (1Tm 4,1-3). Destes, sem dúvida, destes é que falava. Estes proíbem casar, estes se abstêm dos alimentos que Deus criou; disto veremos depois. Mas agora vede se esta burla não é propriamente dos demônios, e não dos homens, conforme o Espírito predissera. Pergunta-lhes quem foi o autor da sua seita: não te darão nenhum. Que heresia não teve, entre os homens, o seu próprio heresiarca? Os maniqueus tiveram Mani por chefe e mestre, os sabelianos Sabélio, os arianos Ário, os eunomianos Eunômio, os nestorianos Nestório. E assim se sabe que todas as outras pestes deste gênero tiveram cada uma o seu mestre, um homem, de quem tiraram a origem e o nome. Com que nome ou título designarás estes? Com nenhum; porque a sua heresia não vem de um homem, nem a receberam por meio de um homem. Longe de nós, porém, pensar que a receberam por revelação de Jesus Cristo; mas antes, e sem dúvida, como predisse o Espírito Santo, por sugestão e engano dos demônios, de gente que fala mentiras com hipocrisia e proíbe casar!`
    },
    {
      n: 3,
      texto: `Falam isto, sem dúvida, com hipocrisia e astúcia de raposa, fingindo dizer por amor da castidade aquilo que antes inventaram para alimentar e multiplicar a torpeza. A coisa, porém, é tão clara que me admira como se pôde alguma vez persuadir disto um cristão; a não ser que estes sejam tão bestiais que não percebam como solta as rédeas a toda imundície quem condena o matrimônio; ou então tão cheios de maldade e absorvidos pela malignidade diabólica que, percebendo-o, o dissimulam e se alegram com a perdição dos homens. Tira da Igreja o matrimônio honrado e o leito sem mancha (Hb 13,4): não a enches de concubinários, de incestuosos, de dissolutos, de efeminados, de homens que se deitam com homens, e enfim de toda espécie de impuros? Escolhe, pois, uma das duas: ou que se salvem todos estes monstros de homens, ou que o número dos que se hão de salvar fique reduzido ao pequeno número dos continentes. Quão avarento numa coisa! Quão pródigo na outra! Nenhuma das duas convém ao Salvador. Quê? Será coroada a torpeza? Nada convém menos ao autor da honestidade. Será condenado o mundo inteiro, exceto uns poucos continentes? Isto não é ser Salvador. Rara é na terra a continência, e não foi por um ganho tão pequeno que aquela plenitude se esvaziou a si mesma para vir à terra. E como é que da sua plenitude todos recebemos (cf. Jo 1,16), se só aos continentes concedeu participar dela? Não têm o que responder a isto. Nem, creio, àquilo: se há lugar no céu para a honestidade, e não há companhia entre o honesto e o torpe, como não há comunhão entre a luz e as trevas (cf. 2Cor 6,14), sem dúvida nenhum impuro tem lugar reservado no lugar da salvação. Se alguém pensa de outro modo, há de convencê-lo a voz do Apóstolo, que afirma sem nenhuma ambiguidade: Os que fazem tais coisas não possuirão o reino de Deus (Gl 5,21). Por onde sairá agora da toca esta raposinha traiçoeira? Julgo-a apanhada na sua toca, na qual fez para si como que dois buracos, um para entrar, outro para sair; pois é assim que costuma fazer. Vê, pois, como lhe foi fechada a saída de um lado e de outro. Se põe só os continentes no céu, perde-se a salvação na sua maior parte; se põe lá toda a imundície juntamente com os continentes, perde-se a honestidade. Mas é mais justo que pereça ela mesma, que não sairá nem por aqui nem por ali, fechada para sempre e apanhada na toca que fez.`
    },
    {
      n: 4,
      texto: `Alguns deles, porém, discordando dos outros, admitem que se pode contrair matrimônio, mas só entre virgens. Mas não vejo que razão possam dar desta distinção; a não ser que cada um, a seu bel-prazer, se esforça à porfia por dilacerar com dente de víbora os sacramentos da Igreja, como as entranhas de uma mãe. Pois o que se diz que alegam dos primeiros esposos, que eram virgens — em que prejudica isso, pergunto, a liberdade do matrimônio, para que não seja lícito contraí-lo também entre não virgens? Mas sussurram ter encontrado no Evangelho não sei que coisa, que em vão julgam favorecer a sua tolice. Creio que é aquilo: tendo o Senhor citado primeiro o testemunho do Gênesis: E Deus criou o homem à sua imagem e semelhança; criou-os homem e mulher, acrescentou depois: Portanto, o que Deus uniu, o homem não separe (Gn 1,27; Mt 19,4.6). A estes, dizem, Deus uniu, porque ambos eram virgens, e já não era lícito separá-los; mas uma união feita de outro modo não será de Deus. Quem te disse que foram unidos por Deus por serem virgens? Pois a Escritura não diz isso. Então não eram virgens?, dizes. Eram; mas não é a mesma coisa terem sido unidos sendo virgens e terem sido unidos por serem virgens. Embora nem sequer isso encontres dito expressamente, que fossem virgens, ainda que o fossem. O que se exprime é a diversidade dos sexos, não a virgindade, quando se diz: Criou-os homem e mulher. E com razão. Pois a união conjugal não requer a integridade dos corpos, mas a aptidão dos sexos. Com acerto, pois, o Espírito Santo, ao instituí-la, exprimiu o sexo e calou a virgindade, e não deu às raposinhas traiçoeiras ocasião de caçar uma palavra. O que elas teriam feito com gosto — embora também isso em vão. Pois que seria, se tivesse dito: Criou-os virgens? Terias acaso provado por isso, sem mais, que só os virgens podem unir-se? E, no entanto, como terias exultado só com a ocasião da palavra! Como terias desprezado as segundas e terceiras núpcias! Como terias insultado a Igreja católica, que une entre si prostitutas e rufiões com tanto mais gosto quanto não duvida que assim passam do torpe ao honesto! Talvez até repreendesses a Deus por mandar o profeta casar com uma prostituta (Os 1,2); mas agora falta-te até a ocasião, e dá-te gosto ser herege de graça. Pois o testemunho que usurpaste para construir o teu erro mostrou-se mais valioso para o destruir: nada faz a teu favor, e muitíssimo contra ti.`
    },
    {
      n: 5,
      texto: `Ouve agora o que te confunde ou corrige inteiramente, e esmaga e reduz a pó a tua heresia: A mulher está ligada ao marido enquanto ele vive; mas, se o marido morrer, fica livre da lei do marido: case com quem quiser, contanto que seja no Senhor (1Cor 7,39). É Paulo quem concede à viúva casar com quem quiser; e tu, ao contrário, mandas: Nenhuma se case senão a virgem, e só com um virgem, de modo que nem ela se case com quem quiser. Por que encurtas a mão de Deus? Por que restringes a larga bênção das núpcias? Por que reivindicas como próprio da virgem o que foi concedido ao sexo? Paulo não o concederia, se não fosse lícito. E digo pouco: concede; mas também o quer. Quero, diz, que as mais jovens se casem (1Tm 5,14); e não há dúvida de que fala das viúvas. Que há de mais claro? O que concede porque é lícito, também o quer porque convém. E o que é lícito e convém, o herege proíbe? Com esta proibição não persuadirá de nada, senão de que é herege.`
    },
    {
      n: 6,
      texto: `Resta que os acossemos um pouco também com o resto da profecia do Apóstolo. Pois estes se abstêm, como ele predisse, dos alimentos que Deus criou para serem tomados com ação de graças (1Tm 4,3); e também por isto se mostram hereges — não por se absterem, mas por se absterem como hereges. Pois também eu me abstenho às vezes; mas a minha abstinência é satisfação pelos pecados, não superstição a serviço da impiedade. Acaso censuramos Paulo por castigar o seu corpo e reduzi-lo à servidão (1Cor 9,27)? Deixarei o vinho, porque no vinho está a luxúria (Ef 5,18); ou, se estiver doente, usarei dele com moderação, segundo o conselho de Paulo (1Tm 5,23). Deixarei as carnes, para que, alimentando demais a carne, não alimentem também os vícios da carne. O próprio pão procurarei tomá-lo com medida, para que, com o estômago pesado, não me enfade estar de pé a orar, e para que o profeta não me censure também a mim por ter comido o meu pão até me fartar (Ez 16,49). E nem sequer de água pura me acostumarei a encher-me, para que a dilatação do ventre não chegue até o estímulo da sensualidade. O herege faz de outro modo. Pois tem horror ao leite e a tudo o que se faz com ele, e enfim a tudo o que é gerado pelo coito. Faria bem, e cristãmente, se o fizesse não por virem do coito, mas para que não provoquem ao coito.`
    },
    {
      n: 7,
      texto: `Mas que quer dizer evitar-se assim, de modo geral, tudo o que é gerado pelo coito? Faz-me suspeitar esta observância dos alimentos tão expressamente assinalada. Contudo, se nos apresentas isto por regra dos médicos, não censuramos o cuidado da carne, que ninguém jamais odiou, contanto que não seja excessivo. Se por disciplina dos que se abstêm, isto é, da escola dos médicos espirituais, aprovamos até a virtude com que domas a carne e refreias a sensualidade. Mas, se, pela loucura de Mani, pões limites à beneficência de Deus, de modo que aquilo que ele criou e deu para ser tomado com ação de graças, tu, não só ingrato, mas censor temerário, o declares impuro e te abstenhas dele como de um mal, então não louvarei a abstinência, mas amaldiçoarei a blasfêmia; e antes te chamarei impuro a ti, que julgas alguma coisa impura. Tudo é puro para os puros, diz aquele ótimo avaliador das coisas; e nada é impuro senão para quem julga alguma coisa impura (cf. Rm 14,14); mas para os impuros e infiéis nada é puro: estão manchadas a sua mente e a sua consciência (Tt 1,15). Ai de vós, que rejeitais os alimentos que Deus criou, julgando-os impuros e indignos de passar para os vossos corpos; quando, por isso mesmo, o corpo de Cristo, que é a Igreja, vos cuspiu fora como manchados e impuros!`
    },
    {
      n: 8,
      texto: `Não ignoro que se gloriam de ser eles, e só eles, o corpo de Cristo; mas persuadam-se disso os que também estão persuadidos de ter o poder de consagrar todos os dias, à sua mesa, o corpo e o sangue de Cristo, para se alimentarem como corpo e membros de Cristo. Pois gabam-se de ser sucessores dos apóstolos e chamam-se apostólicos, sem poderem mostrar sinal nenhum do seu apostolado. Até quando a lâmpada debaixo do alqueire? Vós sois a luz do mundo, foi dito aos apóstolos; e por isso os apóstolos estão sobre o candelabro, para iluminarem o mundo inteiro. Envergonhem-se os sucessores dos apóstolos de não serem luz do mundo, mas do alqueire — e trevas do mundo. Digamos-lhes: Vós sois as trevas do mundo; e passemos a outra coisa. Dizem-se a Igreja. Mas contradizem aquele que diz: Não se pode esconder uma cidade situada sobre um monte (Mt 5,14-16). Credes então que a pedra desprendida do monte sem intervenção de mãos, que se tornou um monte e encheu o mundo (Dn 2,34-35), está fechada nas vossas cavernas? Mas também não é preciso demorar-nos aqui. A própria opinião deles foge de ser publicada, contente com o seu sussurro. Cristo tem, e terá sempre, inteira a sua herança, e por possessão os confins da terra (cf. Sl 2,8). São antes eles que se subtraem a esta grande herança, eles que tentam tirá-la a Cristo.`
    },
    {
      n: 9,
      texto: `Guardai-vos dos maldizentes, guardai-vos dos cães (cf. Fl 3,2). Zombam de nós porque batizamos as crianças, porque oramos pelos mortos, porque pedimos a intercessão dos santos. Apressam-se a proscrever Cristo em todo gênero de homens e em ambos os sexos, nos adultos e nas crianças, nos vivos e nos mortos: de um lado, excluindo as crianças pela impossibilidade da natureza; do outro, os adultos pela dificuldade da continência. E defraudam os mortos da ajuda dos vivos, e despojam igualmente os vivos da intercessão dos santos que partiram. Longe disso! O Senhor não abandonará o seu povo, que é como a areia do mar, nem se contentará com o pequeno número dos hereges, ele que resgatou a todos. Pois não é pequena, mas abundante junto dele a redenção (cf. Sl 129,7). E que é o número destes diante da grandeza do preço? Defraudam antes a si mesmos do preço aqueles que tentam anulá-lo. Pois que importa que a criança não possa falar por si, se por ela clama a Deus, da terra, a voz do sangue do seu irmão (cf. Gn 4,10) — e de tal irmão? Está presente também, e clama, a mãe Igreja. E a própria criança? Não te parece que também ela, de certo modo, anseia pelas fontes do Salvador, grita a Deus e clama com os seus vagidos: Senhor, sofro violência; responde por mim (Is 38,14)? Implora o auxílio da graça, porque sofre violência da natureza. Clama a inocência do infeliz, clama a ignorância do pequenino, clama a fraqueza do condenado. Assim clamam todas estas coisas — o sangue do irmão, a fé da mãe, o desamparo do infeliz e a infelicidade do desamparado —, e clama-se ao Pai. E o Pai não pode negar-se a si mesmo: pois é pai.`
    },
    {
      n: 10,
      texto: `Ninguém me diga que não tem fé aquele a quem a mãe comunica a sua, envolvendo-a para ele no sacramento, até que se torne capaz de a receber desenvolvida e pura, não só pelo próprio entendimento, mas também pelo próprio assentimento. Acaso é um manto curto, que não possa cobrir os dois (cf. Is 28,20)? Grande é a fé da Igreja. Acaso é menor que a fé da mulher cananeia, que, como é certo, pôde bastar para a filha e para ela? Por isso ouviu: Ó mulher, grande é a tua fé! Seja-te feito como pediste (Mt 15,28). Acaso é menor que a fé daqueles que, descendo o paralítico pelas telhas, lhe obtiveram a saúde da alma e do corpo? Enfim, tens: Vendo a fé deles, disse ao paralítico: Tem confiança, filho, os teus pecados te são perdoados; e pouco depois: Toma o teu leito e anda (Mt 9,2.5-6). Quem crê isto facilmente se persuadirá de que a Igreja, com razão, espera na sua fé não só a salvação para as crianças batizadas, mas também a coroa do martírio para as crianças mortas por Cristo. Sendo assim, os regenerados não sofrerão prejuízo nenhum daquilo que se disse: Sem fé é impossível agradar a Deus (Hb 11,6), pois não estão sem fé os que receberam a graça do batismo em testemunho da fé. Nem daquilo que também se disse: Mas quem não crer será condenado (Mc 16,16). Pois que é crer, senão ter fé? Assim, também a mulher se salvará pela geração dos filhos, se permanecer na fé com modéstia (1Tm 2,15); e as crianças serão socorridas pelo banho da regeneração; e os adultos que não puderem guardar a continência se resgatarão pelo fruto trinta por um do matrimônio; e os mortos que precisarem e forem dignos receberão, por meio dos anjos, as orações e os sacrifícios dos vivos; e aos que ainda vivem não faltarão de modo nenhum as consolações dos que já chegaram, por meio de Deus, que está em toda parte, e dos quais, em Deus, nenhum está ausente pelo afeto da caridade. Pois foi para isto que Cristo morreu e ressuscitou: para ser Senhor dos vivos e dos mortos (Rm 14,9). Por isto também nasceu criança e cresceu, por todos os degraus das idades, até ser homem, para não faltar a nenhuma idade.`
    },
    {
      n: 11,
      texto: `Não creem que depois da morte reste o fogo do purgatório, mas que a alma, logo que se solta do corpo, passa ou ao repouso ou à condenação. Perguntem, pois, àquele que disse que há um pecado que não será perdoado nem neste mundo nem no futuro (Mt 12,32), por que o disse, se no futuro não resta nenhum perdão ou purificação do pecado. E não admira que os que não reconhecem a Igreja falem mal das ordens da Igreja, não recebam as suas instituições, desprezem os sacramentos, não obedeçam aos mandamentos. São pecadores, dizem, os papas, os arcebispos, os bispos, os presbíteros; e por isso não são aptos nem para dar nem para receber os sacramentos. Nunca poderão andar juntas estas duas coisas, ser bispo e ser pecador? É falso. Caifás era pontífice; e, no entanto, que grande pecador, ele que ditava sentença de morte contra o Senhor! Se negas que era pontífice, há de convencer-te o testemunho de João, que conta que ele até profetizou, em testemunho do seu pontificado (Jo 11,51). Judas era apóstolo; e, embora avarento e criminoso, fora escolhido pelo Senhor. Acaso duvidas do apostolado daquele a quem o Senhor escolheu? Não fui eu, diz, que vos escolhi, os doze? E um de vós é um diabo (Jo 6,71). Ouves que o mesmo foi escolhido apóstolo e foi um diabo; e negas que possa ser bispo quem é pecador? Na cátedra de Moisés sentaram-se os escribas e os fariseus; e os que não lhes obedeceram como a pontífices foram culpados de desobediência até contra o próprio Senhor, que mandava, dizendo: Fazei o que eles dizem (Mt 23,2-3). É claro, pois, que, embora escribas, embora fariseus, embora grandíssimos pecadores, por causa da cátedra de Moisés também a eles se aplicava o que disse igualmente: Quem vos ouve a mim ouve; e quem vos despreza a mim despreza (Lc 10,16).`
    },
    {
      n: 12,
      texto: `Muitos outros males foram persuadidos a este povo néscio e insensato pelos espíritos de erro, que falam mentiras com hipocrisia; mas não é possível responder a tudo. Pois quem conhece tudo? Além disso, seria um trabalho infinito e de modo nenhum necessário. Pois, quanto a estes, nem se convencem com razões, porque não entendem; nem se corrigem com autoridades, porque não as aceitam; nem se dobram com persuasões, porque estão pervertidos. Está provado: preferem morrer a converter-se. O fim destes é a perdição; o último destino que os espera é o fogo. Pois a figura deles precedeu no feito de Sansão, com as caudas das raposas incendiadas (Jz 15,4-5). Muitas vezes os fiéis, deitando-lhes as mãos, trouxeram alguns deles a público. Interrogados sobre a fé, como negassem absolutamente, segundo o seu costume, tudo aquilo de que pareciam suspeitos, foram examinados pelo juízo da água e achados mentirosos. E, não podendo já negar, pois tinham sido apanhados — a água não os recebia —, tomaram, como se diz, o freio nos dentes, e, tão miseravelmente quanto livremente, não confessaram a sua impiedade, mas professaram-na, afirmando abertamente que era piedade, e dispostos a morrer por ela. E não menos dispostos a dar-lhes a morte estavam os que assistiam. Assim, o povo, lançando-se sobre eles, deu aos hereges novos mártires da sua própria infidelidade. Aprovamos o zelo, mas não aconselhamos o fato; porque a fé deve ser persuadida, não imposta. Embora, sem dúvida, seja melhor que sejam reprimidos pela espada — daquele, entenda-se, que não traz a espada sem motivo — do que se lhes permita arrastar muitos para o seu erro. Pois ele é ministro de Deus, vingador para castigar quem faz o mal (Rm 13,4).`
    },
    {
      n: 13,
      texto: `Admiram-se alguns de que fossem levados à morte não só com paciência, mas, ao que parecia, até alegres; mas são os que menos reparam em quão grande é o poder do diabo, não só sobre os corpos dos homens, mas também sobre os corações que, uma vez permitido, possuiu. Não é mais o homem lançar mãos contra si mesmo do que suportar de bom grado que outro o faça? E temos visto muitas vezes que o diabo pôde isto em muitos, que se afogaram ou se enforcaram. Enfim, Judas enforcou-se (Mt 27,5), sem dúvida por instigação do diabo. Mas eu julgo coisa maior, e admiro-me mais, de que tenha podido pôr-lhe no coração que entregasse o Senhor (Jo 13,2) do que de que se enforcasse. Nada têm, pois, de semelhante a constância dos mártires e a obstinação destes; porque o desprezo da morte, naqueles, é obra da piedade; nestes, da dureza do coração. E por isso talvez o Profeta dizia, com a voz do mártir: O coração deles coalhou como leite; mas eu meditei na tua lei (Sl 118,70); porque, embora o castigo parecesse o mesmo, a intenção era muito diferente: um endurecia o coração contra o Senhor, o outro meditava na lei do Senhor.`
    },
    {
      n: 14,
      texto: `Sendo assim, não é preciso, como disse, dizer em vão muitas coisas contra homens tão néscios e tão obstinados: basta que sejam conhecidos, para que sejam evitados. Por isso, para que sejam descobertos, devem ser obrigados ou a mandar embora as mulheres ou a sair da Igreja, pois escandalizam a Igreja com a convivência e a coabitação com mulheres. É muito de lamentar que não só príncipes leigos, mas também, segundo se diz, alguns do clero e até da ordem dos bispos, que mais deviam persegui-los, os tolerem por interesse, recebendo presentes deles. E como, dizem, condenaremos quem não foi convencido nem confessou? Coisa bem frívola: não é razão, mas pretexto. Só com isto, ainda que não houvesse outra coisa, os descobres facilmente: se, como disse, separares uns dos outros os homens e as mulheres que se dizem continentes, e obrigares as mulheres a viver com outras do mesmo sexo e do mesmo voto, e igualmente os homens com homens do mesmo propósito. Pois assim se cuidará tanto do voto como da boa fama de uns e outros, que terão testemunhas e guardas da sua continência. E, se não o aceitarem, serão com toda a justiça expulsos da Igreja, que escandalizam com uma coabitação não só notória, mas também ilícita. Bastem, pois, estas coisas para descobrir os enganos destas raposas, para dar conhecimento e cautela à amada e gloriosa esposa de nosso Senhor Jesus Cristo, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
