SERMOES.sermao({
  id: 'bernardo-cantico-72',
  colecao: 'bernardo-cantico',
  ordem: 72,
  numero: 'LXXII',
  titulo: 'Que são o dia que aspira e as sombras que se inclinam; os diversos dias do homem; e como aos justos, que vivem na luz, espera um dia mais claro, e aos ímpios, que andam nas obras das trevas, a noite eterna',
  fonte: 'Dies aspirans, et umbrae inclinatae quae sint',
  argumento: `Resta a última parte do versículo: "até que aspire o dia e se inclinem as sombras". Se a ligamos a "o meu amado para mim, e eu para ele", o "até que" não põe fim a nada, como em "José não a conheceu até que deu à luz"; se a ligamos a "que se apascenta entre os lírios", indica que, no dia da ressurreição, o esposo já não se alimentará dos pecadores nem das obras da obediência: beberá as virtudes, então puras como vinho coado, em vez de as mastigar.

O dia e as sombras são espirituais. As sombras são as potências das trevas, que naquele dia não serão aniquiladas, mas se inclinarão, submetidas; ou então as figuras e os enigmas das Escrituras, que desaparecerão quando vier o que é perfeito. E Bernardo explica por que o dia "aspira": houve o dia que inspirou em Adão o sopro da vida; o dia que conspirou com a serpente e se tornou o dia que expira, no qual todos nascemos; há o dia que respira, quando o espírito resiste à carne; e haverá o dia que aspira, a glória da ressurreição, que acrescentará aos corpos o que a graça já deu às almas. Os justos passam da luz para mais luz; os ímpios, das trevas para trevas mais densas.

Tradução feita do texto latino de Migne (PL 183, 1128-1134).`,
  pontos: [
    {
      n: 1,
      texto: `O meu amado para mim, e eu para ele, que se apascenta entre os lírios, até que aspire o dia e se inclinem as sombras (Ct 2,16-17). Resta tratar só a última parte deste versículo, e logo à entrada hesito sobre a qual das duas anteriores a devo ligar de preferência: pois posso ligá-la indiferentemente a uma ou a outra. Quer digas: O meu amado para mim, e eu para ele, até que aspire o dia e se inclinem as sombras — ficando apenas intercalado: que se apascenta entre os lírios —; quer, seguindo a ordem da letra: que se apascenta entre os lírios, até que aspire o dia e se inclinem as sombras, não a atribuis mal a nenhuma das duas. Importa, porém, isto: se ligares o "até que" à primeira, deves entendê-lo em sentido inclusivo; se à do meio, tens de o entender em sentido exclusivo. Admitamos, com efeito, que o esposo deixe de se apascentar entre os lírios quando o dia aspirar: acaso deixará igualmente de estar atento à esposa, ou ela a ele? Longe disso! Perseverarão um para o outro eternamente; só que então mais felizes, porque com mais intensidade; e com mais intensidade, porque mais desembaraçados. Seja, pois, este "até que" como aquele de Mateus, onde se narra que José não conheceu Maria até que ela deu à luz o seu Filho primogênito (Mt 1,25): pois nem depois a conheceu. Ou, certamente, como aquele do salmo: Os nossos olhos estão voltados para o Senhor nosso Deus, até que tenha piedade de nós (Sl 122,2): pois não se desviarão quando ele começar a ter piedade. Ou ainda como aquela palavra do Senhor aos apóstolos: Eis que estou convosco até a consumação dos séculos (Mt 28,20): pois nem depois deixará de estar com eles. Mas isto é assim se referires o "até que" a: O meu amado para mim, e eu para ele. Se, porém, preferires que se refira a: que se apascenta entre os lírios, deverá ser tomado noutro sentido. E será mais trabalhoso mostrar como o amado deixa de se apascentar quando o dia aspirar. Pois, se esse é o dia da ressurreição, por que não lhe agradaria muito mais apascentar-se ali entre os lírios, onde a abundância deles será muito maior? E fique isto dito para ajustar a sequência da letra.`
    },
    {
      n: 2,
      texto: `Repara agora comigo que, embora todo o reino resplandeça de lírios e o esposo esteja no meio deles, deleitando-se, não haverá, porém, razão para se dizer que se apascenta, pelo menos no sentido em que antes costumava. Pois onde estarão então os pecadores que Cristo incorpore a si, mastigados e mordidos como que pelos dentes de uma disciplina mais austera, isto é, pela aflição da carne e pela contrição do coração? Nem o Verbo esposo exigirá já para si alimento de algumas ações ou obras de obediência, onde todo negócio será ócio, e tudo consistirá só em contemplar e amar. O seu alimento, é certo, é fazer a vontade de seu Pai (cf. Jo 4,34); mas aqui, não lá. Pois que faria de uma vontade já feita? E é certo que então estará perfeitamente cumprida. Enfim, então será dado a todos os santos experimentar qual é a vontade de Deus, boa, agradável e perfeita (cf. Rm 12,2). E, certamente, depois do perfeito, nada resta a fazer. Resta, daí em diante, gozar dela, não fazê-la; experimentá-la, não trabalhar nela; viver dela, não exercitar-se nela. Não é ela aquela que, ensinados pelo Senhor, pedimos com a mais insistente oração que se cumpra assim na terra como no céu (Mt 6,10), para que já nos deleite o seu fruto e não nos canse a sua execução? Não haverá, pois, para o Verbo esposo o alimento da obra, porque é necessário que cesse toda obra onde a sabedoria é recebida por todos com mais plenitude. Pois os que diminuem a atividade é que a recebem (Eclo 38,25).`
    },
    {
      n: 3,
      texto: `Mas vejamos agora se o que dizemos pode sustentar-se também segundo aquela interpretação pela qual alguns entendem o apascentar-se entre os lírios como deleitar-se com a brancura das virtudes — pois também nós não a omitimos entre as outras. Diremos que então as virtudes ou não existirão, ou não agradarão ao esposo? Pensar uma ou outra coisa é loucura. Mas vê se talvez não se deleite com elas de outro modo: pois é certo que se deleita, mas talvez bebendo-as mais do que comendo-as. Neste tempo e neste corpo, certamente, nenhuma virtude nossa estará tão limpa das borras, nenhuma tão suave e pura, que seja própria para o esposo a beber. Mas aquele que quer que todos os homens se salvem (1Tm 2,4) faz vista grossa a muitas coisas (cf. Sb 11,24) e, não podendo por ora engoli-la com a facilidade de quem bebe, procura tirar dela ao menos alguma coisa saborosa, como que com uma certa arte e um certo trabalho de mastigar. Virá o tempo em que a virtude será coada: não será apertada pelo dente, nem cansada por quem a mastiga — ou antes, não cansará quem a mastiga —, mas deleitará sem esforço quem a bebe, como bebida, e não como comida. Enfim, tens no Evangelho a sua promessa: Não beberei deste fruto da videira, diz, até o dia em que o beber, novo, convosco no reino de meu Pai (Mt 26,29). E do alimento não há menção nenhuma. Também no Profeta se lê: Como um valente embriagado pelo vinho (Sl 77,65); mas ali não se encontra absolutamente nada sobre comida. A esposa, pois, conhecedora deste mistério, tendo descoberto e declarado que o amado se apascenta entre os lírios, fixou um termo até o qual ele se dignaria fazê-lo; ou antes, reconheceu e declarou o termo já fixado, dizendo: Até que aspire o dia e se inclinem as sombras. Pois sabia que depois ele havia de beber as virtudes mais do que comê-las. Parece concordar também o costume, segundo o qual se toma a bebida depois da comida. Portanto, quem aqui come, lá beberá, e então com tanto mais suavidade quanto mais segurança, engolindo até aquelas mesmas coisas que agora, com mais escrúpulo e de certo modo com mais trabalho, vai desfazendo como que a mastigar.`
    },
    {
      n: 4,
      texto: `Apliquemo-nos agora a considerar aquele dia e as suas sombras: que dia é aquele, que sombras são estas; por que razão aquele aspira, e em que sentido estas hão de se inclinar. É muito expressivo o que se disse: até que aspire o dia; ou antes, é singular. Pois só neste lugar, se não me engano, encontrarás um dia que aspira. Diz-se que as brisas sopram, não os tempos. Respira o homem, respiram os outros animais, nos quais o ar, indo e vindo sem cessar, mantém a vida. E que é isto, senão vento? Sopra também o Espírito Santo (cf. Jo 3,8), e daí lhe vem o nome de espírito. Como então se diz que o dia sopra, se não é vento, nem espírito, nem animal? Embora nem sequer se tenha dito que sopra, mas, o que soa mais expressivo, que aspira. E não menos fora do comum é o que se diz: e se inclinem as sombras. Pois, ao nascer desta luz corporal e visível, as sombras não se inclinam, mas são anuladas. Estas coisas devem ser procuradas, portanto, fora dos corpos. E, se encontrarmos um dia e sombras espirituais, então talvez se torne mais fácil ver com clareza tanto a inclinação destas como a aspiração daquele. Quem julga corporal aquele dia de que o Profeta diz: Melhor é um dia nos teus átrios do que mil (Sl 83,11), não sei o que já não julgará corporal. Há também um dia em sentido mau, que os profetas amaldiçoaram (Jó 3,3; Jr 20,14). Longe de nós, porém, pensar que seja um destes dias visíveis que o Senhor fez! É, pois, espiritual.`
    },
    {
      n: 5,
      texto: `E quem duvidará de que é espiritual a sombra com que Maria foi coberta ao conceber (Lc 1,35); e igualmente aquela que o profeta lembra assim: O Cristo Senhor é espírito diante da nossa face; à sua sombra viveremos entre as nações (Lm 4,20)? Eu, contudo, penso que neste lugar, com o nome de sombras, se designam antes as potências contrárias, que o Apóstolo chama não só sombras ou trevas, mas também príncipes destas trevas (Ef 6,12); e, juntamente, os da nossa raça que se apegam a elas, filhos da noite, e não da luz nem do dia (cf. 1Ts 5,5). Estas sombras, com efeito, quando o dia aspirar, não voltarão ao nada, como vemos que as sombras corporais, diante desta luz corporal, não só desaparecem, mas perecem por completo. Continuarão, pois, a existir: não num estado mais baixo que o nada, mas mais miserável que ele. Existirão, mas inclinadas e submetidas. Enfim: Há de inclinar-se, diz — sem dúvida o príncipe das sombras —, e cair, quando tiver dominado os pobres (Sl 9,31). Não será, pois, destruída a natureza, mas retirado o poder; não perecerá a substância, mas passará a hora e o poder das trevas (cf. Lc 22,53). São tirados, para que não vejam a glória de Deus (cf. Is 26,10); não são anulados, para que ardam sempre. E como não se inclinarão as sombras, quando os poderosos forem derrubados do trono (cf. Lc 1,52) e postos como escabelo dos pés (cf. Sl 109,1)? O que deve acontecer em breve. É a última hora (1Jo 2,18); a noite vai adiantada, e o dia se aproxima (Rm 13,12). Aspirará o dia, e expirará a noite. A noite é o diabo; noite é o anjo de Satanás (cf. 2Cor 12,7), ainda que se transfigure em anjo de luz (cf. 2Cor 11,14). Noite é também o Anticristo, a quem o Senhor matará com o sopro da sua boca e destruirá com o esplendor da sua vinda (2Ts 2,8). Não é o Senhor o dia? Dia, certamente, que ilumina e sopra, que com o sopro da sua boca afugenta as sombras e destrói os fantasmas com o esplendor da sua vinda. Ou, se se prefere tomar simplesmente a palavra "inclinar-se" e pensar que inclinar-se não é outra coisa senão ser reduzido a nada, para não faltarmos também a este sentido, dizemos que as sombras são as figuras e os enigmas das Escrituras, e também os modos de falar sofísticos, as cavilações de palavras e os enredos dos argumentos, coisas todas que por ora fazem sombra à luz da verdade. Pois conhecemos em parte e em parte profetizamos. Mas, quando o dia aspirar, as sombras se inclinarão, porque, ocupando a plenitude da luz todas as coisas, não poderá restar parte nenhuma de trevas. Enfim, quando vier o que é perfeito, então será abolido o que é parcial (1Cor 13,9-10).`
    },
    {
      n: 6,
      texto: `Até aqui, isto poderia bastar, se se tivesse dito que aquele dia sopra, e não que aspira. Mas agora, por esse pequenino acréscimo, julgo que ainda devo acrescentar alguma coisa, para investigar a razão desta diferença. Pois eu, para dizer a verdade, há muito tempo me convenci de que no texto da palavra sagrada e preciosa nem a menor partícula está ali à toa. Ora, costumamos usar esta palavra quando desejamos alguma coisa intensamente; como, por exemplo, quando dizemos: Fulano aspira a tal honra, ou a tal dignidade. Designa-se, pois, com esta palavra a admirável abundância e veemência do espírito que haverá naquele dia, quando não só os corações, mas também os corpos, a seu modo, serão espirituais (cf. 1Cor 15,44); e os que forem achados dignos se embriagarão da abundância da casa do Senhor e beberão da torrente das suas delícias (cf. Sl 35,9).`
    },
    {
      n: 7,
      texto: `Ou de outro modo. Para os santos anjos já brilhou o dia santificado, soprando-lhes, com o ímpeto contínuo de uma corrente perene, os segredos, doces como o mel, da divindade eterna. Enfim: O ímpeto do rio alegra a cidade de Deus (Sl 45,5); mas a cidade a quem se diz: A morada de todos em ti é como a de quem se alegra (Sl 86,7). E, quando, além disso, soprar também para nós, que habitamos a terra, será não só um dia que sopra, mas que aspira, porque, dilatando o seio, nos acolherá também a nós. Ou ainda — para retomarmos a coisa de um pouco mais alto e a desenvolvermos mais amplamente —: formado o homem do limo da terra, aquele que o formou, como narra a história verídica, inspirou-lhe no rosto um sopro de vida (Gn 2,7), tornando-se assim para ele o dia que inspira. E eis que a noite invejosa se lançou astutamente contra este dia, simulando, é claro, a luz. Pois, prometendo como que uma luz mais esplêndida de ciência, derramou sobre a luz nova as trevas inesperadas de um conselho perverso, e trouxe aos primórdios da nossa origem a negra escuridão de uma prevaricação funesta. Ai, ai! Não souberam nem entenderam, andam nas trevas (cf. Sl 81,5) sem saber, chamando às trevas luz, e à luz trevas (cf. Is 5,20). Enfim, a mulher comeu da árvore — o que a serpente lhe tinha dado e Deus tinha proibido —, e deu ao seu marido (cf. Gn 3,6); e começou para eles como que a amanhecer de novo. Pois imediatamente se abriram os olhos de ambos (Gn 3,7), e fez-se um dia que conspira, expulsando o que inspira e pondo em seu lugar o que expira. Pois conspiraram e se reuniram num só contra o Senhor e contra o seu Cristo (cf. Sl 2,2): a astúcia da serpente, as seduções da mulher, a fraqueza do homem. Por isso diziam entre si, isto é, o Senhor e o seu Cristo: Eis que Adão se tornou como um de nós (Gn 3,22) — porque, para injúria de um e de outro, tinha cedido aos pecadores que o aliciavam.`
    },
    {
      n: 8,
      texto: `Neste dia nascemos todos. Todos trazemos, enfim, gravado em nós o ferrete da antiga conspiração; pois Eva vive na nossa carne, e, por meio da concupiscência que dela herdamos, a serpente procura com diligente empenho ganhar o nosso consentimento para o seu partido. Por isso, como disse, os santos amaldiçoaram este dia (Jó 3,3; Jr 20,14), desejando que fosse breve e se convertesse depressa em trevas, porque é dia de luta e de contradição, em que a carne não cessa de ter desejos contrários ao espírito (cf. Gl 5,17), e a lei dos membros, contrária à lei da mente, a contradiz sem cessar com uma rebelião incansável (cf. Rm 7,23). Assim se tornou um dia que expira. Pois, desde então e daí em diante, quem é o homem que viverá e não verá a morte (Sl 88,49)? Diga alguém que isto é por ira; eu penso que não menos por misericórdia, para que a penosa contradição não canse por muito tempo os eleitos, por causa dos quais tudo se faz, e que também eles são levados cativos na lei do pecado que está nos seus membros. Pois eles têm horror a esse torpe cativeiro e a essa triste luta, e os suportam com grande pena.`
    },
    {
      n: 9,
      texto: `Apressemo-nos, pois, a respirar, livres da antiga e iníqua conspiração, porque os dias do homem são breves (Jó 14,5). Que nos acolha o dia que respira antes que nos trague a noite que suspira, para nos envolver nas trevas exteriores de uma escuridão eterna. Perguntas em que consiste este respirar? Em que o espírito comece, por sua vez, a ter desejos contrários à carne (cf. Gl 5,17). Se lhe resistes, respiras; se pelo espírito mortificas as obras da carne (cf. Rm 8,13), respiraste; se a crucificas com os seus vícios e concupiscências (cf. Gl 5,24), respiraste. Castigo, diz, o meu corpo e o reduzo à servidão, para que não aconteça que, tendo pregado aos outros, eu mesmo seja reprovado (1Cor 9,27). É a voz de quem respira, ou antes, de quem já tinha respirado. Vai, e faze tu o mesmo (Lc 10,37), para provares que respiraste, para saberes que brilhou de novo para ti o dia que inspira. E a noite da morte não prevalecerá contra este dia renascido; antes, ele brilha nas trevas, e as trevas não o apreenderam (cf. Jo 1,5). Tanto não creio que, mesmo quando a vida se vai, se vá a luz da vida, que julgo que a ninguém se aplica com mais propriedade do que a quem assim morreu aquela palavra: E a noite é a minha iluminação nas minhas delícias (Sl 138,11). E como não havia de ver mais claramente, livre da nuvem — ou antes, da borra — do corpo? Sem dúvida, solto dos laços corporais, será livre entre os mortos (cf. Sl 87,6) e vidente entre os cegos. Pois, assim como outrora, estando cegos todos os olhos em todo o Egito, só no meio das trevas via com clareza o povo que vê a Deus, isto é, o povo de Israel — dizendo a Escritura que onde quer que estivesse Israel havia luz (cf. Ex 10,23) —, assim, entre os filhos das trevas, na negra escuridão da morte, os justos brilharão e verão, tanto mais claramente quanto mais despojados das sombras dos corpos. Pois também estes, que antes não respiraram — porque não procuraram a luz do dia que inspira, e o sol da justiça não nasceu para eles (cf. Sb 5,6) —, estes, digo, irão das trevas para trevas mais densas, para que os que estão nas trevas se entenebreçam ainda mais, e os que veem vejam mais (cf. Ap 22,11).`
    },
    {
      n: 10,
      texto: `Aqui talvez não seja despropositado trazer também a palavra do Senhor, que disse: A quem tem, será dado, e terá em abundância; mas a quem não tem, até o que parece ter lhe será tirado (Lc 19,26). Assim é: na morte, acrescenta-se aos que veem, e tira-se aos que não veem. Pois, quanto menos e menos veem estes, tanto mais e mais veem aqueles, até que a uns acolha a noite que suspira, e aos outros o dia que aspira: estes são os últimos estados de uns e de outros, isto é, a extrema cegueira e a suprema claridade. Daí em diante, não haverá mais nada que tirar aos que estão de todo vazios, nem nada que acrescentar aos cheios; a não ser que estes confiam que receberão não sei quê mais do que o cheio, segundo a promessa que lhes foi feita. E a palavra da promessa é esta: Uma medida boa, calcada, sacudida e transbordante vos derramarão no regaço (Lc 6,38). Não te parece que o que transborda é, de certo modo, mais do que cheio? E ouvirás sem estranheza falar de cheio e de mais que cheio, se te lembrares de ter lido: Para sempre e mais além (Ex 15,18). Este será, pois, o acréscimo do dia que aspira. Ele, digo, acrescentará à medida da plenitude inspirada, à abundância do dia que inspira, produzindo, acima de toda medida, um peso sublime de glória (cf. 2Cor 4,17), de modo que o acréscimo transbordante da glorificação se derrame também sobre os corpos. Por esta razão, com efeito, não se disse que sopra, mas que aspira: porque acrescenta algo ao dia que inspira, significando-o o Espírito Santo pela preposição que se juntou à palavra; pois àqueles que o primeiro ilumina por dentro, este adorna por fora, e os reveste com a veste da glória (cf. Eclo 45,9).`
    },
    {
      n: 11,
      texto: `E isto baste para dar a razão da palavra "aspira". E, se quereis saber, o dia que aspira é o próprio Salvador que esperamos, que transformará o nosso corpo humilhado, tornando-o semelhante ao seu corpo glorioso (Fl 3,20-21). Pois o dia que inspira é também ele mesmo, segundo a ação pela qual primeiro nos faz respirar na luz que inspira, para que também nós sejamos nele um dia que respira, na medida em que o nosso homem interior se renova de dia em dia (2Cor 4,16) e se renova no espírito da sua mente (cf. Ef 4,23) à imagem daquele que o criou (cf. Cl 3,10), tornando-se assim dia do dia e luz da luz. Como, pois, precedem em nós dois dias — um que inspira, para a vida do corpo, e outro que respira, na graça da santificação —, e resta ainda um terceiro que aspira, na glória da ressurreição, é claro que um dia se há de cumprir no corpo o que precedeu na cabeça — o grande mistério da piedade (cf. 1Tm 3,16) — e o testemunho do profeta, que diz: Depois de dois dias nos dará a vida; ao terceiro dia nos ressuscitará, e viveremos na sua presença; saberemos, e seguiremos para conhecer o Senhor (Os 6,3). É ele aquele para quem os anjos desejam olhar (1Pd 1,12), o esposo da Igreja, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
