SERMOES.sermao({
  id: 'bernardo-cantico-54',
  colecao: 'bernardo-cantico',
  ordem: 54,
  numero: 'LIV',
  titulo: 'De como, de outro modo, os montes significam os anjos e os homens, e as colinas os demônios; e do tríplice temor com que cada um deve temer perder a graça de agir bem recebida de Deus',
  fonte: 'Qualiter iterum per montes significantur angeli et homines',
  argumento: `Bernardo propõe outro sentido para os saltos do esposo (e lembra, de passagem, que os seus sermões eram anotados por escrito tais como eram ditos). Cristo saltou sobre os anjos quando se fez servidor como eles e os ultrapassou em prontidão: chegou à Virgem antes de Gabriel. Ou saltava "nos" anjos que apareciam aos patriarcas falando em nome do Senhor. As colinas que ele transpõe são os demônios do ar, inchados de soberba e estéreis como os montes de Gelboé, sobre os quais não cai nem orvalho nem chuva. De lá, entre o céu e a terra, o diabo vê os montes que Deus visita e se consome de inveja.

Segue-se uma das páginas mais pessoais de todo o sermonário. Bernardo olha para si e se descobre seco: há dias o salmo não tem sabor, a leitura e a oração não lhe dizem nada, está preguiçoso, sonolento, irritável; vê os irmãos visitados por Deus e julga-se um monte de Gelboé, rejeitado pela soberba. Pede que o imitem nisto: que se acusem, e não se poupem. Daí o tríplice temor: temer quando a graça está presente, para não a desperdiçar nem a atribuir a si; temer mais quando se retira, porque a causa é sempre a soberba; e temer ainda mais quando volta, porque recair é pior que cair. São as três medidas das talhas de Caná: cheias de temor, a caridade as converte em vinho.

Tradução feita do texto latino de Migne (PL 183, 1038-1044).`,
  pontos: [
    {
      n: 1,
      texto: `Sobre o mesmo passo de que se tratou no sermão de ontem, vou dizer também outro sentido, que reservei para hoje: vós examinai e escolhei o melhor. Não é preciso repetir o que foi dito antes, que não creio se tenha perdido da memória em tão pouco tempo. Se, no entanto, se perdeu, foi escrito tal como foi dito, e tomado pela pena, como os outros sermões, para que se recupere facilmente o que porventura tenha esquecido. Recebei, pois, outras coisas. Eis que ele vem, diz, saltando pelos montes, transpondo as colinas (Ct 2,8). Fala do esposo, que sem dúvida saltou então pelos montes quando, enviado pelo Pai a evangelizar os pobres, não desdenhou desempenhar o ofício dos anjos, feito Anjo do grande conselho (cf. Is 9,6), ele que era o Senhor. Desceu por si mesmo à terra quem costumava enviar outros; por si mesmo o Senhor deu a conhecer a sua salvação, por si mesmo revelou a sua justiça à vista das nações (Sl 97,2). Como todos, pois, segundo a sentença de Paulo, são espíritos servidores, enviados para servir aos que hão de herdar a salvação (Hb 1,14), aquele que estava acima deles fez-se entre eles como um deles, fazendo pouco caso da afronta e acumulando a graça. Mas ouve-o a ele: Não vim, diz, para ser servido, mas para servir e dar a minha vida por muitos (Mt 20,28). Coisa que nenhum dos outros se acha ter feito; de modo que ultrapassou, com os seus serviços devotos e fiéis, todos quantos se viu servirem. Bom servidor, que serviu a sua carne como alimento, o seu sangue como bebida, a sua vida como preço. Bom, sem dúvida, porque, pronto de espírito, fervoroso de caridade, devoto de piedade, não só salta pelos montes, mas também transpõe as colinas, isto é, supera-as e vence-as na prontidão de servir, ele a quem Deus, o seu Deus, ungiu com óleo de alegria de preferência aos seus companheiros (Sl 44,8); e nisto, de modo singular, exultou como um gigante para percorrer o caminho. Enfim, passou à frente de Gabriel e chegou antes dele à Virgem, como o atesta o próprio arcanjo, quando diz: Ave, cheia de graça, o Senhor está contigo (Lc 1,28). Quê? Aquele que acabas de deixar no céu, encontra-lo agora no seio? Como? Voou, e voou à tua frente, sobre as asas dos ventos (cf. Sl 17,11). Foste vencido, ó arcanjo: passou por cima de ti aquele que te mandou à frente.`
    },
    {
      n: 2,
      texto: `Ou então saltava pelos montes quando outrora aparecia aos patriarcas nos anjos; o que parece convir mais à propriedade da letra. Pois não diz: saltando para os montes, mas: nos montes, para que pareça que salta neles aquele que faz e concede que eles saltem; assim como fala nos profetas e opera nos justos, quando dá àqueles as palavras e a estes as obras. Acrescenta que alguns deles faziam as vezes dele, de modo que cada um falava não como anjo, mas como Senhor. Por exemplo, aquele anjo que falava com Moisés não dizia: Eu sou do Senhor, mas: Eu sou o Senhor, e repetia-o muitas vezes. Saltava, pois, nos montes, isto é, nos anjos, nos quais falava e mostrava aos homens a sua presença. Pois saltava até os homens, mas nos anjos, não em si mesmo; não na sua natureza, mas na criatura que lhe está sujeita. Pois quem salta vai de um lugar para outro, o que não cabe em Deus. Saltava, pois, nos montes, isto é, nos anjos, ele que em si mesmo não o podia; e saltava até as colinas, isto é, até os patriarcas e os profetas e os outros homens espirituais da terra. Mas transpunha também as colinas quando se dignava falar e aparecer igualmente nos anjos não só a homens grandes e espirituais, mas também a alguns do povo, e até a algumas mulheres. Ou então chama colinas às potestades do ar, que já não se contam entre os montes, porque escorregaram da altura das virtudes pela soberba; mas também não se desincham pela penitência até a baixeza dos vales, ou seja, até os vales dos humildes. É delas, creio, que se disse nos salmos: Os montes derreteram-se como cera diante da face do Senhor (Sl 96,5). Estas colinas inchadas e estéreis, pois, postas como no meio entre os montes dos perfeitos e os vales dos penitentes, sem dúvida as transpôs aquele que salta nos montes; e, deixando-as de lado e desprezando-as, desceu aos vales, para que os vales abundem em trigo (cf. Sl 64,14). E elas, pelo contrário, são condenadas a uma secura e esterilidade eternas, como tens na imprecação do profeta contra elas: Nem orvalho, diz, nem chuva desçam sobre vós. E, para que saibas que é dos anjos prevaricadores que fala, sob a figura dos montes de Gelboé: Onde, diz, caíram muitos feridos (cf. 2Sm 1,21). Quantos do exército de Israel caíram desde o princípio nestes montes malditos, e caem todos os dias! Deles tens também no mesmo profeta, quando diz ao Senhor: Como os feridos que dormem nos sepulcros, de quem já não te lembras, e que foram rejeitados da tua mão (Sl 87,6).`
    },
    {
      n: 3,
      texto: `Não é de admirar, pois, que permaneçam estéreis e sem fruto estas colinas do ar — não montes celestes —, sobre as quais não desce nem orvalho nem chuva; pois o autor da graça e dispensador das bênçãos as transpõe e desce aos vales, para regar com a chuva celeste os humildes que estão sobre a terra, e para que deem fruto na paciência (cf. Lc 8,15), trinta, sessenta e cem por um (Mt 13,8.23). Enfim, visitou a terra e a embriagou; multiplicou as suas riquezas (Sl 64,10). Visitou a terra, não o ar, porque a terra está cheia da misericórdia do Senhor (Sl 32,5). Enfim, operou a salvação no meio da terra (Sl 73,12); acaso também no meio do ar? Isto contra Orígenes, que, com uma mentira impudente, crucifica de novo no ar o Senhor da glória, pelos demônios; quando Paulo, conhecedor deste mistério, afirma que, ressuscitado dos mortos, já não morre, e a morte já não tem domínio sobre ele (Rm 6,9).`
    },
    {
      n: 4,
      texto: `Mas aquele que transpôs o ar não visitou só a terra, mas também o céu, como diz a Escritura: Senhor, a tua misericórdia está no céu, e a tua verdade chega até as nuvens (Sl 35,6). Pois até as nuvens vai o céu que os santos anjos habitam, e a estes o Esposo não os transpôs, mas salta neles, de modo a imprimir-lhes dois vestígios dos seus pés, a misericórdia e a verdade; destes vestígios do Senhor lembro-me de ter tratado mais amplamente em sermões anteriores. Das nuvens para baixo, porém, é a morada dos demônios, neste ar inferior e caliginoso; neles o esposo não salta, mas transpõe-nos e passa adiante, e eles não retêm em si nenhum vestígio de Deus que passa. Pois como haveria verdade no diabo, de quem está nos Evangelhos a sentença da Verdade: que não permaneceu na verdade, mas foi mentiroso desde o princípio? E ninguém chamaria misericordioso aquele que, pela mesma verdade do Evangelho, se prova ter sido homicida desde o princípio (Jo 8,44). E, qual o pai de família, tais os da sua casa. Por isso, com beleza, a Igreja, cantando do Esposo que habita nas alturas e olha para as coisas humildes no céu e na terra (Sl 112,5-6), não faz menção nenhuma dos espíritos soberbos que vivem no ar, porque Deus resiste aos soberbos e dá a graça aos humildes (Tg 4,6).`
    },
    {
      n: 5,
      texto: `Ela o vê, pois, saltando pelos montes e transpondo as colinas, segundo a imprecação de Davi, que diz: Todos os montes que estão ao seu redor — isto é, ao redor de Gelboé — visite-os o Senhor; mas passe ao largo de Gelboé (cf. 2Sm 1,21). Pois o diabo, que é designado por Gelboé, tem de um lado e de outro montes que o Senhor visita: acima, os anjos; abaixo, os homens. Pois, caindo do céu, coube-lhe como castigo um lugar neste ar, no meio entre o céu e a terra, para que veja e inveje e seja atormentado pela própria inveja, como diz a Escritura: O pecador verá e se irritará, rangerá os dentes e se consumirá (Sl 111,10). Quão infeliz, quando olha para os céus, onde contempla montes sem número refulgindo da claridade divina, ressoando de louvores divinos, sublimes na glória, abundantes na graça! Quão mais infeliz, quando olha para a terra, que tem também muitíssimos montes do povo adquirido por Deus, sólidos na fé, elevados na esperança, amplos na caridade, cultivados pelas virtudes, cheios dos frutos das boas obras, recebendo cada dia a bênção do orvalho do céu, como do salto do esposo! Com quanta dor e rancor pensamos que ele, tão ávido de glória, olha para estes montes tão gloriosos ao seu redor, quando, pelo contrário, vê a si e aos seus incultos, tenebrosos, estéreis de todo bem, de modo que se sente o opróbrio dos homens e dos anjos, ele que a todos insultava, conforme aquilo dos Salmos: Esse dragão que formaste para zombares dele (Sl 103,26)!`
    },
    {
      n: 6,
      texto: `E isto, porque o Esposo, por causa da soberba deles, os transpõe, saltando para os montes que estão ao seu redor, como a fonte que sobe do meio do paraíso e rega todas as coisas, e enche de bênção todo ser vivo (cf. Sl 144,16). Felizes os que merecem beber às vezes, ainda que raramente, da torrente desta delícia; aqueles em quem, se não corre continuamente, ao menos por momentos jorra a água da sabedoria e a fonte da vida, para que se torne também neles uma fonte de água que jorra para a vida eterna (cf. Jo 4,14). E o ímpeto deste rio alegra a cidade de Deus (cf. Sl 45,5), sem dúvida perenemente e com abundância. Oxalá, porém, não desdenhe dar às vezes, como numa inundação, alguns saltos nos nossos montes que estão na terra, para que, suficientemente regados, possam gotejar também para nós, que somos vales, ao menos umas gotinhas raras, para que não fiquemos de todo secos e estéreis! Miséria, penúria e fome violenta há naquela região que nunca é umedecida por tais saltos ou gotejamentos, porque a fonte da sabedoria passa ao largo e a transpõe: E, porque não tiveram sabedoria, diz, pereceram por causa da sua insensatez (Br 3,28).`
    },
    {
      n: 7,
      texto: `Eis que ele vem, saltando pelos montes, transpondo as colinas. Salta para transpor, porque não quer chegar a todos; pois nem em todos se compraz Deus (cf. 1Cor 10,5). Irmãos, se, segundo a sabedoria de Paulo, estas coisas foram escritas para nossa correção (1Cor 10,11), observemos os saltos cheios de discernimento e cautela do Esposo, isto é, como, tanto entre os anjos como entre nós, salta sobre os humildes e transpõe os soberbos; pois o Senhor excelso olha para os humildes e conhece de longe os altivos (Sl 137,6). Atentemos, digo, nestas coisas, para termos o cuidado de nos preparar para os saltos salutares do Esposo, para que não passe também ao largo de nós, como dos montes de Gelboé, se nos vir indignos da sua visita. Por que te ensoberbeces, terra e cinza (cf. Eclo 10,9)? O Senhor passa ao largo até dos anjos, detestando a sua soberba. Que a rejeição dos anjos seja, pois, a emenda dos homens; pois foi escrita para a sua correção. Coopere também para o meu bem o mal do diabo, e lave eu as minhas mãos no sangue do pecador (cf. Sl 57,11). Como?, perguntas. Ouve. Sem dúvida é lançada contra o diabo soberbo uma maldição horrível e temível, dizendo dele em espírito o profeta Davi, sob a figura de Gelboé, como se lembrou acima: Os montes que estão ao seu redor, visite-os o Senhor; mas passe ao largo de Gelboé.`
    },
    {
      n: 8,
      texto: `Eu, lendo isto e voltando os olhos para mim, e olhando-me com atenção, acho-me infectado da mesma peste que o Senhor tanto detestou no anjo, a ponto de se desviar dele por causa disso, quando se dignava conceder a graça da sua visita a todos os montes que estavam ao seu redor, anjos ou homens; e, com medo e tremor, digo a mim mesmo: Se assim se fez com o anjo, que será de mim, terra e cinza? Ele se inchou no céu; eu, no monturo. Quem não julga mais tolerável a soberba no rico do que no pobre? Ai de mim! Se aquele poderoso foi castigado com tanta dureza porque o seu coração se elevou, e de nada lhe valeu que a soberba seja reconhecidamente parente dos poderosos, que se há de exigir de mim, miserável e soberbo? Enfim, já pago a pena, já sou açoitado com a maior dureza. Não é sem razão, sem dúvida, que desde ontem e anteontem me invadiu esta languidez da alma, este embotamento da mente, uma inércia de espírito fora do comum. Corria bem; mas eis uma pedra de tropeço no caminho: bati nela e caí. Achou-se em mim a soberba, e o Senhor desviou-se na sua ira do seu servo (cf. Sl 26,9). Daí esta esterilidade da minha alma e a falta de devoção que sofro. Como secou assim o meu coração, coalhou-se como leite (cf. Sl 118,70), tornou-se como terra sem água (cf. Sl 142,6)? Nem consigo compungir-me até as lágrimas, tamanha é a dureza do coração. O salmo não tem sabor, não me apetece ler, não me deleita orar, não encontro as meditações de costume. Onde está aquela embriaguez do espírito? Onde a serenidade da mente, e a paz, e a alegria no Espírito Santo? Por isso sou preguiçoso no trabalho manual, sonolento nas vigílias, precipitado na ira, obstinado no rancor, condescendente demais com a língua e com a gula, mais lento e mais embotado para a pregação. Ai! O Senhor visita todos os montes ao meu redor, mas de mim não se aproxima. Não serei eu uma das colinas que o esposo transpõe? Pois vejo um de abstinência singular, outro de paciência admirável, outro de suma humildade e mansidão, outro de muita misericórdia e piedade; aquele frequentemente arrebatado em contemplação, este a bater à porta dos céus e a penetrá-los com a insistência das orações, e outros a sobressair em outras virtudes. Considero-os todos, digo, fervorosos, todos devotos, todos unânimes em Cristo, todos abundantes em dons celestes e em graça, como verdadeiros montes espirituais que o Senhor visita e que recebem muitas vezes o esposo que salta neles. Mas eu, que nada disto acho em mim, que posso julgar-me senão um dos montes de Gelboé, pelo qual passa ao largo, na sua ira e indignação, aquele benigníssimo visitador de todos os outros?`
    },
    {
      n: 9,
      texto: `Filhinhos, este pensamento tira a altivez dos olhos, atrai a graça, prepara para os saltos do esposo. Apliquei estas coisas a mim por vossa causa, para que também vós façais assim. Sede meus imitadores (1Cor 4,16). E não o digo agora do exercício das virtudes, ou da disciplina dos costumes, ou da glória da santidade (pois não me arrogaria temerariamente nada disto como digno de imitação); mas quero que não vos poupeis, e que vos acuseis a vós mesmos todas as vezes que surpreenderdes em vós a graça esfriando, ainda que um pouco, e a virtude desfalecendo, assim como eu me acuso a mim mesmo por coisas assim. Fazer isto é próprio do homem que se vigia atentamente a si mesmo e perscruta os seus caminhos e os seus empenhos, e em tudo desconfia sempre do vício da arrogância, para que não se insinue. Aprendi em verdade que nada é tão eficaz para merecer a graça, conservá-la e recuperá-la como ser achado em todo tempo, diante de Deus, não a presumir de si, mas a temer (cf. Rm 11,20). Feliz o homem que está sempre temeroso (Pr 28,14). Teme, pois, quando a graça te sorrir; teme quando partir; teme quando voltar de novo; e isto é estar sempre temeroso. Sucedam-se no ânimo estes três temores, conforme se sentir que a graça se digna estar presente, ou se retira ofendida, ou volta de novo aplacada. Quando está presente, teme não agir dignamente segundo ela; pois é isto que adverte o Apóstolo, dizendo: Vede que não recebais em vão a graça de Deus (2Cor 6,1); e ao discípulo: Não descuides, diz, a graça que há em ti (1Tm 4,14); e dizia de si mesmo: A graça de Deus em mim não foi vã (1Cor 15,10). Sabia aquele homem, que tinha o conselho de Deus, que descuidar o dom e não o empregar naquilo para que foi dado redunda em desprezo de quem o dá, e julgava isto uma soberba intolerável; e por isso ele mesmo se guardava deste mal com o maior cuidado e ensinava a guardar-se dele. Mas aqui se esconde ainda uma cova, que não quero que vos fique escondida, da qual o próprio espírito da soberba, tanto mais perigosamente quanto mais ocultamente, arma ciladas, como tendes no salmo, como um leão no seu covil (Sl 9,30). Pois, se não consegue impedir a ação, tenta a intenção, sugerindo e persuadindo que atribuas a ti o efeito da graça. E não duvides de que este gênero de soberba é muito mais intolerável do que o primeiro. Pois que há de mais odioso do que aquela voz com que alguns disseram: Foi a nossa mão poderosa, e não o Senhor, que fez todas estas coisas (Dt 32,27)?`
    },
    {
      n: 10,
      texto: `Se, pois, é preciso temer quando a graça permanece, que será se ela se retirar? Não será então muito mais de temer? Muito mais, sem dúvida; porque, onde te falta a graça, faltas tu. Ouve, com efeito, o que diz o doador da graça: Sem mim, diz, nada podeis fazer (Jo 15,5). Teme, pois, quando a graça te for retirada, como quem está para cair; teme e estremece, porque Deus, como sentes, está irado contigo; teme, porque a tua guarda te abandonou. E não duvides de que a causa é a soberba, ainda que não apareça, ainda que a consciência não te acuse de nada. Pois o que tu não sabes, Deus sabe; e é ele quem te julga. Pois não é aprovado quem se recomenda a si mesmo, mas aquele a quem Deus recomenda (2Cor 10,18). Acaso Deus te recomenda, quando te priva da graça? Ou acaso aquele que dá a graça aos humildes (Tg 4,6) tirará ao humilde a que lhe deu? A privação da graça é, pois, prova de soberba. Embora às vezes a graça seja retirada, ou retida, não por causa da soberba que já existe, mas daquela que existiria se não fosse retirada. Tens uma prova evidente disto no Apóstolo, que suportava contra a vontade o aguilhão da carne, não porque se exaltasse, mas para que não se exaltasse (2Cor 12,7). Mas, quer já exista, quer ainda não, a soberba será sempre a causa da graça retirada.`
    },
    {
      n: 11,
      texto: `E, se a graça, aplacada, voltar, então é preciso temer muito mais, para que não aconteça recair, segundo aquilo do Evangelho: Eis que ficaste são; vai, e não peques mais, para que não te aconteça coisa pior (Jo 5,14). Ouves que é pior recair do que cair. Por isso, crescendo o perigo, cresça também o temor. Feliz serás, se encheres o teu coração com este tríplice temor, de modo que temas pela graça recebida, mais pela perdida, e muito mais pela recuperada. Faze isto, e serás uma talha no banquete de Cristo, cheia até em cima, contendo não só duas medidas, mas três, para mereceres a bênção de Cristo, que converta as tuas águas em vinho de alegria, e a caridade perfeita lance fora o temor (1Jo 4,18).`
    },
    {
      n: 12,
      texto: `O que digo é isto: a água é o temor, porque refresca do ardor dos desejos carnais. O princípio da sabedoria, diz, é o temor do Senhor (Sl 110,10); e tens: Deu-lhe a beber a água da sabedoria salutar (Eclo 15,3). Se o temor é sabedoria, e a sabedoria é água, o temor é água; enfim: O temor do Senhor, diz, é fonte de vida (Pr 14,27). A talha é a tua mente. Cada uma, diz, levava duas ou três medidas. As três medidas são os três temores. E encheram-nas, diz, até em cima (Jo 2,6-7). Não um temor, nem dois, mas os três juntos a enchem até em cima. Teme a Deus em todo tempo e de todo o teu coração, e terás enchido a tua talha até em cima. Deus ama o dom inteiro, o afeto pleno, o sacrifício perfeito. Cuida, pois, de levar às núpcias celestes uma talha cheia, para que também de ti se diga: Encheu-o do espírito do temor do Senhor (Is 11,3). Quem teme assim nada descuida. Pois por onde entraria o descuido naquilo que está cheio? O que ainda pode receber alguma coisa não está cheio. Pela mesma razão, não se pode ao mesmo tempo temer assim e presumir de si. Pois não há por onde admitires a soberba, se estás cheio do temor do Senhor. E o mesmo se deve pensar dos outros vícios, porque todos, necessariamente, ficam excluídos pela plenitude do temor. Então, enfim, se temeres plena e perfeitamente, a caridade, pela bênção do Senhor, dará sabor às tuas águas. Pois sem a caridade o temor supõe castigo. E a caridade é o vinho que alegra o coração do homem (Sl 103,15). E a caridade perfeita lança fora o temor, para que, onde havia água, comece a haver vinho, para louvor e glória do esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
