SERMOES.sermao({
  id: 'bernardo-cantico-02',
  colecao: 'bernardo-cantico',
  ordem: 2,
  numero: 'II',
  titulo: 'Da Encarnação de Cristo, anunciada pelos patriarcas e profetas e por eles ardentissimamente esperada',
  fonte: 'De Incarnatione Christi',
  argumento: `Prometido no fim do sermão anterior, começa aqui o comentário do primeiro versículo: Beije-me com o beijo da sua boca. Bernardo ouve nele a voz dos santos antigos, cansados de promessas e de demoras, que já não querem profetas, mas o próprio Verbo. Daí a definição que dá ao centro do sermão: a boca que beija é o Verbo que assume, o beijado é a carne assumida, e o beijo é a pessoa composta de ambos — Cristo mediador.

Tradução feita do texto latino de Migne (PL 183, 789-794).`,
  pontos: [
    {
      n: 1,
      texto: `Pensando muitíssimas vezes no ardor do desejo com que os Pais suspiravam pela presença de Cristo na carne, sinto compunção e vergonha de mim mesmo; e agora a custo contenho as lágrimas, tanto me envergonham a tibieza e o torpor destes miseráveis tempos. Pois a qual de nós a graça já concedida traz tanta alegria quanto desejo a sua promessa acendia nos santos antigos? Eis quantos hão de alegrar-se nesta Natividade que em breve celebraremos! Mas oxalá se alegrem pela natividade, e não pela vaidade! É o desejo ardente deles e o afeto da sua piedosa espera que sinto respirar nesta voz: Beije-me com o beijo da sua boca (Ct 1,1). Todo aquele que naquele tempo podia ser espiritual pressentia, sem dúvida, em espírito, quanta graça havia de ser derramada naqueles lábios. Por isso, falando no desejo da sua alma, dizia: Beije-me com o beijo da sua boca — desejando de todo o coração não ficar privado de tão grande suavidade.`
    },
    {
      n: 2,
      texto: `Cada um dos perfeitos dizia: De que me servem estas bocas dos profetas, semeadoras de palavras? Antes ele mesmo, o mais formoso dos filhos dos homens (Sl 44,3), ele mesmo me beije com o beijo da sua boca. Já não dou ouvidos a Moisés: tornou-se para mim tardo de língua (Ex 4,10). Os lábios de Isaías são impuros (Is 6,5); Jeremias não sabe falar, porque é criança (Jr 1,6); e todos os profetas são mudos. Ele mesmo, aquele de quem falam, ele mesmo fale; ele mesmo me beije com o beijo da sua boca. Que já não me fale neles nem por meio deles, porque são escuras as águas nas nuvens do ar (Sl 17,12); mas ele mesmo me beije com o beijo da sua boca, e que a sua graciosa presença e as correntes da sua admirável doutrina se tornem em mim fonte de água que jorra para a vida eterna (Jo 4,14). Daquele que o Pai ungiu com óleo de alegria, de preferência aos seus companheiros (Sl 44,8), não me virá porventura uma graça mais abundante, se ele se dignar beijar-me com o beijo da sua boca? A sua palavra, viva e eficaz (Hb 4,12), é para mim um beijo: não o encontro dos lábios, que às vezes finge uma paz que não existe entre as almas, mas a infusão das alegrias, a revelação dos segredos, uma admirável e, de certo modo, indistinta fusão da luz do alto com a mente iluminada. Pois quem se une a Deus forma com ele um só espírito (1Cor 6,17). Com razão, portanto, não aceito visões nem sonhos, não quero figuras nem enigmas; até as aparições dos anjos me enfastiam. Pois também a eles o meu Jesus supera de longe em formosura e beleza. Não peço, pois, que me beije outro, nem anjo nem homem, mas ele mesmo, com o beijo da sua boca. Também não tenho a presunção de ser beijado pela sua própria boca, porque isso é felicidade única e prerrogativa singular da humanidade que o Verbo assumiu; mas, com mais humildade, peço ser beijado com o beijo da sua boca, que é comum a muitos, os quais podem dizer: E todos nós recebemos da sua plenitude (Jo 1,16).`
    },
    {
      n: 3,
      texto: `Prestai atenção. Entendamos que a boca que beija é o Verbo que assume; que o beijado é a carne que é assumida; e que o beijo, formado igualmente por quem beija e por quem é beijado, é a própria pessoa composta de ambos, o mediador entre Deus e os homens, o homem Cristo Jesus (1Tm 2,5). É por isso que nenhum dos santos ousava dizer: Beije-me com a sua boca, mas somente: com o beijo da sua boca. Reservavam essa prerrogativa àquele a quem, de modo único e uma só vez, se imprimiu a boca do Verbo, quando toda a plenitude da divindade se deu a ele corporalmente (Cl 2,9). Beijo feliz, admirável por tão espantosa condescendência, em que não é a boca que se imprime na boca, mas Deus que se une ao homem. No beijo comum, o contato dos lábios significa o abraço das almas; aqui, porém, a aliança das naturezas une o humano ao divino, pacificando o que está na terra e o que está nos céus (Cl 1,20). Pois ele é a nossa paz, que de ambos fez um só (Ef 2,14). Por este beijo, portanto, suspiravam todos os santos do tempo antigo, porque pressentiam que nele se guardavam a alegria e a exultação, e que nele estavam escondidos todos os tesouros da sabedoria e da ciência (Cl 2,3); e desejavam também eles receber da sua plenitude.`
    },
    {
      n: 4,
      texto: `Percebo que vos agrada o que digo; mas escutai também outro sentido. Mesmo antes da vinda do Salvador, os santos sabiam que Deus tinha pensamentos de paz para com a raça dos mortais (Jr 29,11). Pois ele nada faria sobre a terra sem o revelar aos seus servos, os profetas (Am 3,7). Para muitos, contudo, esta palavra permanecia escondida (Lc 18,34). Naquele tempo, na verdade, era rara a fé sobre a terra, e bem tênue a esperança, mesmo em muitos dos que aguardavam a redenção de Israel. Mas os que o sabiam de antemão anunciavam também que Cristo havia de vir na carne, e com ele a paz. Por isso diz um deles: E haverá paz na nossa terra, quando ele vier (Mq 5,5). Mais ainda: pregavam com toda a confiança, conforme o tinham recebido de Deus, que por ele os homens haviam de recuperar a graça divina. João, o precursor do Senhor, reconheceu que isso se cumprira no seu tempo, e deu testemunho, dizendo: A graça e a verdade vieram por Jesus Cristo (Jo 1,17); e todo o povo cristão experimenta agora que assim é.`
    },
    {
      n: 5,
      texto: `Entretanto, enquanto eles anunciavam a paz e o autor da paz tardava, vacilava a fé do povo, porque não havia quem o redimisse nem quem o salvasse. E assim os homens se queixavam da demora, porque aquele príncipe da paz, tantas vezes anunciado, ainda não vinha, como prometera pela boca dos seus santos profetas desde os tempos antigos (Lc 1,70). Desconfiando das promessas, exigiam o sinal da reconciliação prometida, que é o beijo — como se alguém do povo respondesse aos mensageiros da paz: Até quando nos deixareis a alma em suspenso (cf. Jo 10,24)? Há muito tempo anunciais a paz, e ela não vem; prometeis bens, e a perturbação continua. Muitas vezes e de muitos modos, os anjos anunciaram isto mesmo aos pais, e os nossos pais a nós, dizendo: Paz, paz; e não há paz (Jr 6,14). Se Deus quer que eu creia naquilo que, por tantas embaixadas, me faz saber do beneplácito da sua vontade, mas não o cumpre, que me beije com o beijo da sua boca e, com o sinal da paz, me dê a certeza da paz. Pois como posso ainda crer em palavras? É preciso que as palavras sejam confirmadas por obras. Mostre Deus que os seus mensageiros dizem a verdade, se é que são mensageiros seus, e venha ele mesmo depois deles, como tantas vezes prometeram, pois sem ele nada podem fazer. Mandou o servo com o bastão, e ainda não há voz nem vida (2Rs 4,29-31). Não me levanto, não ressuscito, não me sacudo do pó, não respiro na esperança, se o próprio profeta não descer e não me beijar com o beijo da sua boca.`
    },
    {
      n: 6,
      texto: `Acresce que aquele que se apresenta como nosso mediador junto de Deus é o Filho de Deus, e é Deus (1Tm 2,5). E que é o homem, para que Deus se dê a conhecer a ele, ou o filho do homem, para que dele faça caso (Sl 143,3)? Que confiança posso ter para ousar entregar-me a tão grande majestade? Como posso eu, que sou terra e cinza (Gn 18,27), presumir que Deus cuide de mim? Além disso, ele ama o seu Pai, mas de mim não precisa, nem necessita dos meus bens (Sl 15,2). Como hei de ter certeza, então, de que o meu mediador não está só de um dos lados? Contudo, se de fato, como dizeis, Deus decidiu ter misericórdia e pensa em mostrar-se ainda mais favorável, estabeleça um pacto de paz e firme comigo uma aliança eterna no beijo da sua boca. Para não anular o que saiu dos seus lábios (Sl 88,35), esvazie-se, humilhe-se, incline-se, e beije-me com o beijo da sua boca. Para que o mediador, pertencendo igualmente às duas partes, não seja suspeito a nenhuma delas, faça-se homem o Deus Filho de Deus, faça-se filho do homem, e dê-me certeza com este beijo da sua boca. Com segurança recebo como mediador o Filho de Deus, que reconheço como também meu. Já não me será suspeito de modo algum, pois é meu irmão e minha carne (Gn 37,27). Penso que já não poderá desprezar-me aquele que é osso dos meus ossos e carne da minha carne (Gn 2,23).`
    },
    {
      n: 7,
      texto: `Assim, pois, a antiga queixa reclamava o sacrossanto beijo, isto é, o mistério da encarnação do Verbo, enquanto a fé, cansada de tão longa e penosa espera, desfalecia, e o povo infiel, vencido pelo tédio, murmurava contra as promessas de Deus. Dizei que é invenção minha, se vós mesmos não encontrardes o mesmo nas Escrituras. Daí vêm aquelas vozes queixosas e cheias de murmuração: Manda, torna a mandar; espera, torna a esperar; um pouco aqui, um pouco ali (Is 28,10). Daí aquelas preces ansiosas e cheias de piedade: Dá a recompensa, Senhor, aos que esperam em ti, para que os teus profetas sejam achados fiéis. E ainda: Realiza, Senhor, as preces que os antigos profetas fizeram em teu nome (Eclo 36,18.17). Daí aquelas promessas ternas e cheias de consolação: Eis que o Senhor aparecerá, e não mentirá; se tardar, espera-o, porque certamente virá, e não tardará (Hab 2,3). E ainda: Está próximo o seu tempo, e os seus dias não tardarão (Is 14,1). E, na boca daquele que foi prometido: Eis que eu, diz ele, me inclino sobre vós como um rio de paz, e como uma torrente que transborda com a glória das nações (Is 66,12). Nessas palavras vê-se bem a insistência dos pregadores e a desconfiança dos povos. Assim, o povo murmurava e a fé vacilava; e, segundo a profecia de Isaías, os anjos da paz choravam amargamente (Is 33,7). Por isso, para que todo o gênero humano não perecesse no desespero com a demora de Cristo — enquanto a frágil condição mortal se julgava desprezada e desconfiava da graça, tantas vezes prometida, da sua reconciliação com Deus —, os santos, que no espírito já tinham certeza, desejavam a certeza da sua presença na carne, e com toda a insistência pediam o sinal da paz que havia de ser restaurada, por causa dos pusilânimes e dos incrédulos.`
    },
    {
      n: 8,
      texto: `Ó raiz de Jessé, erguida como sinal para os povos (Is 11,10)! Quantos reis e profetas quiseram ver-te, e não viram (Lc 10,24)! Feliz, porém, entre todos, Simeão, cuja velhice foi rica de misericórdia! Ele exultou por ver o sinal tão desejado; viu-o e alegrou-se; e, recebido o beijo da paz, foi despedido em paz, não sem antes anunciar abertamente que Jesus nascera como sinal de contradição (Lc 2,25-35). E assim foi, de fato. O sinal da paz, logo que apareceu, foi contradito, mas por aqueles que odeiam a paz: pois é paz para os homens de boa vontade (Lc 2,14), mas, para os de má vontade, pedra de escândalo e rocha de tropeço. Herodes perturbou-se, e toda Jerusalém com ele (Mt 2,3); pois veio para o que era seu, e os seus não o receberam (Jo 1,11). Felizes aqueles pastores que passavam a noite em vigília e foram julgados dignos de ver este sinal. Já então ele se escondia dos sábios e prudentes e se revelava aos pequeninos (Mt 11,25). Também Herodes quis vê-lo; mas, como não o quis com boa vontade, não o mereceu — pois era sinal de paz, dado somente aos homens de boa vontade; a Herodes e aos que são como ele não será dado outro sinal senão o do profeta Jonas (Mt 12,39). Aos pastores, porém, diz o anjo: E isto vos servirá de sinal — a vós, humildes; a vós, obedientes; a vós, que não aspirais às grandezas; a vós, que vigiais e meditais dia e noite na lei de Deus. Isto, diz ele, vos servirá de sinal. Que sinal? Aquilo que os anjos prometiam, que os povos pediam, que os profetas haviam predito: é isto que o Senhor fez agora e vos mostrou, para que nele os incrédulos recebam a fé, os pusilânimes a esperança, os perfeitos a segurança. Isto, pois, vos servirá de sinal. Sinal de quê? Do perdão, da graça, da paz — e de uma paz que não terá fim. Este é o sinal: Encontrareis um menino envolto em panos e deitado numa manjedoura (Lc 2,12). E, no entanto, é Deus que nele reconcilia o mundo consigo (2Cor 5,19). Ele morrerá pelos vossos pecados e ressuscitará para a vossa justificação, para que, justificados pela fé, tenhais paz com Deus (Rm 4,25; 5,1). Outrora o profeta propôs ao rei Acaz que pedisse este sinal de paz ao Senhor seu Deus, fosse lá no alto, fosse cá embaixo, no abismo. Mas o rei ímpio recusou (Is 7,11-12): não acreditava, o infeliz, que neste sinal as realidades mais baixas haviam de unir-se em paz às mais altas, de modo que também os que estavam na mansão dos mortos, quando o Senhor descesse para salvá-los, recebessem no beijo santo o sinal da paz; e os espíritos celestes, quando ele voltasse aos céus, participassem igualmente dele em eterna suavidade.`
    },
    {
      n: 9,
      texto: `É preciso terminar o sermão; mas, para resumir brevemente o que nele se tratou: fica claro que este santo beijo foi concedido ao mundo por duas razões necessárias — para dar fé aos fracos e para saciar o desejo dos perfeitos; e que o próprio beijo não é outro senão o mediador entre Deus e os homens, o homem Jesus Cristo, que, sendo Deus, vive e reina com o Pai e o Espírito Santo pelos séculos dos séculos. Amém.`
    }
  ]
});
