SERMOES.sermao({
  id: 'bernardo-cantico-46',
  colecao: 'bernardo-cantico',
  ordem: 46,
  numero: 'XLVI',
  titulo: 'Do estado e da composição de toda a Igreja; e de como, pela vida ativa, vivida na obediência, se chega à contemplativa',
  fonte: 'De statu et compositione totius Ecclesiae',
  argumento: `A esposa canta um epitalâmio e convida o amado ao repouso, como os discípulos de Emaús o obrigaram a ficar. Bernardo lê no versículo um retrato de toda a Igreja: o leito florido são os claustros e mosteiros; as casas, o povo cristão; as vigas de cedro, os que governam, nas duas ordens, e mantêm tudo unido com leis justas; os tetos de cipreste, o clero bem formado. Cedro e cipreste não apodrecem e têm bom perfume, como devem ser os que governam e os clérigos. E a esposa diz "nosso" não por usurpação, mas porque o amor não julga alheio nada do que é do amado.

Depois, a aplicação a cada um. Quem deseja o repouso da contemplação deve primeiro enfeitar o leito com as flores das boas obras e da obediência: querer Raquel sem passar por Lia é inverter a ordem. E é impudência convidar o Senhor da pureza para uma consciência cheia de urtigas de rebeldia. Cada alma é também uma casa: as vigas são o temor, a paciência, a perseverança e a caridade; os carismas extraordinários são madeira rara e perigosa de lavrar, e Bernardo aconselha a forrar os tetos com madeira mais modesta e mais firme — a paz, a bondade, a alegria no Espírito Santo.

Tradução feita do texto latino de Migne (PL 183, 1004-1008).`,
  pontos: [
    {
      n: 1,
      texto: `O nosso leito é florido, as vigas das nossas casas são de cedro, os nossos tetos de cipreste (Ct 1,15-16). Ela canta um epitalâmio, descrevendo com belas palavras o leito e os aposentos nupciais. Convida o esposo ao repouso. Pois isto é melhor: repousar e estar com Cristo (cf. Fl 1,23). Mas é necessário sair em busca de ganhos, por causa dos que se hão de salvar. Agora, porém, tendo achado, como julga, a ocasião, anuncia que o quarto está adornado e, como que apontando com o dedo o leito, convida, como disse, o amado ao repouso; e, como os que iam para Emaús, não suportando o ardor do coração, arrasta-o para a hospedaria da mente e obriga-o a passar a noite consigo (Lc 24,29.32); e diz com Pedro: Senhor, é bom estarmos aqui (Mt 17,4).`
    },
    {
      n: 2,
      texto: `Busquemos agora o que estas coisas contêm espiritualmente. Na Igreja, o leito em que se repousa são, a meu ver, os claustros e os mosteiros, onde se vive em sossego, longe dos cuidados do mundo e das preocupações da vida. E este leito se mostra florido quando o modo de viver e a vida dos irmãos resplandecem, como que salpicados de flores perfumadas, com os exemplos e as instituições dos padres. Entende por casas as assembleias do povo cristão, que os que estão postos no alto — os príncipes cristãos de ambas as ordens — mantêm firmemente unidas, como as vigas às paredes, impondo-lhes leis justas, para que, vivendo cada um segundo a sua lei ou a sua vontade, não se separem de si mesmos como paredes inclinadas e muros derrubados (cf. Sl 61,4), e assim toda a estrutura do edifício desabe e se desfaça. E os tetos, que pendem firmemente das vigas e adornam magnificamente as casas, julgo que designam os costumes mansos e disciplinados de um clero bem formado, e os ofícios devidamente desempenhados. Pois como se hão de manter as ordens dos clérigos e as suas funções, se não forem sustentadas pelo benefício e pela generosidade dos príncipes, como por vigas, e protegidas pelo seu poder?`
    },
    {
      n: 3,
      texto: `E, se as vigas são descritas de cedro e os tetos de cipreste, é sem dúvida porque estas espécies de madeira têm por natureza alguma coisa que convém às ordens mencionadas. O cedro, como é madeira que não apodrece, perfumada e de grande altura, indica bastante bem que homens convém tomar para fazerem as vezes de vigas. É preciso, pois, que os que são postos sobre os outros sejam fortes e constantes, e também pacientes na esperança, erguendo o cume da mente para as coisas do alto; e que, espalhando em toda parte o bom perfume da sua fé e do seu modo de viver, possam dizer com o Apóstolo: Pois somos para Deus o bom perfume de Cristo em todo lugar (2Cor 2,15). Do mesmo modo o cipreste, madeira igualmente de bom perfume e que também não apodrece, mostra que todo clérigo deve ser de vida e de fé incorruptas, para ser com razão destinado à beleza da casa e ao ornato dos tetos. Pois está escrito: À tua casa convém a santidade, Senhor, por longos dias (Sl 92,5). Aí se exprimem tanto a beleza da santidade como a perseverança de uma graça que não falha. É preciso, pois, que o homem tomado para ornamento e beleza da casa seja adornado de bons costumes; e, embora esteja sempre dentro, tenha bom testemunho também dos de fora (cf. 1Tm 3,7). Há ainda outras coisas na natureza destas madeiras que convêm ao que se expõe espiritualmente; mas omito-as, por brevidade.`
    },
    {
      n: 4,
      texto: `Note-se como é belo que todo o estado da Igreja esteja compreendido num só versículo breve: a autoridade dos prelados, a beleza do clero, a disciplina do povo, o repouso dos monges. Quando tudo isto está bem, a santa mãe Igreja alegra-se em contemplá-lo; e então o oferece também ao olhar do amado, referindo tudo à bondade dele, como autor de tudo, sem atribuir nada a si mesma. Pois, se diz "nosso" e "nossas", não é sinal de usurpação, mas de amor: porque, pela confiança de uma caridade imensa, não julga alheio a si nada do que é daquele a quem muito ama. Pois não julga que deva ser afastada da convivência do esposo nem da participação no seu repouso, ela que sempre costumou buscar não o que é seu, mas o que é dele; e é esta a razão por que ousou declarar comuns a si e ao esposo tanto o leito como as casas. Pois disse: O nosso leito; e: As vigas das nossas casas; e: Os nossos tetos — associando-se ousadamente na posse àquele a quem não duvida estar unida no amor. Não é assim a alma que ainda não renunciou à vontade própria, mas se deita à parte e mora à parte; ou antes, não à parte, mas vive dissolutamente com meretrizes — falo das concupiscências da carne —, com as quais dissipa os seus bens e a parte da herança que pediu que lhe separassem (Lc 15,12-13).`
    },
    {
      n: 5,
      texto: `Mas tu, que ouves ou lês estas vozes do Espírito Santo, julgas poder aplicar a ti alguma destas coisas que se dizem, e reconhecer em ti mesmo alguma coisa da felicidade da esposa, que o próprio Espírito canta neste poema de amor, para que não se diga também de ti que ouves a sua voz e não sabes de onde vem nem para onde vai (cf. Jo 3,8)? Eis que talvez também tu desejes o repouso da contemplação, e fazes bem; só não te esqueças das flores com que lês que o leito da esposa está salpicado. Cuida, pois, também tu, de rodear igualmente o teu com as flores das boas obras, e de fazer que o exercício das virtudes preceda o santo repouso, como a flor precede o fruto. De outro modo, quererás cochilar num ócio bem regalado, se desejares repousar sem te teres exercitado, e, desprezada a fecundidade de Lia, quiseres deleitar-te só nos abraços de Raquel. E é também uma ordem invertida exigir o prêmio antes do mérito e tomar o alimento antes do trabalho, quando diz o Apóstolo: Quem não trabalha não coma (2Ts 3,10). Pelos teus mandamentos alcancei entendimento, diz (Sl 118,104), para que saibas que o gosto da contemplação de modo nenhum é devido senão à obediência aos mandamentos. Não julgues, pois, que, por amor do teu próprio repouso, se possa prejudicar de algum modo as obras da santa obediência ou as tradições dos anciãos. De outro modo, o esposo não dormirá contigo num mesmo leito, sobretudo naquele que, em lugar das flores da obediência, salpicaste de cicutas e urtigas de desobediência. Por isso não ouvirá as tuas orações e, chamado, não virá; pois não se entregará ao desobediente quem tanto ama a obediência que preferiu morrer a não obedecer. E não aprova o ócio vazio da tua contemplação quem diz pelo profeta: Cansei-me de suportar (Jr 6,11), indicando o tempo em que, exilado do céu e da pátria do supremo repouso, operou a salvação no meio da terra. Antes, temo que te envolva também a ti aquela temível sentença que troveja assim contra a infidelidade dos judeus: Não suportarei as vossas luas novas, os sábados e as outras festas; e ainda: As vossas calendas e as vossas solenidades, a minha alma as odeia; tornaram-se para mim um peso (Is 1,13-14). E o profeta chorará sobre ti e dirá: Viram-na os inimigos e zombaram dos seus sábados (Lm 1,7). Pois por que o inimigo não zombaria do que o amado rejeita?`
    },
    {
      n: 6,
      texto: `Admiro-me muito da impudência de alguns que estão entre nós, que, depois de nos terem perturbado a todos com a sua singularidade, irritado com a sua impaciência e desprezado com a sua teimosia e rebeldia, ousam ainda convidar, com toda a insistência das orações, o Senhor de toda pureza para o leito tão imundo da sua consciência. Mas, quando estenderdes as mãos, diz, desviarei de vós os meus olhos; e, quando multiplicardes a oração, não ouvirei (Is 1,15). Pois quê? O leito não é florido, antes é fétido; e tu arrastas para lá o Rei da glória? Fazes isso para que ele repouse, ou para que te acuse? O centurião, cuja fé perfuma todo o Israel, pede-lhe que não entre debaixo do seu teto, por causa da sua indignidade (Mt 8,8.10); e tu, sujo da imundície de tantos vícios, o obrigas a entrar na tua casa? O príncipe dos apóstolos clama: Afasta-te de mim, Senhor, porque sou um homem pecador (Lc 5,8); e tu dizes: Entra na minha casa, Senhor, porque sou santo? Sede todos unânimes na oração, diz; amai os irmãos (1Pd 3,8; 2,17). E o vaso de eleição: Levantando mãos puras, diz, sem ira e sem contenda (1Tm 2,8). Vês como concordam entre si o príncipe dos apóstolos e o doutor dos gentios, e como falam com o mesmo espírito da paz e da tranquilidade de ânimo que deve ter quem ora? Continua, pois, a estender o dia inteiro as mãos para Deus, tu que o dia inteiro molestas os irmãos, combates a concórdia e te separas da unidade!`
    },
    {
      n: 7,
      texto: `E que queres que eu faça?, perguntas. Sem dúvida, que primeiro purifiques a consciência de toda mancha de ira, de contenda, de murmuração e de inveja; e que te apresses a lançar fora da morada do coração tudo o que se sabe ser contrário à paz dos irmãos ou à obediência aos anciãos. Depois, que te rodeies das flores de todas as boas ações e dos empenhos louváveis, e dos perfumes das virtudes; isto é, cuida de pensar em tudo o que é verdadeiro, tudo o que é pudico, tudo o que é justo, tudo o que é santo, tudo o que é amável, tudo o que é de boa fama, em tudo o que é virtude e louvor da disciplina (Fl 4,8), e de te exercitar nisso. Para um leito assim, chamarás o esposo com segurança; pois, quando o introduzires, poderás dizer também tu com verdade: O nosso leito é florido — exalando a consciência o perfume da piedade, e da paz, e da mansidão, e da justiça, e da obediência, e da alegria, e da humildade. E isto quanto ao leito.`
    },
    {
      n: 8,
      texto: `E reconheça-se casa espiritual de Deus cada um que já não anda na carne, mas no espírito: Pois o templo de Deus é santo, diz, e esse templo sois vós (1Cor 3,17). Cuidai, pois, irmãos, deste edifício espiritual que vós sois, para que, quando começar a crescer para o alto, não vacile e desabe, por não estar apoiado e travado com madeiras fortes. Cuidai, digo, de lhe dar vigas que não apodreçam nem se movam: o temor casto do Senhor, aquele que permanece pelos séculos dos séculos (Sl 18,10); a paciência, da qual está escrito que a paciência dos pobres não perecerá para sempre (Sl 9,19); também a longanimidade, que, perseverando sem se dobrar sob qualquer peso da construção, se prolonga pelos séculos infinitos da vida feliz, como diz o Salvador no Evangelho: Quem perseverar até o fim será salvo (Mt 10,22); e, acima de tudo, a caridade, que nunca acaba (cf. 1Cor 13,8), porque o amor, diz, é forte como a morte, e o ciúme duro como o inferno (Ct 8,6). Procurai depois pôr por baixo destas vigas e prender a elas outras madeiras igualmente preciosas e belas — quem as tiver à mão — para a obra dos tetos, para beleza da casa: isto é, a palavra de sabedoria ou de ciência, a profecia, o dom das curas, a interpretação das línguas (cf. 1Cor 12,8-10) e outras coisas assim, que, como se sabe, são mais próprias para ornamento do que necessárias para a salvação. Sobre estas coisas não tenho preceito, mas dou conselho (cf. 1Cor 7,25): como é certo que madeiras deste gênero se procuram com trabalho, se acham com dificuldade e se lavram com perigo — pois a nossa terra, sobretudo nestes tempos, as produz raramente —, aconselho e advirto que não se busquem com muito empenho; mas que se preparem os tetos com outras madeiras, que, ainda que pareçam menos esplêndidas, não se mostram menos sólidas, e além disso se possuem com mais facilidade e mais segurança.`
    },
    {
      n: 9,
      texto: `Oxalá também eu tenha em abundância aquelas madeiras de que o jardim do Esposo, que é a Igreja, está copiosamente povoado: a paz, a bondade, a benignidade, a alegria no Espírito Santo, compadecer-se com alegria, dar com simplicidade, alegrar-se com os que se alegram, chorar com os que choram (Rm 12,8.15)! Não julgarias bastante e abundantemente adornada — no que toca aos tetos — a casa que visses forrada com tais madeiras, em quantidade suficiente e bem dispostas? Senhor, amei a beleza da tua casa (Sl 25,8). Dá-me sempre, peço-te, estas madeiras, com as quais te apresente sempre adornado o quarto da consciência — digo da minha consciência e da dos outros. Com elas ficarei contente. E haverá quem queira seguir o meu conselho nisto, porque creio que também tu ficarás contente; o resto deixo-o aos santos apóstolos e aos homens apostólicos. Também vós, caríssimos, ainda que não tenhais aquelas madeiras, se tendes estas, tende confiança; aproximai-vos com toda confiança da pedra suprema, angular, escolhida, preciosa; e sobre o fundamento dos apóstolos e dos profetas, também vós, como pedras vivas, sede edificados como casas espirituais, sacerdócio santo, para oferecer sacrifícios espirituais agradáveis a Deus, por Jesus Cristo (Ef 2,19-22; 1Pd 2,4-9), esposo da Igreja, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
