SERMOES.sermao({
  id: 'bernardo-cantico-20',
  colecao: 'bernardo-cantico',
  ordem: 20,
  numero: 'XX',
  titulo: 'Dos três modos do amor com que amamos a Deus',
  fonte: 'De triplici modo dilectionis, qua Deum diligimus',
  argumento: `As medidas prometidas no fim do sermão anterior. Bernardo procura-as primeiro em Cristo, que amou com doçura, com sabedoria e com força — doce ao tomar a carne, prudente ao guardar-se da culpa, forte ao suportar a morte — e só então as devolve ao cristão, ligando-as às três partes do mandamento: de todo o coração, de toda a alma, com todas as forças.

Pedro é o exemplo do percurso: amava de todo o coração quando quis impedir a paixão, e ouviu que não entendia as coisas de Deus; passou depois a amar de toda a alma; e só amou com todas as forças diante do Sinédrio. No fim vem a página sobre o amor carnal a Cristo — a imagem do Homem-Deus diante de quem ora —, que Bernardo louva como dom do Espírito e ao mesmo tempo apresenta como degrau.

Tradução feita do texto latino de Migne (PL 183, 867-872).`,
  pontos: [
    {
      n: 1,
      texto: `Que o sermão comece por palavras do Mestre: Quem não ama o Senhor Jesus, seja anátema (1Cor 16,22). Deve ser muito amado por mim aquele por quem existo, vivo e tenho juízo. Se lhe sou ingrato, sou também indigno. Merece a morte, sem dúvida, quem se recusa a viver para ti, Senhor Jesus — e já está morto; quem não tem juízo para ti, desatina; e quem cuida de existir a não ser por ti, nada vale e nada é. Enfim, que é o homem, senão por te teres dado a conhecer a ele? (Sl 143,3) Por causa de ti mesmo, ó Deus, fizeste todas as coisas; e quem quer existir para si e não para ti começa a não ser nada entre tudo o que existe. Teme a Deus e guarda os seus mandamentos: isto é, diz a Escritura, o homem todo (Ecl 12,13). Se, pois, isto é o homem todo, sem isto o homem todo é nada. Inclina para ti, ó Deus, este pouco que te dignaste fazer de mim; e da minha vida mísera recebe, peço-te, o resto dos meus anos. E, pelos que perdi ao vivê-los, porque vivi perdidamente, não desprezes, ó Deus, um coração contrito e humilhado. Os meus dias declinaram como sombra (Sl 101,12) e passaram sem fruto. É impossível trazê-los de volta: que te apraza ao menos que os repasse diante de ti, na amargura da minha alma. Quanto à sabedoria, todo o meu desejo está diante de ti, e o propósito do meu coração: se houvesse alguma em mim, eu a guardaria para ti. Mas tu, ó Deus, conheces a minha insensatez (Sl 68,6) — a não ser que talvez seja já sabedoria eu reconhecê-la, e isso por dom teu. Aumenta-o em mim, que não sou ingrato por esse pequeno dom, mas ando inquieto pelo que falta. Por tudo isso te amo, pois, quanto posso.`
    },
    {
      n: 2,
      texto: `Mas há uma coisa que mais me move, mais me aperta, mais me acende. Acima de tudo, bom Jesus, o que te torna amável para mim é o cálice que bebeste, a obra da nossa redenção. Isto, sem mais, reclama facilmente para si todo o nosso amor. É isto que atrai a nossa devoção com mais doçura, que a exige com mais justiça, que a prende mais apertado e que a comove com mais força. Muito trabalhou nisso o Salvador; e em toda a construção do mundo o seu autor não tomou sobre si tanto cansaço. Ali, enfim, ele disse e as coisas foram feitas; mandou, e foram criadas (Sl 32,9). Aqui, porém, teve de suportar quem o contradisse no que dizia, quem o espiava no que fazia, quem zombou dele nos tormentos e quem o insultou na morte. Vede como amou. Acrescenta que esse amor não foi pagamento, mas dádiva. Pois quem lhe deu primeiro, para que lhe seja retribuído? (Rm 11,35) Mas, como diz o evangelista São João: Não fomos nós que amamos a Deus, mas foi ele que nos amou primeiro (1Jo 4,10). Amou até os que ainda não existiam; e mais: passa a amar também os que lhe resistem, conforme o testemunho de Paulo: Quando ainda éramos inimigos, fomos reconciliados com Deus pelo sangue do seu Filho (Rm 5,10). De outro modo, se não tivesse amado inimigos, ainda não teria amigos; assim como ainda não existiriam aqueles a quem assim ama, se não tivesse amado os que ainda não existiam.`
    },
    {
      n: 3,
      texto: `E amou com doçura, com sabedoria e com força. Chamaria doce o ter-se revestido de carne; prudente, o ter-se guardado da culpa; forte, o ter suportado a morte. Pois aqueles a quem visitou na carne não os amou de modo algum carnalmente, mas na prudência do espírito; porque Cristo Senhor é espírito diante da nossa face (Lm 4,20), e nos ama com zelo de Deus, não de homem — e com um zelo mais são, decerto, do que o do primeiro Adão pela sua Eva. Assim, aos que buscou na carne amou-os no espírito e redimiu-os com poder. Está cheio de toda a doçura da suavidade ver feito homem aquele que criou o homem. Mas, ao separar com prudência a natureza da culpa, também afastou com poder a morte da natureza. Ao tomar a carne, desceu até mim; ao evitar a culpa, cuidou de si; ao aceitar a morte, deu satisfação ao Pai: amigo doce, conselheiro prudente, ajudador forte. A este me confio sem receio: ele quer salvar-me, sabe como e pode. A quem procurou, também chamou pela sua graça; lançará fora quem vem a ele? E não temo força nem fraude alguma que me possa arrancar da sua mão; pois ele venceu a morte, que vence tudo, e enganou com arte mais santa a serpente que enganou o mundo: mais prudente que ela, mais poderoso que a morte. Tomou a verdade da carne, mas só a semelhança do pecado: naquela oferecendo ao fraco uma consolação bem doce, e nesta escondendo com prudência o laço com que enganaria o diabo. E, para nos reconciliar com o Pai, enfrenta e subjuga a morte com força, derramando o seu sangue como preço da nossa redenção. Se, pois, não tivesse amado com doçura, aquela majestade não teria vindo procurar-me no cárcere; mas juntou ao afeto a sabedoria, com que enganaria o tirano, e juntou também a paciência, com que aplacaria a Deus Pai, ofendido. São estes os modos que vos prometera; e apresentei-os primeiro em Cristo, para que os tivésseis por mais recomendáveis.`
    },
    {
      n: 4,
      texto: `Aprende de Cristo, ó cristão, como se ama a Cristo. Aprende a amar com doçura, a amar com prudência, a amar com força: com doçura, para que não nos desviem do amor do Senhor as seduções; com prudência, para que não nos desviem os enganos; com força, para que não nos desvie o peso da opressão. Para não te deixares levar pela glória do mundo ou pelos prazeres da carne, seja Cristo, a sabedoria, mais doce para ti do que eles; para não seres seduzido pelo espírito da mentira e do erro, brilhe para ti Cristo, a verdade; para não te cansares nas adversidades, conforte-te Cristo, poder de Deus. Que a caridade inflame o teu zelo, que a ciência lhe dê forma, que a constância o firme. Seja fervoroso, seja atento, seja invencível. Não tenha tibieza, não lhe falte discernimento, não seja medroso. E vê se porventura estas três coisas não te foram já dadas na lei, quando Deus disse: Amarás o Senhor teu Deus de todo o teu coração, de toda a tua alma e de todas as tuas forças (Dt 6,5). Parece-me — se não houver nesta tríplice distinção outro sentido mais próprio — que o amor do coração se refere a certo ardor do afeto; o amor da alma, à diligência ou ao juízo da razão; e o amor das forças, à constância ou ao vigor do ânimo. Ama, pois, o Senhor teu Deus com todo o afeto do coração, e por inteiro; ama com toda a vigilância e o cuidado da razão; ama também com todas as forças, de modo a não teres medo de morrer por amor dele, como está escrito adiante: Porque o amor é forte como a morte, e o ciúme é duro como a mansão dos mortos (Ct 8,6). Seja o Senhor Jesus suave e doce ao teu afeto, contra as seduções — más, ainda que doces — da vida carnal; e vença a doçura à doçura, como um prego expulsa outro prego. Mas seja também luz que vai à frente do entendimento e guia da razão: não só para evitares as armadilhas da fraude herética e guardares a pureza da fé das astúcias delas, mas também para teres cuidado de evitar, no teu modo de viver, uma veemência excessiva e sem discernimento. Seja também forte e constante o teu amor, sem ceder aos terrores nem sucumbir aos trabalhos. Amemos, pois, com afeto, com cuidado e com vigor, sabendo que o amor do coração, a que chamamos afetuoso, sem aquele a que chamamos da alma é doce, sim, mas fácil de enganar; e que este, sem aquele que é das forças, é racional, mas frágil.`
    },
    {
      n: 5,
      texto: `E vê em exemplos claros que é assim como dizemos. Como os discípulos levassem a mal o que o próprio Mestre lhes dissera sobre a sua partida, ao subir aos céus, ouviram: Se me amásseis, teríeis alegria de que eu vá para o Pai (Jo 14,28). Então? Não amavam aquele cuja partida os fazia sofrer? Amavam de um certo modo, e não amavam. Amavam com doçura, mas com pouca prudência; amavam carnalmente, mas não racionalmente; amavam, enfim, de todo o coração, mas não de toda a alma. O amor deles ia contra a salvação deles; por isso ele dizia: Convém-vos que eu vá (Jo 16,7) — censurando o juízo, não o afeto. E, quando falava da sua morte futura e Pedro, que o amava com ternura, tentou opor-se, ao contê-lo com aquela repreensão de que vos lembrais, que outra coisa censurou nele senão a imprudência? Afinal, que quer dizer «não entendes as coisas de Deus» (Mc 8,32-33) senão: «não amas com sabedoria, por seguires um afeto humano contra um desígnio divino»? E chamou-lhe Satanás, porque, ainda que sem saber, se opunha à salvação quem impedia o Salvador de morrer. Por isso, uma vez corrigido, quando depois ouviu repetir aquela palavra triste, já não o proibiu de morrer, mas prometeu morrer com ele. Não cumpriu, porém, porque ainda não chegara ao terceiro grau, em que se ama com todas as forças. Já estava ensinado a amar de toda a alma, mas ainda era fraco: bem instruído, mas pouco socorrido; não ignorava o mistério, mas tinha medo do martírio. Não era ainda, decerto, aquele amor forte como a morte, o que sucumbiu diante da morte; mas foi depois, quando, revestido do poder do alto segundo a promessa de Jesus Cristo, começou enfim a amar com tanta força que, proibido pelo Sinédrio de pregar o nome santo, respondeu com firmeza aos que o proibiam: É preciso obedecer a Deus antes que aos homens (At 5,29). Só então amou com todas as forças, quando por amor não poupou nem a própria vida. Pois ninguém tem maior amor do que dar a vida pelos amigos (Jo 15,13); e, se então ainda não a deu, já a expôs. Amar de todo o coração, de toda a alma e com todas as forças é, pois, não se deixar levar por lisonjas, não se deixar seduzir por enganos e não se deixar quebrar por injúrias.`
    },
    {
      n: 6,
      texto: `E repara que o amor do coração é de certo modo carnal, porque move o coração humano sobretudo para a carne de Cristo e para o que Cristo fez ou mandou na carne. Quem está cheio desse amor comove-se facilmente com qualquer palavra sobre essas coisas. Nada ouve com mais gosto, nada lê com mais empenho, nada recorda mais vezes, nada medita com mais doçura. Daí tira com que engordar os holocaustos das suas orações, como da gordura de um novilho cevado. Diante de quem ora está a imagem sagrada do Homem-Deus: ora nascendo, ora mamando, ora ensinando, ora morrendo, ora ressuscitando, ora subindo ao céu. E tudo o que assim lhe venha à mente necessariamente ou aperta o ânimo no amor das virtudes, ou expulsa os vícios da carne, afugenta as seduções e acalma os desejos. Creio que foi esta a razão principal por que o Deus invisível quis ser visto na carne e portar-se como homem entre os homens: para atrair primeiro todos os afetos dos carnais — que não sabiam amar senão carnalmente — ao amor salutar da sua carne, e assim os levar aos poucos até o amor espiritual. Não estavam ainda neste grau os que diziam: Eis que deixamos tudo e te seguimos? (Mt 19,27) Foi só pelo amor da presença corporal que deixaram tudo — tanto que nem suportavam ouvir com calma uma palavra sobre a paixão e a morte que haviam de salvá-los, nem puderam depois olhar para a glória da subida senão com grande tristeza. É o que ele lhes dizia: Porque vos falei estas coisas, a tristeza encheu o vosso coração (Jo 16,6). Assim, por ora, só com a graça da sua carne presente os tinha desprendido do amor de toda carne.`
    },
    {
      n: 7,
      texto: `Depois, porém, mostrava-lhes um grau mais alto do amor, ao dizer: É o espírito que vivifica; a carne de nada aproveita (Jo 6,64). Creio que já tinha subido a ele quem dizia: Ainda que tenhamos conhecido Cristo segundo a carne, agora já não o conhecemos assim (2Cor 5,16). E talvez estivesse também nele o profeta, ao dizer: Cristo Senhor é espírito diante da nossa face. Pois o que acrescenta — À sua sombra viveremos entre as nações (Lm 4,20) — parece-me ter dito em nome dos que começam: que ao menos descansem à sombra os que não se sentem fortes bastante para suportar o ardor do sol, e que se alimentem da doçura da carne enquanto ainda não conseguem receber o que é do Espírito de Deus. Pois tenho por sombra de Cristo a sua carne, com a qual também Maria foi coberta de sombra (Lc 1,35), para que, interpondo-se ela, o ardor e o esplendor do Espírito se temperassem para ela. Console-se, pois, por enquanto, na devoção à carne, quem ainda não tem o Espírito que vivifica do modo como o têm aqueles que dizem: Cristo Senhor é espírito diante da nossa face; e também: Ainda que tenhamos conhecido Cristo segundo a carne, agora já não o conhecemos assim. Pois, de resto, nem mesmo na carne se ama a Cristo sem o Espírito Santo — ainda que não naquela plenitude. A medida desta devoção é esta: que aquela suavidade ocupe o coração inteiro e o reclame todo para si, tirando-o do amor de toda carne e de toda sedução carnal. É isto amar de todo o coração. De outro modo, se prefiro à carne do meu Senhor algum parentesco ou algum prazer da minha própria carne — de sorte que por isso cumpra menos aquilo que ele, vivendo na carne, me ensinou por palavras e por exemplo —, não fica claro que não amo de todo o coração, tendo-o dividido: uma parte gasto na carne dele, outra desvio para a minha? Pois ele diz: Quem ama o pai ou a mãe mais do que a mim não é digno de mim; e quem ama o filho ou a filha mais do que a mim não é digno de mim (Mt 10,37). Em poucas palavras, pois: amar de todo o coração é pôr abaixo do amor da sua carne sacrossanta tudo o que agrada na carne própria ou alheia. E aqui incluo igualmente a glória do mundo, porque a glória do mundo é glória da carne, e não há dúvida de que são carnais os que se deleitam com ela.`
    },
    {
      n: 8,
      texto: `Ainda que esta devoção à carne de Cristo seja um dom, e grande dom do Espírito, eu chamaria carnal a este amor — em comparação, claro está, com aquele outro, em que já não se saboreia tanto o Verbo feito carne quanto o Verbo sabedoria, o Verbo justiça, o Verbo verdade, o Verbo santidade, bondade, poder, e o que mais assim se possa dizer. E Cristo é tudo isso: ele que se fez para nós, da parte de Deus, sabedoria, justiça, santificação e redenção (1Cor 1,30). Parece-te que estão dispostos do mesmo modo aquele que se compadece com piedade de Cristo padecente, se comove e se enternece facilmente à lembrança do que ele sofreu, e se alimenta da doçura dessa devoção e se fortalece para tudo o que é saudável, honesto e piedoso; e aquele outro, que arde sempre de zelo pela justiça, que zela em toda parte pela verdade, que se apaixona pelo estudo da sabedoria; a quem são caras a santidade de vida e a disciplina dos costumes; cujos costumes se envergonham da ostentação, abominam a maledicência, não conhecem inveja, detestam a soberba, e não só fogem de toda glória humana, mas a enjoam e a desprezam; que com a maior veemência abominam e perseguem em si toda impureza da carne e do coração; e que, como por natureza, rejeitam tudo o que é mau e abraçam o que é bom? Se comparas as disposições de um e de outro, não fica claro que o primeiro, em comparação com este, ama de certo modo carnalmente?`
    },
    {
      n: 9,
      texto: `É bom, contudo, esse amor carnal, pelo qual se exclui a vida carnal e se despreza e se vence o mundo. E nele se progride quando se torna também racional; e ele se aperfeiçoa quando se faz também espiritual. É racional quando, em tudo o que se deve pensar de Cristo, a razão da fé se mantém tão firme que nenhuma aparência de verdade, nenhuma cilada herética ou diabólica a desvia, nem por pouco, da pureza do sentir da Igreja; e também quando, no modo de viver, se guarda aquela cautela de não ultrapassar o limite do discernimento por nenhuma superstição, nenhuma leviandade, nem pela veemência de um espírito que se julga mais fervoroso. E já dissemos acima que isto é amar a Deus de toda a alma. E, se ainda se acrescentar tal vigor do Espírito que ajuda, que a justiça nunca seja abandonada por medo de trabalhos, de tormentos ou mesmo da morte, então ama-se também com todas as forças, e esse é o amor espiritual. Creio que este nome convém especialmente a este amor, pela prerrogativa da plenitude do espírito em que ele sobressai. E baste isto quanto ao que diz a esposa: Por isso as jovenzinhas te amaram em demasia (Ct 1,2). No que vem a seguir, digne-se abrir-nos os tesouros da sua misericórdia aquele mesmo que os guarda, Jesus Cristo, Senhor nosso, que vive e reina com o Pai, na unidade do Espírito Santo, Deus, por todos os séculos dos séculos. Amém.`
    }
  ]
});
