SERMOES.sermao({
  id: 'bernardo-cantico-74',
  colecao: 'bernardo-cantico',
  ordem: 74,
  numero: 'LXXIV',
  titulo: 'Das visitas do Verbo esposo, quão ocultamente se fazem à alma santa; o que Bernardo declara com humildade e pudor, pelo seu próprio exemplo, para edificação dos seus',
  fonte: 'De visitationibus Verbi sponsi',
  argumento: `"Volta", diz a esposa. Bernardo aplica o versículo ao Verbo e à alma, confessando que o faz a pedido dos monges e com temor. O Verbo, que é Deus e enche todas as coisas, não se move de lugar: vem e vai no sentir da alma, que, quando sente a graça, reconhece a presença e, quando não, se queixa da ausência e o chama de volta com o desejo, que é a sua voz. Como fez com os discípulos de Emaús e com os apóstolos no mar, ele finge afastar-se para ser retido.

Depois Bernardo fala de si, "como insensato": o Verbo veio muitas vezes a ele, mas nunca sentiu a sua entrada nem a sua saída; não entrou pelos sentidos, nem veio de fora nem de dentro, pois está acima do mais alto e abaixo do mais baixo do seu ser. Reconheceu-o só pelos efeitos: o coração movido, os vícios em fuga, as faltas ocultas descobertas, os costumes emendados, o espírito renovado; e, quando ele se retira, tudo esfria como panela tirada do fogo. Por isso repete: "Volta". Mas que venha cheio de graça e de verdade, com a alegria do filhote e os olhos da gazela: a graça sem a verdade fez Judas e o anjo soberbo, que perdeu a sabedoria na sua beleza; e a verdade sem a graça só entristece.

Tradução feita do texto latino de Migne (PL 183, 1139-1144).`,
  pontos: [
    {
      n: 1,
      texto: `Volta, diz (Ct 2,17). É claro que não está presente aquele a quem chama de volta; mas que esteve presente, e não muito antes, pois parece ser chamado de volta enquanto ainda se vai. Chamá-lo de volta assim fora de tempo é sinal de um grande amor de uma parte e de uma grande amabilidade da outra. Quem são estes cultores da caridade, tão incansáveis seguidores do negócio do amor, dos quais a um persegue, e a outra impele, um amor tão inquieto? A mim, como me lembro da minha promessa, cabe aplicar esta passagem ao Verbo e à alma; mas confesso que, para fazê-lo dignamente, ainda que só um pouco, preciso da ajuda do próprio Verbo. E, certamente, este sermão conviria mais a quem tivesse mais experiência e mais conhecimento íntimo do santo e secreto amor; mas não posso faltar ao meu ofício, nem de modo nenhum aos vossos desejos. Vejo o meu perigo, e não me previno; sois vós que me obrigais. Obrigais-me, de fato, a andar em coisas grandes e maravilhosas acima de mim (cf. Sl 130,1). Ai! Como receio ouvir logo: Por que narras tu as minhas delícias e tomas o meu segredo na tua boca (cf. Sl 49,16)? Ouvi-me, contudo, a mim, homem que treme de falar e não pode calar. Talvez o meu próprio temor desculpe a minha ousadia; mais ainda a vossa edificação, se a houver. E talvez se levem em conta também estas lágrimas. Volta, diz. Bem. Ele se ia, e é chamado de volta. Quem me desvendará o mistério desta mudança? Quem me explicará dignamente o ir e o voltar do Verbo? Acaso o esposo age com leviandade (cf. 2Cor 1,17)? De onde, e para onde, pode vir ou ir de novo aquele que enche todas as coisas (cf. Jr 23,24)? Enfim, que movimento de lugar pode ter aquele que é espírito (cf. Jo 4,24)? Ou, finalmente, que movimento, de qualquer gênero que seja, atribuis àquele que é Deus? Pois ele é inteiramente imutável.`
    },
    {
      n: 2,
      texto: `Mas quem pode entender estas coisas, entenda (cf. Mt 19,12). Nós, porém, caminhando com cautela e simplicidade na exposição da palavra sagrada e mística, sigamos o costume da Escritura, que com as nossas palavras fala da sabedoria escondida no mistério (cf. 1Cor 2,7); que dá a entender Deus, representando-o com os nossos afetos; que, por meio de semelhanças conhecidas das coisas sensíveis, como em taças de matéria mais vil, dá a beber às mentes humanas as coisas preciosas, as coisas desconhecidas e invisíveis de Deus (cf. Rm 1,20). Sigamos, pois, também nós o costume da palavra casta (cf. Sl 11,7), e digamos que o Verbo de Deus, Deus esposo da alma, vem à alma quando quer, e de novo a deixa; contanto que entendamos que isto se faz no sentir da alma, e não por um movimento do Verbo. Por exemplo: quando sente a graça, reconhece a presença; quando não, queixa-se da ausência e procura de novo a presença, dizendo com o Profeta: A minha face te buscou; a tua face, Senhor, eu buscarei (Sl 26,8). E como não havia de buscar? Pois, tirado a ela um esposo tão doce, não lhe apetecerá, entretanto, não digo desejar, mas nem sequer pensar em outra coisa. Resta, pois, que busque com empenho o ausente e chame de volta o que se vai. Assim, pois, é chamado de volta o Verbo; e é chamado de volta pelo desejo da alma, mas daquela alma a quem uma vez concedeu a sua suavidade. Não é o desejo uma voz? E bem forte. Enfim: O Senhor ouviu o desejo dos pobres, diz (Sl 9,38). Quando, pois, o Verbo se vai, a única e contínua voz da alma, entretanto, é o seu contínuo desejo, como um único e contínuo "Volta", até que ele venha.`
    },
    {
      n: 3,
      texto: `E agora dá-me uma alma que o Verbo esposo costume visitar com frequência, a quem a familiaridade tenha dado ousadia, o gosto fome, o desprezo de todas as coisas repouso: e eu atribuo-lhe sem hesitar a voz e também o nome de esposa; e não julgaria de modo nenhum alheia a ela a passagem que temos entre mãos. É uma alma assim, com efeito, que aqui se apresenta falando. Pois, chamando-o de volta, mostra sem dúvida que mereceu a sua presença, embora não o gozo pleno dela. De outro modo, não o teria chamado de volta, mas simplesmente chamado. E a palavra de quem chama de volta é: Volta. E talvez se tenha retirado para ser chamado de volta com mais ânsia e retido com mais força. Pois também certa vez fingia ir mais longe, não porque o quisesse, mas porque queria ouvir: Fica conosco, Senhor, porque já é tarde (Lc 24,28-29). E, outra vez, andando sobre o mar, enquanto os apóstolos navegavam e se cansavam a remar, como que querendo passar adiante deles, nem então o queria, mas antes provar a fé e suscitar a oração. Enfim, como diz o evangelista: Perturbaram-se e gritaram, pensando que era um fantasma (Mc 6,48-49). Assim, esta espécie de piedosa simulação — ou antes, de salutar disposição — que o Verbo feito corpo por vezes mostrou então corporalmente, não cessa o Verbo, que é espírito, de a praticar assiduamente, a seu modo espiritual, com a alma que lhe é devota. Passando, quer ser retido; indo-se, quer ser chamado de volta. Pois este não é um Verbo irrevogável. Vai e volta conforme o seu beneplácito, como quem visita de madrugada e de repente põe à prova (cf. Jó 7,18). E o ir é para ele, de certo modo, uma disposição da sua providência; o voltar, porém, é sempre por sua vontade; mas uma coisa e outra estão cheias de juízo. A razão disto, porém, só ele a conhece.`
    },
    {
      n: 4,
      texto: `Ora, é certo que se dão na alma estas alternâncias do Verbo que vai e volta, como ele diz: Vou, e venho a vós (Jo 14,28); e ainda: Um pouco, e não me vereis; e mais um pouco, e me vereis (Jo 16,17). Ó pouco e pouco! Ó pouco tão longo! Senhor piedoso, chamas pouco ao tempo em que não te veremos? Salvo o respeito pela palavra do meu Senhor: é longo, e demasiado longo. Mas uma coisa e outra são verdadeiras: é pouco para os méritos, e longo para os desejos. Tens uma e outra coisa no profeta: Se tardar, diz, espera-o, porque certamente virá, e não tardará (Hab 2,3). Como não tardará, se tardar, senão porque o que basta para o mérito não basta para o desejo? A alma que ama é levada pelos desejos, arrastada pelas ânsias, não faz caso dos méritos, fecha os olhos à majestade e abre-os ao deleite, pondo a sua confiança na salvação e agindo nela com confiança (cf. Sl 11,6). Enfim, sem temor e sem pudor chama de volta o Verbo e reclama com confiança as suas delícias, chamando-o, com a liberdade de costume, não Senhor, mas amado: Volta, meu amado; e acrescenta: Sê semelhante à gazela e ao filhote dos cervos sobre os montes de Betel. Mas disto, depois.`
    },
    {
      n: 5,
      texto: `Agora, porém, suportai um pouco da minha insensatez (cf. 2Cor 11,1). Quero dizer — pois também isto prometi — como se passam comigo estas coisas. Não convém, é verdade (cf. 2Cor 12,1). Mas que eu me descubra, contanto que seja proveitoso; e, se vós aproveitardes, terei consolo para a minha insensatez; se não, confessarei a minha insensatez. Confesso que também a mim veio o Verbo — falo como insensato (cf. 2Cor 11,17) —, e muitas vezes. E, embora tenha entrado em mim muitas vezes, algumas vezes não senti quando entrou. Senti que estava presente, lembro-me de que esteve; às vezes pude até pressentir a sua entrada, mas senti-la, nunca, nem tampouco a sua saída. Pois de onde veio à minha alma, ou para onde foi quando de novo a deixou, e até por onde entrou ou saiu, confesso que ainda agora o ignoro, segundo aquela palavra: Não sabes de onde vem nem para onde vai (Jo 3,8). E não admira, porque é ele aquele a quem se disse: E as tuas pegadas não serão conhecidas (Sl 76,20). Certamente não entrou pelos olhos, porque não tem cor; nem pelos ouvidos, porque não fez som; nem pelas narinas, porque não se mistura com o ar, mas com a mente — não impregnou o ar, mas o fez; nem pela garganta, porque não foi mastigado nem bebido; nem pelo tato o percebi, porque não é palpável. Por onde, então, entrou? Ou talvez nem sequer tenha entrado, porque não veio de fora? Pois não é nenhuma das coisas que estão fora. Mas também não veio de dentro de mim, porque é bom, e eu sei que em mim não há bem (cf. Rm 7,18). Subi também ao que há de mais alto em mim: e eis que o Verbo se elevava ainda acima disso. Desci também, explorador curioso, ao que há de mais baixo em mim: e mesmo assim se encontrava ainda mais abaixo. Se olhei para fora, descobri que estava fora de tudo o que há de exterior em mim; se para dentro, também ele estava mais dentro. E conheci que é verdade o que tinha lido: nele vivemos, nos movemos e existimos (At 17,28); mas bem-aventurado aquele em quem ele está, que vive para ele, que é movido por ele.`
    },
    {
      n: 6,
      texto: `Perguntas, então, sendo os seus caminhos tão absolutamente impenetráveis (cf. Rm 11,33), como sei que está presente? É vivo e eficaz (Hb 4,12): e, logo que entrou, despertou a minha alma adormecida; moveu, abrandou e feriu o meu coração, que era duro, de pedra e doente. Começou também a arrancar e a destruir, a edificar e a plantar (cf. Jr 1,10), a regar o que estava seco, a iluminar o que estava escuro, a abrir o que estava fechado, a inflamar o que estava frio, e ainda a endireitar o que era tortuoso e a aplanar os caminhos ásperos (cf. Is 40,4), de modo que a minha alma bendissesse o Senhor, e tudo o que há em mim o seu santo nome (cf. Sl 102,1). Assim, pois, entrando em mim algumas vezes, o Verbo esposo nunca deu a conhecer a sua entrada por nenhum sinal: nem pela voz, nem pela aparência, nem pelo passo. Enfim, não o percebi por nenhum movimento seu, nem por nenhum dos meus sentidos notei que se tivesse insinuado no meu íntimo: só pelo movimento do coração, como disse antes, compreendi a sua presença; pela fuga dos vícios e pela repressão dos afetos carnais, notei a força do seu poder; pelo exame e pela repreensão das minhas faltas ocultas, admirei a profundidade da sua sabedoria; pela emenda, por pequena que fosse, dos meus costumes, experimentei a bondade da sua mansidão; pela renovação e reforma do espírito da minha mente (cf. Ef 4,23), isto é, do meu homem interior, percebi de algum modo a formosura da sua beleza; e pela contemplação de todas estas coisas juntas fiquei pasmado com a imensidão da sua grandeza (cf. Sl 150,2).`
    },
    {
      n: 7,
      texto: `Mas, como todas estas coisas, quando o Verbo se retira, logo começam a ficar entorpecidas e frias, numa espécie de languidez, como se tirasses o fogo de uma panela que ferve — e este é para mim o sinal da sua partida —, é necessário que a minha alma fique triste até que ele volte de novo e o meu coração se aqueça outra vez dentro de mim (cf. Sl 38,4), como de costume; e seja este o indício da sua volta. Tendo tal experiência do Verbo, que admira que também eu tome para mim a voz da esposa para o chamar de volta quando se ausenta, eu que sou levado por um desejo, se não igual, ao menos em parte semelhante? Enquanto eu viver, será familiar para mim, para chamar de volta o Verbo, a palavra de quem chama de volta, que é: Volta. E, quantas vezes me escapar, tantas o repetirei; e não cessarei de clamar, como que pelas costas de quem se vai, com o desejo ardente do coração, que volte e me restitua a alegria da sua salvação (cf. Sl 50,14), que me restitua a si mesmo. Confesso-vos, filhos: nada mais me agrada, entretanto, enquanto não está presente aquele que é o único que me agrada. E peço isto: que não venha vazio, mas cheio de graça e de verdade (Jo 1,14), segundo o seu costume, como ontem e anteontem. Nisto me parece que se pode mostrar a semelhança da gazela e do filhote: pois a verdade tem os olhos da gazela, e a graça a alegria do filhote.`
    },
    {
      n: 8,
      texto: `Uma e outra coisa me são necessárias: a verdade, à qual não posso esconder-me; e a graça, à qual não quero esconder-me. De outro modo, sem uma ou outra, a visita não será plena, pois a severidade daquela, sem esta, pode parecer pesada, e a alegria desta, sem aquela, dissoluta. Amarga é a verdade sem o tempero da graça; assim como, sem o freio da verdade, a própria devoção é leviana e sem medida, e muitas vezes até insolente. A quantos não aproveitou ter recebido a graça, porque não receberam também o contrapeso da verdade? Por isso se compraziam nela mais do que convinha, não temendo o olhar da verdade, não atendendo à maturidade da gazela, mas entregando-se de todo à leveza e à alegria do filhote. Daí aconteceu que foram privados da graça em que tinham querido exultar privadamente; e a eles se pôde dizer, ainda que tarde: Ide, pois, e aprendei o que significa (cf. Mt 9,13): Servi ao Senhor com temor, e exultai nele com tremor (Sl 2,11). Enfim, uma alma santa tinha dito na sua abundância: Não serei abalado para sempre; e de repente sentiu que o Verbo tinha desviado dela a face, e que ela não só estava abalada, mas até perturbada (Sl 29,7-8); e assim aprendeu na tristeza que precisava, com o dom da devoção, também do peso da verdade. Portanto, a plenitude da graça não está só na graça, mas nem só na verdade. De que serve saber o que deves fazer, se não te é dado também querer fazê-lo? E de que serve, se quiseres, mas de modo nenhum puderes? Quantos conheci por experiência que ficaram mais tristes depois de conhecer a verdade, e tanto mais porque já não lhes era lícito recorrer à desculpa da ignorância, sabendo e não fazendo aquilo a que a Verdade exortava!`
    },
    {
      n: 9,
      texto: `Sendo assim, nenhuma das duas basta sem a outra. Disse pouco: nem sequer convém. Como sabemos isto? Para quem sabe fazer o bem e não o faz, diz, isso é pecado (Tg 4,17); e ainda: O servo que conhece a vontade do seu senhor e não age de acordo com ela levará muitos açoites (Lc 12,47). Isto, porém, quanto à parte da verdade. E quanto à da graça? Está escrito: E depois do bocado entrou nele Satanás (Jo 13,27). Fala de Judas, que, tendo recebido o dom da graça, por não andar na verdade com o Mestre da verdade, ou antes, com a Verdade mestra, deu lugar em si ao diabo (cf. Ef 4,27). Ouve ainda: Alimentou-os com a flor do trigo, e saciou-os com o mel da rocha (Sl 80,17). A quem? Os inimigos do Senhor mentiram-lhe (Sl 80,16). Aqueles que alimentou com mel e com a flor do trigo, esses lhe mentiram, feitos inimigos, porque não juntaram a verdade à graça. Deles tens noutro lugar: Os filhos estrangeiros mentiram-me; os filhos estrangeiros envelheceram e coxearam, afastando-se das suas veredas (Sl 17,45-46). E como não haviam de coxear, contentes com o único pé da graça, sem lhe juntar a verdade? Será, pois, o tempo deles para sempre (Sl 80,16), como o do seu príncipe, que também ele não permaneceu na verdade, mas foi mentiroso desde o princípio (Jo 8,44); e por isso ouviu: Perdeste a sabedoria na tua beleza (Ez 28,17). Não quero uma beleza que me tire a sabedoria.`
    },
    {
      n: 10,
      texto: `Perguntas que beleza é essa tão nociva e tão perniciosa? A tua. Ainda estás sem entender (cf. Mt 15,16)? Ouve mais claramente: a beleza particular, a própria. Não censuramos o dom, mas o uso. Enfim, se reparaste, não se diz que ele perdeu a sabedoria na beleza, mas na sua beleza. E, se não me engano, a única beleza do anjo e da alma é ela mesma, a sabedoria. Pois que é esta ou aquele sem a sabedoria, senão matéria bruta e disforme? Por ela, pois, ele não só foi formado, mas também foi formoso. Mas perdeu-a quando a fez sua: de modo que perder a sabedoria na sua beleza não é outra coisa senão perdê-la na sua própria sabedoria. A causa é a apropriação. Ter sido sábio para si mesmo, não ter dado glória a Deus, não ter dado graças pela graça, não ter andado nela segundo a verdade, mas tê-la torcido para a sua própria vontade: eis por que a perdeu; ou antes, eis o que foi perdê-la. Pois ter assim é perder. Se Abraão, diz, foi justificado pelas obras, tem de que se gloriar, mas não diante de Deus (Rm 4,2). E eu digo: Então não estou em segurança; perdi tudo o que tenho fora de Deus. Pois que há de tão perdido como o que vive exilado fora de Deus? Que é a morte, senão a privação da vida? Assim, a perdição não é outra coisa senão o afastamento de Deus. Ai de vós, que sois sábios aos vossos próprios olhos e prudentes diante de vós mesmos (Is 5,21)! De vós se diz: Destruirei a sabedoria dos sábios e rejeitarei a prudência dos prudentes (1Cor 1,19). Perderam a sabedoria, porque a sua sabedoria os perdeu. Que não perderam os que também eles se perderam? Ou não estão perdidos aqueles que Deus não conhece?`
    },
    {
      n: 11,
      texto: `E as virgens insensatas — que, penso eu, não são insensatas por outra razão senão porque, dizendo-se sábias, se tornaram tolas (cf. Rm 1,22) —, essas, digo, têm de ouvir de Deus: Não vos conheço (Mt 25,12). E igualmente aqueles que usurparam para a sua glória a graça dos milagres hão de ouvir também: Nunca vos conheci (Mt 7,23); para que por isto fique bem claro que a graça não aproveita onde não há verdade na intenção, mas antes prejudica. E no esposo estão uma e outra coisa. Enfim: A graça e a verdade vieram por Jesus Cristo, diz João Batista (Jo 1,17). Se, pois, o Senhor Jesus Cristo — pois ele é o Verbo de Deus, o esposo da alma — bater à minha porta com qualquer uma delas sem a outra, entrará, certamente, não como esposo, mas como juiz. Longe disso! Que tal não aconteça! Não entre em juízo com o seu servo (cf. Sl 142,2). Entre pacífico, entre alegre e jovial; mas entre também maduro e sério, e, com um rosto mais severo de verdade, reprimindo em mim a insolência, purifique a minha alegria. Entre como o filhote que salta, como a gazela que olha em volta: que, fingindo não ver, salte por cima da culpa, e, compadecendo-se, olhe para a pena. Entre como quem desce dos montes de Betel, festivo e resplandecente, e como quem procede do Pai, suave e manso, ele que não desdenha ser chamado e tornar-se esposo da alma que o busca, sendo Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
