SERMOES.sermao({
  id: 'bernardo-cantico-01',
  colecao: 'bernardo-cantico',
  ordem: 1,
  numero: 'I',
  titulo: 'Sobre o próprio título do livro: «Cântico dos cânticos de Salomão»',
  fonte: 'De ipso titulo libri',
  argumento: `Bernardo abre a pregação justificando por que aos monges se pode servir alimento sólido, e por que o Cântico só se dá a quem já passou pelo Eclesiastes e pelos Provérbios. Depois detém-se no próprio título: por que Cântico dos cânticos, e não simplesmente cântico, como os de Moisés, de Débora, de Judite e dos profetas.`,
  pontos: [
    {
      n: 1,
      texto: `A vós, irmãos, devem-se dizer coisas diversas das que se dizem aos que vivem no século — ou, ao menos, dizê-las de outro modo. Àqueles, com efeito, dá de beber leite e não alimento sólido quem guarda a norma do Apóstolo no ensinar. Pois que aos espirituais se deve servir alimento mais sólido, ele mesmo o ensina com o próprio exemplo, ao dizer: Falamos não com palavras aprendidas da sabedoria humana, mas com as ensinadas pelo Espírito, exprimindo realidades espirituais em termos espirituais; e ainda: Falamos sabedoria entre os perfeitos (1Cor 2,13.6) — e tais confio que sois vós, a não ser que em vão vos ocupeis já há tanto tempo com os estudos celestes, exercitados nos sentidos e meditando dia e noite na lei de Deus. Preparai, pois, a garganta, não para o leite, mas para o pão. Há um pão em Salomão, e por sinal muito alvo e saboroso: refiro-me ao livro que se intitula Cântico dos cânticos. Que seja trazido, se vos apraz, e partido.`
    },
    {
      n: 2,
      texto: `Pois, quanto às palavras do Eclesiastes, estais suficientemente instruídos, se não me engano, pela graça de Deus, para conhecer e desprezar a vaidade deste mundo. E os Provérbios? Acaso a vossa vida e os vossos costumes não foram bastante corrigidos e formados segundo a doutrina que neles se encontra? Portanto, já provados ambos aqueles pães, que recebestes emprestados da despensa do amigo, aproximai-vos também deste terceiro, para que proveis, talvez, coisas melhores. Com efeito, sendo dois os males que, ou sozinhos ou mais que todos, guerreiam contra a alma — a saber, o vão amor do mundo e o supérfluo amor de si mesmo —, sabe-se que aqueles dois livros vêm ao encontro de uma e de outra peste: um, com a enxada da disciplina, cortando o que há de torto nos costumes e de supérfluo na carne; o outro, com a luz da razão, descobrindo argutamente em toda glória do mundo o falso colorido da vaidade e distinguindo-o com verdade daquilo que é sólido. Por fim, a todos os empenhos humanos e desejos mundanos preferiu temer a Deus e observar os seus mandamentos. E com razão. Pois o primeiro é o princípio da verdadeira sabedoria; o segundo, a sua consumação — se é que tendes por certo que a verdadeira e consumada sabedoria não é outra coisa senão apartar-se do mal e fazer o bem; e, do mesmo modo, que ninguém pode afastar-se perfeitamente do mal sem o temor de Deus, nem existe obra boa alguma fora da observância dos mandamentos.`
    },
    {
      n: 3,
      texto: `Expulsos, pois, os dois males pela leitura dos dois livros, chega-se já convenientemente a este discurso sagrado e contemplativo, o qual, sendo fruto de ambos, de modo nenhum deve ser confiado senão a mentes e ouvidos sóbrios. De outra sorte, antes que a carne esteja domada pelo exercício da disciplina e submetida ao espírito, antes que sejam desprezados e lançados fora a pompa e o fardo do século, indignamente ousam os impuros tomar para si a leitura santa. Pois, assim como em vão a luz envolve olhos cegos ou fechados, assim o homem animal não percebe as coisas que são do Espírito de Deus (1Cor 2,14). Com efeito, o Espírito Santo, que é de disciplina, foge do fingimento (Sb 1,5) — isto é, da vida incontinente; nem jamais terá parte alguma com a vaidade do mundo, sendo ele o Espírito da verdade (Jo 14,17). Pois que sociedade há entre a sabedoria que vem do alto e a sabedoria do mundo, que é loucura diante de Deus (1Cor 3,19), ou a sabedoria da carne, que também ela é inimiga de Deus (Rm 8,7)? Penso, porém, que já não terá do que murmurar contra nós aquele amigo que nos chega de viagem, uma vez que houver tomado também este terceiro pão.`
    },
    {
      n: 4,
      texto: `Mas quem o partirá? Presente está o pai de família: reconhecei o Senhor no partir do pão. Pois quem mais seria idôneo? Certamente não me arrogaria eu tal coisa temerariamente. Olhai para mim de tal modo que de mim nada espereis. Também eu sou um dos que esperam, mendigando eu mesmo, convosco, o alimento da minha alma, o sustento do espírito. Na verdade, pobre e necessitado, bato à porta daquele que abre e ninguém fecha, por causa do profundíssimo mistério destas palavras. Os olhos de todos esperam em ti, Senhor. Os pequeninos pediram pão; não há quem o parta para eles: isso se espera da tua bondade. Ó piedosíssimo, parte o teu pão aos que têm fome — com as minhas mãos, se te dignas, mas com a tua força.`
    },
    {
      n: 5,
      texto: `Dize-nos, por favor: por quem, de quem, a quem se diz Beije-me com o beijo da sua boca (Ct 1,1)? E que princípio é este, tão repentino, feito de súbito como que do meio de um discurso? Pois irrompe em palavras como se antes tivesse posto alguém a falar e em seguida introduzisse esta personagem — quem quer que seja a que reclama o beijo — a responder-lhe. Depois, se pede, ou ordena, que a beije não sei quem, por que expressamente e por seu nome com a boca, e com a sua boca? Como se os que beijam costumassem oferecer outra coisa que não a boca, ou boca alheia e não antes a própria. E nem sequer diz isto: «Beije-me com a sua boca», mas algo ainda mais insólito: com o beijo, diz, da sua boca. Agradável é, sem dúvida, esta linguagem, que toma o seu início de um beijo; e certa face acariciante da Escritura facilmente move e atrai à leitura, de modo que deleita investigar, ainda que com trabalho, o que nela se esconde, e a dificuldade da busca não cansa onde a suavidade da expressão afaga. Mas a quem não tornaria bem atento um princípio destes, sem princípio, e a novidade da locução num livro antigo? Donde consta que esta obra foi composta não pelo engenho humano, mas pela arte do Espírito, de sorte que, embora difícil de entender, seja deleitável de investigar.`
    },
    {
      n: 6,
      texto: `Mas então? Havemos de passar por cima do título? Não convém omitir nem sequer um iota (Mt 5,18), uma vez que nos é mandado recolher até as migalhas dos fragmentos, para que não se percam (Jo 6,12). O título é este: Começam os Cânticos dos cânticos de Salomão. Observa, antes de tudo, que o nome do Pacífico — que é Salomão — convém ao princípio do livro, que começa pelo sinal da paz, isto é, pelo beijo. E adverte, ao mesmo tempo, que por tais princípios só são convidadas a entender esta Escritura as mentes pacíficas, aquelas que já são capazes de se livrar das perturbações dos vícios e dos tumultos das preocupações.`
    },
    {
      n: 7,
      texto: `Em seguida, não julgues ocioso também isto: que a inscrição não traz simplesmente Cânticos, mas Cântico dos cânticos. Pois li muitos cânticos nas Escrituras e não me lembro de que algum deles seja assim chamado. Israel cantou um poema ao Senhor por haver escapado igualmente à espada e ao jugo do Faraó, libertado e ao mesmo tempo vingado, de modo admirável, pelo duplo serviço do mar. Contudo, o que cantou não se chamou Cântico dos cânticos, mas, se bem me recordo, diz a Escritura: Cantou Israel este poema ao Senhor (Ex 15,1). Cantou também Débora (Jz 5,1), cantou Judite (Jt 16,1), cantou a mãe de Samuel (1Sm 2,1); cantaram ainda alguns profetas, e de nenhum deles se lê que tenha chamado ao seu cântico Cântico dos cânticos. Na verdade, hás de achar que todos, se não me engano, cantaram por algum bem recebido, seu ou dos seus: por exemplo, por uma vitória alcançada, por um perigo evitado, ou pelo benefício de haverem obtido alguma coisa desejada. Assim cantaram muitos, cada um por seus motivos, para não serem achados ingratos aos benefícios divinos, conforme aquilo: Ele te louvará, quando lhe tiveres feito bem (Sl 48,19). Este rei Salomão, porém, singular em sabedoria, sublime em glória, abundante em bens, seguro na paz, não consta que houvesse carecido de nada disso, cujo recebimento lhe desse motivo para entoar tais coisas. Nem a própria Escritura parece indicar, em parte alguma, algo semelhante a seu respeito.`
    },
    {
      n: 8,
      texto: `Por isso, divinamente inspirado, cantou os louvores de Cristo e da Igreja, a graça do sagrado amor e os mistérios do eterno matrimônio; e ao mesmo tempo exprimiu o desejo da alma santa e, exultando em espírito, compôs o canto do epitalâmio em agradável eulógio, ainda que figurado. Sem dúvida velava também ele, à maneira de Moisés, o próprio rosto (Ex 34,33), talvez não menos resplandecente nesta parte, porque naquele tempo ninguém havia — ou raro havia — que pudesse contemplar de rosto descoberto tal glória. Julgo, portanto, que por sua excelência foi este canto nupcial assinalado com semelhante título, de modo que com razão se chame, de modo único, Cântico dos cânticos, assim como também aquele a quem se canta foi chamado, de modo único, Rei dos reis e Senhor dos senhores (1Tm 6,15).`
    },
    {
      n: 9,
      texto: `Quanto a vós, porém, se atentardes para a vossa experiência: acaso, na vitória com que a vossa fé venceu o mundo, e na vossa saída do lago da miséria e do lodo da borra, não cantastes também vós ao Senhor um cântico novo, porque fez maravilhas? E de novo, quando ele acrescentou pôr primeiro os vossos pés sobre a pedra e dirigir os vossos passos, penso que também então, pela novidade de vida concedida, foi posto na vossa boca um cântico novo, um hino ao nosso Deus. E quando, arrependidos vós, não somente vos perdoou os pecados, mas ainda vos prometeu prêmios — não cantastes muito mais, alegres na esperança dos bens futuros, nos caminhos do Senhor, porque grande é a glória do Senhor? E se a algum de vós porventura se iluminou alguma vez algo de fechado ou obscuro nas Escrituras, então é de todo necessário que, pelo alimento recebido do pão celeste, o som de quem se banqueteia acaricie os ouvidos divinos em voz de exultação e de louvor. Mas também nos exercícios e nas guerras de cada dia — que a nenhuma hora faltam, da parte da carne, do mundo e do diabo, aos que vivem piamente em Cristo, pois experimentais sem cessar em vós mesmos que a vida do homem sobre a terra é milícia (Jó 7,1) — é necessário renovar cânticos diários pelas vitórias alcançadas. Cada vez que se vence uma tentação, ou se subjuga um vício, ou se evita um perigo iminente, ou se descobre o laço de quem arma ciladas, ou se cura de uma vez e perfeitamente alguma paixão antiga e inveterada da alma, ou enfim se obtém, por dom de Deus, uma virtude longamente desejada e muitas vezes pedida — que outra coisa ressoa senão, conforme o profeta, a ação de graças e a voz do louvor (Is 51,3), e a cada benefício bendiz-se a Deus em seus dons? De outro modo, quando vier o exame, será tido por ingrato quem não puder dizer a Deus: Os teus preceitos eram para mim cânticos no lugar da minha peregrinação (Sl 118,54).`
    },
    {
      n: 10,
      texto: `Julgo que reconheceis já em vós mesmos aqueles que, no saltério, se chamam não Cântico dos cânticos, mas Cânticos dos Degraus, porque a cada um dos vossos progressos, segundo as subidas que cada qual dispôs no seu coração, se devem entoar cânticos próprios, para louvor e glória daquele que faz progredir. De outra maneira, não vejo como se cumpra aquele versículo: Voz de exultação e de salvação nas tendas dos justos (Sl 117,15); ou ainda aquela belíssima e saudabilíssima exortação do Apóstolo: Cantando salmos, hinos e cânticos espirituais, e salmodiando em vossos corações ao Senhor (Ef 5,19).`
    },
    {
      n: 11,
      texto: `Mas há um cântico que, pela dignidade e suavidade que só a ele pertencem, com razão sobrepuja todos os que mencionamos, e quaisquer outros que existam; e com direito eu o chamaria Cântico dos cânticos, porque ele é o fruto de todos os demais. Tal cântico só a unção o ensina, só a experiência o aprende. Reconheçam-no os que o experimentaram; inflamem-se os inexperientes no desejo, não tanto de conhecer quanto de experimentar. Pois não é ruído da boca, mas júbilo do coração; não é som de lábios, mas movimento de alegrias; consonância de vontades, não de vozes. Não se ouve fora, nem ressoa em público: só o ouvem a que canta e aquele para quem se canta, isto é, a esposa e o esposo. É, com efeito, canto nupcial, que exprime os castos e alegres abraços das almas, a concórdia dos costumes e a caridade dos afetos, mútua e concorde.`
    },
    {
      n: 12,
      texto: `De resto, cantá-lo ou ouvi-lo não é para a alma ainda pueril e neófita, recém-convertida do século, mas para a mente já adiantada e instruída, que com seus progressos, sob o impulso de Deus, de tal modo já cresceu que chegou à idade perfeita e, de certa maneira, aos anos núbeis — anos, digo, de méritos, não de tempo —, tornada apta às núpcias do Esposo celeste, tal como afinal se descreverá mais plenamente em seu lugar. Mas passa a hora em que a pobreza e a observância regular nos urgem a sair para o trabalho das mãos. Amanhã, em nome do Senhor, prosseguiremos o que havíamos começado acerca do beijo, pois o sermão de hoje nos desobrigou do título.`
    }
  ]
});
