SERMOES.sermao({
  id: 'bernardo-cantico-05',
  colecao: 'bernardo-cantico',
  ordem: 5,
  numero: 'V',
  titulo: 'Dos quatro gêneros de espíritos: o do animal, o do homem, o do anjo e o de Deus',
  fonte: 'De quatuor generibus spirituum',
  argumento: `A pergunta deixada em aberto no sermão anterior — como pode ter boca, mão e pés aquele que é espírito — leva Bernardo a percorrer os quatro gêneros de espíritos. Todos precisam de corpo, cada um à sua maneira: o do animal para existir, o nosso para aprender, o do anjo para servir. Só Deus não precisa de nada, e é essa a conclusão a que o sermão caminha.

Sobre a natureza dos corpos angélicos, Bernardo interrompe a discussão com uma frase rara nele: confesso que não sei.

Tradução feita do texto latino de Migne (PL 183, 798-803).`,
  pontos: [
    {
      n: 1,
      texto: `Conheceis os quatro gêneros de espíritos: o do animal, o nosso, o do anjo e aquele que criou os outros três. De todos eles, não há um só que não precise de um corpo, ou ao menos de algo semelhante a um corpo, seja por causa de si, seja por causa de outro, seja pelas duas razões — com a única exceção daquele a quem toda criatura, tanto corporal como espiritual, com razão confessa e diz: Tu és o meu Deus, porque não precisas dos meus bens (Sl 15,2). E o primeiro deles precisa de tal modo do corpo que sem ele não consegue subsistir de modo algum: quando o animal morre, aquele espírito deixa ao mesmo tempo de dar vida e de viver. Nós, ao contrário, vivemos depois do corpo; mas, para chegar àquilo que nos faz viver felizes, nenhum caminho se abre para nós senão pelo corpo. Entendeu isto quem dizia: As coisas invisíveis de Deus se contemplam pela inteligência, por meio das coisas que foram feitas (Rm 1,20). Pois essas mesmas coisas feitas, isto é, as corporais e visíveis, só chegam ao nosso conhecimento depois de percebidas pelos sentidos do corpo. Portanto, a criatura espiritual que nós somos precisa do corpo, porque sem ele não alcança de modo algum aquele conhecimento que recebeu como único degrau para as realidades cuja contemplação a torna feliz. Se alguém me objetar aqui o caso das crianças batizadas, que saem do corpo sem nenhum conhecimento das coisas corporais e que, no entanto, cremos passarem à vida bem-aventurada, respondo em poucas palavras: isso lhes é dado pela graça, e não pela natureza. E que tenho eu a ver com o milagre de Deus, se estou tratando daquilo que é natural?`
    },
    {
      n: 2,
      texto: `Que também os espíritos celestes precisem de corpos, disso nos dá certeza, acima de tudo, aquela sentença verdadeira e verdadeiramente divina: Não são todos eles espíritos encarregados de um serviço, enviados em favor dos que hão de receber a herança da salvação (Hb 1,14)? De que modo, então, cumpririam o seu serviço sem corpo, sobretudo junto dos que vivem num corpo? Além disso, ir de um lado para outro e passar de um lugar a outro é próprio dos corpos; e que os anjos façam isso com frequência, prova-o uma autoridade tão conhecida quanto indiscutível. Daí vem que apareceram aos patriarcas, entraram em suas casas, comeram e lavaram os pés. Assim, tanto o espírito inferior como o superior precisam do próprio corpo, mas apenas para com ele ajudarem, e não para serem ajudados.`
    },
    {
      n: 3,
      texto: `O animal, na verdade, serve por dever de servidão, e ajuda apenas nas necessidades temporais e corporais; por isso aquele espírito passa com o tempo e acaba com o corpo. Pois o servo não permanece para sempre na casa (Jo 8,35), ainda que aqueles que bem se servem dele convertam todo o uso desta servidão temporal em ganho para a eternidade. O anjo, ao contrário, cuida e se esforça por exercer, na liberdade do espírito, um ofício de piedade, mostrando-se aos mortais ministro pronto e diligente dos bens futuros, como a quem um dia há de ser seu concidadão para sempre e coerdeiro da alegria do alto. Um, pois, para servir por obrigação; o outro, para socorrer por piedade: ambos, sem dúvida, precisam do próprio corpo para ajudar. Pois em que o corpo os ajude a eles, ao menos quanto ao progresso para a eternidade, não vejo. O espírito irracional, ainda que também ele recolha pelo corpo as coisas corporais, será por acaso ajudado pelo seu corpo a ponto de, pelas coisas corporais e sensíveis que por ele percebe, chegar a progredir até as espirituais e inteligíveis? Sabe-se, no entanto, que, com o seu serviço corporal e temporal, ele ajuda a alcançá-las aqueles que convertem todo o uso das coisas temporais em fruto das eternas, usando deste mundo como se dele não usassem (1Cor 7,31).`
    },
    {
      n: 4,
      texto: `O espírito celeste, porém, sem o auxílio do corpo e sem olhar para aquilo que pelo corpo se percebe, basta-se com a proximidade e o vigor da sua própria natureza para apreender as realidades mais altas e penetrar as mais íntimas. Não foi isso que o Apóstolo entendeu quando, ao dizer que as coisas invisíveis de Deus se contemplam pela inteligência por meio das coisas que foram feitas, logo acrescentou: a partir da criatura do mundo? Sem dúvida, porque a partir da criatura do céu não é assim. Pois aquilo a que este espírito, envolto em carne e habitante da terra, se esforça por chegar aos poucos e por degraus, progredindo pela consideração das coisas sensíveis, aquele outro, habitante dos céus, alcança com toda a rapidez e facilidade, pela sutileza e pela elevação que lhe são naturais, sem se apoiar em nenhum sentido corporal, sem o auxílio de nenhum membro do corpo, sem nada aprender da observação de coisa corpórea alguma. Pois por que havia de procurar nos corpos os sentidos espirituais, se os lê no livro da vida sem contestação e os entende sem dificuldade? Por que se cansaria, com o suor do rosto, em separar o grão da palha, o vinho das uvas e o azeite da borra, se tem tudo isso à mão, e em abundância? Quem iria mendigar o sustento por casas alheias, tendo pão de sobra na sua? Quem se daria ao trabalho de cavar um poço e de procurar penosamente nas entranhas da terra as veias de água, se uma fonte viva lhe corre espontânea, com água limpa e farta? Portanto, nem o espírito do animal nem o do anjo são de algum modo ajudados pelo próprio corpo para alcançar aquilo que faz feliz a criatura espiritual: um, porque por natureza é incapaz de recebê-lo; o outro, porque, pela prerrogativa de uma glória mais alta, disso não precisa.`
    },
    {
      n: 5,
      texto: `Quanto ao espírito do homem, que ocupa um lugar intermediário entre o mais alto e o mais baixo, é manifesto que precisa do corpo para as duas coisas, a ponto de sem ele não poder nem progredir, nem ser útil a outro. Pois, para não falar dos demais membros do corpo e das suas funções: de que modo, pergunto eu, sem língua ensinarias quem te ouve, ou sem ouvidos entenderias quem te ensina?`
    },
    {
      n: 6,
      texto: `Assim, uma vez que sem o apoio do corpo nem o espírito do animal consegue pagar a dívida da sua condição servil, nem a criatura espiritual e celeste cumprir o seu ministério de piedade, nem a alma racional prover à salvação, tanto do próximo como de si mesma, fica claro que todo espírito criado precisa absolutamente do auxílio do corpo: ou para ajudar, ou para ao mesmo tempo ser ajudado e ajudar. E que dizer, se há animais que se mostram inúteis para o nosso proveito e não servem a nenhuma das necessidades humanas? Aproveitam, sem dúvida, pela vista, ainda que não pelo uso: podem ser mais úteis ao coração de quem os contempla do que ao corpo de quem os usa. E, ainda que sejam nocivos, e até perniciosos à saúde temporal dos homens, nem por isso falta aos seus corpos com que cooperar para o bem daqueles que, segundo o desígnio de Deus, foram chamados a ser santos (Rm 8,28). Se não servindo de alimento nem prestando algum serviço, ao menos exercitando a inteligência, segundo aquele ensinamento comum, sempre ao nosso alcance seja qual for o uso que delas se faça, pelo qual as coisas invisíveis de Deus se contemplam pela inteligência, por meio das coisas que foram feitas. Pois também o diabo e os seus sequazes, cuja intenção é sempre maligna, sempre desejam prejudicar; mas que possam prejudicar os que têm zelo do bem, aos quais se diz: Quem vos poderá fazer mal, se fordes zelosos do bem (1Pd 3,13)? — isso, não. Antes lhes aproveitam, mesmo sem querer, e cooperam para o bem dos bons.`
    },
    {
      n: 7,
      texto: `Quanto aos corpos dos anjos, se são naturais a esses espíritos, como os nossos o são para nós; se eles são seres animados como os homens, mas imortais, coisa que os homens ainda não são; se mudam e transformam esses corpos na forma e no aspecto que querem, quando querem aparecer, condensando-os e tornando-os sólidos quanto querem, embora na sua realidade, pela sutileza da sua natureza e da sua substância, sejam impalpáveis e de todo inacessíveis aos nossos olhos; ou se, ao contrário, subsistindo numa substância simplesmente espiritual, tomam corpos quando é preciso e, terminada a obra, tornam a depô-los, para que se dissolvam na mesma matéria de que foram tomados — tudo isso não quero que me pergunteis. Parece que os Padres pensaram de modos diversos sobre o assunto; não vejo com clareza de onde ensinar uma coisa ou outra, e confesso que não sei. E julgo, além disso, que conhecer tais coisas pouco contribui para o vosso progresso.`
    },
    {
      n: 8,
      texto: `Sabei, porém, isto: nenhum espírito criado se aplica por si mesmo à nossa mente, de modo a misturar-se ou infundir-se em nós sem a mediação do nosso corpo ou do seu, para que, participando dele, nos tornemos instruídos ou mais instruídos, bons ou melhores. Nenhum anjo, nenhuma alma pode ser recebida por mim desse modo, nem eu sou capaz de receber nenhum deles. Nem os próprios anjos se recebem assim uns aos outros. Reserve-se, portanto, esta prerrogativa ao Espírito supremo e sem limites, o único que, ao ensinar a ciência ao anjo ou ao homem, não precisa do instrumento do nosso ouvido corporal, como também não precisa de boca para si. Por si mesmo se infunde, por si mesmo se dá a conhecer, e, sendo puro, é recebido pelos puros. Só ele não precisa de nada; só ele basta a si mesmo e a todos, unicamente pela sua vontade onipotente.`
    },
    {
      n: 9,
      texto: `E, contudo, realiza coisas imensas e inumeráveis por meio da criatura que lhe está sujeita, corporal ou espiritual; mas como quem manda, não como quem mendiga. Eis, por exemplo, que ele tomou agora a minha língua corporal para a sua obra, isto é, para vos ensinar, quando sem dúvida poderia fazê-lo por si mesmo, com mais facilidade e mais doçura: isso é condescendência, e não necessidade. Com o vosso progresso ele busca mérito para mim, e não alívio para si. É isto que precisa entender todo homem que faz o bem, para não se gloriar em si mesmo dos bens do Senhor, em vez de se gloriar no Senhor. Há, no entanto, quem faça o bem sem querer, seja homem mau, seja anjo mau; e é claro que o que se faz por meio dele não se faz por causa dele, já que nenhum bem pode aproveitar a quem o pratica contra a vontade. A esse, portanto, é confiada apenas a distribuição; e, não sei bem como, o bem que nos chega por um distribuidor mau nos deixa mais agradecidos e nos sabe melhor. É essa, pois, a razão por que Deus faz o bem aos bons mesmo por meio dos maus — e não porque precise das obras deles para fazer o bem.`
    },
    {
      n: 10,
      texto: `E quem duvidará de que Deus precisa muito menos daquilo que não tem razão nem sentidos? Mas, quando também essas coisas concorrem para uma obra boa, fica claro que tudo o serve, e que com razão ele pode dizer: Minha é a terra inteira (Sl 49,12). Ou então, porque sabe por quais meios cada coisa se faz melhor, ele não busca no serviço da criatura corporal a eficácia, mas a conveniência. Admitamos, além disso, que o serviço dos corpos quase sempre se aplique de modo oportuno às obras divinas — como a chuva, por exemplo, para dar vida às sementes, multiplicar as searas e amadurecer os frutos. Que faria então, pergunto eu, com um corpo próprio aquele a quem obedecem ao menor aceno todos os corpos, celestes e terrestres, sem distinção? Em vão teria um corpo seu quem não encontra corpo algum que lhe seja estranho. Mas, se quisermos encerrar neste sermão tudo o que aqui ocorre dizer, ele passará da medida, e talvez das forças de alguns; por isso guardemos o que resta para ser concluído noutro começo.`
    }
  ]
});
