SERMOES.sermao({
  id: 'bernardo-cantico-35',
  colecao: 'bernardo-cantico',
  ordem: 35,
  numero: 'XXXV',
  titulo: 'Da dura repreensão que o esposo faz à esposa; e da dupla ignorância, que muito se deve temer e evitar',
  fonte: 'De increpatione dura, quam facit sponsus ad sponsam',
  argumento: `"Sai" é a palavra que os servos ouvem de senhores irados, e é com ela que o esposo ameaça a amada, se ela não se conhecer. Sair quer dizer passar do espírito para a carne, do repouso interior para o barulho do mundo; e os cabritos que ela terá de apascentar são os sentidos do corpo, que pastam junto às tendas, nunca acima delas.

Daí Bernardo passa ao homem que, posto na honra, não entendeu que era barro e se tornou semelhante aos animais; e à resposta de Deus, que se fez feno na manjedoura para alimentar os que se tinham feito gado: "adora no estábulo aquele de quem fugias no paraíso". Há, porém, uma segunda ignorância, pior que a primeira: a primeira fez o homem igual aos animais, a segunda o põe atrás deles, porque os animais não serão julgados. O sermão termina anunciando o tema dos seguintes: a ignorância de si e a ignorância de Deus.

Tradução feita do texto latino de Migne (PL 183, 962-966).`,
  pontos: [
    {
      n: 1,
      texto: `Se não te conheces, diz, sai (Ct 1,7). Dura e áspera repreensão é dizer: Sai. Pois é esta a palavra que os servos costumam ouvir dos senhores muito irados e indignados, ou as criadas das suas senhoras, quando as ofenderam gravemente: Sai daqui, sai de perto de mim, sai da minha presença e desta casa. É desta palavra áspera, bastante amarga e sobremodo repreensiva que o esposo usa agora contra a amada — sob condição, porém: se ela não se conhecer. Pois nada mais forte ou mais eficaz podia usar para a assustar do que ameaçá-la de ter de sair. E também tu podes percebê-lo, se reparares bem de onde e para onde lhe mandam sair. De onde, e para onde, julgas tu, senão do espírito para a carne, dos bens da alma para os desejos do mundo, do repouso interior da mente para o barulho do mundo e a inquietação dos cuidados exteriores? Em tudo isso não há senão trabalho e dor (cf. Sl 89,10), e aflição de espírito (cf. Ecl 1,14). Pois a alma que uma vez aprendeu e recebeu do Senhor a graça de entrar em si mesma, de suspirar no seu íntimo pela presença de Deus e de buscar sempre a sua face (Sl 104,4) — pois Deus é espírito (Jo 4,24), e os que o buscam devem andar no espírito, e não na carne, como quem vive segundo a carne —, uma alma assim, digo, não sei se julgaria mais horrível ou mais penoso experimentar por um tempo o próprio inferno do que, depois de ter provado uma vez a suavidade desta aplicação espiritual, sair de novo para os atrativos — ou melhor, para os incômodos — da carne, e voltar à curiosidade insaciável dos sentidos; como diz o Eclesiastes: O olho não se farta de ver, nem o ouvido de ouvir (Ecl 1,8). Ouve, pois, um homem que experimentou o que dizemos: Tu és bom, Senhor, para os que esperam em ti, para a alma que te busca (Lm 3,25). Se alguém tentasse desviar deste bem aquela alma santa, creio que ela o teria sentido como se se visse expulsa do paraíso e da própria entrada da glória. Ouve ainda outro semelhante a este: A ti falou o meu coração, diz; o meu rosto te buscou; o teu rosto, Senhor, eu buscarei (Sl 26,8). Por isso dizia também: Para mim, o bem é estar unido a Deus (Sl 72,28); e, falando de novo à sua alma, diz: Volta, minha alma, ao teu repouso, porque o Senhor te fez bem (Sl 114,7). Digo-vos, pois: quem uma vez recebeu este benefício nada teme tanto quanto ser abandonado pela graça e ter de sair de novo para as consolações da carne — ou melhor, para as suas desolações — e suportar outra vez o tumulto dos sentidos carnais.`
    },
    {
      n: 2,
      texto: `Terrível, portanto, e muito temível é a ameaça: Sai, e apascenta os teus cabritos. Isto é: Fica sabendo que és indigna daquela tua contemplação familiar e suave das coisas celestes, inteligíveis, divinas. Por isso, sai do meu santuário, que é o teu coração, onde costumavas beber docemente os sentidos secretos e sagrados da verdade e da sabedoria; e, antes, como uma das mulheres do mundo, embaraça-te em apascentar e deleitar os sentidos da tua carne. Pois chama cabritos — que significam o pecado e no juízo serão postos à esquerda (Mt 25,33) — aos sentidos do corpo, errantes e petulantes, pelos quais o pecado, como a morte pelas janelas (Jr 9,21), entrou na alma. E com isto combina bem o que se segue na Escritura: Junto às tendas dos pastores. Pois os cabritos não se apascentam por cima delas, como os cordeiros, mas junto às tendas dos pastores. Os pastores que são verdadeiros pastores, ainda que tenham tendas feitas de terra e postas na terra — isto é, os seus corpos —, nos dias em que agora combatem, não costumam apascentar os rebanhos do Senhor com o que é da terra, mas com os pastos celestes: pois não lhes pregam a sua própria vontade, mas a do Senhor. Mas os cabritos, que são os sentidos do corpo, não buscam as coisas celestes; e, junto às tendas dos pastores — isto é, em todos os bens sensíveis deste mundo, que é a região dos corpos —, tomam com que, antes, irritar do que saciar os seus desejos.`
    },
    {
      n: 3,
      texto: `Vergonhosa troca de ocupações! Que aquela que antes se aplicava a apascentar a sua alma peregrina e exilada com santas meditações, como com bens celestes; a buscar o beneplácito de Deus e os mistérios da sua vontade (cf. Ef 1,9); a penetrar os céus com a devoção e percorrer com a mente as moradas do alto; a saudar os patriarcas, os apóstolos e os coros dos profetas, a admirar os triunfos dos mártires e a pasmar diante das belíssimas ordens dos anjos — agora, deixando tudo isto, se entregue à vergonhosa servidão do corpo, para obedecer à carne, satisfazer o ventre e a gula, e mendigar por toda a terra com que consolar de algum modo, com a figura deste mundo que passa (1Cor 7,31), a sua curiosidade sempre faminta! Que os meus olhos derramem torrentes de água (cf. Sl 118,136) sobre uma alma assim, que, criada na púrpura, acaba abraçando o esterco (Lm 4,5). Pois, segundo a sentença do santo varão, apascentou a estéril que não tinha filhos, e à viúva não fez bem (Jó 24,21). E vê que não diz simplesmente: Sai; mas: Sai, diz, e vai atrás dos rebanhos dos teus companheiros, e apascenta os teus cabritos. Nisto, ao que me parece, adverte-nos de algo grande. O quê? Ai! Que a criatura egrégia, que se destacava do rebanho, tendo-se feito há muito tempo parte do rebanho, e agora precipitando-se miseravelmente para pior, não pode sequer permanecer entre os rebanhos, mas recebe ordem de ir atrás deles. Como?, perguntas. Como lês: O homem, quando estava na honra, não entendeu; foi comparado aos animais insensatos, e tornou-se semelhante a eles (Sl 48,13). Eis como a criatura egrégia se tornou do rebanho. Creio que os animais, se lhes fosse dado falar, diriam: Eis que Adão se tornou como um de nós (Gn 3,22). Quando estava na honra, diz. Em que honra?, perguntas. Habitava no paraíso, e vivia num lugar de delícias. Não sentia incômodo nenhum, necessidade nenhuma: cercado de frutos perfumados, sustentado por flores (cf. Ct 2,5), coroado de glória e de honra, e posto sobre as obras das mãos do Criador (Sl 8,6-7); e sobressaía mais ainda pela insígnia da semelhança divina; e tinha a sua parte e a sua companhia com o povo dos anjos e com toda a milícia do exército celeste.`
    },
    {
      n: 4,
      texto: `Mas trocou esta glória de Deus pela imagem de um bezerro que come feno (Sl 105,20). Daí vem que o pão dos anjos (Sl 77,25) se fez feno posto na manjedoura, servido a nós como a animais. Pois o Verbo se fez carne (Jo 1,14), e, segundo o profeta, toda carne é feno (Is 40,6). Mas este feno não secou, nem dele caiu a flor, porque repousou sobre ele o Espírito do Senhor (Is 11,2). Pois foi por isto que um dia chegou o fim de toda carne (Gn 6,13): porque o espírito da vida se tinha retirado. Enfim, diz: O meu espírito não permanecerá para sempre no homem, porque ele é carne (Gn 6,3). Entende que aqui, com o nome de carne, se designa o vício, e não a natureza: pois não é a natureza que expulsa o espírito, mas o vício. Por causa do vício, pois, toda carne é feno, e toda a sua glória como a flor do feno. Secou o feno, diz, e caiu a flor — mas não aquela flor que subiu da vara e da raiz de Jessé, porque sobre ela repousou o Espírito do Senhor (Is 11,1-2); nem aquele feno que o Verbo se tornou, por causa do que se segue no profeta: Mas o Verbo do Senhor permanece para sempre (Is 40,6-8). Pois, se o feno é o Verbo, e o Verbo permanece para sempre, é necessário que também o feno permaneça para sempre. De outro modo, como daria a vida eterna, se ele mesmo não permanecesse para sempre? Pois diz: Se alguém comer deste pão, viverá eternamente. E que pão quer dizer, ele o explica ao acrescentar: E o pão que eu darei é a minha carne, para a vida do mundo (Jo 6,52). Como, pois, não seria eterno aquilo de que se vive eternamente?`
    },
    {
      n: 5,
      texto: `Mas lembra agora comigo a voz do Filho que fala ao Pai no salmo: Não deixarás, diz, o teu Santo ver a corrupção (Sl 15,10). Não há dúvida de que fala do corpo que jazia sem vida no sepulcro. Pois deste Santo falou também o anjo que fez o anúncio à Virgem, dizendo: E o Santo que nascerá de ti será chamado Filho de Deus (Lc 1,35). Como, pois, poderia ver a corrupção o santo feno que, nascido nos pastos floridos do seio incorrupto, sempre verdes, pode prender em si até os olhares ávidos dos anjos, para os deleitar sem jamais os saciar (cf. 1Pd 1,12)? Perca o feno o seu verdor, se Maria perdeu a virgindade! O alimento do homem transformou-se, pois, em pasto de gado, porque o homem se transformou em gado. Ai, triste e lamentável mudança! Que o homem, morador do paraíso, senhor da terra, cidadão do céu, familiar do Senhor dos exércitos, irmão dos espíritos bem-aventurados e coerdeiro das potestades celestes, por uma súbita reviravolta se tenha achado deitado no estábulo, por causa da fraqueza; necessitado de feno, pela semelhança com o gado; e amarrado à manjedoura, pela sua ferocidade indomada, como está escrito: Com cabresto e freio aperta as queixadas dos que não se aproximam de ti (Sl 31,9). Reconhece, porém, ó boi, o teu dono; e tu, jumento, a manjedoura do teu senhor (Is 1,3), para que se mostrem fiéis os profetas de Deus que predisseram estas suas maravilhas. Reconhece, feito gado, aquele que não reconheceste quando eras homem; adora no estábulo aquele de quem fugias no paraíso; honra a manjedoura daquele cujo mandamento desprezaste; come como feno aquele que desdenhaste como pão, e pão dos anjos.`
    },
    {
      n: 6,
      texto: `Mas qual é, perguntas, a causa de tão grande queda? Sem dúvida, que o homem, quando estava na honra, não entendeu. Que é que não entendeu? Ele não o diz; digamo-lo nós. Posto na honra, encantado com o cume da honra, não entendeu que era barro; e logo experimentou em si o que, tanto tempo depois, um homem dos filhos do cativeiro percebeu com prudência e expressou com verdade, dizendo: Quem se julga alguma coisa, não sendo nada, engana-se a si mesmo (Gl 6,3). Ai do infeliz, porque não houve então quem lhe dissesse: Por que te ensoberbeces, terra e cinza? (Eclo 10,9). Daí a criatura egrégia se misturou ao rebanho; daí a semelhança de Deus foi trocada pela semelhança dos animais; daí se fez sociedade com os animais em lugar da companhia dos anjos. Vês como devemos fugir desta ignorância, da qual vieram tantos milhares de males a todo o nosso gênero? Pois diz que o homem foi comparado aos animais insensatos precisamente porque não entendeu. Devemos, pois, guardar-nos de todos os modos da ignorância, para que, se formos achados ainda sem entendimento, mesmo depois do castigo, não nos achem males muito mais numerosos e mais graves que os primeiros, e não se diga de nós: Tratamos a Babilônia, e ela não sarou (Jr 51,9). E com razão, pois nem o castigo deu entendimento ao ouvido (cf. Is 28,19).`
    },
    {
      n: 7,
      texto: `E vê se não é também por isso que o esposo, ao afastar a amada da ignorância com tão grande trovão de repreensão, não disse: Sai com os rebanhos, ou: Sai para os rebanhos; mas: Sai, diz, atrás dos rebanhos dos teus companheiros. Para quê? Sem dúvida, para mostrar que a segunda ignorância é mais de temer e mais vergonhosa que a primeira: aquela fez o homem igual aos animais; esta o põe até atrás deles. Pois os homens, por mérito da sua ignorância, serão ignorados — isto é, reprovados —, e terão de comparecer àquele tremendo juízo e ser entregues ao fogo eterno; os animais, não. E não há dúvida de que será pior para os que existirem assim do que para os que simplesmente não existirem. Melhor lhe fora, diz, que aquele homem não tivesse nascido (Mc 14,21). Não quer dizer: se não tivesse nascido de todo, mas: se não tivesse nascido homem — e sim, por exemplo, animal, ou qualquer outra criatura, que, não tendo juízo, não viria a juízo, e por isso nem ao suplício. Saiba, pois, a alma racional, que se envergonha de si mesma por causa da primeira ignorância, que tem os animais por companheiros no gozo dos bens da terra, mas que não os terá igualmente por companheiros no sofrimento dos tormentos do inferno; e que então será expulsa com ignomínia até dos rebanhos dos animais seus companheiros; e já não irá nem sequer com eles, mas claramente atrás deles, quando, não sentindo eles mal nenhum, ela será exposta a todos os males — dos quais nunca mais será livrada, se tiver acrescentado a segunda ignorância. Sai, pois, o homem, e vai sozinho atrás dos rebanhos dos seus companheiros, quando sozinho é lançado no mais fundo do inferno (cf. Sl 85,13). Não te parece que ocupa o último lugar quem, de mãos e pés amarrados, é lançado nas trevas exteriores (Mt 22,13)? E, sem dúvida, o último estado daquele homem será pior que o primeiro (Mt 12,45), quando aquele que antes se igualava aos animais agora é posto até abaixo deles.`
    },
    {
      n: 8,
      texto: `Creio que, se reparares bem, também nesta vida julgarás que o homem vai atrás dos animais. Não te parece, com efeito, de certo modo mais bestial que as próprias bestas o homem que tem o vigor da razão e não vive segundo a razão? Pois o animal, se não se governa pela razão, tem a desculpa da natureza, que lhe negou de todo este dom; o homem não a tem, a quem ela o deu por privilégio especial. Com razão, pois, se considera que o homem sai e vai atrás dos animais do rebanho, pelo simples fato de ser ele o único animal que, transgredindo as leis da natureza com um modo de vida degenerado, imita nos costumes e nos afetos, dotado de razão como é, os seres que não a têm. Fica provado, pois, que o homem vai atrás dos rebanhos: agora, pela depravação da natureza; depois, também pelo extremo do castigo.`
    },
    {
      n: 9,
      texto: `Eis como será amaldiçoado o homem que for achado na ignorância de Deus. Direi de Deus, ou de si mesmo? De um e de outro, sem dúvida: ambas as ignorâncias são condenáveis, e qualquer das duas basta para a perdição. Queres saber que é assim? Da ignorância de Deus não duvidas, se é certo para ti que a vida eterna não é outra coisa senão conhecer o Pai, Deus verdadeiro, e aquele que ele enviou, Jesus Cristo (Jo 17,3). Ouve, pois, o esposo condenar clara e abertamente, na alma, também a ignorância de si mesma. Pois que diz? Não, certamente: Se não conheces a Deus; mas: Se não te conheces, e o resto. É claro, pois, que quem ignora será ignorado (1Cor 14,38), quer ignore a si mesmo, quer a Deus. Sobre uma e outra ignorância teremos, se Deus puser a sua mão, uma discussão muito útil. Mas não agora: para que, cansados e sem ter feito antes a oração, como é costume, nem eu trate com menos cuidado uma coisa necessária, nem vós ouçais com menos atenção o que só se deve receber com grande desejo. Pois, se o alimento do corpo, quando o tomas sem apetite e já saciado, não só não aproveita como até faz muito mal, muito mais o pão da alma, tomado com fastio, trará não o alimento da ciência, mas antes o tormento da consciência. Que isso afaste de nós o esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
