SERMOES.sermao({
  id: 'bernardo-cantico-75',
  colecao: 'bernardo-cantico',
  ordem: 75,
  numero: 'LXXV',
  titulo: 'Deus deve ser buscado no tempo, do modo e no lugar devidos; e agora é o tempo favorável, em que cada um, pelas boas obras, pode encontrar a Deus e operar a sua salvação',
  fonte: 'Deus quaerendus est debito tempore, modo, et loco',
  argumento: `"No meu pequeno leito, durante as noites, busquei aquele a quem a minha alma ama." Chamado, o esposo não voltou, para que o desejo crescesse; e a esposa o busca no leito, na cidade, nas praças, sem o encontrar. Por que não o encontra, se ele promete que quem busca encontra? Três coisas frustram a busca: buscar fora do tempo, do modo errado ou no lugar errado. O tempo é agora, nos dias da salvação: depois da morte já não há sacrifício pelos pecados, e o sangue de Cristo, que pacificou a terra e o céu, não desce aos infernos. A esposa busca no tempo certo e com ardor; o erro está no lugar.

O pequeno leito é a fraqueza que Cristo tomou de nós — o seio da Virgem, o presépio, o sepulcro —; mas ele ressuscitou e está sentado à direita do Pai: em vão o buscam no sepulcro as santas mulheres, que voltam ungidas pela notícia da ressurreição, e Pedro e João. As noites são a infidelidade dos judeus, a ignorância dos pagãos, as seitas dos hereges e a vida carnal dos católicos, onde a esposa, ainda pequenina, buscou a verdade e não a achou. Levantar-se é ressuscitar com Cristo e buscá-lo no alto, e não andar em círculos pela cidade, como os que têm fome.

Tradução feita do texto latino de Migne (PL 183, 1144-1150).`,
  pontos: [
    {
      n: 1,
      texto: `No meu pequeno leito, durante as noites, busquei aquele a quem a minha alma ama (Ct 3,1). O esposo não voltou à voz e ao desejo de quem o chamava de volta. Por quê? Para que o desejo crescesse, para que o afeto fosse provado, para que se exercitasse o negócio do amor. É, pois, fingimento, não indignação. Mas resta que seja buscado, para ver se, buscado, se deixa encontrar aquele que, chamado, não veio, pois diz o Senhor: Todo aquele que busca, encontra (Mt 7,8). Ora, a palavra com que o chamava de volta era esta: Volta; sê semelhante, meu amado, à gazela e ao filhote dos cervos (Ct 2,17). Como ele não voltou a esta voz, pelas razões que se disseram, ela, que ama, tornada por isso mais ansiosa, logo se entregou com toda a avidez a buscá-lo. E primeiro busca-o no pequeno leito, mas não o encontra. Levanta-se dali, percorre a cidade, vai e volta pelas praças e pelas ruas, e ele não aparece nem se mostra. Interroga todos os que por acaso encontra, e nada de certo consegue saber. E esta busca e esta frustração não são de uma só vez, nem de uma só noite, pois ela diz: busquei durante as noites. Que desejo e que ardor é este, que, levantando-se de noite, não se envergonha de aparecer em público, percorre a cidade, pergunta abertamente e por toda parte pelo amado, e não pode ser desviada por nenhuma razão de seguir as pisadas dele, nem impedida por nenhuma dificuldade, nem retida pelo amor do repouso a que a hora convida, nem pelo pudor de esposa, nem sequer pelo medo da noite? E, no entanto, em tudo isto viu até agora frustrado o seu desejo. Pergunta-se: que significa esta privação tão obstinada e tão longa, nutriz de desgostos, lenha de suspeitas, facho de impaciência, madrasta do amor, mãe do desespero? Se ainda é fingimento, é penoso demais.`
    },
    {
      n: 2,
      texto: `Admitamos que ele tenha fingido com piedade e proveito enquanto a coisa estava só em chamá-lo ou chamá-lo de volta. Mas agora que é buscado, e buscado assim, de que pode ainda servir o fingimento? Se se trata de esposos carnais e de amores vergonhosos, como a superfície da letra parece ter insinuado, e se entre esses podem acontecer tais coisas, não me interessa: eles que vejam. Mas, se devo responder e satisfazer, na medida do meu pequeno poder, às mentes e aos afetos das almas que buscam o Senhor, é preciso tirar da santa Escritura, na qual confiam ter a vida (cf. Jo 5,39), alguma coisa tanto mais vital quanto mais espiritual, para que os pobres comam e se saciem (Sl 21,27), e os seus corações vivam. E que há de tanta vida para os corações como o meu Senhor Jesus Cristo, de quem dizia aquele que vivia dele: Quando Cristo, vossa vida, aparecer, então também vós aparecereis com ele na glória (Cl 3,4)? Venha, pois, ele ao meio, para que também a nós se possa dizer com verdade: No meio de vós está aquele que não conheceis (Jo 1,26). Embora não sei como o esposo, que é Espírito, possa não ser conhecido pelos espirituais, que tanto progrediram no espírito que podem dizer com o profeta: O Cristo Senhor é espírito diante da nossa face (Lm 4,20); e com o Apóstolo: Ainda que tenhamos conhecido Cristo segundo a carne, agora já não o conhecemos assim (2Cor 5,16). Não é este aquele que a esposa buscava? Este é verdadeiramente o esposo, que ama e é amável. Este, digo, é verdadeiramente esposo, assim como a sua carne é verdadeiramente comida, e o seu sangue verdadeiramente bebida (Jo 6,56); e tudo o que é dele é verdadeiramente, pois ele não é outra coisa senão a própria Verdade.`
    },
    {
      n: 3,
      texto: `Mas por que razão este esposo, buscado, não é encontrado, sendo buscado com tanto empenho e sem descanso, ora no pequeno leito, ora na cidade, ou ainda nas praças e nas ruas, quando ele mesmo diz: Buscai, e encontrareis; e: Quem busca, encontra (Mt 7,7-8)? E o profeta lhe diz também: Bom és, Senhor, para a alma que te busca (cf. Lm 3,25); e igualmente o santo Isaías: Buscai o Senhor enquanto pode ser encontrado (Is 55,6). Como se cumprirão, pois, as Escrituras? Pois a que aqui se apresenta buscando não é uma daqueles a quem ele diz: Vós me buscareis e não me encontrareis (Jo 7,34). Mas reparai que há três causas que por ora me ocorrem e que costumam frustrar os que buscam: quando não buscam no tempo devido, ou não como convém, ou não onde convém. Pois, se todo tempo é apto para buscar, por que diz então o profeta, como já lembrei: Buscai o Senhor enquanto pode ser encontrado? Haverá, sem dúvida, um tempo em que não poderá ser encontrado; e por isso acrescenta que seja invocado enquanto está perto (Is 55,6), porque virá um tempo em que já não estará perto. Pois por quem não será então buscado? Diante de mim, diz, se dobrará todo joelho (Is 45,24). E, no entanto, não será encontrado pelos ímpios, que os anjos vingadores certamente afastarão, e tirarão, para que não vejam a glória de Deus (cf. Is 26,10). Em vão clamarão também as virgens insensatas: ele já não sai de modo nenhum ao encontro delas, fechada a porta (Mt 25,10). Tomem, pois, para si estas palavras: Vós me buscareis e não me encontrareis.`
    },
    {
      n: 4,
      texto: `Mas agora é o tempo favorável, agora são os dias da salvação (2Cor 6,2); tempo, certamente, de buscar e de invocar, em que muitas vezes se sente que ele está presente antes mesmo de ser invocado. Ouve, enfim, o que promete: Antes que me invoqueis, diz, direi: Eis-me aqui (Is 65,24). Nem passou despercebida esta benignidade e esta facilidade do tempo presente àquele que diz no salmo: O Senhor ouviu o desejo dos pobres; o teu ouvido ouviu a disposição do seu coração (Sl 9,38). E, se Deus é buscado pelas boas obras, então, enquanto temos tempo, façamos o bem a todos (Gl 6,10); sobretudo porque o Senhor anuncia claramente que vem a noite, quando ninguém pode trabalhar (Jo 9,4). Pensas tu que encontrarás nos séculos futuros outro tempo para buscar a Deus e fazer o que é bom, além deste que Deus te fixou, para se lembrar de ti (cf. Jó 14,13)? E por isso são dias de salvação, porque neles o próprio Deus, nosso rei antes dos séculos, operou a salvação no meio da terra (Sl 73,12).`
    },
    {
      n: 5,
      texto: `Vai, pois, tu, e espera no meio do inferno a salvação que já foi feita no meio da terra! Que possibilidade sonhas que te há de vir, entre os ardores eternos, de merecer o perdão, quando já passou o tempo da misericórdia? Não te resta sacrifício pelos pecados (cf. Hb 10,26), se morreres nos pecados. O Filho de Deus não é crucificado de novo; morreu uma vez, já não morre (Rm 6,9). O sangue que foi derramado sobre a terra não desce aos infernos. Beberam-no todos os pecadores da terra (cf. Sl 74,9): não há nada dele que os demônios possam reclamar para apagar os seus fogos, nem tampouco os homens companheiros dos demônios. Uma só vez desceu lá, não o sangue, mas a alma; e esta foi a porção dos que estavam na prisão (cf. 1Pd 3,19): aquela única visita, que então se fez pela presença da alma, enquanto o corpo pendia sem vida sobre a terra. O sangue regou a terra seca, o sangue embebeu a terra e a embriagou (cf. Sl 64,10); o sangue pacificou as coisas que estão na terra e as que estão nos céus (cf. Cl 1,20), mas não as que estão nos infernos; a não ser que, como disse, a sua alma foi lá uma vez e fez em parte a redenção, para que nem naquele momento ficasse parada a obra da caridade; mas não o fará mais. Agora, pois, é o tempo favorável e apto para buscar, em que certamente quem busca encontra; contanto, porém, que busque onde e como convém. E esta é uma das causas que podem impedir que o esposo seja encontrado pelos que o buscam: quando não buscam no tempo oportuno. Mas não é esta que impede a esposa, pois ela o invoca e o busca no tempo oportuno. Nem o busca com tibieza, negligência ou superficialidade: busca-o com coração ardente e de todo incansável, exatamente como convém.`
    },
    {
      n: 6,
      texto: `Resta ver a terceira: se não busca onde não convém. No meu pequeno leito busquei aquele a quem a minha alma ama. Ou talvez não devesse ser buscado num pequeno leito, mas num leito grande, ele para quem o mundo é estreito? Mas não tenho horror ao pequeno leito, eu que conheço o pequenino. Enfim, um pequenino nasceu para nós (Is 9,6). Exulta e louva, habitação de Sião, porque é grande no meio de ti o Santo de Israel (Is 12,6). Mas o mesmo Senhor, grande em Sião (cf. Sl 98,2), foi achado pequenino entre nós, fraco entre nós: por uma coisa tinha de estar deitado, pela outra, de estar deitado num pequeno leito. Não é um pequeno leito o sepulcro? Não é um pequeno leito o presépio? Não é um pequeno leito o seio da Virgem? Pois o seio do grande Pai não é um pequeno leito, mas um leito grande, do qual diz ao Filho: Do seio, antes da aurora, eu te gerei (Sl 109,3). Embora talvez nem sequer se deva chamar dignamente leito àquele seio, que é antes lugar de quem governa do que de quem está deitado. Pois, permanecendo no Pai, governa com o Pai todas as coisas. Enfim, a fé sem dúvida sustenta que o Filho não está deitado, mas sentado à direita do Pai; e ele mesmo declara que o céu é o seu trono, e não o seu leito (cf. Is 66,1): para que saibas que ele, no que é seu, isto é, no alto, de modo nenhum tem os alívios da fraqueza, mas as insígnias do poder.`
    },
    {
      n: 7,
      texto: `Com razão, pois, a esposa, pondo o pequeno leito, diz que é seu, porque é manifesto que tudo o que há de fraco em Deus não está nele pelo que é seu, mas pelo que é nosso. De nós tomou o que suportou por nós: nascer, mamar, morrer, ser sepultado. Minha é a mortalidade do que nasceu, minha a fraqueza do pequenino, minha a morte do crucificado, meu o sono do sepultado. As coisas antigas passaram, e eis que tudo se fez novo (2Cor 5,17). No meu pequeno leito, durante as noites, busquei aquele a quem a minha alma ama. Quê? Buscavas no teu aquele que já se tinha recolhido ao que é seu? Não tinhas visto o Filho do homem subir para onde estava antes (cf. Jo 6,63)? Já trocou o sepulcro e o estábulo pelo céu, e tu ainda o buscas no teu pequeno leito? Ressuscitou, não está aqui (Mc 16,6). Por que buscas no pequeno leito o forte, no pequeno leito o grande, no estábulo o glorificado? Entrou nas obras poderosas do Senhor (cf. Sl 70,16), revestiu-se de beleza e de força (cf. Sl 92,1); e eis que está sentado sobre os querubins (cf. Sl 79,2) aquele que jazia debaixo da pedra. Daí em diante já não está deitado, mas sentado: e tu preparas auxílios como para quem está deitado? Ou, para que a verdade fique mais completa: ou está sentado para julgar, ou está de pé para socorrer (cf. At 7,55).`
    },
    {
      n: 8,
      texto: `Assim vós, ó boas mulheres, a quem, pergunto, prestais esta vigília? Para quem comprais aromas e preparais unguentos (cf. Mc 16,1)? Se soubésseis quão grande ele é, e quão livre entre os mortos (cf. Sl 87,6) é este morto que ides ungir, talvez tivésseis antes pedido para ser ungidas por ele. Não é este aquele que o seu Deus ungiu com óleo de alegria, de preferência aos seus companheiros (Sl 44,8)? Bem-aventuradas sereis vós, se puderdes gloriar-vos ao voltar e dizer: Também nós recebemos da sua plenitude (Jo 1,16). E assim aconteceu. Pois voltam ungidas as que tinham vindo para ungir. E como não voltariam ungidas, com tão alegre notícia da nova e perfumada ressurreição? Quão belos são os pés dos que anunciam a paz, dos que anunciam os bens (Rm 10,15)! Enviadas pelo anjo, fazem a obra de evangelista (cf. 2Tm 4,5); e, feitas apóstolas dos apóstolos, enquanto se apressam a anunciar de manhã a misericórdia do Senhor (cf. Sl 91,3), dizem: Corremos ao odor dos teus perfumes (Ct 1,3). Desde então, pois, e daí em diante, em vão se buscou o esposo no pequeno leito; porque, ainda que a Igreja o tivesse conhecido segundo a carne, isto é, segundo a fraqueza da carne, agora já não o conhece assim (cf. 2Cor 5,16). Enfim, foi buscado depois também por Pedro e João no sepulcro, mas não foi encontrado (cf. Jo 20,3-8). Vê tu se cada um deles não podia então dizer com propriedade e acerto: No meu pequeno leito busquei aquele a quem a minha alma ama; busquei-o, e não o encontrei. Pois a carne, que não vinha do Pai e havia de ir para o Pai, primeiro, pela glória da ressurreição, despojou-se de toda fraqueza, cingiu-se de poder, revestiu-se de luz como de um manto (cf. Sl 103,2): com tal glória e ornato convinha, sem dúvida, que se apresentasse aos olhos do Pai.`
    },
    {
      n: 9,
      texto: `Belamente, porém, a esposa não diz: aquele que eu amo, mas: aquele a quem a minha alma ama; porque verdadeira e propriamente pertence só à alma aquele amor com que se ama alguma coisa espiritualmente, por exemplo, Deus, um anjo, uma alma. E também amar a justiça, a verdade, a piedade, a sabedoria e as outras virtudes é deste gênero. Pois, quando a alma ama segundo a carne alguma coisa, ou antes, a apetece — por exemplo, a comida, a roupa, o domínio e outras coisas corporais ou terrenas deste gênero —, deve chamar-se amor da carne mais do que da alma. E isto fica dito porque a esposa, de modo menos usual, mas não menos próprio, diz que é a sua alma que ama o esposo, mostrando assim que o esposo é espírito, e que ela o ama não com amor carnal, mas espiritual. E diz bem que o buscou durante as noites. Pois, se, segundo Paulo, os que dormem, dormem de noite, e os que se embriagam, embriagam-se de noite (1Ts 5,7), assim não será absurdo, penso eu, dizer que os que ignoram, ignoram de noite, e por isso os que buscam, buscam de noite. Pois quem buscaria o que tem à vista? Ora, o dia torna visível o que a noite esconde, de modo que encontras de dia o que tinhas buscado de noite. É noite, pois, enquanto se busca o esposo; porque, se fosse dia, ele estaria à vista, e de modo nenhum seria buscado. E basta disto; a não ser que este número plural de noites indique ainda alguma coisa a buscar, pois não disse "de noite", mas "durante as noites".`
    },
    {
      n: 10,
      texto: `E parece-me — se não tens coisa melhor — que se pode dar esta razão. Este mundo tem as suas noites, e não poucas. Que digo, que o mundo tem noites, se ele mesmo é quase todo noite, e todo ele anda sempre nas trevas? Noite é a infidelidade judaica, noite a ignorância dos pagãos, noite a perversidade herética, noite também a vida carnal ou animal dos católicos. Não é noite onde não se percebem as coisas que são do Espírito de Deus (cf. 1Cor 2,14)? E, entre os hereges ou cismáticos, tantas seitas, tantas noites. Em vão buscais durante estas noites o sol da justiça e a luz da verdade, isto é, o esposo; porque não há comunhão entre a luz e as trevas (cf. 2Cor 6,14). Mas alguém dirá que a esposa não é tão tola nem tão cega que busque a luz nas trevas, que busque o amado junto dos que o ignoram e não o amam. Como se ela dissesse que agora o busca durante as noites, e não que o buscou antes! Não diz: Busco; mas: Busquei durante as noites aquele a quem a minha alma ama. E o sentido é este: quando era pequenina, pensava como pequenina, raciocinava como pequenina (cf. 1Cor 13,11), e buscava a verdade onde ela não estava, errando e não a encontrando, segundo aquela palavra do salmo: Andei errante como ovelha perdida (Sl 118,176). Enfim, lembra que então ainda estava no pequeno leito, como quem era fraca na idade e pequenina no entendimento.`
    },
    {
      n: 11,
      texto: `Se, porém, construíres a frase assim: No meu pequeno leito — subentende: estando ou jazendo — busquei aquele a quem a minha alma ama; isto é, não o busquei no pequeno leito, mas busquei-o estando no pequeno leito; quer dizer: Quando ainda era fraca e sem forças, e de todo pouco apta para seguir o esposo aonde quer que fosse (cf. Ap 14,4), para o seguir às alturas árduas da sua sublimidade, dei com muitos que, conhecendo o meu desejo, me diziam: Eis aqui o Cristo, ei-lo ali (Mc 13,21); e ele não estava nem aqui nem ali. Dei com eles, mas sem me deixar enganar. Pois quanto mais me aproximei e examinei com diligência, tanto mais depressa e com mais certeza conheci que a verdade de modo nenhum estava com eles. Busquei, com efeito, e não encontrei; e descobri que eram noites os que mentiam ser dias.`
    },
    {
      n: 12,
      texto: `E disse: Vou levantar-me e percorrer a cidade; pelas ruas e praças buscarei aquele a quem a minha alma ama (Ct 3,2). Repara agora que está deitada a que diz: Vou levantar-me. Belíssimo. E como não se levantaria, sabendo da ressurreição do amado? Mas, ó bem-aventurada, se ressuscitaste com Cristo, deves gostar das coisas do alto; e é necessário que busques Cristo não em baixo, mas no alto, onde está sentado à direita do Pai (Cl 3,1-2). Mas dizes: percorrerei a cidade. Para quê? Os ímpios andam em círculo (Sl 11,9). Deixa isto aos judeus, dos quais o seu próprio profeta vaticinou que sofreriam fome como cães e rondariam a cidade (Sl 58,7). E, se entrares na cidade, segundo outro profeta, eis os que estão consumidos pela fome (Jr 14,18); o que certamente não aconteceria, se nela estivesse o pão da vida. Ressuscitou do coração da terra (cf. Mt 12,40), mas não ficou sobre a terra. Subiu para onde estava antes. Pois aquele que desceu é o mesmo que subiu (cf. Ef 4,10), o pão vivo que desceu do céu (Jo 6,51), ele mesmo, o esposo da Igreja, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
