SERMOES.sermao({
  id: 'bernardo-cantico-65',
  colecao: 'bernardo-cantico',
  ordem: 65,
  numero: 'LXV',
  titulo: 'Dos hereges clandestinos: da sua religião às avessas, do seu empenho em esconder os seus mistérios e da escandalosa convivência com mulheres',
  fonte: 'De clandestinis haereticis',
  argumento: `Terceiro sermão sobre as raposas, agora voltado não para a vinha do mosteiro, mas para a grande vinha do Senhor, a Igreja inteira. Os hereges antigos combatiam às claras e, vencidos em público, eram logo "apanhados"; os de agora, que Bernardo conhece de perto, se escondem: "jura, perjura, mas não reveles o segredo" — eles que, de resto, se recusam a jurar por escrúpulo evangélico. Bernardo os acossa com o próprio Evangelho: o que se ouve ao ouvido deve pregar-se sobre os telhados; os apóstolos clamavam em público, e eles sussurram em porões.

Por fora, são irrepreensíveis: vão à igreja, confessam-se, jejuam, vivem do trabalho das mãos. Mas os frutos os denunciam: mulheres deixam os maridos, clérigos abandonam as suas igrejas para viver entre tecelões. E há um sinal que não falha: todos vivem com mulheres que não são suas esposas nem parentes. Estar sempre com uma mulher e não a conhecer seria mais que ressuscitar um morto; quem não quer afastar o escândalo mostra-se desprezador do Evangelho e da Igreja, e a Igreja deve afastá-lo. A lista das suas doutrinas fica para o sermão seguinte.

Tradução feita do texto latino de Migne (PL 183, 1088-1093).`,
  pontos: [
    {
      n: 1,
      texto: `Sobre um só versículo fiz-vos dois sermões; preparo um terceiro, se não vos cansar ouvir. E julgo-o necessário. Pois, quanto à nossa vinha de casa, que sois vós, julgo ter feito bastante nos dois sermões para a proteger contra as ciladas de três gêneros de raposas: os aduladores, os maldizentes e certos espíritos sedutores, hábeis e acostumados a introduzir o mal sob a aparência do bem. Mas não assim quanto à vinha do Senhor. Falo daquela que encheu a terra, da qual também nós somos uma parte: vinha grandíssima, plantada pela mão do Senhor, resgatada pelo sangue, regada pela palavra, propagada pela graça, fecundada pelo Espírito. Cuidando mais do que é nosso, fui menos útil ao que é comum. E o que me move em favor dela é a multidão dos que a destroem, o pequeno número dos que a defendem, a dificuldade da defesa. A dificuldade vem de se esconderem. Pois, embora a Igreja tenha tido sempre raposas desde o seu princípio, todas foram logo descobertas e apanhadas. O herege combatia às claras — pois era herege sobretudo porque desejava vencer às claras — e sucumbia. Assim, pois, aquelas raposas eram apanhadas facilmente. Que importava que, posta a verdade à luz, o herege, ficando nas trevas da sua obstinação, secasse sozinho, lançado fora? Nem por isso a raposa deixava de ser tida por apanhada, condenada a impiedade e lançado fora o ímpio, que dali em diante viveria para exemplo, e não para fruto. Daí em diante, segundo o profeta, tinha peitos secos e ventre estéril (Os 9,14); porque o erro refutado publicamente não torna a brotar, e a falsidade descoberta não germina.`
    },
    {
      n: 2,
      texto: `Que faremos com estas raposas malignissimas, para que possam ser apanhadas, elas que preferem fazer mal a vencer, e nem sequer querem aparecer, mas rastejar? Todos os hereges sempre tiveram um só intento: buscar glória pela singularidade da ciência. Só esta heresia, mais maligna e mais astuta que as outras, alimenta-se do dano alheio, descuidando a própria glória. Ensinada, creio, pelo exemplo das antigas, que, denunciadas, não conseguiam escapar, mas eram logo apanhadas, tomou a cautela de operar o mistério da iniquidade (cf. 2Ts 2,7) com um novo gênero de maleficência, tanto mais livremente quanto mais às escondidas. Enfim, impuseram a si mesmos, segundo se diz, o esconderijo, e firmaram entre si esta palavra perversa: Jura, perjura, mas não reveles o segredo. Pois, de resto, não aceitam de modo nenhum jurar, nem levemente, por causa daquilo do Evangelho: Não jureis, nem pelo céu, nem pela terra (Mt 5,34-35), etc. Ó insensatos e lentos de coração, cheios verdadeiramente do espírito dos fariseus, que coam o mosquito e engolem o camelo (Mt 23,24)! Jurar não é lícito, e perjurar é lícito? Ou só neste caso são lícitas as duas coisas? De que passo dos Evangelhos me tirais esta exceção, vós que, como vos gloriais falsamente, não deixais passar nem um i? É claro que sois escrupulosos a respeito do juramento e criminosamente atrevidos a respeito do perjúrio. Ó perversidade! O que foi aconselhado por cautela, isto é, não jurar, isso observam com tanta obstinação como se fosse mandamento; e o que foi estabelecido por um direito imutável, isto é, não perjurar, disso dispensam à vontade, como de coisa indiferente. Não, dizem, mas é para não publicarmos o mistério. Como se a glória de Deus não fosse revelar a palavra! Acaso invejam a glória de Deus? Mas antes creio que se envergonham de revelá-lo, sabendo que é coisa sem glória. Pois diz-se que fazem em segredo coisas nefandas e obscenas; pois também a traseira das raposas fede.`
    },
    {
      n: 3,
      texto: `Mas calo o que eles negariam; respondam ao que é manifesto. Acaso, segundo o Evangelho, evitam dar o que é santo aos cães e as pérolas aos porcos (Mt 7,6)? Mas isto é confessar abertamente que não são da Igreja, pois julgam cães e porcos todos os que são da Igreja. Pois julgam que se deve subtrair aquilo que é deles, seja o que for, a todos, sem exceção, os que não são da sua seita. Mas, embora pensem isto, não o responderão, para não se tornarem manifestos, coisa de que fogem de todos os modos — mas não escaparão. Responde-me, ó homem que sabes mais do que convém e deliras mais do que se pode dizer. O mistério que escondes é de Deus ou não? Se é, por que não o revelas para a sua glória? Pois a glória de Deus é revelar a palavra. Se não é, por que tens fé naquilo que não é de Deus, senão porque és herege? Ou revelem, pois, o segredo de Deus para a glória de Deus; ou neguem que é mistério de Deus, e não neguem que são hereges; ou então confessem-se abertamente inimigos da glória de Deus, pois não querem tornar manifesto o que sabem que seria para a sua glória. Pois permanece a verdade da Escritura: A glória dos reis é esconder a palavra; a glória de Deus é revelar a palavra (Pr 25,2). Não queres revelar? Então não queres glorificar a Deus. Mas talvez não aceites esta Escritura. Assim é: declaram-se zeladores só do Evangelho, e os únicos. Respondam, pois, ao Evangelho: O que vos digo nas trevas, diz, dizei-o à luz; e o que ouvis ao ouvido, pregai-o sobre os telhados (Mt 10,27). Já não é lícito calar. Até quando se mantém escondido o que Deus manda tornar público? Até quando está velado o vosso evangelho? Desconfio: o vosso não é o de Paulo, pois ele declara que o seu não está velado. Se o meu evangelho está velado, diz, está velado para os que se perdem (2Cor 4,3). Vede se não falava de vós, entre os quais se acha o evangelho velado. Que há de mais claro do que estardes a perder-vos? Ou talvez nem sequer aceitais Paulo? De alguns ouvi dizer isso. Pois nem todos vós concordais em tudo entre vós, ainda que todos discordeis de nós.`
    },
    {
      n: 4,
      texto: `Mas as palavras, os escritos e as tradições dos que estiveram corporalmente com o Salvador, todos vós, se não me engano, recebeis indistintamente com a mesma autoridade do Evangelho. Acaso eles mantiveram velado o seu evangelho? Acaso calaram, em Deus, as fraquezas da carne, os horrores da morte, a ignomínia da cruz? Pelo contrário: por toda a terra se espalhou a sua voz (Sl 18,5). Onde está a forma e a vida apostólica de que vos gabais? Eles clamam, vós sussurrais; eles em público, vós num canto; eles voam como nuvens (Is 60,8), vós vos escondeis nas trevas e em casas subterrâneas. Que semelhança com eles mostrais em vós? Talvez a de terdes mulheres convosco — não, na verdade, levando-as convosco pelos caminhos, mas fechando-vos com elas em casa? Pois andar em companhia não dá tanto lugar a suspeita como morar juntos. Mas quem suspeitaria algo de mau daqueles que ressuscitavam os mortos? Faze tu o mesmo, e acreditarei que um homem pode deitar-se ao lado de uma mulher. De outro modo, usurpas temerariamente a licença daqueles cuja santidade não tens. Estar sempre com uma mulher e não conhecer a mulher não é mais do que ressuscitar um morto? Não podes o que é menos, e queres que te creia no que é mais? Todos os dias o teu lado está junto do lado de uma mocinha à mesa; o teu leito junto do leito dela no quarto; os teus olhos junto dos olhos dela na conversa; as tuas mãos junto das mãos dela no trabalho: e queres ser tido por continente? Seja que o és; mas eu não fico sem suspeita. És para mim escândalo: tira a causa do escândalo, para te mostrares verdadeiro zelador do Evangelho, como te gabas. Quem escandalizar um só da Igreja, não o condena o Evangelho? Tu escandalizas a Igreja. És uma raposa que destrói a vinha. Ajudai-me, companheiros, a apanhá-la; ou antes, apanhai-a vós para nós, ó santos anjos. É muito astuta, coberta pela sua iniquidade e impiedade. É verdadeiramente tão pequena e sutil que escapa facilmente aos olhares humanos. Acaso também aos vossos? Por isso aquela voz se dirige a vós, como companheiros do esposo: Apanhai-nos as raposas pequenas (Ct 2,15). Fazei, pois, o que vos é mandado; apanhai-nos esta raposinha tão manhosa, que, eis, há tanto tempo perseguimos em vão. Ensinai e sugeri como se há de descobrir a fraude. Pois isto é ter apanhado a raposa; porque um falso católico faz muito mais mal do que se aparecesse como verdadeiro herege. Mas não é próprio do homem saber o que há no homem (cf. Jo 2,25), a não ser que alguém tenha sido iluminado para isso pelo Espírito de Deus ou instruído pela diligência dos anjos. Que sinal dareis, para que se torne manifesta esta péssima heresia, que aprendeu a mentir não só com a língua, mas com a vida?`
    },
    {
      n: 5,
      texto: `A devastação recente da vinha indica, sem dúvida, que esteve ali uma raposa; mas, com não sei que arte de fingir, este animal astutíssimo confunde de tal modo as suas pegadas que não se pode descobrir facilmente por onde entra ou por onde sai. E, estando patente a obra, não aparece o autor; tanto dissimula tudo com o que mostra por fora. Enfim, se lhe perguntas pela fé, nada mais cristão; se pela vida, nada mais irrepreensível; e o que diz, prova-o com os fatos. Podes ver o homem, em testemunho da sua fé, frequentar a igreja, honrar os presbíteros, fazer a sua oferta, confessar-se, participar dos sacramentos. Que há de mais fiel? E, quanto à vida e aos costumes, não engana ninguém, não se aproveita de ninguém, não extorque ninguém. Além disso, tem o rosto pálido dos jejuns, não come o pão na ociosidade, trabalha com as mãos para ganhar a vida. Onde está agora a raposa? Tínhamo-la presa: como nos escapou das mãos? Como desapareceu tão de repente? Insistamos, investiguemos: pelos seus frutos a conheceremos (cf. Mt 7,16). E, sem dúvida, a destruição das vinhas atesta a raposa. Mulheres, deixando os maridos, e também maridos, abandonando as mulheres, vão juntar-se a eles. Clérigos e sacerdotes, deixando os povos e as igrejas, foram muitas vezes encontrados entre eles, sem tonsura e barbudos, no meio de tecelões e tecelãs. Não é esta uma grave destruição? Não são estas obras de raposas?`
    },
    {
      n: 6,
      texto: `Mas talvez não se descubram em todos coisas tão manifestas; e, ainda que as haja, não há como prová-las. De que modo os apanhamos? Voltemos à companhia e à coabitação com mulheres: pois não há entre eles quem não a tenha. Pergunto a um deles: Ouve, bom homem! Quem é esta mulher, e de onde a tens? É tua esposa? Não, diz, pois isso não convém ao meu voto. Tua filha, então? Não. Que é, então? Não é tua irmã, nem sobrinha, nem ligada a ti por algum grau de parentesco ou de afinidade? Por nenhum. E como está segura, com ela, a tua continência? Na verdade, isto nem sequer te é lícito. A Igreja, se não sabes, proíbe a coabitação de homens e mulheres àqueles que fizeram voto de continência. Se não queres escandalizar a Igreja, manda embora a mulher. De outro modo, por esta só coisa as outras, que não são tão manifestas, tornam-se sem dúvida dignas de crédito.`
    },
    {
      n: 7,
      texto: `Mas em que passo do Evangelho, diz, me mostras que isto é proibido? Apelaste para o Evangelho; ao Evangelho irás (cf. At 25,12). Se obedeces ao Evangelho, não darás escândalo; pois o Evangelho proíbe claramente dar escândalo. E tu o dás, não afastando esta mulher conforme a determinação da Igreja. Eras suspeito; mas agora serás julgado claramente desprezador do Evangelho e adversário da Igreja. Que julgais, irmãos? Se for tão obstinado que nem obedeça ao Evangelho nem se submeta à Igreja, que evasiva lhe resta? Não vos parece claramente descoberta a fraude e apanhada a raposa? Se não afasta a mulher, não afasta o escândalo; se não afasta o escândalo, podendo afastá-lo, fica convicto de transgressor do Evangelho. Que há de fazer a Igreja, senão afastar aquele que não quer afastar o escândalo, para não ser desobediente como ele? Pois tem no Evangelho o mandamento de não poupar o olho que a escandaliza, nem a mão, nem o pé, mas de arrancar aquele, cortar estes e lançá-los para longe de si. Se não ouvir a Igreja, diz, seja para ti como o pagão e o publicano (Mt 18,6-9.17).`
    },
    {
      n: 8,
      texto: `Fizemos alguma coisa? Creio que fizemos. Apanhamos a raposa, porque percebemos a fraude. Tornaram-se manifestos os falsos católicos que se escondiam, verdadeiros saqueadores da Igreja católica. Pois, enquanto tomavas comigo o doce alimento — falo do corpo e do sangue de Cristo —, enquanto andávamos juntos e de acordo na casa de Deus (cf. Sl 54,15), havia lugar para persuadir, ou antes, ocasião para seduzir, segundo aquilo da Sabedoria: O fingido engana com a boca o seu amigo (Pr 11,9). Mas agora, segundo a sabedoria de Paulo, depois de uma e outra advertência, evitarei facilmente o herege, sabendo que quem é assim está pervertido (Tt 3,10-11), e tomarei cautela para que não seja também pervertedor. Não é pouco, pois, segundo a palavra do Sábio, que os iníquos sejam apanhados nas suas próprias ciladas (Pr 11,6), sobretudo aqueles iníquos que tomam a cautela de usar ciladas em lugar de armas. Pois neles falta de todo a capacidade de combater e de se defender. É, com efeito, gente vil e rústica, sem letras e inteiramente incapaz de combater. Enfim, são raposas, e pequenas; mas nem sequer as coisas em que se diz que pensam mal são defensáveis, nem são tão sutis quanto persuasivas, e isso só para mulherzinhas rústicas e ignorantes — como, aliás, são todos os que até agora conheci desta seita. Pois, em todas as suas afirmações, que são muitas, não me lembro de ter ouvido nada de novo ou de inaudito, mas coisas batidas e rebatidas entre os antigos hereges, e trituradas e dispersadas pelos nossos. É preciso dizer, contudo, e direi, quais são essas tolices: em parte as que eles mesmos confessaram, respondendo com pouca cautela aos católicos que os interrogavam; em parte as que, divididos e brigando entre si, denunciaram uns dos outros; em parte também as que alguns deles, voltando à Igreja, revelaram; não que eu responda a todas, pois não é necessário, mas só para que sejam conhecidas. Mas isto será obra de outro sermão, para louvor e glória do nome do esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
