SERMOES.sermao({
  id: 'bernardo-cantico-61',
  colecao: 'bernardo-cantico',
  ordem: 61,
  numero: 'LXI',
  titulo: 'De como a Igreja encontra as riquezas da misericórdia divina nas fendas das chagas de Cristo; e da fortaleza que os mártires receberam de Cristo',
  fonte: 'Quomodo Ecclesia reperit divitias divinae misericordiae in foraminibus vulnerum Christi',
  argumento: `Pela primeira vez o esposo chama a amada abertamente de "esposa", justamente quando a leva às vinhas, onde se aproxima o vinho da caridade. E pede-lhe o que ela costumava pedir: que lhe mostre o rosto e lhe faça ouvir a voz, lá nas fendas da rocha. Bernardo adverte que tudo isso se deve ouvir com ouvidos castos: não se trata de um homem e uma mulher, mas do Verbo e da alma.

As fendas da rocha são as chagas de Cristo, e este é um dos grandes textos da devoção medieval às chagas. Nelas a pomba se esconde do gavião; nelas o pecador, perturbado pelos seus pecados, não se desespera, porque nenhum mal é tão mortal que a morte de Cristo não desfaça. Pelas aberturas do corpo fica patente o segredo do coração: o cravo que penetra tornou-se chave que abre. "O meu mérito é a misericórdia do Senhor", e a sua justiça é um manto largo que cobre os dois. Nesta vida vemos as costas do Senhor, pálidas como ouro na morte; e é dessa rocha que vem a fortaleza dos mártires: morando nas chagas de Cristo, o mártir não sente as suas, não por insensibilidade, mas por amor.

Tradução feita do texto latino de Migne (PL 183, 1070-1074).`,
  pontos: [
    {
      n: 1,
      texto: `Levanta-te, minha amiga, minha esposa, e vem (Ct 2,13). O esposo mostra o seu grande amor repetindo as palavras de amor. Pois a repetição é expressão do afeto; e, ao incitar de novo a amada ao trabalho das vinhas, mostra quanto se preocupa com a salvação das almas. Pois já ouvistes que as vinhas são as almas. Não nos demoremos sem necessidade no que já foi dito. Vede o que se segue. Contudo, em toda esta obra, se bem me lembro, ainda não a tinha chamado abertamente esposa, senão agora, quando se vai às vinhas, quando se aproxima o vinho da caridade. E, quando esta vier e for perfeita, fará o matrimônio espiritual; e serão dois, não numa só carne, mas num só espírito, como diz o Apóstolo: Quem se une a Deus é um só espírito com ele (1Cor 6,17).`
    },
    {
      n: 2,
      texto: `Segue-se: Minha pomba, nas fendas da rocha, nas cavidades do muro, mostra-me o teu rosto, ressoe a tua voz aos meus ouvidos (Ct 2,14). Ama, e continua a dizer palavras de amor. Chama-a de novo, com carinho, pomba; diz que é sua e reivindica-a como própria; e aquilo que ela costumava pedir-lhe com insistência, agora, invertendo os papéis, é ele que lhe pede: que se deixe ver e que converse com ele. Age como esposo; mas, como pudico, envergonha-se do público, e decide gozar das suas delícias num lugar retirado: nas fendas da rocha e nas cavidades do muro. Imagina, pois, que o esposo diz assim: Não temas, amiga, que este trabalho das vinhas a que te exortamos vá impedir ou interromper a obra do amor. Haverá nele, sem dúvida, alguma ocasião também para aquilo que ambos desejamos. As vinhas têm muros de pedra, e estes são refúgios agradáveis para os pudicos. Este é o jogo da letra. Por que não diria jogo? Que há de sério na sequência desta letra? O que soa por fora nem sequer é digno de ser ouvido, se o Espírito não ajudar por dentro a fraqueza do nosso entendimento. Não fiquemos, pois, de fora, para não parecer — Deus nos livre! — que andamos a recitar as seduções de amores torpes; trazei ouvidos castos ao sermão sobre o amor que temos entre mãos; e, quando pensardes nos próprios amantes, deveis entender não um homem e uma mulher, mas o Verbo e a alma. E, se disser Cristo e a Igreja, é o mesmo; salvo que com o nome de Igreja não se designa uma só alma, mas a unidade de muitas, ou antes, a sua unanimidade. E não julgueis que as fendas da rocha ou as cavidades do muro são esconderijos dos que praticam a iniquidade, para que não surja suspeita nenhuma de obras das trevas.`
    },
    {
      n: 3,
      texto: `Outro expôs assim este passo, interpretando as fendas da rocha como as chagas de Cristo. E com toda a razão, pois a rocha é Cristo (cf. 1Cor 10,4). Boas fendas, que confirmam a fé na ressurreição e na divindade de Cristo. Meu Senhor, diz, e meu Deus (Jo 20,28). De onde se trouxe este oráculo, senão das fendas da rocha? Nelas o pardal encontrou casa para si, e a rola um ninho onde pôr os seus filhotes (Sl 83,4); nelas a pomba se põe a salvo e olha sem medo para o gavião que voa ao redor. E por isso diz: Minha pomba, nas fendas da rocha. Voz da pomba: Sobre a rocha me elevou (Sl 26,6); e ainda: Firmou, diz, os meus pés sobre a rocha (Sl 39,3). O homem sábio edifica a sua casa sobre a rocha, porque ali não teme a violência dos ventos nem das enchentes (Mt 7,24-25). Que bem não há na rocha? Sobre a rocha estou elevado, sobre a rocha estou seguro, sobre a rocha estou firme. Seguro contra o inimigo, forte contra a queda; e isto porque estou elevado da terra. Pois tudo o que é terreno é incerto e caduco. Esteja no céu a nossa cidadania (cf. Fl 3,20), e não temeremos nem cair nem ser derrubados. No céu está a rocha; nela está a firmeza e a segurança. A rocha é refúgio dos ouriços (Sl 103,18). E, na verdade, onde há segurança e repouso protegido e firme para os fracos, senão nas chagas do Salvador? Lá habito tanto mais seguro quanto mais poderoso ele é para salvar. O mundo ruge, o corpo pesa, o diabo arma ciladas: não caio, porque estou fundado sobre a rocha firme. Pequei um grande pecado: a consciência se perturbará, mas não se transtornará, porque me lembrarei das chagas do Senhor. Pois foi ferido por causa das nossas iniquidades (Is 53,5). Que há de tão mortal que não seja desfeito pela morte de Cristo? Se, pois, me vier à mente um remédio tão poderoso e tão eficaz, já nenhuma malignidade da doença me pode assustar.`
    },
    {
      n: 4,
      texto: `Por isso é claro que errou aquele que disse: A minha iniquidade é grande demais para que eu mereça perdão (Gn 4,13). A não ser que não era dos membros de Cristo, nem lhe dizia respeito o mérito de Cristo, de modo que pudesse contar com ele como seu e chamar seu o que era de Cristo, como o membro chama seu o que é da cabeça. Mas eu tomo para mim com confiança, das entranhas do Senhor, o que me falta por mim mesmo, porque transbordam de misericórdia; e não faltam as aberturas por onde ela escorra. Traspassaram-lhe as mãos e os pés (cf. Sl 21,17), e furaram-lhe o lado com a lança (cf. Jo 19,34); e por estas fendas posso sugar mel da rocha e óleo da pedra duríssima (cf. Dt 32,13), isto é, provar e ver como o Senhor é suave (Sl 33,9). Ele tinha pensamentos de paz (cf. Jr 29,11), e eu não o sabia. Pois quem conheceu o pensamento do Senhor? Ou quem foi o seu conselheiro (Rm 11,34)? Mas o cravo que penetra tornou-se para mim a chave que abre, para que eu veja a vontade do Senhor. Por que não veria pela abertura? Clama o cravo, clama a chaga, que verdadeiramente Deus estava em Cristo reconciliando consigo o mundo (2Cor 5,19). O ferro traspassou a sua alma (cf. Sl 104,18) e chegou-lhe ao coração, para que já não deixe de saber compadecer-se das minhas fraquezas (cf. Hb 4,15). Pelas aberturas do corpo fica patente o segredo do coração; fica patente aquele grande mistério da piedade, ficam patentes as entranhas de misericórdia do nosso Deus, com as quais nos visitou o Sol nascente que vem do alto (Lc 1,78). Por que não ficariam as entranhas patentes pelas chagas? Pois em que brilharia mais claramente do que nas tuas chagas que tu, Senhor, és suave e manso e cheio de misericórdia (Sl 85,5)? Pois ninguém tem maior misericórdia do que aquele que dá a vida pelos votados à morte e pelos condenados (cf. Jo 15,13).`
    },
    {
      n: 5,
      texto: `O meu mérito, pois, é a misericórdia do Senhor. Não sou de todo pobre de méritos enquanto ele não o for de misericórdias. E, se as misericórdias do Senhor são muitas (cf. Sl 118,156), também eu sou rico de méritos. Que importa que tenha consciência de muitas faltas? Pois onde abundou o delito, superabundou a graça (Rm 5,20). E, se as misericórdias do Senhor são desde sempre e para sempre (Sl 102,17), também eu cantarei eternamente as misericórdias do Senhor (Sl 88,2). Acaso as minhas justiças? Senhor, recordarei só a tua justiça (Sl 70,16). Pois também ela é minha: tu te fizeste para mim justiça que vem de Deus (cf. 1Cor 1,30). Acaso devo temer que uma só não baste para os dois? Não é um manto curto, que, segundo o profeta, não possa cobrir dois (Is 28,20). A tua justiça é justiça eterna (Sl 118,142). Que há de mais longo que a eternidade? Uma justiça larga e eterna cobrirá largamente a ti e a mim. E em mim cobre a multidão dos pecados (cf. 1Pd 4,8); mas em ti, Senhor, que cobre senão os tesouros da piedade, as riquezas da bondade? Estas estão guardadas para mim nas fendas da rocha. Quão grande é nelas a abundância da tua doçura (cf. Sl 30,20) — escondida, sim, mas para os que se perdem (cf. 2Cor 4,3)! Pois para que se daria o que é santo aos cães, ou as pérolas aos porcos (cf. Mt 7,6)? Mas a nós Deus revelou-o pelo seu Espírito (1Cor 2,10), e, abertas as fendas, introduziu-nos no santuário. Quanta abundância de doçura há nelas, que plenitude de graça, que perfeição de virtudes!`
    },
    {
      n: 6,
      texto: `Irei a estas despensas tão cheias e, segundo o conselho do profeta, deixarei as cidades e habitarei na rocha (Jr 48,28). Serei como a pomba que faz o ninho na borda mais alta da fenda, para que, posto com Moisés na fenda da rocha, quando o Senhor passar, mereça ao menos ver as suas costas (Ex 33,22-23). Pois o rosto de quem está de pé, isto é, a claridade do imutável, quem o veria, senão quem já mereceu ser introduzido, não no santuário, mas no Santo dos Santos? Mas não é vil nem desprezível a contemplação das costas. Despreze-a Herodes; eu tanto menos a desprezo quanto mais desprezível ele se mostrou a Herodes (cf. Lc 23,11). Também as costas do Senhor têm alguma coisa que dá gosto ver. Quem sabe se Deus se voltará e perdoará, e deixará atrás de si uma bênção (Jl 2,14)? Virá o tempo em que mostrará o seu rosto, e seremos salvos (cf. Sl 79,4). Mas por ora venha ao nosso encontro com bênçãos de doçura (cf. Sl 20,4), aquelas que costuma deixar atrás de si. Mostre agora as costas da sua condescendência, ele que depois mostrará o seu rosto na glória da sua dignidade. Sublime no reino, mas suave na cruz. Nesta visão venha ao meu encontro; naquela me sacie. Tu me encherás, diz, de alegria com o teu rosto (Sl 15,11). Ambas as visões são salutares, ambas suaves; mas aquela está na sublimidade, esta na humildade; aquela no esplendor, esta na palidez.`
    },
    {
      n: 7,
      texto: `Enfim, diz: E as suas costas têm a palidez do ouro (Sl 67,14). Como não empalideceria na morte? Mas melhor é o ouro pálido que o latão reluzente, e o que é loucura em Deus é mais sábio que os homens (1Cor 1,25). O ouro é o Verbo, o ouro é a Sabedoria. Este ouro descoloriu-se a si mesmo, escondendo a forma de Deus e mostrando a forma de servo (cf. Fl 2,6-7). Descoloriu também a Igreja, que diz: Não repareis em eu ser morena, porque o sol me queimou (Ct 1,5). Também as suas costas, pois, têm a palidez do ouro, porque não se envergonhou do escuro da cruz, não teve horror da queimadura da paixão, não fugiu das marcas roxas das chagas. E ela se compraz nelas, e deseja que o seu fim seja semelhante a elas. Por isso, enfim, ouve: Minha pomba, nas fendas da rocha — porque vive com toda a devoção nas chagas de Cristo e se demora nelas em meditação contínua. Daí lhe vem a constância no martírio, daí a grande confiança junto do Deus altíssimo. Não há por que o mártir tema levantar o rosto sem sangue e roxo para aquele por cujas feridas foi curado (cf. Is 53,5), e apresentar-lhe a gloriosa semelhança da sua morte, com a palidez do ouro. Que temeria aquele a quem o próprio Senhor diz: Mostra-me o teu rosto? Para quê? Parece-me que ele quer antes mostrar-se a si mesmo. Assim é: quer ser visto, não ver. Pois que é que ele não vê? Não precisa de que alguém se lhe mostre, a ele que vê tudo, ainda que alguém se esconda. Quer, pois, ser visto: o chefe benigno quer que o soldado devoto levante o rosto e os olhos para as suas chagas, para lhe erguer por isso o ânimo e, com o seu exemplo, torná-lo mais forte para suportar.`
    },
    {
      n: 8,
      texto: `Pois não sentirá as suas feridas enquanto contemplar as dele. O mártir está de pé, exultando e triunfando, ainda que com o corpo todo dilacerado; e, enquanto o ferro lhe esquadrinha os flancos, olha não só com fortaleza, mas até com alegria, o sangue sagrado a borbulhar da sua carne. Onde está então a alma do mártir? Em lugar seguro, sem dúvida: na rocha, nas entranhas de Jesus, cujas chagas estão abertas para se entrar. Se estivesse nas suas próprias entranhas, sentiria sem dúvida o ferro que as esquadrinha; não suportaria a dor, sucumbiria e negaria. Mas agora, morando na rocha, que admira se se tornou dura como a rocha? Nem admira que, exilada do corpo, não sinta as dores do corpo. E isto não o faz a insensibilidade, mas o amor. Pois o sentido é submetido, não perdido; a dor não falta, mas é vencida, é desprezada. Da rocha, pois, vem a fortaleza do mártir; daí se torna capaz de beber o cálice do Senhor. E este cálice que embriaga, quão esplêndido é (Sl 22,5)! Esplêndido, digo, e alegre, não menos para o comandante que o contempla do que para o soldado que triunfa. Pois a alegria do Senhor é a nossa fortaleza (Ne 8,10). Por que não se alegraria com a voz de uma confissão tão forte? Enfim, até a pede com desejo, dizendo: Ressoe a tua voz aos meus ouvidos. E não tardará a retribuir, segundo a sua promessa: logo que alguém o tiver reconhecido diante dos homens, também ele o reconhecerá diante de seu Pai (Mt 10,32). Interrompamos o sermão, pois não pode terminar agora; e, para que não fique sem medida, não queiramos abranger num só sermão tudo o que ainda resta do capítulo proposto. Guardemos, pois, o que resta para outro princípio, para que o esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos, se alegre tanto com a nossa palavra como com a nossa medida. Amém.`
    }
  ]
});
