SERMOES.sermao({
  id: 'bernardo-cantico-44',
  colecao: 'bernardo-cantico',
  ordem: 44,
  numero: 'XLIV',
  titulo: 'Da correção, que se deve moderar segundo o caráter dos que pecam: os humildes e dóceis, com brandura; os duros e obstinados, com severidade',
  fonte: 'De correptione pro ingenio peccantium moderanda',
  argumento: `Depois da mirra, o cacho: Cristo, amargo na morte, é vinho na ressurreição. Engadi quer dizer "fonte do cabrito" ou "olho da tentação", e as suas vinhas eram, dizem, plantações de bálsamo; por isso Bernardo vê nelas a Igreja, que tem o óleo da mansidão para os pequenos e os penitentes. Mas o ferido da parábola foi curado com óleo e vinho: quem corrige precisa também do vinho do zelo, e, se a brandura não basta, deve passar à repreensão dura, e até à censura da Igreja.

De onde vem cada um? O óleo vem do amor ao próximo, que nasce do amor natural que cada um tem por si mesmo. As "moscas moribundas" das concupiscências estragaram esse perfume: o homem, como o filho mais novo da parábola, quis ter sozinho o que só se goza em comum, e ficou áspero e sem afeto; só a graça o faz voltar a ser homem. O vinho vem do amor de Cristo: quem o ama não suporta vê-lo ofendido. O sermão termina, mais uma vez, cortado pela doença de Bernardo.

Tradução feita do texto latino de Migne (PL 183, 995-999).`,
  pontos: [
    {
      n: 1,
      texto: `O meu amado é para mim um cacho de Chipre nas vinhas de Engadi (Ct 1,13). Se o amado é amado na mirra, muito mais na suavidade do cacho. O meu Senhor Jesus, pois, mirra para mim na morte, cacho na ressurreição, fez de si mesmo para mim uma bebida salubérrima, dando-me a beber lágrimas em medida (cf. Sl 79,6). Morreu por causa dos nossos pecados e ressuscitou para a nossa justificação (Rm 4,25), para que, mortos para os pecados, vivamos para a justiça (1Pd 2,24). Por isso, se choraste os pecados, bebeste a amargura; mas, se já respiraste na esperança da vida, levando uma vida mais santa, a amargura da mirra se mudou para ti em vinho que alegra o coração do homem (Sl 103,15). E talvez seja isto o que significou o vinho misturado com mirra que ofereceram ao Salvador na cruz (cf. Mc 15,23); e não o quis beber, porque tinha sede deste outro. Tu, pois, que depois das amarguras da mirra, como disse, experimentas o vinho da alegria, poderás dizer também tu, e não sem razão: O meu amado é para mim um cacho de Chipre nas vinhas de Engadi. Engadi tem duas interpretações, e ambas servem a um só sentido. Pois quer dizer fonte do cabrito, que é o batismo dos gentios, e designa claramente as lágrimas dos que pecam. Quer dizer também olho da tentação, olho que igualmente derrama lágrimas e prevê as tentações, que nunca faltam à vida do homem sobre a terra (cf. Jó 7,1). Mas também o povo dos gentios, que andava nas trevas (Is 9,2), nunca pôde por si mesmo reconhecer os laços das tentações, e por isso nem escapar deles, até que, pela graça daquele que ilumina os cegos, recebeu os olhos da fé; até que veio à Igreja, que tem o olho da tentação; até que se entregou, para ser instruído, aos homens espirituais, que, iluminados pelo espírito da sabedoria e ensinados pela própria experiência, podem dizer com verdade: Não ignoramos as astúcias do diabo e os seus pensamentos (2Cor 2,11).`
    },
    {
      n: 2,
      texto: `Dizem que em Engadi crescem arbustos de bálsamo, que os habitantes do lugar cultivam à maneira de vinhas; e talvez por isso lhes tenha chamado vinhas. De outro modo, que faria um cacho de Chipre nas vinhas de Engadi? Quem jamais levou cachos de umas vinhas para outras vinhas? Pois costuma-se levar vinho de fora para onde ele falta, não para onde há. Chama, pois, vinhas de Engadi aos povos da Igreja, que tem o licor do bálsamo, o espírito de mansidão, com que aquece com brandura a fragilidade dos que ainda são pequenos em Cristo e consola as dores dos penitentes. E, se algum irmão for surpreendido em alguma falta, o homem da Igreja que já recebeu este espírito cuidará logo de o instruir no mesmo espírito de brandura, olhando para si mesmo, para não ser também ele tentado (Gl 6,1). É nesta figura que a Igreja costuma ungir também corporalmente, com óleo material, todos os que hão de ser batizados.`
    },
    {
      n: 3,
      texto: `Mas, como as feridas daquele que caiu nas mãos dos ladrões e foi levado na montaria do corpo do piedoso Samaritano para a estalagem da Igreja não se curam só com óleo, mas com vinho e óleo juntamente (Lc 10,30-34), o médico espiritual precisa também do vinho do zelo ardente com o óleo da mansidão, pois lhe cabe não só consolar os pusilânimes, mas também corrigir os inquietos (cf. 1Ts 5,14). Pois, se vir que o ferido, isto é, o que pecou, não se emendou com as exortações brandas e suaves que primeiro lhe foram dirigidas, mas talvez até abusa da mansidão, se torna mais negligente com a paciência e adormece ainda mais seguro no seu pecado, então, frustrado o óleo de admoestações tão suaves, será preciso usar remédios mais ardidos e derramar o vinho da compunção; isto é, tratá-lo com duras repreensões e invectivas e, se o caso o exigir e a dureza for tanta, ferir o desprezador até com o bastão da censura eclesiástica. Mas de onde lhe vem este vinho? Pois nas vinhas de Engadi não se acha vinho, mas óleo. Procure-o, pois, em Chipre; pois aquela ilha é fértil em vinho, e em vinho ótimo. E, tomando de lá para si o cacho enorme que outrora os exploradores de Israel levavam numa vara (Nm 13,24) — figurando numa bela imagem o coro dos profetas que vai à frente, o dos apóstolos que vai atrás, e Jesus no meio —, tomando, pois, este cacho, diga para si: O meu amado é para mim um cacho de Chipre.`
    },
    {
      n: 4,
      texto: `Vimos o cacho; vejamos como dele se espreme o vinho do zelo. Pois, se um homem pecador não se indigna com o homem que peca, mas antes, como que destilando para ele um orvalho de bálsamo suavíssimo, lhe mostra um afeto piedoso de compaixão, sabemos de onde isto vem, e já o ouvistes, mas talvez não reparastes. Pois foi dito que a cada um vem da consideração de si mesmo o ser manso com todos, quando o homem, seguindo o conselho do sapientíssimo Paulo, para saber condescender com piedade aos que foram surpreendidos no pecado, olha para si mesmo, para não ser também ele tentado (Gl 6,1). Não é daqui, enfim, que tira a sua raiz o amor do próximo, de que se manda na lei: Amarás o teu próximo como a ti mesmo (Lc 10,27)? O amor fraterno tira dos mais íntimos afetos humanos o princípio do seu nascimento; e de uma certa doçura natural que o homem traz inata para consigo mesmo, como de uma seiva da terra, toma sem dúvida o vigor e a força pelos quais, soprando do alto a graça, produz frutos de piedade; de modo que a alma não julgue dever negar ao que partilha a sua natureza, isto é, a outro homem, por um certo direito de humanidade, onde puder e convier, o que naturalmente deseja para si, mas o reparta de boa vontade e com gosto. Há, pois, na natureza, se o pecado não a estraga, uma espécie de licor de suavidade grata e excelente, de modo que ela se sente e se mostra mais branda para se compadecer dos que pecam do que áspera para se indignar.`
    },
    {
      n: 5,
      texto: `Mas, como, segundo a sentença do Sábio, as moscas moribundas estragam este perfume de suavidade (Ecl 10,1), e a natureza não tem em si com que o recuperar, uma vez perdido, sente-se cair, por uma triste mudança, naquilo que a Escritura diz com verdade: Os sentidos e os pensamentos do homem inclinam-se para o mal desde a juventude (Gn 8,21). Não é boa a juventude em que o filho mais novo pede que lhe separem a sua parte dos bens paternos, e começa a querer dividir um bem que se possui com mais doçura em comum, e a ter sozinho o que não diminui quando se partilha, e se perde quando se reparte. Enfim: Dissipou, diz, todos os seus bens, vivendo dissolutamente com meretrizes (Lc 15,13.30). Que meretrizes são estas? Vê se não são elas que estragam o perfume da suavidade, isto é, as concupiscências carnais, a respeito das quais a Escritura te adverte de modo muito salutar: Não vás atrás das tuas concupiscências (Eclo 18,30). E com razão o Sábio as descreve como moribundas, porque o mundo passa, e também a sua concupiscência (1Jo 2,17). Enquanto, pois, queremos satisfazê-las cada um para si, privamo-nos da suavidade singular do bem social e comum. Estas são, sem dúvida, as moscas imundas e que picam, que sujam em nós a beleza da natureza, dilaceram a mente com cuidados e preocupações e estragam a suavidade da graça social. Daí se chama ao homem filho mais novo, porque a natureza, depravada por uma espécie de escorregão da juventude insensata, perdeu toda a seiva da maturidade e da sabedoria viril; e, tornado áspero, com o ânimo seco, despreza todos menos a si mesmo, feito sem afeto (cf. Rm 1,31).`
    },
    {
      n: 6,
      texto: `Desde o começo desta péssima e misérrima juventude, pois, os sentidos e os pensamentos do homem inclinam-se para o mal, e a natureza está mais pronta para se indignar do que para se compadecer. Daí que o homem, como que despido de todo o homem, naquilo em que quer que os homens o socorram quando precisa, não quer ele mesmo socorrer os homens que precisam. Antes, o homem julga, despreza, escarnece os homens; o pecador, os que caem, sem olhar para si mesmo, para não ser também ele tentado. Deste mal, como disse, a natureza de modo nenhum se levantará por si mesma, nem recuperará o óleo da mansidão inata, uma vez que nela foi estragado. Mas o que a natureza não pode, pode a graça. Aquele homem, pois, de quem a unção do Espírito se compadecer e a quem se dignar banhar de novo com a sua benignidade, esse logo voltará a ser homem, e ainda receberá da graça alguma coisa melhor do que da natureza. Ela o fará santo na fé e na mansidão (cf. Eclo 45,4), e lhe dará não óleo, mas bálsamo, nas vinhas de Engadi.`
    },
    {
      n: 7,
      texto: `Pois não há dúvida de que da fonte do cabrito brotam carismas melhores, pois a sua unção transforma os cabritos em cordeiros e passa os pecadores da esquerda para a direita, depois de os ter banhado primeiro mais abundantemente com a unção da misericórdia, para que, onde abundaram os delitos, superabunde também a graça (Rm 5,20). Não te parece que voltou verdadeiramente, de certo modo, a ser homem aquele que, depondo a ferocidade da alma mundana e recuperando, e até com juros da graça, a unção da mansidão humana, que as moscas das cobiças carnais nele tinham estragado de todo, tira do homem que traz consigo — ou antes, que ele mesmo é — a matéria e o modelo para se compadecer dos outros homens, de modo que tem horror, como de uma goela de fera, não só de fazer a qualquer homem o que não quereria sofrer, mas também de deixar de fazer a todos tudo o que quereria que lhe fizessem (cf. Mt 7,12)?`
    },
    {
      n: 8,
      texto: `Eis de onde vem o óleo. E o vinho, de onde? Sem dúvida, do cacho de Chipre. Pois, se amas o Senhor Jesus de todo o coração, de toda a alma, com todas as tuas forças, poderás acaso ver as injúrias que lhe fazem e o desprezo com que o tratam e suportá-los com ânimo tranquilo? De modo nenhum; mas logo, arrebatado pelo espírito de julgamento e pelo espírito de ardor (cf. Is 4,4), e como um valente embriagado de vinho (Sl 77,65), cheio do zelo de Fineias (cf. Nm 25,11), dirás com Davi: O meu zelo me consumiu, porque os meus inimigos esqueceram as tuas palavras (Sl 118,139); e com o Senhor: O zelo da tua casa me devora (Sl 68,10; Jo 2,17). Este zelo ardentíssimo é, pois, o vinho espremido do cacho de Chipre, e o cálice que embriaga é o amor de Cristo. Enfim, o nosso Deus é um fogo devorador (Dt 4,24), e o profeta dizia que um fogo enviado do alto lhe entrara nos ossos (Lm 1,13), porque ardia de amor divino. Tendo, pois, do amor fraterno o óleo da mansidão, e do amor divino o vinho do zelo, aproxima-te seguro para curar as feridas daquele que caiu nas mãos dos ladrões, excelente imitador do piedosíssimo Samaritano. Dize também tu com segurança, com a esposa: O meu amado é para mim um cacho de Chipre nas vinhas de Engadi — isto é: o zelo da justiça, que é o amor do meu amado, está para mim nos afetos da piedade. E basta disto. Pois a minha fraqueza manda parar, como faz muitas vezes, de modo que, como sabeis, muitas vezes sou obrigado a deixar incompletas as discussões e a reservar para outro dia o resto dos capítulos. Mas quê? Eu estou pronto para os açoites (Sl 37,18), sabendo que ainda recebo muito menos do que mereço. Que eu apanhe, sim, que apanhe como quem obra mal, na esperança de que os golpes me sejam contados como mérito; talvez se compadeça do açoitado aquele que não encontra em mim bem que recompense, o esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
