SERMOES.sermao({
  id: 'bernardo-cantico-84',
  colecao: 'bernardo-cantico',
  ordem: 84,
  numero: 'LXXXIV',
  titulo: 'Que a alma que busca a Deus foi antecipada por ele; e que é aquela busca em que ele já se antecipou a ela',
  fonte: 'Quod anima quaerens Deum, praeventa est ab eo',
  argumento: `Buscar a Deus é o primeiro dos dons e o último dos progressos, e não termina nem quando ele é encontrado: o feliz encontro não extingue o desejo, mas o dilata — um desejo sem ânsia, porque o amado está presente. Mas a alma que busca deve saber que foi buscada primeiro, para não transformar um grande bem num grande mal, atribuindo a si o que recebeu: quem é ótimo pela graça e se gloria dela torna-se péssimo. Sem ser buscada pelo Verbo, a alma, abandonada a si, é "um sopro que vai e não volta"; o próprio querer voltar já é efeito da busca de Deus, que precisa de a buscar de novo para lhe dar também o poder.

A esposa foi antecipada com duas bênçãos: o amor, causa da busca, e a busca, fruto e garantia do amor. Bernardo aplica a si mesmo a figura da adúltera que ousa voltar ao marido que desprezou; e ouve a alma responder: "Não temo, porque amo; e não amaria, se não fosse amada". Aos principiantes, que ainda não o experimentaram, remete à palavra de Deus em Jeremias: "Prostituíste-te com muitos amantes; e, contudo, volta para mim, e eu te receberei".

Tradução feita do texto latino de Migne (PL 183, 1184-1187).`,
  pontos: [
    {
      n: 1,
      texto: `No meu pequeno leito, durante as noites, busquei aquele a quem a minha alma ama (Ct 3,1). Grande bem é buscar a Deus. Eu não o julgo inferior a nenhum dos bens da alma. É o primeiro dos dons e o último dos progressos. Não vem depois de nenhuma virtude, nem cede a nenhuma. Depois de qual viria, se nenhuma o precede? A qual cederia, se é antes a consumação de todas? Pois que virtude se pode atribuir a quem não busca a Deus? Ou que termo tem quem busca a Deus? Buscai, diz, sempre a sua face (Sl 104,4). Penso que nem mesmo quando for encontrado se deixará de buscar. Deus não se busca com os passos dos pés, mas com os desejos. E o feliz encontro não extingue o santo desejo, mas o estende. Acaso consumar-se a alegria é consumir-se o desejo? É antes azeite para ele, pois o desejo é chama. Assim é. A alegria será plena; mas não haverá fim para o desejo, e por isso nem para a busca. Tu, porém, pensa, se podes, neste empenho de buscar sem carência, e neste desejo sem ânsia. Pois uma coisa exclui-a a presença, a outra a abundância.`
    },
    {
      n: 2,
      texto: `Vede agora por que disse isto primeiro. Para que toda alma entre vós que busca a Deus, a fim de não torcer um grande bem num grande mal para si, saiba que nisto foi antecipada, e que foi buscada antes de buscar. Pois assim costumam nascer de grandes bens males não pequenos: quando, tornados insignes pelos bens do Senhor, usamos dos dons como se não nos tivessem sido dados, e não damos glória a Deus. Assim, os que pareciam muito grandes pela graça recebida são tidos por muito pequenos diante de Deus, por não a terem retribuído. Eu, porém, poupo-vos. Usei palavras mais moderadas, "muito grandes" e "muito pequenos"; mas não exprimi o que penso. Envolvi o perigo; eu mesmo o desvendarei: devia ter dito "ótimos" e "péssimos". Pois, verdadeiramente e sem dúvida, cada um é péssimo por aquilo mesmo em que é ótimo, se atribuir a si mesmo aquilo pelo qual é ótimo. Isto, sim, é péssimo. E, se alguém disser: Longe disso! Reconheço que pela graça de Deus sou o que sou (1Cor 15,10); mas procurar colher uma gloriazinha pela graça que recebeu, não é ser ladrão e salteador? Ouça quem é assim: Pela tua boca te julgo, servo mau (Lc 19,22). Que há de mais mau que um servo que usurpa para si a glória do seu senhor?`
    },
    {
      n: 3,
      texto: `No meu pequeno leito, durante as noites, busquei aquele a quem a minha alma ama. A alma busca o Verbo, mas porque foi primeiro buscada pelo Verbo. De outro modo, uma vez saída ou expulsa da face do Verbo, o seu olho não voltará a ver o bem (cf. Jó 7,7), se não for buscada pelo Verbo. Como se a nossa alma fosse outra coisa, se for abandonada a si mesma, senão um sopro que vai e não volta (Sl 77,39). Ouve a fugitiva e extraviada, do que se lamenta e o que pede: Andei errante como ovelha perdida: busca o teu servo (Sl 118,176). Ó homem, queres voltar? Mas, se a coisa depende da vontade, por que pedes ajuda? Por que mendigas de outrem aquilo em que tens abundância? É claro que quer e não pode; é um sopro que vai e não volta, embora esteja mais longe aquele que nem sequer quer. Mas eu não diria que está de todo desamparada ou abandonada a alma que deseja voltar e pede para ser buscada. Pois de onde lhe vem esta vontade? Daí, se não me engano: de que já foi visitada e buscada pelo Verbo. E não foi inútil a busca que produziu a vontade, sem a qual não podia haver volta. Mas não basta ser buscada uma vez: tão grande é a languidez da alma, e tão grande a dificuldade da volta. Pois que adianta querer? A vontade jaz por terra, se não há capacidade. Pois diz: O querer está ao meu alcance, mas não encontro o modo de realizar o bem (Rm 7,18). Que busca, pois, aquele que tiramos do salmo? Nada mais do que ser buscado; o que não buscaria, se não tivesse sido buscado; e, de novo, não o buscaria, se tivesse sido buscado o bastante. E é isto que pede, dizendo: Busca o teu servo; para que aquele que deu o querer dê também o realizar, segundo o seu beneplácito (cf. Fl 2,13).`
    },
    {
      n: 4,
      texto: `A mim, porém, não parece que esta passagem possa convir a uma alma deste tipo, que ainda não recebeu a segunda graça, e quer, mas não consegue ir ter com aquele a quem a sua alma ama. Pois como pode convir-lhe o que ali se segue: levantar-se e percorrer a cidade, e buscar o amado pelas ruas e praças (Ct 3,2), se ela mesma precisa de ser buscada? Faça isto quem pode; contanto que se lembre de que foi buscada primeiro, assim como foi amada primeiro, e de que daí vem que busca e que ama. Oremos também nós, caríssimos, para que estas misericórdias se antecipem depressa a nós, porque estamos extremamente pobres (cf. Sl 78,8); e não digo isto de todos vós. Pois sei que muitíssimos de vós andam no amor com que Cristo nos amou (cf. Ef 5,2) e o buscam com simplicidade de coração (cf. Sb 1,1). Mas há alguns — digo-o com tristeza — que até agora não nos deram nenhum sinal desta antecipação tão salutar, nem, por isso, da sua salvação: homens que se amam a si mesmos (cf. 2Tm 3,2), não ao Senhor, e que buscam os seus interesses, não os do Senhor (cf. Fl 2,21).`
    },
    {
      n: 5,
      texto: `Busquei, diz ela, aquele a quem a minha alma ama. Pois a isto te incita a benignidade daquele que se antecipou a ti, que primeiro te buscou e primeiro te amou. De modo nenhum buscarias, se não tivesses sido primeiro buscada, assim como não amarias, se não tivesses sido primeiro amada. Não com uma só bênção, mas com duas foste antecipada: o amor e a busca. O amor é a causa da busca; a busca é o fruto e a garantia do amor. Foste amada, para que não suspeites que foste buscada antes para o castigo; foste buscada, para que não te queixes de ter sido amada em vão. Uma e outra suavidade, descoberta tão amiga, deu-te ousadia, afastou a vergonha, persuadiu-te a voltar e moveu o teu afeto. Daí este zelo, daí este ardor de buscar aquele a quem a tua alma ama; porque certamente não podias buscar sem ter sido buscada, nem agora, tendo sido buscada, podes deixar de buscar.`
    },
    {
      n: 6,
      texto: `Mas não te esqueças de onde vieste para aqui. E, para aplicar antes a mim o que se diz — pois isso é mais seguro —: és tu, ó minha alma, a que, deixando o teu primeiro marido, com quem estavas bem (cf. Os 2,7), violaste a primeira fé (cf. 1Tm 5,12), indo atrás dos teus amantes (cf. Os 2,5)? E agora, depois de te prostituíres com eles quanto quiseste, e talvez desprezada por eles, ousas, impudente e descarada, querer voltar para aquele que desprezaste com soberba? Quê? Digna das trevas, procuras a luz, e corres para o esposo, mais digna de açoites que de beijos? Admira que não encontres o juiz em vez do esposo. Feliz quem ouvir a sua alma responder a isto: Não temo, porque amo; o que de modo nenhum faria, se não fosse amada. Portanto, também sou amada. A amada nada tem a temer. Tremam as que não amam. Como não haviam de suspeitar continuamente de inimizades? Eu, porém, que amo, não posso duvidar de que sou amada, não mais do que de que amo. Nem posso temer o rosto daquele cujo afeto senti. Em quê? Em que não só buscou uma tal como eu, mas também a moveu de afeto, e assim a tornou certa de ter sido buscada. Como não corresponderia, buscando-o, àquele a quem correspondo com o afeto? Acaso se irará, sendo buscado, aquele que, até desprezado, fingiu não ver? Ao contrário: não repelirá quem o busca, ele que busca até quem o despreza. Benigno é o espírito do Verbo (cf. Sb 1,6), e anuncia-me coisas benignas, dando-me a conhecer e persuadindo-me do zelo e do desejo do Verbo, que certamente não lhe podem estar escondidos. Ele perscruta as profundezas de Deus (cf. 1Cor 2,10), conhecedor dos pensamentos de paz, e não de aflição, que Deus tem (cf. Jr 29,11). Como não me animaria a buscar, tendo experimentado a clemência e estando persuadida da paz?`
    },
    {
      n: 7,
      texto: `Irmãos, ser assim aconselhada é ser buscada pelo Verbo; ser persuadida é ser encontrada. Mas nem todos entendem esta palavra (cf. Mt 19,11). Que faremos com os nossos pequeninos — falo dos que ainda são incipientes entre nós, mas não insipientes, pois têm o princípio da sabedoria (cf. Sl 110,10), sujeitos uns aos outros no temor de Cristo (cf. Ef 5,21)? Como, digo, lhes faremos crer que estas coisas se passam assim com a esposa, se eles mesmos ainda não sentiram que se passem assim com eles? Mas eu os remeto a alguém em quem não devem deixar de crer. Leiam no livro o que não creem porque não o veem no coração de outro. Está escrito nos profetas: Se um homem repudiar a sua mulher, e ela, afastando-se, tomar outro marido, acaso voltará ele ainda para ela? Não ficará essa mulher manchada e contaminada? Tu, porém, te prostituíste com muitos amantes; e, contudo, volta para mim, diz o Senhor, e eu te receberei (Jr 3,1). São palavras do Senhor: não é lícito suspender a fé. Creiam o que não experimentam, para que um dia alcancem, pelo mérito da fé, o fruto da experiência. Julgo ter declarado bastante o que é ser buscado pelo Verbo, e que esta necessidade não é do Verbo, mas da alma; só que quem o experimentou conhece estas coisas mais plenamente e com mais felicidade. Resta que no tratado seguinte ensinemos as almas sedentas a buscar aquele por quem foram buscadas; ou antes, que o aprendamos daquela que aqui se apresenta buscando aquele mesmo a quem a sua alma ama, o esposo da alma, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
