SERMOES.sermao({
  id: 'bernardo-cantico-69',
  colecao: 'bernardo-cantico',
  ordem: 69,
  numero: 'LXIX',
  titulo: 'Como é abatida toda altivez que se levanta contra o conhecimento de Deus; da vinda e da morada do Pai e do Verbo na alma que ama; e da familiaridade que daí nasce entre Deus e a alma',
  fonte: 'Qualiter omnis altitudo se extollens adversus scientiam Dei dejicitur',
  argumento: `Pode uma alma sozinha dizer o que diz a Igreja inteira: "o meu amado para mim"? Bernardo responde que sim, mas não qualquer uma: a que nada ama fora de Deus, para quem viver é Cristo, que anda sempre na presença do Senhor. Duas razões lhe dão essa confiança: a natureza simplicíssima de Deus, que olha para um só como para muitos e para muitos como para um, sem se dividir; e a condescendência do Pai e do Verbo, que vêm à alma e fazem nela a sua morada — o Verbo instruindo na sabedoria, o Pai infundindo o amor dela, porque a ciência sem amor incha, e o amor sem ciência erra.

Daí uma digressão sobre o zelo do Pai pelo Filho, que abate toda altivez levantada contra o conhecimento de Deus: o anjo, que ambicionou o poder, foi julgado no furor; o homem, que ambicionou a ciência, só na ira, e por isso pode renascer. A chave dos tesouros da sabedoria está em Cristo, que a deu a Pedro, e não na serpente. Bernardo pede ser corrigido pela unção, e não pela punição: quando a Escritura se abre e uma devoção humilde afasta a vaidade, sente a presença do Verbo e do Pai. E a alma que ama sabe que foi amada primeiro: a alma que vê a Deus vê-o como se só ela fosse vista por ele.

Tradução feita do texto latino de Migne (PL 183, 1112-1116).`,
  pontos: [
    {
      n: 1,
      texto: `O meu amado para mim, e eu para ele (Ct 2,16). O sermão anterior atribuiu esta palavra à Igreja universal, por causa das promessas que Deus lhe fez da vida presente e também da futura (cf. 1Tm 4,8); e ficou proposta a questão a respeito da alma, porque uma só não pode arrogar-se o que o conjunto ousa, nem de modo algum aplicar a si aquela palavra. Se não é lícito, é preciso então referi-la à Igreja de tal maneira que de modo nenhum a uma pessoa; e não só esta, mas também as outras palavras semelhantes, que dizem coisas grandes, como por exemplo: Esperei, esperei o Senhor, e ele esteve atento a mim (Sl 39,2), e outras que o sermão anterior tocou de passagem. Mas, se alguém julga que é lícito, eu não o nego; importa, porém, a quem: pois não a qualquer um. A Igreja de Deus tem, certamente, os seus homens espirituais, que procedem nisso não só com fidelidade, mas também com confiança, falando com Deus como com um amigo (cf. Ex 33,11), e a consciência da glória dele lhes dá testemunho. Quem sejam eles, só Deus sabe; tu, porém, ouve como deves ser, se queres ser assim. O que, no entanto, eu digo não como quem experimentou, mas como quem deseja experimentar. Dá-me uma alma que nada ame além de Deus e do que se deve amar por causa de Deus; para quem viver seja Cristo (cf. Fl 1,21), e não só agora, mas já há muito tempo; cujo empenho e cujo repouso seja ter sempre o Senhor diante dos olhos (cf. Sl 15,8); para quem andar solícita com o Senhor seu Deus (cf. Mq 6,8) seja, não digo a grande, mas a única vontade, e a quem não falte a capacidade; dá-me, digo, uma alma assim, e eu não nego que seja digna do cuidado do esposo, do olhar da majestade, do favor do Senhor, da solicitude de quem governa. E, se quiser gloriar-se, não será insensata (cf. 2Cor 12,6); contanto que quem se gloria, se glorie no Senhor (1Cor 1,31). Assim, naquilo em que muitos ousam, ousa também um só, mas por outra razão.`
    },
    {
      n: 2,
      texto: `Pois o que dá confiança à santa multidão são as causas acima ditas; à alma santa, uma razão dupla. Primeiro, que a divindade do esposo, na sua natureza simplicíssima, tem a propriedade de olhar muitos como se fossem um, e um como se fosse muitos. Não se multiplica diante da multidão, nem se rarefaz diante do pequeno número; não se divide diante da diversidade, nem se restringe diante de um só; não se angustia com os cuidados, nem se perturba ou se agita com as preocupações. Está atento a um só sem ficar detido, atento a muitos sem ficar distraído. Depois — coisa tão suavíssima de experimentar quanto raríssima de ter experimentado —, é tão grande a condescendência do Verbo, tão grande a benevolência do Pai do Verbo para com a alma bem disposta e bem ordenada — o que, aliás, já é dom do Pai e obra do Verbo —, que àquela que prepararam para si, antecipando-se a ela com tal bênção, se dignam também dar a sua presença; e de tal modo que não só vêm a ela, mas fazem nela a sua morada (Jo 14,23). Pois não basta que se mostrem; é preciso que também se deixem desfrutar. Que é o Verbo vir à alma? Instruí-la na sabedoria. Que é o Pai vir? Inclinar o afeto ao amor da sabedoria, para que ela possa dizer: Tornei-me amante da sua beleza (Sb 8,2). Amar é próprio do Pai; e por isso a vinda do Pai se reconhece pelo amor infundido. Que faria a instrução sem o amor? Incharia (cf. 1Cor 8,1). E o amor sem a instrução? Erraria. Enfim, erravam aqueles de quem se dizia: Dou-lhes testemunho de que têm zelo de Deus, mas não segundo o conhecimento (Rm 10,2). Não convém que a esposa do Verbo seja tola; e, soberba, o Pai não a suporta. Pois o Pai ama o Filho (Jo 5,20), e está sempre pronto a abater e destruir toda altivez que se levanta contra o conhecimento do Verbo (cf. 2Cor 10,5), seja infundindo o seu zelo, seja apontando-o contra ela: uma coisa é da misericórdia, a outra do juízo. Oxalá reprima em mim toda altivez — ou antes, a abata e a reduza a nada — não o furor aceso, mas o amor infundido! Oxalá eu aprenda a não ser soberbo, tendo por mestra antes a unção que a punição! Senhor, não me repreendas no teu furor (cf. Sl 6,2), como ao anjo que se exaltava no céu; nem me castigues na tua ira, como ao homem no paraíso. Ambos meditaram a iniquidade, ambicionando a altura: aquele, a do poder; este, a da ciência. Enfim, a mulher insensata acreditou naquele que prometia, mas seduzia: Sereis como deuses, conhecendo o bem e o mal (Gn 3,5). Já antes se tinha seduzido a si mesmo aquele que se persuadira de que seria semelhante ao Altíssimo (Is 14,14). Pois quem julga ser alguma coisa, não sendo nada, seduz-se a si mesmo (Gl 6,3).`
    },
    {
      n: 3,
      texto: `Mas uma e outra altura foram abatidas, embora no homem mais brandamente, assim o julgando aquele que faz tudo com peso e medida (cf. Sb 11,21). Pois, tendo sido o anjo punido — ou antes, condenado — no furor, o homem sentiu apenas a ira, e não o furor. Pois, quando se irou, lembrou-se da misericórdia (cf. Hab 3,2). Por isso a sua descendência são filhos da ira (cf. Ef 2,3), e não do furor, até o dia de hoje. Se eu não nascesse filho da ira, não seria preciso renascer; se nascesse filho do furor, ou não me seria dado renascer, ou de nada me serviria. Queres ver o filho do furor? Se viste Satanás cair do céu como um raio (Lc 10,18), isto é, precipitado no ímpeto do furor, conheceste o furor de Deus. Então ele não se lembrou da sua misericórdia; porque, quando se irar, há de lembrar-se da misericórdia, mas não quando já se inflamou até o furor. Ai dos filhos da incredulidade (cf. Ef 2,2)! Ai também daqueles que, sendo de Adão e nascidos filhos da ira, eles mesmos, por uma obstinação diabólica, convertem para si a ira em furor, a vara em bastão, ou antes, em martelo. Enfim, acumulam para si ira para o dia da ira (Rm 2,5). E a ira acumulada, que é senão furor? Pecaram o pecado do diabo, e são atingidos pela sentença do diabo. Ai também, ainda que mais brandamente, de certos filhos da ira que, nascidos na ira, não esperaram renascer na graça! Mortos naquilo em que nasceram, permanecerão filhos da ira. Da ira, digo, não do furor; porque, como se crê com muita piedade e se lamenta com muita humanidade, brandíssimas são as penas dos que trazem de outra parte tudo aquilo por que foram condenados.`
    },
    {
      n: 4,
      texto: `O diabo, pois, foi julgado no furor, porque a sua iniquidade foi achada digna de ódio (cf. Sl 35,3); a do homem, porém, digna de ira, e por isso é castigado na ira. Assim foi esmagada toda altura, tanto a que incha como a que precipita, porque o Pai tem zelo pelo Filho. Pois num e noutro caso há injúria ao Filho: pelo poder usurpado contra o poder de Deus, que é ele; e pela ciência pretendida de outra fonte que não a sabedoria de Deus, que também é ele (cf. 1Cor 1,24). Senhor, quem é semelhante a ti (Sl 34,10)? Quem, senão o esplendor e a figura da tua substância (cf. Hb 1,3)? Quem, senão a tua imagem (cf. Cl 1,15)? Só ele está na tua forma; só ele, o altíssimo Filho do Altíssimo, não julgou usurpação ser igual a ti (Fl 2,6). Como não seria igual? Ele e tu sois até um só (cf. Jo 10,30). O seu lugar é à tua direita, não debaixo dos teus pés. Com que direito ousa alguém invadir o lugar do teu Unigênito? Seja precipitado. Põe para si um trono nas alturas (cf. Is 14,13)? Seja derrubada a cátedra da pestilência (cf. Sl 1,1). E ainda: quem ensina ao homem a ciência (Sl 93,10)? Não és tu, ó chave de Davi, que abres a quem queres e fechas a quem queres (cf. Ap 3,7)? E como se tentava sem a chave a entrada — ou antes, a invasão — nos tesouros da sabedoria e da ciência (cf. Cl 2,3)? Quem não entra pela porta é ladrão e salteador (Jo 10,1). Entrará, pois, Pedro, que recebeu as chaves. Não, porém, sozinho: pois também me fará entrar, se quiser, e excluirá outro, se assim quiser, na ciência e no poder que lhe foram dados do alto.`
    },
    {
      n: 5,
      texto: `E que chaves são estas? O poder de abrir e de fechar, e o discernimento entre os que devem ser excluídos e os que devem ser admitidos. E os tesouros não estão na serpente, mas em Cristo. E por isso a serpente não pôde dar a ciência, que não tinha; mas quem a tinha, deu-a. Nem pôde ela ter o poder, que não recebeu; mas quem o recebeu, teve-o. Cristo deu (Mt 16,19), Pedro recebeu, sem se inchar pela ciência, sem merecer ser precipitado pelo poder. Por quê? Porque em nenhuma das duas se levanta contra o conhecimento de Deus, ele que nada disso ambicionou à revelia do conhecimento de Deus, como aquele que agiu com dolo diante dele, de modo que a sua iniquidade foi achada digna de ódio (Sl 35,3). Como, enfim, à revelia do conhecimento de Deus, ele que se escreve apóstolo de Jesus Cristo segundo a presciência de Deus Pai (1Pd 1,1-2)? E isto fique dito a propósito do que se apresentou sobre o zelo de Deus, que ele aponta contra o anjo e o homem prevaricadores — pois em ambos encontrou maldade (cf. Jó 4,18) —; isto é, como na sua ira e no seu furor destruiu toda altura que se levanta contra o conhecimento de Deus.`
    },
    {
      n: 6,
      texto: `Agora é preciso voltar ao zelo da misericórdia, isto é, ao que não se aponta contra, mas se infunde; porque o que se aponta contra, como já dissemos, é do juízo, e já nos assustou bastante com os exemplos lembrados dos que foram punidos tão gravemente. Por isso irei eu para o lugar de refúgio, longe da face do furor do Senhor, para aquele zelo de piedade que arde suavemente e purifica eficazmente. Acaso a caridade não purifica? E poderosamente. Li que cobre a multidão dos pecados (1Pd 4,8). Mas digo: acaso não é apta e suficiente para abater e humilhar toda altivez dos olhos e do coração (cf. Sl 130,1)? E muitíssimo: pois não se exalta, não se incha (cf. 1Cor 13,4). Se, pois, o Senhor Jesus se dignar vir a mim, ou antes, em mim, não no zelo do furor, nem sequer na ira, mas na caridade e no espírito de mansidão (cf. 1Cor 4,21), zelando por mim com o zelo de Deus (cf. 2Cor 11,2) — e que há de tão próprio de Deus como a caridade? Ela é o próprio Deus (cf. 1Jo 4,8) —; se, digo, vier nela, nisto conhecerei que não está só, mas que veio também com ele o seu Pai. Pois que há de tão paterno? Por isso, com efeito, é chamado não só Pai do Verbo, mas também Pai das misericórdias (2Cor 1,3), porque lhe é inato compadecer-se sempre e perdoar. Se eu sentir que se me abre a inteligência para compreender as Escrituras (cf. Lc 24,45), ou que a palavra da sabedoria como que brota do mais íntimo, ou que, por uma luz infundida do alto, se revelam os mistérios, ou ainda que se estende sobre mim como que um regaço amplíssimo do céu, e que chuvas mais abundantes de meditações descem do alto sobre a alma, não duvido de que o esposo está presente. Pois estas riquezas são do Verbo, e é da sua plenitude que as recebemos (cf. Jo 1,16). E se ao mesmo tempo se infundir uma devoção humilde, mas rica, que me banha por dentro, de modo que o amor da verdade conhecida gere em mim um necessário ódio e desprezo da vaidade, para que nem a ciência me inche, nem a frequência das visitas me exalte, então sinto que sou tratado de modo verdadeiramente paterno, e não duvido de que o Pai está presente. E, se eu perseverar em corresponder sempre, quanto está em mim, a esta condescendência com afetos e atos dignos dela, e a graça de Deus não tiver sido vã em mim (cf. 1Cor 15,10), farão também em mim a sua morada tanto o Pai que alimenta como o Verbo que instrui.`
    },
    {
      n: 7,
      texto: `Quanta graça de familiaridade pensas que nasce desta morada entre a alma e o Verbo, e quanta confiança se segue da familiaridade? Uma tal alma, penso eu, já não tem por que recear dizer: O meu amado para mim. Pelo fato de sentir que ama, e que ama intensamente, não duvida de que também é amada intensamente; e, pela singular atenção, solicitude, cuidado, trabalho, diligência e empenho com que ela mesma vela sem cessar e ardentemente para agradar a Deus, reconhece sem dúvida nenhuma todas essas mesmas coisas nele, lembrando-se da sua promessa: Com a medida com que medirdes, sereis medidos (Mt 7,2); a não ser que a esposa prudente teve o cuidado de tomar antes para si a parte da retribuição da graça, sabendo que o amado se antecipou a ela. Daí vem que põe em primeiro lugar a obra dele, dizendo: O meu amado para mim, e eu para ele. Pelo que há nela, pois, reconhece o que há em Deus; e não duvida de que é amada, ela que ama. Assim é. O amor de Deus gera o amor da alma, e a atenção dele, que vem antes, torna a alma atenta, e a sua solicitude a torna solícita. Pois, por não sei que parentesco de natureza, quando a alma puder uma vez contemplar de rosto descoberto a glória de Deus, logo terá necessariamente de conformar-se a ele e de ser transformada na mesma imagem (cf. 2Cor 3,18). Assim, tal como te preparares para Deus, tal é preciso que Deus te apareça. Com o santo será santo, e com o homem inocente será inocente (Sl 17,26). E por que não também amante com quem ama, disponível com quem se torna disponível para ele, atento com quem está atento, e solícito com quem é solícito?`
    },
    {
      n: 8,
      texto: `Enfim, diz: Eu amo os que me amam, e os que de manhã cedo vigiarem por mim me encontrarão (Pr 8,17). Vês como te torna certo não só do seu amor, se tu o amares, mas também da solicitude que tem por ti, se te sentir solícito por ele. Vigias tu? Ele também vigia. Levanta-te de noite, ao começo das tuas vigílias (cf. Lm 2,19); apressa-te quanto quiseres, até a antecipar as próprias vigílias: hás de encontrá-lo, não de antecipar-te a ele. É temeridade, em tal assunto, atribuir-te qualquer coisa de primeiro ou de maior: ele ama mais, e ama antes. Se a alma sabe isto — ou antes, porque o sabe —, admiras-te de que se glorie de que aquela majestade, como se não cuidasse das outras coisas, esteja atenta só a ela, que, pondo de lado todos os outros cuidados, se guarda só para ele com toda a devoção? O sermão pede um fim; mas digo uma coisa aos espirituais que há entre vós, admirável, sim, mas verdadeira: a alma que vê a Deus vê-o exatamente como se só ela fosse vista por Deus. É, pois, com essa confiança que diz que ele está atento a ela, e ela a ele, não vendo nada além de si e dele. Bom és, Senhor, para a alma que te busca (cf. Lm 3,25)! Vens-lhe ao encontro, abraças, mostras-te esposo, tu que és Senhor — ou antes, que és Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
