SERMOES.sermao({
  id: 'bernardo-cantico-28',
  colecao: 'bernardo-cantico',
  ordem: 28,
  numero: 'XXVIII',
  titulo: 'Da negrura e da formosura do esposo; e de como, nas coisas da fé e para o conhecimento da verdade, o ouvido vale mais que a vista',
  fonte: 'De nigredine et formositate sponsi',
  argumento: `As peles de Salomão, lidas agora pela negrura: são as peles escuras que cobriam a tenda do rei e protegiam o adorno lá dentro. E Bernardo aplica-as a Cristo — negro por fora, formoso por dentro; negro na opinião de Herodes, formoso na confissão do ladrão e na fé do centurião.

O centurião leva ao assunto que dá nome ao sermão. Ele não reconheceu o Filho de Deus pelo que viu, mas pelo grito que ouviu: o ouvido achou o que a vista não achou. Daí uma página sobre a primazia do ouvido na fé, com Isaac, que se enganou nos olhos, no paladar e nas mãos, mas não no ouvido; e com Madalena, a quem se diz «não me toques» porque ainda confiava mais no olho do que na palavra.

Tradução feita do texto latino de Migne (PL 183, 921-928).`,
  pontos: [
    {
      n: 1,
      texto: `Guardais, creio, de que Salomão e a que peles julgo comparada a formosura da esposa — se a comparação tirada delas se refere a mostrar e louvar a beleza. Mas, se se julgar que deve referir-se antes à negrura, como a das tendas de Cedar, não me ocorre outra coisa a respeito destas peles de Salomão senão aquelas que o rei talvez usasse para a sua tenda, quando lhe aprouvesse morar sob tendas; e essas, se é que existiram, haviam de ser sem dúvida escuras e feias, expostas como estavam ao sol de cada dia e aos estragos das chuvas frequentes. E não em vão, mas para que se conservasse mais brilhante o adorno guardado lá dentro. Com este exemplo, a esposa não nega a negrura, mas desculpa-a; e não tem por vergonha nenhum aspecto que a caridade forme e que o juízo da verdade não reprove. Enfim, quem desfalece, com quem ela não desfaleça? Quem se escandaliza, que ela não queime? (2Cor 11,29) Veste-se com a mancha da compaixão, para aliviar ou curar no outro a doença da paixão; enegrece por zelo da brancura, para ganhar beleza.`
    },
    {
      n: 2,
      texto: `A negrura de um faz brancos a muitos — não quando se tinge de culpa, mas quando se deixa tomar pelo cuidado. Convém, diz ele, que morra um só homem pelo povo, e que não pereça a nação inteira (Jo 11,50): convém que um só, por todos, seja enegrecido pela semelhança da carne de pecado, e que a nação inteira não seja condenada pela negrura do pecado; que o esplendor e a imagem da substância de Deus (Hb 1,3) se anuvie na forma de servo, pela vida do servo; que a brancura da vida eterna enegreça na carne, para purificar a carne; que o mais belo dos filhos dos homens, para iluminar os filhos dos homens, se escureça na paixão, se desfigure na cruz, empalideça na morte; que não lhe fique de todo nem aparência nem beleza, para adquirir para si uma esposa bela e formosa, a Igreja, sem mancha e sem ruga. Reconheço a pele de Salomão; ou antes, abraço o próprio Salomão na pele negra. Também Salomão tem negrura, mas na pele: negro por fora, negro na cútis, não por dentro; pois toda a glória da filha do rei está dentro (Sl 44,14). Dentro estão a brancura da divindade, a beleza das virtudes, o esplendor da glória, a pureza da inocência; mas cobre tudo isso uma cor de fraqueza bem desprezível, e o seu rosto fica como escondido e desprezado (Is 53,3), enquanto é tentado em tudo, à nossa semelhança, sem pecado (Hb 4,15). Reconheço a forma da natureza enegrecida; reconheço aquelas túnicas de pele, a veste dos primeiros pais depois de pecarem (Gn 3,21). Enfim, enegreceu-se a si mesmo, tomando a forma de servo, tornando-se semelhante aos homens e reconhecido em aspecto como homem (Fl 2,7). Reconheço, sob a pele do cabrito, que significa o pecado, a mão que não cometeu pecado e o pescoço por onde não passou pensamento mau; e por isso não se achou engano na sua boca (Is 53,9). Sei que és liso por natureza, manso e humilde de coração, afável no aspecto, suave no espírito, e ungido com óleo de alegria mais que os teus companheiros (Sl 44,8). De onde vem, então, que agora sejas peludo e áspero como Esaú? De quem é esta imagem enrugada e feia, e de onde vêm estes pelos? São meus: pois as mãos peludas exprimem a semelhança do pecador. Reconheço como meus estes pelos; e na minha pele vejo Deus, meu Salvador.`
    },
    {
      n: 3,
      texto: `Mas não foi Rebeca que o vestiu assim, e sim Maria — e ele era tanto mais digno de receber a bênção quanto mais santa era a que o deu à luz. E com razão na minha veste, porque é para mim que se reclama a bênção, para mim que se pede a herança. Pois ele tinha ouvido: Pede-me, e eu te darei as nações por herança, e por possessão os confins da terra (Sl 2,8). A tua herança, diz, e a tua possessão eu te darei. Como lhe darás, se é dele? E como o exortas a pedir o que é dele? Ou como é dele, se precisa de pedir? Pede-a, pois, para mim, ele que vestiu a minha forma justamente para tomar a minha causa. Pois o castigo que nos traz a paz caiu sobre ele, como diz o profeta, e o Senhor pôs sobre ele a iniquidade de todos nós (Is 53,5-6); por isso devia assemelhar-se em tudo aos irmãos, como diz o Apóstolo, para se tornar misericordioso (Hb 2,17). Por isso a voz é a voz de Jacó, mas as mãos são as mãos de Esaú (Gn 27,22). O que se ouve dele é dele; o que se vê nele é nosso. O que diz é espírito e vida; o que aparece é mortal, e é morte. Uma coisa é o que se vê, outra o que se crê. Os sentidos dizem que é negro; a fé prova que é branco e formoso. É negro, mas aos olhos dos insensatos; para a mente dos fiéis é formosíssimo. É negro, mas formoso: negro na opinião de Herodes, formoso na confissão do ladrão e na fé do centurião.`
    },
    {
      n: 4,
      texto: `Que formoso o tinha visto aquele que exclamou: Verdadeiramente este homem era Filho de Deus! Mas é preciso reparar em que é que ele o viu. Pois, se olhasse para o que aparecia, como seria formoso, como seria Filho de Deus? Que se oferecia aos olhos de quem olhava senão algo disforme e negro, quando, de mãos estendidas na cruz, entre dois malfeitores, dava motivo de riso aos maus e de choro aos fiéis? E era objeto de riso o único que podia ser objeto de terror, o único a quem se devia honra. De onde, pois, percebeu a beleza do Crucificado, e que era Filho de Deus aquele que foi contado entre os iníquos? (Is 53,12) Não nos é lícito, nem necessário, responder a isto por nossa conta: a diligência do evangelista não deixou passar a coisa. Pois assim tens escrito: E o centurião, que estava diante dele, vendo que expirara clamando assim, disse: Verdadeiramente este homem era Filho de Deus (Mc 15,39). Creu, pois, pela voz; foi pela voz, e não pelo rosto, que reconheceu o Filho de Deus. Era, talvez, uma das suas ovelhas, de que ele diz: As minhas ovelhas ouvem a minha voz (Jo 10,27).`
    },
    {
      n: 5,
      texto: `O ouvido achou o que a vista não achou: a aparência enganou o olho, e a verdade entrou pelo ouvido. O olho declarava-o fraco, o olho declarava-o feio, o olho declarava-o desgraçado, o olho declarava-o condenado à morte mais vergonhosa; ao ouvido deu-se a conhecer como Filho de Deus, ao ouvido deu-se a conhecer como formoso — mas não ao ouvido dos judeus, porque eram incircuncisos de ouvidos (At 7,51). Com razão Pedro cortou a orelha do servo (Jo 18,10): para abrir caminho à verdade, e para que a verdade o libertasse (Jo 8,32), isto é, o fizesse livre. Aquele centurião era incircunciso, mas não de ouvido: a uma só voz de quem expirava, e sob tantos sinais de fraqueza, reconheceu o Senhor da majestade. E por isso não desprezou o que viu, porque creu no que não viu. E não creu pelo que viu, mas sem dúvida pelo que ouviu, porque a fé vem pelo ouvido (Rm 10,17). Teria sido digno que a verdade entrasse na alma pelas janelas mais altas, as dos olhos; mas isso, ó alma, fica-nos reservado para depois, quando virmos face a face. Agora, porém, entre o remédio por onde entrou a doença, e siga a vida a morte pelas mesmas pegadas, a luz as trevas, o antídoto da verdade o veneno da serpente; e cure o olho que está perturbado, para que, sereno, veja aquele que perturbado não pode ver. O ouvido, primeira porta da morte, abra-se primeiro também para a vida; o ouvido, que tirou a vista, restaure a vista; porque, se não crermos, não entenderemos (Is 7,9). O ouvido, pois, é para o mérito; a vista, para o prêmio. Daí dizer o Profeta: Ao meu ouvido darás gozo e alegria (Sl 50,10) — porque a paga fiel da escuta é a visão feliz, e o mérito da visão feliz é a escuta fiel. Felizes os puros de coração, porque verão a Deus (Mt 5,8). E o olho que há de ver a Deus deve ser purificado pela fé, como tens escrito: purificando pela fé os seus corações (At 15,9).`
    },
    {
      n: 6,
      texto: `Entretanto, pois, enquanto a vista ainda não está preparada, desperte-se o ouvido, exercite-se o ouvido, receba o ouvido a verdade. Feliz aquele de quem a Verdade testemunha: Ao ouvir a minha voz, obedeceu-me (Sl 17,45). Serei digno de ver se, antes de ver, for achado obediente; verei sem receio, se o dom da minha obediência tiver ido à frente. Quão feliz quem diz: O Senhor Deus abriu-me o ouvido, e eu não resisto, não voltei atrás (Is 50,5)! Aqui tens a forma da obediência voluntária e o exemplo da perseverança: pois quem não resiste obedece de boa vontade, e quem não volta atrás persevera. As duas coisas são necessárias, porque Deus ama quem dá com alegria (2Cor 9,7), e quem perseverar até o fim será salvo (Mt 10,22). Oxalá o Senhor me abra também a mim o ouvido, entre no meu coração a palavra da verdade, purifique-me o olho e o prepare para a visão alegre, para que também eu diga a Deus: O teu ouvido escutou a preparação do meu coração (Sl 9,17); para que também eu ouça de Deus, com os outros que obedecem: E vós já estais limpos, pela palavra que vos falei (Jo 15,3). Não são purificados todos os que ouvem, mas os que obedecem: Felizes os que ouvem e a guardam (Lc 11,28). Tal escuta pede aquele que manda: Ouve, Israel (Dt 6,4); tal escuta oferece quem diz: Fala, Senhor, que o teu servo escuta (1Sm 3,9); tal escuta promete quem diz: Ouvirei o que o Senhor Deus diz em mim (Sl 84,9).`
    },
    {
      n: 7,
      texto: `E, para saberes que também o Espírito Santo guarda esta ordem no progresso espiritual da alma — formar primeiro o ouvido, antes de alegrar a vista —, diz ele: Ouve, filha, e vê (Sl 44,11). Por que estendes o olho? Prepara o ouvido. Desejas ver Cristo? É preciso que primeiro o ouças, e que ouças falar dele, para que, quando o vires, digas: Como ouvimos, assim vimos (Sl 47,9). A claridade é imensa, a vista é estreita, e não chegas até ela. Chegas pelo ouvido, mas não pelo olhar. Quando Deus clamava — Adão, onde estás? (Gn 3,9) —, eu, já pecador, não o via; mas ouvia-o. Mas o ouvido restituirá a vista, se for à frente com piedade, com vigilância e com fé. A fé limpará o olho que a impiedade turvou; e a obediência abrirá o que a desobediência fechou. Enfim, diz o salmo: Pelos teus mandamentos adquiri entendimento (Sl 118,104) — porque a observância dos mandamentos devolve o entendimento que a transgressão tirou. Repara ainda, no santo Isaac, como, já velho, o ouvido tinha mais vigor que os outros sentidos. Os olhos do patriarca estão turvos, o paladar é enganado, a mão se engana; o ouvido não se engana. Que há de admirar que o ouvido perceba a verdade, se a fé vem pelo ouvido, e o ouvido pela palavra de Deus (Rm 10,17), e a palavra de Deus é a verdade (Jo 17,17)? A voz, diz, é a voz de Jacó. Nada mais verdadeiro. Mas as mãos são as mãos de Esaú (Gn 27,22). Nada mais falso. Enganas-te: a semelhança das mãos te enganou. Nem no gosto está a verdade, ainda que esteja a suavidade: pois como tem a verdade quem pensa comer caça, quando come carne de cabritos da casa? E muito menos o olho, que nada vê. Não está no olho a verdade, nem a sabedoria. Ai dos que sois sábios aos vossos próprios olhos!, diz o profeta (Is 5,21). Não é boa a sabedoria que é amaldiçoada: é do mundo, e por isso é loucura diante de Deus (1Cor 3,19).`
    },
    {
      n: 8,
      texto: `A sabedoria boa e verdadeira tira-se do que está escondido, como entende o bem-aventurado Jó (Jó 28,18). Por que a procuras fora, nos sentidos do corpo? O sabor está no paladar; a sabedoria, no coração. Não procures a sabedoria no olho da carne, porque não é a carne e o sangue que a revelam, mas o espírito (Mt 16,17). Nem no gosto da boca: pois não se acha na terra dos que vivem nas delícias (Jó 28,13). Nem no tato da mão, pois diz o santo: Se beijei a minha mão com a minha boca, o que é iniquidade enorme e negação de Deus (Jó 31,27-28)... O que creio acontecer quando o dom de Deus, que é a sabedoria, se atribui não a Deus, mas aos méritos das próprias ações. Isaac era sábio, e contudo se enganou nos sentidos. Só o ouvido, que recebe a palavra, possui a verdade. Com razão foi proibida de tocar a carne ressuscitada do Verbo a mulher que entendia as coisas segundo a carne: dava mais crédito ao olho do que ao oráculo, isto é, mais aos sentidos da carne do que à palavra de Deus. Pois não creu ressuscitado aquele que vira morto, embora ele mesmo o tivesse prometido. Enfim, o olho não sossegou enquanto a vista não se fartou, porque nela não havia consolação da fé, nem tinha por firme a promessa de Deus. Não hão de passar e perecer o céu e a terra, e tudo quanto o olho da carne pode alcançar, antes que passe um só i ou um só til de tudo o que Deus disse (Mt 5,18)? E, no entanto, parou de chorar ao ver com os olhos aquela que não quisera consolar-se com a palavra do Senhor, tendo em mais conta a experiência do que a fé. Mas a experiência engana.`
    },
    {
      n: 9,
      texto: `Ela é mandada, pois, para o conhecimento mais certo da fé, que alcança o que os sentidos não conhecem e a experiência não encontra. Não me toques (Jo 20,17), diz ele — isto é: desacostuma-te deste sentido fácil de enganar; apoia-te na palavra, acostuma-te à fé. A fé, que não sabe enganar-se, que abarca o invisível, não sente a pobreza dos sentidos; ultrapassa até os limites da razão humana, o curso da natureza, as fronteiras da experiência. Por que perguntas ao olho aquilo a que ele não chega? E por que tenta a mão explorar o que está acima dela? É menos do que devia tudo o que um ou outra possam dizer. Que seja a fé a pronunciar-se a meu respeito, ela que nada tira à majestade. Aprende a ter por mais certo, e a seguir com mais segurança, aquilo que ela aconselhar. Não me toques, porque ainda não subi para o meu Pai (Jo 20,17). Como se, depois de subir, quisesse ou pudesse então ser tocado por ela! E poderá, sim — mas com o afeto, não com a mão; com o desejo, não com o olho; com a fé, não com os sentidos. Por que procuras tocar-me agora, diz ele, tu que avalias a glória da ressurreição pelos sentidos do corpo? Não sabes que, ainda no tempo da minha mortalidade, os olhos dos discípulos não conseguiram suportar a glória de um corpo que havia de morrer, transfigurado por uma hora? (Mt 17,6) Por ora ainda faço a vontade aos teus sentidos, mostrando-te a forma de servo, que reconheces por costume. Mas a minha glória tornou-se admirável para ti, é alta demais, e não chegarás até ela (Sl 138,6). Adia, pois, o teu juízo, suspende a tua sentença, e não confies aos sentidos a definição de coisa tão grande: reserva-a para a fé. Ela a definirá com mais dignidade e mais certeza, porque a abarcará mais plenamente. Pois abarca, naquele seu seio místico e profundo, qual é o comprimento, a largura, a altura e a profundidade (Ef 3,18). O que o olho não viu, nem o ouvido ouviu, nem subiu ao coração do homem (1Cor 2,9), ela o traz fechado em si como num invólucro, e o guarda selado.`
    },
    {
      n: 10,
      texto: `Há de tocar-me dignamente, pois, aquela que me receber sentado junto ao Pai, já não em veste humilde, mas celeste: na mesma carne, mas com outra aparência. Por que queres tocar-me disforme? Espera, para me tocares formoso. Pois quem agora é disforme será então formoso: disforme ao tato, disforme à vista; disforme, enfim, para ti, que também és disforme, porque te prendes mais aos sentidos do que à fé. Sê formosa, e toca-me; sê fiel, e és formosa. Formosa, tocarás o formoso com mais dignidade e com mais felicidade. Tocarás com a mão da fé, com o dedo do desejo, com o abraço da devoção; tocarás com o olho da mente. E ainda negro? De modo nenhum! O teu amado é branco e rosado. Formoso, sem dúvida, aquele a quem rodeiam as flores das rosas e os lírios dos vales — isto é, os coros dos mártires e das virgens; e eu, que estou no meio, não destoo de nenhum dos dois coros, virgem e mártir que sou. Pois como não me ajustaria aos coros brancos das virgens, eu, virgem, filho da Virgem e esposo da virgem? Como não me ajustaria aos coros rosados dos mártires, eu, causa, força, fruto e modelo do martírio? Toca-me assim, sendo tu assim, e desse modo, e dize: O meu amado é branco e rosado, escolhido entre milhares (Ct 5,10). Milhares de milhares estão com o amado, e dez vezes cem mil ao redor do amado (Dn 7,10), e ninguém se compara ao amado. Hás de temer, porventura, dar por engano com algum dos da multidão, ao procurares aquele a quem amas? Não terás dúvida nenhuma sobre quem escolher. Logo te aparecerá o escolhido entre milhares, mais insigne que todos, e dirás: Este é formoso na sua veste, avançando na grandeza da sua força (Is 63,1). Não, pois, na pele negra, que até então tinha de ser posta diante dos olhos dos perseguidores, para que o desprezassem e o matassem; ou dos amigos, para que o reconhecessem vivo de novo. Não aparecerá mais, digo, na pele negra, mas em veste branca, belo de aspecto, não só acima dos filhos dos homens, mas também acima dos rostos dos anjos. Por que queres tocar-me em veste humilde, em forma de servo, em aparência desprezível? Toca-me belo de aparência celeste, coroado de glória e de honra (Sl 8,6); temível pela majestade divina, mas amável e sereno pela serenidade que me é natural.`
    },
    {
      n: 11,
      texto: `Entre estas coisas há que notar a prudência da esposa e a profundidade das suas palavras: sob a figura das peles de Salomão, isto é, na carne, ela perscrutou Deus; na morte, a vida; entre os opróbrios, o cume da glória e da honra; e, sob a veste negra do crucificado, a brancura da inocência e o esplendor das virtudes — assim como aquelas peles, sendo negras e desprezadas, guardavam em si os adornos preciosos e brancos de um rei riquíssimo. Com razão não despreza a negrura das peles, pois repara na beleza que está debaixo delas. E foi por isso que alguns desprezaram aquela: porque não conheceram esta; pois, se a tivessem conhecido, nunca teriam crucificado o Senhor da glória (1Cor 2,8). Não a conheceu Herodes, e por isso o desprezou; não a conheceu a Sinagoga, que, lançando-lhe em rosto a negrura da paixão e da fraqueza, dizia: Salvou os outros, e não pode salvar-se a si mesmo. O Cristo, rei de Israel, desça agora da cruz, e creremos nele (Mt 27,42). Mas conheceu-a o ladrão, da cruz — ele mesmo na cruz —, que confessou a pureza da sua inocência — Mas este, que mal fez? — e ao mesmo tempo proclamou a glória da sua majestade régia, dizendo: Lembra-te de mim quando entrares no teu reino (Lc 23,41-42). Conheceu-a o centurião, que o proclama Filho de Deus (Mt 27,54); conhece-a a Igreja, que imita a negrura para participar da beleza. Não se envergonha de parecer negra e de ser chamada negra, para poder dizer ao amado: Os insultos dos que te insultavam caíram sobre mim (Sl 68,10). Mas negra como as peles de Salomão: por fora, e não por dentro; pois o meu Salomão não tem negrura por dentro. Ela não diz «sou negra como Salomão», mas «como as peles de Salomão», porque a negrura do verdadeiro pacífico está só na superfície. A negrura do pecado está dentro, e a culpa mancha primeiro o interior, antes de aparecer aos olhos. Pois do coração saem os maus pensamentos, os roubos, os homicídios, os adultérios, as blasfêmias; e são estas coisas que mancham o homem (Mt 15,19-20) — mas longe de nós dizer que manchem Salomão! No verdadeiro pacífico não acharás de modo nenhum manchas destas. Pois é preciso que seja sem pecado aquele que tira os pecados do mundo (Jo 1,29), para que, achado capaz de reconciliar os pecadores, reclame com direito o nome de Salomão.`
    },
    {
      n: 12,
      texto: `Mas há a negrura da penitência que aflige, quando se toma o pranto pelos pecados. Talvez Salomão não tenha horror a esta em mim, se eu a vestir de livre vontade pelos meus pecados; porque um coração contrito e humilhado Deus não despreza (Sl 50,19). Há também a negrura da compaixão que comove, quando sofres com o aflito e o mal do irmão te tira a cor. E o nosso pacífico não julga, decerto, que se deva rejeitar esta, pois ele mesmo se dignou vesti-la por nós, ele que levou os nossos pecados no seu corpo sobre o madeiro (1Pd 2,24). Há ainda a negrura da perseguição, que se tem até pelo maior adorno, se é sofrida pela justiça e pela verdade. Daí aquilo: Os discípulos saíam alegres da presença do Sinédrio, porque foram julgados dignos de sofrer afronta pelo nome de Jesus (At 5,41); e ainda: Felizes os perseguidos por causa da justiça (Mt 5,10). Creio que é desta sobretudo que a Igreja se gloria, e é esta que ela imita de mais bom grado nas peles do esposo. Pois tem esta promessa: Se me perseguiram, também vos perseguirão (Jo 15,20).`
    },
    {
      n: 13,
      texto: `Por isso a esposa acrescenta: Não repareis em eu ser morena, porque o sol me queimou (Ct 1,5) — isto é: não me tenhais por disforme por me verdes, sob a perseguição que me cerca, menos florescente, com menos cor segundo a glória do mundo. Por que me lançais em rosto uma negrura que me trouxe o ardor da perseguição, e não a vergonha da minha vida? Ou chama sol ao zelo da justiça, com que se acende e se arma contra os malfeitores, dizendo a Deus: O zelo da tua casa me devorou (Sl 68,10)? E aquilo: O meu zelo me consumiu, porque os meus inimigos se esqueceram das tuas palavras; e também: Tomou-me o desfalecimento por causa dos pecadores que abandonam a tua lei (Sl 118,139.53); e ainda: Não odiava eu, Senhor, os que te odeiam, e não me consumia por causa dos teus inimigos? (Sl 138,21) Guarda também com cuidado aquilo do Sábio: Tens filhas? Não lhes mostres um rosto alegre (Eclo 7,26) — de modo que aos frouxos, aos moles e aos que fogem da disciplina mostre não a brancura da serenidade, mas a sombra da severidade. Ou então ser queimada pelo sol é arder de caridade fraterna, chorar com os que choram, desfalecer com os que desfalecem, queimar-se com os escândalos de cada um. Ou assim: queimou-me Cristo, o Sol da justiça, de cujo amor desfaleço (Ct 2,5). Este desfalecimento é como um apagar-se da cor e um desmaio da alma no desejo; por isso diz: Lembrei-me de Deus e deleitei-me; meditei, e o meu espírito desfaleceu (Sl 76,4). Assim, como um sol que queima, o ardor do desejo tira a cor a quem peregrina no corpo, pois torna impaciente da recusa quem anseia pelo rosto da glória, e a demora atormenta quem ama. Qual de nós arde de tal modo em amor santo que, pelo desejo de ver a Cristo, enjoe e ponha de lado toda a cor da glória e da alegria presentes, testemunhando-lhe com aquela voz profética: E não desejei o dia do homem, tu o sabes (Jr 17,16); e também com o santo Davi: A minha alma recusou ser consolada (Sl 76,3) — isto é, despreza colorir-se com a alegria vã dos bens presentes? Ou ainda: o sol tirou-me a cor pela comparação com o seu esplendor; pois, ao aproximar-me dele, descubro-me escura por causa dele, acho-me negra, vejo-me feia. De resto sou formosa; por que me chamais morena, se só fico atrás da beleza do sol? Mas o que segue parece concordar mais com o primeiro sentido. Pois, ao acrescentar: Os filhos da minha mãe combateram contra mim, dá a entender claramente que sofreu perseguição. Mas daqui começaremos outro sermão, porque desta vez pode bastar o que recebemos, por dom dele, a respeito da glória do esposo da Igreja, Nosso Senhor Jesus Cristo, que é Deus bendito pelos séculos. Amém.`
    }
  ]
});
