SERMOES.sermao({
  id: 'bernardo-cantico-82',
  colecao: 'bernardo-cantico',
  ordem: 82,
  numero: 'LXXXII',
  titulo: 'Como a alma, permanecendo semelhante a Deus, se tornou, contudo, dessemelhante pelo pecado na simplicidade, na imortalidade e na liberdade',
  fonte: 'Qualiter anima similis Deo manens, per peccatum tamen dissimilis facta est',
  argumento: `Antes de voltar ao Cântico, Bernardo resolve uma dúvida que ficou do sermão anterior — e conta que certa vez, retendo para si o que o Espírito lhe sugeria, ouviu: "Enquanto guardares isso, não receberás outra coisa". Se a semelhança com o Verbo é inseparável da alma, como diz a Escritura que o homem se tornou semelhante aos animais? A resposta: a semelhança não foi apagada, mas coberta por outra; a alma não se despojou da forma nativa, mas revestiu-se por cima de uma forma estranha, como o ouro que escureceu, mas continua ouro. À simplicidade coseu-se a duplicidade, desde a serpente e as desculpas de Adão; à imortalidade, a sombra da morte, pelo desejo das coisas mortais; à liberdade, o temor servil e a necessidade voluntária: um "manto duplo" de semelhança e dessemelhança.

Por isso o homem se parece com os animais na concepção, no nascimento, na vida e na morte; e o iníquo, posto diante da sua própria face, exclama: "Senhor, quem é semelhante a ti?". Mas é a semelhança que permanece que torna odiosa a dessemelhança; e o mal que a alma vê em si a lança para o bem que também vê, esperando-o da graça e não da natureza. O semelhante procura o semelhante: quando vier o que é perfeito, a alma conhecerá como é conhecida e amará como é amada.

Tradução feita do texto latino de Migne (PL 183, 1177-1181).`,
  pontos: [
    {
      n: 1,
      texto: `Que vos parece? Podemos já voltar à ordem da exposição de onde nos desviamos, visto que está patente o parentesco do Verbo e da alma, para cuja demonstração se fez a própria digressão? Poderíamos, parece-me, se não sentisse que ainda resta um pouco de dúvida no que se disse. Não quero furtar nada. Não passo por alto de bom grado o que julgo útil para vós. E como ousaria fazê-lo, sobretudo com aquilo que recebo para vós? Conheço um homem (cf. 2Cor 12,2) que certa vez, falando, retinha e reservava para si alguma coisa do que o Espírito lhe sugeria — não com ânimo infiel, mas com pouca confiança —, para ter o que dizer quando voltasse a tratar do assunto; e eis que lhe veio uma voz, ao que lhe pareceu: "Enquanto guardares isso, não receberás outra coisa". Que seria, se o tivesse retido não para prover à sua pobreza, mas por inveja do progresso dos irmãos? Não lhe seria tirado, com razão, até o que parecia ter (cf. Lc 8,18)? Deus afaste sempre isso do vosso servo, como sempre o afastou. Assim se digne transbordar sempre para mim aquela fonte inesgotável da sabedoria salutar, como eu vos comuniquei sem inveja (cf. Sb 7,13) e vos devolvi tudo o que até agora ela se dignou infundir em mim. Se eu vos defraudo, por quem não temerei ser eu mesmo defraudado? Nem sequer por Deus.`
    },
    {
      n: 2,
      texto: `Há, pois, no que se disse, alguma coisa que, receio, pode servir de tropeço, se não for aplanada. E, se não me engano, há alguns dos que aqui estão a quem causou escrúpulo o que quero dizer. Lembrais-vos de que aquela tríplice semelhança com o Verbo, que atribuímos à alma — ou antes, com que notamos que ela está marcada —, nos pareceu estar nela até de modo inseparável? Isto pareceria contrariar alguns testemunhos das Escrituras, como, por exemplo, aquele dos salmos: O homem, quando estava em honra, não entendeu; foi comparado aos animais insensatos e tornou-se semelhante a eles (Sl 48,13.21); e também aquele: Trocaram a sua glória pela semelhança de um novilho que come erva (Sl 105,20); e ainda o que se disse claramente na pessoa de Deus: Pensaste iniquamente que eu seria semelhante a ti (Sl 49,21); e muitos outros que parecem afirmar de comum acordo que a semelhança de Deus no homem foi apagada depois do pecado. Que diremos, pois, a isto? Que aquelas três coisas não estão em Deus, e que por isso se devem procurar outras em que ponhamos a semelhança? Ou que estão em Deus, mas não na alma, e que nem assim se encontra nelas a semelhança? Ou que estão também na alma, mas podem também não estar, e por isso não são inseparáveis? Longe disso! Estão em Deus e na alma, e estão sempre; e não há por que nos arrependermos de ter dito nada disto, tão apoiado está tudo numa verdade indubitável e absolutíssima. Mas, quando a Escritura fala da dessemelhança que se produziu, não o diz porque esta semelhança tenha sido apagada, mas porque se lhe sobrepôs outra. A alma não se despojou da forma nativa, mas revestiu-se por cima de uma forma estranha. Aquela foi acrescentada, não esta perdida; e a que sobreveio pôde obscurecer a inata, mas não exterminá-la. Enfim: Obscureceu-se o seu coração insensato, diz o Apóstolo (Rm 1,21); e o profeta: Como se obscureceu o ouro, mudou-se a cor tão bela (Lm 4,1)! Chora o ouro obscurecido, mas ouro, apesar de tudo; a cor tão bela mudada, mas não arrancado o fundo da cor. Permanece no fundo, inteiramente inabalável, a simplicidade; mas não aparece, coberta pela duplicidade da astúcia humana, da simulação, da hipocrisia.`
    },
    {
      n: 3,
      texto: `Quão desajustadamente se mistura a duplicidade com a simplicidade! Quão indignamente se assenta tal construção sobre tal fundamento! Deste tipo de astúcia se tinha revestido a serpente, quando, para enganar, se apresentava como conselheira e fingia ser amiga. Dela se revestiram também os habitantes do paraíso, seduzidos por ela, quando procuravam cobrir a nudez já vergonhosa com a sombra da árvore frondosa, com cintos de folhas e com palavras de desculpa (cf. Gn 3,7-12). Quão largamente, desde então e daí em diante, o veneno hereditário da hipocrisia infeccionou toda a descendência! Quem me darás, dentre os filhos de Adão, que, não digo queira, mas ao menos suporte ser visto como é? Mas, apesar disso, persevera em toda alma, junto com a duplicidade de origem, a simplicidade comum, de modo que a comparação aumente a confusão; persevera igualmente a imortalidade, mas escura e sombria, invadida pela escuridão tenebrosa da morte corporal. Pois, embora não seja privada da vida, já não consegue assegurar ao seu corpo o benefício da vida. E que dizer de que nem sequer conserva para si a sua vida espiritual? Pois a alma que pecar, essa morrerá (Ez 18,4). Com a investida desta dupla morte, não fica bem tenebrosa e mesquinha aquela imortalidade, tal como for, que ela conserva? Acrescenta que o desejo das coisas terrenas, que são todas para a perdição, adensa as trevas, de tal modo que na alma que vive assim não se vê aparecer em parte nenhuma senão um rosto pálido e uma espécie de imagem da morte. Por que, sendo imortal, não deseja as coisas semelhantes a ela, imortais e eternas, para que apareça o que é e viva conforme aquilo para que foi feita? Mas gosta das coisas contrárias e as procura; e, conformando-se à mortalidade por uma vida degenerada, enegrece a brancura da imortalidade com a cor de pez de um costume mortífero. Como não havia o desejo das coisas mortais de tornar a imortal semelhante ao mortal e dessemelhante ao imortal? Quem toca o pez, diz o Sábio, ficará manchado por ele (Eclo 13,1). Gozando das coisas mortais, revestiu-se de mortalidade, e descoloriu, sem a despir, a veste da imortalidade, sobrevindo a semelhança da morte.`
    },
    {
      n: 4,
      texto: `Repara em Eva: como a sua alma imortal cobriu a glória da sua imortalidade com o disfarce da mortalidade, desejando as coisas mortais. Pois por que, sendo imortal, não desprezou as coisas mortais e passageiras, contentando-se com as que lhe eram semelhantes, as imortais e eternas? Viu, diz, que a árvore era bela aos olhos, deleitável à vista e boa para comer (Gn 3,6). Não é tua, ó mulher, essa doçura, esse deleite, essa beleza; e, se é tua pela parte do barro, não é só tua, mas comum a todos os animais da terra. A tua, a que é verdadeiramente tua, vem de outra parte e é outra: pois é eterna, da eternidade. Por que imprimes na tua alma outra forma — ou antes, uma deformidade estranha? Pois o que agrada ter, também se teme perder; e o temor é uma cor. Tingindo a liberdade, encobre-a, e torna-a igualmente dessemelhante de si mesma. Quão mais digno da sua origem seria que não desejasse nada, para nada temer, e defendesse assim deste temor servil a liberdade que lhe é inata, que permaneceria no seu vigor e na sua beleza! Ai! Não é assim! Mudou-se a cor tão bela. Foges e escondes-te: ouves a voz do Senhor Deus, e ocultas-te (cf. Gn 3,8). Por que isto, senão porque temes aquele a quem amavas, e a forma servil expulsou a beleza da liberdade?`
    },
    {
      n: 5,
      texto: `Mas também aquela necessidade voluntária e a lei contrária imposta aos membros, de que falei no sermão anterior, pesam sobre essa mesma liberdade, e, seduzindo-a, sujeitam à servidão, pela sua própria vontade, a criatura livre por natureza, cobrindo-lhe o rosto de ignomínia (cf. Sl 82,17), de modo que, ao menos com a carne, serve à lei do pecado, mesmo sem querer. Como, pois, descuidou de defender com a retidão dos costumes a nobreza da natureza, pelo justo juízo do Criador aconteceu, não que fosse despojada da sua liberdade própria, mas que fosse coberta por cima, como de um manto duplo, com a sua confusão (Sl 108,29). E bem se diz "como de um manto duplo", onde, sendo a veste como que dobrada, permanece a liberdade por causa da vontade, e a vida servil prova, contudo, a necessidade. O mesmo se pode notar quanto à simplicidade e à imortalidade da alma; e, se consideras bem, nada te aparecerá nela que não esteja coberto deste manto duplo de semelhança e dessemelhança. Não é um manto duplo, quando à simplicidade se coseu — não nascida com ela, mas pregada e como que cosida com a agulha do pecado — a fraude; à imortalidade, a morte; à liberdade, a necessidade? Pois a duplicidade do coração não anula a simplicidade da essência; nem a morte — seja a voluntária, do pecado, seja a necessária, do corpo — anula a imortalidade da natureza; nem a necessidade de uma servidão voluntária anula a liberdade do arbítrio. Assim, os males vindos de fora, como não substituem os bens da natureza, mas se lhes acrescentam, desfiguram-nos, mas não os exterminam; perturbam-nos, mas não os derrubam. Daí vem que a alma é dessemelhante de Deus, e dessemelhante também de si mesma; daí que foi comparada aos animais insensatos e se tornou semelhante a eles; daí o que se lê: que trocou a sua glória pela semelhança de um novilho que come erva; daí que os homens, como as raposas, têm tocas de duplicidade e de fraude (cf. Mt 8,20), e, porque se fizeram iguais às raposas, serão a porção das raposas (Sl 62,11); daí que, segundo Salomão, é uma só a saída do homem e do animal (Ecl 3,19). E como não havia de sair do mesmo modo quem viveu do mesmo modo? Deitou-se sobre as coisas terrenas como os animais; como os animais morrerá, saindo da terra. Ouve outra coisa. Que admira que tenhamos uma saída semelhante, nós que temos também uma entrada semelhante? Pois de onde vem aos homens, senão da semelhança com os animais, aquele ardor tão intemperante no ato conjugal, aquela dor tão desmedida no parto? Assim o homem, na concepção e no nascimento, na vida e na morte, foi comparado aos animais insensatos e tornou-se semelhante a eles.`
    },
    {
      n: 6,
      texto: `E que dizer de que a criatura livre não governa como senhora o apetite que lhe está sujeito, mas o segue e lhe obedece como escrava? Não se assemelha também nisto e não se conta entre os outros animais, que a natureza não chamou à liberdade, mas criou para a servidão, para servir ao seu ventre e obedecer ao apetite? Não se envergonha Deus, com razão, de ser dito ou julgado semelhante a um tal ser? Por isso diz: Pensaste iniquamente que eu seria semelhante a ti; e acrescenta: Hei de repreender-te e pôr-te diante da tua própria face (Sl 49,21). Não é próprio da alma que se vê a si mesma julgar Deus semelhante a si — da alma, digo, pecadora e iníqua, como a minha. Pois é uma alma assim que é repreendida: Pensaste iniquamente, diz; e não diz: Pensaste, ó alma, ou: Pensaste, ó homem, que eu seria semelhante a ti. Mas, se o iníquo for posto diante da sua própria face, e colocado diante do rosto doente e fétido do seu homem interior, de modo que não possa dissimular nem evitar a impureza da sua consciência, mas veja, mesmo contra a vontade, a imundície dos seus pecados, e contemple a deformidade dos seus vícios, de modo nenhum poderá já julgar que Deus seria semelhante a si; mas, como que desesperando por tão grande dessemelhança que verá, há de exclamar, penso eu, e dizer: Senhor, quem é semelhante a ti (Sl 34,10)? O que se diz por causa daquela dessemelhança voluntária e nova. Pois a primeira semelhança permanece; e por isso aquela desagrada mais, porque esta permanece. Ó que grande bem é esta, e que grande mal aquela! Mas, comparadas uma com a outra, cada uma sobressai mais no seu gênero.`
    },
    {
      n: 7,
      texto: `Quando, pois, a alma vê em si mesma tão grande distância entre as coisas, como não havia de clamar, posta entre a esperança e o desespero: Senhor, quem é semelhante a ti? É arrastada ao desespero por tão grande mal; mas é chamada de volta à esperança por tão grande bem. Daí vem que, quanto mais se desagrada a si mesma pelo mal que vê em si, tanto mais ardentemente se lança para o bem que igualmente vê em si, e deseja tornar-se aquilo para que foi feita: simples e reta, temente a Deus e afastada do mal (Jó 1,1). Por que não poderia afastar-se daquilo de que pôde aproximar-se? Por que não poderia aproximar-se daquilo de que pôde afastar-se? Mas digo que uma e outra coisa se devem esperar da graça, não da natureza, nem sequer do próprio esforço. Pois é a sabedoria que vence a malícia (Sb 7,30), não o esforço ou a natureza. E não falta motivo de confiança: é para o Verbo que ela se converte. Não é inútil junto do Verbo o nobre parentesco da alma, de que já tratamos há três dias, nem a semelhança que persevera como testemunha do parentesco. Admite com condescendência à comunhão do Espírito aquela que lhe é semelhante na natureza. E, certamente, pela razão da natureza, o semelhante procura o semelhante. É a voz de quem procura: Volta, sulamita; volta, para que te contemplemos (Ct 6,12). Contemplará a semelhante aquele que não olhava para a dessemelhante; e também se dará a contemplar. Sabemos que, quando ele aparecer, seremos semelhantes a ele, porque o veremos como ele é (1Jo 3,2). Pensa, pois, que aquela pergunta — Senhor, quem é semelhante a ti? — nasce mais da dificuldade do que da impossibilidade.`
    },
    {
      n: 8,
      texto: `Ou, se preferes isto, é voz de quem se admira. Admirável e assombrosa é, de fato, aquela semelhança que a visão de Deus acompanha — ou antes, que é a visão de Deus; digo, porém, na caridade. A caridade é aquela visão, é aquela semelhança. Quem não se assombrará com a caridade de Deus, desprezado e, contudo, chamando de volta? Com razão é repreendido como iníquo aquele que se apresentou acima, usurpando para si a semelhança de Deus, quando, amando a iniquidade, não pode amar nem a si nem a Deus; pois tens isto: Quem ama a iniquidade odeia a sua alma (Sl 10,6). Tirada, pois, do meio a iniquidade, que produz esta dessemelhança parcial, haverá união de espírito, haverá visão mútua e amor mútuo. Pois, quando vier o que é perfeito, será abolido o que é parcial (1Cor 13,10); e haverá de um para o outro um amor casto e consumado, um conhecimento pleno, uma visão manifesta, uma união firme, uma comunhão indivisível, uma semelhança perfeita. Então a alma conhecerá como é conhecida (1Cor 13,12); então amará como é amada; e o esposo se alegrará com a esposa (cf. Is 62,5), conhecendo e conhecido, amando e amado, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
