SERMOES.sermao({
  id: 'bernardo-cantico-62',
  colecao: 'bernardo-cantico',
  ordem: 62,
  numero: 'LXII',
  titulo: 'Que significa a alma fiel morar nas fendas da rocha e nas cavidades do muro; que se deve perscrutar antes a vontade de Deus do que a sua majestade; e da pureza de mente necessária para pregar a verdade',
  fonte: 'Quid sit animam fidelem commorari in foraminibus petrae',
  argumento: `A pomba tem dois refúgios: as fendas da rocha, que são as chagas de Cristo, e as cavidades do muro. O muro é a comunhão dos santos e a guarda dos anjos, e as suas cavidades são os lugares deixados vazios pelos anjos caídos, que os homens hão de preencher. Assim a Igreja se consola com duas coisas: a memória da paixão, no passado, e a esperança das moradas celestes, no futuro. Ou então as cavidades não se encontram, fazem-se: pelo desejo e pela oração, cada um pode ir cavando no muro celeste e visitar os patriarcas, os profetas, os apóstolos, os mártires, os anjos.

Há, pois, duas contemplações: a da cidade do alto, que é cavar no muro, e a da majestade do rei, que é cavar na rocha, mais difícil e mais doce. João e Paulo cavaram na rocha; Davi repartia com o povo o que podia e guardava o resto para festejar com Deus. Não há perigo em perscrutar a majestade quando se busca a glória de Deus, e não a própria; mas é mais seguro perscrutar a sua vontade, que é misericórdia, e conformar-se a ela. Quem ainda não pode nem uma coisa nem outra esconda-se nas chagas do Crucificado até sarar. E só então agradam o rosto e a voz: a pureza deve preceder a pregação, porque ninguém fala bem do que não viu.

Tradução feita do texto latino de Migne (PL 183, 1074-1080).`,
  pontos: [
    {
      n: 1,
      texto: `Minha pomba, nas fendas da rocha, nas cavidades do muro (Ct 2,14). A pomba não encontra refúgio seguro só nas fendas da rocha; encontra-o também nas cavidades do muro. E, se entendemos por muro não um amontoado de pedras, mas a comunhão dos santos, vejamos se não chamou cavidades do muro aos lugares como que deixados vazios pelos anjos que caíram pela soberba; lugares que hão de ser preenchidos com homens, como ruínas que se hão de reparar com pedras vivas. Por isso diz o apóstolo Pedro: Aproximando-vos da pedra viva, também vós, como pedras vivas, sede edificados como casas espirituais (1Pd 2,4-5). E não julgo fora de propósito entender que a guarda dos anjos faz as vezes de muro na vinha do Senhor, que é a Igreja dos predestinados, pois Paulo diz: Não são todos eles espíritos servidores, enviados para servir aos que hão de herdar a salvação (Hb 1,14)? E o Profeta: O anjo do Senhor acampa ao redor dos que o temem (Sl 33,8). E, se isto assenta bem, o sentido será que duas coisas consolam a Igreja no tempo e no lugar da sua peregrinação: quanto ao passado, a memória da paixão de Cristo; quanto ao futuro, o pensamento e a confiança de que será recebida na herança dos santos. Contempla ambas estas coisas com desejo insaciável, como quem tem olhos à frente e atrás; e ambos os olhares lhe são muito agradáveis, ambos são para ela refúgio contra a tribulação dos males e contra a dor. É consolação completa, pois sabe não só o que deve esperar, mas também em que se funda a sua confiança. Espera alegre e sem dúvida, porque firmada na morte de Cristo. Por que temeria diante da grandeza do prêmio aquela que considera o valor do preço? Com que gosto visita com a mente as fendas por onde correu para ela o preço do sangue sacrossanto! Com que gosto percorre as cavidades, os aposentos e as moradas, que na casa do Pai são muitas (cf. Jo 14,2) e diversas, nas quais há de acomodar os seus filhos segundo a diversidade dos méritos de cada um! E agora, que é só o que por ora pode, repousa nelas só com a memória, revestindo-se já em ânimo da morada celeste que vem do alto (cf. 2Cor 5,2). Mas virá o tempo em que preencherá as ruínas, em que habitará as cavidades com o corpo e com a mente; em que iluminará com a presença de todos os seus as moradas vazias que os antigos habitantes deixaram, e já não aparecerá nenhuma cavidade no muro celeste, que daí em diante se alegrará com a sua feliz perfeição e integridade.`
    },
    {
      n: 2,
      texto: `Ou, se preferes isto, diremos que estas cavidades não se encontram, mas se fazem pelas mentes estudiosas e piedosas. De que modo?, perguntas. Pelo pensamento e pelo desejo. Pois este piedoso muro, à maneira de um muro mais mole, cede ao desejo da alma, cede à contemplação pura, cede à oração frequente. Enfim, a oração do justo penetra os céus (cf. Eclo 35,21). Não, certamente, porque rasgará as espaçosas alturas deste ar corpóreo, como ave que voa com o remo das suas asas, ou furará, como espada aguda, a abóbada sólida e alta do próprio firmamento; mas há céus santos, vivos, racionais, que narram a glória de Deus (Sl 18,2), que com uma piedade favorável se inclinam de boa vontade aos nossos desejos e, curvando os seus afetos ao toque da nossa devoção, nos recebem nas suas entranhas todas as vezes que batemos à sua porta com uma intenção digna. Pois a quem bate se abrirá (cf. Mt 7,8). Será, pois, lícito a cada um de nós, mesmo neste tempo da nossa mortalidade, cavar para si, na parte que quiser, cavidades no muro do alto: ora visitar os patriarcas, ora saudar os profetas, ora misturar-se ao senado dos apóstolos, ora juntar-se aos coros dos mártires; e também percorrer, com toda a prontidão da mente, as condições e as moradas das potestades bem-aventuradas, desde o menor anjo até os querubins e serafins, conforme a devoção de cada um o levar. E junto daqueles a quem se sentir mais afeiçoado, segundo o que o Espírito lhe inspirar, como quer, se parar e bater, logo se lhe abrirá; e, feita como que uma cavidade nesses montes — ou antes, nessas mentes santas —, que por si mesmas se inclinam à piedade, repousará ao menos um pouco junto deles. De toda alma que assim faz, tanto o rosto como a voz são agradáveis a Deus: o rosto, pela pureza; a voz, pela confissão. Pois a confissão e a beleza estão diante dele (Sl 95,6). Por isso se diz a quem é assim: Mostra-me o teu rosto, ressoe a tua voz aos meus ouvidos. A voz é a admiração no ânimo de quem contempla; a voz é a ação de graças. Deus se deleita muito com estas cavidades, das quais lhe ressoa a voz de ação de graças, a voz de admiração e de louvor.`
    },
    {
      n: 3,
      texto: `Feliz a mente que se aplicar a cavar frequentemente neste muro; mas mais feliz a que cavar na rocha. É lícito cavar também na rocha; mas para isso é preciso um olhar da mente mais puro, uma aplicação de todo mais intensa, e também méritos maiores de santidade. E quem é capaz destas coisas? Sem dúvida aquele que disse: No princípio era o Verbo, e o Verbo estava junto de Deus, e o Verbo era Deus; ele estava no princípio junto de Deus (Jo 1,1-2). Não te parece que mergulhou no próprio íntimo do Verbo e tirou dos esconderijos do seu peito como que a medula sacrossanta da sabedoria mais íntima? E aquele que falava de sabedoria entre os perfeitos, a sabedoria escondida no mistério, que nenhum dos príncipes deste mundo conheceu (1Cor 2,6-8)? Não a trouxe ele, piedoso investigador, do terceiro céu, depois de ter furado o primeiro e o segundo com uma curiosidade aguda, mas piedosa? E não a calou para nós, mas comunicou-a fielmente aos fiéis com as palavras que pôde. Mas ouviu palavras inefáveis, que não lhe era lícito dizer (2Cor 12,2.4). Não, certamente, a um homem; pois dizia-as a si e a Deus. Imagina, pois, que Deus consola deste modo a caridade como que aflita de Paulo, e lhe diz: Por que te afliges de que o ouvido humano não possa receber o que concebeste? Ressoe a tua voz aos meus ouvidos; isto é: se não é lícito revelar aos mortais o que sentes, consola-te, porém, de que a tua voz pode acariciar os ouvidos divinos. Vês a alma santa, ora sóbria para nós pela caridade, ora arrebatada para Deus pela pureza (cf. 2Cor 5,13)? Vê também, a respeito do santo Davi, se não é ele mesmo o homem de quem fala com Deus como de outro: Porque o pensamento do homem te louvará, e as sobras do pensamento te celebrarão festa (Sl 75,11). Aquilo, pois, do pensamento profético que podia vir a público pela palavra e pelo exemplo do Profeta, o Profeta o soltava logo em louvor público, e com isso louvava o Senhor entre os povos; o resto guardava-o para si e para Deus, celebrando com ele uma festa em alegria e exultação. É isto, pois, o que nos quis dar a entender no versículo mencionado: de tudo o que conseguia tirar do segredo da sabedoria com aquele seu pensamento investigador e ávido, repartia com pregação solícita, para a salvação dos povos, a parte que podia; o resto, que os povos não podiam receber, empregava-o com júbilo festivo nos louvores de Deus. Vês que nada se perde da santa contemplação, pois o que não se pode empregar na edificação dos povos se torna para Deus um louvor alegre e belo.`
    },
    {
      n: 4,
      texto: `Sendo assim, é claro que há dois gêneros de contemplação: um, a respeito do estado, da felicidade e da glória da cidade do alto, e da ação ou do repouso em que se ocupa aquela imensa multidão dos cidadãos do céu; o outro, a respeito da majestade, da eternidade, da divindade do próprio rei. Aquela está no muro; esta, na rocha. Mas, quanto mais difícil é cavar nesta, tanto mais doce sabe o que dela tiras. E não temas aquilo com que a Escritura ameaça os que perscrutam a majestade (Pr 25,27). Traze só um olho puro e simples: não serás esmagado pela glória, mas admitido — a não ser que busques, não a glória de Deus, mas a tua. Pois cada um é esmagado pela sua própria glória, e não pela de Deus, quando, inclinado para aquela, não consegue levantar a cabeça para esta, pesada como está de cobiça. Sacudida esta, perscrutemos com segurança na Rocha, na qual estão escondidos os tesouros da sabedoria e da ciência (Cl 2,3). Se ainda duvidas, ouve a própria Rocha: Os que trabalham em mim, diz, não pecarão (Eclo 24,30). Quem me dará asas como de pomba, e voarei e repousarei (Sl 54,7)? Ali encontra repouso o manso e o simples, onde é esmagado o enganador, o altivo e o ávido de vanglória. A Igreja é pomba, e por isso repousa. Pomba, porque é inocente, porque geme. Pomba, digo, porque recebe com mansidão a palavra nela plantada (cf. Tg 1,21). E repousa no Verbo, isto é, na rocha; pois a rocha é o Verbo. A Igreja está, pois, nas fendas da rocha, pelas quais olha para dentro e vê a glória do seu esposo; e, contudo, não é esmagada pela glória, porque não a usurpa para si. Não é esmagada, porque não perscruta a majestade, mas a vontade. Pois, quanto à majestade, às vezes ousa também olhar para ela, mas como quem admira, não como quem perscruta. E, se alguma vez lhe acontece ser arrebatada até ela em êxtase, é o dedo de Deus que levanta o homem por bondade, e não a temeridade do homem que invade com insolência as alturas de Deus. Pois, se o Apóstolo lembra que foi arrebatado (2Cor 12,2-4), para desculpar o seu atrevimento, que outro mortal ousaria meter-se com os próprios esforços neste temível exame da majestade divina e, contemplador inoportuno, irromper nos segredos que fazem tremer? Julgo, pois, que se chamam perscrutadores da majestade, como invasores, não os que são arrebatados até ela, mas os que nela irrompem. Esses, pois, são esmagados pela glória.`
    },
    {
      n: 5,
      texto: `É, pois, temível perscrutar a majestade; mas perscrutar a vontade é tão seguro quanto piedoso. Por que não me aplicaria com toda a diligência a perscrutar o mistério da gloriosa vontade à qual sei que devo obedecer em tudo? Suave glória, que não procede de outra coisa senão da contemplação da sua própria suavidade, do olhar posto nas riquezas da sua bondade e da sua grande misericórdia. Enfim, vimos esta glória, glória como do Unigênito que vem do Pai (Jo 1,14). Tudo o que apareceu de glória nesta parte é benigno e verdadeiramente paterno. Esta glória não me oprimirá, ainda que eu olhe para ela com todas as forças: antes, ficarei impresso nela. Pois, contemplando de rosto descoberto, somos transformados na mesma imagem, de claridade em claridade, como pelo Espírito do Senhor (2Cor 3,18). Somos transformados quando somos conformados. Longe de nós que o homem presuma conformar-se a Deus na glória da majestade, e não antes na modéstia da vontade! A minha glória é esta: se algum dia ouvir de mim: Encontrei um homem segundo o meu coração (cf. At 13,22). O coração do esposo é o coração do seu Pai. E como é ele? Sede misericordiosos, diz, como também o vosso Pai é misericordioso (Lc 6,36). Esta é a forma que deseja ver quando diz à Igreja: Mostra-me o teu rosto: a forma da piedade e da mansidão. Ela a levanta com toda confiança para a Rocha, com a qual se parece: Aproximai-vos dele, diz, e sereis iluminados, e os vossos rostos não serão confundidos (Sl 33,6). Como seria confundida a humilde pelo humilde, a santa pelo piedoso, a modesta pelo manso? O rosto puro da esposa não recuará diante da pureza da rocha, como a virtude não recua diante da virtude, nem a luz diante da luz.`
    },
    {
      n: 6,
      texto: `Mas, como a Igreja ainda não pode, por ora, chegar-se inteira a furar a rocha — pois não é de todos os que estão na Igreja examinar os mistérios da vontade divina, ou alcançar por si mesmos as profundezas de Deus —, por isso se mostra que habita não só nas fendas da rocha, mas também nas cavidades do muro. Nos perfeitos, pois, que pela pureza da consciência ousam, e pela agudeza da inteligência podem, esquadrinhar e penetrar os segredos da sabedoria, ela habita nas fendas da rocha. Nos restantes, nas cavidades do muro: para que os que não são capazes de cavar por si mesmos na rocha, ou não se atrevem, cavem no muro, contentes de contemplar com a mente ao menos a glória dos santos. E, se alguém nem isto puder, a este ela proporá Jesus, e Jesus crucificado (cf. 1Cor 2,2), para que também ele habite, sem trabalho seu, nas fendas da rocha, em que não trabalhou. Os judeus trabalharam nelas, e ele entrará no trabalho dos infiéis para ser fiel. E não há de temer ser repelido quem é até chamado para entrar. Entra na rocha, diz, esconde-te na terra cavada, diante do terror do Senhor e da glória da sua majestade (Is 2,10). À alma ainda fraca e sem forças — que, como alguém confessa de si mesmo no Evangelho, não pode cavar e tem vergonha de mendigar (Lc 16,3) — mostra-se a terra cavada onde se esconda, até que recobre forças e progrida, para poder também ela cavar por si mesma fendas na rocha, pelas quais entre no interior do Verbo, com o vigor e a pureza do ânimo.`
    },
    {
      n: 7,
      texto: `E, se entendemos por terra cavada aquela que diz: Traspassaram as minhas mãos e os meus pés (Sl 21,17), não se deverá duvidar de que a alma ferida que nela se demorar alcançará nela depressa a saúde. Pois que há de tão eficaz para curar as feridas da consciência e purificar o olhar da mente como a meditação assídua das chagas de Cristo? Mas, enquanto não estiver perfeitamente purificada e curada, não vejo como se lhe possa aplicar o que se diz: Mostra-me o teu rosto, ressoe a tua voz aos meus ouvidos. Pois como ousaria mostrar o rosto ou levantar a voz aquela a quem até se manda esconder-se? Esconde-te, diz, na terra cavada. Por quê? Porque não tem um rosto belo, nem é digna de ser vista. Não será digna de ser vista enquanto não for capaz de ver. Mas, quando, morando na terra cavada, tiver progredido tanto na cura do olho interior que também ela possa contemplar de rosto descoberto a glória de Deus, então, por fim, falará já com confiança do que vir, agradando pela voz e pelo rosto. É forçoso que agrade o rosto que pode fitar a claridade de Deus. Pois não o poderia, se não fosse também ele claro e puro, transformado na mesma imagem de claridade que contempla. De outro modo, recuaria pela própria dessemelhança, repelido pelo fulgor desacostumado. Quando, pois, pura, puder contemplar a verdade pura, então o esposo desejará ver o seu rosto, e em consequência ouvir a sua voz.`
    },
    {
      n: 8,
      texto: `Pois quanto lhe agrada a pregação da verdade unida à pureza da mente, mostra-o quando logo acrescenta: Pois a tua voz é doce (Ct 2,14). E que a voz não agrada se desagrada o rosto, mostra-o quando logo acrescenta: E o teu rosto é formoso. Que é a formosura do rosto interior, senão a pureza? Esta agradou em muitos sem a voz da pregação; aquela, sem esta, em ninguém. Aos impuros a Verdade não se mostra, a Sabedoria não se confia. Como falam, pois, daquela que não viram? Falamos do que sabemos, diz, e damos testemunho do que vimos (Jo 3,11). Vai, pois, tu, e atreve-te a dar testemunho do que não viste e a falar do que ignoras! Perguntas a quem chamo impuro? Àquele que busca os louvores humanos; que não prega o Evangelho gratuitamente (cf. 1Cor 9,18); que evangeliza para comer; que toma a piedade por fonte de lucro; que não busca o fruto, mas a dádiva (cf. Fl 4,17). Tais homens são impuros; e, embora por causa da impureza não tenham com que ver a verdade, têm contudo com que falar dela. Por que agis com tanta precipitação? Por que não esperais a luz? Por que vos atreveis à obra da luz antes da luz? É vão para vós levantar-vos antes da luz (Sl 126,2). A luz é a pureza, a luz é a caridade, que não busca os seus próprios interesses (1Cor 13,5). Que ela vá à frente, e o pé da língua não se porá em terreno incerto. Ao olho soberbo a verdade não se deixa ver; ao sincero fica patente. Não há por que a verdade se negue a ser contemplada pelo coração puro, e por isso também a ser anunciada por ele. Mas ao pecador diz Deus: Por que recitas as minhas leis e tomas a minha aliança na tua boca (Sl 49,16)? Muitos, descuidando a pureza, tentaram falar antes de ver; e ou erraram gravemente, sem saber de que falavam nem o que afirmavam (cf. 1Tm 1,7), ou se tornaram vergonhosamente desprezíveis, porque, ensinando os outros, não se tinham ensinado a si mesmos (cf. Rm 2,21). Que deste duplo mal nos guarde sempre, pelas vossas orações, o Esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
