SERMOES.sermao({
  id: 'bernardo-cantico-68',
  colecao: 'bernardo-cantico',
  ordem: 68,
  numero: 'LXVIII',
  titulo: 'Como Cristo, o esposo, está atento à Igreja, sua esposa, e ela a ele; do cuidado que Deus tem dos eleitos; e do mérito e da confiança da Igreja',
  fonte: 'Quomodo sponsus Christus intendit sponsae Ecclesiae',
  argumento: `Bernardo explica a palavra que adiara: dizer "o meu amado está atento a mim" é afirmar que o próprio Deus, que governa o universo, se ocupa da sua esposa — e a esposa somos nós. Deus tem providência de todas as criaturas, mas cuidado, como diz Pedro — "ele tem cuidado de vós" —, só da Igreja dos eleitos, a ovelha perdida que o pastor trouxe de volta nos ombros. E a esposa corresponde: ele para mim, por bondade; eu para ele, por gratidão.

A Igreja pode ousar tanto porque Deus precisa dela: sem ela nem os patriarcas chegam à perfeição, nem se completa o número dos anjos, nem o céu conhece a alegria dos que passaram pelo fogo e pela água. A sua confiança não se apoia nos méritos, mas no desígnio de Deus, que há de cumprir o que decidiu: basta, para o mérito, saber que os méritos não bastam. Fica para outro sermão a questão mais difícil: se uma alma sozinha pode aplicar a si o que se diz da Igreja inteira.

Tradução feita do texto latino de Migne (PL 183, 1108-1112).`,
  pontos: [
    {
      n: 1,
      texto: `Ouvi agora o que ontem adiamos; ouvi a alegria que senti. É vossa também: ouvi com alegria. Senti-a numa só palavra da esposa e, tendo-lhe apenas sentido o perfume, escondi-a, para vos oferecer hoje com tanto mais festa quanto mais a propósito. A esposa falou e disse que o esposo está atento a ela. Quem é a esposa, e quem é o esposo? Ele é o nosso Deus; e ela, se ouso dizê-lo, somos nós, com toda a restante multidão dos cativos que ele conhece. Alegremo-nos: esta é a nossa glória; somos nós aqueles a quem Deus está atento. E, no entanto, que desproporção! Que são diante dele os nascidos da terra e os filhos dos homens (cf. Sl 48,3)? Segundo o profeta, são como se não fossem, e ele os considera como nada e vazio (Is 40,17). Que significa, pois, este emparelhamento de partes tão desiguais? Ou ela se gloria sem medida, ou ele ama sem medida. Que admirável é que ela reivindique para si, como coisa própria, a atenção dele, dizendo: O meu amado para mim! E, não contente com isso, continua a gloriar-se ainda mais: diz que lhe corresponde como de igual para igual, que lhe faz a vontade, que lhe retribui por sua vez. Pois continua: E eu para ele (Ct 2,16). Palavra ousada: e eu para ele. E não menos ousada: o meu amado para mim; a não ser que as duas juntas sejam mais ousadas do que cada uma.`
    },
    {
      n: 2,
      texto: `Oh, que não ousa o coração puro, a consciência boa e a fé sincera (cf. 1Tm 1,5)! Está atento a mim, diz. Então aquela majestade, a quem cabem o governo e a administração do universo, está atenta a ela? E o cuidado dos séculos se transfere unicamente para os negócios — ou antes, para os ócios — do amor e do desejo desta? Exatamente. Pois ela é a Igreja dos eleitos, dos quais diz o Apóstolo: Tudo, por causa dos eleitos (2Tm 2,10). E quem duvida de que a graça e a misericórdia de Deus estão com os seus santos, e o seu olhar sobre os seus eleitos (Sb 4,15)? Não negamos, pois, a providência às outras criaturas; mas o cuidado, a esposa o reivindica para si. Acaso Deus tem cuidado dos bois (1Cor 9,9)? E não há dúvida de que podemos dizer o mesmo dos cavalos, dos camelos, dos elefantes e de todos os animais da terra; e igualmente dos peixes do mar e das aves do céu; enfim, de todas as coisas que há sobre a terra, exceto, é claro, só aqueles a quem se diz: Lançai sobre ele toda a vossa preocupação, porque ele tem cuidado de vós (1Pd 5,7). Não te parece que com estas palavras se diz como que: Estai atentos a ele, porque ele está atento a vós? E observa se o apóstolo Pedro — pois as palavras são dele — não guardou também ele a ordem das palavras da esposa. Pois não diz: Lançai sobre ele toda a vossa preocupação, para que ele tenha cuidado de vós; mas: porque ele tem cuidado de vós; mostrando claramente, assim, não só quanto é amada a Igreja dos santos, mas também que foi amada primeiro.`
    },
    {
      n: 3,
      texto: `É evidente que não se aplica a ela o que o Apóstolo disse dos bois; pois tem cuidado dela aquele que a amou e se entregou por ela (Ef 5,25). Não é ela aquela ovelha perdida, cujo cuidado foi preferido até ao cuidado dos rebanhos do alto? Enfim, deixando aqueles, o pastor desceu até esta, procurou-a com diligência e, encontrando-a, não a fez voltar pelo próprio pé, mas trouxe-a carregada; e, com ela e por causa dela, levou aos céus novas festas de alegria, convidando para a solenidade os povos dos anjos (Lc 15,4-7.10). Que dizer então? Dignou-se trazê-la de volta nos próprios ombros, e não terá cuidado dela? Por isso não se envergonha de dizer: O Senhor cuida de mim (Sl 39,18). Nem pensa enganar-se quando diz igualmente: O Senhor retribuirá por mim (Sl 137,8); e tudo o mais que pareça significar o cuidado de Deus para com ela. Daí vem que chama seu amado ao Senhor dos exércitos, e se gloria de que esteja atento a ela aquele que julga todas as coisas com tranquilidade (Sb 12,18). E por que não se gloriaria? Ouviu-o dizer-lhe: Pode acaso uma mãe esquecer-se, a ponto de não ter compaixão do filho das suas entranhas? E, ainda que ela se esquecesse, eu, contudo, não me esquecerei de ti (Is 49,15). Enfim, os olhos do Senhor estão sobre os justos (Sl 33,16). E que é a esposa, senão a assembleia dos justos? Que é ela, senão a geração dos que buscam o Senhor, dos que buscam a face do esposo (cf. Sl 23,6)? Pois não é que ele esteja atento a ela, e ela não a ele. Por isso põe uma coisa e outra, dizendo: Ele para mim, e eu para ele. Ele para mim, porque é benigno e misericordioso; eu para ele, porque não sou ingrata. Ele para mim, graça por pura graça; eu para ele, graças pela graça (cf. Jo 1,16). Ele, para a minha libertação; eu, para a honra dele. Ele, para a minha salvação; eu, para a vontade dele. Ele para mim, e não para outra, porque sou a sua única pomba (cf. Ct 6,8); eu para ele, e não para outro: pois não ouço a voz dos estranhos (cf. Jo 10,5), nem dou crédito aos que me dizem: Eis aqui o Cristo, ou: Ei-lo ali (Mc 13,21). Isto, quanto à Igreja.`
    },
    {
      n: 4,
      texto: `E cada um de nós? Pensamos que há entre nós alguém a quem se possa aplicar o que se diz? Que disse eu, entre nós? Eu, por mim, não julgaria de modo nenhum repreensível que alguém fizesse esta pergunta a respeito de qualquer um que esteja dentro da Igreja. Pois não é a mesma a condição de um só e a de muitos. Enfim, não por causa de uma só alma, mas para reunir muitas numa só Igreja e estreitá-las numa única esposa, Deus fez e suportou tantas coisas, quando operou a salvação no meio da terra (Sl 73,12). Ela é a caríssima, única para o único: não se une a outro esposo, não cede o lugar a outra esposa. Que não ousará ela junto de um amante que a pretendeu com tanto empenho? Que não esperará daquele que a procurou desde o céu e a chamou dos confins da terra? E não só a procurou, mas a adquiriu. Acrescenta ainda o modo da aquisição: no sangue de quem a adquiriu (cf. At 20,28). Por outro lado, como costuma, confia tanto mais porque, olhando para o futuro, não ignora que o Senhor precisa dela (cf. Mt 21,3). Perguntas para quê? Para ver a bondade dos seus eleitos, para se alegrar com a alegria do seu povo, para ser louvado com a sua herança (Sl 105,5). E não julgues pouca coisa esta necessidade: nenhuma obra, digo-te, ficará acabada, se esta falhar. Não depende acaso do estado e da consumação da Igreja o fim de todas as coisas? Tira-a, e em vão esta criação inferior espera a revelação dos filhos de Deus (cf. Rm 8,19). Tira-a, e nem os patriarcas nem os profetas chegarão à perfeição, pois Paulo afirma que Deus dispôs as coisas a nosso respeito de tal modo que eles não chegassem à perfeição sem nós (Hb 11,40). Tira-a, e a própria glória dos santos anjos coxeará pela incompletude do seu número, e a cidade de Deus não se alegrará da sua integridade.`
    },
    {
      n: 5,
      texto: `Como se cumprirá, então, o desígnio de Deus, o mistério da sua vontade (cf. Ef 1,9) e aquele grande mistério da piedade (cf. 1Tm 3,16)? De onde, enfim, me darás as crianças e os meninos de peito, de cuja boca Deus tire o louvor perfeito (Sl 8,3)? O céu não tem crianças; a Igreja tem, e é a elas que diz: Dei-vos leite a beber, não alimento sólido (1Cor 3,2). E são estes que o Profeta convida como que para completar o louvor, dizendo: Louvai, meninos, o Senhor (Sl 112,1). Pensas tu que o nosso Deus terá todo o louvor da sua glória antes que venham os que, na presença dos anjos, lhe cantem: Alegramo-nos pelos dias em que nos humilhaste, pelos anos em que vimos a desgraça (Sl 89,15)? Este gênero de alegria, os céus não o conheceram senão pelos filhos da Igreja; com esta alegria nunca se alegra quem nunca deixou de alegrar-se. Oportunamente vem a alegria depois da tristeza, o repouso depois do trabalho, o porto depois do naufrágio. A segurança agrada a todos, mas mais a quem teve medo. A luz é agradável a todos, mas mais agradável a quem escapa do poder das trevas (cf. Cl 1,13). Ter passado da morte à vida (cf. Jo 5,24) duplica o encanto da vida. Esta é a minha parte no banquete celeste, distinta da dos próprios espíritos bem-aventurados. Ouso dizer que a própria vida bem-aventurada não teria parte nesta minha felicidade, a não ser que se digne reconhecer que dela goza em mim, pela caridade, e por meio de mim. Parece, com efeito, que também àquela perfeição se acrescentou alguma coisa vinda de mim, e não pouca. Enfim, os anjos se alegram com a penitência do pecador (cf. Lc 15,10). E, se as minhas lágrimas são as delícias dos anjos, que serão as minhas delícias? Toda a obra deles é louvar a Deus; mas falta alguma coisa ao louvor, se faltarem os que digam: Passamos pelo fogo e pela água, e tu nos conduziste ao refrigério (Sl 65,12).`
    },
    {
      n: 6,
      texto: `Feliz, pois, a Igreja na sua universalidade, cuja glória, toda ela, fica aquém do seu motivo, não só pelo que já lhe foi feito, mas também pelo que ainda deve ser feito a respeito dela. Pois por que haveria de se preocupar com os méritos aquela a quem o desígnio de Deus fornece uma razão mais firme e mais segura para se gloriar? Deus não pode negar-se a si mesmo (cf. 2Tm 2,13), nem deixar de fazer o que já fez — ele que, como está escrito, fez o que há de ser (cf. Is 45,11). Fará, fará; Deus não faltará ao seu desígnio. Assim, não tens por que perguntar com que méritos esperamos os bens, sobretudo quando ouves no profeta: Não é por causa de vós, mas por minha causa que eu agirei, diz o Senhor (Ez 36,22). Basta, para o mérito, saber que os méritos não bastam. Mas, assim como para o mérito basta não presumir dos méritos, assim para a condenação basta carecer de méritos. Quanto às crianças renascidas, nenhuma carece de méritos: têm os méritos de Cristo. Tornam-se, porém, indignas deles, se deixarem de lhes juntar os seus — não por não poderem, mas por negligência. Este perigo, é claro, já é da idade adulta. Procura, pois, ter méritos; tendo-os, reconhece que te foram dados; espera o fruto — a misericórdia de Deus —, e terás escapado a todo perigo: o da pobreza, o da ingratidão, o da presunção. Pobreza perniciosa é a falta de méritos; e a presunção do espírito é riqueza enganosa. Por isso diz o Sábio: Não me dês, Senhor, nem riqueza nem pobreza (Pr 30,8). Feliz a Igreja, à qual não faltam nem méritos sem presunção, nem confiança sem apoio nos méritos. Tem em que apoiar a sua confiança, mas não nos méritos; tem méritos, mas para merecer, não para presumir. Não presumir, não é isso mesmo merecer? Portanto, tanto mais seguramente confia quanto menos presume; e não tem por que se envergonhar da palavra de glória aquela que tem tanta matéria para se gloriar. Muitas são as misericórdias do Senhor (cf. Sl 118,156), e a sua verdade permanece para sempre (cf. Sl 116,2).`
    },
    {
      n: 7,
      texto: `E por que não se gloriaria, segura, aquela em testemunho de cuja glória a misericórdia e a verdade se encontraram (Sl 84,11)? Quer diga: O meu amado para mim; quer diga: Esperei, esperei o Senhor, e ele esteve atento a mim (Sl 39,2); quer ainda: O Senhor cuida de mim (Sl 39,18); ou quaisquer outras palavras deste gênero que pareçam exprimir igualmente um afeto divino e um favor singular para com alguém, nada disso julgará alheio a si aquela cuja razão de confiar é o decreto do Senhor; sobretudo não vendo outra esposa, nem outra Igreja, a quem possam acontecer as coisas que não podem deixar de acontecer. Quanto à Igreja, pois, está claro que em nada terá receio de aplicar a si todas estas coisas. Pergunta-se também, a respeito de uma só alma, se, sendo espiritual e santa, lhe é lícito de algum modo ter tal ousadia. Pois uma só da multidão não se arrogará todas as prerrogativas daquela única multidão católica por causa da qual tudo se faz, por maior que seja a santidade em que se destaque. E por isso, a meu ver, será mais difícil achar — se é que se há de achar — como isso pode ser lícito. Por isso julgo necessário tentar esta questão noutro sermão, e não entrar agora pelos caminhos de uma discussão escrupulosa, cuja saída ainda ignoramos, sem que antes se tenha orado, sobre esta palavra escondida, àquele que abre, e ninguém fecha (Ap 3,7), o esposo da Igreja, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
