SERMOES.sermao({
  id: 'bernardo-cantico-52',
  colecao: 'bernardo-cantico',
  ordem: 52,
  numero: 'LII',
  titulo: 'Do arrebatamento a que se chama contemplação, no qual o esposo faz repousar a alma santa, zelando pelo seu repouso',
  fonte: 'De excessu, qui contemplatio dicitur',
  argumento: `As filhas de Jerusalém são proibidas de acordar a esposa, que dorme nos braços do esposo, e ele mesmo vela pelo sono dela. Bernardo não cabe em si de alegria diante dessa condescendência de Deus, e pergunta que sono é esse. Não é o sono do corpo, nem a morte do pecado, mas um sono "vivo e desperto", que não adormece os sentidos: arrebata-os. É uma espécie de morte, o êxtase, que livra a alma não da vida, mas dos laços da vida. Há a morte dos homens, que já não se prendem aos desejos das coisas, e a morte dos anjos, que já não se enredam nas imagens dos corpos; esta é, propriamente, a contemplação. Só quem sobrevoa as imagens foi "para longe" e encontrou o lugar do repouso.

O juramento "pelas gazelas e pelos cervos dos campos", animais de vista aguda e salto rápido, evoca as almas santas e os anjos, cuja companhia as jovenzinhas não devem perturbar por pouca coisa. Mas a esposa não é como os maus pastores, que só querem as ovelhas gordas: fica ao seu critério repousar ou cuidar das filhas. O sermão termina com uma queixa de Bernardo contra os monges que não lhe deixam uma hora livre — queixa que ele logo retira, para que ninguém deixe de o procurar quando precisar.

Tradução feita do texto latino de Migne (PL 183, 1029-1033).`,
  pontos: [
    {
      n: 1,
      texto: `Eu vos conjuro, filhas de Jerusalém, pelas gazelas e pelos cervos dos campos, que não desperteis nem acordeis a amada, até que ela o queira (Ct 2,7). A proibição é para as jovenzinhas — pois é a elas que chama filhas de Jerusalém, porque, embora delicadas e moles, e ainda fracas, por assim dizer, em afetos e ações femininos, se unem à esposa na esperança de progredir e de partir para Jerusalém. São proibidas, pois, de incomodar a esposa que dorme, isto é, de se atreverem a despertá-la de algum modo contra a sua vontade. Pois foi para isso que o dulcíssimo esposo pôs a sua esquerda sob a cabeça dela, segundo o que se disse antes: para a fazer repousar e dormir no seu seio. E agora, como a Escritura prossegue logo, ele mesmo, seu guarda, vela sobre ela com a maior bondade e benevolência, para que, inquietada pelas necessidades frequentes e miúdas das jovenzinhas, não seja obrigada a acordar. Esta é a coerência literal do texto. Mas aquele juramento feito pelas gazelas e pelos cervos dos campos não parece ter, segundo a letra, nenhuma sequência razoável, tanto assim que o entendimento espiritual o reivindica todo para si. Mas, seja como for, entretanto é bom estarmos aqui e contemplarmos um pouco a bondade, a suavidade, a condescendência da natureza divina. Pois que experimentaste jamais, ó homem, nos afetos humanos, de mais doce do que o que agora te é mostrado do coração do Altíssimo? E é mostrado por aquele que sonda as profundezas de Deus (cf. 1Cor 2,10) e não pode ignorar o que há nele, porque é o seu Espírito; e não pode falar outra coisa senão o que viu junto dele, porque é o Espírito da verdade.`
    },
    {
      n: 2,
      texto: `Enfim, não falta no nosso gênero quem tenha merecido a felicidade de se alegrar com este dom, e assim tenha tido em si mesmo a experiência deste suavíssimo segredo — a não ser que não demos fé nenhuma ao passo da Escritura que temos entre mãos, onde claramente se apresenta o esposo celeste zelando com a maior veemência pelo repouso de uma sua amada, cuidadoso de a guardar adormecida entre os próprios braços, para que nenhum incômodo ou inquietação a arranque do seu suavíssimo sono. Não caibo em mim de alegria, porque aquela majestade não desdenha inclinar-se para a nossa fraqueza numa companhia tão familiar e doce, e a Divindade do alto não despreza celebrar núpcias com a alma exilada e mostrar-lhe o afeto de um esposo preso do mais ardente amor. Assim, assim não duvido que seja no céu, como leio na terra; e a alma sentirá com certeza o que contém a página — salvo que esta de modo nenhum basta para exprimir quanto ela então poderá receber, nem sequer quanto já pode. Que pensas que receberá lá aquela que aqui é agraciada com tamanha familiaridade, que se sente abraçada pelos braços de Deus, aquecida no seio de Deus, guardada pelo cuidado e pela solicitude de Deus, para que ninguém a desperte enquanto dorme, até que ela mesma acorde?`
    },
    {
      n: 3,
      texto: `Vamos, pois, digamos, se pudermos, que sono é esse em que o esposo quer que a sua amada adormeça, e não permite de modo nenhum que a despertem senão quando ela quiser; para que ninguém, lendo no Apóstolo: Já é hora de despertarmos do sono (Rm 13,11), ou no Profeta, que pede a Deus que lhe ilumine os olhos para que nunca adormeça na morte (Sl 12,4), se perturbe com o duplo sentido das palavras e não ache de modo nenhum o que pensar dignamente do sono da esposa de que se fala aqui. Pois nem sequer se parece com este aquilo que o Senhor diz de Lázaro no Evangelho: Lázaro, o nosso amigo, dorme; vamos acordá-lo do sono (Jo 11,11). Pois dizia isto da morte do seu corpo, ao passo que os discípulos pensavam que falava do repouso do sono. Mas este sono da esposa não é o sono do corpo — nem o tranquilo, que adormece suavemente por um tempo os sentidos da carne, nem o horrível, que costuma tirar de todo a vida. E muito mais distante está daquele em que se adormece na morte, isto é, quando se persevera irrevogavelmente no pecado que leva à morte (cf. 1Jo 5,16). Antes, este sono vivo e desperto ilumina o sentido interior e, afastada a morte, dá a vida eterna. É verdadeiramente um sono, mas que não adormece o sentido: arrebata-o. É também uma morte — digo-o sem hesitar —, pois o Apóstolo, louvando alguns que ainda viviam na carne, fala assim: Estais mortos, e a vossa vida está escondida com Cristo em Deus (Cl 3,3).`
    },
    {
      n: 4,
      texto: `Por isso, também eu não chamaria absurdamente morte ao êxtase da esposa — morte que, no entanto, não a arranca da vida, mas dos laços da vida, para que possa dizer: A nossa alma escapou, como um pássaro, do laço dos caçadores (Sl 123,7). Pois nesta vida caminha-se no meio de laços, que não se temem todas as vezes que a alma é arrebatada de si mesma por algum pensamento santo e veemente — contanto que se retire e voe com a mente tão longe que ultrapasse também o uso comum e o costume de pensar; pois em vão se lança a rede diante dos olhos dos que têm asas (Pr 1,17). Pois como temer a luxúria, onde nem sequer a vida se sente? Saindo a alma, se não da vida, ao menos do sentido da vida, é necessário que também não sinta a tentação da vida. Quem me dará asas como de pomba, e voarei e repousarei (Sl 54,7)? Oxalá eu caia muitas vezes nesta morte, para escapar dos laços da morte, para não sentir as carícias mortíferas da vida luxuriosa, para ficar insensível ao sentimento da sensualidade, ao ardor da avareza, aos aguilhões da ira e da impaciência, às angústias das preocupações e aos incômodos dos cuidados! Morra a minha alma a morte dos justos (cf. Nm 23,10), para que nenhuma fraude a enlace, nenhuma iniquidade a seduza. Boa morte, que não tira a vida, mas a transfere para melhor; boa, em que não cai o corpo, mas se eleva a alma.`
    },
    {
      n: 5,
      texto: `Mas esta é a morte dos homens. Morra a minha alma também a morte, se assim se pode dizer, dos anjos, para que, saindo da memória das coisas presentes, se dispa não só dos desejos das coisas inferiores e corporais, mas também das suas imagens, e tenha uma convivência pura com aqueles com quem tem a semelhança da pureza. Tal arrebatamento, a meu ver, é o que se chama contemplação — ou somente ele, ou ele sobretudo. Pois não se deixar prender, ao viver, pelos desejos das coisas é próprio da virtude humana; não se envolver, ao contemplar, nas imagens dos corpos é próprio da pureza angélica. Ambas as coisas, porém, são dom divino; ambas são sair de si, ambas são ultrapassar-te a ti mesmo — mas uma para longe, a outra não para longe. Feliz quem pode dizer: Eis que fugi para longe e morei na solidão (Sl 54,8). Não se contentou em sair, mas afastou-se para longe, para poder repousar. Passaste por cima dos deleites da carne, de modo que já não obedeces às suas concupiscências nem te prendes aos seus atrativos: progrediste, separaste-te, mas ainda não foste para longe, se não conseguires também, pela pureza da mente, sobrevoar os fantasmas das imagens corporais que se precipitam de todos os lados. Até aí, não te prometas o repouso. Enganas-te, se julgas encontrar aquém disso o lugar do repouso, o segredo da solidão, a serenidade da luz, a morada da paz. Mas dá-me quem tenha chegado lá, e eu declaro sem hesitar que repousa, e que pode dizer com razão: Volta, minha alma, ao teu repouso, porque o Senhor te fez bem (Sl 114,7). E este é verdadeiramente um lugar na solidão e uma morada na luz — bem conforme o profeta, uma tenda que dá sombra de dia contra o calor, e segurança e abrigo contra o turbilhão e a chuva (Is 4,6); da qual diz também o santo Davi: Escondeu-me na sua tenda no dia da desgraça; protegeu-me no segredo da sua tenda (Sl 26,5).`
    },
    {
      n: 6,
      texto: `Imagina, pois, que a esposa se retirou para esta solidão e ali, pela amenidade do lugar, adormeceu suavemente entre os abraços do esposo — isto é, foi arrebatada em espírito —, quando foi proibido às jovenzinhas despertá-la, até que ela o quisesse. Mas de que modo? Pois não foram proibidas simplesmente, nem com uma leve advertência, como é costume, mas com um juramento de todo novo e insólito: pelas gazelas e pelos cervos dos campos. Com este gênero de animais parecem-me representados com bastante propriedade as almas santas despidas dos corpos e também os anjos que estão com Deus, por causa da agudeza da vista e da rapidez do salto. Pois sabemos que ambas estas coisas convêm a uns e outros espíritos: facilmente se dirigem às alturas e penetram no íntimo. E a sua vida nos campos indica claramente as corridas livres e desembaraçadas da contemplação. Que quer dizer, pois, o juramento feito por eles? Sem dúvida, que as jovenzinhas inquietas não se atrevam, por um motivo leve, a chamar a amada para fora de tão venerável companhia, à qual, sem dúvida, ela se junta todas as vezes que é arrebatada na contemplação. É, pois, belo que as assustem com a autoridade daqueles de cuja companhia, como é certo, ela é arrancada pela importunidade delas. Reparem as jovenzinhas a quem ofendem ao mesmo tempo, quando inquietam a mãe; e não confiem tanto na caridade materna que não temam irromper naquela assembleia celeste sem grande necessidade. Pois pensem que é isto que fazem todas as vezes que molestam mais do que é justo a que repousa na contemplação. Fica, com efeito, na vontade dela tanto dedicar-se a si mesma como aplicar-se ao cuidado delas, conforme julgar conveniente, quando se proíbe que elas a despertem até que ela o queira. O esposo sabe com quanto amor a esposa arde também pelo próximo, e que a mãe é bastante solicitada pela sua própria caridade a cuidar dos progressos das filhas, e que de modo nenhum se lhes subtrairá nem se lhes negará, tanto e tantas vezes quanto for preciso; e por isso julgou que podia confiar com segurança ao discernimento dela esta administração. Pois ela não é como muitos que vemos marcados a ferro pela palavra profética, que tomam o que é gordo e forte e rejeitam o que é fraco (Ez 34,3-4). Acaso o médico procura os sãos, e não antes os doentes (cf. Mt 9,12)? Se o faz, fá-lo talvez como amigo, mas não como médico. A quem ensinarás, bom Mestre, se repelires todos os ignorantes? Com quem, pergunto, empregarás o cuidado da disciplina, se afugentares todos os indisciplinados, ou fugires deles? Com quem, peço-te, provarás a tua paciência, se admitires só os mansos e excluíres os inquietos?`
    },
    {
      n: 7,
      texto: `Há, contudo, entre os que aqui estão sentados, alguns que oxalá considerassem com mais atenção este passo. Pensariam, sem dúvida, quanta reverência se deve aos superiores, pois, inquietando-os temerariamente, tornam-se hostis também aos cidadãos do céu; e começariam talvez a poupar-nos um pouco mais que de costume, e já não se intrometeriam com tanta irreverência e leviandade quando estamos livres. Bem raramente, como eles sabem, me é concedida uma hora de descanso dos que chegam — e isto mesmo quando eles me suportam com toda a paciência. Mas faço esta queixa com bastante escrúpulo, para que nenhum pusilânime, por temer inquietar-me, cale as suas necessidades além do que a sua paciência aguenta. Desisto, pois, também para não parecer dar aos fracos um exemplo de impaciência. Os pequenos que creem no Senhor são dele; não permito que sofram escândalo por minha causa (cf. Mt 18,6). Não uso deste poder (cf. 1Cor 9,12); antes, que eles usem de mim como quiserem, contanto que se salvem. Hão de poupar-me, se não me pouparem; e eu repousarei antes nisto: em que não tenham medo de me inquietar pelas suas necessidades. Farei a vontade deles quanto puder, e neles servirei ao meu Deus enquanto viver, com caridade sem fingimento. Não buscarei o que é meu; e não julgarei útil para mim o que me é útil, mas o que é útil a muitos (cf. 1Cor 10,33). Só peço isto: que o meu ministério lhes seja agradável e proveitoso, para que talvez ao menos por isso eu ache misericórdia, no dia mau, aos olhos do Pai deles e também do esposo da Igreja, Jesus Cristo, Senhor nosso, que com ele é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
