SERMOES.sermao({
  id: 'bernardo-cantico-83',
  colecao: 'bernardo-cantico',
  ordem: 83,
  numero: 'LXXXIII',
  titulo: 'Como a alma, por mais corrompida que esteja pelos vícios, ainda pode voltar, pelo amor casto e santo, à semelhança do esposo, isto é, de Cristo',
  fonte: 'Qualiter anima per amorem castum et sanctum potest redire ad similitudinem sponsi',
  argumento: `Resumindo os três sermões anteriores, Bernardo tira a conclusão: toda alma, por mais carregada de pecados, presa, dispersa e desesperada que esteja, pode descobrir em si, pela imagem e pela semelhança que nunca perdeu, não só motivo para esperar o perdão, mas ousadia para aspirar às núpcias do Verbo. Basta que não deixe dormir o empenho e se converta ao Verbo, para ser reformada por ele e conformada a ele na caridade: quando, semelhante a ele pela natureza, se torna semelhante também pela vontade, amando como é amada, está casada com ele.

Entre esposos só há um laço: amar e ser amado. Deus quer ser temido como Senhor, honrado como pai e amado como esposo; e o amor prevalece, porque sem ele o temor é servil e a honra, adulação. O amor basta a si mesmo, não busca causa nem fruto fora de si: "amo porque amo; amo para amar". É o único afeto em que a criatura pode retribuir ao Criador com algo semelhante. O amor dos filhos ainda pensa na herança; o da esposa é puro, sem interesse. E, embora a esposa ame menos, porque é menor, se ama com todo o seu ser nada lhe falta, pois foi amada primeiro e mais.

Tradução feita do texto latino de Migne (PL 183, 1181-1184).`,
  pontos: [
    {
      n: 1,
      texto: `Na medida em que o permitiu a hora regular que fixamos para falar, gastamos estes três dias em demonstrar a afinidade do Verbo e da alma. Que utilidade há em todo este trabalho? Esta. Ensinamos que toda alma — ainda que carregada de pecados, enredada em vícios, presa pelas seduções, cativa no exílio, encarcerada no corpo, pegada à lama, cravada no lodo, fixada aos membros, traspassada de cuidados, dispersa em negócios, encolhida pelos temores, afligida pelas dores, errante nos enganos, ansiosa pelas preocupações, inquieta pelas suspeitas, e enfim estrangeira em terra de inimigos, segundo a palavra do profeta, contaminada com os mortos, contada entre os que estão no inferno (Br 3,10-11) —, ainda que, digo, assim condenada e assim desesperada, pode, contudo, descobrir em si mesma não só com que respirar na esperança do perdão, na esperança da misericórdia, mas também com que ousar aspirar às núpcias do Verbo, não tremer de firmar com Deus um pacto de aliança, não recear levar com o Rei dos anjos o suave jugo do amor. Pois que não ousará com segurança junto daquele cuja imagem vê que traz como insígnia, cuja semelhança sabe que a torna ilustre? Que temerá, digo, da majestade, aquela a quem a própria origem dá confiança? Basta que cuide de conservar a nobreza da natureza com a honestidade da vida; ou antes, que se esforce por embelezar e adornar a beleza celeste, que está nela desde a origem, com as cores dignas dos costumes e dos afetos.`
    },
    {
      n: 2,
      texto: `Pois por que havia de dormir o empenho? Ele mesmo é, certamente, um grande dom da natureza em nós; e, se não cumprir a sua parte, não se perturbará tudo o que a natureza ainda tem em nós, não se cobrirá tudo como que de uma ferrugem de velhice? E isto seria uma injúria ao Criador. E foi para isto, certamente, que o próprio Deus Criador quis que se conservasse para sempre na alma a insígnia da nobreza divina: para que ela tenha sempre em si, vinda do Verbo, aquilo que sempre a advirta de permanecer com o Verbo, ou de voltar para ele, se se tiver afastado. Afastada, não como quem muda de lugar ou anda a pé; mas, movendo-se — como se move uma substância espiritual, com os seus afetos, ou antes, com os seus defeitos —, sai de certo modo de si para pior, quando pela perversidade da vida e dos costumes se torna dessemelhante de si mesma e se faz degenerada; esta dessemelhança, contudo, não é abolição da natureza, mas vício, que, pela comparação consigo, faz sobressair o próprio bem da natureza tanto quanto o mancha pela união. A volta da alma, por sua vez, é a sua conversão ao Verbo, para ser reformada por ele e conformada a ele. Em quê? Na caridade. Pois diz: Sede imitadores de Deus, como filhos caríssimos; e andai no amor, como também Cristo vos amou (Ef 5,1-2).`
    },
    {
      n: 3,
      texto: `Tal conformidade desposa a alma com o Verbo, quando, sendo semelhante a ele pela natureza, se mostra semelhante a ele também pela vontade, amando como é amada. Se, pois, ama perfeitamente, está casada. Que há de mais agradável que esta conformidade? Que há de mais desejável que a caridade, pela qual, ó alma, não contente com o magistério humano, te aproximas por ti mesma, com confiança, do Verbo, te unes constantemente ao Verbo, interrogas familiarmente o Verbo e o consultas sobre todas as coisas, tão ousada no desejo quanto capaz na inteligência? Este é verdadeiramente o contrato de um casamento espiritual e santo. Disse pouco, contrato: é um abraço. Abraço, sem dúvida, em que o querer e o não querer a mesma coisa fazem de dois um só espírito. E não se deve temer que a desigualdade das pessoas faça coxear em alguma coisa a concordância das vontades, porque o amor não conhece reverência. Pois o amor tira o nome de amar, não de honrar. Honre, sim, quem se arrepia, quem se pasma, quem teme, quem se admira: tudo isto cessa em quem ama. O amor basta a si mesmo; o amor, quando vem, atrai a si e toma cativos todos os outros afetos. Por isso a que ama, ama, e não conhece outra coisa. Ele mesmo, que com razão é digno de honra, e com razão de pasmo e de admiração, prefere, contudo, ser amado. São esposo e esposa. Que outro laço ou vínculo procuras entre esposos, senão ser amado e amar? Este laço vence até aquele que a natureza atou mais estreitamente, o vínculo dos pais com os filhos. Enfim: Por isso, diz, o homem deixará seu pai e sua mãe e se unirá à sua esposa (Mt 19,5). Vês como este afeto, nos esposos, é mais forte não só que os outros afetos, mas até que ele mesmo.`
    },
    {
      n: 4,
      texto: `Acrescenta que este esposo não só ama, mas é o amor. Será a honra? Sustente-o quem quiser: eu não o li. Li, porém, que Deus é amor (1Jo 4,16); e não li que é honra ou dignidade. Não que Deus não queira a honra, ele que diz: Se eu sou pai, onde está a minha honra? Mas isto é o Pai. Se se mostrar como esposo, penso que mudará a voz e dirá: Se eu sou esposo, onde está o meu amor? Pois também antes falou assim: Se eu sou Senhor, onde está o meu temor (Ml 1,6)? Deus exige, pois, ser temido como Senhor, honrado como pai, e amado como esposo. Qual destas coisas prevalece, qual sobressai? O amor, sem dúvida. Sem ele, o temor traz castigo (cf. 1Jo 4,18), e a honra não tem graça. O temor é servil enquanto não é alforriado pelo amor. E a honra que não vem do amor não é honra, mas adulação. É verdade que só a Deus a honra e a glória (1Tm 1,17); mas Deus não aceitará nenhuma destas coisas, se não estiverem temperadas com o mel do amor. O amor basta por si mesmo, agrada por si mesmo e por causa de si mesmo. Ele é mérito e prêmio para si mesmo. O amor não busca, fora de si, nem causa nem fruto. O seu fruto é o seu exercício. Amo porque amo; amo para amar. Grande coisa é o amor, contanto que volte ao seu princípio, que, restituído à sua origem e refluindo para a sua fonte, beba sempre dela aquilo com que possa correr sem cessar. De todos os movimentos, sentidos e afetos da alma, o amor é o único em que a criatura pode corresponder ao Criador, ainda que não de igual para igual, e retribuir-lhe com algo semelhante. Por exemplo: se Deus se irar comigo, porventura me irarei eu igualmente contra ele? Certamente não; mas terei medo, tremerei, pedirei perdão. Assim também, se me repreender, não será repreendido por mim, mas antes será justificado por mim (cf. Sl 50,6). Nem, se me julgar, o julgarei eu a ele, mas o adorarei; e, salvando-me, não pede para ser salvo por mim, nem precisa de ser libertado por alguém aquele que liberta a todos. Se domina, cabe-me servir; se manda, cabe-me obedecer, e não exigir por minha vez do Senhor serviço ou obediência. Vê agora como é diferente quanto ao amor. Pois, quando Deus ama, não quer outra coisa senão ser amado: não ama para outra coisa senão para ser amado, sabendo que os que o amarem serão felizes pelo próprio amor.`
    },
    {
      n: 5,
      texto: `Grande coisa é o amor; mas há nele graus. A esposa está no mais alto. Pois também os filhos amam, mas pensam na herança; e, temendo perdê-la de algum modo, reverenciam mais e amam menos aquele de quem esperam a herança. É-me suspeito o amor que parece apoiar-se na esperança de obter outra coisa. É fraco o amor que, se lhe tiram a esperança, talvez se apague ou diminua. É impuro o que deseja também outra coisa. O amor puro não é mercenário. O amor puro não tira as suas forças da esperança, e, contudo, não sente os danos da desconfiança. Este é o da esposa, porque a esposa, seja quem for, é isto. A posse e a esperança da esposa são uma só: o amor. Disto a esposa tem em abundância, e com isto se contenta o esposo. Nem ele busca outra coisa, nem ela tem outra coisa. Por isso ele é esposo, e ela é esposa. Este amor é próprio dos esposos, e nenhum outro o alcança, nem sequer o filho. Enfim, aos filhos clama: Onde está a minha honra? e não diz: Onde está o meu amor?, guardando para a esposa a prerrogativa. E também se manda ao homem honrar seu pai e sua mãe (Dt 5,16), e cala-se sobre o amor; não porque os pais não devam ser amados pelos filhos, mas porque muitos filhos estão mais inclinados a honrar os pais do que a amá-los. Seja: a honra do rei ama o juízo (Sl 98,4); mas o amor do esposo — ou antes, o esposo, que é o Amor — só pede em troca amor e fidelidade. Seja, pois, permitido à amada amar por sua vez. Como não havia de amar a esposa, e esposa do Amor? Como não havia de ser amado o Amor?`
    },
    {
      n: 6,
      texto: `Com razão, renunciando a todos os outros afetos, entrega-se toda e só ao amor aquela que tem de corresponder ao próprio Amor retribuindo amor. Pois, mesmo quando se tiver derramado toda em amor, que é isso em comparação com o fluxo perene daquela fonte? Não correm com igual abundância a que ama e o Amor, a alma e o Verbo, a esposa e o esposo, o Criador e a criatura, não mais do que o sedento e a fonte. E então? Perecerá por isso, e será de todo frustrado o voto da que vai casar-se, o desejo da que suspira, o ardor da que ama, a confiança da que ousa, porque não pode correr de igual para igual com o gigante (cf. Sl 18,6), competir em doçura com o mel, em mansidão com o cordeiro, em brancura com o lírio, em claridade com o sol, em amor com aquele que é o Amor? Não. Pois, embora a criatura ame menos, porque é menor, se ama com todo o seu ser, nada falta onde há tudo. Por isso, como disse, amar assim é estar casada; porque não pode amar assim e ser pouco amada, de modo que no consentimento dos dois se firma um casamento íntegro e perfeito. A não ser que alguém duvide de que a alma é amada pelo Verbo primeiro e mais. Certamente, no amar, é antecipada e vencida. Feliz aquela que mereceu ser antecipada com a bênção de tão grande doçura (cf. Sl 20,4)! Feliz aquela a quem foi dado experimentar o abraço de tão grande suavidade! O qual não é outra coisa senão o amor santo e casto, o amor suave e doce, amor de tanta serenidade quanta sinceridade, amor mútuo, íntimo e forte, que une dois não numa só carne, mas num só espírito, e faz que os dois já não sejam dois, mas um, como diz Paulo: Quem se une a Deus é um só espírito com ele (1Cor 6,17). E agora ouçamos antes sobre isto aquela que a unção mestra (cf. 1Jo 2,27) e a experiência frequente fizeram facilmente mestra de todas estas coisas. A não ser que seja melhor guardarmos isto para o princípio de outro sermão, para não apertarmos uma coisa tão boa nos limites deste, que já está quase a terminar. E, se aprovais, termino até antes do fim, para que amanhã, famintos, nos reunamos a tempo para as delícias da alma santa, de que ela, bem-aventurada, merece gozar com o Verbo e do Verbo, o seu esposo, Jesus Cristo, nosso Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
