SERMOES.sermao({
  id: 'bernardo-cantico-64',
  colecao: 'bernardo-cantico',
  ordem: 64,
  numero: 'LXIV',
  titulo: 'Das tentações dos monges adiantados, que são as raposas mais perigosas para eles; e de como se devem apanhar os hereges, raposas da Igreja',
  fonte: 'De tentationibus monachorum provectorum',
  argumento: `As raposas são as tentações. Aos principiantes, o perigo vem às claras, como a geada; aos que já progridem, vem escondido, como raposas: vícios com aparência de virtude. Bernardo dá exemplos tirados da vida do mosteiro. Um monge fervoroso pensa que, se voltasse para a sua terra, converteria os parentes e os amigos; vai, e perde-se sem ganhar ninguém. Outro sente desejo de pregar em público; mas o ofício do monge é chorar, não ensinar, e pregar não convém ao monge, não é proveitoso ao noviço e não é lícito a quem não foi enviado. Outros deixam o mosteiro pelo ermo e voltam tíbios; outros, com abstinências singulares, perturbam a comunidade inteira.

Estas raposas são pequenas pela sutileza, e o esposo manda "apanhá-las", isto é, desmascará-las: uma vez reconhecidas, já não fazem mal. Na leitura alegórica, as raposas são os hereges, e a ordem é apanhá-los com argumentos, e não com armas, para os reconciliar com a Igreja; só os obstinados, depois de duas advertências, devem ser evitados ou contidos. E o esposo diz "apanhai-nos": fala como quem tudo partilha, porque o amor triunfa até sobre Deus.

Tradução feita do texto latino de Migne (PL 183, 1083-1088).`,
  pontos: [
    {
      n: 1,
      texto: `Aqui estou para cumprir a minha promessa. Apanhai-nos as raposas pequenas, que destroem as vinhas; pois a nossa vinha está em flor (Ct 2,15). As raposas são as tentações. É inevitável que venham as tentações (cf. Mt 18,7). Pois quem será coroado, senão quem tiver lutado segundo as regras (2Tm 2,5)? E como lutarão, se faltar quem ataque? Tu, pois, ao te aproximares do serviço de Deus, permanece no temor e prepara a tua alma para a tentação (Eclo 2,1), certo de que todos os que querem viver piedosamente em Cristo sofrerão perseguição (2Tm 3,12). E as tentações são diversas, conforme a diversidade dos tempos. Sobre os nossos começos, como sobre as flores tenras das plantações novas, abate-se às claras a força do frio, de que falamos no outro sermão, prevenindo os principiantes contra esta peste. Mas aos empenhos mais santos dos que progridem as forças contrárias não ousam opor-se abertamente; costumam armar ciladas às escondidas, como umas raposinhas astutas: virtudes na aparência, vícios na realidade. Quantos, por exemplo, que tinham entrado nos caminhos da vida, que tinham avançado para o melhor, que caminhavam e progrediam bem e seguros pelas veredas da justiça, vi — que vergonha! — derrubados pela astúcia destas raposas, e chorar tarde demais os frutos das virtudes sufocados em si!`
    },
    {
      n: 2,
      texto: `Vi eu um homem que corria bem; e eis que lhe veio um pensamento — por que não diria que foi uma raposinha? A quantos, diz ele, eu poderia repartir o bem de que gozo sozinho, se estivesse na minha terra — irmãos e parentes, conhecidos e amigos! Eles me amam, e facilmente se deixariam persuadir por mim. Para que este desperdício? Vou para lá, e salvo muitos deles, e também a mim. E não há o que temer na mudança de lugar. Pois, contanto que eu faça o bem, que importa onde? A não ser que é sem dúvida melhor viver lá onde eu viva com mais fruto. Que mais? Vai, e perde-se o infeliz — não tanto um exilado que volta à pátria quanto um homem que volta ao vômito da carne. E o infeliz perdeu-se a si mesmo, e não ganhou nenhum dos seus. Eis uma raposinha: aquela esperança enganosa que teve de ganhar os seus. Também tu podes, por ti mesmo, encontrar ou notar em ti outras e outras semelhantes a esta, se não fores descuidado.`
    },
    {
      n: 3,
      texto: `Queres, contudo, que eu te mostre ainda outra? Faço-o, e hei de mostrar-te também uma terceira e uma quarta, se te achar vigilante para apanhar as que porventura destas notares na tua vinha. Às vezes, a alguém que progride bem, quando sente que se derrama sobre ele com mais abundância alguma graça do alto, entra no ânimo o desejo de pregar — não, é verdade, aos pais e aos parentes, segundo aquilo: Não consultei imediatamente a carne e o sangue (Gl 1,16); mas, como coisa mais pura, mais frutuosa e mais forte, aos estranhos e a todos, por toda parte. Com muita prudência, parece. Teme, sem dúvida, incorrer na maldição profética, se esconder do povo o trigo que recebeu às escondidas (cf. Pr 11,26), e agir contra o Evangelho, se não pregar sobre os telhados o que ouviu ao ouvido (Mt 10,27). É uma raposa, e tanto mais nociva que a anterior quanto vem mais escondida. Mas eu a apanho para ti. Primeiro diz Moisés: Não lavrarás com o primogênito do boi (Dt 15,19). Interpretando isto, Paulo diz: Não um recém-convertido, para que não caia, ensoberbecido, na condenação do diabo (1Tm 3,6); e ainda: Ninguém toma para si esta honra, senão quem é chamado por Deus, como Aarão (Hb 5,4); e o mesmo diz: Como pregarão, se não forem enviados (Rm 10,15)? E sabemos que o ofício do monge não é ensinar, mas chorar. Juntando estas e outras coisas semelhantes, teço para mim uma rede e apanho a raposa, para que não destrua a vinha. Pois por estas coisas fica claro e certo que pregar em público não convém ao monge, não é proveitoso ao noviço, e não é lícito a quem não foi enviado. E ir contra estas três coisas, que destruição da consciência não é! Tudo, pois, o que de semelhante for sugerido ao ânimo, quer seja pensamento teu, quer sugestão do anjo mau, reconhece nisso a raposinha astuta, isto é, o mal sob a aparência do bem.`
    },
    {
      n: 4,
      texto: `Mas olha outra. A quantos, fervorosos de espírito, saídos dos mosteiros, recebeu a solidão do ermo, e depois ou os vomitou tíbios, ou os reteve, contra a lei do ermo, não só relaxados, mas até dissolutos? E assim se viu que ali estivera uma raposinha, pois se fez tamanha devastação da vinha, isto é, tamanho dano à vida e à consciência do homem. Pensava que, vivendo sozinho, colheria frutos do espírito muito mais abundantes, ele que tanta graça espiritual experimentara na vida comum. E o seu pensamento pareceu-lhe bom; mas o desfecho mostrou que aquele pensamento fora antes para ele uma raposa destruidora.`
    },
    {
      n: 5,
      texto: `E que dizer daquilo que também a nós, nesta casa, inquieta tantas vezes e tão gravemente — falo da abstinência singular e exagerada de alguns que estão entre nós, com a qual se tornam molestos a todos, e todos molestos a eles? Como não seria esta discórdia tão geral tanto a ruína da sua própria consciência como, quanto dele depende, a destruição desta grande vinha que a destra do Senhor plantou, isto é, da concórdia de todos vós? Ai do homem por quem vem o escândalo (Mt 18,7)! Quem escandalizar, diz, um destes pequeninos (Mc 9,41) — duro é o que se segue. Quanto mais duro merece quem escandaliza uma multidão tão grande e tão santa? Carregará o juízo mais duro, seja ele quem for. Mas isto fica para outra ocasião.`
    },
    {
      n: 6,
      texto: `Mas agora atentemos no que o Esposo diz destes animais pequenos e astutos que destroem as vinhas. Pequenos, digo, não na maldade, mas na sutileza. Pois este gênero de animal é astuto por natureza, e muito pronto para prejudicar às escondidas; e parece-me designar com toda propriedade certos vícios sutilíssimos, disfarçados sob a aparência de virtudes, cuja forma já mostrei um pouco com os exemplos, ainda que poucos, que dei acima para que os conhecêsseis. Pois não podem prejudicar de outro modo senão fingindo-se virtudes por uma certa semelhança com as virtudes. E são ou pensamentos vãos dos homens, ou sugestões feitas pelos anjos maus, os anjos de Satanás, que se transfiguram em anjos de luz (2Cor 11,14), preparando as suas flechas na aljava, isto é, às escondidas, para ferir no escuro os retos de coração (Sl 10,3). Por isso julgo que se chamam pequenas, porque, enquanto os outros vícios se mostram manifestos por uma espécie de corpulência, este gênero, pela sua sutileza, não se reconhece facilmente, e por isso não se pode evitar, senão pelos perfeitos e exercitados, que têm os olhos do coração iluminados (cf. Ef 1,18) para discernir o bem e o mal, e sobretudo para o discernimento dos espíritos, e que podem dizer com o Apóstolo: Não ignoramos as astúcias de Satanás, nem os seus pensamentos (2Cor 2,11). E vê se não é por isso que o esposo manda, não que sejam exterminadas, afugentadas ou mortas, mas apanhadas: porque estes animaizinhos espirituais e astutos devem ser observados e examinados com toda a vigilância e cautela, e assim apanhados, isto é, surpreendidos na sua astúcia. Quando, pois, se denuncia o engano, quando se descobre a fraude, quando se prova a falsidade, então se diz com toda a propriedade que foi apanhada a raposa pequena que destruía a vinha. Enfim, dizemos que um homem é apanhado na palavra, como tens no Evangelho: os fariseus reuniram-se para apanhar Jesus em alguma palavra (Mt 22,15).`
    },
    {
      n: 7,
      texto: `Assim, pois, o esposo manda apanhar as raposas pequenas que destroem as vinhas, isto é, surpreendê-las, desmascará-las, denunciá-las. Só este gênero de maldade tem isto de próprio: que, uma vez reconhecido, já não faz mal; de modo que ser reconhecido é para ele ser vencido. Pois quem, senão um louco, depois de descobrir a armadilha, mete nela o pé sabendo o que faz? Basta, pois, que as coisas deste gênero sejam apanhadas, isto é, que as denuncies e as tragas a público; pois para elas aparecer é perecer. Não assim os outros vícios. Esses vêm às claras e fazem mal às claras; aprisionam quem sabe, vencem quem resiste, porque agem pela força, não pela astúcia. Contra estes animais que se enfurecem às claras não é preciso investigação, mas freio. Só estas raposas pequenas, grandíssimas fingidoras, porque, denunciadas, já não fazem mal, basta trazê-las à luz e apanhá-las na sua astúcia. Pois têm tocas. Por esta razão, pois, manda-se apanhar estas raposas, e descrevem-se como pequenas. Ou então são pequenas para que, observando com vigilância os vícios que nascem, os apanhes logo no próprio nascimento, enquanto são pequenos, para que, crescendo, não façam mais mal e não sejam mais difíceis de apanhar.`
    },
    {
      n: 8,
      texto: `E, se, segundo a alegoria, entendermos por vinhas as Igrejas, e por raposas as heresias, ou antes os próprios hereges, o sentido é simples: que os hereges sejam apanhados, e não afugentados. Apanhados, digo, não com armas, mas com argumentos, com os quais se refutem os seus erros; e eles mesmos, se for possível, sejam reconciliados com a Igreja católica e chamados de volta à verdadeira fé. Pois esta é a vontade daquele que quer que todos os homens se salvem e cheguem ao conhecimento da verdade (1Tm 2,4). Enfim, mostra que é isto o que quer, pois não diz simplesmente: Apanhai as raposas, mas: Apanhai-nos as raposas. Manda, pois, que estas raposas sejam ganhas para si e para a sua esposa, isto é, para a Igreja católica, quando diz: Apanhai-as para nós. Por isso o homem da Igreja, exercitado e douto, se se põe a discutir com um herege, deve dirigir a sua intenção a convencer o que erra de tal modo que também o converta, lembrando-se daquilo do apóstolo Tiago: Quem fizer voltar um pecador do erro do seu caminho salvará a sua alma da morte e cobrirá uma multidão de pecados (Tg 5,20). E, se não quiser voltar, nem convencido depois da primeira e da segunda advertência, como quem está de todo pervertido, deverá ser evitado, segundo o Apóstolo (Tt 3,10). Daí em diante, a meu ver, é melhor afugentá-lo, ou até prendê-lo, do que deixá-lo destruir as vinhas.`
    },
    {
      n: 9,
      texto: `E nem por isso julgue que não fez nada quem venceu e convenceu o herege, refutou as heresias, distinguiu clara e abertamente o verossímil do verdadeiro, mostrou com razões claras e irrefutáveis que as doutrinas perversas são perversas, e enfim reduziu ao cativeiro o entendimento perverso que se levantava contra o conhecimento de Deus (cf. 2Cor 10,5). Pois quem fez tais coisas apanhou igualmente a raposa, ainda que não para a salvação dela; e apanhou-a para o esposo e para a esposa, embora de outro modo. Pois, ainda que o herege não se tenha levantado da borra, a Igreja é confirmada na fé; e o esposo, sem dúvida, alegra-se com os progressos da esposa. Pois a alegria do Senhor é a nossa fortaleza (Ne 8,10). Enfim, não julga alheios a si os nossos ganhos aquele que se associa a nós com tanta bondade, quando manda apanhar as raposas, não para si, mas para nós com ele. Apanhai-nos, diz. Pois é de notar que diz "nos". Que há de mais fraterno do que esta palavra? Não te parece dizê-lo como um pai de família que nada tem só para si, mas tudo em comum com a mulher, os filhos e os da casa? E quem fala é Deus; mas não o diz como Deus, e sim como esposo.`
    },
    {
      n: 10,
      texto: `Apanhai-nos as raposas. Vês com que espírito de companhia fala quem não tem companheiro? Podia dizer: Para mim; mas preferiu: Para nós, deleitando-se na companhia. Ó suavidade! Ó graça! Ó força do amor! Assim o mais alto de todos se fez um entre todos? Quem fez isto? O amor, que não conhece a dignidade, rico em condescendência, poderoso no afeto, eficaz na persuasão. Que há de mais violento? O amor triunfa sobre Deus. E, contudo, que há de menos violento? É o amor. Que força é esta, pergunto, tão violenta para vencer, tão vencida para a violência? Enfim, esvaziou-se a si mesmo (Fl 2,7), para que saibas que foi obra do amor que a plenitude se derramasse, que a altura se igualasse, que a singularidade se associasse. Com quem tens, ó admirável esposo, tão familiar companhia? Apanhai-nos, dizes. Quem está contigo? A Igreja dos gentios? Foi reunida de mortais e pecadores. Sabemos quem ela é. Mas tu, quem és, amante tão devotado e tão ardente desta etíope? Sem dúvida, não um outro Moisés, mas mais que Moisés (cf. Nm 12,1). És tu aquele, o mais belo dos filhos dos homens (Sl 44,3)? Disse pouco: és a brancura da vida eterna, o esplendor e a figura da substância de Deus (Hb 1,3); enfim, Deus acima de todas as coisas, bendito pelos séculos. Amém (Rm 9,5).`
    }
  ]
});
