SERMOES.sermao({
  id: 'bernardo-cantico-09',
  colecao: 'bernardo-cantico',
  ordem: 9,
  numero: 'IX',
  titulo: 'Dos peitos do esposo, isto é, de Cristo: um é a longanimidade em esperar os pecadores; o outro, a bondade em recebê-los',
  fonte: 'De uberibus sponsi, id est Christi',
  argumento: `O sermão abre com uma cena. Os companheiros do esposo encontram a esposa a resmungar e a interrogam: já não recebeste o beijo dos pés e o da mão? De que te queixas? A resposta é a confissão de quem cumpre tudo e não sente nada — «em tudo isso o que há é só costume: de doçura, nada».

Entra então no versículo seguinte, «os teus peitos são melhores que o vinho», e Bernardo o lê de três modos, conforme seja a esposa, o esposo ou os companheiros quem fala. O terceiro traz o aviso que todo contemplativo precisa ouvir.

Tradução feita do texto latino de Migne (PL 183, 815-819).`,
  pontos: [
    {
      n: 1,
      texto: `Cheguemos enfim ao livro, e demos às palavras da esposa uma razão e um encadeamento. Pois elas ficam no ar e, cortadas assim, oscilam sem começo. É preciso, portanto, pôr antes alguma coisa a que possam ligar-se convenientemente. Suponhamos, pois, que aqueles a quem chamamos companheiros do esposo tenham vindo também agora visitar e saudar a esposa, como ontem e anteontem; e que, encontrando-a a resmungar e enfadada, se admirem da causa e lhe falem mais ou menos assim. Que houve de novo? Por que te vemos mais triste que de costume? Qual a causa desse queixume inesperado? Não é verdade que, quando andavas desviada e estranha, atrás dos teus amantes, com quem te ias mal, e foste enfim forçada a voltar ao teu primeiro marido, insististe com muitas preces e lágrimas para ao menos mereceres tocar-lhe os pés? Lembro-me, diz ela. E depois? Uma vez alcançado isso, e recebido no beijo dos pés o perdão das ofensas, não ficaste de novo impaciente, sem te contentares com favor tão grande, mas desejosa de maior intimidade? E não pediste e obtiveste, com a mesma insistência de antes, também a segunda graça, de modo que no beijo da mão recebeste virtudes não poucas nem pequenas? Não o nego, diz ela. E eles: Mas não és tu que costumavas jurar e afirmar que, se alguma vez te fosse dado chegar ao beijo da mão, isso já te bastaria, e que nada mais pedirias daí em diante? Sou eu. Então? Queixas-te acaso de que te tenham tirado alguma coisa do que havias recebido? Nada. Ou temes que te venham a cobrar de novo aquilo que julgavas perdoado da tua antiga vida má? Não.`
    },
    {
      n: 2,
      texto: `Vamos, pois: dize em que te podemos satisfazer. Não sossego, diz ela, enquanto ele não me beijar com o beijo da sua boca. Obrigada pelo beijo dos pés, obrigada também pelo da mão; mas, se ele tem algum cuidado de mim, Beije-me com o beijo da sua boca (Ct 1,1). Não sou ingrata: é que amo. Recebi, confesso, mais do que mereço, mas muito menos do que desejo. É o desejo que me leva, não a razão. Não me acuseis, peço, de presunção, onde é o afeto que aperta. O pudor protesta, sem dúvida; mas o amor é mais forte. E não ignoro que a honra do rei ama o juízo (Sl 98,4); mas o amor, quando se precipita, não espera pelo juízo, não se modera pelo conselho, não se refreia pelo pudor, não se sujeita à razão. Peço, suplico, exijo: beije-me com o beijo da sua boca. Eis que, pela graça dele, há muitos anos cuido de viver com castidade e sobriedade; aplico-me à leitura, resisto aos vícios, entrego-me muitas vezes à oração; vigio contra as tentações, repasso os meus anos na amargura da minha alma (Is 38,15). Julgo portar-me entre os irmãos sem dar motivo de queixa, quanto está em meu poder; estou sujeita às autoridades superiores; saio e volto ao mando do superior. Não cobiço o alheio; antes dei o que era meu, e a mim mesma junto. Como o meu pão com o suor do meu rosto (Gn 3,19). No entanto, em tudo isso o que há é só costume: de doçura, nada. Que sou eu, senão, como diz o profeta, a novilha de Efraim, ensinada a gostar da debulha? (Os 10,11) E, no Evangelho, quem faz só aquilo que deve fazer é tido por servo inútil (Lc 17,10). Os mandamentos, talvez os cumpra de algum modo; mas a minha alma está neles como terra sem água (Sl 142,6). Para que, pois, o meu holocausto seja rico: beije-me, peço, com o beijo da sua boca.`
    },
    {
      n: 3,
      texto: `Muitos de vós, se bem me lembro, também costumam queixar-se a mim, nas confissões particulares, desse langor de alma ressequida e dessa dureza de mente embotada: de não conseguirem penetrar as coisas altas e sutis de Deus, de nada sentirem, ou quase nada, da suavidade do espírito. E que fazem eles senão suspirar pelo beijo? Suspiram, sem dúvida, e anseiam pelo espírito de sabedoria e de inteligência: pela inteligência, para alcançarem; pela sabedoria, para saborearem o que a inteligência alcançou. Creio que foi com esse mesmo afeto que o santo Profeta orou, ao dizer: Encha-se a minha alma como de gordura e de substância, e a minha boca te louvará com lábios exultantes (Sl 62,6). Era mesmo o beijo que pedia — aquele beijo a cujo toque, banhados os lábios com a riqueza de uma graça especial, viesse depois o que ele mesmo pede noutro lugar: Encha-se a minha boca de louvor, para que eu cante a tua glória e todo o dia a tua grandeza (Sl 70,8). E, uma vez que provou, logo transbordou: Quão grande é a abundância da tua doçura, Senhor, que reservaste para os que te temem (Sl 30,20). Este beijo já nos deteve bastante, e ainda assim, para dizer a verdade, não me fio de o ter exprimido como merece. Mas passemos adiante; porque isso se dá a conhecer melhor impresso do que expresso.`
    },
    {
      n: 4,
      texto: `Segue-se: Porque os teus peitos são melhores que o vinho, e cheiram aos melhores perfumes (Ct 1,1-2). De quem sejam estas palavras, o autor não diz, deixando-nos comentar livremente a que pessoa convêm melhor. Quanto a mim, não me falta com que as atribuir, com propriedade, ou à esposa, ou ao esposo, ou até aos companheiros do esposo. E mostrarei primeiro como convêm à esposa. Enquanto ela e eles conversavam, aproximou-se aquele de quem se falava. Ele se aproxima de bom grado dos que falam dele: é seu costume. Assim se mostrou companheiro agradável e bom de conversa aos que iam para Emaús e discorriam entre si (Lc 24,15). É o que promete no Evangelho: Onde dois ou três estiverem reunidos em meu nome, aí estou eu no meio deles (Mt 18,20); e pelo profeta: Antes que clamem, diz, eu os ouvirei; e, enquanto ainda estiverem falando, direi: Aqui estou (Is 65,24). Assim, pois, agora esteve presente sem ser chamado e, comprazendo-se com aquelas palavras, antecipou-se às preces. Creio que às vezes nem espera as palavras, e basta o pensamento para chamá-lo. Enfim, diz aquele homem que foi achado segundo o coração de Deus: O Senhor ouviu o desejo dos pobres; o teu ouvido escutou a preparação do seu coração (Sl 9,17). Cuidai também vós de vós mesmos em todo lugar, sabendo que Deus conhece tudo o que é vosso, ele que sonda os corações e os rins (Sl 7,10), que formou um a um os vossos corações e entende todas as vossas obras (Sl 32,15). A esposa, pois, percebendo que o esposo estava ali, deteve-se — envergonhada do atrevimento em que se via apanhada, porque julgara mais discreto tratar do assunto por intermediários — e logo, voltando-se para ele, tenta desculpar como pode a sua temeridade: Porque os teus peitos, diz, são melhores que o vinho, e cheiram aos melhores perfumes. Como se dissesse: Se pareço ter pretensões altas, foste tu que o fizeste, ó esposo, que na doçura dos teus peitos me amamentaste com tanta bondade, a ponto de, expulso todo o medo pelo teu amor — e não pela minha ousadia —, eu me atreva talvez a mais do que convém. Atrevo-me, decerto, lembrada da tua ternura e esquecida da tua majestade. Isto seja dito quanto ao encadeamento das palavras.`
    },
    {
      n: 5,
      texto: `Vejamos agora que elogio é este dos peitos do esposo. Os dois peitos do esposo são duas provas da mansidão que lhe é natural: espera com paciência quem peca e recebe com clemência quem se arrepende. É dupla, digo, a doçura que transborda do peito do Senhor Jesus: a longanimidade em esperar e a prontidão em perdoar. E ouve que isto não é invenção minha. Lês, com efeito, a respeito da longanimidade: Desprezas as riquezas da sua bondade, da sua paciência e da sua longanimidade? E ainda: Ignoras que a bondade de Deus te conduz ao arrependimento? (Rm 2,4) Pois é para isso que por muito tempo suspende sobre quem o despreza a sentença do castigo: para poder um dia conceder a quem se arrepende a graça do perdão. É que não quer a morte do pecador, mas que se converta e viva. Ponhamos exemplos também do outro peito, a que chamamos prontidão em perdoar. Lês igualmente a seu respeito: Em qualquer hora em que o pecador gemer, o seu pecado lhe será perdoado (Ez 33,11-12); e lês: Deixe o ímpio o seu caminho, e o homem iníquo os seus pensamentos, e volte para o Senhor, que dele terá misericórdia; e para o nosso Deus, porque é generoso em perdoar (Is 55,7). Com beleza Davi encerrou as duas coisas em poucas palavras: Longânimo e muito misericordioso (Sl 102,8). É pela experiência desta dupla bondade que a esposa confessa ter crescido até a confiança de ousar pedir o beijo. Que há de admirar, diz ela, se assim me atrevo contigo, ó esposo, eu que experimentei dos teus peitos tão grande abundância de doçura? É a doçura dos teus peitos que me leva a ousar, e não a confiança nos meus méritos.`
    },
    {
      n: 6,
      texto: `E o que diz — os teus peitos são melhores que o vinho — quer dizer isto: a riqueza da graça que corre dos teus peitos é mais eficaz para o meu progresso espiritual do que a repreensão mordaz dos superiores. E não só melhores que o vinho, mas também cheirando aos melhores perfumes; porque não alimentas apenas os presentes com o leite da doçura interior, mas também espalhas sobre os ausentes o odor agradável da boa fama, tendo bom testemunho tanto dos que estão dentro como dos que estão fora (1Tm 3,7). Tens, digo, leite dentro e perfumes fora; pois não haveria a quem alimentar com o leite, se antes não os atraísses pelo perfume. Sobre estes perfumes, se encerram algo digno de consideração, veremos depois, quando chegarmos ao lugar em que se diz adiante: Correremos ao odor dos teus perfumes (Ct 1,3). Agora, conforme prometemos, vejamos se estas mesmas palavras, que atribuímos à esposa, convêm também ao esposo.`
    },
    {
      n: 7,
      texto: `Falando a esposa do esposo, de repente, como eu dizia, ele aparece, atende ao pedido, dá o beijo e cumpre nela aquela palavra que está escrita: Deste-lhe o desejo do seu coração, e não lhe negaste o que os seus lábios queriam (Sl 20,3). E prova-o pelos peitos dela, que se enchem. É tal a eficácia do beijo santo que, mal o recebe, a esposa concebe logo dele, e os peitos incham e, por assim dizer, engrossam de leite, como testemunho. Os que se empenham em orar muitas vezes já experimentaram o que digo. Muitas vezes chegamos ao altar com o coração morno e seco, e nos entregamos à oração; mas, se persistimos, de repente a graça se derrama, o peito se enche, uma inundação de ternura toma as entranhas — e, se houver quem aperte, não tardarão a verter em abundância o leite da doçura concebida. Diga, pois, o esposo: Tens, esposa, o que pediste; e o sinal disso é que os teus peitos se fizeram melhores que o vinho. Por isto hás de saber que recebeste o beijo: porque sentes que concebeste. Daí também te incharem os peitos, tornados, na abundância do leite, melhores que o vinho da ciência do mundo — que embriaga, sim, mas de curiosidade, não de caridade; que enche, mas não nutre; que incha, mas não edifica; que entope, mas não fortalece.`
    },
    {
      n: 8,
      texto: `Mas deixemos também os companheiros dizerem isto. Sem razão, dizem eles, te queixas do esposo: porque vale mais o que ele já deu do que aquilo que pedes. Pois o que pedes deleita a ti; mas os peitos, com que alimentas os pequeninos que dás à luz, são melhores — isto é, mais necessários — do que o vinho da contemplação. É uma coisa o que alegra o coração de um só homem, e outra o que edifica a muitos. Pois, ainda que Raquel seja mais formosa, Lia é mais fecunda. Não te prendas demais, portanto, aos beijos da contemplação: porque são melhores os peitos da pregação.`
    },
    {
      n: 9,
      texto: `Ocorre-me ainda outro sentido, que eu não tinha previsto, mas que não deixarei passar. Por que não havemos de dizer que estas palavras convêm ainda melhor àqueles de quem ela cuida com solicitude, como mãe ou ama cuida dos pequeninos? É que as almas ainda jovens e tenras não levam a bem que se entregue ao repouso aquela por cuja doutrina desejam ser instruídas mais plenamente, e por cujos exemplos desejam ser formadas. E não é a inquietação dessas mesmas que se contém mais adiante, quando, sob grave juramento, se lhes proíbe despertar a amada enquanto ela mesma não quiser? (Ct 2,7) Estas, pois, ao perceberem que a esposa anseia pelos beijos, que busca o retiro, que foge do público, que evita a multidão e prefere o próprio descanso ao cuidado delas, dizem: Não, não faças isso; porque há mais fruto nos peitos do que nos abraços. Pois por eles nos livras dos desejos carnais, que guerreiam contra a alma (1Pd 2,11); arrancas-nos do mundo e ganhas-nos para Deus. É isto, pois, que elas dizem: Porque os teus peitos são melhores que o vinho. O prazer da carne, dizem, que pouco antes nos tinha embriagadas como um vinho, é vencido por estas delícias espirituais que os teus peitos destilam para nós.`
    },
    {
      n: 10,
      texto: `E com acerto comparam ao vinho o afeto carnal. Pois, assim como a uva, uma vez espremida, já não tem o que derramar de novo, mas fica condenada a uma secura perpétua, assim também a carne, na prensa da morte, seca de todo o seu deleite e não torna a reverdecer para as paixões. Daí o profeta: Toda carne é feno, e toda a sua glória é como a flor do feno. Secou-se o feno, e caiu a flor (Is 40,6-7); e o Apóstolo: Quem semeia na carne, da carne colherá corrupção (Gl 6,8); e ainda: O alimento é para o ventre, e o ventre para o alimento; mas Deus destruirá tanto um como o outro (1Cor 6,13). Repara, porém, que talvez esta comparação não valha só para a carne, e sim também para o mundo. Pois também ele passa, e a sua concupiscência (1Jo 2,17); e, ainda que tudo quanto há no mundo tenha fim, o fim deles não será fim. Com os peitos não é assim: quando se esvaziam, tornam a tirar da fonte do peito materno o que dar a beber a quem mama. Com razão, pois, se dizem melhores que o amor da carne e do mundo os peitos da esposa, que nunca secam, por mais numerosos que sejam os que mamam, mas sempre transbordam das entranhas da caridade, para correrem de novo. Pois do seu ventre correm rios, e faz-se nela uma fonte de água viva que jorra para a vida eterna (Jo 7,38; 4,14). E o louvor dos peitos se completa com a fragrância dos perfumes: porque não alimentam só com o sabor das palavras, mas também exalam o bom nome das obras. Quais sejam esses peitos, de que leite estão cheios e de que perfumes estão ungidos, mostraremos, com a ajuda de Cristo, no começo de outro sermão: ele que, com o Pai e o Espírito Santo, vive e reina Deus por todos os séculos dos séculos. Amém.`
    }
  ]
});
