SERMOES.sermao({
  id: 'bernardo-cantico-40',
  colecao: 'bernardo-cantico',
  ordem: 40,
  numero: 'XL',
  titulo: 'A intenção é a face da alma; qual é a sua beleza ou a sua fealdade; e qual a sua solidão e o seu pudor',
  fonte: 'Quod intentio sit facies animae',
  argumento: `Repreendida, a esposa corou, e o esposo lhe diz: as tuas faces são belas como as da rola. Bernardo afasta logo a leitura carnal: a face da alma é a intenção, e o rubor é o pudor. Se o texto diz "faces", no plural, é porque na intenção há duas coisas — o que se pretende e por que se pretende —, e cada uma pode ser bela ou feia. Daí uma pequena galeria de almas: a mundana, feia dos dois lados; a hipócrita, que olha para Deus mas não por Deus; a pusilânime, que busca a Deus pelas necessidades da vida; a de Marta, que se ocupa de outras coisas, mas por Deus, e só se suja de uma poeira leve; e a esposa, que busca só a Deus, e só por ele.

A rola, ave pudica que vive com um só companheiro, leva ao elogio da solidão: não tanto a do corpo, embora Cristo tenha orado sozinho, mas a do espírito. Está só quem não julga os outros; e, se não puder desculpar a obra, desculpe a intenção. Corrigir fica para o "amigo do esposo", isto é, para quem tem cargo de almas.

Tradução feita do texto latino de Migne (PL 183, 981-984).`,
  pontos: [
    {
      n: 1,
      texto: `As tuas faces são belas como as da rola (Ct 1,9). Delicado é o pudor da esposa; e, à repreensão do esposo, creio que o seu rosto se cobriu de rubor, e, parecendo por isso mais bela, ouve logo: As tuas faces são belas como as da rola. Mas cuida de não pensar carnalmente na podridão colorida da carne, nem no fluxo de humor amarelo ou sanguíneo que se espalha por igual à superfície da pele transparente, e de cuja mistura moderada se tempera um rubor um tanto pálido, que embeleza o desenho das faces e produz a beleza corporal. Pois aquela substância incorpórea e invisível da alma nem se distingue em membros corporais, nem se pinta com cores visíveis. Tu, porém, alcança, se podes, a essência espiritual com um olhar espiritual; e, para ajustar a figura da comparação proposta, pensa que a face da alma é a intenção da mente, pela qual se avalia a retidão da obra, como pela face a beleza do corpo. E entende o pudor como a cor na face, porque é sobretudo esta virtude que dá formosura e aumenta a graça. As tuas faces, pois, são belas como as da rola. Poderia, de modo mais usual, mencionar o rosto e descrevê-lo belo, como se costuma dizer, de alguém cuja beleza se louva, que tem um rosto belo ou formoso; mas não sei o que quis dizer ao preferir falar das faces, no plural — a não ser que de modo nenhum creio que isto seja ocioso. Pois quem fala é o Espírito da sabedoria, a quem não é lícito atribuir nada, por pequeno que seja, de ocioso, ou dito de modo diferente do que convinha. Há, pois, sem dúvida, uma razão, seja ela qual for, para ter preferido dizer as faces, no plural, a dizer o rosto, no singular. E, se tu não tens coisa melhor, eu exponho o que me parece.`
    },
    {
      n: 2,
      texto: `Na intenção, que dissemos ser a face da alma, requerem-se necessariamente duas coisas: o objeto e o motivo; isto é, o que pretendes, e por quê. E por estas duas coisas se julga a beleza ou a fealdade da alma; de modo que, por exemplo, à alma que tiver ambas retas e pudicas se diga com razão e com verdade: As tuas faces são belas como as da rola. Mas da que carecer de uma delas não se poderá dizer que as suas faces são belas como as da rola, por causa da fealdade que nela haverá ainda em parte. E muito menos poderá isto convir àquela em que nenhuma das duas se acha louvável. Mas tudo isto ficará mais claro com exemplos. Se alguém, por exemplo, aplica o ânimo a buscar a verdade, e isto só por amor da verdade, não te parece que tem honestos tanto o objeto como o motivo, e que pode com razão reivindicar para si o que se diz: As tuas faces são belas como as da rola? Pois em nenhuma das suas faces aparece mancha que mereça censura. Mas, se se aplicar à verdade não pelo desejo da verdade, mas em vista da vanglória ou de qualquer outra vantagem temporal, então, ainda que pareça ter bela uma das faces, não hesitarás, creio, em julgá-lo feio ao menos em parte, pois a torpeza do motivo lhe manchou a outra face. E, se vires um homem que não se aplica a nenhuma ocupação honesta, mas está enredado nos atrativos da carne, entregue ao ventre e à luxúria, como aqueles cujo deus é o ventre, e cuja glória está na sua vergonha, que só pensam nas coisas da terra (Fl 3,19) — que dirás dele? Não o julgarás feíssimo de ambos os lados, pois na sua intenção se acham reprováveis tanto o objeto como o motivo?`
    },
    {
      n: 3,
      texto: `Visar, pois, não a Deus, mas ao mundo, é próprio da alma mundana, que não tem nenhuma das faces formosa. Visar como que a Deus, mas não por causa de Deus, é próprio da alma hipócrita; e, ainda que uma das suas faces pareça formosa, porque olha para Deus com alguma intenção, a própria simulação destrói nela toda beleza e lhe espalha antes a fealdade por inteiro. Se, porém, alguém voltou a intenção para Deus só, ou sobretudo, por causa das necessidades da vida presente, não dizemos que é fétido da borra da hipocrisia, mas que é um tanto sombrio pelo vício da pusilanimidade, e menos agradável. Ao contrário, visar a outra coisa que não Deus, mas por causa de Deus, não é o repouso de Maria, mas a lida de Marta. Longe de mim dizer que a alma assim tenha alguma coisa de feio! Mas também não afirmaria que chegou à perfeição da beleza, pois ainda está inquieta e se agita com muitas coisas (cf. Lc 10,41), e não pode deixar de se sujar ao menos com uma poeira leve das ações terrenas. Poeira que, no entanto, a intenção casta e a interrogação que uma boa consciência dirige a Deus (cf. 1Pd 3,21) limpam depressa e com facilidade, ao menos na hora do santo repouso. Buscar, pois, só a Deus, e só por causa dele, é ter belíssimas as duas faces da intenção, que é dupla; e isto é próprio e especial da esposa, a quem com razão convém ouvir, por um privilégio singular: As tuas faces são belas como as da rola.`
    },
    {
      n: 4,
      texto: `Mas por que como as da rola? É uma avezinha pudica; e dizem que não vive com muitos, mas se contenta com um só companheiro, de tal modo que, se o perder, não procura outro, mas vive sozinha daí em diante. Tu, pois, que ouves isto — para que não ouças em vão o que foi escrito por tua causa, e agora por tua causa é tratado e discutido —, tu, digo, se te comoves com estes incentivos do Espírito Santo e ardes por empenhar-te em fazer da tua alma esposa de Deus, procura ter belas ambas estas faces da tua intenção, para que, imitando a castíssima ave, te sentes solitário, segundo o profeta, porque te elevaste acima de ti (Lm 3,28). Sem dúvida está acima de ti ser desposado pelo Senhor dos anjos. Não está acima de ti unir-te a Deus e ser com ele um só espírito (cf. 1Cor 6,17)? Senta-te, pois, solitário, como a rola. Nada tenhas com as multidões, nada com o grande número dos outros; esquece até o teu povo e a casa de teu pai, e o rei desejará a tua beleza (Sl 44,11-12). Ó alma santa, sê só, para te guardares só para aquele que escolheste entre todos. Foge do público, foge até dos da tua casa; retira-te dos amigos e dos íntimos, e até daquele que te serve. Não sabes que tens um esposo pudico, que de modo nenhum te quer conceder a sua presença estando outros presentes? Retira-te, pois — mas com a mente, não com o corpo; com a intenção, com a devoção, com o espírito. Pois o Cristo Senhor é um espírito diante da tua face (Lm 4,20), e requer a solidão do espírito, não a do corpo — ainda que também com o corpo não te separes em vão, de vez em quando, quando o podes oportunamente, sobretudo no tempo da oração. Também nisto tens o mandamento do esposo e o seu exemplo: Tu, diz, quando orares, entra no teu quarto e, fechada a porta, ora (Mt 6,6). E o que disse, fez. Passava a noite sozinho em oração, não só escondendo-se das multidões, mas não admitindo nenhum dos discípulos, nenhum dos seus íntimos (Lc 6,12-13). Enfim, tinha levado consigo os seus três íntimos quando caminhava por vontade própria para a morte; e, querendo orar, afastou-se também deles (Mt 26,37-39). Faze tu também assim, quando quiseres orar.`
    },
    {
      n: 5,
      texto: `No mais, só te é pedida a solidão da mente e do espírito. Estás só se não pensas no que todos pensam, se não te apegas às coisas presentes, se desprezas o que muitos admiram, se tens fastio do que todos desejam, se evitas as brigas, se não sentes os prejuízos, se não te lembras das injúrias. De outro modo, nem que estejas só com o corpo, estás só. Vês que podes estar só quando estás entre muitos, e entre muitos quando estás só? Estás só, por maior que seja a multidão de homens em que vivas; basta que te guardes de ser espião curioso ou juiz temerário da vida alheia. Ainda que surpreendas alguma coisa mal feita, nem assim julgues o próximo, mas antes desculpa-o. Desculpa a intenção, se não podes desculpar a obra; pensa que foi ignorância, pensa que foi descuido, pensa que foi acaso. E, se a certeza do fato não admite de modo nenhum fechar os olhos, persuade-te ainda assim, e dize contigo mesmo: A tentação foi violenta demais; que teria feito de mim, se tivesse recebido sobre mim o mesmo poder? E lembra-te de que agora estou falando à esposa, e não instruindo o amigo do esposo (cf. Jo 3,29), para o qual o caso é outro: ele deve vigiar com mais cuidado para que ninguém peque, investigar se alguém peca e corrigir quem tiver pecado. Desta necessidade a esposa está livre, vivendo só para si e para aquele que ama, seu esposo e ao mesmo tempo seu Senhor, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
