SERMOES.sermao({
  id: 'bernardo-cantico-51',
  colecao: 'bernardo-cantico',
  ordem: 51,
  numero: 'LI',
  titulo: 'De como a esposa pede que se lhe juntem os frutos das boas obras com as flores e os perfumes da fé; e da esperança e do temor',
  fonte: 'Qualiter sponsa petit sibi accumulari fructus bonorum operum',
  argumento: `Depois de uma visita mais longa e mais doce que de costume, o esposo se retira, e a esposa desfalece de amor: a ausência aumenta o desejo. Enquanto espera, pede flores e frutos. Na Igreja, são os principiantes e os perfeitos; na alma, a fé e as obras, porque não há fruto sem flor, nem flor que valha sem fruto. Quando a luz da contemplação se retira, a alma não cai no ócio: recolhe-se à vida ativa, porque Marta é irmã de Maria. Bernardo fala aqui da própria experiência: o progresso dos seus monges consola-o do repouso contemplativo que deixa para lhes pregar, como Jacó se consolou com a fecundidade de Lia.

De passagem, defende a pluralidade de sentidos da Escritura: já explicara estes versículos de outro modo no tratado Sobre o amor de Deus, e a caridade, a quem a Escritura serve, edifica mais quanto mais sentidos verdadeiros encontra nela. Depois, a esquerda e a direita do esposo: a esquerda é a ameaça do castigo, a direita a promessa do reino. Enquanto o medo servil pesa sobre a alma, a esquerda está sobre a cabeça; quando a esperança cresce e o amor lança fora o temor, está debaixo dela, e a alma pode dormir em paz.

Tradução feita do texto latino de Migne (PL 183, 1025-1029).`,
  pontos: [
    {
      n: 1,
      texto: `Sustentai-me com flores, cercai-me de maçãs, porque desfaleço de amor (Ct 2,5). O amor cresceu, porque os incentivos do amor foram mais numerosos que de costume. Vês, com efeito, quanta oportunidade houve desta vez, não só de ver, mas também de conversar. A própria visão parece ter sido concedida com um rosto mais sereno, e a palavra foi mais alegre, e a conversa mais longa e demorada. E ela não só se deleitou com a conversa, mas também se gloriou com o elogio. Além disso, refrescou-se à sombra daquele que desejara, alimentou-se do seu fruto, bebeu do seu cálice. Pois não se deve pensar que saiu sem sede da adega, na qual há pouco se gloriou de ter sido introduzida; ou antes, saiu com sede, porque quem me bebe, diz, terá ainda sede (Eclo 24,29). Depois de tudo isto, retirando-se o esposo, como costuma, ela declara que desfalece de amor, isto é, por causa do amor. Pois, quanto mais agradável tinha experimentado a presença, tanto mais penosa sentiu depois a ausência. A privação daquilo que amas é, com efeito, aumento do desejo; e o que desejas com mais ardor, com mais dor te falta. Por isso ela pede, entretanto, que a reconfortem com os perfumes das flores e dos frutos, até que volte de novo aquele cuja demora suporta com tanta pena. E esta é a sequência das palavras.`
    },
    {
      n: 2,
      texto: `Tentemos agora, guiados pelo Espírito da verdade, extrair o fruto espiritual que nelas há. Se entendermos que aqui fala a Igreja inteira dos santos, somos nós os designados pelas flores e pelos frutos, e também todos os que em todo o mundo se converteram do mundo. Nas flores se mostra a vida nova e ainda tenra dos principiantes; nos frutos, a força dos que progridem e a maturidade dos perfeitos. Cercada deles, a mãe peregrina e fecunda, para quem o viver é Cristo e o morrer é lucro (Fl 1,21), suporta sem dúvida com mais serenidade o incômodo da demora, porque, segundo a Escritura, lhe dão do fruto das suas mãos, como das primícias do Espírito, e as suas obras a louvam às portas (Pr 31,31). E, se queres ver, segundo o sentido moral, ambas as coisas — flores e frutos — numa só alma, entende por flor a fé, e por fruto a ação. E não te parecerá inconveniente, creio, se reparares como, à maneira da flor que precede necessariamente o fruto, também a boa obra deve ser precedida pela fé. De outro modo, sem fé é impossível agradar a Deus (Hb 11,6), como atesta Paulo; e ele mesmo ensina ainda: Tudo o que não vem da fé é pecado (Rm 14,23). Assim, nem há fruto sem flor, nem boa obra sem fé. Mas também a fé sem obras é morta (Tg 2,20), como também em vão aparece a flor, quando não se segue o fruto. Sustentai-me com flores, cercai-me de maçãs, porque desfaleço de amor. A mente acostumada ao repouso recebe, pois, consolação das boas obras enraizadas numa fé sem fingimento, todas as vezes que, como costuma acontecer, se lhe retira a luz da contemplação. Pois quem, enquanto permanece neste corpo, goza da luz da contemplação, não digo continuamente, mas sequer por algum tempo? Mas, todas as vezes que, como disse, cai da vida contemplativa, recolhe-se à ativa, de onde, como de perto, voltará com mais familiaridade ao mesmo ponto; porque estas duas são companheiras e moram juntas: Marta é irmã de Maria. Pois, ainda que caia da luz da contemplação, não se deixa de modo nenhum cair nas trevas do pecado ou na preguiça do ócio, mantendo-se na luz das boas obras. E, para que saibas que também as obras são luz: Brilhe a vossa luz, diz, diante dos homens (Mt 5,16); o que, sem dúvida, foi dito das obras, que os homens podiam ver.`
    },
    {
      n: 3,
      texto: `Sustentai-me com flores, cercai-me de maçãs, porque desfaleço de amor. Quando o amado está presente, o amor tem vigor; quando está ausente, desfalece. O que não é outra coisa senão um certo tédio do desejo impaciente, de que forçosamente se ressente a mente de quem ama com veemência, estando ausente aquele a quem ama; pois, todo voltado para a espera, tem por demora qualquer pressa, por maior que seja. E por isso ela pede que se lhe juntem os frutos das boas obras com os perfumes da fé, para neles repousar entretanto, enquanto o esposo tarda. Falo-vos da minha própria experiência. Se alguma vez soube que alguns de vós progrediram com os meus conselhos, então, confesso, não me pesou ter preferido o cuidado da palavra ao meu próprio repouso e sossego. Quando, por exemplo, depois do sermão, se acha algum irado mudado em manso, algum soberbo em humilde, algum pusilânime em forte; e se reconhece que o manso, o humilde, o forte cresceram cada um na sua graça e se tornaram melhores do que eram; e também os que talvez se tinham tornado tíbios e lânguidos no empenho espiritual, entorpecidos e sonolentos, parecem ter voltado a ferver e ter despertado com a palavra ardente do Senhor; e os que, abandonando a fonte da sabedoria, tinham cavado para si cisternas da vontade própria, que não podem conter a água (cf. Jr 2,13), e por isso murmuravam, oprimidos e de coração seco, contra tudo o que se lhes mandava, sem terem em si nenhuma umidade de devoção — estes, digo, quando se vê que, com o orvalho da palavra e a chuva generosa que Deus reservou para a sua herança (cf. Sl 67,10), refloresceram em obras de obediência, feitos em tudo dispostos e devotos, não há, digo-vos, por onde me entre na mente a tristeza, como por ter interrompido o empenho da agradável contemplação, quando estou rodeado de tais flores e frutos de piedade. Deixo-me arrancar com paciência dos abraços da estéril Raquel, para que de Lia me venham em abundância os frutos dos vossos progressos. De modo nenhum me pesará o repouso interrompido pelo cuidado da palavra, quando vir germinar em vós a minha semente e crescerem por ela os frutos da vossa justiça. Pois a caridade, que não busca os seus próprios interesses (1Cor 13,5), já há muito me persuadiu facilmente a não antepor nada do que desejo ao vosso proveito. Orar, ler, escrever, meditar e os outros ganhos do empenho espiritual, eu os considerei perda por vossa causa (cf. Fl 3,7).`
    },
    {
      n: 4,
      texto: `Sustentai-me com flores, cercai-me de maçãs, porque desfaleço de amor. Isto disse, pois, a esposa às jovenzinhas, na ausência do esposo, exortando-as a progredir na fé e nas boas obras até que ele venha, sentindo que nisto estaria o agrado do esposo, a salvação das filhas e a sua própria consolação. Sei que expliquei este passo mais amplamente no livro Sobre o amor de Deus, e noutro sentido; se melhor ou pior, julgue o leitor a quem agradar ver as duas explicações. Um homem prudente não me há de condenar pela diversidade dos sentidos, contanto que a verdade nos proteja nos dois casos, e que a caridade, a quem as Escrituras devem servir, edifique tanto mais gente quanto mais sentidos verdadeiros tirar delas para a sua obra. Por que desagradaria nos sentidos das Escrituras o que experimentamos continuamente nos usos das coisas? Para quantos usos dos nossos corpos, por exemplo, serve só a água? Assim também, qualquer palavra divina não estará fora de propósito se gerar sentidos diversos, que se adaptem às diversas necessidades e usos das almas.`
    },
    {
      n: 5,
      texto: `Segue-se: A sua esquerda está sob a minha cabeça, e a sua direita me abraçará (Ct 2,6). Lembro-me de ter tratado também isto com mais abundância na obrinha mencionada; mas assinalemos a sequência das palavras. Está claro que o esposo está de novo presente — creio que para levantar com a sua presença a que desfalecia. Pois como não recobraria forças na sua presença aquela que a sua ausência tinha prostrado? Ele, pois, não suporta a aflição da amada: está presente; pois não pode tardar, chamado por tão grandes desejos. E, porque a tinha achado, enquanto esteve ausente, fiel nas obras e solícita nos ganhos — pois mandara que lhe juntassem flores e frutos —, voltou desta vez com uma recompensa de graça ainda mais generosa. Enfim, com um dos braços sustenta a cabeça da que está deitada, e prepara o outro para a abraçar e a aquecer no seu seio. Feliz a alma que se reclina sobre o peito de Cristo e repousa entre os braços do Verbo! A sua esquerda está sob a minha cabeça, e a sua direita me abraçará. Não diz: me abraça, mas: me abraçará, para que saibas que ela foi tão pouco ingrata à primeira graça, que antecipou a segunda com a ação de graças.`
    },
    {
      n: 6,
      texto: `Aprende a não ser lento nem preguiçoso em agradecer; aprende a dar graças por cada dom. Considera com cuidado, diz, o que te é servido (Pr 23,1), para que nenhum dos dons de Deus fique privado da devida ação de graças: nem os grandes, nem os médios, nem os pequenos. Enfim, manda-se-nos recolher os pedaços, para que não se percam (Jo 6,12); isto é, não esquecer nem os menores benefícios. Não se perde acaso o que se dá a um ingrato? A ingratidão é inimiga da alma, esvaziamento dos méritos, dispersão das virtudes, perda dos benefícios. A ingratidão é um vento que queima e seca para si a fonte da piedade, o orvalho da misericórdia, os rios da graça. Por isso, enfim, a esposa, logo que sentiu a graça da esquerda, deu graças, sem esperar a plenitude que está na direita. Pois, depois de lembrar que a esquerda já estava sob a sua cabeça, não continuou dizendo que a direita igualmente a abraçava, mas: me abraçará.`
    },
    {
      n: 7,
      texto: `Mas que pensamos que sejam a esquerda e a direita do Verbo esposo? Acaso a palavra do homem tem em si partes corporais deste gênero, divididas, e traços distintos, que distingam esquerda e direita? Quanto mais a Palavra que é de Deus e é Deus não admite variedade nenhuma, mas é aquele que é (Ex 3,14), tão simples na sua natureza que não tem partes, tão uno que não tem número. Pois é a sabedoria de Deus, da qual está escrito: E a sua sabedoria não tem número (Sl 146,5). E, se o que é invariável é necessariamente incompreensível, e por isso também inefável, onde, pergunto, acharás palavras com que designar dignamente aquela majestade, ou falar dela com propriedade, ou defini-la adequadamente? Falemos, contudo, de algum modo, o que de algum modo sentimos dela pela revelação do Espírito Santo. Pela autoridade dos Padres e pelo costume das Escrituras, aprendemos que é lícito tomar comparações convenientes das coisas conhecidas; e não inventar palavras novas, mas tomar emprestadas as conhecidas, com as quais essas comparações se revistam de modo digno e adequado. De outro modo, tentarás ridiculamente ensinar o desconhecido pelo desconhecido.`
    },
    {
      n: 8,
      texto: `Como, pois, pela direita e pela esquerda se costumam designar as prosperidades e as adversidades, parece-me que aqui se pode entender pela esquerda do Verbo a ameaça do castigo, e pela direita a promessa do reino. Há momentos em que a nossa mente é oprimida servilmente pelo medo do castigo; e então de modo nenhum se deve dizer que a esquerda está sob a cabeça, mas sobre a cabeça; e a alma assim disposta não pode de modo nenhum dizer: A sua esquerda está sob a minha cabeça. Mas, se, progredindo, passar deste espírito de servidão (cf. Rm 8,15) a um afeto mais digno de serviço espontâneo, de modo a ser atraída pelos prêmios mais do que constrangida pelos castigos, e mais ainda se for movida pelo amor do próprio bem, então poderá dizer sem hesitar: A sua esquerda está sob a minha cabeça; pois venceu, com uma disposição de ânimo melhor e mais excelente, aquele medo servil que está na esquerda, e com desejos dignos se aproximou também da direita, na qual estão todas as promessas, como diz o Profeta ao Senhor: Delícias na tua direita até o fim (Sl 15,11). Por isso, concebida uma esperança certa, diz com confiança: E a sua direita me abraçará.`
    },
    {
      n: 9,
      texto: `Vê agora comigo se à alma assim disposta, e que alcançou este lugar de tanta suavidade, convém também tomar para si aquela palavra do salmo e dizer ela mesma: Em paz, no mesmo instante, dormirei e repousarei; sobretudo porque lhe assiste a razão que se segue: Porque tu, Senhor, me estabeleceste singularmente na esperança (Sl 4,9-10). O que quer dizer isto: enquanto alguém é oprimido pelo espírito de servidão e tem pouco de esperança e muito de temor, não tem paz nem repouso, pois a consciência flutua entre a esperança e o temor, e é sobretudo atormentada pelo temor que predomina; pois o temor supõe castigo (cf. 1Jo 4,18). E por isso não lhe cabe dizer: Em paz dormirei e repousarei, já que ainda não pode dizer que está estabelecido singularmente na esperança. Mas, se, pouco a pouco, com o crescimento da graça, o temor começar a diminuir e a esperança a crescer, quando por fim se chegar ao ponto em que a caridade, levantando-se com todas as forças em auxílio da esperança, lança fora o temor, não parecerá tal alma estabelecida singularmente na esperança, e por isso já a dormir e repousar em paz?`
    },
    {
      n: 10,
      texto: `Se dormirdes, diz, no meio das sortes, sereis como as penas da pomba, prateadas (Sl 67,14). E julgo que se disse isto porque há um lugar entre o temor e a segurança, como entre a esquerda e a direita: a esperança, que está no meio, e na qual a mente e a consciência repousam suavissimamente, tendo posto por baixo o leito macio da caridade. E talvez este lugar esteja designado mais adiante neste mesmo cântico, onde, na descrição da liteira de Salomão, tens entre outras coisas: O meio forrou-o de caridade, por causa das filhas de Jerusalém (Ct 3,10). Pois quem se sente estabelecido singularmente na esperança já não serve com temor, mas repousa na caridade. Enfim, repousa e dorme a esposa, a respeito de quem se diz: Eu vos conjuro, filhas de Jerusalém, pelas gazelas e pelos cervos dos campos, que não desperteis nem acordeis a amada, até que ela o queira (Ct 2,7). Grande e espantosa bondade: faz repousar no seu seio a alma que contempla, e além disso a guarda dos cuidados que a molestam e a protege das inquietações das ações e dos incômodos dos afazeres; e não permite de modo nenhum que a despertem, senão quando ela quiser. Mas isto não se deve empreender no aperto de um sermão que já vai terminando; antes, comece-se daqui outro, para que um passo tão deleitoso não seja defraudado do cuidado que merece. Não que, nem então, sejamos capazes de pensar alguma coisa por nós mesmos, como vinda de nós, sobretudo numa matéria tão digna, tão excelente e tão acima de tudo; mas a nossa capacidade vem de Deus (cf. 2Cor 3,5), do esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
