SERMOES.sermao({
  id: 'bernardo-cantico-07',
  colecao: 'bernardo-cantico',
  ordem: 7,
  numero: 'VII',
  titulo: 'Do amor ardente com que a alma ama a Deus; e da atenção que se deve guardar na oração e na salmodia',
  fonte: 'De amore ardenti quo anima diligit Deum',
  argumento: `Bernardo paga primeiro uma dívida — que mão é essa que se beija? São duas, diz ele: largueza e força. E passa enfim ao terceiro beijo. Quem o pede é a esposa, isto é, a alma que ama: não pede liberdade, nem salário, nem herança, nem sequer doutrina, mas o próprio esposo, e o pede sem rodeios, como quem está embriagado.

Como ela não fala diretamente com ele, mas com os que lhe são familiares, o sermão se desvia para os anjos que assistem aos que oram — e daí para uma repreensão aos monges que dormem nas vigílias, e para o modo de cantar os salmos.

Tradução feita do texto latino de Migne (PL 183, 806-810).`,
  pontos: [
    {
      n: 1,
      texto: `Sou eu mesmo que dou trabalho a mim, pois de bom grado vos provoco a perguntar. Como, a propósito do primeiro beijo, cuidei de mostrar os pés espirituais de Deus com definições e nomes próprios — e até com sobra —, agora continuais a perguntar também pela mão, que se propõe beijar em segundo lugar. Consinto, faço-vos a vontade; e mais: não vos mostro uma mão, mas duas, e distingo-as com nomes próprios. Chame-se uma largueza, e a outra força: porque ele dá com abundância e guarda com poder aquilo que deu. As duas há de beijar quem não for ingrato, reconhecendo e confessando que Deus é, ao mesmo tempo, o doador de todos os bens e o seu guardião. Creio que já se disse o bastante sobre os dois primeiros beijos; vejamos agora o terceiro.`
    },
    {
      n: 2,
      texto: `Beije-me com o beijo da sua boca (Ct 1,1). Quem o diz? A esposa. E quem é ela? A alma sedenta de Deus. Mas vou pôr diante de vós vários afetos, para que aquele que propriamente convém à esposa apareça com mais nitidez. Se é servo, teme diante do rosto do Senhor; se é assalariado, espera alguma coisa da mão do Senhor; se é discípulo, apura o ouvido para o mestre; se é filho, honra o pai; mas aquela que pede o beijo, ama. Entre os dons da natureza, este afeto do amor é o mais alto, sobretudo quando volta ao seu princípio, que é Deus. E não se acharam nomes igualmente doces para exprimir os doces afetos entre o Verbo e a alma como estes: esposo e esposa. Pois entre eles tudo é comum, nada é próprio, nada há que esteja dividido. Uma só é a herança dos dois, uma a casa, uma a mesa, um o leito, uma até a carne. Por causa dela, enfim, deixará ele o pai e a mãe e se unirá à sua mulher, e serão dois numa só carne (Gn 2,24). E a ela, do mesmo modo, manda-se que esqueça o seu povo e a casa de seu pai, para que ele se enamore da sua formosura (Sl 44,11-12). Se, portanto, amar convém de modo especial e principal aos esposos, não é sem razão que se chama esposa a alma que ama. E ama aquela que pede o beijo. Não pede a liberdade, não pede salário, não pede herança, não pede sequer ensino: pede o beijo — ao modo de uma esposa castíssima, que respira amor sagrado e não consegue de modo algum disfarçar a chama que a queima. Repara em como ela arranca logo no começo da fala. Vai pedir coisa grande a alguém grande e, no entanto, não usa, como é costume, nenhum verniz de lisonjas, nem dá voltas para chegar ao que deseja. Não faz introdução, não procura primeiro cair nas graças; mas, irrompendo de repente da abundância do coração, diz, sem rodeios e com bastante ousadia: Beije-me com o beijo da sua boca.`
    },
    {
      n: 3,
      texto: `Não te parece que é como se ela dissesse abertamente: Que tenho eu no céu? E, fora de ti, que quis eu sobre a terra? (Sl 72,25) Ama castamente, sem dúvida, quem busca aquele mesmo a quem ama, e não outra coisa qualquer dele. Ama santamente, porque não na concupiscência da carne, mas na pureza do espírito. Ama ardentemente aquela que de tal modo se embriaga do próprio amor que já não pensa na majestade. Pois então? Ele olha para a terra e faz com que ela trema (Sl 103,32) — e esta pede que ele a beije! Estará embriagada? Está, e por inteiro. Talvez, quando irrompeu nessas palavras, tivesse acabado de sair da adega, onde depois se gloria de ter sido introduzida (Ct 1,3; 2,4). Pois também Davi dizia a Deus, a respeito de alguns: Eles se embriagarão com a abundância da tua casa, e tu lhes darás a beber da torrente das tuas delícias (Sl 35,9). Ó, que força tem o amor! Que confiança, no espírito de liberdade! Que há de mais claro do que isto: que a caridade perfeita lança fora o temor? (1Jo 4,18)`
    },
    {
      n: 4,
      texto: `Por pudor, contudo, ela não dirige a palavra ao próprio esposo, mas a outros, como quem fala de alguém ausente: Beije-me, diz, com o beijo da sua boca. É que se pede coisa grande, e convém que o pudor acompanhe a súplica e que alguém recomende quem pede. Por isso é pelos familiares e íntimos que ela busca o acesso ao que é íntimo, e procura chegar àquele que deseja. E quem são eles? Cremos que os santos anjos assistem aos que oram e oferecem a Deus as preces e os votos dos homens — quando veem, porém, que se levantam mãos puras, sem ira e sem discussão (1Tm 2,8). Prova-o o anjo, falando assim a Tobias: Quando oravas com lágrimas e sepultavas os mortos, e deixavas o teu almoço e escondias os mortos em tua casa durante o dia, para sepultá-los de noite, eu apresentei a tua oração ao Senhor (Tb 12,12). Creio que outros testemunhos da Escritura já vos convenceram bastante disso. E de que os santos anjos costumam, por sua bondade, juntar-se também aos que cantam os salmos, que há de mais claro do que o que diz o Salmista: Vieram à frente os príncipes, unidos aos cantores, no meio das jovens que tocavam tamboris? (Sl 67,26) Daí também dizer ele: Na presença dos anjos cantarei para ti (Sl 137,1). Dói-me, por isso, que alguns de vós sejam vencidos por um sono pesado nas vigílias sagradas, e não tenham reverência aos cidadãos do céu, mas apareçam como mortos diante dos príncipes — logo eles, que, movidos pelo vosso fervor, têm prazer em tomar parte nas vossas solenidades. Receio que um dia, tomando horror à vossa preguiça, se retirem indignados, e cada um de vós comece, tarde demais, a dizer a Deus, gemendo: Afastaste de mim os meus conhecidos, e fizeram de mim objeto de horror; e ainda: Afastaste de mim o amigo e o próximo, e os meus conhecidos, por causa da minha miséria (Sl 87,9.19); e também: Os que estavam junto de mim puseram-se longe, e faziam violência os que buscavam a minha vida (Sl 37,12-13). Pois é certo que, se os bons espíritos se afastarem de nós, quem suportará o assalto dos malignos? Digo, portanto, aos que são assim: Maldito o que faz com negligência a obra de Deus (Jr 48,10). E diz também — não eu, mas o Senhor: Quem dera te encontrasse quente ou frio! Mas, porque te encontrei morno, começarei a vomitar-te da minha boca (Ap 3,15-16). Por isso, atentai para os vossos príncipes quando vos pondes a orar ou a cantar os salmos, e ficai de pé com reverência e disciplina; e gloriai-vos, porque os vossos anjos veem todos os dias a face do Pai (Mt 18,10). Enviados que são para servir a nós, que havemos de receber a herança da salvação (Hb 1,14), eles levam para o alto a nossa devoção e trazem de volta a graça. Tomemos, pois, o ofício daqueles cuja companhia nos coube em sorte, para que na boca das crianças e dos que ainda mamam se cumpra o louvor (Sl 8,3). Digamos-lhes: Cantai ao nosso Deus, cantai; e ouçamos que eles respondem, por sua vez: Cantai ao nosso Rei, cantai (Sl 46,7).`
    },
    {
      n: 5,
      texto: `Erguendo, pois, o louvor em comum com os cantores do céu, como concidadãos dos santos e membros da casa de Deus (Ef 2,19), cantai com sabedoria (Sl 46,8). O alimento tem sabor na boca; o salmo, no coração. Que a alma fiel e prudente não deixe de triturá-lo com os dentes da sua inteligência; não aconteça que, engolindo-o inteiro e sem mastigar, o paladar fique privado daquele sabor desejável, mais doce que o mel e o favo. Ofereçamos com os apóstolos, no banquete celeste e na mesa do Senhor, um favo de mel (Lc 24,42). O mel está na cera; a devoção, na letra. Do contrário a letra mata, se a engolires sem o tempero do espírito (2Cor 3,6). Mas, se com o Apóstolo cantares com o espírito e cantares também com a mente (1Cor 14,15), também tu reconhecerás como é verdadeira aquela palavra que Jesus disse: As palavras que eu vos falei são espírito e vida (Jo 6,64); e aquela outra que lemos, dita pela Sabedoria: O meu espírito é mais doce que o mel (Eclo 24,27).`
    },
    {
      n: 6,
      texto: `Assim a tua alma há de deleitar-se com manjares substanciosos, e assim o teu holocausto será rico. Assim aplacarás o rei, assim agradarás aos príncipes, assim, enfim, farás que toda a corte te seja favorável; e eles, sentindo nas alturas o odor de suavidade, dirão também de ti: Quem é esta que sobe pelo deserto como uma coluna de fumaça, exalando mirra e incenso e todos os pós do perfumista? (Ct 3,6) Os príncipes de Judá, diz ele, seus chefes; os príncipes de Zabulon, os príncipes de Neftali (Sl 67,28) — isto é, os príncipes dos que louvam, dos que se contêm, dos que contemplam. Pois os nossos príncipes sabem que ao seu Rei é aceita a confissão dos que cantam, a fortaleza dos que se contêm e a pureza dos que contemplam; e empenham-se em exigir de nós essas primícias do espírito, que não são outra coisa senão os primeiros e puríssimos frutos da sabedoria. Como não ignorais, Judá quer dizer «o que louva» ou «o que confessa»; Zabulon, «morada da fortaleza»; Neftali, «cervo à solta». E este, com os saltos da sua agilidade, bem exprime os arroubos de quem contempla; e, assim como o cervo costuma penetrar no escuro dos bosques, também o contemplativo penetra no que há de obscuro nos sentidos da Escritura. E sabemos quem foi que disse: O sacrifício de louvor me honrará (Sl 49,23).`
    },
    {
      n: 7,
      texto: `Mas, se não fica bem o louvor na boca do pecador (Eclo 15,9), não vos é sumamente necessária a virtude da continência, para que o pecado não reine no vosso corpo mortal (Rm 6,12)? Ora, não tem mérito diante de Deus a continência que busca a glória dos homens. Por isso é necessária sobretudo a pureza de intenção, pela qual a vossa mente deseje agradar só a Deus e seja capaz de unir-se só a ele. Pois unir-se a Deus não é outra coisa senão ver a Deus — e isso, por felicidade singular, só se concede aos puros de coração. Coração puro tinha Davi, que dizia a Deus: A minha alma se apegou a ti (Sl 62,9); e ainda: Para mim, o bem é estar unido a Deus (Sl 72,28). Vendo, unia-se; e unindo-se, via. À alma exercitada nestas coisas os mensageiros celestes se mostram familiares e assíduos, sobretudo se a perceberem muitas vezes em oração. Quem me dará, ó bondosos príncipes, que por vosso meio os meus pedidos se tornem conhecidos junto de Deus? Não digo «a Deus» — a quem já se confessa até o pensamento do homem —, mas «junto de Deus»: isto é, àqueles que estão com Deus, tanto às bem-aventuradas Virtudes como aos espíritos já livres da carne. Quem me levantará da terra, a mim que sou indigente, e erguerá do esterco a mim que sou pobre, para que eu me sente com os príncipes e ocupe um trono de glória (1Sm 2,8)? Não duvido de que recolham com alegria no palácio aquele que por bondade visitam no monturo. Afinal, alegraram-se com a sua conversão (Lc 15,10); e não haverão de reconhecê-lo quando ele for recebido lá em cima?`
    },
    {
      n: 8,
      texto: `Penso, portanto, que é a estes que a esposa se dirige enquanto ora, e é a eles, como a familiares e companheiros do esposo, que abre o desejo do seu coração ao dizer: Beije-me com o beijo da sua boca. E repara na conversa familiar e amiga que a alma, suspirando ainda na carne, tem com as potestades celestes. Anseia por beijos, pede o que deseja; mas não diz o nome daquele a quem ama, porque não duvida de que eles o conheçam: é dele que costuma falar com eles muitas vezes. Por isso não diz «beije-me este ou aquele», mas apenas «beije-me» — como também Maria Madalena não dizia o nome de quem procurava, e só disse a quem julgava ser o jardineiro: Senhor, se foste tu que o levaste (Jo 20,15). Se o levaste — mas a quem? Ela não o declara, porque supõe que seja claro para todos quem é aquele que nem por um instante lhe sai do coração. Assim também esta, falando aos companheiros do seu esposo como a quem está a par de tudo e diante de quem se sabia à mostra, sem dizer o nome irrompe de repente nestas palavras sobre o amado: Beije-me com o beijo da sua boca. Sobre esse beijo não quero deter-vos mais hoje; no sermão de amanhã ouvireis o que, enquanto orardes, se dignar sugerir-me a unção que ensina a respeito de tudo (1Jo 2,27). Pois não são a carne e o sangue que revelam este segredo (Mt 16,17), mas o Espírito Santo, que perscruta as profundezas de Deus (1Cor 2,10) — o qual, procedendo do Pai e do Filho, com eles igualmente vive e reina pelos séculos dos séculos. Amém.`
    }
  ]
});
