SERMOES.sermao({
  id: 'bernardo-cantico-17',
  colecao: 'bernardo-cantico',
  ordem: 17,
  numero: 'XVII',
  titulo: 'De como se deve notar a vinda e a retirada do Espírito Santo; e da inveja do diabo contra o gênero humano',
  fonte: 'De accessu et recessu Spiritus sancti observando',
  argumento: `Um sermão sobre coisa prática: perceber quando o Espírito chega e quando se vai. Ignorá-lo é o mais perigoso, diz Bernardo — quem não nota a partida fica exposto ao engano, e quem não nota o regresso é ingrato à visita. Daí a regra sobre o que fazer no silêncio do Espírito: pode-se duvidar, mas nunca afirmar com certeza o que não se sabe.

Depois vem uma hipótese que ele apresenta como hipótese, com a cautela que acabou de recomendar: teria Lúcifer invejado o óleo derramado sobre os homens, resmungando já então «para que este desperdício»? Dessa conjetura sai a página sobre o martelo dos humildes, que forja sem saber coroas eternas. E o sermão acaba anunciando o fim das alegorias e a passagem ao sentido moral.

Tradução feita do texto latino de Migne (PL 183, 855-859).`,
  pontos: [
    {
      n: 1,
      texto: `Achamos que já avançamos bastante no santuário de Deus, ao examinar este mistério admirável? Ou ousaremos seguir o espírito ainda mais para dentro, para esquadrinhar o que porventura resta? Esse Espírito perscruta não só os corações e os rins dos homens, mas também as profundezas de Deus; e, seja para o que é nosso, seja para o que é alto, eu o sigo sem receio, para onde quer que vá. Contanto que ele guarde os nossos corações e as nossas inteligências, para que não aconteça julgarmos que está presente quando não está, e seguirmos o nosso próprio juízo em lugar do seu, e assim nos desviarmos. Pois ele vem e vai conforme quer, e ninguém sabe facilmente de onde vem nem para onde vai (Jo 3,8). E talvez se possa ignorar isso sem dano para a salvação; mas quando ele vem e quando se retira — isso é perigosíssimo ignorar. Pois, quando não se observam com a maior vigilância essas alternâncias com que o Espírito Santo dispõe de nós, acontece que não desejas o que está ausente nem glorificas o que está presente. Ele se retira justamente para ser buscado com mais avidez; mas como será buscado, se não se sabe que está ausente? E, quando por bondade volta para consolar, como há de ser recebido com a dignidade que a sua majestade pede, se nem se sente que chegou? A mente que não percebe a partida fica exposta ao engano; e a que não nota o regresso será ingrata à visita.`
    },
    {
      n: 2,
      texto: `Eliseu pediu certa vez alguma coisa ao mestre, ao perceber que a partida dele estava iminente; e não a obteve, como sabeis, senão com a condição de ver o momento em que ele lhe fosse tirado (2Rs 2,9-10). Aquilo lhes aconteceu em figura, mas foi escrito por causa de nós (1Cor 10,11). O exemplo do profeta ensina-nos e adverte-nos a estarmos vigilantes e atentos à obra da nossa salvação, que o Espírito realiza sem cessar no mais íntimo de nós, com a finura e a suavidade admiráveis da sua arte divina. Que nunca a unção mestra, que ensina sobre tudo, nos seja tirada sem que o saibamos, se não quisermos ficar privados de um dom em dobro. Que nunca, ao chegar, nos encontre despreparados, mas sempre de rosto atento e de regaço aberto para a bênção generosa do Senhor. Que espécie de homens procura ele? Semelhantes aos que esperam o seu senhor, quando voltar das bodas (Lc 12,36) — e ele nunca volta de mãos vazias daquelas delícias abundantes da mesa do alto. É preciso vigiar, pois, e vigiar a toda hora, porque não sabemos em que hora o Espírito há de vir, ou tornar a partir. O Espírito vai e volta; e quem está de pé enquanto ele o segura cai necessariamente quando ele o larga — mas não se despedaça, porque o Senhor lhe põe a mão por baixo outra vez (Sl 36,24). E não cessa de alternar essas vezes nos que são espirituais — ou antes, nos que ele quer justamente tornar espirituais —, visitando-os de madrugada e pondo-os à prova de repente (Jó 7,18). Enfim, sete vezes cai o justo e sete vezes se levanta (Pr 24,16) — contanto que caia de dia, para que veja que está caindo, saiba que caiu, deseje levantar-se, busque a mão de quem o ajuda e diga: Senhor, na tua vontade deste força à minha beleza; desviaste de mim o teu rosto, e fiquei perturbado (Sl 29,8).`
    },
    {
      n: 3,
      texto: `Uma coisa é duvidar da verdade, o que tens necessariamente de sofrer quando o Espírito não sopra; outra é ter gosto pela falsidade, do que facilmente te guardas, se não ignorares a tua própria ignorância, para poderes dizer também tu: Se em algo fui ignorante, a minha ignorância está comigo (Jó 19,4). É sentença do santo Jó: reconhecei-a. A ignorância é péssima mãe, e tem duas filhas igualmente péssimas: a falsidade e a dúvida. Aquela é mais miserável, esta mais digna de pena; aquela mais perniciosa, esta mais incômoda. Quando o Espírito fala, ambas cedem; e há não só verdade, mas verdade certa. Pois ele é o Espírito da verdade, a que se opõe a falsidade; e é o Espírito da sabedoria, que, sendo o esplendor da vida eterna e alcançando tudo pela sua pureza, não admite a escuridão da ambiguidade. Quando esse Espírito não fala, há que evitar a dúvida, ainda que não seja incômoda; e há que detestar a falsidade. Pois uma coisa é, na incerteza, inclinar-se para isto ou para aquilo como opinião; outra é afirmar temerariamente o que não se sabe. Ou, portanto, que o Espírito fale sempre — o que não está no nosso arbítrio —, ou, quando lhe aprouver calar, que indique isso mesmo e fale ao menos o seu silêncio; para que, julgando falsamente que ele vai à nossa frente, não sigamos em lugar dele, com falsa segurança, o nosso próprio erro. E, se nos deixar suspensos na dúvida, que não nos abandone à mentira. Há quem diga uma falsidade com dúvida, e não mente; e há quem afirme uma verdade que não sabe, e mente. O primeiro não diz que é o que não é: diz que crê no que crê, e diz a verdade, ainda que não seja verdade aquilo em que crê. O segundo, ao dizer-se certo daquilo de que não está certo, não diz a verdade, ainda que seja verdadeiro aquilo que afirma.`
    },
    {
      n: 4,
      texto: `Ditas estas coisas para cautela dos inexperientes, sigo agora o Espírito, que confio ir à minha frente — mas com a mesma cautela que acabo de recomendar, se puder. E tentarei fazer eu mesmo o que ensino, para que não se diga também a mim: Tu, que ensinas os outros, não ensinas a ti mesmo (Rm 2,21). Há que distinguir entre o que é manifesto e o que é duvidoso, não pondo aquilo em dúvida nem afirmando isto temerariamente. E isso mesmo há de esperar-se do magistério do Espírito, pois a nossa diligência não basta de modo algum para tanto. Qual dos homens sabe se aquele juízo de Deus entre os homens, que um sermão anterior manifestou — o quarto antes deste, se bem me lembro —, foi precedido lá no alto por outro juízo já feito?`
    },
    {
      n: 5,
      texto: `O que digo é isto: julgas tu que aquele Lúcifer, que nascia de manhã, mas se levantava depressa demais, antes de se converter em trevas teve inveja de que se derramasse o óleo sobre o gênero humano — a ponto de, indignado, resmungar já então consigo mesmo: Para que este desperdício? Não afirmo que seja o Espírito quem o diz, nem digo que ele o contradiga: não sei. Pode, contudo, ter acontecido — se não se julgar incrível — que ele, cheio de sabedoria e perfeito em beleza, pudesse prever que haveria homens, e que estes haviam de alcançar glória igual à sua. E, se o previu, viu-o sem dúvida no Verbo de Deus; e, na sua inveja, cobiçou-lhes o lugar e tratou de os ter por súditos, desdenhando tê-los por companheiros. São mais fracos, disse ele, e inferiores por natureza; não convém que sejam concidadãos nem iguais em glória. Não denuncia porventura essa trama ímpia aquela subida presunçosa e aquele assentar-se que significa magistério: Subirei ao monte alto, disse, e me sentarei nos flancos do aquilão (Is 14,13)? Com isso alcançaria enfim a semelhança com o Altíssimo: se este, sentado sobre os querubins, governa toda a criatura angélica, assim também ele se sentaria no alto e governaria o gênero humano. De modo nenhum! Meditou a iniquidade no seu leito (Sl 35,5); que a iniquidade minta a si mesma (Sl 26,12). Nós não reconhecemos outro juiz senão o nosso autor. Não o diabo, mas o Senhor julgará a terra; ele é o nosso Deus pelos séculos dos séculos, e ele nos governará para sempre (Sl 47,15).`
    },
    {
      n: 6,
      texto: `No céu, pois, concebeu a dor, e no paraíso deu à luz a iniquidade (Sl 7,15) — filha da malícia, mãe da morte e das aflições; e a primeira mãe de todas elas foi a soberba. Pois, ainda que pela inveja do diabo a morte tenha entrado no mundo (Sb 2,24), o princípio de todo pecado é a soberba (Eclo 10,15). Mas de que lhe serviu? Tu continuas em nós, Senhor, e o teu nome foi invocado sobre nós (Jr 14,9); e o povo que adquiriste, a Igreja dos redimidos, diz: Óleo derramado é o teu nome. Quando eu sou lançado fora, tu o derramas atrás de mim e sobre mim; porque, mesmo irado, te lembrarás da misericórdia (Hab 3,2). Satanás recebeu, contudo, um reino sobre todos os filhos da soberba, feito príncipe destas trevas — de modo que a própria soberba sirva ao reino da humildade, já que, num único principado seu, temporal e desses, ele faz de muitos humildes reis altos e eternos. Juízo bem alegre: aquele soberbo, martelo dos humildes, forja sem saber coroas eternas para esses mesmos, atacando a todos e sucumbindo diante de todos. Pois em toda parte e sempre o Senhor julgará os povos, salvará os filhos dos pobres e humilhará o caluniador (Sl 71,4). Em toda parte e sempre defenderá os seus, repelirá os que fazem mal e tirará a vara dos pecadores de sobre a herança dos justos, para que os justos não estendam as mãos para a iniquidade (Sl 124,3); e virá enfim o dia em que quebrará de todo o arco, partirá as armas e queimará os escudos no fogo (Sl 45,10). Tu, desgraçado, pões o teu trono no aquilão, região de névoa e de frio; e eis que os indigentes são levantados do pó, e os pobres do esterco, para se sentarem com os príncipes e possuírem um trono de glória — e tu sofres ao ver cumprir-se aquilo: O pobre e o indigente louvarão o teu nome (Sl 73,21).`
    },
    {
      n: 7,
      texto: `Graças te damos, pai dos órfãos e juiz dos que não têm quem os defenda: aqueceu-se sobre nós o monte coalhado, o monte fértil; os céus destilaram diante da face do Deus do Sinai (Sl 67,6.16.9); derramou-se o óleo, espalhou-se o nome — aquele que o iníquo nos invejava, e por causa do qual nos invejava. Espalhou-se, digo, até os corações e as bocas dos pequeninos; e na boca das crianças e dos que mamam se cumpre o louvor (Sl 8,3). O pecador o verá e se irará (Sl 111,10); e, tão implacável quanto a sua ira, será inextinguível a chama já preparada para ele e para os seus anjos. O zelo do Senhor dos exércitos fará isso (Is 9,7). Como me amas, meu Deus, meu amor? Como me amas, lembrando-te de mim em toda parte, zelando em toda parte pela salvação do necessitado e do pobre — não só contra homens soberbos, mas até contra anjos sublimes? No céu e na terra julgas, Senhor, os que me fazem mal; combates os que me combatem (Sl 34,1); em toda parte acodes, em toda parte assistes, em toda parte estás à minha direita, Senhor, para que eu não vacile (Sl 15,8). Isto cantarei ao Senhor em minha vida, e ao meu Deus cantarei enquanto existir (Sl 145,2). São estes os seus feitos, estas as maravilhas que fez. Este é o primeiro e maior juízo, que me revelou a Virgem Maria, sabedora dos segredos: Depôs os poderosos do trono e exaltou os humildes; encheu de bens os famintos e despediu vazios os ricos (Lc 1,52-53). E o segundo é semelhante a este, e já o ouvistes: que os que não veem vejam, e os que veem fiquem cegos (Jo 9,39). Console-se o pobre com estes dois juízos e diga: Lembrei-me dos teus juízos de sempre, Senhor, e fui consolado (Sl 118,52).`
    },
    {
      n: 8,
      texto: `Mas voltemos a nós mesmos e examinemos os nossos caminhos; e, para podermos fazê-lo na verdade, invoquemos o Espírito da verdade e chamemo-lo de volta do alto para onde nos tinha levado, a fim de que vá à nossa frente também no caminho até nós mesmos — porque sem ele nada podemos. E não há que temer que ele desdenhe descer até nós: antes se indigna, isso sim, se tentamos sem ele a menor coisa. Pois ele não é dos que vão e não voltam: leva-nos e traz-nos de volta, de claridade em claridade (2Cor 3,18), como Espírito do Senhor; ora arrebatando-nos a si na sua luz, ora moderando-a e iluminando as nossas trevas, para que, acima de nós ou junto de nós, andemos sempre na luz e sempre como filhos da luz. Atravessamos as sombras das alegorias; chegamos ao exame dos sentidos morais. A fé foi edificada: instrua-se agora a vida. A inteligência foi exercitada: que se dite agora a ação. Pois bom entendimento têm todos os que o põem em prática (Sl 110,10) — contanto que tanto a ação como a inteligência sejam dirigidas para o louvor e a glória de Nosso Senhor Jesus Cristo, que é Deus sobre todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
