SERMOES.sermao({
  id: 'bernardo-cantico-31',
  colecao: 'bernardo-cantico',
  ordem: 31,
  numero: 'XXXI',
  titulo: 'Da excelência da visão de Deus; e de como, na vida presente, o gosto da presença divina varia nos homens santos segundo os diversos desejos da alma',
  fonte: 'De excellentia divinae visionis',
  argumento: `Um sermão sobre os modos de ver a Deus. Bernardo começa pela visão definitiva, a do céu, que é estável porque o que se vê é o puro «é», sem «foi» nem «será». Aqui na terra não se vê a Deus como é: vê-se o sol pelo que ele ilumina, e só um olho sereno o suporta.

Distingue então três modos: o comum, pelas coisas criadas, que são raios da Divindade; o dos Pais, por visões e vozes que vinham de fora; e a visita interior, quando o Verbo se derrama na alma — um Verbo que não soa, mas penetra; que não fala muito, mas age. E percorre as figuras com que o Cântico o mostra: esposo nos beijos, médico nos perfumes, companheiro de viagem, rei rico. Termina na sombra da fé, que não apaga a luz, mas a guarda — e em Cristo, que é ao mesmo tempo pastor, pasto e redenção.

Tradução feita do texto latino de Migne (PL 183, 940-945).`,
  pontos: [
    {
      n: 1,
      texto: `Mostra-me, tu a quem a minha alma ama, onde apascentas o rebanho, onde repousas ao meio-dia (Ct 1,6). O Verbo, que é o esposo, aparece muitas vezes às almas aplicadas, e não sob uma só figura. Por que assim? Sem dúvida porque ainda não se vê tal como é. Pois aquela visão é estável, porque é estável a forma que então se vê: ela é, e não admite, por «foi» ou por «será», mudança alguma naquilo que é. Tira o «foi» e o «será»: de onde viria então a mudança, ou a sombra de variação (Tg 1,17)? Mas tudo o que, vindo do «foi», não cessa de tender para o «será», passa, é certo, pelo «é» — mas não é de modo algum. Pois como é aquilo que nunca permanece no mesmo estado? Só é verdadeiramente, portanto, aquilo que nem é cortado pelo «foi» nem apagado pelo «será», mas a que resta só o «é», inexpugnável — e permanece o que é. O «foi» não lhe tira ser desde a eternidade, nem o «será» ser para sempre; e assim reclama para si o ser verdadeiro, isto é, incriado, sem fim, invariável. Quando, pois, aquele que é assim — ou antes, que não é assim ou assado — é visto tal como é, aquela visão, como disse, é estável, porque nenhuma variação a interrompe. E então àqueles que assim veem é dado a todos aquele único denário do Evangelho (Mt 20,9), na única figura que se oferece. Pois o que aparece, assim como é invariável em si, assim também está invariavelmente presente aos que olham; e aqueles a quem aparece não querem ver nada de mais desejável, nem podem ver nada de mais deleitoso. Quando, pois, se enfadará aquela avidez, ou se retirará aquela suavidade, ou enganará aquela verdade, ou acabará aquela eternidade? E, se se estendem para sempre, juntas, a possibilidade de ver e a vontade de ver, como não será plena a felicidade? Pois nada falta aos que sempre veem, nem nada sobra aos que sempre querem.`
    },
    {
      n: 2,
      texto: `Mas tal visão não é da vida presente: fica reservada para o fim, só para aqueles que podem dizer: Sabemos que, quando ele aparecer, seremos semelhantes a ele, porque o veremos tal como é (1Jo 3,2). Agora, sim, aparece a quem quer; mas como quer, não como é. Nem o sábio, nem o santo, nem o profeta pode ou pôde vê-lo tal como é neste corpo mortal; mas poderá, no corpo imortal, quem for tido por digno. Vê-se, pois, também aqui, mas como a ele parece bem, e não como é. Pois nem este grande luzeiro — falo deste sol que vês todos os dias — o viste jamais tal como é, mas só como ilumina o ar, por exemplo, o monte, a parede. E nem isso poderias, de modo algum, se a própria luz do teu corpo, pela serenidade e transparência que lhe são naturais, não fosse em alguma parte semelhante à luz do céu. Nenhum outro membro do corpo é capaz de luz, por causa da grande dessemelhança. E nem o próprio olho, quando se turva, se aproxima da luz, por ter perdido a semelhança. O olho turvo, pois, não vê de modo algum o sol sereno, por causa da dessemelhança; o olho sereno vê-o em certa medida, por causa de alguma semelhança. E, se tivesse uma pureza em tudo igual, veria o sol tal como é, sem nada que lhe ferisse a vista, por causa de uma semelhança completa. Assim também aquele Sol da justiça, que ilumina todo homem que vem a este mundo (Jo 1,9): quem foi iluminado pode vê-lo neste mundo como ilumina, porque já lhe é em algo semelhante; mas não pode de modo algum vê-lo como é, porque ainda não lhe é perfeitamente semelhante. Por isso diz: Aproximai-vos dele e sereis iluminados, e os vossos rostos não serão envergonhados (Sl 33,6). Assim é, sim — contanto que sejamos iluminados quanto basta para que, contemplando de rosto descoberto a glória de Deus, sejamos transformados na mesma imagem, de claridade em claridade, como pelo Espírito do Senhor (2Cor 3,18).`
    },
    {
      n: 3,
      texto: `É preciso, pois, aproximar-se dele, e não precipitar-se sobre ele, para que o investigador irreverente da majestade não seja esmagado pela glória (Pr 25,27). E não se aproxima dele por lugares, mas por claridades — e não claridades do corpo, mas do espírito, como pelo Espírito do Senhor. Pelo Espírito do Senhor, sim, e não pelo nosso — ainda que no nosso. Quem é mais claro está, pois, mais perto; e ser claríssimo é ter chegado. E, para os que já estão presentes, ver tal como ele é não é outra coisa senão ser tal como ele é, e não se envergonhar de dessemelhança alguma. Mas isso será então, como disse. Entretanto, esta variedade tão grande de formas e este número de espécies nas coisas criadas, que são senão raios da Divindade, que mostram que existe de fato aquele de quem vêm, mas sem definirem de todo o que ele é? Vês, pois, algo dele, mas não a ele. E, vendo as outras coisas que vêm daquele que não vês, sabes sem dúvida que existe aquele que é preciso procurar — para que a graça não falte a quem procura, e a ignorância não desculpe quem descuida. Mas este modo de ver é comum. Pois está ao alcance de todo aquele que usa a razão, segundo o Apóstolo, ver pela inteligência o que Deus tem de invisível, através das coisas que foram feitas (Rm 1,20).`
    },
    {
      n: 4,
      texto: `Outro, sem dúvida, é aquele modo pelo qual outrora foi concedida por bondade aos Pais aquela familiaridade frequente e tão desejada com a presença divina — ainda que também a eles não como ela é, mas como se dignou. E não de um só modo a todos, mas, como diz o Apóstolo, muitas vezes e de muitos modos (Hb 1,1) — embora ele seja um só em si mesmo, como ele próprio diz a Israel: O Senhor teu Deus é o único Deus (Dt 6,4). E esta manifestação não era comum, mas fazia-se por fora, mostrada por imagens que apareciam de fora, ou por vozes que soavam. Mas há uma visita divina, tanto mais diferente destas quanto mais interior: quando Deus se digna visitar por si mesmo a alma que o procura, e que se entregou a procurá-lo com todo o desejo e todo o amor. E eis o sinal de uma vinda assim, como nos ensina quem a experimentou: Um fogo irá diante dele e abrasará em redor os seus inimigos (Sl 96,3). Pois é preciso que o ardor de um santo desejo vá à frente dele a toda alma a que ele há de vir, para consumir toda a ferrugem dos vícios e assim preparar um lugar para o Senhor. E então a alma sabe que o Senhor está perto, quando se sente abrasada por aquele fogo e diz com o profeta: Do alto mandou um fogo aos meus ossos, e ensinou-me (Lm 1,13); e aquilo: Aqueceu-se o meu coração dentro de mim, e na minha meditação se acenderá um fogo (Sl 38,4).`
    },
    {
      n: 5,
      texto: `A uma alma assim, que suspira muitas vezes, ou antes, que ora sem cessar e se aflige de desejo, quando às vezes lhe vem ao encontro, compadecido, aquele que ela deseja e procura, creio que lhe convém dizer, pela própria experiência, com o santo Jeremias: Bom és, Senhor, para os que esperam em ti, para a alma que te procura (Lm 3,25). E o seu anjo, que é um dos companheiros do esposo, destinado justamente para isto — ministro e testemunha da saudação secreta e mútua —, esse anjo, digo, como salta de alegria, como se alegra e se deleita com ela, e, voltando-se para o Senhor, diz: Graças te dou, Senhor da majestade, porque lhe deste o desejo do seu coração e não lhe negaste o que os seus lábios queriam (Sl 20,3)! É ele que, como um criado atento, acompanha a alma por toda parte e não cessa de a solicitar e de a avisar com sugestões contínuas, dizendo: Deleita-te no Senhor, e ele te dará os pedidos do teu coração; e ainda: Espera o Senhor e guarda o seu caminho (Sl 36,4.34); e também: Se demorar, espera-o, porque certamente virá, e não tardará (Hab 2,3). E ao Senhor diz: Como o cervo deseja as fontes das águas, assim esta alma te deseja a ti, ó Deus (Sl 41,2). Desejou-te de noite, e o teu espírito, nas entranhas dela, vigiou por ti desde a madrugada (Is 26,9). E ainda: Todo o dia estende para ti as mãos (Sl 87,10); atende-a, porque clama atrás de ti (Mt 15,23); volta-te um pouco e deixa-te aplacar para com ela (Sl 89,13). Olha do céu, vê, e visita a desolada (Sl 79,15). Fiel padrinho de bodas, que conhece o amor mútuo sem o invejar, não busca a própria graça, mas a do Senhor: vai e vem entre o amado e a amada, levando os desejos e trazendo os dons. Desperta a ela, aplaca a ele. E às vezes, ainda que raramente, põe-nos um diante do outro, seja arrebatando-a a ela, seja trazendo-o a ele; pois é da casa e conhecido no palácio, não teme recusa, e vê todos os dias a face do Pai (Mt 18,10).`
    },
    {
      n: 6,
      texto: `Mas cuida de não julgar que entendemos nesta união do Verbo com a alma alguma coisa corporal ou imaginária. Dizemos o que diz o Apóstolo: quem se une a Deus é um só espírito com ele (1Cor 6,17). O arrebatamento da mente pura em Deus, ou a descida amorosa de Deus na alma, exprimimo-los com as palavras que temos, exprimindo coisas espirituais em termos espirituais (1Cor 2,13). Esta união faz-se, pois, no espírito, porque Deus é espírito, e se enamora da beleza daquela alma que vê andar segundo o espírito e não satisfazer os desejos da carne (Rm 13,14) — sobretudo se a vê a arder de amor por ele. Uma alma assim disposta e assim amada não se contentará, pois, nem com aquela manifestação do esposo que se fez a muitos pelas coisas criadas, nem com a que se fez a poucos por visões e sonhos, se não o receber também, por uma prerrogativa especial, descido do céu aos afetos mais íntimos e ao próprio âmago do coração, e se não tiver presente aquele que deseja — não em figura, mas derramado dentro; não aparecendo, mas tocando-a; e sem dúvida tanto mais agradável quanto está dentro, e não fora. Pois é um Verbo que não soa, mas penetra; que não fala muito, mas age; que não faz barulho aos ouvidos, mas acaricia os afetos. É um rosto que não tem forma, mas dá forma; que não fere os olhos do corpo, mas alegra o rosto do coração — agradável pelo dom do amor, não pela cor.`
    },
    {
      n: 7,
      texto: `Não diria, contudo, que ele aparece ainda tal como é, embora deste modo não mostre de todo outra coisa senão o que é. Pois nem mesmo assim estará presente continuamente, ainda que às almas mais devotas, nem de modo uniforme a todos. É preciso que o gosto da presença divina varie segundo os diversos desejos da alma, e que o sabor derramado da doçura do alto deleite de um modo e de outro o paladar de uma alma que deseja coisas diversas. Enfim, já reparaste, neste canto de amor, quantas vezes ele mudou de rosto, e em quantas formas da sua doçura se dignou transformar-se diante da amada: ora, como um esposo pudico, procura os abraços secretos da alma santa e se deleita com beijos; ora aparece com óleo e perfumes, mostrando-se médico — por causa das almas tenras e fracas, que ainda precisam de tais emplastros e remédios, e por isso são designadas pelo nome delicado de jovenzinhas. Se alguém resmungar, ouvirá que não são os sãos que precisam de médico, mas os doentes (Mt 9,12). Ora ainda, como um viajante qualquer que se junta à esposa e às jovenzinhas enquanto caminham, alivia toda a comitiva do cansaço da estrada com as suas conversas agradabilíssimas, de modo que, quando ele se vai, dizem: Não ardia o nosso coração dentro de nós, quando ele nos falava pelo caminho? (Lc 24,32) Companheiro de boa conversa, que, com a suavidade das suas palavras e dos seus modos, como com o bom cheiro de perfumes que exalam, faz todos correrem atrás de si; por isso dizem: Correremos ao odor dos teus perfumes (Ct 1,3). Outras vezes vem ao encontro como um pai de família muito rico, em cuja casa sobra o pão (Lc 15,17); ou antes, como um rei magnífico e poderoso, que parece levantar o ânimo abatido da esposa pobre e despertar-lhe o desejo, mostrando-lhe todas as coisas desejáveis da sua glória — as riquezas dos lagares e das despensas, a abundância dos hortos e dos campos — e introduzindo-a enfim nos próprios segredos do quarto. Pois o coração do seu marido confia nela (Pr 31,11), e de tudo o que tem não há nada que julgue dever esconder daquela que remiu pobre, provou fiel e abraça amável. E assim, deste ou daquele modo interior, não cessa de aparecer continuamente à vista dos que o procuram, para que se cumpra a palavra que disse: Eis que estou convosco até o fim dos tempos (Mt 28,20).`
    },
    {
      n: 8,
      texto: `E em tudo isto é suave e manso, e cheio de misericórdia (Sl 85,5). Nos beijos mostra-se afetuoso e terno; no óleo, nos aromas e nos perfumes, clemente e transbordante de entranhas de piedade e de compaixão; no caminho, alegre, afável, cheio de graça e de consolo; e, ao mostrar as suas riquezas e posses, generoso e largo, recompensando com liberalidade de rei. Assim, por todo o texto deste canto, acharás o Verbo esboçado em comparações deste tipo. Por isso creio que é isto que significa o profeta, quando diz: Cristo Senhor é espírito diante da nossa face; à sua sombra viveremos entre as nações (Lm 4,20) — isto é, que agora vemos num espelho e em enigma, e ainda não face a face. Mas isto só enquanto vivemos entre as nações; pois entre os anjos será de outro modo, quando, com uma felicidade em tudo igual à deles, também nós o veremos tal como é, isto é, na forma de Deus, e não na sombra. Pois, assim como dizemos que entre os antigos houve a sombra e a figura, e que para nós, pela graça de Cristo presente na carne, brilha por si mesma a própria verdade, assim também ninguém negará que nós, em relação ao século futuro, vivemos por ora numa certa sombra da verdade — a não ser quem não aceite o Apóstolo, que diz: Conhecemos em parte e profetizamos em parte (1Cor 13,9); e aquilo: Não julgo tê-lo alcançado (Fl 3,13). Pois como não haveria diferença entre quem anda pela fé e quem anda pela visão (2Cor 5,7)? O justo vive da fé (Hab 2,4); o bem-aventurado exulta na visão. E por isso o homem santo vive por ora à sombra de Cristo, e o anjo santo se gloria no esplendor do rosto da glória.`
    },
    {
      n: 9,
      texto: `E é boa a sombra da fé, que tempera a luz para o olho que ainda está turvo e prepara o olho para a luz; pois está escrito: purificando pela fé os seus corações (At 15,9). A fé, pois, não apaga a luz: guarda-a. O que quer que seja aquilo que o anjo vê, a sombra da fé o guarda para mim, depositado no seu seio fiel, para ser revelado a seu tempo. Não é bom ter ao menos envolto o que ainda não consegues receber descoberto? Também a Mãe do Senhor vivia à sombra da fé, ela a quem se disse: Feliz és tu, que creste. E teve também a sombra do corpo de Cristo, ela que ouviu: E o poder do Altíssimo te cobrirá com a sua sombra (Lc 1,35.45). E não é sombra vil a que se forma do poder do Altíssimo. Havia de fato poder na carne de Cristo, que cobriu de sombra a virgem, para que ela — coisa impossível a uma mulher mortal —, graças ao anteparo daquele invólucro do corpo que dá vida, suportasse a presença da majestade e aguentasse a luz inacessível. Poder, sem dúvida, pelo qual foi vencida toda força contrária: poder e sombra que afugentam os demônios e protegem os homens — ou ainda, poder que dá vigor e sombra que refresca.`
    },
    {
      n: 10,
      texto: `Vivemos, pois, à sombra de Cristo, nós que andamos pela fé e nos alimentamos da sua carne para viver. Pois a carne de Cristo é verdadeiramente comida (Jo 6,56). E vê se não é por isso que também aqui ele é descrito aparecendo como que em figura de pastor, onde a esposa parece falar-lhe como a um dos pastores, dizendo: Mostra-me onde apascentas, onde repousas ao meio-dia. Bom Pastor, que dá a vida pelas suas ovelhas (Jo 10,11): a vida por elas, a carne para elas; aquela como preço, esta como alimento. Coisa admirável! Ele mesmo é o pastor, ele mesmo é o pasto, ele mesmo é a redenção. Mas o sermão vai longe, porque o lugar é amplo e encerra coisas grandes, e não se explicará em poucas palavras; e por esta razão parece-me que é preciso antes interrompê-lo do que terminá-lo. Mas, como o assunto fica em suspenso, é preciso que a memória vigie, para que, onde se parou, dali se retome logo e se trate, conforme o Senhor der — Jesus Cristo, esposo da Igreja, que é Deus sobre todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
