SERMOES.sermao({
  id: 'bernardo-cantico-03',
  colecao: 'bernardo-cantico',
  ordem: 3,
  numero: 'III',
  titulo: 'Do beijo do pé, da mão e da boca do Senhor',
  fonte: 'De osculo pedis, manus et oris Domini',
  argumento: `Bernardo abre o sermão dizendo que hoje se lê no livro da experiência, e adverte que ninguém peça de saída o beijo da boca. Traça então o caminho em três degraus — os pés, a mão, a boca —, tomando por figura a pecadora do Evangelho. O sermão é interrompido pela chegada de hóspedes ao mosteiro, e Bernardo sai para recebê-los.

Tradução feita do texto latino de Migne (PL 183, 794-796).`,
  pontos: [
    {
      n: 1,
      texto: `Hoje lemos no livro da experiência. Voltai-vos para vós mesmos, e cada um atenda à sua consciência acerca do que se há de dizer. Quisera investigar se alguma vez foi dado a algum de vós dizer, de coração: Beije-me com o beijo da sua boca (Ct 1,1). Pois não é de qualquer homem dizer isto por afeto; mas, se alguém recebeu ao menos uma vez da boca de Cristo o beijo espiritual, a própria experiência o solicita e ele o repete de bom grado. Julgo que ninguém pode sequer saber o que isso seja, senão quem o recebe: é, com efeito, o maná escondido, e só quem o come ainda terá fome. É a fonte selada, de que não participa o estranho, e só quem dela bebe ainda terá sede. Ouve como o pede quem o experimentou: Restitui-me, diz, a alegria da tua salvação (Sl 50,14). Não se arrogue isto, portanto, alma semelhante à minha, carregada de pecados e ainda sujeita às paixões da sua carne, que não sentiu ainda a suavidade do espírito, de todo ignorante e inexperiente dos gozos interiores.`
    },
    {
      n: 2,
      texto: `Mostro-lhe, contudo, a essa alma, o lugar que na obra da salvação lhe convém. Não se levante temerariamente até a boca do serenissimo esposo, mas jaza comigo, temerosa, aos pés do severissimo Senhor, e com o publicano olhe tremendo para a terra e não para o céu (Lc 18,13), para que a face acostumada às trevas, confundida com as luzes do céu, não seja oprimida pela glória e, ferida pelos insólitos esplendores da majestade, não venha a envolver-se de novo na cegueira de mais densa treva. Não te pareça, ó alma, quem quer que sejas assim, não te pareça vil ou desprezível aquele lugar onde a santa pecadora depôs os pecados e se revestiu de santidade. Ali a etíope mudou a pele e, restituída a nova alvura, já então respondia com confiança e verdade aos que lhe lançavam em rosto a palavra: Sou negra, mas formosa, filhas de Jerusalém (Ct 1,4). Admiras-te de por qual arte o pôde, ou por quais méritos o alcançou? Ouve em poucas palavras. Chorou amargamente e, tirando das entranhas longos suspiros, sacudida por dentro de salutares soluços, vomitou os humores de fel. O médico celeste acorreu velocíssimo, porque velozmente corre a sua palavra (Sl 147,15). Porventura não é bebida a palavra de Deus? É-o certamente, e forte e veemente, e que perscruta os corações e os rins (Sl 7,10). Enfim: a palavra de Deus é viva e eficaz, e mais penetrante que toda espada de dois gumes, e atinge até a divisão da alma e do espírito, das juntas e das medulas, e é discernidora dos pensamentos (Hb 4,12). Pelo exemplo, pois, desta bem-aventurada penitente, prostra-te também tu, ó mísera, para deixares de ser mísera; prostra-te também tu por terra; abraça os pés, aplaca-os com beijos, rega-os com lágrimas, com as quais, todavia, não o laves a ele, mas a ti, para que te faças uma do rebanho das ovelhas tosquiadas que sobem do lavadouro (Ct 4,2). E de tal modo não ouses levantar o rosto coberto de pudor e de tristeza antes que ouças, também tu: Perdoados te são os teus pecados (Lc 7,37-48); antes que ouças: Levanta-te, levanta-te, cativa filha de Sião; levanta-te, sacode o pó (Is 52,1-2).`
    },
    {
      n: 3,
      texto: `Tomado, pois, aos pés o primeiro beijo, nem assim presumirás erguer-te logo ao beijo da boca; mas terás como degrau para ele um certo outro beijo intermédio, que em segundo lugar receberás na mão. E disto recebe também a razão. Se Jesus me disser: Perdoados te são os teus pecados — de que me aproveitará, se eu não deixar de pecar? Despi a minha túnica; se de novo a vestir, que ganhei? Se de novo sujar os meus pés, que havia lavado, de que valerá tê-los lavado? Sórdido de todo gênero de vícios, jazi longamente no lodo da borra; mas será sem dúvida pior ao que recai do que ao que jaz. Enfim, lembro-me de que aquele que me curou me disse: Eis que ficaste são; vai, e não peques mais, para que não te aconteça coisa pior (Jo 5,14). Ora, aquele que deu a vontade de fazer penitência é preciso que acrescente também a virtude de conter-se, para que eu não repita o que é preciso chorar e não faça as minhas últimas coisas piores que as primeiras. Pois ai de mim, ainda que penitente, se ele imediatamente retirar a mão, sem a qual nada posso fazer. Nada, digo, porque nem arrepender-me, nem conter-me. Ouço, por isso, o que aconselha o Sábio: Não repitas, diz, a palavra na tua oração (Eclo 7,15). E temo também o que o juiz ameaça à árvore que não dá bom fruto (Mt 3,10). Confesso, por tudo isto, que não me contento de todo com a primeira graça, pela qual já me arrependo dos males, se não receber também a segunda — a saber, para produzir dignos frutos de penitência e não tornar depois ao vômito.`
    },
    {
      n: 4,
      texto: `Isto, portanto, me resta pedir e receber, antes de presumir tocar coisas mais altas e mais sagradas. Não quero tornar-me sumo de repente: quero progredir pouco a pouco. Quanto desagrada a Deus a impudência do pecador, tanto lhe agrada o pudor do penitente. Mais depressa o aplacas se guardares a tua medida e não buscares o que está acima de ti. Longo e árduo é o salto do pé à boca, e nem sequer é acesso conveniente. Pois quê? Ainda salpicado de pó recente, hás de tocar a boca sagrada? Ontem tirado do lodo, hoje te apresentas ao rosto da glória? Passa pela mão. Que ela primeiro te limpe, ela te levante. De que modo te levantará? Dando-te de onde possas presumir. E que é isso? A formosura da continência e os dignos frutos de penitência, que são as obras de piedade. Estas te levantarão do esterco para a esperança de ousar coisas maiores. E, ao receberes o dom, beija a mão: isto é, não a ti, mas ao nome dele dá glória. Dá-a uma vez, e dá-a outra vez: pelos crimes perdoados e pelas virtudes conferidas. Ou então vê com que hás de guardar a fronte contra estes golpes: Que tens tu que não tenhas recebido? E, se o recebeste, por que te glorias como se não tivesses recebido? (1Cor 4,7).`
    },
    {
      n: 5,
      texto: `Enfim, tendo já nos dois beijos a dupla experiência da divina condescendência, talvez não te envergonhes de presumir coisas mais santas. Pois quanto cresces em graça, tanto te dilatas em confiança. Daí vem que ames mais ardentemente e batas mais confiadamente por aquilo que sentes faltar-te. Ora, a quem bate se abrirá. Creio que aquele beijo sumo, seja ele qual for, de suma condescendência e de admirável suavidade, não será negado a quem assim está afeiçoado. Este é o caminho, esta é a ordem. Primeiro prostramo-nos aos pés e choramos diante do Senhor que nos fez aquilo que nós mesmos fizemos. Em segundo lugar buscamos a mão daquele que levanta e fortalece os joelhos vacilantes. Por fim, quando com muitas preces e lágrimas obtemos estas coisas, então enfim ousamos, talvez, levantar a cabeça até a própria boca da glória — com temor e tremor o digo —, não somente para a contemplar, mas ainda para a beijar; porque Cristo Senhor é espírito diante da nossa face, e, aderindo a ele no ósculo santo, tornamo-nos, por condescendência sua, um só espírito com ele.`
    },
    {
      n: 6,
      texto: `A ti, Senhor Jesus, a ti com razão disse o meu coração: A minha face te buscou; a tua face, Senhor, buscarei. Pois de manhã me fizeste ouvir a tua misericórdia, quando a mim, que jazia primeiro no pó e beijava os teus veneráveis vestígios, perdoaste o que eu vivera mal. Depois, no correr do dia, alegraste a alma do teu servo, quando em seguida, no beijo da mão, me concedeste também a graça de viver bem. E agora, que resta, ó bom Senhor, senão que, na plenitude da luz, no fervor do espírito, admitindo-me dignamente também ao beijo da boca, me encha de alegria o teu rosto? Mostra-me, ó suavíssimo, ó serenissimo, mostra-me onde apascentas, onde repousas ao meio-dia. Irmãos, bom é estarmos aqui; mas eis que nos chama a malícia do dia. Estes que agora se anuncia terem chegado obrigam-me antes a romper que a terminar um discurso agradável. Eu sairei ao encontro dos hóspedes, para que nada falte aos deveres daquela caridade de que falamos, e não suceda que também de nós se ouça: Dizem, e não fazem (Mt 23,3). Vós, entretanto, orai, para que Deus faça aceitas as ofertas voluntárias da minha boca, para edificação vossa e para louvor e glória do seu nome.`
    }
  ]
});
