SERMOES.sermao({
  id: 'bernardo-cantico-39',
  colecao: 'bernardo-cantico',
  ordem: 39,
  numero: 'XXXIX',
  titulo: 'Dos carros do Faraó, isto é, do diabo, e dos chefes do seu exército, que são a maldade, a luxúria e a avareza',
  fonte: 'De curribus Pharaonis, id est diaboli',
  argumento: `Depois da repreensão, o esposo consola a esposa lembrando os dons que já lhe deu e prometendo outros. O primeiro é tê-la comparado à sua cavalaria contra os carros do Faraó: a passagem do mar Vermelho, figura do batismo, cumpre-se de novo em cada alma libertada do pecado, e com mais glória, porque agora o inimigo derrubado é o diabo. Uma alma santa pode ser comparada a um exército inteiro, pela ordem das suas virtudes e pela guarda dos anjos que a rodeiam.

O centro do sermão é uma alegoria minuciosa do exército do Faraó invisível. Três grandes chefes — a Maldade, a Luxúria e a Avareza — têm cada um o seu carro, com quatro rodas de vícios, cavalos e cocheiros próprios; Bernardo descreve peça por peça, e deixa aos monges o exercício de descobrir os outros chefes. No fim, a esposa é chamada amiga, e a lembrança de Moisés casado com a etíope abre caminho para o sermão seguinte.

Tradução feita do texto latino de Migne (PL 183, 977-981).`,
  pontos: [
    {
      n: 1,
      texto: `À minha cavalaria contra os carros do Faraó eu te comparei, minha amiga (Ct 1,8). Antes de tudo, reconhecemos de bom grado nestas palavras que a figura da Igreja precedeu nos patriarcas, e que os mistérios da nossa salvação foram mostrados de antemão. Na saída de Israel do Egito, e naquele duplo serviço do mar admirável, que deu passagem ao povo e tirou vingança dos inimigos, exprime-se claramente a graça do batismo, que salva os homens e afoga os crimes. Todos, diz, estiveram debaixo da nuvem, e todos foram batizados em Moisés, na nuvem e no mar (1Cor 10,1-2). Mas é preciso, como costumamos, assinalar a sequência das palavras e ligar o que se segue ao que vem antes; e só então tirar, se pudermos, alguma coisa suave que sirva para formar os costumes. Depois que a presunção da esposa foi contida com uma repreensão dura e severa, para que não ficasse triste demais, lembram-lhe alguns bens que já tinha recebido e prometem-lhe outros que ainda não tinha recebido; e além disso é de novo declarada bela e chamada amiga. Por eu te ter falado com dureza, minha amiga, diz, não suspeites em mim ódio nem rancor. Pois sinais evidentes do meu amor por ti são os próprios dons com que te honrei e adornei. E não tenho intenção de retirá-los, mas antes de acrescentar outros maiores. Ou assim: Não leves a mal, minha amiga, não receber agora o que pedes, tu que já recebeste de mim tantas coisas; e receberás coisas maiores do que estas, se andares nos meus preceitos e perseverares no meu amor. Isto quanto à sequência da letra.`
    },
    {
      n: 2,
      texto: `Vejamos agora quais são os dons que ele recorda ter dado. O primeiro é que a comparou à sua cavalaria contra os carros do Faraó, livrando-a do jugo do pecado, mortificadas todas as obras da carne; assim como aquele povo foi livrado da servidão do Egito, derrubados e afogados todos os carros do Faraó (Ex 14,28). Esta é, sem dúvida, a maior das misericórdias; e, se eu também quiser gloriar-me nela, não serei insensato, pois direi a verdade (2Cor 12,6). Confesso e confessarei: Se o Senhor não me tivesse ajudado, por pouco a minha alma habitaria no inferno (Sl 93,17). Não sou ingrato, não esqueci: cantarei eternamente as misericórdias do Senhor (Sl 88,2). Mas até aqui vai o que tenho em comum com a esposa. Quanto ao resto, ela, por uma bondade singular, depois de libertada é tomada como amiga, e reveste-se de beleza como esposa do Senhor — por enquanto, porém, só nas faces e no pescoço. Além disso, prometem-lhe colares por adorno: de ouro, pelo valor, e marchetados de prata, pela beleza. A quem não agradaria muito a própria ordem dos dons? Primeiro, é libertada por misericórdia; segundo, é amada por bondade; terceiro, é lavada e purificada com benignidade; por último, recebe a promessa de um ornamento excelente.`
    },
    {
      n: 3,
      texto: `Não duvido de que alguns de vós já reconhecem em si mesmos o que se diz e, instruídos pela própria experiência, voam à frente para o entender. Mas, lembrado daquele versículo: A explicação das tuas palavras ilumina e dá entendimento aos pequenos (Sl 118,130), julgo justo, por causa destes, explicar as mesmas coisas um pouco mais amplamente. Pois o Espírito da sabedoria é benigno (Sb 1,6), e agrada-lhe o mestre benigno e diligente, que deseja satisfazer os estudiosos de tal modo que não se recuse a acomodar-se aos mais lentos. Enfim: Os que me explicam terão a vida eterna, diz a própria Sabedoria (Eclo 24,31); e eu não quereria ser privado deste prêmio. E, mesmo nas coisas que parecem claras, às vezes se escondem outras que não será inútil explicar com mais cuidado também aos que parecem mais capazes e voam à frente com o engenho.`
    },
    {
      n: 4,
      texto: `Mas vê agora a comparação a respeito do Faraó e do seu exército, e da cavalaria do Senhor. A comparação não se faz entre os dois exércitos, mas a partir deles. Pois que comunhão há entre a luz e as trevas? Ou que parte tem o fiel com o infiel (2Cor 6,14-15)? Mas há, sem dúvida, comparação entre a alma santa e espiritual e a cavalaria do Senhor, e entre o Faraó e o diabo, e entre os exércitos de ambos. E não te admirarás de que uma única alma seja comparada a uma multidão de cavaleiros, se reparares quantas fileiras de virtudes há numa só alma, contanto que seja santa: quanta ordem nos afetos, quanta disciplina nos costumes, quanta armadura nas orações, quanto vigor nas ações, quanto terror no zelo, e enfim quantos combates contínuos com o inimigo, quantos triunfos! Enfim, mais adiante se lê: Terrível como um exército em ordem de batalha (Ct 6,3); e ainda: Que verás na Sulamita, senão coros de acampamentos (Ct 7,1)? Ou, se isto não te agrada, fica sabendo que uma alma assim nunca está sem a guarda dos anjos, que têm por ela o ciúme de Deus, cuidadosos de guardá-la para o seu esposo e de apresentá-la a Cristo como virgem casta (cf. 2Cor 11,2). E não digas no teu coração: Onde estão? Quem os viu? Viu-os o profeta Eliseu, e ainda fez, orando, que também Giezi os visse (2Rs 6,16-17). Tu não os vês, porque não és profeta, nem servo de profeta. Viu-os o patriarca Jacó, e disse: Este é o acampamento de Deus (Gn 32,2). Viu-os também o doutor dos gentios, que dizia: Não são todos eles espíritos servidores, enviados para servir aos que hão de herdar a salvação (Hb 1,14)?`
    },
    {
      n: 5,
      texto: `A esposa, pois, que avança sustentada pelo serviço dos anjos e rodeada pela tropa do alto, é semelhante à cavalaria do Senhor — àquela que outrora triunfou sobre os carros do Faraó com tão espantoso milagre do auxílio divino. Pois, se reparares com cuidado, tudo o que ali admiras como feito com magnificência acharás aqui igualmente admirável. Salvo que agora se triunfa com mais magnificência, porque o que ali aconteceu antes corporalmente se cumpre aqui espiritualmente. Não te parece, com efeito, muito mais forte e muito mais glorioso derrubar o diabo que o Faraó, e vencer as potestades do ar que derrubar os carros do Faraó? Ali, enfim, combateu-se contra a carne e o sangue; aqui, contra os principados e as potestades, contra os dominadores deste mundo de trevas, contra os espíritos do mal que estão nos ares (Ef 6,12). E percorre agora comigo cada membro da correspondência. Ali o povo é tirado do Egito, aqui o homem do mundo; ali é derrubado o Faraó, aqui o diabo; ali são derrubados os carros do Faraó, aqui são destruídos os desejos carnais e mundanos, que combatem contra a alma (1Pd 2,11); aqueles nas vagas, estes no pranto; aqueles no mar, estes no amargor. Creio que também agora os demônios gritam, quando lhes acontece dar com uma alma assim: Fujamos de Israel, porque o Senhor combate por ele (Ex 14,25). Queres também que te designe pelos seus nomes próprios alguns dos chefes do Faraó e te descreva os seus carros, para que, a exemplo deles, possas tu mesmo descobrir outros, se os houver? Grande chefe do rei espiritual e invisível do Egito é, sem dúvida, a Maldade; grande, a Luxúria; grande, a Avareza. E estes possuem os seus territórios sob o seu rei, conforme foram atribuídos a cada um. Pois a Maldade domina em toda a região dos malefícios e dos crimes; a Luxúria governa toda imundície e torpeza da carne; à Avareza coube o principado nas regiões da rapina e da fraude.`
    },
    {
      n: 6,
      texto: `Ouve agora também que carros o Faraó preparou para estes seus chefes, para perseguirem o povo de Deus. A Maldade tem o seu carro, que assenta em quatro rodas: a Crueldade, a Impaciência, a Audácia, a Impudência. Pois é muito veloz este carro para derramar sangue (cf. Rm 3,15): não o detém a inocência, nem o retarda a paciência, nem o freia o temor, nem o contém a vergonha. É puxado por dois cavalos muito ligeiros e prontíssimos para toda ruína: o Poder terreno e a Pompa mundana. Pois esta quadriga da maldade corre muito velozmente quando, de um lado, a eficácia do poder está à disposição para cumprir os seus intentos maldosos, e, do outro, o aplauso da pompa sorri aos crimes cometidos, para que se cumpra a palavra que está escrita: Porque o pecador é louvado nos desejos da sua alma, e o iníquo é abençoado (Sl 9,24); e ainda outra Escritura: Esta é a vossa hora e o poder das trevas (Lc 22,53). E estes dois cavalos são conduzidos por dois cocheiros, o Orgulho e a Inveja: o Orgulho guia a pompa, e a Inveja, o poder. Pois é arrebatado pelo amor veloz das pompas diabólicas aquele cujo coração primeiro se inchou dentro de si. O coração que se mantém firme em si, contido pelo temor, moderado pela gravidade, sólido pela humildade, são pela pureza, de modo nenhum será facilmente arrebatado pelo vento desta vaidade. Do mesmo modo, a montaria do poder terreno não é tocada pela inveja, e picada de um lado e de outro como por umas esporas de despeito — a suspeita de ter de ceder o lugar e o medo de sucumbir? Pois uma coisa é suspeitar de um sucessor, e outra temer um invasor. É com estes aguilhões que o poder terreno é continuamente tocado. E assim é o carro da maldade.`
    },
    {
      n: 7,
      texto: `O carro da Luxúria também roda sobre quatro rodas de vícios: a Voracidade do ventre, a Paixão do coito, a Moleza das roupas e o Relaxamento do ócio e do sono. É puxado igualmente por dois cavalos, a Prosperidade da vida e a Abundância dos bens; e os dois que os conduzem são o Torpor da preguiça e a Segurança traiçoeira: porque a abundância solta as rédeas à preguiça, e, segundo a Escritura, a prosperidade dos insensatos os perderá (Pr 1,32) — não por outro motivo senão porque os torna perigosamente seguros: Quando disserem: Paz e segurança, então lhes sobrevirá de repente a ruína (1Ts 5,3). Estes não têm esporas, nem chicotes, nem coisa semelhante; em lugar disso, usam um toldo para fazer sombra e um leque para fazer vento. O toldo é a Dissimulação, que faz sombra e protege do calor das preocupações. Pois é próprio da alma mole e delicada fingir que não vê até as preocupações necessárias e, para não sentir o calor dos cuidados, esconder-se no abrigo da dissimulação. O leque é a Prodigalidade, que traz o vento da adulação. Pois os luxuriosos são generosos, e compram com ouro o vento que sai da boca dos aduladores. E basta disto.`
    },
    {
      n: 8,
      texto: `A Avareza, por sua vez, também é levada sobre quatro rodas de vícios, que são a Pusilanimidade, a Desumanidade, o Desprezo de Deus e o Esquecimento da morte. Os animais que a puxam são a Mesquinhez e a Rapacidade; e um só cocheiro conduz ambos: o Ardor de possuir. Pois só a Avareza, como não suporta pagar a muitos, se contenta com um único servidor. E este, executor muito pronto e incansável da obra que lhe foi confiada, para tocar os animais que puxam usa chicotes muito cortantes: a Cobiça de adquirir e o Medo de perder.`
    },
    {
      n: 9,
      texto: `Há ainda outros chefes do rei do Egito, que também têm os seus carros na campanha do seu senhor: como a Soberba, que é um dos chefes maiores; como a Impiedade, inimiga da fé, que também ocupa um grande lugar na casa e no reino do Faraó; e há ainda muitos outros sátrapas e cavaleiros de ordem inferior, sem número, no exército do Faraó, cujos nomes e ofícios, e também as armas e o equipamento, deixo ao vosso estudo, para que vos exerciteis em procurá-los. Com a força destes chefes e dos seus carros, o Faraó invisível, correndo por toda parte, enfurece-se como tirano, com todas as forças que pode, contra toda a família do Senhor, e ainda nestes dias persegue Israel que sai do Egito. Mas Israel, sem ser levado em carros nem protegido por armas, fortalecido só pela mão do Senhor, canta seguro: Cantemos ao Senhor, porque se cobriu de glória: lançou ao mar cavalo e cavaleiro (Ex 15,1); e ainda: Uns confiam em carros, outros em cavalos; nós, porém, invocaremos o nome do Senhor nosso Deus (Sl 19,8). E baste isto sobre a comparação proposta da cavalaria do Senhor e dos carros do Faraó.`
    },
    {
      n: 10,
      texto: `Depois disto, é chamada amiga. Pois ele já era amigo antes da libertação — de outro modo, não teria libertado quem não amasse —; mas ela foi levada, pelo benefício da libertação, a ser amiga. Ouve enfim quem o confessa: Não fomos nós que o amamos, diz, mas ele nos amou primeiro (1Jo 4,10). Lembra-te agora de Moisés e da etíope (Nm 12,1), e reconhece já então prefigurado o casamento do Verbo com a alma pecadora; e distingue, se podes, o que te sabe mais doce, na consideração deste suavíssimo mistério: a bondade excessivamente benigna do Verbo, ou a glória inestimável da alma, ou a confiança inesperada do pecador. Mas Moisés não pôde mudar a pele da etíope (cf. Jr 13,23); Cristo pôde. Pois segue-se: As tuas faces são belas como as da rola (Ct 1,9). Mas isto fique reservado para outro sermão, para que, tomando sempre com avidez o que nos é servido à mesa do Esposo, o façamos transbordar em louvor e glória dele mesmo, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
