SERMOES.sermao({
  id: 'bernardo-cantico-10',
  colecao: 'bernardo-cantico',
  ordem: 10,
  numero: 'X',
  titulo: 'Dos três perfumes espirituais: o da contrição, o da devoção e o da piedade',
  fonte: 'De tribus unguentis spiritualibus',
  argumento: `Bernardo fecha o assunto dos peitos da esposa, que são a compaixão e a alegria com quem se alegra. Daí sai uma das páginas mais duras que escreveu: contra os que tomaram sobre si o governo das almas e fundem na fornalha da avareza o patrimônio do Crucificado.

Depois abre o assunto dos perfumes. O da contrição faz-se dos próprios pecados, triturados no almofariz da consciência; o da devoção, da memória dos benefícios de Deus — e este, adverte ele, não está ao alcance de uma alma pobre. O terceiro, o da piedade, fica para mais adiante.

Tradução feita do texto latino de Migne (PL 183, 819-824).`,
  pontos: [
    {
      n: 1,
      texto: `Não sou de entendimento profundo nem de engenho tão penetrante que possa inventar de mim mesmo alguma coisa nova; mas a boca de Paulo é uma fonte grande e inesgotável, aberta para nós. É dela que tiro também agora, ao mostrar os peitos da esposa, como costumo fazer tantas vezes. Alegrar-se com os que se alegram, chorar com os que choram (Rm 12,15), diz ele. Em poucas palavras se exprimem os afetos de uma mãe; porque os pequeninos não podem nem sofrer nem passar bem sem aquela que os gerou: num caso e no outro é preciso que ela se conforme aos filhos que trouxe nas entranhas. Assim, seguindo a sentença de Paulo, atribuirei esses dois afetos aos dois peitos da esposa: a um, a compaixão; ao outro, a alegria com quem se alegra. De outro modo é ainda menina, e não está em idade de casar, se ainda não lhe cresceram os peitos — isto é, se não se sente pronta a alegrar-se com os outros nem inclinada a sofrer com eles. Se uma assim for por acaso escolhida para o governo das almas ou para o ofício da pregação, não aproveita aos outros e faz a si mesma muito mal. E, se ela mesma se oferece para isso, que desfaçatez não é?`
    },
    {
      n: 2,
      texto: `Mas voltemos aos peitos da esposa e, conforme a diferença dos peitos, distingamos também duas espécies de leite. Pois a alegria compartilhada verte o leite da exortação, e a compaixão, o leite da consolação. E a mãe espiritual sente que ambas lhe são derramadas do céu em abundância sobre o peito amoroso todas as vezes que recebe o beijo. Logo a verás debruçada, de peitos cheios, sobre os pequeninos que há de amamentar, dando com mais abundância de um a consolação e do outro a exortação, conforme lhe parecer que convém a cada um. Por exemplo: se descobrir que algum daqueles que gerou no Evangelho foi abalado por alguma tentação forte e, perturbado e triste, ficou sem ânimo, já sem forças para suportar o ímpeto da tentação — como sofre com ele, como o acaricia! Como chora, como o consola! Quantas razões de ternura logo encontra para levantar o desolado! Se, ao contrário, o encontra pronto, alegre e em bom progresso, exulta, vem com avisos salutares, acende-o ainda mais, instrui-o no que pode para que persevere e o exorta a progredir sempre para melhor. A todos se ajusta, toma para si os sentimentos de todos, e mostra-se mãe tanto dos que desfalecem como dos que avançam.`
    },
    {
      n: 3,
      texto: `Quantos há hoje que se mostram de outra disposição! Falo dos que tomaram sobre si o governo das almas. Pois — e não se pode dizer isto sem um gemido de dó — os opróbrios de Cristo, os escarros, os açoites, os cravos, a lança, a cruz e a morte, tudo isso eles fundem na fornalha da avareza e gastam em ganho torpe, apressando-se por fechar nas suas bolsas o preço do mundo inteiro. Só nisto diferem de Judas Iscariotes: ele avaliou todo esse ganho em poucas moedas; estes, com sofreguidão mais voraz de lucro, exigem dinheiro sem conta. Por ele anseiam com desejo insaciável; por ele temem, para não o perder; e, quando o perdem, doem-se. No amor dele descansam — no pouco que lhes sobra do cuidado de guardá-lo ou de aumentá-lo. Das almas não se faz conta nem da ruína nem da salvação. Não são mães, decerto, os que, engordados, nutridos e alargados à custa do patrimônio do Crucificado, não se compadecem da ruína de José (Am 6,6). Quem é mãe não disfarça: tem peitos, e não vazios. Sabe alegrar-se com os que se alegram e chorar com os que choram, e não cessa de espremer do peito da alegria o leite da exortação, e do peito da compaixão o leite da consolação. E baste isto sobre os peitos da esposa e sobre o leite deles.`
    },
    {
      n: 4,
      texto: `Vou dizer agora de que perfumes cheiram esses mesmos peitos, se as vossas orações me ajudarem, para que aquilo que me foi dado sentir também me seja dado dizer dignamente, para proveito de quem ouve. Uns são os perfumes do esposo, outros os da esposa, assim como cada um tem os seus peitos. Já ficou dito acima em que lugar se há de tratar dos do esposo; agora voltemo-nos para os da esposa, e com mais atenção, por serem daqueles que a Escritura não louvou por pouco: chamou-os não simplesmente bons, mas ótimos. E vou apresentar diversas espécies de perfumes, para que entre muitas escolhamos as que melhor convêm aos peitos da esposa. Há o perfume da contrição, há o da devoção e há o da piedade. O primeiro é picante, e faz doer; o segundo é calmante, e alivia a dor; o terceiro é curativo, e expulsa a própria doença. Tratemos agora de cada um mais largamente.`
    },
    {
      n: 5,
      texto: `Há, pois, um perfume que a alma presa em muitos crimes prepara para si, se, ao começar a pensar nos seus caminhos, recolhe, ajunta e tritura no almofariz da consciência as muitas e variadas espécies dos seus pecados, e as cozinha todas juntas na panela do peito que ferve, num certo fogo de penitência e de dor, a ponto de poder dizer com o Profeta: Aqueceu-se o meu coração dentro de mim, e na minha meditação se acenderá um fogo (Sl 38,4). Eis um primeiro perfume, com que a alma pecadora deve temperar os começos da sua conversão e que deve aplicar às suas feridas recentes. Pois o primeiro sacrifício a Deus é um espírito atribulado. Enquanto, sendo pobre e necessitada, não tiver com que compor um perfume melhor e mais precioso, não deixe de preparar entretanto este, ainda que com ingredientes vis; porque um coração contrito e humilhado Deus não despreza (Sl 50,19). E tanto menos vil parecerá aos olhos divinos quanto mais vil ela se tiver tornado a si mesma na lembrança dos seus pecados.`
    },
    {
      n: 6,
      texto: `Contudo, se dissermos que este perfume invisível e espiritual foi figurado naquele perfume visível com que, no Evangelho, a Pecadora ungiu visivelmente os pés corporais de Deus, já não o poderemos ter por vil. Pois o que se lê dele? E a casa, diz o texto, encheu-se do odor do perfume (Jo 12,3). Escorria das mãos de uma pecadora e derramava-se sobre os membros mais baixos do corpo, isto é, os pés; e nem por isso foi tão desprezível ou tão vil que a força dos aromas e a suavidade do odor não enchessem a casa inteira. Ora, se considerarmos com que fragrância a Igreja é aspergida na conversão de um só pecador, e para quantos se torna odor de vida para a vida (2Cor 2,16) qualquer penitente que faça penitência em público e por inteiro, também deste perfume diremos, com a mesma certeza, que a casa se encheu do seu odor. O odor da penitência chega até as moradas altas dos bem-aventurados, tanto que, segundo o testemunho da própria Verdade, há grande alegria entre os anjos de Deus por um só pecador que faz penitência (Lc 15,10). Alegrai-vos, penitentes; animai-vos, vós que estais sem ânimo. A vós falo, que, recém-convertidos do mundo e afastados dos vossos maus caminhos, fostes logo tomados pela amargura e pela vergonha próprias de quem se arrepende, e a quem a dor excessiva de feridas ainda frescas atormenta e perturba. Que as vossas mãos destilem sem receio a amargura da mirra para esta unção saudável; porque um coração contrito e humilhado Deus não despreza. Não se há de desprezar nem ter por vil uma unção assim, cujo odor não só move os homens a corrigir-se, mas convida os anjos a exultar.`
    },
    {
      n: 7,
      texto: `Mas há um perfume tanto mais precioso do que este quanto é feito de melhores ingredientes. E, para não os buscarmos longe, reparemos que temos à mão, sem dificuldade, outros que colhemos com toda a facilidade dos nossos hortos, sempre que a necessidade pede. Pois quem não tem bastante do seu, quando quer, iniquidades e pecados à mão, se não os disfarça? Mas estes, como bem reconheceis, são os ingredientes do primeiro perfume, que já descrevemos. Já os aromas deste segundo a nossa terra não produz de modo algum: vamos buscá-los longe, nos confins do mundo. É que toda dádiva excelente e todo dom perfeito vem do alto, e desce do Pai das luzes (Tg 1,17). Pois este perfume se faz dos benefícios divinos concedidos ao gênero humano. Feliz quem cuida de os recolher com empenho e de os trazer de volta diante dos olhos da mente com a devida ação de graças. Depois de moídos e triturados no vaso do peito com o pilão de uma meditação frequente, e depois cozidos todos juntos no fogo de um santo desejo, e enfim amassados com o óleo da alegria, farão uma unção muito mais preciosa e mais excelente que a primeira. Basta para o provar o testemunho daquele que diz: O sacrifício de louvor me honrará (Sl 49,23). E não há dúvida de que a lembrança dos benefícios move ao louvor.`
    },
    {
      n: 8,
      texto: `Ora, visto que a Escritura só diz do outro que não é desprezado, fica claro que é mais louvado este, que até honra. Além disso, aquele se põe nos pés; este, na cabeça. Pois, se em Cristo a cabeça se refere à divindade, como diz Paulo — a cabeça de Cristo é Deus (1Cor 11,3) —, sem dúvida unge a cabeça quem dá graças, porque toca em Deus, não no homem. Não que não seja homem aquele que é Deus, pois Cristo é um só, Deus e homem; mas porque todo bem vem de Deus e não do homem, mesmo aquele que é distribuído por meio de um homem. Pois é o espírito que vivifica; a carne de nada aproveita (Jo 6,64). Por isso também é maldito quem põe a sua esperança no homem (Jr 17,5); porque, ainda que toda a nossa esperança dependa, e com razão, de um homem que é Deus, não é por ser homem, mas por ser Deus. Assim, aquele se oferece aos pés e este à cabeça: porque a humilhação de um coração contrito convém à humildade da carne, e à majestade convém a glorificação. Vede que perfume vos propus: aquela cabeça, temível aos principados, não julga indigno ser tocada por ele; antes o tem por sinal de honra, ao dizer: O sacrifício de louvor me honrará.`
    },
    {
      n: 9,
      texto: `Por isso não é de alma pobre e necessitada, nem de coração pequeno, preparar uma unção destas; porque os seus aromas e ingredientes só a confiança os possui — uma confiança, porém, que venha da liberdade do espírito e da pureza do coração. Pois a mente sem ânimo e de pouca fé fica apertada pela escassez do que é seu, e a pobreza não lhe permite ter folga para se entregar aos louvores divinos, nem para contemplar os benefícios, que é o que gera os louvores. E, se alguma vez tenta erguer-se, logo os cuidados urgentes das necessidades domésticas a chamam de volta para o que é seu, e a própria indigência a obriga a encolher-se em si mesma. E, se me perguntam a causa desta miséria, direi uma coisa que vós mesmos, se não me engano, reconhecereis existir, ou ter existido, em vós. Parece-me que esta doença da alma e esta desconfiança costumam vir de duas causas: ou de ser recente a conversão, ou então da tibieza da vida, mesmo quando já se tem muito tempo de convertido. Uma e outra abatem e humilham a consciência e a deixam inquieta, enquanto — seja pelo pouco tempo, seja pela pouca chama — ela sente que as antigas paixões ainda não morreram dentro de si. E, obrigada por isso a cuidar de arrancar do horto do coração os espinhos das iniquidades e as urtigas das cobiças, não lhe é permitido afastar-se muito de si mesma. Pois então? Quem se afadiga no seu gemido poderá ao mesmo tempo exultar nos louvores de Deus? Como soará na boca de quem geme e chora aquilo de Isaías: a ação de graças e a voz de louvor (Is 51,3)? Pois, como aprendemos do Sábio: Música em tempo de luto é conversa fora de hora (Eclo 22,6). E a ação de graças vem depois do benefício, não antes. Ora, a alma que ainda está na tristeza não goza do benefício: precisa dele. Tem, pois, com que oferecer preces, mas não com que dar graças. Como há de lembrar um benefício que não recebeu? Com razão, portanto, disse que não é de alma pobre preparar este perfume, que se há de compor da lembrança dos benefícios divinos; porque não pode ver a luz enquanto olha para as trevas. Está na amargura, e a triste lembrança dos pecados lhe ocupa a memória, e não lhe apetece acolher ao mesmo tempo nada de alegre. Por isso o espírito profético avisa a esses: É inútil levantar-vos antes da luz (Sl 126,2) — isto é: em vão vos levantais para contemplar os benefícios que deleitam, se antes não recebestes a luz da consolação a respeito das culpas que perturbam. Não é, portanto, dos pobres este perfume.`
    },
    {
      n: 10,
      texto: `Mas vede quem é que se gloria, e com razão, de o ter em abundância. Os apóstolos saíam alegres da presença do Sinédrio, porque foram julgados dignos de sofrer afronta pelo nome de Jesus (At 5,41). Muito haviam destilado sobre si da riqueza do espírito, esses cuja mansidão não cedeu — não digo a palavras — nem mesmo a açoites. É que eram ricos de caridade, que nenhuma despesa esgota, e dela podiam facilmente oferecer holocaustos de substância. Os peitos, transbordando, derramavam por toda parte o licor santo de que estavam cheios, quando falavam em várias línguas as maravilhas de Deus, conforme o Espírito Santo lhes dava exprimir-se (At 2,11.4). E não há dúvida de que abundavam nos mesmos perfumes aqueles a quem o Apóstolo dava este testemunho: Dou graças ao meu Deus sem cessar por vós, pela graça de Deus que vos foi dada em Cristo Jesus; porque em tudo fostes enriquecidos nele, em toda palavra e em toda ciência, de tal modo se confirmou entre vós o testemunho de Cristo, que nada vos falta em graça alguma (1Cor 1,4-7). Oxalá eu possa dar essas mesmas graças também por vós, e ver-vos ricos em virtudes, alegres nos louvores de Deus, transbordando com mais abundância desta riqueza espiritual, em Cristo Jesus, Senhor nosso.`
    }
  ]
});
