SERMOES.sermao({
  id: 'bernardo-cantico-50',
  colecao: 'bernardo-cantico',
  ordem: 50,
  numero: 'L',
  titulo: 'Da dupla caridade, a das obras e a do afeto, e da sua ordenação',
  fonte: 'De duplici charitate, scilicet actuali et affectuali',
  argumento: `Bernardo serve os "restos do banquete de ontem": ainda há o que dizer sobre a caridade ordenada. Distingue uma caridade das obras, que é mandada e dá mérito, e uma caridade do afeto, que é dada como prêmio e só se consuma no céu. Os mandamentos do amor apontam para as obras: amai os inimigos, fazei-lhes o bem; se me amais, guardai as minhas palavras. Não se trata de agir com o coração seco: há um afeto que vem da carne, doce mas torpe; outro que a razão governa, seco mas forte; e outro que a sabedoria tempera, rico e suave.

As duas caridades seguem ordens opostas. A das obras começa pelos últimos: atende primeiro os mais fracos, deixa a oração, o livro e até a missa quando o irmão precisa — "a necessidade não tem lei". A do afeto começa pelos primeiros, porque é sabedoria, e faz que cada coisa tenha o sabor do que é: Deus acima de tudo; a si mesmo e ao próximo enquanto amam a Deus; o inimigo como quem um dia talvez amará. O sermão termina numa oração à Sabedoria, para que ordene as ações segundo a necessidade e os afetos segundo a verdade.

Tradução feita do texto latino de Migne (PL 183, 1020-1025).`,
  pontos: [
    {
      n: 1,
      texto: `Talvez espereis que se trate do que se segue, julgando terminado o versículo de que se tratava por último. Mas eu preparo outra coisa: pois tenho ainda o que vos servir dos restos do banquete de ontem, que recolhera para que não se perdessem (cf. Jo 6,12). Mas perdem-se, se não os servir a ninguém; pois, se os quiser ter só para mim, sou eu que me perco. Não quero, pois, privar deles a vossa gula, que conheço bem; sobretudo porque são do prato da caridade, tanto mais doces quanto mais finos, tanto mais saborosos quanto mais miúdos. De outro modo, seria muito contra a caridade defraudar-vos da própria caridade. Aqui estou, pois: Ordenou em mim a caridade (Ct 2,4).`
    },
    {
      n: 2,
      texto: `Há uma caridade nas obras, e há uma caridade no afeto. E julgo que foi a respeito da que é das obras que se deu a lei aos homens e se formulou o mandamento; pois, no afeto, quem a tem como se manda? Aquela, pois, é mandada para o mérito; esta é dada como prêmio. Não negamos que também a vida presente possa, pela graça divina, experimentar o seu começo e o seu progresso; mas sustentamos claramente que a sua consumação pertence à felicidade futura. Como, pois, havia de ser mandada uma caridade que de modo nenhum se podia cumprir? Ou, se preferes que o mandamento tenha sido dado a respeito da caridade do afeto, não discuto, contanto que também tu concordes comigo que ninguém nesta vida pode nem pôde cumpri-lo. Pois quem ousaria arrogar-se aquilo que o próprio Paulo confessa não ter alcançado (Fl 3,13)? E não ignorava o legislador que o peso do preceito excede as forças dos homens; mas julgou útil que por isso mesmo fossem advertidos da sua insuficiência, e soubessem para que fim da justiça deviam esforçar-se segundo as suas forças. Mandando, pois, coisas impossíveis, não fez os homens prevaricadores, mas humildes, para que toda boca se feche e todo o mundo se reconheça sujeito a Deus; porque pelas obras da lei nenhuma carne será justificada diante dele (Rm 3,19-20). Pois, recebendo o mandamento e sentindo a falta, clamaremos ao céu, e Deus se compadecerá de nós; e saberemos naquele dia que não foi pelas obras de justiça que praticamos, mas segundo a sua misericórdia, que ele nos salvou (Tt 3,5).`
    },
    {
      n: 3,
      texto: `E digo isto no caso de concordarmos que a lei mandou a caridade do afeto. Mas que convém antes à das obras parece mostrar-se sobretudo por isto: depois de dizer o Senhor: Amai os vossos inimigos, acrescenta logo, a respeito das obras: Fazei o bem aos que vos odeiam (Lc 6,27). E também a Escritura: Se o teu inimigo tiver fome, dá-lhe de comer; se tiver sede, dá-lhe de beber (Rm 12,20). Também aqui tens obras, não afeto. Mas ouve também o Senhor, mandando a respeito do amor a ele mesmo: Se me amais, diz, guardai as minhas palavras (Jo 14,15). Também aqui somos remetidos às obras, pela observância dos mandamentos que nos é imposta. Seria supérfluo ter-nos advertido quanto às obras, se o amor já estivesse no afeto. Assim, pois, deves entender também aquilo que te é mandado: amar o teu próximo como a ti mesmo (Mt 22,39), ainda que não esteja expresso tão claramente. Enfim, não julgarias que basta para cumprir este mandamento do amor ao próximo observar perfeitamente aquilo que a lei da natureza prescreve com razão a todo homem: O que não queres que te façam, não o faças a outro (Tb 4,16)? E ainda aquilo: Tudo o que quereis que os homens vos façam, fazei-o também vós a eles (Mt 7,12).`
    },
    {
      n: 4,
      texto: `E não digo isto para que fiquemos sem afeto e, com o coração seco, movamos só as mãos para as obras. Li que, entre outros males grandes e graves dos homens que o Apóstolo enumera, está também este: ser sem afeto (Rm 1,31). Mas há um afeto que a carne gera; há outro que a razão governa; e há outro que a sabedoria tempera. O primeiro é aquele que o Apóstolo diz não estar sujeito à lei de Deus, nem poder estar (Rm 8,7); o segundo, aquele que ele mostra, pelo contrário, concordar com a lei de Deus, porque é boa (Rm 7,16); e não há dúvida de que distam entre si o que resiste e o que consente. Mas o terceiro dista muito de ambos: é o que prova e saboreia como o Senhor é suave (Sl 33,9), eliminando o primeiro e recompensando o segundo. Pois o primeiro é doce, mas torpe; o segundo, seco, mas forte; o último, rico e suave. Pelo segundo, pois, fazem-se as obras, e nele assenta a caridade — não aquela do afeto, que, temperada com o sal da sabedoria e enriquecida, traz à mente a grande abundância da doçura do Senhor (cf. Sl 30,20); mas uma caridade das obras, que, embora ainda não restaure suavemente com aquele amor doce, acende com veemência o amor do próprio amor. Não amemos, diz, com palavras nem com a língua, mas com obras e em verdade (1Jo 3,18).`
    },
    {
      n: 5,
      texto: `Vês com que cautela caminha entre o amor vicioso e o amor afetuoso, distinguindo de ambos esta caridade das obras, que traz a salvação? Neste amor não admite o fingimento da língua que mente, nem, por outro lado, exige o gosto da sabedoria que comove. Amemos, diz, com obras e em verdade; isto é, sejamos movidos a obrar bem mais por um impulso da verdade viva do que pelo afeto daquela caridade saborosa. Ordenou em mim a caridade. Qual delas, julgas tu? Ambas, mas em ordem oposta. Pois a caridade das obras põe à frente as coisas inferiores; a do afeto, as superiores. Numa mente bem afeiçoada, não há dúvida, por exemplo, de que o amor de Deus se antepõe ao amor do homem, e, entre os próprios homens, os mais perfeitos aos mais fracos, o céu à terra, a eternidade ao tempo, a alma à carne. No entanto, numa ação bem ordenada, acha-se muitas vezes, ou até sempre, a ordem oposta. Pois somos mais pressionados e mais vezes ocupados com o cuidado do próximo; assistimos com mais diligente solicitude aos irmãos mais fracos; aplicamo-nos, pelo direito da humanidade e pela própria necessidade, mais à paz da terra do que à glória do céu; a inquietação dos cuidados temporais mal nos deixa sentir alguma coisa das eternas; servimos quase continuamente às fraquezas do nosso corpo, pospondo o cuidado da alma; e, enfim, cercamos de mais honra os nossos membros mais fracos, segundo a sentença do Apóstolo (1Cor 12,23) — cumprindo assim, de certo modo, a palavra do Senhor: Os últimos serão os primeiros, e os primeiros serão os últimos (Mt 20,16). Enfim, quem duvida de que o homem que ora fala com Deus? E, no entanto, quantas vezes somos tirados e arrancados dali, por ordem da caridade, por causa dos que precisam do nosso trabalho ou da nossa palavra! Quantas vezes o piedoso repouso cede piedosamente ao tumulto dos afazeres! Quantas vezes se deixa o livro, com boa consciência, para suar no trabalho manual! Quantas vezes, para administrar coisas terrenas, deixamos com toda a justiça de celebrar as próprias solenidades das missas! Ordem invertida; mas a necessidade não tem lei. A caridade das obras segue, pois, a sua ordem, conforme a ordem do pai de família, começando pelos últimos (Mt 20,8). É, sem dúvida, piedosa e justa, pois não faz acepção de pessoas, nem considera o valor das coisas, mas as necessidades dos homens.`
    },
    {
      n: 6,
      texto: `Mas não assim a caridade do afeto: esta começa a ordem pelos primeiros. Pois é sabedoria, pela qual cada coisa tem o sabor que corresponde ao que é: de modo que, por exemplo, o que por natureza vale mais, também o afeto o sente como de mais valor; o que é menor, como menos; o que é mínimo, como mínimo. E aquela ordem da caridade, fá-la a verdade; esta ordem da verdade, reivindica-a para si a caridade. Pois a caridade é verdadeira nisto: que os que mais precisam recebam primeiro; e, por sua vez, a verdade se mostra querida se guardamos no afeto a ordem que ela guarda na razão. Tu, pois, se amares o Senhor teu Deus de todo o coração, de toda a alma, com todas as tuas forças (Mt 22,37), e, ultrapassando com um afeto mais fervoroso aquele amor do amor com que se contenta a caridade das obras, recebido o espírito em plenitude, te inflamares todo, de perto, no próprio amor divino, para o qual aquele é degrau, então Deus terá para ti, sem dúvida, o seu sabor — não de modo inteiramente digno, como ele é (o que é impossível a toda criatura), mas certamente na medida em que tu és capaz de saborear. Depois, também tu terás para ti mesmo o sabor do que és, quando sentires que não tens absolutamente nada por que te amar, senão enquanto és de Deus, pois derramaste nele tudo aquilo com que amas. Terás para ti, digo, o sabor do que és quando, pela própria experiência do teu amor e do afeto que tiveres por ti mesmo, descobrires que nada és digno de ser amado, nem sequer por ti mesmo, senão por causa daquele sem o qual não és nada.`
    },
    {
      n: 7,
      texto: `E o próximo, que deves verdadeiramente amar como a ti mesmo, para que também ele tenha para ti o sabor do que é, não terá outro sabor senão o que tu tens para ti mesmo, pois é o mesmo que tu: é homem. Tu, pois, que não te amas senão porque amas a Deus, amas consequentemente como a ti mesmo todos os que igualmente o amam. Quanto ao homem inimigo, como não é nada, por não amar a Deus, não o podes amar como a ti mesmo, tu que amas a Deus; mas hás de amá-lo, para que ele ame. E não é a mesma coisa amar para que ame, e amar porque ama. Por isso, para que também ele tenha para ti o sabor do que é, terá o sabor, não do que é, pois não é nada, mas do que talvez venha a ser — o que é quase nada, pois está ainda em suspenso, na dúvida. Pois aquele de quem é certo que não voltará mais ao amor de Deus terá necessariamente para ti o sabor, já não de quase nada, mas de nada absolutamente, pois é nada para sempre. Excetuado este, que não só já não deve ser amado, mas deve até ser odiado, segundo aquilo: Não odiava eu, Senhor, os que te odeiam, e não me consumia contra os teus inimigos (Sl 138,21)? — quanto ao resto, a caridade, neste ponto verdadeiramente ambiciosa, não permite que se negue a nenhum homem, por mais inimigo que seja, um mínimo de afeto. Quem é sábio, e entenderá estas coisas (cf. Os 14,10)?`
    },
    {
      n: 8,
      texto: `Dá-me um homem que, antes de tudo, ame a Deus com todo o seu ser; a si mesmo e ao próximo, na medida em que o amam; ao inimigo, como a quem talvez um dia há de amar; aos pais segundo a carne, mais intimamente, por causa da natureza; aos seus mestres espirituais, mais largamente, por causa da graça; e que, deste modo, se volte com um amor ordenado para todas as outras coisas de Deus, desprezando a terra, olhando para o céu, usando deste mundo como se não usasse (cf. 1Cor 7,31), e distinguindo, por um sabor íntimo da mente, entre as coisas de que se deve usar e aquelas de que se deve gozar, de modo que cuide das coisas passageiras de passagem, só para o que é preciso e na medida em que é preciso, e abrace as eternas com um desejo eterno; dá-me, digo, um homem assim, e eu o declaro ousadamente sábio, porque cada coisa tem para ele verdadeiramente o sabor do que é, e a ele cabe gloriar-se com verdade e segurança e dizer: Ordenou em mim a caridade. Mas onde está ele, ou quando serão estas coisas? Digo-o chorando: até quando sentiremos o perfume sem provar, olhando de longe a pátria sem a alcançar, suspirando e saudando-a de longe? Ó Verdade, pátria dos exilados, fim do exílio! Vejo-te, mas não me deixam entrar, retido pela carne; e nem sou digno de ser admitido, sujo de pecados. Ó Sabedoria, que atinges de um extremo ao outro com força, ao criar e sustentar as coisas, e dispões tudo com suavidade (cf. Sb 8,1), ao tornar felizes e ordenar os afetos! Dirige as nossas ações conforme pede a nossa necessidade temporal, e dispõe os nossos afetos conforme exige a tua verdade eterna, para que cada um de nós possa gloriar-se em ti com segurança e dizer: Ordenou em mim a caridade. Pois tu és a força de Deus e a sabedoria de Deus (1Cor 1,24), Cristo, esposo da Igreja, Senhor nosso, Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
