SERMOES.sermao({
  id: 'bernardo-cantico-48',
  colecao: 'bernardo-cantico',
  ordem: 48,
  numero: 'XLVIII',
  titulo: 'Do louvor recíproco entre o esposo e a esposa, e de como pela sombra de Cristo se entendem a sua carne e a fé',
  fonte: 'De laude reciproca, quae fit inter sponsum et sponsam',
  argumento: `O esposo compara a amada ao lírio entre os espinhos: enquanto está na carne, a alma vive no meio das tentações e tribulações, e precisa de vigilância, porque a flor fura ao menor aperto. Mas o espinho pode ser salutar — "bem te picam, se te compungem" —, e o lírio tem a beleza evangélica de iluminar com a sua brancura até os espinhos que o ferem, como quem ama os inimigos.

A esposa responde comparando o amado à macieira entre as árvores do bosque. O elogio parece pequeno, e Bernardo o admite: é pequeno porque é louvor de um pequeno. Não se canta aqui a majestade, mas a humildade do Verbo feito homem, única árvore que dá fruto entre as árvores estéreis dos homens. A sombra dessa árvore é a sua carne e a fé: Maria foi coberta pela sombra da carne do Filho, nós pela sombra da fé. Vive-se agora à sombra, e depois na luz. E a esposa não diz, como o profeta, que "vive" à sombra, mas que "se sentou": repousa já no amor e prova o fruto da contemplação, ainda que por espelho.

Tradução feita do texto latino de Migne (PL 183, 1012-1016).`,
  pontos: [
    {
      n: 1,
      texto: `Como o lírio entre os espinhos, assim é a minha amiga entre as filhas (Ct 2,2). Não são boas filhas as que picam. Repara no péssimo produto daquela que foi amaldiçoada, a nossa terra. Quando a cultivares, diz, produzirá para ti espinhos e abrolhos (Gn 3,18). Enquanto, pois, a alma está na carne, vive sem dúvida entre espinhos; e é inevitável que sofra as inquietações das tentações e os aguilhões das tribulações. E, se ela é um lírio, segundo a palavra do esposo, veja quão vigilante e cuidadosa deve ser na guarda de si mesma, cercada por toda parte de espinhos que apontam de um lado e de outro os seus aguilhões. Pois a delicadeza da flor não suporta de modo nenhum nem a mais leve picada do espinho; mal é apertada um pouco, fica furada. Sentes com quanta razão e necessidade nos exorta o profeta a servir ao Senhor com temor (Sl 2,11), e também o Apóstolo, a operar a nossa própria salvação com temor e tremor (Fl 2,12)? Eles conheciam, sem dúvida, pela própria experiência, a verdade desta sentença, como amigos do esposo que eram, e não duvidavam de modo nenhum de que também se referia às suas almas o que se diz: Como o lírio entre os espinhos, assim é a minha amiga entre as filhas. Enfim, um deles diz: Voltei-me para a minha miséria, enquanto o espinho se me cravava (Sl 31,4). Bem cravado foi quem daí se converteu. Bem te picam, se te compungem. Muitos, quando sentem o castigo, corrigem a culpa; e quem é assim pode dizer: Voltei-me para a minha miséria, enquanto o espinho se me cravava. Espinho é a culpa, espinho é o castigo, espinho é o falso irmão, espinho é o mau vizinho.`
    },
    {
      n: 2,
      texto: `Como o lírio entre os espinhos, assim é a minha amiga entre as filhas. Ó lírio resplandecente de brancura! Ó flor tenra e delicada! Estão contigo incrédulos e subversivos (cf. Ez 2,6): vê com que cautela andas entre os espinhos. O mundo está cheio de espinhos: estão na terra, estão no ar, estão na tua carne. Viver no meio deles e não ser ferido é obra do poder divino, não da tua virtude. Mas tende confiança, diz, eu venci o mundo (Jo 16,33). Ainda que vejas, pois, apontados contra ti de todos os lados os aguilhões das tribulações, como os dos abrolhos, não se perturbe o teu coração nem tenha medo, sabendo que a tribulação produz a paciência, a paciência a prova, a prova a esperança; e a esperança não confunde (Rm 5,3-5). Considera os lírios do campo, como vicejam e brilham entre os espinhos. Se Deus guarda assim a erva que hoje existe e amanhã é lançada ao forno (Mt 6,28-30), quanto mais a sua amiga e esposa caríssima? Enfim, o Senhor guarda todos os que o amam (Sl 144,20). Como o lírio entre os espinhos, assim é a minha amiga entre as filhas. Não é pequeno título de virtude viver bom entre os perversos e conservar entre os malfeitores a brancura da inocência e a brandura dos costumes; e mais ainda, se te mostras pacífico com os que odeiam a paz (cf. Sl 119,7) e amigo dos próprios inimigos. Isto, sem dúvida, te dará direito especial, como coisa tua, à comparação do lírio, que não cessa de iluminar e embelezar com a sua brancura os próprios espinhos que o picam. Não te parece, pois, que o lírio cumpre de certo modo a perfeição do Evangelho, pela qual nos é mandado orar pelos que nos caluniam e perseguem, e fazer o bem aos que nos odeiam (Lc 6,27-28)? Faze, pois, tu também assim, e a tua alma será amiga do Senhor, e ele te louvará, dizendo de ti: Como o lírio entre os espinhos, assim é a minha amiga entre as filhas.`
    },
    {
      n: 3,
      texto: `Segue-se: Como a macieira entre as árvores do bosque, assim é o meu amado entre os filhos (Ct 2,3). A esposa devolve o elogio ao esposo que a louvou: ser louvada por ele é tornar-se louvável; e louvá-lo é compreendê-lo e admirá-lo como louvável. E, assim como o esposo figurou o louvor dela com uma flor excelente, assim ela, por sua vez, mostra com uma árvore excelente a glória singular e a superioridade dele. Inquieta-me, porém, quanto a esta árvore, que não pareça de tanta excelência como algumas outras, e por isso seja menos digna de servir à comparação, como se não bastasse para retribuir o louvor. Como a macieira entre as árvores do bosque, assim é o meu amado entre os filhos. Enfim, nem a esposa parece tê-la estimado muito, pois cuidou de exaltá-la só entre as árvores do bosque, que são estéreis e não dão frutos próprios para o sustento humano. Por que, pois, deixadas de lado árvores melhores e mais nobres, se trouxe esta árvore mediana para formar o elogio do esposo? Devia receber um louvor com medida aquele que não recebeu o Espírito com medida (cf. Jo 3,34)? Pois a comparação com aquela árvore faz que pareça ter um superior aquele que não tem igual. Que diremos a isto? Confesso: é pequeno o louvor, porque é louvor de um pequeno. Pois aqui não se proclama o Senhor grande e muito digno de louvor (Sl 144,3), mas o Senhor pequeno e muito digno de amor — o pequenino que nasceu para nós (Is 9,6).`
    },
    {
      n: 4,
      texto: `Aqui, pois, não se exalta a majestade, mas louva-se a humildade; e é justo e razoável que o que é fraco e louco em Deus seja preferido à força e à sabedoria dos homens. Pois são eles as árvores do bosque, sem fruto, porque, segundo o Profeta, todos se desviaram, todos juntos se tornaram inúteis; não há quem faça o bem, não há nem um sequer (Sl 13,3). Como a macieira entre as árvores do bosque, assim é o meu amado entre os filhos. Entre as árvores do bosque, o Senhor Jesus é a única árvore que dá fruto — segundo a humanidade, é claro: posto acima dos homens, mas feito pouco menor que os anjos (Sl 8,6). Pois de modo admirável, feito carne, sujeitou-se aos anjos, e, permanecendo Deus, conservou os anjos sujeitos a si. Enfim: Vereis, diz, os anjos subir e descer sobre o Filho do homem (Jo 1,51); porque, num só e mesmo homem, Cristo Jesus, amparam a fraqueza e pasmam diante da majestade. Como, pois, à esposa sabe mais doce aquilo em que ele se diminuiu, ela exalta de melhor vontade a graça, põe à frente a misericórdia, pasma diante da bondade. Por isso lhe agradou admirar o homem entre os homens, e não Deus entre os anjos, como a macieira que se destaca entre as árvores do bosque, e não entre as plantas dos jardins. E não julga que o louvor diminua quando, pela consideração da fraqueza, se exalta a bondade da piedade. Pois, na medida em que, sob um aspecto, modera o louvor, sob outro louva mais, insistindo menos na glória da dignidade para que sobressaia a graça da condescendência. Assim, pois, como o Apóstolo diz que o que é louco e fraco em Deus é mais sábio e mais forte que os homens (1Cor 1,25) — mas não que os anjos —, e como o Profeta proclama que ele é o mais belo dos filhos dos homens (Sl 44,3) — e não dos anjos —, assim também ela, falando sem dúvida no mesmo espírito, quis aqui, sob a figura da árvore frutífera e das árvores do bosque, exaltar o Homem-Deus acima de toda graça dos homens, e não acima da excelência dos anjos.`
    },
    {
      n: 5,
      texto: `Como a macieira entre as árvores do bosque, assim é o meu amado entre os filhos. E bem diz entre os filhos; porque, sendo o único do seu Pai, empenhou-se, sem inveja, em lhe adquirir muitos filhos, a quem não se envergonha de chamar irmãos (cf. Hb 2,11), para que ele seja o primogênito entre muitos irmãos (Rm 8,29). E com razão é posto acima de todos os adotados pela graça aquele que é filho por natureza. Com razão é como a macieira, pois, à maneira de árvore frutífera, tem a sombra do refrigério e dá um fruto ótimo. Não é verdadeiramente árvore frutífera aquela cujas flores são frutos de honra e de honestidade (Eclo 24,23)? Enfim, é árvore de vida para os que o abraçam (Pr 3,18). Não se compararão a ele todas as árvores do bosque, porque, ainda que haja árvores belas e grandes, que parecem prestar auxílio orando, servindo, ensinando, ajudando com o exemplo, só Cristo, Sabedoria de Deus, é árvore de vida; só ele é o pão vivo que desceu do céu e dá a vida ao mundo (Jo 6,41.33).`
    },
    {
      n: 6,
      texto: `Por isso diz: À sombra daquele que eu desejara me sentei, e o seu fruto é doce ao meu paladar (Ct 2,3). Com razão desejara a sombra daquele de quem havia de receber ao mesmo tempo o refrigério e o alimento. Pois as outras árvores do bosque, ainda que tenham sombra que consola, não têm o alimento da vida, não têm os frutos perenes da salvação. Pois um só é o autor da vida, um só o mediador entre Deus e os homens, o homem Cristo Jesus (1Tm 2,5), que diz à sua esposa: Eu sou a tua salvação (Sl 34,3). Não foi Moisés, diz, que vos deu este pão do céu, mas o meu Pai vos dá o verdadeiro pão do céu (Jo 6,32). Por isso desejara sobretudo a sombra de Cristo, porque só ele não só refresca do calor dos vícios, mas também enche do deleite das virtudes. À sombra daquele que eu desejara me sentei. A sua sombra é a sua carne; a sua sombra é a fé. A Maria cobriu com a sua sombra a carne do seu próprio Filho; a mim, a fé no Senhor. Embora também a mim, como não me cobriria com a sua sombra a carne, se a como no mistério? E também a santa Virgem experimentou a sombra da fé, ela a quem foi dito: Feliz és tu, que creste (Lc 1,45). À sombra daquele que eu desejara me sentei. E o profeta: O Cristo Senhor, diz, é um espírito diante da nossa face; à sua sombra viveremos entre as nações (Lm 4,20). À sombra entre as nações; na luz com os anjos. Estamos na sombra enquanto caminhamos pela fé e não pela visão (cf. 2Cor 5,7); e por isso o justo, que vive da fé, está na sombra. Mas quem vive do entendimento é bem-aventurado, porque já não está na sombra, mas na luz. Davi era justo e vivia da fé, quando dizia a Deus: Dá-me entendimento, para que aprenda os teus mandamentos, e viverei (Sl 118,73.144); sabendo que à fé sucederia o entendimento, e que ao entendimento se revelaria a luz da vida, e a vida da luz. Primeiro é preciso chegar à sombra, e assim passar àquilo de que ela é sombra; pois, se não crerdes, diz, não entendereis (Is 7,9).`
    },
    {
      n: 7,
      texto: `Vês que a fé é vida, e sombra da vida. Pois, ao contrário, a vida passada nas delícias, porque não vem da fé, é morte e sombra da morte. Pois a viúva, diz, que vive nas delícias, está morta, embora viva (1Tm 5,6). Enfim, a sabedoria da carne é morte (Rm 8,6). E é também sombra da morte — daquela que atormenta eternamente. Também nós estivemos sentados outrora nas trevas e na sombra da morte (cf. Lc 1,79), vivendo segundo a carne e não da fé; já mortos para a justiça, e por pouco não engolidos pela segunda morte. Pois, tanto quanto a sombra está perto do corpo de que é sombra, tanto, sem dúvida, aquela nossa vida esteve perto do inferno. Enfim: Se o Senhor não me tivesse ajudado, diz, por pouco a minha alma habitaria no inferno (Sl 93,17). Agora, porém, passamos da sombra da morte à sombra da vida; ou antes, fomos transferidos da morte para a vida (1Jo 3,14), vivendo à sombra de Cristo — se é que vivemos, e não estamos mortos. Pois não creio que, pelo simples fato de alguém estar à sua sombra, viva nela, porque nem todo aquele que tem fé vive da fé. Pois a fé sem obras é morta (cf. Tg 2,26), e não pode dar a vida que ela mesma não tem. Por isso o profeta, depois de dizer: O Cristo Senhor é um espírito diante da nossa face, não se contentou em continuar dizendo: À sua sombra estamos; mas: À sua sombra, diz, vivemos entre as nações. Vê, pois, também tu, de viver, a exemplo do profeta, à sua sombra, para que um dia reines também na sua luz. Pois não tem só sombra; tem também luz. Ele, pela carne, é sombra da fé; ele, pelo Espírito, é luz do entendimento. Pois é carne, e é espírito: carne para os que permanecem na carne; espírito diante da nossa face, isto é, no futuro — se, esquecendo o que fica para trás, nos lançarmos para o que está adiante (cf. Fl 3,13), para que, chegando lá, experimentemos a palavra que ele disse: A carne de nada serve; o espírito é que dá a vida (Jo 6,64). E não ignoro que alguém, ainda permanecendo na carne, disse: Ainda que tenhamos conhecido Cristo segundo a carne, agora já não o conhecemos assim (2Cor 5,16). Mas isso é com ele. Nós, porém, que ainda não merecemos ser arrebatados ao paraíso, ao terceiro céu, alimentemo-nos entretanto da carne de Cristo, veneremos os seus mistérios, sigamos os seus exemplos, guardemos a fé; e viveremos, sem dúvida, à sombra.`
    },
    {
      n: 8,
      texto: `À sombra daquele que eu desejara me sentei. Talvez ela se glorie de ter experimentado alguma coisa mais feliz, ao dizer que, à sombra, não vive, como o profeta, mas se sentou. Pois sentar-se é repousar. E repousar à sombra é mais do que viver nela, como viver é mais do que simplesmente estar nela. O profeta, pois, tomando para si o que é comum a muitos, diz: À sua sombra vivemos; a esposa, porém, que tem um privilégio, gloria-se até de se ter sentado sob ela sozinha. Pois não disse, como ele, no plural: Vivemos; nem disse: Sentamo-nos; mas, no singular: Sentei-me, para que reconheças o privilégio. Onde nós, pois, vivemos com trabalho, nós que, cientes dos nossos pecados, servimos com temor, ali ela, devota e amante, repousa suavemente. Enfim, o temor traz castigo; o amor, suavidade. Por isso diz: E o seu fruto é doce ao meu paladar, significando o gosto da contemplação, que alcançara, suavemente elevada pelo amor. Mas isto, à sombra, porque é como num espelho e em enigma (cf. 1Cor 13,12). Virá o tempo em que as sombras declinarão, crescendo a luz, ou antes, desaparecerão de todo, e entrará uma visão tão clara quanto perpétua; e haverá não só suavidade para o paladar, mas também saciedade para o ventre — sem fastio, porém. À sombra daquele que eu desejara me sentei, e o seu fruto é doce ao meu paladar. Também nós, onde a esposa descansa, descansemos igualmente, glorificando, pelo gosto que provamos, o pai de família que nos convidou para tal banquete, o esposo da Igreja, Jesus Cristo, Senhor nosso, que é Deus acima de todas as coisas, bendito pelos séculos. Amém.`
    }
  ]
});
